### ISSUE TITLE
sound loss when Calf Multiband Compressor LADSPA 'split'-dials reaches high values of their designed span

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5650] opened 2020-08-20 13:58 UTC
## Bug Summary 
sound loss when Calf Multiband Compressor LADSPA 'split' dials reaches high values of their designed span

#### Steps to reproduce
To reproduce:
1. Put any instrument in song editor.
2. Insert "Calf Multiband Gate LADSPA" -effect.
3. Automate any of Split 1/2, Split 2/3, or Split 3/4 dials
4. Playback: At dial above 18000 a very short high-pitched sound causes a serious clip, and the sound disappear. No Crash!
If *not in playback*, the bug is not present!
 
#### Expected behaviour
No loss of sound when any dial moves inside its designed span

#### Actual behaviour
Clip and loss of sound

#### Screenshot
No

#### Affected LMMS versions
1.2.2

Demo project: 
[CMCL-fail.zip](https://github.com/LMMS/lmms/files/5103527/CMCL-fail.zip)

**Comment by thmueller64** [comment] 2020-08-23 18:36
I tried the demo project with the 1.2.2 stable version and can confirm the problem. However, the problem does not seem to exist on the current master build. Could you try it out with a master build? 
And do you really mean the Calf Multiband Gate as described above? Because your example project uses the Calf Multiband Compressor.

**Comment by qnebra** [comment] 2020-08-23 18:45
Checked quickly. Looks like "master" wasn't affected by this bug.

**Comment by musikBear** [comment] 2020-08-24 15:05
> And do you really mean the Calf Multiband Gate

No i did not, but there we go once more with my ailing sight, i read it wrong -no fun -sad -depressed 😞

**Comment by musikBear** [comment] 2020-08-28 14:56
@qnebra Could you try with **Calf Multiband Gate LADSPA** on *that same Master*, because *'Gate'* is now *also* reported having same issue. 
So both *Calf Multiband Gate LADSPA* and *Calf Multiband Compressor LADSPA* are having that same bug on 1.2.2

**Comment by qnebra** [comment] 2020-08-28 19:03
> @qnebra Could you try with **Calf Multiband Gate LADSPA** on _that same Master_, because _'Gate'_ is now _also_ reported having same issue.
> So both _Calf Multiband Gate LADSPA_ and _Calf Multiband Compressor LADSPA_ are having that same bug on 1.2.2

Tried both. Or I have no idea what exactly this bug is in your case, or it has been fixed in master branch. But also, something is bit really wrong here. 

Because in one hand there is less glitches and "oscilloscope" didn't go nuts, but also in case of your particular project some notes are not played, especially those in quick succesion and D. I tried with different melodies and 3xOSC patches, and just simple C-major scale run, which was played entirely and without glitches. And sometimes lmms crashes when switching from Compressor to Gate and vice versa.

**Comment by musikBear** [comment] 2020-08-29 12:13
> just simple C-major scale run, which was played entirely and without glitches. And **sometimes** lmms crashes when switching from Compressor to Gate and vice versa.

Looks like this sticks deeper than 'just' the reported issue
If it even is periodical as in **sometimes**, then this bug is a hard one to squash 😢

**Comment by allejok96** [comment] 2022-10-08 08:18
Confirmed in 1.2.2. Tested with multiband gate and multiband compressor on master, cannot reproduce. Since we are three to confirm that master is unaffected, I'm closing this.

**Closed by allejok96** 2022-10-08 08:18 UTC
Labels: bug
