### ISSUE TITLE
A drum rack/multi-sampler 

### ISSUE THREAD

**Issue by kerbingamer376** [LMMS/lmms#2947] opened 2016-07-29 14:48 UTC
Hi,
would it be possible to add an instrument that works as a multi-sampler, allowing you to set multiple samples to be played when different keys are pressed? (Like drum racks in ableton)?

**Comment by tresf** [comment] 2016-07-29 19:17
Duplicate of https://github.com/LMMS/lmms/issues/1460.  Not possible yet through LMMS alone although you may have luck with a 3rd party drum sampler plugin.

**Closed by tresf** 2016-07-29 19:17 UTC
Labels: duplicate
