### ISSUE TITLE
Improve Equalizer plugin's RTA dB range

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#3811] opened 2017-09-18 09:33 UTC
The analyzer in the built-in Equalizer plugin is very nice - but it has a very limited loudness range. I often have to crank my sounds just to be able to see the peaks on the spectrum analyser.

As a quick fix I'd propose changing the lowest visible dB level to -60 dBFS (instead of current -16 or so).
The next step would be making the dB range adjustable by the user.

What do you think?

**Comment by PhysSong** [comment] 2017-09-18 09:59
Duplicate of #3624

**Closed** 2017-09-18 09:59 UTC
Labels: duplicate
