### ISSUE TITLE
custom instruments

### ISSUE THREAD

**Issue by gnudles** [LMMS/lmms#4955] opened 2019-04-21 22:27 UTC
I think there should also be a way to assign different frequencies for every note in the piano roll, and by this way creating custom instruments. I think it could be nice to play with these http://www.wendycarlos.com/resources/pitch.html
https://en.m.wikipedia.org/wiki/Double_harmonic_scale
by not forcing the regular 12 notes division...

**Comment by DouglasDGI** [comment] 2019-04-21 22:33
The Double Harmonic Scale is actually a scale in 12 TET (which LMMS uses).  Everything else you're talking about looks like a duplicate of #1387.

**Closed by DouglasDGI** 2019-04-21 22:33 UTC
