### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Enprogames** [LMMS/lmms#1819] opened 2015-03-04 00:45 UTC
Whenever I delete too many things in the song-editor at once it crashes. This has made me have to restart many projects and it's a very big problem for me. Please fix this soon.

**Comment by tresf** [comment] 2015-03-04 00:49
We can't fix it if we can't reproduce it.  Please offer the steps to reproduce.

Furthermore, being impatient and demanding for something free and community supported is rude.

If you can't offer steps to reproduce, we'll close as invalid.

**Comment by Sti2nd** [comment] 2015-03-04 09:13
So this has to be master branch

**Comment by musikBear** [comment] 2015-03-04 09:54
i believe i can add a little to this
If a user tries to delete note or automation blocks fast in S-E, it *can* crash the program, *especially* if these blocks *overlaps*, It is almost sure to crash lmms.
For taht reason the *worst* posible thing to do is to use **sh-del** to make a huge stack of blocks in the 0 bar pos and then cascade-delete in this pile of blocks.
If the new *remove-from-barPos-to-barPos* functionality works (have yet to see a win-exe with this feature?), then this issue is with no relevance

**Comment by Enprogames** [comment] 2015-03-05 02:01
Well then are you going to fix this? Or just fuck around.

**Comment by tresf** [comment] 2015-03-05 03:14
Closing due to lack of steps to reproduce.

**Closed by tresf** 2015-03-05 03:14 UTC

**Comment by Spekular** [comment] 2015-03-05 06:45
Sorry enpro, we should stop trying to figure out where the issue stems from
and just fix it. @tresf try removing crashLMMS() from the deletion code,
how silly of us to add that there :) Afterwards perhaps we can auto-update
everyone's LMMS with the fix, much better than the usual testing and
release system we use.

**Comment by tresf** [comment] 2015-03-05 16:01
@Spekular :laughing:
