### ISSUE TITLE
two main things are lagging...1/ no slice tool. 2/need more option in sample editing.

### ISSUE THREAD

**Issue by banti101** [LMMS/lmms#4476] opened 2018-07-10 03:00 UTC
two main things are lagging...1/ no slice tool. 2/need more option in sample editing. there is almost no option in sample editing section in sample track.

**Comment by PhysSong** [comment] 2018-07-10 05:57
They are already known issues and now part of #1471. Closing as a duplicate of #1471.
If you need something not reported/suggested, please feel free to open a new one. Don't forget to search for existing issues!

**Closed by PhysSong** 2018-07-10 05:57 UTC
