### ISSUE TITLE
Better MIDI exporting

### ISSUE THREAD

**Issue by peefTube** [LMMS/lmms#6290] opened 2022-01-23 06:40 UTC
Is there any plan to fix up how MIDI files are exported so that individual tracks can be set to a MIDI bank (according to the native soundfont, if there is one, otherwise following the standard of the Microsoft soundfont) or something of the sort? Would be nice to have a feature like this to bypass the need for a secondary software dedicated to MIDI, such as Melody Assistant

I presume the code used to store SF2 tracks in .mmpz files would come in handy, the hard part would probably be tweaking this to work with MIDI. I might hop in and do it myself or fork LMMS and do that, but I don't necessarily have the time on my hands to become a core dev

**Comment by Spekular** [comment] 2022-01-23 07:07
https://github.com/LMMS/lmms/search?q=midi+export&type=issues

Duplicate of #4185, #5287, #5198

See also: #5516

**Closed by Spekular** 2022-01-23 07:07 UTC
