### ISSUE TITLE
keyboed Enhancments 

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1917] opened 2015-04-02 22:18 UTC
Move the pitch bend knob and it's rage box and the Mod Wheel knob and it's rage box as part all of the Instrument plugins.
mockup # 1 
![lmms keyboard](https://cloud.githubusercontent.com/assets/8137561/6974940/c0a058b6-d95c-11e4-8600-e0afd6a041a5.png)
mockup # 2 
![e1e658d8-d946-11e4-81e7-e47ff06ceb16](https://cloud.githubusercontent.com/assets/8137561/6976456/cea30bf8-d96f-11e4-8b8b-1373b0d775ed.jpg)

 Mod Wheel #1890

**Comment by Wallacoloo** [comment] 2015-04-02 22:53
Can you clarify your issue? Is this a screenshot of what the keyboard section of an instrument looks like on your system, and the problem is that the two RANGE boxes aren't vertically aligned? Or is this a mockup of where you'd like the PITCH and MOD knobs to be positioned?

The keyboard section of instrument plugins currently looks like this for me (different than the image you have above):

![llms-3xosc](https://cloud.githubusercontent.com/assets/1210751/6975365/f539ffcc-d98a-11e4-8ac1-92f2608605dc.png)

**Comment by Reaper10** [comment] 2015-04-02 23:12
mockup

**Comment by Wallacoloo** [comment] 2015-04-03 00:01
I see how this could be more desirable in that it mimics most electronic keyboardd with pitch/mid wheels, but looking at the size of the above tripleosc instrument (and most of the native instruments have similar size), there really isn't enough room to put the 2 knobs there - the keyboard would just be too squished.

Maybe there's another solution that could place the knobs closer to the virtual keyboard but avoid squishing it. 

But I'm not even sure if you could get a consensus that placing the pitch knob near the keyboard is any better than placing it with the vol/pan knobs. Even having used electronic keyboards a lot, both locations make the same amount of sense to me, and I would expect that users who haven't used keyboards with pitch knobs might find the current location more intuitive.

**Comment by Reaper10** [comment] 2015-04-03 00:38
![e1e658d8-d946-11e4-81e7-e47ff06ceb16](https://cloud.githubusercontent.com/assets/8137561/6976456/cea30bf8-d96f-11e4-8b8b-1373b0d775ed.jpg)

**Comment by tresf** [comment] 2015-04-03 03:03
What is mod?

**Comment by unfa** [comment] 2015-04-03 10:57
__...baybe don't push me, don't push me, no more!__

_Sorry._

Actually I just got a controller (m-audio Oxygen 49 IV) and wanted to talk about master keyboard integration...

**Comment by Reaper10** [comment] 2015-04-03 15:25
#1890

**Comment by Reaper10** [comment] 2015-04-03 17:50
Vibed need a pitch knob and range box.

**Comment by tresf** [comment] 2015-04-03 19:04
So are you recommending to add a knob (one which only exists in your mind) to all plugins?

**Comment by tresf** [comment] 2015-04-03 19:07
> Vibed need a pitch knob and range box.

Duplicate of #1121, not all instruments support it yet.

**Closed** 2015-04-03 21:33 UTC
