### ISSUE TITLE
LMMS closes when you touch the audio file processor

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4651] opened 2018-10-08 03:30 UTC
When I open a sample with the audiofile processor, and start to configure the waveform of the audio processor, lmms 1.2.0 rc7 closes automatically, I currently use av linux 2018. but you can do the test, you just have to configure or make several clicks in the wave and automatically lmms will close without warning.

Here an image
![error de audio processor](https://user-images.githubusercontent.com/26127693/46591454-e1f39480-ca88-11e8-9bc4-575a0bdc1ad6.png)

Regards.

**Comment by PhysSong** [comment] 2018-10-08 07:35
The symptom looks similar to https://github.com/LMMS/lmms/issues/3926#issuecomment-340444254. The linked bug is related to the mouse cursor.

**Comment by Gabrielxd195** [comment] 2018-10-08 08:36
> El síntoma se ve similar a [# 3926 (comentario)](https://github.com/LMMS/lmms/issues/3926#issuecomment-340444254) . El error vinculado está relacionado con el cursor del ratón.

It is the same error that appears to me.

**Comment by SecondFlight** [comment] 2018-10-08 13:22
I was going to close in favor of #3926, but after looking at it I think it might be better to consolidate #3926 into this one by adding the steps to reproduce. I'll let someone else make that call.

**Comment by musikBear** [comment] 2018-10-08 14:40
What OS has this bug?
Win32 can edit AFP waveforms fine:
![afpwaveformedited](https://user-images.githubusercontent.com/6662066/46615482-91c41300-cb18-11e8-8761-ebc09172773c.JPG)
Or is it *one* specific waveform ?
What is the name of the crash AFP-preset
I used factory *Erazor*

**Comment by musikBear** [comment] 2018-10-09 11:13
So this is a linux issue?
Can other Linux users confirm?

**Comment by CYBERDEViLNL** [comment] 2018-10-09 20:44
I'm on Arch with LMMS RC7 and I don't experience this with AFP as the issuer describes. What I did experience was in one of my somewhat bigger  projects I added a new AFP (many there before) and as soon I opened the AFP window LMMS froze and then seg faulted. I found that when I moved the new AFP a few tracks up before opening it it is fine. It had to be above a automation track which automated a `Higher Quality Pitch Scaler`’s knob, not sure how any is related. I haven't been able to reproduce in any other project.

**Comment by Gabrielxd195** [comment] 2018-10-11 06:42
> I'm on Arch with LMMS RC7 and I don't experience this with AFP as the issuer describes. What I did experience was in one of my somewhat bigger projects I added a new AFP (many there before) and as soon I opened the AFP window LMMS froze and then seg faulted. I found that when I moved the new AFP a few tracks up before opening it it is fine. It had to be above a automation track which automated a `Higher Quality Pitch Scaler`’s knob, not sure how any is related. I haven't been able to reproduce in any other project.

In your case it was worse, that problem must be reviewed.

**Comment by PhysSong** [comment] 2019-04-14 09:13
Closing since #3926 is fixed.

**Closed by PhysSong** 2019-04-14 09:13 UTC
