### ISSUE TITLE
Ability to save the project in an archive format containing the samples (zip, 7z...)

### ISSUE THREAD

**Issue by rawthought** [LMMS/lmms#441] opened 2014-03-12 16:39 UTC
It would be great if we could store all the project files (the samples) in an unique archive file (7z, zip, tar, ...).

I principaly use my own samples to create music, and sometimes I move or modify my samples, so, as a result, the songs are broken.

I'm not a programmer, I hope that's not too much work to do.

By the way, thanks to all who have worked on lmms... it become a great software ! :)
(sorry for my bad skill in english, I hope I am understandable...)

**Comment by Umcaruje** [comment] 2015-07-03 21:50
Closing as a duplicate of #1257

**Closed by Umcaruje** 2015-07-03 21:50 UTC
Labels: duplicate, enhancement
