### ISSUE TITLE
LMMS Plugins

### ISSUE THREAD

**Issue by DanielRios549** [LMMS/lmms#4114] opened 2018-01-15 22:54 UTC
Why isn't there plugins for LMMS for Linux? This is simply ridiculous, the program has a Linux version but the plugins does not, all plugins only have versions for Windows and Mac... What can I do to use these plugins?

**Comment by Umcaruje** [comment] 2018-01-15 22:57
Are you talking about Linux VST support? If so, this a duplicate of #416

**Comment by tresf** [comment] 2018-01-15 23:00
Calling a project rediculous is not acceptable demeanor for our bug tracker.

**Closed by tresf** 2018-01-15 23:00 UTC
