### ISSUE TITLE
Multiple patterns in a BB track

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#2398] opened 2015-10-03 21:17 UTC
With the beat+bassline system we currently have, songs with less repetitive beats require one BB track per beat pattern, which is not an adequate solution.

To address this problem, we could add a feature to enable a BB track to hold multiple patterns (unable to play simultaneously, of course). In the song editor, each of these patterns would be identified by a number.

Keeping backward compatibility will be very easy, as BB tracks from old projects can be treated simply as BB tracks with only one pattern.

**Comment by tresf** [comment] 2015-10-03 21:33
Duplicate of https://github.com/LMMS/lmms/issues/454

**Closed** 2015-10-08 19:25 UTC
Labels: duplicate
