### ISSUE TITLE
implement sh+Ins & sh+Del also in piano-roll

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2281] opened 2015-08-19 13:37 UTC
sometimes i find myself with a piece of notes, and in then realize that in bar 5-8, the notes are not 'bad', but a 'part' is missing. So now all note past bar 5 has to be marked up and then manually moved, and i better not miss some, because that would be b a d ..
if the known and really useful behavior in song-editor, was adapted in piano-roll, this manual moving, could be replaced with easy sh+ins 'pushing' of everything to the right of playhead.
This would enhance the usage.
**The obvious alternative is methods to select everything between the loop-markers**
That will offer even more options!
What is simplest to implement?

**Comment by Umcaruje** [comment] 2015-08-19 13:44
Please don't post duplicates of your own issues. 

Duplicate of #1643

**Closed by Umcaruje** 2015-08-19 13:44 UTC
Labels: duplicate

**Comment by musikBear** [comment] 2015-08-20 10:49
:blush: Ooooops sooory :blush:
I should have remembered that, but diddent 
:blush:
