### ISSUE TITLE
VST Preview Crash

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#300] opened 2014-02-12 14:22 UTC
0.9.90 p.r.  v32bit
Platform winXP
Old bug
The 'pre-hear' feature is very nice for all factory-presets, but VSTs will launch a vsts-GUI without a lmms-handle. It can be closed through the window-context-menu, but it still exists in memory (eg leak). (with one especially large VST (Alionoctis), lmms crashed, but that can definately be my memory, and not related to lmms)

**Comment by curlymorphic** [comment] 2015-01-06 12:59
Im confused as to whats needed?

are we trying to stop previewing vst instruments, or any instrument with a vst effect on?

**Comment by tresf** [comment] 2015-01-06 13:13
> are we trying to stop previewing vst instruments

Yes.

> or any instrument with a vst effect on?

Not sure about effects.  Probably good to disable them too but for now, disabling the VST instrument  presets would be a big win (or we focus on fixing the underlying crash).

-Tres

**Comment by curlymorphic** [comment] 2015-01-06 13:18
> or we focus on fixing the underlying crash

I cant reproduce a crash, but i do end up with orphaned vst effects.

Can someone test to see if this crash is still reproducible with master please?

**Comment by tresf** [comment] 2015-01-06 13:22
> I cant reproduce a crash, but i do end up with orphaned vst effects.

If you are on Linux, Wine may be handling this better.  In this case, we may have to make a Windows installer to reproduce the actual crash.

**Comment by curlymorphic** [comment] 2015-01-08 08:23
Some progress 

@tresf  your if statement was nearly there

	if(dataFile.content().elementsByTagName( "vestige" ).length() == 0 )

is what we needed. But this leads onto another issue, what to do when i know its a vestige?

if i simply dont loadTrackSpecficSettings , then a preview of the last selected previewed track will play.
If there was no last preview then lmms segfaults.

I think the cleanest solution maybe to have a dummy preset, (any native synth with vol = 0 ) loaded instead. This dummy preset can simply be an xml string hard coded into the source, to save users ever finding the file.

Is this the way to proceed?

**Comment by tresf** [comment] 2015-01-08 13:29
> Is this the way to proceed?

Hmm... We have the concept of dummy instruments.  A dummy preview/preset may be a good option.

**Comment by tresf** [comment] 2015-01-09 22:49
Closed via #1587

**Closed by tresf** 2015-01-09 22:49 UTC
Labels: bug
