### ISSUE TITLE
crash when/after closing LMMS

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2088] opened 2015-06-10 15:08 UTC
1.1.3 win 32 on xp
wonder if others experience this.
ever now and then (randomly.. alas) windows throw an **'An error occurred LMMS had to close' ** popup 
We all know which one..
But here is the odd thing:
This happens 'several' (5~10) seconds *after* i *have saved* my project, and deliberately and normally (eg X in right cornor)  *have closed* the program.
Nothing is missing in the file
The file reopens completely normally.
Have *anyone* also seen this weird thing?
(Not at all sure its a lmms issue, unless others can confirm?)

**Comment by Wallacoloo** [comment] 2015-06-10 15:23
If you're using ZynAddSubFX, it's likely due to the conflicting "Engine"
class names. I'm in email, so can't look up the relevant
issues/pull-requests, but there are a lot of recent relevant ones on the
issue tracker and the PR about moving lmms into a namespace aims to solve
that issue.

**Comment by tresf** [comment] 2015-06-10 15:31
> If you're using ZynAddSubFX, it's likely due to the conflicting "Engine"
class names.

Isn't that issue relatively new to master?  I've never encountered that on 1.1.3.

@musikBear there could be many causes, one of them could be sound driver related.  On Apple for example, this happens when going to sleep.

The issue with any Windows issue is the lack of debugging tools, so if you can reproduce the issue on Linux, that would be ideal.  Also, Wine tends to be a bit more verbose than Windows, if you prefer to debug the Windows binary, bu that would still require Linux.

-Tres

**Comment by musikBear** [comment] 2015-06-10 15:45
> so if you can reproduce the issue on Linux, that would be ideal. 

darn, cant - still dont have an installation
But until this oddness has been confirmed by other win-users **ON !:!:3** Then this could simply be my pc only, so **unless** someone confirm, this is either 'irrelevant' or 'not our bug'

**Comment by mikobuntu** [comment] 2015-06-10 16:51
You could always run a live USB with a linux distro such as Ubuntu, which loads into RAM at runtime and install LMMS ( which will only be temporary unless you allow persistance i.e n/GB on the USB )Google  " ubuntu unetbootin live usb with persistance "


thanks Mikobuntu ;)


Date: Wed, 10 Jun 2015 08:45:54 -0700

**Comment by Wallacoloo** [comment] 2015-06-10 17:30
Right, I missed the part about 1.1.3 - not the zyn issue then.

I wonder if we should install a segfault handler to log a stack trace
whenever lmms crashes. That would make Windows debugging a little easier.

**Comment by tresf** [comment] 2015-06-10 18:04
> I wonder if we should install a segfault handler to log a stack trace
whenever lmms crashes. That would make Windows debugging a little easier.

Just getting the console output on Windows would be a good start, then perhaps we offer debug builds along side our stable.  I thought we had a bug for this, but I lost it.

**Comment by musikBear** [comment] 2015-06-28 13:06
just want to add, that this is not totally harmless. If the project has any VST, then this 'after closing crash' will creates 'orphans' and memory-leak

**Comment by musikBear** [comment] 2015-07-01 15:47
Happed the first time i used MASTER of 1. jul test binaries (lmms-1.1.3-010715-win32.exe)
Kindly supplied by @Umcaruje 
Unfortunately this shows that the problem persist in Master
(several other issue exists, but i will make a list, referencing the relevant '#'numbers )

**Comment by musikBear** [comment] 2015-07-13 10:34
Want to add a link to a guy from forum, that has a crash every time he closes lmms. He has a keyboard connected, so the issue is not exactly the same, but there may be relations (?)
I add the link, in order to collect the complere picture of 'crash-after-close'
http://lmms.io/forum/viewtopic.php?f=7&t=3463&p=11016#p11016

**Comment by Spekular** [comment] 2015-09-07 17:48
Can we rename this to something more descriptive like "crash when/after closing LMMS"?

**Comment by tresf** [comment] 2016-02-18 13:56
Closing, since we won't be fixing for `stable-1.1`.  Marking as duplicate of #2584 which happens much more frequently and will be easier to reproduce and track.  We can continue to track it there.

**Closed by tresf** 2016-02-18 13:56 UTC
Labels: bug, duplicate
