### ISSUE TITLE
Freeboy Plugin crashes LMMS

### ISSUE THREAD

**Issue by CaitlinChoban** [LMMS/lmms#3495] opened 2017-04-08 17:59 UTC
I made a few melodies with the plugin freeboy. However, i haven't been able to listen to it all the way though because LMMS crashes whenever it gets to a certain time length.

**Comment by tresf** [comment] 2017-04-08 18:17
@CaitlinChoban can you please upload sample project file on our [lsp](https://lmms.io/lsp/) which reproduces this problem?  Also, if you can post here a link to the file after uploaded as well as provide your OS, the LMMS version and how you obtained LMMS, that will help.

**Comment by CaitlinChoban** [comment] 2017-05-17 18:37
Here is a link to the file on LSP. 
https://lmms.io/lsp/?action=show&file=10923

I am running Windows 8 64bit. LMMS 1.1.3 that i obtained from the LMMS website.

**Comment by zonkmachine** [comment] 2017-05-17 20:36
It doesn't look like Freeboy itself is the problem here but the Piano Roll pattern at bar 15 that is faulty. There are multiple notes hidden under the top ones. There are hundreds of them so it looks like a copy/paste maneuvre gone wrong.
To fix this you need to redo the patterns that crash the song

**Comment by zonkmachine** [comment] 2017-05-20 17:38
As this looks solved I'm closing this now. Please check out the forum and specifically the [support](https://lmms.io/forum/viewforum.php?f=7) section which has more traffic than the github site.

**Closed by zonkmachine** 2017-05-20 17:38 UTC
Labels: support request
