### ISSUE TITLE
projects/templates/default.mpt listed in the "recently open projects"

### ISSUE THREAD

**Issue by notorand-it** [LMMS/lmms#1892] opened 2015-03-22 09:46 UTC
I have defined a custom default template to be used at startup.
I did so by creating a template named projects/templates/default.mpt.
At every LMMS startup I get this template used as the default one.
But it also gets listed in the "recently open projects" as the most recent one.
I would say it is wrong as that'd be a template, not a project.

**Comment by tresf** [comment] 2015-03-22 16:13
Duplicate of #1812 I believe.

**Comment by notorand-it** [comment] 2015-03-22 16:17
Yup! I failed to see it!

**Comment by tresf** [comment] 2015-03-22 16:19
:+1:

**Closed by tresf** 2015-03-22 16:19 UTC
Labels: duplicate
