### ISSUE TITLE
ZynAddSubFX microtunings broken

### ISSUE THREAD

**Issue by GeekyGami** [LMMS/lmms#6273] opened 2022-01-14 03:36 UTC
### Bug Summary
ZynAddSubFX microtunings break upon ZynAddSubFX's interface being opened or closed, reverting back to 12TET.
Since exporting makes LMMS close Zyn's interface, this means that upon export everything is reverted to 12TET as well.

#### Steps to reproduce
Open Zyn. Under the scale button that is under the panic button in advanced mode, set up a scale.
Say,
12/6
4/5
8/3
9/2

Fractions will cause the issue, decimals will not.

Doesn't matter too much what scale it is.
Click retune.
Now, in pianoroll, with Zyn's interface still open, set up an order of notes you know you would be able to pinpoint belong to this temperament.
Play it on loop.
Close Zyn's interface.

#### Expected behavior
It should keep the microtuning.
#### Actual behavior
It reverts to 12TET.

#### Affected LMMS versions
1.3.0-alpha-1.102, both on Windows and Linux.
Apparently VST versions of Zyn are unaffected.

#### Comments
As it stands, using the VST version would mean being unable to load patches saved as .XPF from LMMS' own Zyn implementation, and patches as .XYZ, on the same version, cannot be saved from Zyn. It crashes.
I'm filing that under another issue.

**Comment by PhysSong** [comment] 2022-01-14 03:48
This looks like a duplicate of #5092. Can you confirm you get the behavior identical to #5092?

**Comment by GeekyGami** [comment] 2022-01-14 04:08
My bad, it's indeed a duplicate.

**Closed** 2022-01-14 04:57 UTC
Labels: bug
