### ISSUE TITLE
Notes played on a midi keyboard won't record on Linux.

### ISSUE THREAD

**Issue by Gps2010** [LMMS/lmms#1732] opened 2015-01-31 15:11 UTC
Ref: http://lmms.io/forum/viewtopic.php?f=7&t=1627&p=7158#p7158

What I tried:

I used alsa and pulse audio, but that does not changed a thing.
I also tried window7, and it does record there. ( so its not the midi keybaord I use)
In the topic, I list, there is a user with win 8 and lmms 1.0 stable.
Recording works for him.
I have recorded on linux with an older version of lmms.

So it seems there is something about 1.1.0 and linux.

The O.S. I use is openSUSE 13.1 64 bit. But in the topic other distro's have the same problem.

**Comment by pbella** [comment] 2015-02-01 01:41
I'm running LMMS 1.1 on Linux with a USB MIDI keyboard and haven't had this issue so it's not a global issue re: Linux and keyboards.  Unless someone else chimes in with knowledge about what the problem might be, we'll probably need more information to get to the bottom of this.  What repository did you install LMMS from?  And just to confirm: you are both seeing the visual indicator of the notes being played in the track you are trying to record to as well as hearing the note being played by LMMS, correct?

**Comment by Gps2010** [comment] 2015-02-01 03:28
I compiled lmms myself.
I do see the visual indicator, I think, and I do hear the notes.
By visual indicator you mean the keyboard keys in the piano roll moving? 

I compiled lmms myself, because the one I got from packman had issues.

I saw today in yast, an lmms version from 16 januari. That should be a newer version, then the one I had issues with. I could try to install that one.

If its not general Linux, there must be something else wrong,interesting.

I tried to install the one from packman, I think it worked, it seems, I now have lmms installed twice.
Stil lthe same issue.

I am thinking though, how to get rit of all of lmms, and start all over.
I already moved my projects to a different folder, so they are safe.

Is it enough to delete the lmms folder from my home folder ?

**Comment by pbella** [comment] 2015-02-01 05:38
Building from source can be problematic.  When I hit a key on my MIDI keyboard I see visual confirmation 3 ways: 1) the keys in the piano roll 2) the green indicator on the track 3) the vu meter in the mixer.

Generally expect to have to work through some issues when building a package like LMMS from source... there are many ways things can go wrong from a prerequisite / version standpoint.  As far as how to remove it, the lmms folder in your home directory only contains your projects.  I'm not sure of the preferred uninstall method (I don't see an uninstall target) so you might want to install and then uninstall the packaged version assuming you didn't use an install prefix.

I'd suggest seeing if you can get feedback to the right people (distro bug reporting or package maintainer) to see if they can get a working package built.  Then you'd have a good baseline version to compare to if you still need to build from source.

**Comment by softrabbit** [comment] 2015-02-01 07:03
Duplicate of #1464?

**Comment by Gps2010** [comment] 2015-02-01 14:17
@ softrabbit I have read #1464  I don't have a clue, if I compiled the master branch ?
How can I tell ?

Through this page: https://lmms.io/download/#linux-suse, I went to the wiki, assuming it would give me 1.1.0 ? 

@ pbella. I don't see the green bars, nor the vu meter move, I do hear the sound. 
I have already send two emails to packman about lmms. That's probably why the latest build version is of 16 jan. ( Build Time: Fri 16 Jan 2015 02:08:18 PM CET )
I did find prob something interesting in the package manager though.
The lmms devel file I have installed is an old version, not belonging to 1.1

To uninstall lmms ( or any program) you compiled you're self, it seems you have do something like make uninstall.

I am willing to test what: $ sudo zypper install lmms will do. but it worries me.
With opensuse comes a lot of stuff, but some not very recent.
To update after an install, you have to do in YAST (package manager) a vender change.
You change the lmms (multimedia)  repository from openSUSE to packman.

I doubt zypper will change the repository, with the listed command ?

For now I will uninstall the self compiled one, and then get the latest version from packman.
Version 1.1.0-47.6 ( the 47- 6 part is just for openSUSE.)
Through a topic I opened on the lmms forum, I found I had version 1.1.0-47-3 before.

If I get this right though, were can I find the source for 1.1.0 if I want ( need) to compile it myself ?

**Comment by Sti2nd** [comment] 2015-02-01 14:28
https://github.com/processing/processing/wiki/Build-Instructions
https://github.com/LMMS/lmms.git

**Comment by Sti2nd** [comment] 2015-02-01 14:29
https://github.com/LMMS/lmms/wiki/Compiling-lmms

**Comment by Gps2010** [comment] 2015-02-01 14:44
Thank you, those are how ever the links I used to compile.
On the command line, git clone https://github.com/processing/processing.git
Should give me 1.1.0 stable and not the master branch as stated in  #1464 ?

**Comment by Sti2nd** [comment] 2015-02-01 14:53
I gave you completely wrong links, updated my comment. https://github.com/LMMS/lmms/wiki/Compiling-lmms
Oh yeah... it will give you master branch... Maybe
```$ git checkout stable-1.1```

**Comment by tresf** [comment] 2015-02-01 15:48
The compilation instructions have nothing to do with the branch.... 

https://github.com/LMMS/lmms/wiki/Accessing-git-repository

These git instructions will clone master.  To get `stable-1.1`, one would normally do a `-b stable-1.1` after the clone command.  Switching branches (mentioned previously) would also do the trick.

**Comment by Gps2010** [comment] 2015-02-01 16:40
I have used google, but can find, how to switch branches ?

I am thinking of deleting the lmms folder ( with the build folder and everything in it) and just start over by:
git clone https://github.com/LMMS/lmms.git -b stable-1.1 ?

**Comment by Gps2010** [comment] 2015-02-01 18:35
Bring in the dancing girls.

I renamed the old lmms folder I used to build LMMS.

Then used  git clone https://github.com/LMMS/lmms.git -b stable-1.1

Then I did cmake and of course I had about everything already.

I did install portaudio, although I am not sure I will use it.
There is no Carla for openSUSE, so I skipped that one.
(every thing I already had)

Then hooked up the midi keyboard and started lmms.

My problem is solved. I can't speak for the others in the topic on the lmms forum, but if they don't respond here.......

I think the compile wiki should have something about stable versus masterbranch.
This one: https://github.com/LMMS/lmms/wiki/Accessing-git-repository
It could have saved me a lot of work.

But I am happy, and would like to thank you guys, for the help.

**Comment by tresf** [comment] 2015-02-02 15:20
> Duplicate of #1464?

Duplicate of #1464. :+1:

**Closed by tresf** 2015-02-02 15:20 UTC

**Comment by Gps2010** [comment] 2015-02-12 21:40
Because I had to reinstall openSUSE, I also had to recompile lmms.
Although I seemed to have managed that again, with a lot of searching, because I found out I was missing:
glibc-devel-32bit
gcc-32bit - The system GNU C Compiler
gcc48-32bit - The GNU C Compiler 32bit support

When I started lmms, I found out it was version 1.1.2 :( 

I then tried to start over, but: 
guus@linux-ab3o:~/lmms2> git clone https://github.com/LMMS/lmms.git -b stable-1.1.1
Cloning into 'lmms'...
fatal: Remote branch stable-1.1.1 not found in upstream origin
Unexpected end of command stream
guus@linux-ab3o:~/lmms2> git clone https://github.com/LMMS/lmms.git -b stable-1.1.0
Cloning into 'lmms'...
fatal: Remote branch stable-1.1.0 not found in upstream origin
Unexpected end of command stream

Am I doing something wrong or ? 
If I knew I was getting 1.1.2 , I would not even have bothered, because from the forums I know there is a problem with 1.1.2.

**Comment by mikobuntu** [comment] 2015-02-12 22:32
I would try with just cloning  the source and  ommit the " -b stable-1.1.1 " then you can use tab completion to see available branches and just pull the required one, this is normally how I do it if I want to try a new testing branch or something, If you need more explaining please reply again ;)
so basically in the LMMS working tree you would do " git pull -b origin " , then use the tab key for auto completion, which will list all branches, then just select.... 

thanks Mikobuntu ;)


Date: Thu, 12 Feb 2015 13:40:34 -0800

**Comment by mikobuntu** [comment] 2015-02-12 22:33
I would try with just cloning  the source and  ommit the " -b stable-1.1.1 " then you can use tab completion to see available branches and just pull the required one, this is normally how I do it if I want to try a new testing branch or something, If you need more explaining please reply again ;)
so basically in the LMMS working tree you would do " git pull -b origin " , then use the tab key for auto completion, which will list all branches, then just select.... 

thanks Mikobuntu ;)


Date: Thu, 12 Feb 2015 13:40:34 -0800

**Comment by mikobuntu** [comment] 2015-02-12 22:42
*EDIT* sorry I may have got my last reply wrong, I believe you will need to use the command " git checkout " followed by tab completion on your keyboard, and then " git pull " if i rem correctly, then the normal build procedures.

thanks Mikobuntu ;)

**Comment by Gps2010** [comment] 2015-02-12 23:13
Thank you but:
git clone https://github.com/LMMS/lmms.git checkout

Does not work at least not in a way, I can choose what to download.
It gives me this:
guus@linux-ab3o:~/lmms2> git clone https://github.com/LMMS/lmms.git checkout
Cloning into 'checkout'...
remote: Counting objects: 62088, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 62088 (delta 14), reused 18 (delta 10)
Receiving objects: 100% (62088/62088), 56.46 MiB | 5.98 MiB/s, done.
Resolving deltas: 100% (46440/46440), done.
Checking connectivity... done
guus@linux-ab3o:~/lmms2> 

I am very interested in tab completion, and being able to choose what I download though.
That should save me a lot of problems.

I might have found a better way.
https://github.com/LMMS/lmms/releases

Then I can just pick the version I want and download the zip file.
The command line way is giving me a headache, and I can't find documentation explaining how to do it, properly.
And trying what the lmms wiki suggest wont work either, or I am misinterpreting it.
Just downloaded the 1.1.1 zip. That version worked fine. fingers crossed.

**Comment by mikobuntu** [comment] 2015-02-12 23:20
I probably did not explain the steps to do this over the command line so well, but I sometimes take it ( wrongly ) for granted that everyone using linux is a master of the command line ;) ... Anyway the main thing is you found a way to get the version you were after and hopefully it works OOTB as they say ( or out of the zip folder ) for you ;)

thanks Mikobuntu ;)

**Comment by Gps2010** [comment] 2015-02-12 23:50
You were trying to help and I appreciate that.
But I hardly know more then: ls, mk dir, cd and ./ 
And of course tab completion, su and sudo.

I am using Linux for a while now, but my first Linux was SUSE 9.3 or something.
You already hardly needed a command line with that version.

These days there are Linux users, who do not even know were to find the command line, or what it is.
Its progress, but I sometimes wish I had started earlier with Linux in the good ? old days were you had to learn how to use the commandline.

**Comment by mikobuntu** [comment] 2015-02-13 00:09
I,m by no means an expert as my 1st linux distro was ubuntu 8.04, but I found I needed the command line more and more to get tasks done. Now I have grown to enjoy using it. Funnily enough I was looking at my .bash_history files yesterday and thinking to myself " did I really type in all of those commands wow!" lol
Remember man pages are your friend for e.g " man bash "  or " man ls "   ( although sometimes you will be using your fav search engine to understand what is going on with some of these documents )
thanks Mikobuntu ;)

**Comment by tresf** [comment] 2015-02-13 01:20
It is `stable-1.1`, not 1.1.1

**Comment by Gps2010** [comment] 2015-02-13 14:49
Thank you but that got me 1.1.2. At least that's what it said in the top of the lmms window.
Then I tried adding the third digit, which failed.

I am having a lot of issues this time around with compiling. The dependencies list is missing stuff at least for openSUSE 13.1. (64 bit)

If you're wondering why I did not have these issues before with same distro and version, its because I had already install allot of 32 bit libs, to fix issues with steam (games).
Now I am starting over from a totally fresh  openSUSE install.

I did make it yesterday beyond make install though, but midi is not working. (1.1.0)
There is no keyboard icon, on the midi tab, of the instruments, and when I try to change to change the midi settings under settings, it keeps going back to dummy.

Then I started lmms from the command line, and found the problem.
I don't have a clue yet on what lib I am missing. ( but I assume that’s the problem) 

Without midi controller plugged it:

Notice: could not set realtime priority.
VST sync support disabled in your configuration
[u]cannot open MIDI-device: Ongepaste ioctl() voor apparaat[/u]
Couldn't create MIDI-client, neither with ALSA nor with OSS. Will use dummy-MIDI-client.
( Ongepaste ioctl() voor apparaat = improper ioctl() for device)

Then with controller plugged in:
Notice: could not set realtime priority.
VST sync support disabled in your configuration
[u]ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed:[/u] Bestand of map bestaat niet
cannot open MIDI-device: Bestand of map bestaat niet
Couldn't create MIDI-client, neither with ALSA nor with OSS. Will use dummy-MIDI-client.
( Bestand of map bestaat niet = no such file or directory)

When running cmake, it said alsa oke. I will of course try to solve this myself, but if any of you has an idea on what I am missing ? 

A person from  the openSUSE forum tried to help me, by building a package for me on the obs.
(openbuild service:  https://build.opensuse.org/ )
But that one did not work 100% either.
I think that we, as in openSUSE users and package builder (packman), need a more complete list of dependecies ? 
I am also still talking with packman, but they don't know yet what goes wrong when they build the openSUSE package. 

@ mikobuntu  My first computers lessons involved basic at school, msdos and autocad , yes I am that old.
There was no windows yet. I hated the commandline back then.
But since I am using Linux, that has changed, I now love the command-line, at least the one from Linux.

**Comment by tresf** [comment] 2015-02-13 15:39
> Thank you but that got me 1.1.2.

Which version do you want?  There is no longer a 1.1.0 unless you grab the archive or `git clone` and then do a hard reset to a specific commit, but I recommend you use 1.1.2 because it has a fix with the FX Mixer that causes quite a bit of performance issues.  We've stalled the release to our home page due to some unrelated issues with the Windows build environment.

> I am having a lot of issues this time around with compiling. The dependencies list is missing stuff at least for openSUSE 13.1. (64 bit)

Yeah, "dependency h3ll" is a problem compiling anything on Linux.  I'm sure you have valid reasons to use the distro you've chosen and your efforts to get the software working are noble, but they have more to do with SUSE package management than they do LMMS.

If you really need a second set of eyes, I can setup an openSUSE VM and reproduce what you're seeing, but I don't have a MIDI device to test with so I'm not sure if I'll be able to reproduce the exact problem.  I'd also ask for the commands you've used to meet the dependencies (will save me 30 minutes searching yast)

**Comment by Gps2010** [comment] 2015-02-13 17:51
From the forums, I got the impression there was a problem with 1.1.2. But if its only for the windows version, I should not have a problem. I will get the zip for 1.1.2.
I am getting quite handy at this compiling. :)   

I did not use commands, I copy pasted the dependencies from the wiki into the yast desktop version.
Then let yast search for them. Although I am doing it one by one, yast can do more then one at a time. 
But if you don't have a midi controller, It wont solve anything.

After this I used cmake and make, and that did not go smooth, but reading the error and using google, I managed to solve them all.

I would not mind that much switching distro for lmms, but over my dead body, that unbuntu will be installed on my pc. Conical even has arguments with the people from debian, about how they do things. And then the ubuntu desktop.... 

Also Valve switched form ubuntu to debian, for their steam machines.
And if I learned anything from the steam github, its ubuntu doing things different.
Arch, fedora and openSUSE, do most or all stuff the same.

And about openSUSE, did you know that SUSE (used on servers) comes from openSUSE, and not the other way round like most people assume?
OpenSUSE is very secure, which I will admit, causes issues sometimes, and even got Linus Torvalds annoyed, because he had to use the root password, to change his desktop resolution.
He called openSUSE paranoid. :)

**Comment by tresf** [comment] 2015-02-13 19:39
> did you know that SUSE (used on servers) comes from openSUSE, and not the other way round like most people assume?

Same for Fedora vs. RedHat.  This way users stabilize the software.

> Also Valve switched form ubuntu to debian, for their steam machines.

We do have some pretty successful results on Debian from the KXStudio packaging.

> After this I used cmake and make, and that did not go smooth, but reading the error and using google, I managed to solve them all.

Right, but if you look at our Ubuntu instructions, you'll notice someone can compile with the copying/pasting of a handful of commands quickly.  If we can get people to document this for other distros, it can save the time each new user wants to compile from scratch.

**Comment by Gps2010** [comment] 2015-02-13 20:18
In general that should be easy.
I would need some help on the specific command but if we have the dependencies sorted it would be something like this:

sudo zypper install build-essential cmake libqt4-dev libsndfile1-dev libfftw3-dev \
libvorbis-dev libogg-dev libasound2-dev libjack-dev libsdl-dev libsamplerate0-dev \
libstk0-dev libfluidsynth-dev portaudio19-dev libfltk1.3-dev wine-dev \
libxinerama-dev libxft-dev libgig-dev

I will ask on the openSUSE forums if this is possible, or if I am overlooking something.

**Comment by Gps2010** [comment] 2015-02-13 23:43
I have been looking at jack, its been a while I used that, but it was easy to find my midi controller.
Why I am attempting this?
I found a topic of an Arch user who used jack to get rid of that alsa message with lmms.
The same as I am getting.
And as I stated before, Arch solutions often work on openSUSE too.

I made a tiny bit of progress.
When I use the gear in front of the instrument, I can select my midi keyboard in lmms.
To bad it wont record the notes I play, sound plays however, when I press a key.

And I tried a few different version from the openbuild service for openSUSE.
They all seem to have the same issue, on the midi tab, the piano keyboard icon is missing.

**Comment by tresf** [comment] 2015-02-14 14:50
Can you type `git remote show origin` from the build directory and verify you are on the stable-1.1 branch?

**Comment by Gps2010** [comment] 2015-02-14 16:02
Let me start by telling you, I did it again, lmms is working again, and does record midi input.

The command gives me:
guus@linux-ab3o:~/lmms2/lmms> cd build
guus@linux-ab3o:~/lmms2/lmms/build> git remote show origin
* remote origin
  Fetch URL: https://github.com/LMMS/lmms.git
  Push  URL: https://github.com/LMMS/lmms.git
  HEAD branch: master
  Remote branches:
    cmake_dist             tracked
    lmms2                  tracked
    master                 tracked
    models                 tracked
    old-master             tracked
    qrc                    tracked
    revert-1624-patch-4    tracked
    stable-0.4             tracked
    stable-1.0             tracked
    stable-1.0-vstbase-fix tracked
    stable-1.1             tracked
  Local branch configured for 'git pull':
    stable-1.1 merges with remote stable-1.1
  Local ref configured for 'git push':
    stable-1.1 pushes to stable-1.1 (up to date)

I am only a bit annoyed, I cant tell you guys exactly how I fixed it.
After cmake and make and make install ( without errors) lmms was not working right yet.
I do know what I did last night. Install about everything with alsa in the name, which to me looked like something that could be related. I also installed more jack related stuff, and audacity.
And suddenly,  the instruments in lmms, on the midi tab, were again showing that keyboard icon. 

I was hoping to make a list of dependencies for openSUSE, I had even started a text doc, on stuff I had to add. But as things go, its get late, and you loose a bit of focus.
One possible solution might be audacity.
As usual when you select something in yast, yast will tell you, that for this program, you need extra stuff (libs), and wants you to confirm, if you allow this.
The last time I managed to get it working I did not have that jack gui installed, but I did have audacity installed...

I can make music again and in the top of the lmms window it says 1.1.2

I will however have a talk with an opensue guy, to see if, now that I got it working, I can pull out a list of dependencies. I am afraid it wont be that simple though.

The list of extra dependencies for openSUSE might be:
glibc-devel-32bit
gcc-32bit - The system GNU C Compiler
gcc48-32bit - The GNU C Compiler 32bit support
and audacity. 

Very happy it is working again, and again I am thanking you guys for the help.
I also got another email from packman. They have build a new package with 1.1.2.
Fingers crossed this one will work. I have not tested it, because it has not yet appeared online (through yast)
