### ISSUE TITLE
Play the file by right arrow

### ISSUE THREAD

**Issue by hashhakaj** [LMMS/lmms#2514] opened 2016-01-21 04:46 UTC
Hello
I Still use LMMS in every PC that I purchase ,from desktop, Laptop, Hybrid and windows tablet. all with my project works perfect. 
One thing that I notice is the file explorer inside LMMS only play present by mouse left click only. since my usually work on laptop, the touch pad is my mouse. the left click is tap twice. So, the annoying for this is it usually didn't play well. specially play the presents while playing the master project. it usually play click or 0.05sec play . sometime it doesn't play at all that make me tap more than twice and it imports into my project by accident.

I get a solution for this. to use right arrow button on the keyboard to play the present file option to avoid import it by accident. 

So the right arrow has two function on LMMS file explorer, explore sub-folders and play presents. the length of play is how long you press the right arrow key.

Hopefully this suggested idea is implemented.

Regards

**Comment by zonkmachine** [comment] 2016-01-21 05:33
Hi @hashhakaj!
It's a very good idea. Either that or use some other key like the space bar. It's been suggested before. 
Here #871

**Comment by hashhakaj** [comment] 2016-01-21 05:43
Thanks zonkmachine
I'm glad you put the similar issue link. I'm tired to look an entire issues :)

**Comment by Umcaruje** [comment] 2016-01-22 11:37
Marking this as a duplicate of #871

**Closed by Umcaruje** 2016-01-22 11:37 UTC
