### ISSUE TITLE
Be able to preview sample sounds by keyboard selection (up/down arrow keys)

### ISSUE THREAD

**Issue by KeronCyst** [LMMS/lmms#5604] opened 2020-07-29 18:56 UTC
### Enhancement Summary

When exploring samples in the sidebar, it would be nice to be able to hear the sounds by arrow keys instead of only by clicking them.

#### Justification

Having to click to preview each sample is too much visual work; I'd like to listen to samples more quickly by using the arrow keys.

Thank you so much.

**Comment by Spekular** [comment] 2020-07-29 19:16
Duplicate of #871

**Closed by Spekular** 2020-07-29 19:16 UTC
Labels: enhancement

**Comment by KeronCyst** [comment] 2020-07-29 20:05
Sorry, I couldn't find it despite searching. At least it's in the works!
