### ISSUE TITLE
Piano Roll: not all notes are played, if one goes right after another.

### ISSUE THREAD

**Issue by vlad1777d** [LMMS/lmms#4003] opened 2017-11-22 23:49 UTC
Hello.

Problem.
Notes, that go just right after the same one aren't played by Piano Roll. They aren't intersected, I checked on 800 % of zoom.

Here are notes:
![screenshot from 2017-11-23 01-42-25](https://user-images.githubusercontent.com/12682937/33154271-edfc4e0a-cfef-11e7-9822-26af5980f4ad.png)

Same notes under zoom 800% (they doesn't intersect):
https://user-images.githubusercontent.com/12682937/33154288-0589b03a-cff0-11e7-8183-dd557fed02d9.png

Video demonstration (.mkv in .zip archive) (please, look to keys in Piano Roll, because this tool doesn't record Jack): [lmms___not_all_notes_are_played.mkv.zip](https://github.com/LMMS/lmms/files/1497746/lmms___not_all_notes_are_played.mkv.zip)

System: Linux Mint 18.2 x64 Cinnamon.
LMMS: RC4.96 from here: https://github.com/LMMS/lmms/pull/3688

**Comment by PhysSong** [comment] 2017-11-23 02:09
I think this issue is two-fold: piano-roll display issue and note on/off issue. Display issue is already reported in #3919.
By the way, which instrument is problematic? I guess you mean a note does not play its sound. Is it SF2 player, ZynAddSubFX, or other instrument?

**Comment by musikBear** [comment] 2017-11-23 16:06
@vlad1777d  can you upload project?

**Comment by vlad1777d** [comment] 2017-11-23 18:53
@PhysSong , I use SF2 player.

**Comment by vlad1777d** [comment] 2017-11-23 18:56
@musikBear , of course I can, but it's at home (I'll be there after 2 hours).
Also that project is really big, so I'll try to cut only "problem" place and create new project with only one instrument and pattern.

**Comment by vlad1777d** [comment] 2017-11-23 21:58
@musikBear , here is example with bug in Piano Roll: [bug___lmms_piano_roll.mmpz.zip](https://github.com/LMMS/lmms/files/1500243/bug___lmms_piano_roll.mmpz.zip)

**Comment by PhysSong** [comment] 2017-11-24 00:13
Just tested. The second C5 note plays sound, but it's not displayed. I think this is a duplicate of #3919.

**Comment by vlad1777d** [comment] 2017-11-24 01:03
Yeah, it is.
Sorry, I searched by "note", "note not", "note not played", but didn't found that =)

**Comment by lukas-w** [comment] 2017-11-24 13:52
Closing as duplicate of #3919.

**Closed by lukas-w** 2017-11-24 13:52 UTC

**Comment by musikBear** [comment] 2017-11-25 14:07
> @musikBear , here is example with bug in Piano Roll: 

Thanks, i try it out and see if i also get the bug
