### ISSUE TITLE
LFO speed multiplied by number of connections

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#3064] opened 2016-10-04 20:48 UTC
Steps to reproduce:
1) Add some LFO in the controller rack.
2) Add some FX effect to some instrument and connect Dry/Wet to created LFO.
3) Add another FX effect to same instrument and connect Dry/Wet to created LFO.

Expected result: LFO speed is same if both FX effects are active and when one of them is muted.

Actual result: LFO speed is multiplied by number of connections active.

Does not happen always but often. Usually after some time of playing. Stopping song and playing again makes LFO speed normal for a while.

Edit: Sometimes even LFO with single connection becomes several times faster than defined. Seems to be not related to CPU usage.

**Comment by DeRobyJ** [comment] 2016-11-03 20:01
Reproduced in 1.1.90.435, KXStudio 14
Added 2 effects on an instrument, connected the W/D to a controller, the same for both, the speed is doubled.

The problem gets fixed upon hitting play
The problem returns if you try to reproduce it on a new controller.

I think it's a minor bug, tho.

**Comment by Umcaruje** [comment] 2016-11-08 19:50
Reproduced on elementary OS Loki as well. Could not reproduce on 1.1.3. Marking as a bug, staging for 1.2, though this shouldn't affect the release if it doesn't get solved.

**Comment by JordanKyser** [comment] 2017-04-23 20:29
I found this bug on this file: https://lmms.io/lsp/?action=show&file=7410

**Closed** 2017-05-07 21:12 UTC
Labels: bug
