### ISSUE TITLE
Consistent behaviour, paint brush, saving settings.

### ISSUE THREAD

**Issue by Escordian** [LMMS/lmms#6317] opened 2022-02-20 14:40 UTC
I tried searching but I couldn't find any similar issues but I might be wrong on this and it's been brought up in the past, but here goes.

I have three suggestions:

1. In the piano roll you use right click to delete a note, in the beat editor you use the left click and in the song editor you use middle mouse button, I don't know why the behaviour is not consistent but it's pretty weird. As an extra, the middle mouse button is not a comfortable button and I would like to see right click being the universal delete key on all three editors. At least as an option.

2. A paint brush (like in fl) where you could paint several patterns at once in the song editor by just holding down the mouse button, clicking for each one works but it's not as fast. 

3. saving settings, for example being able to save the setting that you don't want to Auto-scroll would be super helpful. Also saving where the different editors show up on the screen, I like having the Beat editor on the left of the screen and the mixer on the bottom right and I have to move them each time I start the program.

**Comment by Monospace-V** [comment] 2022-02-20 15:09
For 1, MMB to delete is something I've seen elsewhere, and LMB to erase is actually pretty common (see MS Paint even), while also being a context menu button. But since we don't have a context menu for notes, while we do have one for clips, current behaviour works. However, right-clicking on a B/B track is the only way to trigger the context menu since what you are seeing technically isn't the notes, it's the clip. If you're clicking a box and a beat appears, it doesn't make sense to click it with a DIFFERENT button for the beat to disappear. The UI gives you the feeling that the same button should be used for removing that is used for placing.
Wondering, if LMB became default erase, what would be the button for clip context menu? We need song editor erase too often to manually switch between eraser and pencil mode, too...
I'd prefer it as an option and not universal, though. It'd be useful for a lot of users. Not for inconsistency reasons, but because MMB is an unusual button.
You might like to know, OP, that LMMS 1.3 alpha has the ability to delete TCO's with the delete key on the keyboard. Any selected TCO in SE can be deleted this way. This might make your workflow easier, if Del is less awkward than middle mouse button for you.

Regarding 3, already exists. Check out File > Save As Default Template.

2 I don't quite understand. What do you mean by "paint several patterns at once" by just holding down the mouse button and clicking for each one? Can you give us a video of what you mean showcasing the feature?

**Comment by Escordian** [comment] 2022-02-20 15:28
Thanks for the quick reply and thanks for explaining the behaviour of 1, maybe if you needed to hold down a button to get the context menu or something . But as an option like you said.

Didn't know you could save the layout as a template, that's awesome, thought that meant something else, chalk that up to me bing stupid. :) 

This is what I meant with painting patterns, you can tick it as an option in FL instead of doing it step by step like in LMMS. 
![GIF 2022-02-20 16-13-33](https://user-images.githubusercontent.com/28258960/154849664-88c0b56b-91b3-47b7-b1f7-8240ea482c42.gif)

**Comment by musikBear** [comment] 2022-02-20 18:46
FLs Painting:
Does the painted  notes 'glue' and create _one continuous_ note, or are they 'arpigated' single-notes? 
Its hard to see where Single notes in continuation comes in as useful often(?)
I am working on a small feature that let you elongate (+/-) any note, its really a accessibility feature (poor sight makes it hard to grab tiny notes), but in a way it will also let you change short notes to long notes and vis a vi

**Comment by Spekular** [comment] 2022-02-20 19:07
> 1. In the piano roll you use right click to delete a note, in the beat editor you use the left click and in the song editor you use middle mouse button, I don't know why the behaviour is not consistent but it's pretty weird.

Duplicate of https://github.com/LMMS/lmms/issues/1488, see also #1475 and #4877. Also, there's no reason to use different buttons for place and removal in the pattern editor, LMB simply toggles a position on or off.

> 2. A paint brush (like in fl) where you could paint several patterns at once in the song editor by just holding down the mouse button, clicking for each one works but it's not as fast.

Duplicate of #4694.

> 3. saving settings, for example being able to save the setting that you don't want to Auto-scroll would be super helpful. Also saving where the different editors show up on the screen, I like having the Beat editor on the left of the screen and the mixer on the bottom right and I have to move them each time I start the program.

As mentioned, already possible via default templates.

**Closed by Spekular** 2022-02-20 19:07 UTC
Labels: enhancement

**Comment by Escordian** [comment] 2022-02-20 19:08
What I want is to have this behaviour in the Song-editor, like this

A more clear example
![GIF 2022-02-20 20-08-04](https://user-images.githubusercontent.com/28258960/154859824-1e86709a-ef6b-4cdc-8c7a-683f8535bd42.gif)


So for example if I create a drum pattern and I want it to continue for eight bars I can just paint the eight bars instead of doing them one by one or copying a bunch of them etc.

As far as I know LMMS doesn't let you do this, I realise this is just a quality of life thing but it's so smooth just painting the patterns instead of doing them one at a time.

But FL does let you do this in the piano roll as well, I've hardly used it there but to answer you question it doesn't glue the notes, it just creates a bunch of different notes.

**Comment by musikBear** [comment] 2022-02-21 16:35
> What I want is to have this behaviour in the Song-editor, like this
A more clear example ![GIF 2022-02-20 20-08-04](https://user-

Yes, that is how FLs does, buthere LMMS has chosen a different method. You just ctrl-drag the clip the number of times you  want to copy. 
LMMS is **not** meant to be a clone of FLs! 
There are things that are being done almost identical in all DAWs, and those are also found in LMMS, but LMMS does other things in its own way! -And copying clips is one. 
And as Specular already has pointed out: You suggestions are duplicates of already existing request.
_Please_ do search the database before posting requests.
Here:
![image](https://user-images.githubusercontent.com/6662066/154994885-60f8187f-f5af-4ca8-a249-65c87af65776.png)
The formulae is a bit 'odd'
You need to remove the filter-option(s) **is:issue is:open**  Because you want to see _everything_! Default you only see bugs and only those that is not closed! That is not intuitive, but other wise the search works reasonably well
_Please use it_  :)

**Comment by Escordian** [comment] 2022-02-21 17:23
Hey, I'm aware that LMMS is not a clone of FL, I'm not asking for LMMS to be FL either, I just wanted a couple of features that is available in FL that I feel makes it easier to work with. If you don't agree with having those features that's fine but I'm allowed to politely ask for them. :)

I'm sorry that I missed the previous posts and I will do a better more thorough search next time thanks to your tips :)

**Comment by rdrpenguin04** [comment] 2022-02-22 01:20
@Escordian You're fine! Thank you for opening the issue; even if it's a duplicate, you now know what to look for.

@musikBear Chill.
