### ISSUE TITLE
Tab MISC | 'Enable the use of Master-pitch' is ignored

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2613] opened 2016-02-26 14:30 UTC
PR 17. feb. g23d284 win32

To reproduce:
Insert any number of presets or sample tracks in B&B-editor
Add some notes.

Disable all MISC. |  MASTER-PITCH
Start replay
Move Master-pitch-slider

all the track changes pitch

Does current windows Master (still) have this behavior?

Demofile: https://lmms.io/lsp/download_file.php?file=8152&name=masterpitchErrors.mmp

propl. related to #2612

**Comment by karmux** [comment] 2016-10-26 22:04
Disabling use of master pitch doesn't work in B+B editor but does in song editor.

**Comment by zonkmachine** [comment] 2017-03-13 14:40
Duplicate of https://github.com/LMMS/lmms/issues/2612

**Closed by zonkmachine** 2017-03-13 14:40 UTC
Labels: duplicate

**Comment by musikBear** [comment] 2017-07-25 11:40
@zonkmachine No no this is not a duplicate 
The 2612 is a fishy thing with the actual flag-change-event
There is something that make the 'next' in the chain take the previous setting, but **this** is simply reporting the observation, that the feature 'enable the use of master-pitch' is unreliable 
To reproduce win32 RC3:
* Open a new  project
* Open Samples and swap default preset for bassdrum01.ogg
* on Miscellaneous tab -Disable **'enable the use of master-pitch'**
* insert a few events, play
When i move the Master-pitch, the pitch *does* change, and here there is only *one* preset so the 'slave-behaviour' of 2612 is not relevant.
-Can you please reopen (i as 'not-contributor' have no button..

**Comment by zonkmachine** [comment] 2017-07-26 06:59
> -Can you please reopen (i as 'not-contributor' have no button..

I will look at this again.

**Comment by zonkmachine** [comment] 2017-07-28 13:12
Tested. My first impression is the same. It's most certainly the same issue. Both issues can be summed up by 'Misc/Enable the use of Master-pitch - Erratic behaviour'.
Not reopening, but I'll link to this issue from the other.
