### ISSUE TITLE
LMMS jack output channels is fixed at the value "2"

### ISSUE THREAD

**Issue by synthnassizer** [LMMS/lmms#5960] opened 2021-03-21 23:12 UTC
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.

### Bug Summary
LMMS jack output channels is fixed at the value "2"
#### Steps to reproduce
Go to "Edit" Menu ->"settings" -> audio settings-> select "jack" output -> try to change the #2 of channels.
#### Expected behavior
The # of channels should be editable
#### Actual behavior
it is stated that I could "enter a new value between 2 and 2". 
This means I am not able to change the # of output channels.
#### Screenshot
![Screenshot_2021-03-22_01-07-51](https://user-images.githubusercontent.com/6747253/111924036-0c940500-8aab-11eb-809b-1c3f218846a5.png)
#### Affected LMMS versions
1.2.1

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by IanCaio** [comment] 2021-03-21 23:19
That's because LMMS currently can only work with 2 audio channels. Closing this as it's not a bug but an enhancement request which is a duplicate of this one https://github.com/LMMS/lmms/issues/4064

Maybe we could disable that Spinbox, but since it doesn't allow the user changing the number of outputs to an invalid one this is not a priority but a minor UX issue.

**Closed by IanCaio** 2021-03-21 23:19 UTC
Labels: bug
