### ISSUE TITLE
Changing between .wav and .ogg in 2nd export screen doesn't fully work

### ISSUE THREAD

**Issue by return2monki** [LMMS/lmms#6369] opened 2022-04-09 22:41 UTC
If you change file format in the 2nd export screen that comes up it doesn't change the file extension output.

Maybe the file format changing should be removed from that screen to avoid confusion? If it can't be fixed that is.

version 1.2.2

**Comment by Spekular** [comment] 2022-04-09 23:48
Duplicate of #5744

**Closed by Spekular** 2022-04-09 23:48 UTC
