### ISSUE TITLE
Moving and dragging & dropping tracks enhancement.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3592] opened 2017-05-30 18:55 UTC
* When clicking on a "move-grip" or the track label  or any empty space in a track, this is what happens:
![bug 1](https://cloud.githubusercontent.com/assets/25503477/26597071/6d0a4618-4579-11e7-8295-92cd8fa68702.png)
"Move-grip", "Actions for this track" and "Mute this track" disappear but "Solo" doesn't.

* Dragging & dropping a track can only be done after pressing & holding Ctrl then clicking & dragging from the "move-grip", but moving a track isn't limited to the "move-gip" only.
I think we should limit the ability of moving and dragging & dropping tracks to these:
![image](https://user-images.githubusercontent.com/25503477/31543848-cd883df8-b020-11e7-87e3-9642ebf64786.png)

Last **edit** was in 13 October, 2017.

**Comment by PhysSong** [comment] 2017-05-31 07:33
Actually (2) isn't a bug. It is a feature that shows the track is moving.
See link below:

https://github.com/LMMS/lmms/blob/stable-1.2/src/core/Track.cpp#L1770-L1774

**Comment by BaraMGB** [comment] 2017-05-31 07:41
But why the solo button isn't hide? This is a little bit confusing.

**Comment by karmux** [comment] 2017-05-31 08:11
(3) is #757. Seems that some people have this issue (me and @Hussam-Eddin-Alhomsi) while some don't (@davidgerard).

**Comment by Hussam-Eddin-Alhomsi** [comment] 2017-05-31 13:15
I removed the bug (that's what I thought) from my first comment that was about the ability of moving a track when clicking & holding & dragging in areas other than the "move-grip" because @BaraMGB said that it's a feature,
But there's a new bug that I noticed which is the third one now.

**Comment by musikBear** [comment] 2017-05-31 16:21
> Seems that some people have this issue

OS? Lmms vers? ..
Not seen on win32 xp up to 1.190 at least

**Comment by Hussam-Eddin-Alhomsi** [comment] 2017-05-31 16:36
I'm on Windows 10 Pro 64-bit using LMMS 1.2.0-rc2.

**Comment by karmux** [comment] 2017-05-31 16:40
Linux master and with both Qt4 and Qt5.

**Comment by PhysSong** [comment] 2017-06-01 03:39
@BaraMGB

Should we hide solo button? or just hide move-grip and action button only?

**Comment by BaraMGB** [comment] 2017-06-01 07:15
I'm not sure if hiding is a good idea at all. It has a taste of bug. @umcaruje @tresf @other?

**Comment by Spekular** [comment] 2017-06-01 07:22
A transparent gray box over the whole track label to signal "inactive"
might look less buggy?

**Comment by Hussam-Eddin-Alhomsi** [comment] 2017-06-01 13:05
We need an indicator of the ability of moving the track inside the "BB E".

If we are not going to hide anything (which I agree with) I think this would look nice:
![track idea 1](https://cloud.githubusercontent.com/assets/25503477/26680777/51a5a8ca-46e3-11e7-9ea7-311d1f1ed9cf.png)
^ The same green as the "mute this track" button.

If we are going to hide, I think hiding the "Action" button only and replacing it with something the buttons of an elevator would look nice too:
![track idea 2](https://cloud.githubusercontent.com/assets/25503477/26680803/6b4df57a-46e3-11e7-9038-471debeb1a56.png)

The animation of moving a track to the"Song-Editor" or the "BB E" while pressing <Ctrl> then clicking on the "move-grip" and dragging and dropping looks fine to me.

**Comment by musikBear** [comment] 2017-06-01 16:05
since earlier (<1.9n) ver. did not have this, it points at qt5

**Comment by BaraMGB** [comment] 2017-06-01 16:49
>since earlier (<1.9n) ver. did not have this, it points at qt5

This issue is reduced to only one issue. We only talk about what's described in the first comment now.

**Comment by tresf** [comment] 2017-06-01 20:31
> since earlier (<1.9n) ver. did not have this, it points at qt5

1. There's no such version as `1.9`
2. On discord we reproduced with 1.1.3, which uses qt4

> OS? Lmms vers? ..
> Not seen on win32 xp up to 1.190 at least

Please test, reproduce and post.

**Comment by tresf** [comment] 2017-11-15 04:40
Closed via #3592.

**Closed by tresf** 2017-11-15 04:40 UTC
Labels: gui, ux

**Comment by Sawuare** [comment] 2017-11-15 11:51
@tresf You miss referenced the pull that closed this issue. It should be pull #3878. :D
