### ISSUE TITLE
VST-Plugins tune off when exporting on LMMS 1.1.3

### ISSUE THREAD

**Issue by naturbua** [LMMS/lmms#4469] opened 2018-07-08 16:22 UTC
Certain VST-Plugins, including seemingly everything by DSK and some others, tune off when I export a song. While working with the plugins in the daw itself, everything sounded fine, but after exporting, the exported wav/ogg itself and the projekt sounded off. Only certain VSTs are affected by this, as I already mentioned. I remeber using them on Windows 8 and an older LMMS version without having this problem.

For a better understanding I'll add two soundfiles. One I recorded with Audacity directely from the daw, and one with  the exported file. 
I used FireBird for the melody part, which is uneffected by the off-tuning, MRTramp2 for the electric piano, which has the wrong pitch after exporting (just by like 11 cents, but you can easily hear it) and Juno6 vor some very silient background noise which was meant to support the percussions, but those last two aren't affected by the issue.

Sound in the daw:
https://soundcloud.com/user-498225535/lmms-daws-sound/s-zH6De

Exported file:
https://soundcloud.com/user-498225535/lmms-exported-sound/s-DleBY

Specs:
Windows 10 Pro
AMD Ryzen 5 1600X Six-Core Processor @ 3.60GHz, 16GB RAM
LMMS 1.1.3 is installed on my C Drive, a SSD by Crucial (with enought room to breathe)
I am using a USB Razer Kraken 2 but this isn't the cause since I had the same issues when I switched to headphones with a normal aux jack.

I also tried to mess a bit with the audio-settings of lmms and also with the export settings. Nothing concerning this issue changed.

Being well aware that this issue is quite similar to #2085 I have to again highlight that only by exporting this issue appears, not in general.

Can anyone with WIndows 10 reproduce this problem? 
Here's the link to MrTramp: https://www.genuinesoundware.com/?a=showproduct&b=40
And here's one to DSK http://www.dskmusic.com/
I had problems with DSK World StringZ, DSK  SaxophoneZ and DSK Indian DreamZ, but since most of their VSTs are based on the same architecture, I guess that every DSK plugin is affected.

Thank you in advance for your help.

**Comment by DomClark** [comment] 2018-07-08 16:29
Thank you for the bug report. We've been improving VST support recently and there may have been changes in this area; can you try downloading our latest beta version (under "Beta Versions" at https://lmms.io/download/) and see if the issue still persists?

**Comment by jibin1573** [comment] 2018-07-09 04:09
I know this problem. You can try using Portaudio in audio settings. I have tried this.  Portaudio can export the song without detuning. Portaudio was removed from RC5. 

SDL detunes even in RC6. And the amount of latency is also high.

**Comment by jibin1573** [comment] 2018-07-09 04:13
And most important. SDL will detune only if you cross 44100hz (audio quality). And as you keep increasing the audio quality, the pitch goes upwards. 
For the portaudio to work properly, you have to make the entire song with Portaudio enabled. (From the beginning of the song)

**Comment by DomClark** [comment] 2018-07-09 15:01
My apologies, I thought I'd fixed this but it turns out the code never made it as far as GitHub. I'll address this in an upcoming PR.

**Comment by musikBear** [comment] 2018-07-09 16:29
@jibin1573 Those 2 https://github.com/LMMS/lmms/issues/4469#issuecomment-403354780 are very good finds! Especially because SDL is LMMS' fixed standard for windows OS.
*That* said, i have never actually experienced this. Must some oversampling take place, or does other export settings play a role too?
(I will try exporting Onion.mmpz with a Synth1 VST as lead)

**Comment by jibin1573** [comment] 2018-07-09 17:55
Thanks @musikBear! Some of the VSTi that cause problems are:

1.MaxSynth's Bass Module (Free): Effect: pitch shifts upwards 
Cause: happened when I was exporting wav @ 24bit with sample rate at 96000hz. 
(No problems were found when I exported it at 44100hz @24bit.)

2. Helm: 
Effect: pitch shifts upwards 
Cause: happened when I was exporting wav @ 24bit with sample rate at 96000hz. 
(No problems were found when I exported it at 44100hz @24bit.)

3. DSK Overture:
Effect: pitch shifts upwards 
Cause: happened when I was exporting wav @ 24bit with sample rate at 96000hz. 
(No problems were found when I exported it at 44100hz @24bit.)

I'll report other VSTs, when I get time.

**Comment by naturbua** [comment] 2018-07-09 18:18
So I tested some of the vsts which caused issues in 1.13 in RC6 and they seem to be vanished (aside from that I had some hassle with Port Audio, which doesn't exist in RC6 so I had to switch to SDL in 1.13 to make it start; also see #4405 ) . Even some Big Cat  VST instruments (e.g. Iowa Piano) which caused crashes when saving and reloading a project run now smoother and didn't cause crashes at all so far.

I exported some melodies and they had the same pitch as the daw's sound. 
Out of sheer curiosity I retested the same VSTs in 1.13 with using SDL and -oh wonder- the detune was gone. 

So as a conclusion I can tell that SDL worked best for me, in both, RC6 and 1.13. Increasing the quality did actually end up in messing up the pitch of the sound, but it was rather like 3 or 4 semitones higher than having a strange detune. But the export parameteres always appeared a bit unsteadily to me and the results I got were always messed up. (Probably worth opening a new separate issue?)

Additionally, I should mention that I found another bug of which I am not sure of if it is known yet: When you try to overwrite an opened audio file (e.g. you opened it Windows Media Player), RC6 will tell you that it can't get access to the file and then crash/ close without saying goodbye.

But I feel like the VST support improved a lot in RC6, even if The Anvil v3 by Ignite Amps, Neo Piano, Piano One, and Orchestral Strings (by Yichi Wang) still don't work in RC6.
I will keep testing some vsts and let you know when I find some weird things beside an uncompatible VST-Plugin.
Thanks for everyone's approches on this issue so far :)

**Comment by jibin1573** [comment] 2018-07-10 04:30
@naturbua, if possible, please try out LMMS 1.2.0 RC4 with Portaudio also. You can test exporting with Portaudio and also test the latency while playing MIDI.

**Comment by SecondFlight** [comment] 2018-07-10 13:38
RC4 is old and does not have all the latest VST fixes so I do not see the purpose of testing this in RC4 as it does not relate to this issue. The issue author said that their issues were fixed in RC6.

If you're having issues exporting with different samplerates, that is a separate issue. I suggest opening it as such.

 >44100hz (audio quality).

44100 is the samplerate your computer will play back at. Increasing the samplerate is known as oversampling, and some plugins do this internally to improve audio quality, but this isn't very useful without the algorithm to convert back. The highest frequency that can exist in an audio file is equal to half of the samplerate. 44100/2 is 22050 which is just above the range of human hearing. Increasing the samplerate just allows for more frequencies you can't hear.

That's not to say increasing the samplerate doesn't have its uses, but it's not a direct audio quality thing as long as you are at or above 44100 hz.

Again, if you have an issue with exporting at higher samplerates, please report it. We support exporting at different samplerates, so if there is an issue with doing so then we'd like to know about it.

**Comment by DomClark** [comment] 2018-07-10 14:36
Since the OP says their issues are fixed in the latest RC/by using SDL, I'm going to close this and track @jibin1573's issue in #4479.

@naturbua:
Glad to hear RC6 is working better for you.

>Increasing the quality did actually end up in messing up the pitch of the sound, but it was rather like 3 or 4 semitones higher than having a strange detune.

Is this the whole file or just the VSTs? If just the VSTs, this is probably the same as @jibin1573's issue. If it's the whole file, can you provide an example, with a file at the correct pitch and a file at the wrong pitch?

>But the export parameteres always appeared a bit unsteadily to me and the results I got were always messed up. (Probably worth opening a new separate issue?)

A new issue sounds like a good idea, but try to elaborate a little more as to what you mean by "unsteady" and "messed up".

>When you try to overwrite an opened audio file (e.g. you opened it Windows Media Player), RC6 will tell you that it can't get access to the file and then crash/ close without saying goodbye.

Is this the same as #4426? If not, can you open a new issue for us please?

**Closed by DomClark** 2018-07-10 14:36 UTC
Labels: bug, vst

**Comment by musikBear** [comment] 2018-07-10 21:56
@jibin1573 Ohh! Its VST specific! Then i can understand why i have not experienced it!
I tried with Synth1 in Onion, and i made a discovery. Onion is 'base-noted' -eg tuned, in lots of ways! The reason is, that it mostly uses *samples*, and they are 'pitch-by-ear' Onion is completely wrong for this purpose. In fact, i think i will find a new standard-song for tests. A test-project should be based on reproduceable standards, and Onion is not.
Helm is one of those i have on the no-go-list. Iirc It will not reopen with user-settings, but revert to its defaults.
In the meantime, this was closed.. idk..
