### ISSUE TITLE
Trying to open ZynAddSubFX parameters crashes ZynAddSubFX

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#5989] opened 2021-04-17 15:58 UTC
Opening a ZynAddSubFX instrument's GUI, then clicking on File > Open Parameters causes the ZynAddSubFX GUI window to flicker, then crashes ZynAddSubFX.
Windows 10, 64 bit, LMMS 1.2.1

**Comment by DomClark** [comment] 2021-04-18 17:44
This sounds like a duplicate of #4455.

**Closed by DomClark** 2021-04-18 17:44 UTC
