### ISSUE TITLE
patterns should be passable by reference

### ISSUE THREAD

**Issue by ballerburg9005** [LMMS/lmms#5608] opened 2020-08-02 22:10 UTC
Currently if you copy a note pattern in the song-editor it creates a new pattern that is identical to the original. Changes in either one are not reflected in the other.

**The feature:**

If patterns were passable by reference, a copy would create a copy of the reference only and therefore changes made to the pattern would be consistent across the entire song. Pattern "duplication" as a second option on the other hand would mimic the current behavior. 

The patterns should be indexed, selectable in a browser and usable across instruments. It would also be very useful to be able to superimpose "pattern modifiers" onto one pattern to create a new one. The new one wouldn't be a duplication of the other, but a reference to the original that dynamically modifies it according to certain rules. Those "pattern modifiers" could be, just to make a small  example: octave shift, inverting the notes horizontally or vertically, scaling the note length by a factor, offsetting the notes, repeating each note several times, keeping just every note on the n-th tick and adding or subtracting another pattern to/from the current pattern.

**An example:**

A bassline for electronic music is generated by 3 synthesizers. There are 6 unique patterns each 8 units long that repeat throughout the entire song, which is 248 units long (5 minutes). Thus 32 references per synthesizer, means 96 references are required total for the bassline. 

Currently, if the user desires to change merely one note in the finished song for merely the bassline, they have to change each one of the 96 static copies by hand - since references are not implemented. A job that takes close to 5-10 minutes.

With references implemented, the user simply needs to change the one note in each of the 6 unique patterns. A job of less than 30 seconds.

This is not only true for basslines, but also true to leads, strings, choirs, beat and also across combinations of all of them. Simply with the already present octave shift in the instrument options, you could work with mere 6-8 unique patterns, and easily end up passing 400 references to them in a 5 minute song.

With "pattern modifiers", as mentioned in the feature description, those 400 references could be easily reduced to mere 2-3 (or even just one!) unique patterns. Which means that if you changed just one note in the bassline, it would be consistently reflected across the entire song and the choirs and leads also consistently reflected this change if the user desired it so and laid it out in that way. Similarly instruments, samples and percussion that are meant to be auxiliary to the melody would instantly  reflect changes in the melody pattern, if so desired, by means of just very basic "pattern modifiers" that all boil down to the single root pattern.

**The implications:**

Without pattern references, the editing process is in fact so much restricted, that people using LMMS have to meticulously engineer their entire production technique to accommodate for just this limitation. Going beyond one or two 16 unit patterns, i.e. a couple of seconds, LMMS users are required to compose the entire song largely in their heads by imagination alone, just to avoid the extreme efforts required to change something in hindsight, as described earlier in the example. Then as the final step the patterns are copied statically across the entire song, only to be ever changed again in critical cases of emergency.

**The conclusion:**

Music is highly repetitive, with most instrument notes being the same or just minor variations of one another that form just a sparse hand full of unique patterns in an entire song. Composing music is a creative process that highly depends on experiencing it. This means iterating over and over again over your work to make changes that all affect each other forwards and backwards. This concerns small scales (samples, sounds), intermediate scales (patterns of sounds), the whole (patterns of patterns) and any reciprocative intermixture thereof.

Without pattern references, the creative process is restrained by a "bottom to top reverse pyramid" and "sculptured in stone" workflow. 

While it is true that sculpting in stone is not necessarily a "bad workflow", it is nonetheless a limitation - a really huge and fundamental limitation in the work and design process. Changing just one chord in the finished song is a cardinal error along the lines of chipping off Michelangelo's David's nose: You would end up editing some 400 statically copied patterns, taking you literally hours. Although gluing the nose back on can theoretically still be done, its just isn't for obvious reasons, and it shouldn't be thought of as viable to do so. By the same logic, LMMS currently doesn't work alike a DAW intrinsically should, but rather like an analog tape recorder. Because patterns once laid out are of quasi irreversible nature. 

Passing patterns by reference has been implemented since the dawn of digital music production over 40 years ago. It is such a basic and fundamental feature. And it is also so simple to implement, while being highly beneficial. It remains a mystery how LMMS does miss it.

**Comment by Spekular** [comment] 2020-08-03 07:58
Duplicate of #3100

**Closed by Spekular** 2020-08-03 07:58 UTC
Labels: enhancement
