### ISSUE TITLE
[BUG] Automation, when copied/pasted, doesn't repeat

### ISSUE THREAD

**Issue by mrrm92** [LMMS/lmms#3738] opened 2017-07-29 18:40 UTC
The title is pretty self-explanatory.
I tried to copy and paste an automation track (done from the song editor) and it happens this way.
I guess the automation should repeat from where I copied it from beginning.

**Comment by musikBear** [comment] 2017-07-30 11:07
duplicate of #3359

**Closed** 2017-07-30 15:24 UTC
Labels: duplicate
