### ISSUE TITLE
AFP sample tuning  knob

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2411] opened 2015-10-13 16:56 UTC
AFP could use s simple sample tuning  knob like the TripleOscillator  Oscillator tuning  knobs.

**Comment by Spekular** [comment] 2015-10-13 19:20
As in the pitch knob?

**Comment by tresf** [comment] 2015-10-13 19:35
Duplicate of your own comment here:  https://github.com/LMMS/lmms/issues/1471#issuecomment-104350718 which is already being tracked in our `Better Sample Track` thread.

@Reaper10 We've issued a warning, final warning and now this is the final straw.  Your account will no longer be allowed to post to our tracker due to misuse.  If you'd like to dispute this, you can do so on the forums.

**Closed by tresf** 2015-10-13 19:35 UTC
