### ISSUE TITLE
Drag instrument track label onto mixer slot to assign instrument's FX channel

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#2011] opened 2015-04-26 06:07 UTC
LMMS would benefit from an easier way of linking an instrument to a newly created FX channel. I think one way to do that is to mimic the way controls are assigned to automations via `ctrl+drag`. In this case, `ctrl+dragging` an instrument track view onto a mixer slot would set up the instrument to route its output to that FX channel.

Here's a rather poor image, but hopefully it will do a decent job of illustrating the idea:

![lmms-mockup-mixerlink](https://cloud.githubusercontent.com/assets/1210751/7336079/8ed7386a-ebd9-11e4-8372-197e3ab8a7c5.png)

Additionally, dragging the instrument directly onto the "+" button in the mixer could create a new FX channel for the link. I think this would be especially useful.

**Comment by musikBear** [comment] 2015-04-26 09:58
is related to #355 
imo a button on the preset (355) gives more intuitive workflow:
Drag in instrument
make a preset
name it
click new fx-connect-button
New named fx-channel is added to mixer
This workflow does not need more than one window (preset) opend, and allow for the whole event to take place.

**Comment by Sti2nd** [comment] 2015-04-26 19:35
Agreed, Ctrl + drag would be wonderful!

**Comment by tresf** [comment] 2015-04-27 13:51
We have to exercise caution when re-using a shortcut such as `CTRL + Drag`, as it can confuse the end-user a bit, as the `CTRL + Drag` for a very long time has been associated with adding automation events.  Once we re-use this same shortcut for a different purpose, it has the possibility of confusing people.

This also a two-way street IMO... Dragging a track to an FX channel should probably be the same as dragging an FX channel to a track.

That said, `CTRL + Drag` seems sensible enough. :+1:

**Comment by musikBear** [comment] 2015-04-28 09:58
Instead of that drag, which is a more difficult thing to do with the mouse, Why not 
![pastelmmsknap](https://cloud.githubusercontent.com/assets/6662066/7367133/78986b12-ed9d-11e4-92cc-cc7f725525ba.PNG)
Simply having the fx-selecter designed as a button?
pressing it would connect to FX-mixer, and copy the chosen instrument name into FX-mixers name-field.
Scrolling mouse-wheel over ut, would scroll the FX-number, just as today
That is simpler - imho, and there need to be no confusing around drag&drop

**Comment by tresf** [comment] 2015-04-28 12:32
@musikBear we're getting there... #1572 :)

**Comment by tresf** [comment] 2015-08-24 16:17
@Wallacoloo do you mind closing this as a duplicate of #48 or do you still want the drag/drop support?  I'm sure our drag/drop support could be enhanced to accommodate what you're describing, but we'd likely need to use a modifier key, such as CTRL.

**Comment by Wallacoloo** [comment] 2015-08-24 16:36
@tresf #48 doesn't seem very well-defined to me, but what I gather as its intent is mainly summarized in this sentence:

> Another thing is to request mixer to assign an unused mixer strip to every newly added instrument. Then if the user renames it, the auto-rename feature will do the rest.

So whereas #48 is about automatically connecting new instruments to new Fx channels & shortening the name, this issue is specifically about drag/drop support. I feel they are sufficiently (rather *entirely*) different. But feel free to close this issue and consolidate it into a relevant WIP/mega-thread if there is any.

**Comment by tresf** [comment] 2015-08-24 16:47
> @tresf #48 doesn't seem very well-defined to me

Sorry... I should have linked the PR #1572 which was inspired by #48.
> feel free to close this issue and consolidate it into a relevant WIP/mega-thread if there is any.

If you still want it then it's still valid. :+1:

**Comment by tresf** [comment] 2019-03-11 21:08
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Closed by tresf** 2019-03-11 21:08 UTC
Labels: enhancement, gui
