### ISSUE TITLE
Sample Track: allow sending to FX-mixer

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#3791] opened 2017-09-03 14:37 UTC
I really miss an option to route a Sample Track output to a channel in the FX-Mixer.

**Comment by Umcaruje** [comment] 2017-09-03 14:39
Duplicate of #2619, #133, which are a part of #1471

@unfa please search the tracker before posting so we avoid duplicate issues.

**Closed by Umcaruje** 2017-09-03 14:39 UTC

**Comment by unfa** [comment] 2017-09-03 14:44
Oh, sorry - I messed up :(
