### ISSUE TITLE
Vst Plugin windows doesn't auto size to plugin size.

### ISSUE THREAD

**Issue by superfirak** [LMMS/lmms#5350] opened 2019-12-21 08:48 UTC
When i using MJUC, i clicked to sub window arrow and sub window opened but i can't see sub window. I cant change window size.
![resim](https://user-images.githubusercontent.com/8155284/71305619-bf2c7200-23e7-11ea-9540-74b346791014.png)

**Comment by DomClark** [comment] 2020-01-09 18:34
I think this is a duplicate of #4087. You can work around it for now by changing the plugin embedding mode to "no embedding" in settings.

**Closed by DomClark** 2020-01-09 18:34 UTC
