### ISSUE TITLE
All ZynAddSubFX presets are duplicated visually

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#3180] opened 2016-12-27 11:54 UTC
There are Zyn presets nicely in subfolders like they have always been. I noticed that all Zyn presets are also showing directly under ZynAddSubFX folder below "the_mysterious_bank4".
This happens only when there are presets saved under into {LMMS_DIR}/presets/ZynAddSubFX/. If I move presets away from this folder, all factory duplicates go away as well.
Master branch on Linux.

**Comment by tresf** [comment] 2016-12-27 13:52
@karmux normally, user-presets are added to `~/lmms/presets/`, not `{LMMS_DIR}/presets/`.  Have you accidentally configured your LMMS home directory to be the same place as the read-only directory?  If that's the case, I can understand how this happened but this is not intended usage.  I don't believe we have any logic to remove duplicates if both locations are the same.

**Comment by jasp00** [comment] 2016-12-27 14:07
I can confirm karmux has spotted a bug.

**Comment by karmux** [comment] 2016-12-27 14:07
@tresf by LMMS_DIR I actually meant ~/lmms/ which in my case is ~/Documents/LMMS.

**Comment by Umcaruje** [comment] 2017-01-09 15:34
Fixed by #3184

**Closed by Umcaruje** 2017-01-09 15:34 UTC
Labels: bug
