### ISSUE TITLE
Export as Loop improvements

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#1936] opened 2015-04-07 11:14 UTC
In Export screen, you can chose to export as loop, but:
- Reverbs/Delays are cut
- Due to this, final phase may not be 0 (clipping a end of loop)

Improvements:
- Export as loop wil make so that final phase is 0 (quick fadeout?)
- A new toggle will "create reverb and delays at beginning of loop"

This way loops can be loopable even if with reverb.

I know, people shouldn't put reverb in loops, but when using them. 
I find this feature really interesting for background repetitive music, such as for youtube vlogs and expecially videogames.
Right now, to achieve this behaviour, you need to export the song with a slice of the beginning at the end, then replace the output file beginning with the end, add some fading and so on.

Another workaroud is to make an automation to turn reverbs/delays off quickly at the end of the loop. This only sound well if a very similar reverb returns when repeating the loop, such as in small loops.

**Comment by tresf** [comment] 2015-04-07 16:06
Duplicate of #1484.

**Closed by tresf** 2015-04-07 16:06 UTC
Labels: duplicate
