### ISSUE TITLE
Make Possible to Ctrl-Z deleted instrument in the Next Release

### ISSUE THREAD

**Issue by unersame342** [LMMS/lmms#6844] opened 2023-09-03 17:25 UTC
All is in the title,
I made a very good pattern and i wanted to remove instrument to make the song end progressively but i missed and
deleted the instrument instead of the pattern case so please make possible to recover instrument when accidentaly remove

Thanks a lot

**Comment by DomClark** [comment] 2023-09-04 23:31
A confirmation dialog when deleting instruments has been added for now (in #5274), which should prevent losses due to misclicks. This is a good eventual goal, though.

**Comment by zonkmachine** [comment] 2023-09-05 18:36
I believe this is a duplicate of https://github.com/LMMS/lmms/issues/6348

**Comment by DomClark** [comment] 2023-09-05 23:09
Perhaps even of #2235 - #6348 is a bit wider in scope and covers other issues that need to be addressed in order to solve this. Either way, this one can be closed as a duplicate.

**Closed by DomClark** 2023-09-05 23:09 UTC
Labels: enhancement
