### ISSUE TITLE
quick palette for user-colors

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2332] opened 2015-09-09 11:27 UTC
This idea is really first interesting, when lmms have user-controlled colors on all blocks in song-editor. Then i think a method to fast color-changes, will enhance workflow
The img is just a **crude** mockup, and this should ofcause be seriously improved -An array 4*4 of tablets would be neat.
I suggest that a right-click in a tablet-field would let user insert a color-through a color-dialog, and left-click let user pick that color for the next block-operation
Mockup
![kvikpalette](https://cloud.githubusercontent.com/assets/6662066/9760568/8a3263ce-56f6-11e5-9f6f-9e6485f772ba.jpg)

**Comment by Wallacoloo** [comment] 2015-09-09 13:54
I don't know about that. Placing too many non-essential controls in the
main toolbar makes things feel a bit overwhelming.

**Comment by Spekular** [comment] 2015-09-09 15:15
Slightly related/tangent:

One idea I've been pondering is to have a palette of preset colors in the
colorize menu and only allow those. If the palette is set through a theme
file, the palette idea is less restrictive, and you'll never open a project
to find that the original artist chose colors that are poorly
fitting/poorly visible in your theme. It also simplifies the menu, and
possibly simplifies storing colors for tons of tracks.

@diizy would address your concerns?

As for how this relates to this issue, you can cherry pick the part where
the palette is in the colorize menu and not the toolbar.

**Comment by tresf** [comment] 2015-09-09 15:47
I would advocate for an auto-rotation of a color palette, similar to what @Spekular describes, and we can leave it off by default.  Letting a user pick a color from the default palette or a custom palette shouldn't be a problem.  If the color is hard to read, they can just change it to a theme-compatible color.

This also can give a quick visual indicator to a mixer channel per something like #1214.

But this is really a duplicate of #1176 and can be consolidated into @Spekular's #1665

**Comment by Spekular** [comment] 2015-09-09 18:34
Alright, @tresf can you close this then?
@musikBear this issue has been/will be consolidated into #1665 as it has to do with user definable colors.

**Closed** 2015-09-09 18:38 UTC

**Comment by tresf** [comment] 2015-09-09 18:55
> @musikBear this issue has been/will be consolidated into #1665 as it has to do with user definable colors.

@Spekular that's your thread.  You should probably add the #XXXX to the appropriate bullet point so we don't loose track of this one.

**Comment by Spekular** [comment] 2015-09-09 19:04
@tresf I have. I said "will be" because it feels odd saying the issue "has been" consolidated when it's still open.

**Comment by tresf** [comment] 2015-09-09 19:24
@Spekular sorry, I thought it would be bundled with "Improving colored tracks"
