### ISSUE TITLE
Crash when clicking "Quantize" in a Piano-Roll with no pattern

### ISSUE THREAD

**Issue by styken** [LMMS/lmms#3608] opened 2017-06-04 13:50 UTC
Reproduce:
1 - open pianoroll
2 - press quantize

**Comment by Texxiliator** [comment] 2017-06-04 13:52
Nothing happens 
atleast for me

**Comment by Texxiliator** [comment] 2017-06-04 13:52
What OS are you using?

**Comment by karmux** [comment] 2017-06-04 13:54
I can reproduce.

**Comment by DeRobyJ** [comment] 2017-06-04 16:13
I cannot reproduce in Windows 8.1 or Windows 7, 64-bit

**Comment by styken** [comment] 2017-06-05 07:50
Do you have an empty roll? I only have the text "Please open a pattern...".
Then I press 'Q' to the left of the scissors.

**Comment by Hussam-Eddin-Alhomsi** [comment] 2017-06-07 13:38
The issue's title should be "Quantizing in Piano-Roll causes a crash.".

**Comment by zonkmachine** [comment] 2017-06-07 21:12
Closed in https://github.com/LMMS/lmms/pull/3609

**Closed by zonkmachine** 2017-06-07 21:12 UTC
Labels: bug, gui
