### ISSUE TITLE
VST research by LMMS

### ISSUE THREAD

**Issue by IMTG-Music** [LMMS/lmms#5473] opened 2020-04-27 13:32 UTC
### Enhancement Summary
VST plugins in a project are saved with their adress on the computer they are used on (Ex : C:/Music/Installed Plugins/PluginName) and that creates issues with VSTs not opening when changing of laptop or when exchanging projects with other producers where VSTs aren't arranged the same. 

An auto research in the folder of work for VSTs could solve that (similar to how FL Studio works)

**Comment by SecondFlight** [comment] 2020-04-27 14:21
I believe this is a duplicate of #4907. Please let me know if you believe this issue is not related.

**Closed by SecondFlight** 2020-04-27 14:21 UTC
Labels: enhancement
