### ISSUE TITLE
SID: tiny delay before note is played

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4113] opened 2018-01-15 20:45 UTC
RC4-6493
win32
There is a tiny DEL(ateting) of a notes initiation, and the actual sound.
Here i show identical notes, played with resp. SID and 3oc'
![sidlack](https://user-images.githubusercontent.com/6662066/34960735-7272d2be-fa3c-11e7-9029-174e639ef044.JPG)

Observe the red marked line.
That is a click at note initiation. 
In 3oc the note plays at that point
In SID it does not

OOP : http://lmms.io/forum/viewtopic.php?f=4&t=26245 with OOP project
Attached : my version with click at note event.
[ISSUE_sid lag demomB.zip](https://github.com/LMMS/lmms/files/1632965/ISSUE_sid.lag.demomB.zip)

**Comment by zonkmachine** [comment] 2019-11-16 20:52
Confirmed. The issue is there already in lmms-1.0.3. I get about 40ms delay.

**Comment by zonkmachine** [comment] 2019-11-16 21:15
There seem to be an updated version of resid ( the software that SID is based on) here:
https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/src/resid/

**Comment by zonkmachine** [comment] 2024-05-23 18:45
Reevaluated

lmms-1.2.2
lmms-1.3.0 d71116b82
![siddelay](https://github.com/LMMS/lmms/assets/6368949/79dcf4cc-865a-4f8f-b922-99cc0887ece9)

There is no longer a delay but the first part, that was cut off earlier, looks a bit off still.
[sidtest.mmp.txt](https://github.com/LMMS/lmms/files/15421189/sidtest.mmp.txt)

**Comment by zonkmachine** [comment] 2024-05-24 21:02
This appears to be fixed. On the last example above, I had extreme settings (fastest attack on all three channels), but this isn't a good way to test SID. It's based on an early 80's computer sound chip that had extreme limitations by today's standards. The issue as reported was fixed. Probably by the move to a new resid source. Closing.

**Closed by zonkmachine** 2024-05-24 21:02 UTC
Labels: bug
