### ISSUE TITLE
route individual preset of 'advanced' vst's to own midi-channels

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5679] opened 2020-09-18 18:58 UTC
## Enhancement Summary 
I cant explain this complexity, but its requested ..
Apparently some VST now can be loaded as *one* instance, but can then play different presets either alone or even as layers, *and* with different midi-note input (!)
The benefit ; You only need to load one instance of a VST, but that ONE instance can play multiple different tracks (!) 😲 with *different* presets of that one VST.
I just want to make a heads-up for something that now is 'hot' in the DAW family 

#### Justification
Its asked for.....

#### Mockup
No.... But a video 
https://www.youtube.com/watch?v=cacS51r7KHk&feature=youtu.be

**Comment by DomClark** [comment] 2020-09-18 21:48
Duplicate of #1178, consolidated into #1472. (Also relevant: #5108.)

**Closed by DomClark** 2020-09-18 21:48 UTC
Labels: enhancement
