### ISSUE TITLE
Preset save load support For effect plugins

### ISSUE THREAD

**Issue by CaBachhav** [LMMS/lmms#5188] opened 2019-09-15 14:26 UTC
The Settings we do on LMMS-bundled-Effect -plugins while making a project must have Preset save load function so that in future it can be reused for diffrent project without losing time

**Comment by DomClark** [comment] 2019-09-15 14:47
Duplicate of #1680.

**Closed by DomClark** 2019-09-15 14:47 UTC

**Comment by CaBachhav** [comment] 2019-09-15 14:58
Look, these same effects also come bundled with ARDOUR DAW , but they have Preset Save-load support . But in LMMS it doesn't.
