### ISSUE TITLE
LMMS seems to crash my whole computer

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1996] opened 2015-04-21 11:31 UTC
It's something I'm expiriencing for a bout a month, using LMMS 1.1.3.
My laptops started to randomy crash every now and then - it violently powers off without any warning.

Hadware: ASUS K52Jc laptop.
Software: KX Studio 14.04 64-bit

    uname -a Linux unfa-K52Jc 3.13.0-48-lowlatency #80-Ubuntu SMP PREEMPT Thu Mar 12 11:33:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I tried logging dmesg kernel buffer t catch something that occurs directly before the crash, to no avail.
The only trace I have is that everytime the crash occurs, I have LMMS running. It seems to never happen when LMMS is not running. However I made a stress test, opened many intances of LMMS and made it eat 100% CPU and it was running for an hour like that with no crash whatsoever.

I though first that it's related to overheating, but my laptop was working more than 15 hours of 100% usage and 98~100°C on the CPU rendering animations with Blender with not a single crash, while when running LMMS it happened to crash 5 times in one session (about 8 hours).

I also suspected a buggy webcam driver, as the crashes occured most frequently when I was on a video call via qTox. However the system crashes with no videcalls too.

This makes me want to buy a new computer, becasue I can't relay on this setup for live music performance with LMMS, and it gets very frustrating when I work on something and randomly my whole computer just powers off.

Please let me know if anybody have had similar experiences and if I can do anything to get this riddle solved. 

I wonder if anyone has similar

**Comment by mikobuntu** [comment] 2015-04-21 12:36
I found my problem with crashes was due to mainly distribution upgrading from ubuntu-12.04 to ubuntu-14.04, this really bugged out my .xorg
files or some driver or who knows what else ..., now since clean installing 14.04 I have not had 1 single crash. I was blaming my audio apps at the time, but I guess it may have been down to the fact that I use audio apps including LMMS more frequently than anything else on my system.
thanks Mikobuntu ;)



I wonder if anyone has similar

**Comment by unfa** [comment] 2015-04-21 14:36
I'm waiting for new KX Studio live-DVD release to install a clean system, but well, this isn't really a solution to anything, just a way to escape the problem.

**Comment by mikobuntu** [comment] 2015-04-21 14:51
yeah I agree Unfa, it is sometimes the only way whenever your system gets into an unstable state.
I'm sure you have already checked the numerous /var/log/* files for possible culprits to your problem? 

thanks Mikobuntu ;)


Date: Tue, 21 Apr 2015 07:36:03 -0700

**Comment by tresf** [comment] 2015-04-21 15:46
> this isn't really a solution to anything, just a way to escape the problem

This is just a classic problem with open source.  There's no possible way anyone can reasonably account for all libraries everywhere all on their own.

So proper troubleshooting would require finding libraries that are loaded at the start of every application and looking for ones that might be misplaced or left over from an upgrade.

When that effort is compared against the time it takes to simply reinstall the OS, its a pretty easy decision for an individual.

You're correct, it helps no one but yourself, but then again... you're on an LMMS bug tracker talking about system instabilities... so we're a bit out of context from the start. :)

**Comment by tresf** [comment] 2015-04-24 12:52
Closing as invalid as no one can reproduce.  Please feel free to reopen this at a later time if you have steps to reproduce.

**Closed by tresf** 2015-04-24 12:52 UTC
