### ISSUE TITLE
Importing Some MIDI Files Crashes at 66%

### ISSUE THREAD

**Issue by ethanicus** [LMMS/lmms#2444] opened 2015-11-15 04:24 UTC
So basically, I open LMMS, clear everything from the default project, import a MIDI file, and it gets to 66% before just sitting there and not doing anything.
This only happens with some files. About half of the ones I try work. It doesn't seem dependant on length or complexity. It appears random.

I'm running Windows 10 on a laptop with 4GB RAM.

**Comment by michaelgregorius** [comment] 2015-11-15 09:49
@ethanicus Can you please provide an example file that makes LMMS hang? We've fixed some MIDI problems several months ago and it might be that your problem is already fixed in the current version of the code (master). Thanks!

**Comment by tresf** [comment] 2015-11-15 15:43
Agreed.  Duplicate of #972, #1971, #1544 but the fix has not yet been made available for a stable release, so it will be addressed with 1.2.

As @michaelgregorius mentioned, please provide a MIDI file so that we can reproduce.  If you are not sure where to attach it, send it to support@lmms.io and we'll get it hosted and cross-linked for you.

**Comment by ethanicus** [comment] 2015-11-16 00:19
I can't attach the file here, so I'll email it.

**Comment by michaelgregorius** [comment] 2015-11-26 17:57
Did the file get mailed yet?

**Comment by ethanicus** [comment] 2015-11-26 19:28
Yes, I sent it a while ago. Did it not get received?

**Comment by michaelgregorius** [comment] 2015-11-26 20:04
@tresf Did you receive the file?

**Comment by DeRobyJ** [comment] 2015-11-27 10:42
I just sent one that doesn't import on my system.
Also, it stops at 23%, not at 66%.

**Comment by musikBear** [comment] 2015-11-27 16:47
@DeRobyJ -can you upload on lsp?
* Does it load in anvil or similar midi playing programs 
* Can FLdemo (or similar)  import it?

**Comment by tresf** [comment] 2015-11-28 02:43
> @tresf Did you receive the file?

@michaelgregorius, no, but I got @DeRobyJ's via email.  Here it is: [link (drive.google.com)](https://drive.google.com/file/d/0B4PpvIwHd1U0UE1lZ3hkazdqeFE/view?usp=sharing)

**Comment by tresf** [comment] 2015-11-28 04:34
> @DeRobyJ -can you upload on lsp?

@musikBear FYI, LSP doesn't support midi currently.

> Valid LSP Types:
 * .xpf
 * .wav
 * .ogg
 * .mmp
 * .mmpz
 * .png
 * .jpg
 * .tar.gz
 * .tar.bz2

**Comment by michaelgregorius** [comment] 2015-11-28 10:49
@DeRobyJ Your file can be successfully imported in master (3e03e716ff9c2cfd501a5c7764f0edfb65c46d7d). So the problem should be fixed with the next release.

@ethanicus Did you send the file to the address that @tresf provided (support@lmms.io)? Can you please send the file again? Thanks!

**Comment by Umcaruje** [comment] 2015-12-14 23:50
@ethanicus please send the file to the provided email address or upload the file to a service like dropbbox, or I'm afraid this issue will need to be closed.

**Comment by Umcaruje** [comment] 2016-01-13 18:29
No response in 29 days, closing. @ethanicus if you send the file and if it hangs on import in master, I will reopen the issue.

**Closed by Umcaruje** 2016-01-13 18:29 UTC
