### ISSUE TITLE
Open source code for both time-stretching and sampler

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5506] opened 2020-05-17 11:17 UTC
### Enhancement Summary
Found this site https://github.com/openAVproductions/
There is Open source code for both time-stretching and a sampler.
Surely something that could be useful.
I am not smart enough to tackle neither 
#### Justification
We need both
#### Mockup
no

**Comment by SecondFlight** [comment] 2020-05-18 15:57
Could this instead be a comment on #1734 / #3103 / #5474 / etc? I'm tempted to close this as a duplicate of #1734 as time stretching isn't a new request.

**Comment by zonkmachine** [comment] 2020-05-18 16:28
^This. And also, prior to this you should consider bringing it up in discord #techtalk. And if you do, please link to the actual software and not a general page with many different links that most are irrelevant. Feel free to continue the discussion here. Closing.

PS. Precisely what licenses are we talking about?

**Closed by zonkmachine** 2020-05-18 16:28 UTC
Labels: enhancement

**Comment by musikBear** [comment] 2020-05-19 19:55
> Could this instead be a comment on #1734 / #3103 / #5474 / etc?

yes, perhaps a consolidation on everything sample-stretching ?

@zonkmachine -You are correct, i have not looked at license, that is important
