### ISSUE TITLE
Hang-note in zasfx

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5220] opened 2019-10-04 12:51 UTC
win10 1.2.0 
First you should watch this:
https://youtu.be/Jx7jCNv4lAI
The behaviour was initiated as a arpeggio on E3 was playing, so i first found related to  #320. @DomClark mean it is a different issue, and asks  for a new bug-report -This is he....
Here is the file ZASFX_HangNoteProblem.zip
[ZASFX_HangNoteProblem.zip](https://github.com/LMMS/lmms/files/3690580/ZASFX_HangNoteProblem.zip)

Recreate:
It is the note E3 that creates the hang. The arpeggio caused the issue, but arpeggio -replay is not mandatory to invoke the fail.
Just press E3, and that note hangs
Arpeggio' relation is only by chance: E3 is 'pressed' in the arpeggio sequence, and that the initiate the hang.
The Hang is terminated if:
* Show-Gui button is pressed
* Panic-button inside xasfx is pressed

The Hang is however not fixed. It returns if E3 is re-pressed. 
I have tested on win1.2.0 and a Master ( 1.2.0RC7.263 ) Both with the bug, but in Master, only after 2. replay. To me that could indicate some kind of un-precise arpeggio termination signal for the note, but why then is the bug present as soon as E3 is pressed?

**Comment by musikBear** [comment] 2019-10-21 20:17
Has anyone worked on zasfx in 1.2.1 ?
This bug has disappeared!
I cant initiate this hang in 1.2.1 <3
It may be too soon to go *Hoorayy* yet, but i looks like 1.2.1 have this fixed. It is not mentioned in the releasenotes, that any work has been done on zasfx, so this could be a lucky strike
@DomClark Can you confirm?

**Comment by DomClark** [comment] 2019-10-24 20:43
I can't reproduce it in 1.2.1, although I found it difficult to reproduce in 1.2.0 so it may just be that I haven't managed to trigger it yet. However, since you could reproduce it reliably, and now you can't, I'll assume it's fixed and close this issue for now. We can reopen it later if the bug reappears.

**Closed by DomClark** 2019-10-24 20:43 UTC
Labels: bug
