### ISSUE TITLE
Triple oscillator not working from rc2.9.

### ISSUE THREAD

**Issue by bieltoni** [LMMS/lmms#3292] opened 2017-01-24 19:13 UTC
When a track with a tripleoscillator is played, a sound distorsion occurs. I have compiled different versions of lmms to determine from which the problem occurs and the rc2.8 version works correctly. From the version rc2.9 the tripleoscilator stops working correctly.

Debian 8 x64  with KXStudio repositories.

**Comment by bieltoni** [comment] 2017-01-26 22:13
The problem occurs when you play the Triple Oscillator within the song editor. It seems as if buffers information gets corrupted.

**Comment by BaraMGB** [comment] 2017-01-26 23:27
Can you provide a video, please?

**Comment by BaraMGB** [comment] 2017-01-27 14:23
Theres definitely something wrong. I can reproduce it when TripleOSC playes with kicker together and TripleOSC has a OSC with sawwave. Then the sound stops and the peak of 3OSC goes to max.

I guess it's something with: https://github.com/LMMS/lmms/pull/3145

**Comment by michaelgregorius** [comment] 2017-01-27 18:24
@BaraMGB Can you provide a small project that can be used to reproduce the problem? Thanks!

**Comment by musikBear** [comment] 2017-01-28 12:46
What OS are this relevant for?
I have tested RC2.8 on win32
I cant reproduce this bug, No matter what saw-osc (1-3) or wheater or not the kicker is in B&B or song-editor, there is no loss of either 3oc or kicker notes over 3 octaves

If any track is muted in the problem project then, Couldent this be the 'silenced B&B-track' bug?

File: https://lmms.io/lsp/?action=show&file=10214

**Comment by bieltoni** [comment] 2017-01-29 00:36
@BaraMGB Here is another test file.
https://lmms.io/lsp/?action=show&file=10220

A video where it works correctly
https://youtu.be/n_rDyxVusBQ

And a video with the latest version of LMMS with the bug. I hope it helps.
My system is a Debian 8 64bit.
https://youtu.be/Ch8JZ4uMCRY

**Comment by michaelgregorius** [comment] 2017-01-29 10:01
I have tested with https://lmms.io/lsp/?action=show&file=10220 and also with "Surrender-Main" from the "shorties" files and here are some more findings:
* The bug seems to be more likely to occur in release builds.
* The bug seems to be only triggered when several channels are in active use.
* Related to the previous observation: If you solo a problematic channel the problem goes away but comes back if you unsolo the channel.

**Comment by michaelgregorius** [comment] 2017-02-04 12:16
I have reverted the changes from #3145 with commit cf26da330c2ac5c0fce5069a4f469bed60536dbb. However, due to the symptoms described above I think it's rather a problem with the mixing and multithreading. The fact that soloing a Triple Oscillator makes the problem go away and yields correct sound also seems to indicate that there is nothing wrong with the computation of the audio and the update of the phase information. But as we are in an RC phase right now I guess it's better to revert the changes.

@bieltoni Can you please check if the bug is solved once there is a newer RC available? Please only close this ticket if you find that it's solved. Thanks!

**Comment by BaraMGB** [comment] 2017-02-12 13:01
For me the issue seems fixed.

**Comment by musikBear** [comment] 2017-02-13 17:08
It would be a big setback, if the off-phase behaviour is re-instated.
The post 3145 3oc (as in RC2.8) is a significantly better instrument -

**Comment by bieltoni** [comment] 2017-02-13 23:22
@michaelgregorius I have check in a new system (build in Debian 9 without KXStudio sources) and the last git version, works perfect.

**Closed** 2017-02-13 23:29 UTC
