### ISSUE TITLE
Allow renaming BB Tracks inside BB Editor

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#681] opened 2014-05-04 12:55 UTC
For all ver. afair this has been somewhat weird. If a user creates a new BB-line inside BB-editor, it is not possible to name the BB-track. The user need to go to song-editor, find the new track there, and rename it. I think there should be a naming option when the track is created. (low->medium  prio)

**Comment by Umcaruje** [comment] 2015-06-29 16:54
Duplicate of #2014

**Closed by Umcaruje** 2015-06-29 16:54 UTC
Labels: duplicate
