### ISSUE TITLE
White Theme

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4621] opened 2018-09-26 13:13 UTC
I have prepared a White Theme for visually impaired people who need a White Theme. But, there are some issues with this theme, which I am not able to solve. I have strained my eyes and I am unable to carry on with this. So, if someone wants to develop this theme further, they can do so. Here are the screenshots:

![white theme](https://user-images.githubusercontent.com/40867393/46081935-69a0ef80-c1bb-11e8-9040-04e90263971a.png)

SONG EDITOR:
(ISSUE: I don't know how to change the colour of the text (white colour text, Eg: Tempo BPM) on the main toolbar, to black colour. The same goes for the text inside the settings window.)
![song editor](https://user-images.githubusercontent.com/40867393/46082010-96ed9d80-c1bb-11e8-8b12-dee9078733cb.png)

PIANO ROLL:
(ISSUE: Small grids cannot be seen on the darker shades. I did try changing colours but it seems to be something different. And I don't know how to change the colour of the 'marker')
![piano roll](https://user-images.githubusercontent.com/40867393/46082038-a79e1380-c1bb-11e8-95cf-4ada183aa5b0.png)

AUTOMATION EDITOR:
![automation editor](https://user-images.githubusercontent.com/40867393/46082049-b4bb0280-c1bb-11e8-800f-07a0cc939c12.png)

PROJECT NOTES:
ISSUE: I want the text in the Project Notes to be black (with white background), but I don't know where to make the changes. The text is white and the background is also white, so it is unusable

Here's the Theme file:
[White JBN.zip](https://github.com/LMMS/lmms/files/2419808/White.JBN.zip)

**Comment by AndiEcker** [comment] 2018-09-26 14:53
+10 - awesome theme - I really love it <3 - thanks for your great
contribution!!!!

Only the red frames around the effects (in the Effects Chain part of the FX
Mixer window), the EQ window (in the first screenshot) and the instrument
plug-ins (in the 2nd screenshot) would look better IMO when they were in a
greyish colour instead.

Am Mi., 26. Sep. 2018 um 14:14 Uhr schrieb jibin1573 <
notifications@github.com>:

**Comment by jibin1573** [comment] 2018-09-26 15:19
Thanks @AndiEcker! I am fully aware that grey is better for this theme, but I have chosen red for for the visually impaired, for better contrast.

**Comment by tresf** [comment] 2018-09-29 17:10
Not a bug or an enhancement as far as I can see.  We aren't currently accepting any themes into our base code at this time, but the work looks great.  People can refer to this bug report as needed.  Closing as there's nothing the LMMS project has to do on this theme (but rather a community effort).

**Closed by tresf** 2018-09-29 17:10 UTC
