### ISSUE TITLE
MIDI port for multiinstruments VST

### ISSUE THREAD

**Issue by Quentin-CORBET** [LMMS/lmms#6139] opened 2021-08-22 05:26 UTC
MIDI port for VST like edirol orchestra with multiinstruments to use 1 VST for 16 tracks and save a lot of RAM
this feature can be very useful

**Comment by Spekular** [comment] 2021-08-22 05:41
Duplicate of #1178, which is consolidated into #1472.

**Closed by Spekular** 2021-08-22 05:41 UTC
Labels: enhancement
