### ISSUE TITLE
Error when opening file from recent menu

### ISSUE THREAD

**Issue by Atherz97** [LMMS/lmms#3089] opened 2016-10-25 16:53 UTC
"Could not open file /&home/atherz/lmms/projects/music.mmpz"

Seems like a random & appears in the file path when clicking on a file from Recently Open Projects in the File Menu. It's fine when clicking on a project file from the file manager or from the Open Menu.

Running LMMS 1.1.90.428 on Manjaro Linux 64-bit

**Comment by zonkmachine** [comment] 2016-10-25 17:46
Does this happen with all files in the Recently Opened Projects?
Does this happen if you choose use the "Reopen last project on start" in the Settings and restart LMMS?
Do you use another language than the default?

**Comment by Atherz97** [comment] 2016-10-25 22:23
Yes, it happens with all files in that menu. It doesn't happen when that setting is enabled, only when opening from the recently opened menu. And I use the default language.

I just found out though that the & symbol position is tied to which project in the list I choose. Here's a quick video (prior to this, all I did was start up LMMS):
https://dl.dropboxusercontent.com/u/40054022/2016-10-25%2018-18-53.mp4

**Comment by tresf** [comment] 2016-10-26 00:26
Looks like the mnemonic/accelerator flag is being set (e.g. ALT + Shortcut).  Is the OS doing this or is Qt doing this or is our code doing this?  I don't see it in my OSs.

**Comment by BaraMGB** [comment] 2016-10-26 09:08
@Atherz97 is that & char in your username of your OS?

**Comment by Umcaruje** [comment] 2016-11-08 20:10
I also can't reproduce this on elementary os Loki. Weird.

**Comment by tresf** [comment] 2016-11-08 20:47
> Is the OS doing this or is Qt doing this or is our code doing this? I don't see it in my OSs.

Qt is doing it.  This is an [upstream bug](https://bugreports.qt.io/browse/QTBUG-41976) which affected Qt 5.4 has since been fixed.  Marking as "not our bug".

If this still occurs after upgrading to Qt 5.4-RC or higher (e.g. 5.7) I would recommend escalating with the Qt team.

@Atherz97 if you can confirm that upgrading Qt solves this problem, please mark this as resolved.

**Comment by liushuyu** [comment] 2016-11-08 20:52
>If this still occurs after upgrading to Qt 5.4-RC or higher (e.g. 5.7) I would recommend escalating with the Qt team.

No, I compiled LMMS with Qt 5.7, it seems like I can exactly reproduce the same issue

**Comment by tresf** [comment] 2016-11-08 21:02
Ok... still upstream then, different bug:

http://stackoverflow.com/a/32711483/3196753
https://bugs.kde.org/show_bug.cgi?id=337491

**Comment by PhysSong** [comment] 2017-11-26 06:17
Fixed in #3872.

**Closed by PhysSong** 2017-11-26 06:17 UTC
Labels: not our bug
