### ISSUE TITLE
LMMS startup several times slower on master branch

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#4879] opened 2019-03-09 10:08 UTC
In the same system (Manjaro Linux) and using same settings LMMS master starts up several times slower than LMMS 1.2. It gets stuck at "Preparing UI" for very long.

**Comment by tresf** [comment] 2019-03-09 17:03
@karmux hmm... one major change that I see on `master` is that it uses the Qt resource system to load stuff like pixmaps/embedded content, but this is just a guess. 
 https://github.com/LMMS/lmms/commit/9f905bce3eee4e24a2338d9d8a104af6bdbec8ad.  Is there a chance you can help locate the responsible commit(s)?

**Comment by tresf** [comment] 2019-03-09 17:11
FYI, building `master` on macOS I don't see the delay that's being described on startup.

**Comment by karmux** [comment] 2019-03-09 22:15
When I moved away huge amount of Massive presets from `presets` directory then master started to load as fast as 1.2 which loads even faster now.

**Comment by JohannesLorenz** [comment] 2019-03-17 23:14
Confirmed. Running callgrind, I get that it's the calls of `QTreeWidgetItem::setExpanded` inside `FileBrowser::expandItems`. Which I find strange, it's just a GUI operation.

`QTreeWidgetItem::setExpanded` calls `QTreeWidgetItem::expand`. Behind that, I can't see what it's calling next.

**Comment by JohannesLorenz** [comment] 2019-03-18 20:52
The mentioned functions are called equal times in master and in stable-1.2, I just checked it.

Maybe there is a reason they are faster/slower, e.g. they are temporarily not visible in stable-1.2, reducing computation times of the graphics. Just guessing...

**Comment by tresf** [comment] 2019-05-30 21:04
> one major change that I see on master is that it uses the Qt resource system to load stuff like pixmaps/embedded content, but this is just a guess (9f905bc). 

Found a bug... Unsure if it's related...

```diff
QPixmap getIconPixmap(const QString& pixmapName,
	int width, int height, const char** xpm )
{
	QString cacheName;
	if (width > 0 && height > 0)
	{
-		cacheName = QString("%1_%2_%3").arg(pixmapName, width, height);
+		cacheName = QString("%1_%2_%3").arg(pixmapName).arg(width).arg(height);
	}
```

Qt thinks you're using one of the [less-common `.arg(...)` calls](https://doc.qt.io/qt-5/qstring.html#arg) and starts doing weird stuff like `"project_open_%2_%3"`.

Fixing the args produces: `project_open_16_16` instead.

@lukas-w FYI.

**Comment by JohannesLorenz** [comment] 2019-05-31 09:20
> Found a bug... Unsure if it's related...

Unfortunatelly not. It's still slow when I apply those changes.

**Comment by JohannesLorenz** [comment] 2020-01-18 21:47
Assuming this issue is in `src/gui/FileBrowser.cpp`, I only see two commits that may have caused it:

* 1b24a0520dfce99f3dac6e3112867d9d19534cc5 - from michaelgregorius (the only line that *may* cause this problem could be `m_fileBrowserTreeWidget = new FileBrowserTreeWidget( contentParent() )`);
* 674a2fb50c36264dc0f06b4d4736dfabf3077fba - from @karmux 

Karmux, when you wrote commit 674a2fb, would you have noticed the issue (which would mean your commit wouldn't have caused it)? If you revert the changes from 674a2fb (or 1b24a05) manually on master, does it get faster?

**Comment by karmux** [comment] 2020-01-19 12:19
@JohannesLorenz I can confirm that my https://github.com/LMMS/lmms/commit/674a2fb50c36264dc0f06b4d4736dfabf3077fba caused that.

Removing `expandItems();` from `FileBrowser::reloadTree` makes LMMS to not spend few extra seconds at reloading the tree but that breaks filtering again.

It gets noticeably slower only if you have tens of thousands of files in LMMS working directory.

**Comment by LostRobotMusic** [comment] 2023-09-23 16:47
This was partially fixed with #6738.

**Comment by Rossmaxx** [comment] 2024-04-14 00:27
Looks like @sakertooth did something related to this issue. Did this get fixed?

**Comment by Rossmaxx** [comment] 2024-06-29 06:18
I asked saker on discord. This is what he said:

> Me and some others did a bit with `FileBrowser`. Might've been fixed in either #6996, #6985, #6738, or #6721.

@karmux can you check now?

**Comment by Rossmaxx** [comment] 2024-06-29 07:33
I'll close this if there's no response within a week.

**Comment by LostRobotMusic** [comment] 2024-06-29 13:39
It can be closed now.  The ridiculously long load times was due to the file browser very inefficiently loading in all of the files at startup.  The mentioned PRs first sped this up significantly and then removed it entirely.

**Closed by LostRobotMusic** 2024-06-29 13:39 UTC
Labels: performance
