### ISSUE TITLE
crash in QObject::~QObject() while using zynaddsubfx plugin

### ISSUE THREAD

**Issue by lleroy** [LMMS/lmms#2219] opened 2015-07-27 14:15 UTC
I see frequent crashes inside zynaddsubfx, more specificly in QObject::~QObject()

I think this is because the compiler is confusing the class "Engine" defined in 
           (1) lmms/include/Engine.h
with the one in
           (2) lmms/plugins/zynaddsubfx/zynaddsubfx/src/Nio/Engine.h

the plugin is deleting an object of type Engine(2), which is not a descendant of QObject,
but the compiler thinks it is and Engine(1).

I think Engine(1) should be renamed or put inside a namespace ...

**Comment by tresf** [comment] 2015-07-27 14:21
Duplicate of #2049 #2088

**Closed by tresf** 2015-07-27 14:21 UTC
