### ISSUE TITLE
Ghost bases bug

### ISSUE THREAD

**Issue by SirStarstorm** [LMMS/lmms#4033] opened 2017-12-04 19:19 UTC
Lately, this bug is happening to me a _LOT_.
I erase a base and the sound of the track continues to play, and when I save the track, the base returns to where it was. In this situation I have to start a new track. I don't know what triggers it.
Somebody knows how to fix it, or at least how to avoid it?

**Comment by PhysSong** [comment] 2017-12-04 23:04
- Which version of LMMS do you use?
- What does the `base` mean?

**Comment by musikBear** [comment] 2017-12-05 15:37
please post your:
* OS (+service-pack-version)
* lmms version
* lmms sound device chosen
* lmms instrument involved
* lmms preset (if a factory preset is used)
* a demo mmp
Best place for support-requests is forum
http://lmms.io/forum/
Devs has *plenty* to do with bugs..

**Comment by PhysSong** [comment] 2017-12-09 07:49
Closing as a duplicate of #2306

**Closed by PhysSong** 2017-12-09 07:49 UTC
