### ISSUE TITLE
Allow adjacent blocks in the same track to be combined

### ISSUE THREAD

**Issue by overcast07** [LMMS/lmms#5424] opened 2020-03-22 19:38 UTC
### Enhancement Summary
Right now, there isn't a way to merge blocks that are next to each other.

#### Justification
Currently, the action is indirectly possible, but only for some tracks. It's possible for melody tracks, but it requires notes to be cut, pasted and shifted (which would obviously take longer). It isn't possible for automation tracks because copying and pasting aren't possible in the automation editor.

The action is possible in other DAWs.

#### Mockup
Picture, if you will, a context menu button with the label "Combine".

It could be possible to make this a single-click action in the Song-Editor, but this would require more work to design and implement.

**Comment by Spekular** [comment] 2020-03-22 19:53
Duplicate of #3633

**Closed by Spekular** 2020-03-22 19:53 UTC
Labels: enhancement
