### ISSUE TITLE
Audiofileprocessor Sample Bug

### ISSUE THREAD

**Issue by CaitlinChoban** [LMMS/lmms#3494] opened 2017-04-08 17:55 UTC
I have found whenever i save a project, upload samples in audiofileprocessor, and then shut down my computer that the samples listed in audiofileprocessor are not there. 

Say there is a 5s sample i upload into audiofileprocessor called outside clap. When i save the file, the next time i load the project. Audiofileprocessor will say that there is a sample loaded as outside clap, but the sample length is 0s.

Sometimes this happens (there will be silence where there is suppose to be a sample) and other times it will not and i can hear all of my samples.

**Comment by tresf** [comment] 2017-04-08 18:19
@CaitlinChoban this sounds similar to https://github.com/LMMS/lmms/issues/3491.  Is the issue the same?

**Comment by JordanKyser** [comment] 2017-04-08 20:45
This is the same problem

@CaitlinChoban Do you use LMMS 1.2.0-rc2?

**Comment by tresf** [comment] 2017-04-22 22:19
@CaitlinChoban if you can clarify if this is a duplicate of #3491 that would be appreciated.

**Comment by CaitlinChoban** [comment] 2017-05-17 18:11
I use LMMS 1.1.3 on Windows 8 64bit that i downloaded from the LMMS website. 
I looked at 3491. It is not a duplicate, but similar. They were talk about .mmp or .mmpz files being autodetected and an error coming up. I'm guessing from the middle left column that has my projects, my samples, my presets (audiofileprocessor) etc.
I don't get an error, i just get silence where there should be a sample (sound).

My issue was that i would load WAV samples (of my environment) i recorded from a phone mic onto audiofileprocessor. When i saved the whole project file and then opened it again, the name of the WAV samples would be in the audiofileprocessor. But there would be no sound and it would say 0s for the sample length. This happened a few times. I would have to reload my samples onto the audiofileprocessor plugin to hear anything. But i have not seen any more problems with this since i first wrote about this bug.

**Comment by musikBear** [comment] 2017-05-18 15:01
>  I would have to reload my samples onto the audiofileprocessor plugin to hear anything

Was/ are those samples placed in the folder **mySamples**, and properly linked to in **Settings**?
If i understand you correctly, the issue is gone?

**Comment by CaitlinChoban** [comment] 2017-05-25 18:54
They were not linked in my settings at the time. However i did do that recently when I was referencing the manual. So they are now. 
The issue seems to be gone. i still have not had any more problems with audiofileprocessor.

**Comment by tresf** [comment] 2017-05-26 04:54
> The issue seems to be gone. i still have not had any more problems with audiofileprocessor

Thanks for the update.  Closing as `invalid`.  Please request a reopen if the issue reoccurs.

**Closed by tresf** 2017-05-26 04:54 UTC
Labels: needs clarification
