### ISSUE TITLE
removing a Beat-Bass-line track in song-editor deletes BB-notes

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2350] opened 2015-09-14 12:36 UTC
if user deletes a BB-track in song-editor, all notes in that BB-editor-track is lost.

**Comment by tresf** [comment] 2015-09-14 12:57
Agreed.  Title, description and formatting of this bug report require cleanup, but the severity of deleting a BB track is not intuitive nor expected by the initial user. Related #453 #454

**Comment by musikBear** [comment] 2015-09-15 14:17
i did not write this as **bug report** at all - there is no bug. This is entirely workflow and user expectations. Not a bug.

**Comment by tresf** [comment] 2015-09-15 14:53
>  bug report

It's a generic term, get over it.

**Comment by tresf** [comment] 2015-09-15 14:54
P.S. Please clean this up as requested or it will be closed.

**Comment by Spekular** [comment] 2015-09-15 20:37
I'm assuming you're talking about how deleting an instrument from one BB-pattern deletes it from the rest?

* If action X cannot be undone, it is *irreversible*. Action X will be *irreversibly* performed
* Unless you're stretching an essay to a word limit,  phrases like "rather huge" can be shortened to "huge". Yes, I occasionally do this sometimes
* A comma is a pause about as long as one breath. I don't think it makes sense to pause between "message for bb-track" and "may not be possible"
* There's no space between the end of a sentence and punctuation, but there is one after punctuation and before the start of a sentence
* In text you shouldn't start a sentence with "and" or "but", and I've never heard of a sentence starting with "-"
* I just had to go back and fix the spelling of sentence, since I tend to write sentance. I also removed some extraneous words. Even short messages go from first draft to final, reread, review, and fix things, it saves the people who care to read your message time and effort. It's still far from perfect both objectively and subjectively
* Punctuation and structure are thrown almost entirely out the window in the last half of your post. Maybe it'd ve better with "big disaster PERIOD", "Perhaps something like COLON", "QUOTATION MARKS Remove this tracks and ..."

This isn't meant to be patronizing or rude, and I'm not an english teacher or anything, but I think these bullet points would at least bring this report in the right direction and might be useful for later ones.

Maybe the next person can critique my writing, and the next theirs, and so on forever until we're an english forum ;)

**Comment by jackokring** [comment] 2015-11-21 21:59
I just tried this to see. I would say yes it is a bit surprising, but no it is avoidable when known. My preferred 'solution' would be to keep the data, mute the track, and make the track invisible in the song editor. A unmute/revisible button in the editor would facilitate this understanding, and allow fast restoring.

As to removing a track in the BB editor would work similar. An invisibles purge with a yes/no dialog on the tools menu would then be most fine.

**Comment by grejppi** [comment] 2015-11-21 22:12
When you delete an instrument track in the song editor, all its notes are lost. Why should B&B tracks be any different?

**Comment by tresf** [comment] 2015-11-21 22:32
@jackokring Not sure how much of the thread you've read, but the proposal I would make is here: https://github.com/LMMS/lmms/issues/453

From a resource perspective, laserblade makes a valid point here:  https://github.com/LMMS/lmms/issues/453#issuecomment-37607786

From a usability opinion perspective, diizy makes some of his points heard here:  https://github.com/LMMS/lmms/issues/453#issuecomment-37620289

A compromise between all solutions is a feature to hide tracks individually combined with a warning message when a deleted track has dependencies in other BBEditor tracks.  This "compromise" solution would probably be quicker to implement as well.

-Tres

**Comment by jackokring** [comment] 2015-11-21 23:33
All notes lost is bad if unexpected. My proposal was to put all virtually deleted tracks in a drop down off a recycling icon (one icon per editor), such that they could be restored easily, or much later in the production. It would likely need a purge some how, and this should be global.

How do you do a #453 mention, or did it just happen?

**Comment by tresf** [comment] 2018-03-06 22:50
This is really an undo nuance -- or -- a siloe'd BB Editor enhancement.  It's not a bug currently, but it'll continue to be a talking point until the behavior is improved.  Closing.

**Closed by tresf** 2018-03-06 22:50 UTC
Labels: needs clarification
