### ISSUE TITLE
Opening Settings dialog causes LMMS to crash

### ISSUE THREAD

**Issue by tukkek** [LMMS/lmms#4203] opened 2018-03-01 01:28 UTC
Console output:

> ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
> ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
> /tmp/.mount_lmms-1FYFFbO/usr/bin/lmms.real: symbol lookup error: /tmp/.mount_lmms-1FYFFbO/usr/lib/libportaudio.so.2: undefined symbol: jack_client_open

Reproducing is as simple as opening LMMS, going to Edit and clicking Preferences. Using `1.2.0-rc5`.

**Comment by tresf** [comment] 2018-03-01 01:32
@tukkek can you test with this installer?  https://github.com/tresf/lmms/releases/download/v1.2.0-rc4/lmms-1.2.0-rc4.207-linux-x86_64.AppImage

Please pardon the incorrect version number, it is in fact RC5-based.

This may be a duplicate of #4094.

**Comment by tukkek** [comment] 2018-03-01 01:44
Yes, this AppImage version seems to work fine.

**Comment by tresf** [comment] 2018-03-01 01:50
@tukkek thanks.  Closing as duplicate of #4094.

**Closed by tresf** 2018-03-01 01:50 UTC
Labels: duplicate
