### ISSUE TITLE
MIDI Export does not export Instruments from SF2 Plugin

### ISSUE THREAD

**Issue by mrdlink** [LMMS/lmms#5422] opened 2020-03-18 21:19 UTC
I composed some music with only SF2 instruments. I then want to export the project to MIDI format. But when I load the MIDI file in any program, all the instruments are set to "piano" somehow. But the referenced soundfont is correct. Only the instruments are missing.
I expect the MIDI export to save the correct instrument mapping for the used soundfont.

I use version 1.2.1 of LMMS.

[testexport.zip](https://github.com/LMMS/lmms/files/4351418/testexport.zip)

**Comment by musikBear** [comment] 2020-03-19 12:56
MIDI-_export_ does not work. Everything is garbled together in one track, and indeed as you say, as _grand-piano_

**Comment by SecondFlight** [comment] 2020-03-19 14:13
I'm closing this as a duplicate of #5198. If you feel this issue covers something that #5198 does not, please let me know.

This is a known issue, just not fixed. As always, we will gladly accept a PR that fixes the issue.

**Closed by SecondFlight** 2020-03-19 14:13 UTC
Labels: bug
