### ISSUE TITLE
better Instrument picker

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1748] opened 2015-02-07 16:24 UTC
LMMS needs Better Instrument picker like the fx picker where it can see vst so you can open like lmms Instruments so you don't need the VeSTige. pluginin to open a vsti ie they open just like limms Instrument  .
![capture](https://cloud.githubusercontent.com/assets/8137561/5986514/f2866676-a8c0-11e4-8b62-fecf14f22640.PNG)

Chage the VeSTige plugin tab to key rage & preset manager and add env lfo tab and keep all other tabs like you have.

FL Studio
![capture](https://cloud.githubusercontent.com/assets/8137561/5986626/e94453c6-a8c4-11e4-8521-c097bce23697.PNG) 

![capture2](https://cloud.githubusercontent.com/assets/8137561/5986628/249d7308-a8c5-11e4-8079-a4bf836dde24.PNG)

you can keep the vst icon for tracks.

Here is a better Instrument picker
![better instrument picker](https://cloud.githubusercontent.com/assets/8137561/6092769/7c92cdb2-aeb3-11e4-9fba-931f44a6cb34.PNG)

when you need to Search for a vst click Search .

Search Box
![search box](https://cloud.githubusercontent.com/assets/8137561/6092777/405fb228-aeb4-11e4-8202-0d9c8fd3e757.PNG)

**Comment by Sti2nd** [comment] 2015-02-07 18:02
Well that is simply not how LMMS works, they must be opened through VeSTige, and some crucial features is currently only possible through the VeSTige GUI. Interesting idea of populating the instrument plugin side bar with VST instruments

**Comment by tresf** [comment] 2015-02-07 19:19
Duplicate of #1729.

If you can answer the questions there, please reopen.  Don't intentionally create identical bug reports please.

**Closed by tresf** 2015-02-07 19:19 UTC
Labels: duplicate

**Comment by Reaper10** [comment] 2015-02-07 19:27
how do I do that

**Comment by tresf** [comment] 2015-02-07 19:34
> how do I do that

How do you do what exactly?  Answer the question in #1729, reopen, or stop creating duplicate reports? :wink:

**Comment by Reaper10** [comment] 2015-02-07 19:41
reopen

**Comment by tresf** [comment] 2015-02-07 19:43
There is a button at the bottom of the bug report to reopen, but you should first offer a compelling reason to do so by answering the questions.
