### ISSUE TITLE
Remove down arrows from main toolbar and increase icon sizes

### ISSUE THREAD

**Issue by sound8** [LMMS/lmms#5751] opened 2020-10-29 18:53 UTC
The main toolbar in LMMS has two icons that contain little grey down arrows in them.
"Create new project from template"
"Recently opened projects"

To me these little graphical arrows cause those icons to be smaller, are not needed and could be removed.
Then the icon graphics can be increased in size to match the other toolbar button icons sizes.

The "Create new project"   &   "Create new project from template"
Can get increased paper icon width to fill out toolbar button 
and
"Recently opened projects" clock icon can be increased in size as well.

Again, may not be something other users care about, but little things like this could clean up the look of LMMS, especially in main toolbar where they are always visible.
May sound foolish but give it a chance and see how it looks.

**Comment by Spekular** [comment] 2020-10-29 19:33
Those buttons open dropdowns, which is why there's an arrow. Removing it is out of the question IMO, this is a standard and helpful UI practice. The new project icons are already the same size, and widening them would make it less clear what they are (roughly A4 sized paper). I would guess thst the clock icon is small because it's reused from elsewhere, but regardlesd ur could be increased in size without removing the arrow.

**Comment by sound8** [comment] 2020-10-31 20:27
Come on you are going to make me fight you about two little arrows? 
I wasn't really expecting someone to disagree with this.
Don't make me waste my time creating a graphical example, because once I bust out Gimp you are going to be begging for someone to remove these arrows! :)

No but seriously you really feel that strongly that they are needed?  
The drop down menus will show up either way, it is not like someone is going to be surprised that a menu appears without warning :)

I agree paper icons can stay same width that is fine (just make sure they are centered in the button), but deleting the two down arrows and increasing size of clock icon should be considered.

Obviously just a matter of opinion, the thing is as with most posts if someone disagrees issue never gets applied.
I will convince you dammit! :)

**Comment by Spekular** [comment] 2020-10-31 20:39
Using GIMP to prove that arrows in dropdowns are bad feels a bit silly if you ask me.
![image](https://user-images.githubusercontent.com/8918426/97789437-c81dd080-1bc0-11eb-89b7-1c03f767a419.png)
Perhaps you could use Paint.NET instead:
![image](https://user-images.githubusercontent.com/8918426/97789461-f3082480-1bc0-11eb-8363-c15b9cd24bdc.png)
Or Inkscape:
![image](https://user-images.githubusercontent.com/8918426/97789473-0b783f00-1bc1-11eb-8bff-55d3d2672fd9.png)
Krita?
![image](https://user-images.githubusercontent.com/8918426/97789486-2c409480-1bc1-11eb-90cc-eb1eb43ac2bd.png)
Or even Blender?
![image](https://user-images.githubusercontent.com/8918426/97789495-3e223780-1bc1-11eb-9ee5-a40cacd8b986.png)
Regular old Paint?
![image](https://user-images.githubusercontent.com/8918426/97789508-598d4280-1bc1-11eb-9e6f-dd157b66878d.png)

I'll repeat myself: Arrows to indicate a dropdown are good, standard UI. I would absolutely be surprised to find that two buttons in the toolbar open a menu and the others don't, given zero visual indication that this would be the case.

**Comment by tresf** [comment] 2020-11-11 04:26
Closing as this is intended behavior, at least for now.  Note, we're receptive to change and the UI will undergo many changes as we focus towards our interface goal #1911.

**Closed by tresf** 2020-11-11 04:26 UTC
