### ISSUE TITLE
Allow for copy/pasting of effects

### ISSUE THREAD

**Issue by ExperiBass** [LMMS/lmms#7370] opened 2024-07-07 18:18 UTC
### Enhancement Summary

Itd be nice to be able to copy and paste effects, like when moving an effect between channels. the current way to copy is to create a new instance of the effect and copy-paste each control.

### Implementation Details / Mockup

Reusing the cut/copy/paste buttons from the Song Editor would prolly be the best flow, as the rclick menu is already sparse. plenty of space for three more buttons.

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by thismoon** [comment] 2024-07-07 22:55
Other than adding entries to the rclick/context menu, I would like a Ctrl+drag behavior to copy and paste effects like how it happens with clips in the song editor

**Comment by Gabrielxd195** [comment] 2024-07-07 23:01
I had that same idea, I even designed a mockup with the following buttons.
![Copiar y pegar plugins](https://github.com/LMMS/lmms/assets/26127693/136ea2fd-fc29-4bc3-ad9c-e5cfd00864c1)

1- Save Button: This button is to save the plugins that are in the effects chain along with their settings and the order in which they were placed.

2- Minus Button: This button is basically used to remove all plugins from the effects chain.

3- More Button: This is the classic button for adding plugins.

4- Copy Button: This button will be used to copy all the plugins in the effects chain, with their settings and the order in which they were placed.

5- Paste Button: This button is to paste all the plugins that have been copied from a channel or an instrument, their settings will be pasted in the order in which they were placed.

I want to clarify that these button icons are not from LMMS but from Shotcut, which has this same plugin management model but applied to a video editor. I also added the Copy and Paste options to the menus of each plugin individually, and the ability to drag them. I had that menu in mind, but I forgot to design it. I hope the concept is clear. Thank you

**Comment by Spekular** [comment] 2024-07-08 07:37
Duplicate of #1278 (and two other issues) which has been consolidated into #4877.

**Closed by Spekular** 2024-07-08 07:37 UTC
Labels: enhancement

**Comment by Spekular** [comment] 2024-07-08 19:10
> I understand that they have closed this thread in duplicate, but could you take into account the model of the photo? It would be more intuitive to have these buttons in the effect chain.

Personally I think it looks quite busy; I don't think e.g. deleting all the effects in a chain is a common enough operation that it needs a button equally prominent to the one for adding effects. However, anyone who tackles this issue is of course free to reference the mockup in their implementation.

**Comment by ExperiBass** [comment] 2024-07-08 19:55
> Duplicate of #1278 (and two other issues) which has been consolidated into #4877.

i wish githubs fuzzy search wasnt so fuzzy sometimes :/

**Comment by Gabrielxd195** [comment] 2024-07-08 22:29
> Personally I think it looks quite busy; I don't think e.g. deleting all the effects in a chain is a common enough operation that it needs a button equally prominent to the one for adding effects. However, anyone who tackles this issue is of course free to reference the mockup in their implementation.

The "remove" button is very useful because it immediately removes all the plugins from an instrument or channel that is full, obviously it would be easier to delete the channel and create another one, but what do we do when that channel is a bus that is very busy by many clues? 

It is very common for beginners to fill the effects chain due to lack of mixing and mastering knowledge, I think it has happened to all of us in the beginning. This button avoids having to delete all the plugins one by one
