### ISSUE TITLE
Multiband EQ - Distorted Sound

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1885] opened 2015-03-19 11:17 UTC

**Comment by tresf** [comment] 2015-03-19 14:20
Steps to reproduce:

1. Open a new project
2. Open the default Triple Oscillator  instrument
3. Add effect to instrument via `FX` tab,`Add Effect`
4. In the browse window find  `LADSPA: Multiband EQ`
5. Preview the Triple Oscillator by pressing a note
6. Sound is distorted.

![image](https://cloud.githubusercontent.com/assets/6345473/6732275/10206454-ce21-11e4-9390-6bc9f9b56124.png)

---

Original inadequate bug report: (per @musikbear)

> from forum a user reported that ladspa multiband eq is 'defect'
It indeed does create serious distortion, and is of no use at all.
Considering the number of other eq's in factory-pack, and how well lmms uses advanged vst-eq's, it could simply be omitted -imo

**Comment by tresf** [comment] 2015-03-19 14:21
I've milestoned this for 1.2 because as @musikbear states, the plugin is otherwise worthless.  I'm curious if @curlymorphic has some ideas as to the cause of this distortion, since he has some experience in the EQ plugin area... :)

**Comment by geedubess** [comment] 2015-03-24 00:56
I wouldn't say that this plugin is 'worthless', but it's not optimal. It would be many fewer cycles / lines of code to perform convolution in the time domain vs (DFT + multiplication in the frequency domain + IFT), but it should get the job done, and that seems to be the criteria here. (:

**Comment by diizy** [comment] 2015-03-24 04:50
Why not use FFT? We have libs for that...

**Comment by geedubess** [comment] 2015-03-24 07:03
It is indeed using an FFT lib - fftw3. On a signal like this, you're technically performing a Discrete Fourier Transform - that's just part of the terminology (most of the time when you do a FFT it's a DFT). I'm not super familiar with signal processing on the beefy x86 arch, so maybe FFT/IFFT is how it's usually done - you can implement a FIR or IIR filter with much less cpu cost if you're trying to optimize it (say, for a DSP that's running many filters, or a lower-powered processor) - you can basically do it all in the time domain without the costly FFT/IFFT steps. I swear, it seemed like magic when I first learned it. (;But anyways, I may be steering it off topic. I'm curious to see if my changes satisfy the distortion that was seen (as precisely what sort of unwanted distortion was observed wasn't especially clear, but I did see gain being applied even with all knobs at unity).

**Comment by diizy** [comment] 2015-03-24 13:31
Well depending on the size of the impulse used, convolution done via FFT/IFFT can actually be faster than doing the equivalent convolution in the time domain. 

Since (I assume) we here have multiple cacaded filters, and the frequency response of each filter only has to be calculated when the parameters are changed, I'd assume that FFT is actually the faster option here.

**Comment by musikBear** [comment] 2015-03-27 17:56
looks like both c*preampIII & IV has similar problem

**Comment by tresf** [comment] 2015-04-13 20:34
Closed via #1897

**Closed by tresf** 2015-04-13 20:34 UTC
Labels: bug
