### ISSUE TITLE
Automatic skip of a certain part of the Song-Editor

### ISSUE THREAD

**Issue by DarkFlameSquirrel** [LMMS/lmms#709] opened 2014-05-11 19:14 UTC
This would be SWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEET!!!!!! Sometimes we put in little extra bits in the song that throw the rest of the patterns off their Song-Editor background color arrangement. I'm not entirely sure how to explain that but I hope you catch my drift. So that way if I put in a small buildup that takes up like 2 bars, I could have LMMS completely skip 2 bars after so the rest of the patterns in my song complies with the colors in the song editor. It would make mental counting way less confusing. And maybe have the whole skipped vertical section greyed out to easily indicate a skip no matter how up or down you scrolled. I want this so bad man.

**Comment by Umcaruje** [comment] 2015-06-29 17:16
Duplicate of #1175

**Closed by Umcaruje** 2015-06-29 17:16 UTC
Labels: duplicate
