### ISSUE TITLE
LFO spanning observations -AMT not covering full span

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2487] opened 2015-12-17 12:43 UTC
I have looked at The LFO in default-instrument, and i am surprised over the span of the LFO.
This
![silencewave](https://cloud.githubusercontent.com/assets/6662066/11869941/cbe896e2-a4c3-11e5-9952-3c96cd062712.png)
 is audio **silence** sharply abrupted by a sine-wave, then back to **silence**

This wave spectrum, is inserted in the LFO, synchronized to 1/4, and a continuous A4 is played.
LFOsettings:
![lfosilence](https://cloud.githubusercontent.com/assets/6662066/11869900/8458c158-a4c3-11e5-94a7-f5ddb9a12c3b.PNG)

I expected to have no sound output in the silence part of the 'shape', abrupted by sharp increases in loudness. Instead the result is *continuous playing* of the A4, abrupted by tiny changes in what mostly sound as *pitch* changes.
Listen to this: 
https://soundcloud.com/musikbear/lfosilencepr1n4

I cant understand why the AMT do not span over the full area of the shape -Eg, why does it never go silent, when AMT is on max?
To me it looks like the AMT only cover the the full span to ~50% or less.

Is this intended? And if so, Why? It makes it impossible to duck a sound completely with current AMT-span in LFO

(Nb. So far i have only looked at 3oc.)

**Comment by tresf** [comment] 2015-12-17 14:10
I can't read this.  Please rewrite this or we'll close it.

For starters, why do you have the `?` question mark selected?

* Step 1, summarize the bug.
* Step 2, steps to reproduce.

Somewhere in there the expected versus actual.

* Don't ask 10 questions? In your **BUG REPORT**
* Don't over-format-things *things* (and don't "abuse" parenthesis).
* Observations aren't bugs.  Minus signs -INFRONT of words are hard to read.

Stop spewing crap onto our tracker.

**Comment by musikBear** [comment] 2015-12-17 18:04
*Step 1, summarize the bug.*
I have looked at The LFO in default-instrument, and i am surprised over the span of the LFO.

*Step 2, steps to reproduce.*
This
![silencewave](https://cloud.githubusercontent.com/assets/6662066/11869941/cbe896e2-a4c3-11e5-9952-3c96cd062712.png)
 is audio **silence** sharply abrupted by a sine-wave, then back to **silence**

This wave spectrum, **is inserted** THAT IS WHY THE **?** IS SELECTED! in the LFO, synchronized to 1/4, and a continuous A4 is played.
LFOsettings:
![lfosilence](https://cloud.githubusercontent.com/assets/6662066/11869900/8458c158-a4c3-11e5-94a7-f5ddb9a12c3b.PNG)

Expectations:
I expected to have no sound output in the silence part of the 'shape', abrupted by sharp increases in loudness. 

Actual result.
Instead the result is *continuous playing* of the A4, abrupted by tiny changes in what mostly sound as *pitch* changes.
Listen to this: 
https://soundcloud.com/musikbear/lfosilencepr1n4

I cant understand why the AMT do not span over the full area of the shape. Eg, why does it never go silent, when AMT is on max?
To me it looks like the AMT only cover the the full span to ~50% or less.
Is this intended? And if so, Why? It makes it impossible to duck a sound completely with current AMT-span in LFO.

Nb. So far i have only looked at 3oc.

**Comment by Umcaruje** [comment] 2015-12-17 18:28
Is the imported wave file normalised? Does this happen when you use the default shapes?

**Comment by tresf** [comment] 2015-12-17 19:23
> Does this happen when you use the default shapes?

Of course it doesn't, we all use LFO all the time.  Have fun with this.  I'm done.

**Comment by StakeoutPunch** [comment] 2015-12-17 19:36
That imported file is obviously NOT normalized. Just look at the preview window for the LFO shape. This is not a bug, nor is anything wrong here. I have listened to the output file provided, and those are not pitch changes, but artifacts from changing the volume of a sine abruptly with the LFO as it does not use any form of graceful release like the volume envelope.

https://lmms.io/lsp/?action=show&file=7814

This file demonstrates what I am talking about. The first instrument uses a smooth sine for the LFO shape. The second one uses a square, resulting in clicks and pops. Both shapes have been normalized and as such can fully mute the sound.

**Comment by Umcaruje** [comment] 2015-12-17 20:58
Yup, this is not a bug.

@musikBear you can normalize your shape in Audacity.

**Closed by Umcaruje** 2015-12-17 20:58 UTC

**Comment by grejppi** [comment] 2015-12-17 21:41
![kuvakaappaus 2015-12-17 22-57-30](https://cloud.githubusercontent.com/assets/772336/11881803/c2ba7060-a511-11e5-86af-2c22dbeb2f07.png)

The waveform looks like this with DC offset removed:

![kuvakaappaus 2015-12-17 22-58-40](https://cloud.githubusercontent.com/assets/772336/11882467/3be1d9ee-a515-11e5-8572-9e1b697d853c.png)

There is obviously something completely wrong with LMMS if that is what I get from this instrument:

![lfo](https://cloud.githubusercontent.com/assets/772336/11882029/dd324ae8-a512-11e5-88e9-0b727a4604fd.png)

So there is a constant +0.25 offset in the LFO output, and the output value is not mapped linearly to volume. ~~Though considering this is LMMS it may very well be by design ¯\\\_(ツ)_/¯~~

**Comment by musikBear** [comment] 2015-12-18 12:51
You have focused on the unimportant **pitch**, and i think @StakeoutPunch is correct in his observation. 
But It is not the pitch, that i wonder about, it is the horizontal part of the shape. I expect that part to force the Volume-envelope to silence. 
That is also @Umcaruje why normalizing would not change anything, It would still be silence.

But i have a new way to demonstrate this
And here i do use a default shape, from folder *Waveforms*. 
![lfomarkedpart](https://cloud.githubusercontent.com/assets/6662066/11896978/a3779d52-a58b-11e5-9667-ed6ec67f4dc2.png)
Here 3oc has the default shape **halfsine.flak** inserted in LFO, and the SPD is synchronized to *whole-note*

I have marked the part i suspect to be weird. The volume never duck to this level. It is at least 30% when it is at it lowest level.
That is exactly as in the previous experiment. The horizontal part of the shape, never duck the volume to less than ~30% of the chosen volume, even though AMT is at max.

Maybe it is me who does not understand the functionality of the LFO, but i thought that max AMT would enforce the controlling shape 100%, on the Volume-envelope.

@tresf i know you hate my strange experiments, but it is only through strange experiments, that new things are discovered. And that is true for innovative ways to use any thing, but also unfortunately to find strange problems. I am constantly looking for innovative usages, and i share them, as i find them.

**Comment by softrabbit** [comment] 2015-12-18 20:11
I'm getting something of a deja vu here, a feeling I've witnessed a discussion on this behavior before.

> So there is a constant +0.25 offset in the LFO output, 

...which disappears when you turn "modulate env-amount" on. https://github.com/LMMS/lmms/blob/master/src/core/EnvelopeAndLfoParameters.cpp#L327 most likely. 

Not that I'm sure of how exactly everything in there fits together... the LFO level at that point should be in the -0.5...0.5 range to have it work right for the true case, but that should swing the wave to negative if ```m_controlEnvAmountModel.value()==false```. Unless the envelope value at that point is something I don't expect, which it very well might be. The next clue is probably in this function: https://github.com/LMMS/lmms/blob/master/src/core/EnvelopeAndLfoParameters.cpp#L403

> and the output value is not mapped linearly to volume.

https://github.com/LMMS/lmms/blob/master/src/core/InstrumentSoundShaping.cpp#L255 


> I have marked the part i suspect to be weird. The volume never duck to this level. It is at least 30% when it is at it lowest level.

I'd expect the volume to be around 50% at that point in the LFO cycle, assuming an LFO swinging between 0 at the bottom and 1 (or 100%) at the top.

**Comment by musikBear** [comment] 2015-12-19 10:01
@StakeoutPunch 
> I'd expect the volume to be around 50% at that point in the LFO cycle, assuming an LFO swinging between 0 at the bottom and 1 (or 100%) at the top.

If That is what it **should** be, then i am simply just wrong in my expectations. But why restrict the LFO to not be able to modulate inside a deeper span?
In the setup on my last posted image, i would have liked the volume to be around 0% at that point in the LFO cycle, assuming an LFO swinging between 0 at the bottom and 1 (or 100%) at the top, using your own wordings. This post is related to #2480. With a LFO allowing 50% of volume to always 'pass', then 2480 is irrelevant. Neither sidechaining or gating *through LFO-use* will be 'deep' enough to be interesting. 
And this is the line thats determine this?
> env_level * ( 0.5f + *_buf ) :

And that span -0.5..0.5 is intended and correct. 
Well, My expectations was then wrong, and my idea for creative LFO-usage (2480) is irrelevant.  So be it.

**Comment by musikBear** [comment] 2015-12-20 17:42
But just fyi. @tresf @Umcaruje @StakeoutPunch  This
![lfocompared](https://cloud.githubusercontent.com/assets/6662066/11919094/b556723c-a748-11e5-8370-7a11c2ad374b.png)

Is the differences of LMMS LFO volume control and FLs. 
Square shaped wave. Max. AMT in both.

**Comment by StakeoutPunch** [comment] 2015-12-22 21:11
@musikBear 
>i know you hate my strange experiments, but it is only through strange experiments, that new things are discovered. And that is true for innovative ways to use any thing, but also unfortunately to find strange problems. I am constantly looking for innovative usages, and i share them, as i find them.

We have forums for that, which is why I think there is some annoyance at these types of issues made on the tracker. Time and *place* and all that :P

**Comment by musikBear** [comment] 2015-12-23 12:23
@StakeoutPunch .. but *This* is **not** a description of a strange experiment. I show you all that the LFO in lmms **allows too much sound through, when it is at full AMT**
The correct behavior is as in the FLs panel of the picture, It is wrong and crippling that lmms let that much sound through! 
If only someone would write a proper argument for *why* lmms's LFO only should span ~70% AT FULL AMT!! Then i would shut up. I just know this is so wrong. 
But, i only see windmills in the horizon.

**Comment by tresf** [comment] 2015-12-23 14:11
> If only someone would write a proper argument for why lmms's LFO only should span ~70% AT FULL AMT!! Then i would shut up. I just know this is so wrong. 

Several people agree with you.  Just fix your write-up and reopen.

> But, i only see windmills in the horizon

Is this meant to be a euphemism for something?  @softrabbit linked to some areas he suspects could be the culprit.  Perhaps you could help research this issue?

On a side note, I'd like to point something out... As of December 2015, you've [single-handedly authored 207 bug reports](https://github.com/LMMS/lmms/issues/created_by/musikbear) with little or no attempt at actually fixing the problems.  Compare this to our most active users on the tracker who have a long history of researching and closing our their own bug reports.

If other software fixes some very important issues for you, please feel free to use other software until we can get around to fixing these issues.

If you're truly determined about fixing these issues, you should have the common decency to start writing clear and concise bug reports.  After 207 of them, yours should be of the best quality issue reports we have.
