### ISSUE TITLE
LMMS freezes when you try to render audio twice

### ISSUE THREAD

**Issue by PaulBatchelor** [LMMS/lmms#3397] opened 2017-03-02 16:57 UTC
Sorry folks, I found another bug which I can reproduce. LMMS really doesn't like this laptop of mine!

When I bounce an audio file, then go to bounce it again, it freezes. The GDB backtrace would seem to suggest that it's some sort of threading race condition.

[gdb.txt](https://github.com/LMMS/lmms/files/814501/gdb.txt)

On a related but unrelated note, is there someone I can talk to off github whose knowledgeable about the part s of the codebase in charge of offline rendering? My email is thisispaulbatchelor at gmail dot com.

**Comment by musikBear** [comment] 2017-03-03 12:44
> When I bounce an audio file, then go to bounce it again, it freezes

Can you explain 'Bounce' -What does you do exactly?

**Comment by PaulBatchelor** [comment] 2017-03-03 15:59
Sorry, render audio.

**Comment by mikobuntu** [comment] 2017-03-03 18:02
I have been having a similar render issue for quite some time too on master branch ( crash on render ). I haven't delved into debugging the cause yet. From memory I think it may be GUI related ( not sure, but will work on this tonight ) I have been building against QT5 on Linux , so to rule that out I will build with the defaults in another folder too. * note to myself ...test with all possible audio backends and config settings *

**Comment by PaulBatchelor** [comment] 2017-03-15 19:37
@zonkmachine has been running into export crashes with #3403, which I believe are related to this issue. 

I think the issue with this, (and any exporter related issues) is the renderer class itself, which I believe is causing a race condition with the audio mixer.

**Comment by softrabbit** [comment] 2017-03-16 12:25
The discussion in #2457 might contain some hints.

**Comment by PhysSong** [comment] 2017-11-19 02:19
@PaulBatchelor Can you still reproduce this issue with latest `stable-1.2`?

**Comment by PhysSong** [comment] 2017-11-19 02:23
If you still able to do so, could you please post backtrace with all threads(using `thread apply all bt`) and the problematic project file?

**Comment by PaulBatchelor** [comment] 2017-11-20 16:05
I am still able to reproduce this bug. I have attached both the project file and the backtrace below:
[LMMS_3397.zip](https://github.com/LMMS/lmms/files/1488255/LMMS_3397.zip)

**Comment by musikBear** [comment] 2017-11-20 17:10
I cant reproduce with your file on win32 rc4 (std settings wave)
@PaulBatchelor 
I miss flg. info:
* what do you export to
* do you use two different names, or do owerwrite with same name?

In fact, could you list your exact reprocurable method?

**Comment by PaulBatchelor** [comment] 2017-11-20 19:36
I'm running on Slackware Linux 14.1 64-bit, and I am using JACK version 0.124.1. 

Here are the steps I do to get the bug:

1. start LMMS
2. open song one_note.mmpz 
3. select export from menu
4. save as "one_note.wav"
5. leave all default settings (on my machine: 24-bit 44.1Khz, sinc Medium, no oversampling). hit start.
6. select export from menu again
7. save as "one_note.wav". yes to overwrite. 
8. leave all default settings. hit start. 

At this point, LMMS freezes. I have also tried variations where I save to different filenames. Same results.

**Comment by PhysSong** [comment] 2017-11-20 22:33
@PaulBatchelor Does LMMS still hangs if you use other audio backend?

**Comment by PaulBatchelor** [comment] 2017-11-21 13:27
@PhysSong seems to work fine using ALSA.

**Comment by musikBear** [comment] 2017-11-21 15:51
Linux issue, i step out

**Comment by PhysSong** [comment] 2017-11-22 01:02
@PaulBatchelor Are you able to get backtrace using gdb with `thread apply all bt`? Providing other threads' state would be more useful.
>seems to work fine using ALSA.

Anyway, does the first export breaks playback as well as the second export? Those results can be useful when investigating this issue.

**Comment by zonkmachine** [comment] 2017-11-22 01:44
@PhysSong There's a backtrace zipped in this comment above: https://github.com/LMMS/lmms/issues/3397#issuecomment-345741619

**Comment by PhysSong** [comment] 2017-11-22 04:35
Ah, thanks!

**Comment by PhysSong** [comment] 2017-11-23 01:08
https://github.com/LMMS/lmms/blob/55076d0bb05be9144dc0ca2bef892c51621a8e39/src/core/audio/AudioJack.cpp#L399-L403

After rendering finishes, `AudioJack`'s `m_stopped` is set to `false`. However, Mixer's FIFO buffer is empty at the same time. So JACK backend stops.

I think this condition should be removed and replaced properly.

**Comment by PhysSong** [comment] 2017-11-23 13:26
FYI, #3207 might be fixed with the same way...

**Closed** 2017-12-03 02:27 UTC
