### ISSUE TITLE
I found a bug(Japanese)

### ISSUE THREAD

**Issue by camjazz** [LMMS/lmms#2413] opened 2015-10-15 00:48 UTC
I found a bug,but I cannot write English well.
Please excuse me writing it in Japanese.
Please translate it.

既知の問題かもしれませんが、LMMS起動時に、毎回設定画面が表示されます。
しかも、毎回初期設定に戻されているようです。
ホームディレクトリ(C:\Users\ユーザー名\)に設定を保持するファイル、lmmsrc.xmlがあるという情報をこちらのページ(http://c4se.hatenablog.com/entry/20110701/1309499299 )から得て確認したところ、ファイルに問題はなく、ファイルの内容は更新されていました。
さらに、管理者権限で実行しても、変わりませんでした。
LMMSの、設定ファイルの読み込みにバグがあると思われますが、これ以上は確認することができませんでした。

環境はWindows8 32bit、LMMS 1.1.0、1.1.3の32bit版です。
また、手元にあるWindows7 64bit、LMMS 1.1.0、1.1.3の64bit版でも、同様のことが起こることを確認しました。

**Comment by musikBear** [comment] 2015-10-15 12:42
fyi
It may be a known problem, but in LMMS startup , will be displayed every time setting screen .
Moreover , it seems to have been returned to every time initial setting .
Home directory : to give file that holds the set to (C \ Users \ user name) , the information that there is a lmmsrc.xml from this page (http://c4se.hatenablog.com/entry/20110701/1309499299) confirmation where it was , to file no problem , the contents of the file had been updated .
In addition , it is running with administrator privileges , but did not change .
Of LMMS, it is thought that there is a bug in the reading of the configuration file , but more could not be confirmed .

Environment Windows8 32bit, is a 32bit version of LMMS 1.1.0,1.1.3.
In addition, there is at hand Windows7 64bit, even 64bit version of LMMS 1.1.0,1.1.3, we have confirmed that the same thing will happen
(done with google translate)

**Comment by tresf** [comment] 2015-10-16 12:42
> 
It may be a known problem, but in LMMS startup , will be displayed every time setting screen .
Moreover , it seems to have been returned to every time initial setting .
Home directory : to give file that holds the set to (C \ Users \ user name) , the information that there is a lmmsrc.xml from this page (http://c4se.hatenablog.com/entry/20110701/1309499299) [links to http://lmms.io/forum/viewtopic.php?f=7&t=82&p=257] confirmation where it was , to file no problem , the contents of the file had been updated .
In addition , it is running with administrator privileges , but did not change .
Of LMMS, it is thought that there is a bug in the reading of the configuration file , but more could not be confirmed .
> 
> Environment Windows8 32bit, is a 32bit version of LMMS 1.1.0,1.1.3.
In addition, there is at hand Windows7 64bit, even 64bit version of LMMS 1.1.0,1.1.3, we have confirmed that the same thing will happen . 

@camjazz please try:

```cmd
move "%userprofile%\.lmmsrc.xml" "%userprofile%\.lmmsrc.xml.bak"
```

If error, run CMD as Administrator and try again.

This is not a bug.  Closing as invalid.

**Closed by tresf** 2015-10-16 12:42 UTC

**Comment by tresf** [comment] 2015-10-16 12:44
P.S. @musikBear learn to use the quote feature.  Your post was in English and more confusing than the OP's. Let's take proper care of the tracker, you've been on here long enough to not need these quality control warnings.

**Comment by musikBear** [comment] 2015-10-18 11:32
...it is a direct translation - i wrote that i used google translate
-so i forgot to insert it in quotes -shoot me!  uhoh already done
You sure are not a people-person :-1:

**Comment by Umcaruje** [comment] 2015-10-18 15:47
>-so i forgot to insert it in quotes -shoot me! uhoh already done
>You sure are not a people-person :-1:

To be quite honest, he *is* a people person. I'd never bother to read most of your bug reports like @tresf does. If he tells you to use quotes, use quotes. It makes your comments much more readable. Don't cry about it.
