### ISSUE TITLE
MIDI-routed VST are not working

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#4550] opened 2018-08-22 05:38 UTC
Hi.
Long time Im absent here and it let me to think about some lacks those prevent musician to work in LMMS fully. Well let proceed. I discovered that VST like Chordz, Instascale, Instachord (those are chord&arp generators) are not working in favorite LMMS. Its sadly. Well I think a reason is support lack of MIDI-routing. In my modest opinion they working in FL Studio "through the asshole". Sorry for French... In FL Studio it realise through mixer but it's working. In Reaper it realised much easier - there is usual FX chain in track. It let to put FX before Instrument. It's amasing! LMMS has FX chain too but there instrument loaded first always. All my attempts and experiments in this direction were in vain. If you dont believe me try by you self. :-)

P.S. I'll add Bluearp and Xfer Chtulhu in this list more.

**Comment by musikBear** [comment] 2018-08-22 11:30
@NETMANSKY Ok. There are a few on the no-go list in wiki already, but overall, i would say that ~80% of pure VST *instruments* works natively, whereas ~20% of effect-plugins works. -I will update the list with your reported fails.

**Comment by PhysSong** [comment] 2018-08-22 11:44
Duplicate of #3485.

**Closed by PhysSong** 2018-08-22 11:44 UTC

**Comment by NETMANSKY** [comment] 2018-08-22 20:55
Thank you both, friends! I used key words 'chordz & instascale' but forgot about 'bluearp'... I remembered it later.
