### ISSUE TITLE
Freez function

### ISSUE THREAD

**Issue by Synthwave1984** [LMMS/lmms#3720] opened 2017-07-23 09:56 UTC
Any chance haveing this feature for large project's please thank you

**Comment by BaraMGB** [comment] 2017-07-23 14:19
this could be happen to 1.3 or later I think.

**Comment by Hussam-Eddin-Alhomsi** [comment] 2017-07-23 17:34
@Synthwave1984 Can you please explain the feature you are requesting?

**Comment by Synthwave1984** [comment] 2017-07-23 19:15
Hope so here praying they do add it


On 23 Jul 2017 6:34 pm, "Hussam Eddin Alhomsi" <notifications@github.com>
wrote:

@Synthwave1984 <https://github.com/synthwave1984> Can you please explain
the feature you are requesting?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/LMMS/lmms/issues/3720#issuecomment-317268956>, or mute
the thread

**Comment by Synthwave1984** [comment] 2017-07-23 20:40
How Does It Work? When a track is frozen all the CPU-intensive tasks are temporarily committed as recorded audio.for MIDI Clips, the instrument is no longer being played back in real time

**Comment by mikobuntu** [comment] 2017-07-24 04:02
If my memory serves me correctly, I believe "freeze track" was a feature in a previous LMMS version. I,m unsure why it was stripped out of the code, perhaps it was unstable? Anyway it would be a great feature :)

**Comment by musikBear** [comment] 2017-07-24 10:13
@mikobuntu true, it was removed before 1.0.
Perhaps diiz' not liking the feature, and suggesting something MUCH better, could have influenced the descission.
https://github.com/LMMS/lmms/issues/762#issuecomment-44062621
but i believe there was an issue with frozen zasfx tracks, that crashed lmms

**Comment by BaraMGB** [comment] 2017-07-24 11:34
I don't know if freeze worked before 1.0. Technically a freeze feature workes by exporting the track to wav and import it into a sample track. But since lmms couldn't play a sample track in the middle of song a freeze function couldn't work proper before 1.0. 

But now it should be possible.

**Comment by musikBear** [comment] 2017-07-25 15:26
@Synthwave1984 @BaraMGB 
:p i just realized something.
This feature is in a way already in LMMS, all that i needed is to think out of the box:
LMMS already have the option to build soundfiles, and also the options to set not only the length, eg *between loopmarkers* but also the actual number of tracks!
A user could select *export tracks* and then import those he want in his freeze, or he could mute some tracks, export the rest in one take, and then import that as a 'freeze'. In that way LMMS covers the need for frozen tracks, and a new specific feature is not 'really' needed.
If LMMS after all should have a freeze feature, a *regime* of save and import events could fill that gab. 
So, what about the original note-tracks? Well *mute* does nothing for efficiency. Muted tracks are still processed, so they need to 'go'. 
Here something new *is* needed, but that could lead to a new way to handle tracks in general, and i will describe this idea in an other ticket

**Comment by Synthwave1984** [comment] 2017-07-25 18:36
Thank's musikBear

**Comment by BaraMGB** [comment] 2017-07-25 18:48
Sure, if you bounce your track to wav it's freezed. But a real freeze function can unfreeze your track again. This should be implemented.

**Comment by musikBear** [comment] 2017-07-26 11:01
> But a real freeze function can unfreeze your track again

that would mean, that the data is unchanged in the project-file. I can see the idea in that. So a simple flag on the track-code-block, would decide weather or not the track would be instantiated at all. Good!

**Comment by lukas-w** [comment] 2017-08-27 12:05
Duplicate of #762

**Closed by lukas-w** 2017-08-27 12:05 UTC
