### ISSUE TITLE
feature request: scale GUI

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#6353] opened 2022-03-29 15:54 UTC
Hi

On high resolution monitors (4K or higher), the GUI looks very tiny.
A feature to scale the GUI (100%, 150%, ...) would be very usefull

**Comment by lonely-unicorn** [comment] 2022-03-29 16:19
I requested a cross-platform option inside LMMS itself.
The solution you give only works on windows version 10. I use Ubuntu so useless for me.
The same for people using Mac or other windows versions.

**Comment by musikBear** [comment] 2022-03-30 01:33
Linux version:*
as [i]root user[/i] create a file and name it
[code]gnome-qt.sh[/code]
Place this file in 
[code]/etc/profile.d directory[/code]
Open the file in editor and type :
[code]export QT_AUTO_SCREEN_SCALE_FACTOR=0[/code]

**Comment by lonely-unicorn** [comment] 2022-03-30 15:36
can't you make option in LMMS itself?

**Comment by musikBear** [comment] 2022-03-30 16:00
Atm no. Scaling UI is just not doable with the current implementation. It is also arguable weather this is a lmms-issue at all, or the OS ought to take care of scaling accordingly to the display resolution.
Atm 4K is best tackled with the script method
(Win10/11 also can do this:
https://www.youtube.com/watch?v=eXpvy_s8w7w&

**Comment by lonely-unicorn** [comment] 2022-03-31 16:19
Ableton live is made using QT too and it has a nice option to scale the GUI up/down.
Why is LMMS not able to do it, because I thought it uses QT too?

I think LMMS should have this feature, so people can adjust their GUI to their screen cross-platform in an easy way. Just look at ableton live.

**Comment by Spekular** [comment] 2022-04-02 20:44
Related: #455, #2510, #5376.

I think this is a duplicate of the former two in combination, close?

**Closed** 2022-06-30 16:29 UTC
