### ISSUE TITLE
Copyright Status of  Data directory not indicated.

### ISSUE THREAD

**Issue by afarlie** [LMMS/lmms#4583] opened 2018-09-08 17:25 UTC
There is a general license for the code of the program.

However, the licensing for the assets (ie samples/presets) in the Data directory isn't clearly indicated.

This means I can't actually use the samples to actually make anything I'd like to share, because the policy on a third party site requires clear licensing for anything used.

Perhaps someone could add a list detailing or clarifying the licenses for the samples and presets? Thanks.

**Comment by SecondFlight** [comment] 2018-09-09 23:15
From Wrillic on Discord in #assets on June 15, 2018:
> All the assets (samples/presets) are CC0

**Comment by afarlie** [comment] 2018-09-10 19:40
Speaking of which,  some of the ZynAddSubFX Instrument Patches aren't necessarily CC-0.  This is based on the feedback I got in relation to :  https://github.com/zynaddsubfx/instruments/issues/2 and an examination of some of the files in that repository.    I would strongly hint at having a discussion with them about what licenses are used for their Instrument Banks)

**Comment by lukas-w** [comment] 2018-09-10 21:29
@SecondFlight This is not true. That statement by Wrillic refers to the https://github.com/LMMS/assets repository, which as far as I know has been created partly because of the unclear licensing status of the existing samples.

**Comment by SecondFlight** [comment] 2018-09-11 15:47
Alright, thanks for the clarification @lukas-w

**Comment by tresf** [comment] 2018-09-25 01:15
@afarlie as indicated, we're working on it.  Even some of those promised CC0 aren't, and we had to deal with that here: https://github.com/LMMS/assets/issues/15.

We need a lot of help with our samples, presets and projects and help is welcome.  This bug report is really a duplicate of the entire assets repo linked above.  Closing as a duplicate.  Thanks and sorry bout this vagueness.

**Closed by tresf** 2018-09-25 01:15 UTC
