### ISSUE TITLE
LMMS Error Report not resizable, only pros can copy, repeat errors

### ISSUE THREAD

**Issue by qubodup** [LMMS/lmms#5176] opened 2019-09-08 12:21 UTC
(Trying to open https://lmms.io/lsp/?action=show&file=15367 )

![image](https://user-images.githubusercontent.com/18312/64488066-848d3800-d243-11e9-8c81-cae70ed113ba.png)

The Error Report window can't be resized. Allowing to resize it would help make make errors more readable.

Missing DLL errors are repeated. They could be consolidated.

It's possible to copy the error by right-clicking, then selecting select all, then right-clicking, then selecting copy. It would be more beginner-friendly to either have the errors in a disabled text field that allows selecting/copying text like normal text boxes OR a button "copy to clipboard" might be even better.

Might be related to https://github.com/LMMS/lmms/issues/4312

**Comment by Sawuare** [comment] 2019-10-20 01:48
Duplicate of #4312. Closing.

**Closed by Sawuare** 2019-10-20 01:48 UTC
Labels: enhancement, gui
