### ISSUE TITLE
Duplicate only instrument in BB-editor / Song Editor

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6116] opened 2021-07-27 07:29 UTC
### Enhancement Summary
Ability to clone instrument tracks/beat-bassline patterns in-LMMS selectively cloning only some patterns

#### Justification
Trying to clone a track in BB-editor is the easiest way of effectively duplicating an instrument. However, cloning a track clones the instruments AND the pattern. I am asking for how to do two things:
a) directly clone instrument without pattern (can be done by saving preset, but it seems more convenient to be able to do it in-LMMS)
b) clone pattern only in one beat/bassline and not others; ie, one (or a few specified number of) B/Bs gets pattern cloned, all others only have an empty cloned instrument track

#### Mockup

![image](https://user-images.githubusercontent.com/76674645/127113791-8761abdb-4386-4c0e-bb8c-49d4958e1b78.png)

**Comment by Spekular** [comment] 2021-07-27 15:35
Duplicate of #453.

I suggest just using instrument tracks, then you can simply place new clip on the same track instead of making new BB tracks every time you want an instrument to play something different.

**Closed by Spekular** 2021-07-27 15:35 UTC
Labels: enhancement
