### ISSUE TITLE
1.0.0 - Automation Editor can't copy

### ISSUE THREAD

**Issue by ahogen** [LMMS/lmms#515] opened 2014-03-27 06:47 UTC
So I've noticed since the intro duction of the new pattern shaping features (dot, line, and curve) that I can't copy and paste the pattern. LMMS will do it, but the new pattern will not have all the points moved to the top instead of the original locations.

So, looks like there's a bug when copying the Automation pattern.

Original pattern:
![1](https://cloud.githubusercontent.com/assets/6827790/2534460/a1f29c5e-b57b-11e3-9d8c-98b98522d3f8.PNG)

New pattern:
![capture](https://cloud.githubusercontent.com/assets/6827790/2534463/b2c6c780-b57b-11e3-96e9-b2e4b7aa1433.PNG)

**Comment by PhysSong** [comment] 2018-10-17 02:03
Closing because there were no conversations for 4 years and I can't find any reliable way to reproduce this now. Please feel free to request reopening if the bug still exists.

**Closed by PhysSong** 2018-10-17 02:03 UTC
Labels: bug
