### ISSUE TITLE
Math controller? (possibly useless)

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1767] opened 2015-02-15 20:11 UTC
SHAMEFUL INTRODUCTION:

I've got thinking that actually I don't see anything useful one could do with this, that can't be done with current LFO and peak controllers, so if you don't have better things to do - ignore this. Now to the main thing.

BODY OF THE ISSUE:

I've been thinking about what more could be done with the concept of controlers, and I've got an idea.

There could be a controller that can take input from other controllers and perform math on these.

Example GUI layout:

<negative> (x) [operator] <negative> (y)

Explanation:
Building blocks:
( ) - knobs
[ ] - dropdown menus
< > - checkboxes (togleeable LEDs)

Elements:

(x), (y) - two inputs, user can move these with MIDI CC, automation, peak controller, LFO, or input a constant value (I have no idea what value range should be allowed here)

<negative> - inverts the value of assigned knob, so the math controller uses a negative value for positive input and vice-versa.

[operator] - a dropdown menu that lets you choose between addition or multiplication. There's no substraction becasue that's what <negative> options are for, while division could encounter problems with 0 values in the (y) input.

The math controller then performs an equation based on the GUI layout and lets the user control another knob with the math controller.

Possibly stackable (you control inputs of a math controller with other math controllers etc).

What do you think? Useful? Waste of time? "Code it yourself, samrtie"? "Make a proper GUI mockup first"?

**Comment by tresf** [comment] 2015-02-15 20:13
Possible duplicate of #1332

**Comment by tresf** [comment] 2015-02-15 20:14
Also, see my mockup here:  https://github.com/LMMS/lmms/issues/1332#issuecomment-63882625

**Comment by tresf** [comment] 2015-02-25 20:49
Marking as duplicate of #1332.  Please let me know if there's something missing over there and we'll copy it over to the bug report.

**Closed by tresf** 2015-02-25 20:49 UTC
