### ISSUE TITLE
Opening/Saving/Exporting Projects crashes program.

### ISSUE THREAD

**Issue by circuitfry** [LMMS/lmms#2077] opened 2015-05-28 04:39 UTC
-- Pending support request. Yes, using 1.1.3

Accessing the file browsing dialogue in any context with a fresh installation of the new version of LMMS causes the program to hang up and crash. I have to make copies of existing projects, rename them, and associate their filetype with the program in order to open them. Exporting them has no workaround, so I cannot produce music, at the moment.

Steps to reproduce my issue:
0. Uninstall previous version of LMMS
1. Install LMMS
2. Launch LMMS
3. CTRL+O
or in an existing project
1. Project > Save As
or with a finished project
1. Project > Export Project

It's that simple, unfortunately. It feels weird... We wouldn't be seeing a "stable" release if it had this problem. Something must be wrong on my end but I was just using a fully-functional 1.1.0 so I can't imagine what is wrong. Windows 8.1.

**Comment by Wallacoloo** [comment] 2015-05-28 05:06
Hey Circuitfry. It's neat to see your name around here.

The newest version of LMMS is actually 1.1.3 (not 1.1.0), which can be downloaded [here](https://lmms.io/download/#windows). Perhaps writing "1.1.0" was a typo, but if not, you should definitely try upgrading to 1.1.3.

**Comment by Wallacoloo** [comment] 2015-05-28 05:16
And for what it's worth, I installed LMMS 1.1.3 for 64 bit windows from that download link on a Windows 8.1 computer on which LMMS had never been installed before, and I could not reproduce the hang/crash for any of the 3 cases you listed.

**Comment by tresf** [comment] 2015-05-28 05:38
@circuitfry,

Some strange things can happen during the install process that cause stability problems in Windows.

Below are instructions to completely purge LMMS manually.  If they don't work, a DLL may be shared on your system with the same name as one that ships with LMMS.  If that is the case, we'll have to run LMMS.exe against [Dependency Walker](http://www.dependencywalker.com/) to help find the cause.

 1. Uninstall from control panel
 2. Delete (or move) `C:\Program Files\LMMS` if it exists (Right click CMD, run as Administrator)

  ```cmd
  del  "%programfiles%\LMMS"
  del  "%programfiles(x86)%\LMMS"
  ```
 3. Delete (or move) `C:\Program Files (x86)\LMMS` if it exists
 4. Move config file `.lmmsrc.xml`

  ```cmd
  move "%userprofile%\.lmmsrc.xml" "%userprofile%\.lmmsrc.bak"
  ```
 5. Optionally, open `regedit.exe`, delete `.mmp` , `.mmpz`, `LMMS Project`, `LMMS Project (compressed)`:

  ```reg
  HKEY_CLASSES_ROOT\.mmp
  HKEY_CLASSES_ROOT\.mmpz
  HKEY_CLASSES_ROOT\LMMS Project
  HKEY_CLASSES_ROOT\LMMS Project (compressed)
  ```

 6. Optionally, open `regedit.exe`, delete `LMMS Developers` from HKEY_LOCAL_MACHINE, SOFTWARE OR from Wow6432Node.
 7. Optionally, open `regedit.exe`, delete `LMMS` from:

  ```reg
  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\LMMS
  ```

  or 

  ```reg
  HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\LMMS
  ```

**Comment by circuitfry** [comment] 2015-05-28 13:46
Thanks for the support, tresf. The manual purge unfortunately did not resolve it, so I'll go with you on the assumption of a conflicting DLL. I'm assuming Dependency Walker is a program that searches LMMS' dependencies with other programs' dependencies.

**Comment by circuitfry** [comment] 2015-05-28 13:54
After opening LMMS.exe in DependencyWalker, it is telling me that these files cannot be found:
* API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
* API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
* API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
* API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
* EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL

The last one likely isn't important if I'm not an NT User (Windows 8.1). The first one may not be 100% needed if I'm on a 64 bit kernel. The middle three, hm, hard to determine, but if it just can't access Windows stuff in general I suppose that would explain why I can't open/import/export/save any files with it. It's basically telling me that there are missing files. Shouldn't I be getting messages of conflicts?

**Comment by tresf** [comment] 2015-05-28 14:19
Did you upgrade from a 32-bit OS?

You may need to reinstall the  Visual C++ Redistributable Packages per http://answers.microsoft.com/en-us/windows/forum/windows8_1-performance/32-bit-application-fails-to-start-after-81-upgrade/b825723e-e2a2-4c8f-bd1f-10446a5d7059

I'm very interested in knowing the cause and solution to this.

**Comment by circuitfry** [comment] 2015-05-28 14:23
This is a pretty new computer with 64-bit windows 8 to 8.1 so thankfully that's not the issue, we'll just have to and it just fixed itself that's just great I sure love it when computers act like magic and fix themselves that doesn't tick me off at all

I'm gonna go with "the purge worked and it was a delayed fix for whatever reason" for $200, Alex.

**Comment by tresf** [comment] 2015-05-28 14:56
Ok closing with status of `computers act like magic and fix themselves`. :)

**Closed by tresf** 2015-05-28 14:56 UTC
Labels: support request
