### ISSUE TITLE
Lmms Asio

### ISSUE THREAD

**Issue by adanpack** [LMMS/lmms#6342] opened 2022-03-24 05:42 UTC
Hola. Me gustaría que se incluyera en la salida de audio Asio. Es decir que se puedan usar drivers asios en lmms.

**Comment by allejok96** [comment] 2022-03-24 07:55
ASIO is protected by a license that is incompatible with LMMS. Even if someone wrote ASIO support for LMMS they would not be allowed to distribute it. Audacity already has this problem. 

https://manual.audacityteam.org/man/asio_audio_interface.html

> Audacity, as an open source program licensed under the [GPL](http://www.gnu.org/licenses/licenses.html#GPL), is therefore currently unable to support ASIO, despite being ASIO-capable (providing the user's sound device is similarly capable). If ASIO support were distributed in Audacity builds this would either violate Steinberg's licence agreement if the code were included, or conversely would violate Audacity's GPL Licence if the code were withheld.

**Comment by PhysSong** [comment] 2022-04-18 11:51
Duplicate of #2004, #1173.

**Closed by PhysSong** 2022-04-18 11:51 UTC
