### ISSUE TITLE
qt5-x11embed relies on missing cmake modules

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#4247] opened 2018-03-13 19:46 UTC
In the cmake file of qt5-x11embed, a find module is used but not found:

find_package(XCB REQUIRED COMPONENTS XCB ATOM KEYSYMS UTIL)

The Module path is set to:
${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ECM/find-modules

But this directory doesn't exists in the lmms master branch.
On Fedora, this module can be found on /usr/share/ECM ...

**Comment by tresf** [comment] 2018-03-13 22:03
@ycollet looks like a duplicate of #4100, no?

**Comment by tresf** [comment] 2018-03-13 22:05
Sorry, I'll be more specific... it's a [nested submodule](https://github.com/lukas-w/qt5-x11embed/tree/master/3rdparty) (more submodule hell, apologies, we're working to make this better!).  `ECM @ 6604694`

**Comment by lukas-w** [comment] 2018-03-25 10:19
@ycollet I'll assume cloning submodules fixed this for you. Please reopen if needed.

**Closed by lukas-w** 2018-03-25 10:19 UTC
