### ISSUE TITLE
Visual behavior in BB-editor of moved no-length-notes

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#843] opened 2014-06-12 12:59 UTC
1.0.2
win 32

to reproduce
insert a note-event in B&B-editor
Open in piano-roll
Mark the note
Move it any distance - like one tick
Close pianoroll
Now there is no note-event on the BB GUI. The 'track' is _apearently_ empty, but it will playback _with_ note, i the new pos.
This would imply, that no-lengths notes, only will be _shown_ in BB, if they are in default (on tick) pos. If they are moved, the _visually_ disapear. _Not_ logically, though

**Comment by Umcaruje** [comment] 2015-06-30 16:42
Reproduced on ubuntu 15.04 x64 - master branch

Slightly different steps to reproduce though:
* Insert a note in a BB track
* Open track in piano roll
* Move note in piano roll
* Close the piano roll and then reopen the track in it

Here is a gif of the behaviour: 
![gifrecord_2015-06-30_182903](https://cloud.githubusercontent.com/assets/6282045/8436319/b919872a-1f57-11e5-9f9c-89f33a5622ec.gif)

**Comment by Spekular** [comment] 2015-07-02 14:02
This has happened to me in master, but only some notes disappeared after I moved a sequence forwards. Checking piano roll confirmed they were all in positions that should be visible. However, saving, restarting, and opening the project fixed it for me.

**Comment by musikBear** [comment] 2015-07-03 10:59
> However, saving, restarting, and opening the project fixed it for me.

yes! this bug is only visual (as i orr. wrote) - the *logic* is fine. It is just the interpretation of the logic, to visual objects, that has a flaw
Or in other words : 
Those events that make sure a new projects logic is displayed visually correct, are not being re-called after a no-length-note are moved in piano-roll
This **may** be as simple as just finding the event that actually maintain this displaying-update, and call that once more -but also depend on a proper handle to the method
Closing BB-piano-roll could be a candidate for that event-call

**Comment by zonkmachine** [comment] 2017-06-16 23:31
I can't reproduce this with 1.2.0-rc3 .

**Comment by zonkmachine** [comment] 2017-06-18 14:23
Closing. This looks like it's been fixed in 1.2.0-rc3. Please reopen if this can be reprodced.

**Closed by zonkmachine** 2017-06-18 14:23 UTC
Labels: bug, gui
