### ISSUE TITLE
problemas

### ISSUE THREAD

**Issue by mixterioso** [LMMS/lmms#4054] opened 2017-12-15 01:20 UTC
saludos amigos tengo un problema cuando carga una nueva caja de ritmo se borran los instrumentos de las que ya estaban cargadas

**Comment by Spekular** [comment] 2017-12-15 08:18
#### Español
No sé si alguien aquí habla español. Creo que todos los problemas deben describirse en inglés.

¿Qué significa caja de ritmo en lmms? ¿Puedes mostrar una imagen?

Si está cargando la caja de ritmo en "Vestige", "Vestige" solo puede cargar uno. Necesita una instancia de "Vestige" para cada instrumento VST que desee.

#### English

I don't know if anyone here speaks spanish. I believe all issues should be described in english.

What does caja de ritmo mean in lmms? Can you show an image?

If you are loading the caja de ritmo in "Vestige", "Vestige" can only load one. You need one instance of "Vestige" for each VST instrument you want.

(Caja de ritmo appears to mean drum machine. The closest native thing would be the BB editor I suppose, and while it has weird behavior, I don't think it sounds relevant to: "instruments that were already loaded are deleted". Therefore I assume it could be a VST, since loading a new VST in the same copy of Vestige would overwrite the existing one. This doesn't seem entirely likely either, though,)

**Comment by Hevedy** [comment] 2017-12-15 09:11
I think him means that, you need to load one VST/Vestige per instrument, you can't store more than one.

No puedes tener mas de un instrumento por instancia/caja de VST/Vestige, necesitas uno por instrumento.

**Comment by zonkmachine** [comment] 2017-12-17 21:07
@mixterioso Este problemo no es muy claro.
(~This problem isn't very clear...)

**Comment by tresf** [comment] 2018-01-05 18:35
> (~This problem isn't very clear...)

Agreed.  Closing.  Probably a duplicate of #3136 if I'm reading it right.

**Closed by tresf** 2018-01-05 18:35 UTC
Labels: needs clarification
