### ISSUE TITLE
Fast midi switcher

### ISSUE THREAD

**Issue by Achifaifa** [LMMS/lmms#1942] opened 2015-04-10 06:52 UTC
Hi

I use a small MIDI keyboard with lmms. Works fine, but when I have to assign it to a track I have to click in "actions'>'MIDI'>'input'>controller, and when I want to assign it to another track I have to do that twice, once to disable it in the current track and another one to enable it in the other one.

Could it be possible po have an extra check mark per instrument with the 'mute track'/'solo' buttons? A column of buttons per instrument you can click to enable/disable it in that track. That would make switching instruments so much faster. Another pop-up window with a table showing instruments and tracks would also work

**Comment by tresf** [comment] 2015-04-10 13:37
@Achifaifa thanks for filing a bug.  This is a duplicate of #1189 #1781 #1918, which is already on our radar.  Thanks!

-Tres

**Closed by tresf** 2015-04-10 13:37 UTC
Labels: duplicate

**Comment by oeai** [comment] 2015-04-10 14:35
you can assign midi channel #1 to first instrument
and midi channel #2 to a second
then you can change channels on your keyboard to switch between instruments

**Comment by Achifaifa** [comment] 2015-04-10 17:12
@tresf Thanks :)
@oeai It's a 25 key midi controller (Akai LPK25) so I don't think I can do that, but thanks for the tip.
