### ISSUE TITLE
VST3 support

### ISSUE THREAD

**Issue by Spleen-Vitals** [LMMS/lmms#5746] opened 2020-10-29 10:01 UTC
Was wondering if vst3 support is can and will be implemented. Found an open issue but it literally goes astray talking about other things. A lot of good opensource plugins are vst3 and I learned that it's under an opensource license. Please implement vst3.

**Comment by Spekular** [comment] 2020-10-29 11:37
Duplicate of #4715. Please don't open a duplicate issue because you feel the existing one is bad. It would have been better to ask on the existing issue if it should be replaced with a new one/cleaned up/etc.

**Closed by Spekular** 2020-10-29 11:37 UTC
Labels: enhancement

**Comment by Spleen-Vitals** [comment] 2020-10-29 12:01
What's up with devs and being rude all the time? I didn't say it was bad. I just explained that it isn't talking about implementing it that's why I even mentioned that I saw it. All you've been doing is closing the issue every time someone asks about it since 2019 without actually saying anything about it (I think we can assume that's why you're getting duplicates). There was no need to respond like that. Anywho, I'm genuinely sorry, sir. Have a great day.

**Comment by Spekular** [comment] 2020-10-29 12:19
> All you've been doing is closing the issue every time someone asks about it since 2019 without actually saying anything about it

The last off topic comment in #4715 ends with:

> It's better to continue the discussion somewhere else, given it's somewhat deviated of the original VST3 topic.

After that Dom self-assigned the issue and the conversation has been on topic.

I didn't intend to be rude, but I do try to keep my replies concise when possible (and despite this it takes a lot of time to keep up with the tracker). I've cleaned up #4715 a bit since, as you mention, it did go off topic for a while.
