### ISSUE TITLE
Calf Bass Enhancer clips when rendering

### ISSUE THREAD

**Issue by BetoVickers** [LMMS/lmms#2357] opened 2015-09-17 10:40 UTC
It clips until you restart.
To replicate just add the effect and export/render.
I don't know if I'm just me...
![lmms problem 2](https://cloud.githubusercontent.com/assets/10542453/9931134/61d23c1e-5d0f-11e5-8bac-decccf7013c8.png)

**Comment by tresf** [comment] 2015-09-17 12:18
Duplicate of #1048 I believe.

**Comment by BetoVickers** [comment] 2015-09-17 15:44
It isn't DC offset or something like that, it's like... if it had turned up the gain. After the render it is still saturated.
(sorry bad english)

**Comment by zonkmachine** [comment] 2016-08-01 04:20
Thanks for the report! We have a later issue ( in the Calf Exciter ), #2953, that shows the same behaviour so I close this one.

> Duplicate of #1048 I believe.

Maybe, will look into it.

**Closed by zonkmachine** 2016-08-01 04:20 UTC
Labels: duplicate

**Comment by musikBear** [comment] 2017-06-02 12:50
Should not be closed - now it looks looks this specific Bass-Enhancer export-issue is fixed, it is not: http://lmms.io/forum/viewtopic.php?f=7&t=25726&p=46417#p46417

**Comment by tresf** [comment] 2017-06-02 13:45
> Should not be closed

It's not closed as fixed, it's closed as a duplicate of #2953.
