### ISSUE TITLE
SongEditor Tool Choice Does Not Change Icon

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#941] opened 2014-07-07 12:39 UTC
win xp23
choose pencil **visual glitch**
There is no cursor change. Cursor in Song-editor is std-arrow in all opperations.
Logical ok

**Comment by SecondFlight** [comment] 2019-03-12 14:11
Reminder to reproduce when I get home.

If I can reproduce, I'll add this to #4877.

**Comment by SecondFlight** [comment] 2019-03-13 01:27
Reproduced, but on second thought I would like to argue this is not a bug, or at very least that there is no reason to make the requested change.

1. There are only two options in the song editor, and it is very easy to see which one you have selected.
2. The absence of a visual indicator next to the cursor is long-standing behavior.
3. The extra cursor indicator in the song editor and automation editor appears to be drawn directly onto the canvas for each. Adding this functionality to the song editor will not be as trivial as switching cursors.

For these reasons, as well as for the more general reason of cleaning up our issue tracker, I would like to close this issue.

I will leave this open for a while in case there are any objections.

**Closed** 2019-03-13 13:50 UTC
Labels: bug, gui
