### ISSUE TITLE
Playback in Piano roll retarding LMMS

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#4148] opened 2018-02-01 05:37 UTC
In my project were loaded 22 remotevst processes. Basicaly there are fx in mixer and only 2 are VSTi. My system has params:
- i3-2370M 2X2.4 CPU
- 4 Gb RAM
- Win10
- project scope in taskman jumping from ~ 300 Mb to ~900 Mb
- CPU load in taskman is 30-40% at rest and it increase to 50%+ if playing notes in Piano rool. In this case playback are terrible warping and retarding LMMS.

**Comment by musikBear** [comment] 2018-02-01 16:18
>  Basicaly there are fx in mixer

What effect vst?
Can you check your page-file-usage, and see if you are low on ram?

**Comment by NETMANSKY** [comment] 2018-02-02 05:51
@musikBear Basically my VSTfx are GVST but it's not important. Because I can often use another VSTfx and VSTi. I dont use exotical VST. Picture is drawn the same. My past post contain tech params and I pay attention that project scale is too large and it are jumping. More loaded projects in another DAW scaled no more than 400-500 Mb. What params required to launch LMMS: winxp, 512 Mb RAM - or am I wrong? But I have standard Win10 HOME whithout extra anysided processes and 4 Gb RAM. Why I have to see "if you are low on ram". 🥇 In LMMS options I checked Win32 API because QT API is more hard load LMMS in my opinion. My LMMS is x64. Majority of VST are x64 and sometimes there are x32 version.

**Comment by musikBear** [comment] 2018-02-02 16:57
> required to launch LMMS: winxp, 512 Mb RAM - or am I wrong?

Will not do, >1gb is needed. 2 and you are fine.
I have NO idea what GVST is?
I will check your project for you if you like, and see if there is something that looks obvious.
*You* can check the influence of the GVST, by simply moving the dll to a different folder, then lmms will launch the project with a localization 'error', and it will without the GVST thing loaded -what result do you *then* have?

Contact me: http://lmms.io/forum/memberlist.php?mode=viewprofile&u=143#

**Comment by tresf** [comment] 2018-02-02 18:28
> Contact me: http://lmms.io/forum/memberlist.php?mode=viewprofile&u=143#

No, please keep communication in the tracker or on Discord.

> In my project were loaded 22 remotevst processes. 

As @musikBear has requested, to make a valid use-case you need to share one, exact VST plugin that causes this problem, then a developer can reproduce and see if there's a problem in the codebase.

Thanks for reporting this, but please remember that computing is (for the most part) and exact science.  If you give us the steps to reproduce, we will and then we'll fix the underlying bug. 👍

**Comment by tresf** [comment] 2018-02-02 18:31
> Basicaly there are fx in mixer and only 2 are VSTi.

Mixer does not support VSTi, they support VST effects.  I think what I'm reading in this bug report is that something is happening in the Piano Roll editor of this project where notes are spawning new instances of the RemoveVST process.  This is likely a regression, a long standing bug or simply a bug with the VST.  Exact steps needed from 0 RemoteVST processes to 22 RemoteVST processes in an exact use-case.  If you cannot provide this we will close the bug report as `needs clarification`.

**Comment by NETMANSKY** [comment] 2018-02-03 09:59
I forgot to add that my LMMS is RC5x64. 
@musikBear GVST is http://gvst.co.uk
@tresf Of course I know that mixer doesnt support VSTi!!! I wrote about VSTfx in a mixer. I use VSTi in a tracks only. 
Well, let me start from beginnig :-) What I can to share you to solve the trouble? Project file? But you have no VST I used... Or DLLs of used VST? But all my VST are recursive in root VST folder and its place different of your places.. How I can to participate?

**Comment by musikBear** [comment] 2018-02-03 16:06
@NETMANSKY wrote
> What I can to share you to solve the trouble?

First try to do the remove-to-folder test. That will show what influence the effect-plugin's have
You need to let a dev see the project. It is not certain that the effects are the reason, maby the project is flawed, that was why i gave you a PM-option, but tresf say no-go, so you need to post it here -zip it and upload, or make an appointment on discord

**Comment by NETMANSKY** [comment] 2018-02-03 22:18
Well that's here. If you let me I repeat one more time. RC5 came more stable in VST work that previous versions. But warping and retarding playback in Piano roll remained. Watch in LMMS cpu performance graph. Line becomes a red color if press Playback button in Piano roll. But if I press Record_notes_if_Playback button a playback is OK. Also in BB and Song editor a playback is OK. The trouble affects Piano roll Playback only.
[Sahara.zip](https://github.com/LMMS/lmms/files/1692225/Sahara.zip)

**Comment by tresf** [comment] 2018-02-03 22:37
What's interesting about this project is that it solely uses the Piano Roll within the BB Editor.  Anyway, you've failed to provide steps to reproduce.  Closing.

Here's a snippet from Musescore's "How to submit a bug report".  We don't have these written up (we assume they're fairly common sense), but we can't play guesswork with arbitrary steps, arbitrary plugins.  You've failed to mention specific steps.  Closing.

> 
> **Steps to reproduce bug** (borrowed from [musecore's wiki](https://musescore.org/en/developers-handbook/how-write-good-bug-report-step-step-instructions))
> 
> A bug report requires clear instructions, so that others can consistently reproduce it. Many bugs require some experimentation to find the exact steps that cause the problem you are trying to report. If you aren't able to discover these, try obtaining some help on the forums instead.

**Closed by tresf** 2018-02-03 22:37 UTC

**Comment by tresf** [comment] 2018-02-03 22:40
Note, if you provide clear, concise steps to reproduce, we'd be happy to reopen and investigate further.

**Comment by NETMANSKY** [comment] 2018-02-03 22:55
@tresf Are you kidding my English and you dont understand it? May be I have to show my screencats in Youtube then you undestand? I see you like to close my posts not first time and make me an idiot. Well... pretty good developer reaction of "exlusive" product! Thanks GOD for IT!

**Comment by tresf** [comment] 2018-02-03 23:14
Your English fine, however this bug report is missing vital information for a developer to reproduce the problem without spending a large amount of time trying to reverse engineer what plugins, samples and effects you have chosen to use, better yet which steps cause the problem.

A bug submitter shouldn't have to share a screen for a basic bug report, the bug contents should have enough steps to reproduce.

On occasion, a bug report is not easy to explain and a screen cast is necessary.

Anyway, as explained all we need is step-by-step instructions to create the aforementioned symptoms from an empty project so that it can be evaluated.

**Comment by musikBear** [comment] 2018-02-04 16:56
@tresf 
"remove-to-folder test":
> You can check the influence of the GVST, by simply moving the dll to a different folder
