### ISSUE TITLE
Piano roll and automation editor default window size too small

### ISSUE THREAD

**Issue by midi-pascal** [LMMS/lmms#2288] opened 2015-08-23 19:29 UTC
On a new project, the default size of the piano roll and automation editor windows is way too small.
To reproduce:
1- Create a new project
2- Add an instrument - Sf2 Player for example -
3- Double click its track
The result looks really ugly - IMHO -:
![pianoroll](https://cloud.githubusercontent.com/assets/6962451/9429819/80fc0948-49ab-11e5-81f6-0438a7790cab.jpg)
The initial size of the Piano roll window should minimally show the menus and toolbar.

**Comment by michaelgregorius** [comment] 2015-08-23 20:25
This issue is related to the default template and how widgets and editors, e.g. the piano roll, automation editor and project notes, persist their state into it when they are not shown. To reproduce follow these steps:
* Delete the default template (found at `${LMMS_HOME}/templates/default.mpt`).
* Start LMMS.
* Execute the three steps described in the issue text above. The piano roll and automation editor should open in an appropriate size.
* Close LMMS.
* Delete the default template in case it has been created.
* Open LMMS again.
* Click "New project". This will create a new default template due to some strange logic described in #2272.
* Open the default template in a text editor.

The default template should now contain the following section:
```
<pianoroll width="0" x="0" y="0" maximized="0" height="0" visible="0" minimized="0"/>
<automationeditor width="0" x="0" y="0" maximized="0" height="0" visible="0" minimized="0"/>
<projectnotes width="0" x="0" y="0" maximized="0" height="0" visible="0" minimized="0">
```
The problem seems to be that widgets persist a bogus state in case they are not shown when the template is created.

If you start LMMS the method `MainWindow::restoreWidgetState` is called for most of the editors. Because the editors have a position and size of `(0, 0)` they will be resized to be invisible. To reproduce create a breakpoint in `PianoRollWindow::loadSettings` for example.

Most likely this will need to be fixed in `MainWindow::saveWidgetState`.

**Comment by musikBear** [comment] 2015-08-24 12:18
copy of #2194, but with more info

**Comment by M374LX** [comment] 2015-08-24 20:48
I still think it is a good idea to check whether the windows are smaller than the minimum allowed and adjust them if so right after loading a project or template.

**Comment by Wallacoloo** [comment] 2015-08-24 20:52
@M374LX agreed.

**Comment by tresf** [comment] 2015-08-27 04:36
Shouldn't we be making more use of [`adjustSize`](https://github.com/LMMS/lmms/search?utf8=%E2%9C%93&q=adjustSize) (not sure if that helps the 0, 0, 0, 0 problem).

**Closed** 2015-09-17 16:02 UTC
Labels: bug, gui
