### ISSUE TITLE
OS X UI hangs during playback

### ISSUE THREAD

**Issue by sunnystormy** [LMMS/lmms#2504] opened 2016-01-06 22:43 UTC
When playing back audio tracks in the Max OS X 1.1.3 version the UI suddenly stops updating within a few seconds. Audio will continue to play, and the buttons on the screen still work, but the time-elapsed labels, mixer, and song editor stop animating/updating properly. I'm wondering if this is a memory allocation and/or threading issue?

I'm running a Mac Mini (Late 2014) with a 1.4 GHz dual-core processor with El Capitan (10.11.2).

Thank you for your help!

**Comment by tresf** [comment] 2016-01-07 03:29
This sounds vaguely similar to a theming issue we used to have with upgraded versions, but not identical since you report this starts after a few seconds of playback.

Does this eventually recover, or just keep having refresh issues?

I've tested on `Lion`, `Mountain Lion`, `Mavericks`, `Yosemite` without this issue, so it may be new with `El Capitan`, which I haven't performed any testing on yet.  @rhunter @follower @jaehyunmicro @eagles051387 are you on El Capitan?  If so, can you reproduce?

**Comment by sunnystormy** [comment] 2016-01-07 14:31
@tresf 
It happens whenever multiple tracks are within scope of the scroller as it's moving inside of the song editor during playback. Both the song-editor, the time-elapsed labels, and the mixer stop animating properly. As the song finishes, the animation returns to normal.

I tested this with "Tectonic", which finishes with only one track playing, and the animation returned to normal speed as the song completed. It's during the middle of playing, when there are multiple tracks with notes in them at the same time, that the animation begins to grind to a halt.

**Comment by follower** [comment] 2016-01-10 15:25
Alas, I'm not on El Cap, so am no help. :)

**Comment by sunnystormy** [comment] 2016-01-15 22:08
@tresf 
Is there a way you could show me how to compile the source on Max OS X so I can test the application with the current source? If this issue has already been fixed, I'll happily take on the task of fixing it myself.

**Comment by Umcaruje** [comment] 2016-01-15 23:31
@sunnystormy Here's an extensive guide on building lmms on OS X: https://github.com/LMMS/lmms/wiki/Compiling-lmms-(Apple)

Hope that helps.

**Comment by sunnystormy** [comment] 2016-02-09 00:20
@tresf 
I've just tested the 1.1.3 version of the application on another laptop with OS X Yosemite, so I've confirmed that the problem isn't hardware-related, and is exclusive to El Capitan.

Is there a way that this could be marked as a bug? Or should I take care of that myself?

**Comment by tresf** [comment] 2016-02-09 01:20
@sunnystormy done although it doesn't necessarily make a difference as to if it will be worked on or not.  Most of our devs don't have Mac environments.  Furthermore, there's little evidence to suggest this is a LMMS bug... It could equally be a bug combo with QT4 + Cocoa (prob worth a try with QT5 soon).

But we'll leave this open until we know more. :+1:

**Comment by sunnystormy** [comment] 2016-02-09 01:53
@tresf 
You make a valid point, it could very well be an issue with its dependencies. Thank you for your help!

**Comment by sunnystormy** [comment] 2016-02-14 21:51
@Umcaruje  @tresf 

I've tried compiling from source but keep getting issues:

>CMake Error at /opt/local/share/cmake-3.4/Modules/FindQt4.cmake:1324 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:160 (FIND_PACKAGE)

I've got the "qt4-mac" package installed via Macports, so this is confusing. Any help would be appreciated! ^_^

**Comment by tresf** [comment] 2016-02-14 21:53
@sunnystormy Homebrew or Macports?

**Comment by sunnystormy** [comment] 2016-02-14 21:54
@tresf 

Macports

**Comment by tresf** [comment] 2016-02-14 22:01
Does it recognize the command `qmake`?  It sounds a bit fishy that it won't find qt4.  Also, did you install each package by hand via [Compiling-lmms-(Apple)#macports](https://github.com/LMMS/lmms/wiki/Compiling-lmms-(Apple)#macports) or did you use the `sudo port install lmms` command?  I ask because sometimes pkgconfig missing can cause strange issues.

We haven't used MacPorts in a while now and my MacPorts machine is out of reach at the moment.  I know Homebrew logic is in good shape.  Do you use MacPorts already or was it just your first choice?

**Comment by sunnystormy** [comment] 2016-02-14 22:06
@tresf No, it doesn't recognize the command "qmake". I installed each package individually, and not by using the "lmms" command. I used Macports simply because it was the one I was the most familiar with. I'm wondering if I need to install the "qt4-creator-mac" package as well?

I'm open-minded to trying other things too, if you have other suggestions.

**Comment by tresf** [comment] 2016-02-14 22:11
`qt4-creator` won't be needed.  It sounds like MacPorts hasn't been added to your environment variables.  Can you confirm that you can install something else with MacPorts and that it is reachable via command line?

**Comment by sunnystormy** [comment] 2016-02-14 22:22
@tresf Would any of the packages I've installed during this process be applicable to what you're asking, like "npm"?

**Comment by sunnystormy** [comment] 2016-02-15 22:25
@tresf Tried installing with Homebrew instead and get the following when trying the shell script:

```
fltk: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
```
What do I do?

**Comment by tresf** [comment] 2016-02-15 22:50
You can turn off fltk (disables Zyn) via `WANT_FLTK` in CMakeLists.txt.  You could try compiling from source too, but probably overkill.

**Comment by sunnystormy** [comment] 2016-02-16 00:16
@tresf But without ZynAddSubFX... that limits a lot of music-composition options. :(

I kind of feel like I'd want to have that as an option.

I'll compile from source just to make sure that this issue is resolved. I guess making sure all of the dependencies are updated will have to follow.

**Comment by tresf** [comment] 2016-02-16 04:04
> without ZynAddSubFX... that limits a lot of music-composition options. :( I kind of feel like I'd want to have that around.

In the context of the bug report "OS X UI hangs during playback", it's irrelevant, which is the only reason I proposed it.

> Now it's not finding "libsndfile" when trying to compile, even though Homebrew says it's installed:

I'm not sure how or why you are having so many problems with compilation.  I have a El Capitan box I can test the build process out on, but it would be several weeks before I'd be able to fire it up and check our tutorial against it.  I build all of the DMGs against Lion because I can't figure out how to get modern builds to run on older OS X releases.

We have a few other Mac developers on here that may be able to help or may have encountered your issues.... @rhunter, @rageboge and probably a few others.

**Comment by sunnystormy** [comment] 2016-02-16 12:26
@tresf Cool, man! Wasn't trying to knock you or anything with my ZynAddSubFx comment, I just really love the different plugins available and appreciate the amount of effort you guys have made. : )

I'll take a back seat at this point and see if anybody else has anything to add. Thanks again for all of your help!

**Comment by tresf** [comment] 2016-02-16 14:50
@sunnystormy Just to give you some more troubleshooting information... 

We have a build fire on OS X each time a code submission comes in which is run by Travis-CI.

The build process is as follows:

1. https://github.com/LMMS/lmms/blob/master/.travis/osx..install.sh
2. https://github.com/LMMS/lmms/blob/master/.travis/osx..script.sh

To see what the output of one of these commands looks like:
* https://travis-ci.org/LMMS/lmms/jobs/109592863

I believe this build is being fired on [Mavericks, but I'm having a hard time confirming this](https://docs.travis-ci.com/user/osx-ci-environment/) so if your issue is related to the OS X version, getting another dev to try out the build process is the fastest way to get this going. :+1:

**Comment by rageboge** [comment] 2016-02-16 22:56
I'm on El Capitan 10.11.3 and the build is working fine for me.
I had a problem with qt4-mac, as reported in [macports ticket](https://trac.macports.org/ticket/49629) they removed the link to the qmake in favor of a qt_chooser port that is not yet officially available, so I had to create 2 links manually (I have only qt4, no need to dynamically select the qt version).

```bash
sudo ln -s /opt/local/libexec/qt4/bin/qmake /opt/local/bin/qmake   
sudo ln -s /opt/local/libexec/qt4/bin/lrelease /opt/local/bin/lrelease
```
I also had to create a new build folder from scratch, but you shouldn't have the same issue if it is the first time you build it.
My ports are up-to-date.

**Comment by tresf** [comment] 2016-02-17 03:40
@sunnystormy 

Silly question, but did you properly install the XCode command line tools via `sudo xcode-select --install`?  There can be some very strange errors if they're not and these are listed as [prerequisites in the install instrucitons](https://github.com/LMMS/lmms/wiki/Compiling-lmms-(Apple)).

I'm running Brew + El Capitan right now.  It'll take a day or so, I'll report my progress. :beer:

**Comment by tresf** [comment] 2016-02-17 04:04
@sunnystormy 

Ok, I'm running into build issues too, and they appear to be related to upgrading my OS from Yosemite to El Capitan without reinstalling XCode.  Perhaps that helps... Continuing. :+1:

**Comment by sunnystormy** [comment] 2016-02-17 16:56
@tresf Just so you know, I didn't install Xcode on my device until after I upgraded the OS. I also have the command-line tools installed. Hope that helps.

**Comment by tresf** [comment] 2016-02-17 17:54
> @tresf Just so you know, I didn't install Xcode on my device until after I upgraded the OS. I also have the command-line tools installed. Hope that helps.

Yes it does.  I've added the hint to our tutorial anyways because it just snagged me.  My El Capitan environment won't download XCode, so I'm troubleshooting that still. :wine_glass:

**Comment by tresf** [comment] 2016-02-18 21:07
@sunnystormy After reinstalling XCode (I chose 7.3 beta for this particular machine) the build is starting... 

![image](https://cloud.githubusercontent.com/assets/6345473/13158144/9bfbbde8-d659-11e5-8b8c-3ccfc24d7c97.png)

If you'd like I can upload the build for you to try out to see if it resolves the refresh issues you are encountering.

**Comment by sunnystormy** [comment] 2016-02-18 22:34
@tresf That sounds great! I will happily download it when you're ready. :+1:

**Comment by tresf** [comment] 2016-02-18 22:54
Well, it runs fine, but the DMG ended up being 500MB compressed so something is horribly wrong with my packaging process.

I'll work on it some more and upload a release when ready.

FYI, I'm building our master branch currently.  I can supply 1.1.3-stable instead if you'd like although my intentions originally were to vet out the build process, which I can confirm is working fine on El Capitan (although I'll have to double check on the packaging process now).

Also, unrelated, but `make dmg` needs to depend on `make install`, so that's another fix needed.

**Comment by tresf** [comment] 2016-02-19 03:01
Ok, it took completely uninstalling Homebrew, but I've reproduced the `fltk` issue.... Will post updates/update wiki as I get them... 

```
🍺  /usr/local/Cellar/portaudio/19.20140130: 30 files, 448.7K
fltk: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

**Comment by tresf** [comment] 2016-02-19 05:42
@sunnystormy I've added instructions for circumventing the fltk installation problem and added them to the build wiki.  I'll continue and report back my findings.

**Comment by tresf** [comment] 2016-02-19 15:09
@sunnystormy I've documented the remaining steps in the tutorial.  It appears in addition to the `fltk` upstream bug, the packages `cmake` and `pkgconfig` were missing from the travis script.  Closing, marking as resolved.

@Lukas-W do you have any objections to adding these deps to the travis script?  Also, do you have any objections to changing `brew install` to `brew reinstall` I understand they probably aren't needed

**Comment by tresf** [comment] 2016-02-19 15:27
Oh, and the DMG I promised... https://github.com/tresf/lmms/releases/download/v1.1.90-test/lmms-1.1.90-mac10.11.dmg

**Comment by Lukas-W** [comment] 2016-02-19 20:28
> do you have any objections

Nope

**Comment by tresf** [comment] 2016-02-19 21:39
> Nope

Thanks.  Fired the changes via #2595.

**Comment by sunnystormy** [comment] 2016-02-19 23:48
@tresf Downloaded your build and the issue still exists. :(
I'll try building this on my own sometime later to see if a local build helps fix the problem.

**Comment by tresf** [comment] 2016-02-20 15:53
> @tresf Could you please upload a build of one of the stable versions for testing? Thank you.

Unfortunately, if it doesn't work with `master`, it won't work with `stable-1.1.3` either and I can't reproduce the problem in my El Capitan VM.  I do have a physical machine I can upgrade to test this redrawing bug out.  I'll start the El Capitan upgrade process right now to see if I can reproduce this.

**Comment by tresf** [comment] 2016-02-20 19:04
@sunnystormy, I just upgraded my physical box to OS X 10.11 "El Capitan" as well and did a fresh install of `lmms-1.1.3-10.7.dmg` from our downloads page. I still cannot reproduce.  Here are my test results:

https://youtu.be/Dkw1iUwuYow

**Comment by tresf** [comment] 2016-02-20 19:58
I used QuickTime for screen capture.

**Comment by tresf** [comment] 2016-02-20 20:01
Almost, do either/both machines have any 3rd party components from QT installed globally? Perhaps MacPorts/homebrew conflict, etc?  There a command on Mac to show the DYLIBs in use, but I'll have to look it up.

**Comment by sunnystormy** [comment] 2016-02-20 20:05
@tresf This problem was occurring prior to installing anything related to that. Also, I've created the quicktime screen-capture to demonstrate the issue. How would you like me to send it to you? It's ~90MB in size.

**Comment by tresf** [comment] 2016-02-20 20:09
Google drive, drop box, YouTube, whatever. :+1:

**Comment by sunnystormy** [comment] 2016-02-20 20:15
@tresf Dropbox link to video is: https://www.dropbox.com/s/ms7i9dnfssau3ck/LMMS_2504.mov?dl=0

**Comment by tresf** [comment] 2016-02-20 21:11
Does the same thing happen if you are composing a new track?  That looks like the software is working ok at first, but running very, very slow as it gets deeper into the track.

**Comment by sunnystormy** [comment] 2016-02-20 22:21
@tresf Yes. But only when there are multiple tracks playing at the same time on the song editor.

**Comment by tresf** [comment] 2016-02-21 01:37
@sunnystormy I can confirm this track performs equally as bad on my machine.  Looking at the CPU, it spikes from 25% - 50% depending.  Some tracks play OK, but once the CPU goes over 25% the GUI doesn't refresh very well.  Sometimes the EQ hangs for seconds at a time.

Is this a bug?  Probably.  Is it new to El Capitan?  I don't know, we'd have to do some much more specific benchmarks on physical hardware with various OS X versions to know for sure.

Here are some conversations on how we don't utilize CPU very efficiently... #2295 #1916 https://github.com/LMMS/lmms/issues/1600#issuecomment-69782663 https://github.com/LMMS/lmms/issues/643#issuecomment-41467413

If you know a thing or two about debugging, we'd be happy to get some benchmarks on where/why our resources are out of control on OS X. :+1:

**Comment by sunnystormy** [comment] 2016-02-21 02:02
@tresf Should this ticket remain closed, then? Or should we simply defer it to other tickets, like the ones you mentioned?

**Comment by tresf** [comment] 2016-02-21 03:10
:beer:

**Comment by eagles051387** [comment] 2016-02-21 10:30
Probably a stupid question here, but has anyone tried to open the code base
in xcode and run it through the profiler that is part of xcode? Reason I am
asking is that I think it would be useful as well to allow it as an IDE to
provide code hints as well that could help us pinpoint issues for mac users.

I will submit another ticket about creating an xcode project for mac
developers.

This email has been sent from a virus-free computer protected by Avast.
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Jonathan Aquilina

**Comment by tresf** [comment] 2016-02-21 17:03
@eagles051387 yes, please do.  When you have working instructions for debugging in XCode (or even QTCreator), I'll happily test them out and publish them to our wiki.

If you would please write them in markdown format (e.g. on your fork) that would be a great start.

**Comment by tresf** [comment] 2016-02-21 17:05
> I will submit another ticket about creating an xcode project for mac developers.

Please do not create additional tickets for this.  We don't have intructions for .NET either, let's take this one step at a  time.

**Comment by tresf** [comment] 2016-02-24 16:47
@eagles051387 any progress with the debugging process instructions?

**Comment by eagles051387** [comment] 2016-02-24 16:50
Just unwinding after a crazy day at work, Will be trying to get it sorted
soon.

This email has been sent from a virus-free computer protected by Avast.
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Jonathan Aquilina

**Comment by tresf** [comment] 2016-02-24 20:42
@sunnystormy I've added a Qt5 build here for troubleshooting:  [`tresf/lmms-1.1.90.1-gb55b1ab-mac10.11-qt5.dmg`](https://github.com/tresf/lmms/releases/download/v1.1.90-test/lmms-1.1.90.1-gb55b1ab-mac10.11-qt5.dmg).

Warning, the settings dialog is a burden to click if you've purged `~.lmmsrc.xml`.  Probably worth opening a new bug report for, but wanted to warn you about it if you're testing on a machine that hasn't had LMMS installed before.

**Comment by sunnystormy** [comment] 2016-02-24 23:45
@tresf Success! :smile: 

The interface responds appropriately, and everything seems to be working smoothly. Thank you for this QT5 build!

**Comment by tresf** [comment] 2016-02-25 00:57
@sunnystormy Ok great.  We'll attribute it to Qt4 + OSX 10.11 then and close this out since we can't directly fix it.  If we can iron out all of the bugs with QT5 we may be able to switch to it for our 1.2 build, but we don't have a whole lot of testing results yet.

 * For starters, the whole splash screen covering the dialogs needs to be patched.  I'm working on packaging Windows using Qt5 now to see if that bug is reproducible there.
 * Furthermore, the build environment we're currently using (I'm using) has always been Lion for backwards compatibility, but per https://github.com/Homebrew/homebrew/issues/45284, Mountain Lion or higher is needed for Qt5, so it will be some additional work before setting up that build environment.

**Closed by tresf** 2016-02-25 00:57 UTC
Labels: bug, gui
