### ISSUE TITLE
Canot have two independant patterns in Song Editor

### ISSUE THREAD

**Issue by worikgh** [LMMS/lmms#6352] opened 2022-03-29 07:19 UTC
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.

### Bug Summary
Two patterns in sonfg edtor interfere with each other

#### Steps to reproduce
Start with empty song editor

Add a pattern-track

Add a pattern using the `kick-power` instrument there by default

Add another pattern track

Edit it and replace `kick-power` with `clap`

Edit in a pattern (a different pattern)

Close pattern-editor

First pattern has now lost its pattern and the `kixck-power` is replaced by a `clap`
#### Expected behavior

Two independant patterns with differenty instruments

#### Screenshot
![image](https://user-images.githubusercontent.com/5387413/160555409-3b8c1be8-1821-477a-b3dc-c3e43bb3e47e.png)
![image](https://user-images.githubusercontent.com/5387413/160555621-5d23963e-db5b-4848-b583-581c97751842.png)

#### Affected LMMS versions

Version 1.3.0-alpha.1.175+g54bee2272 (Linux/arm32, Qt 5.11.3, GCC 8.3.0).

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by Spekular** [comment] 2022-03-29 10:03
Duplicate of #453

**Closed by Spekular** 2022-03-29 10:03 UTC
Labels: bug
