### ISSUE TITLE
Native Linux VST loading

### ISSUE THREAD

**Issue by IGBC** [LMMS/lmms#5742] opened 2020-10-29 04:39 UTC
Why Can't vestige load a native Linux VST on Linux?

#### Steps to reproduce
forcibly enter the name of a valid Linux .so format VST into Vestige

#### Expected behavior
Plugin Loads, after all it's a Linux plugin, running on a Linux system

#### Actual behavior
LMMS locks up.

#### Affected LMMS versions
lmms 1.2.2-2 (what Arch is shipping RN)

#### Logs
```
*** WEAK-JACK: initializing
*** WEAK-JACK: OK. (0)
Notice: could not set realtime priority.
Cannot load library /usr/lib/lmms/libcarlabase.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /usr/lib/lmms/libcarlapatchbay.so: (libcarlabase.so: cannot open shared object file: No such file or directory)
Cannot load library /usr/lib/lmms/libcarlarack.so: (libcarlabase.so: cannot open shared object file: No such file or directory)
/usr/lib/lmms/RemoteVstPlugin: line 36: exec: wine: not found
remote plugin died! invalidating now.

^C (Killed by user)
```

**Comment by IanCaio** [comment] 2020-10-29 04:48
Closing this issue as this is not a bug: Vestige uses Wine to load Windows VST2 plugins, not Linux VST3 (which are not supported right now). Currently you can load Lv2 and VST3 instruments/effects through Carla though. Native Lv2 support is also being worked on at the moment.

**Closed by IanCaio** 2020-10-29 04:48 UTC
Labels: bug

**Comment by Spekular** [comment] 2020-10-29 11:40
This is also a duplicate of #416
