### ISSUE TITLE
Fonts of LMMS 1.2.0-rc4 are blurry on Windows compared to 1.2.0-rc2

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#3980] opened 2017-11-17 21:46 UTC
The fonts of LMMS 1.2.0-rc4 look quite blurry on my Windows 8.1 machine. Here's rc4 (click the image for full resolution to better see the differences):
![lmms-1 2 0-rc4-fontsblurry](https://user-images.githubusercontent.com/9293269/32970178-2e4541bc-cbe8-11e7-853f-a66fca8235a0.png)

And for comparison here's rc2:
![lmms-1 2 0-rc2-fontssharp](https://user-images.githubusercontent.com/9293269/32970186-3929457e-cbe8-11e7-9f6f-dcd34fc65b06.png)

Guess it has to do with the automatic scaling for HDPI displays that got activated some time ago if I remember correctly. My monitor is a DELL UltraSharp U2515H with a resolution of 2560x1440 and 117.5 DPI.

**Comment by tresf** [comment] 2017-11-17 21:56
Yes, this is intentional until we can add proper HiDPI support.  More information here: https://github.com/LMMS/lmms/pull/3531

Duplicate of https://github.com/LMMS/lmms/issues/2510.

**Closed by tresf** 2017-11-17 21:56 UTC
