### ISSUE TITLE
In Piano Roll Editor, the selection mouse pointer is not consistent

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4112] opened 2018-01-15 05:07 UTC
The mouse pointer randomly changes between a leftward-tilted arrowhead:

![image](https://user-images.githubusercontent.com/9047168/34927916-d31f983e-f9df-11e7-950d-611a3ccf9f3a.png)

-and a vertical double-headed arrow:
![image](https://user-images.githubusercontent.com/9047168/34927921-dccc25e6-f9df-11e7-8ed3-aa9cf7d8dd3c.png)

**Desired:** Use only one shape.

**Comment by Sawuare** [comment] 2018-01-15 15:37
The pointer shape in the first image is the desired shape.
The pointer shape in the second image, in this particular case, is a bug. It happens when the pointer gets in the note velocity/panning editing area at the bottom, and gets out, with the same pointer shape of that area.

**Comment by zonkmachine** [comment] 2018-01-17 14:38
I believe this is a duplicate of https://github.com/LMMS/lmms/issues/3306

**Closed by zonkmachine** 2018-01-17 14:38 UTC
Labels: bug, duplicate
