### ISSUE TITLE
Plugins crash lmms due to name clash

### ISSUE THREAD

**Issue by dsonck92** [LMMS/lmms#2223] opened 2015-07-29 22:38 UTC
Currently I have the issue where showing the ZynAddSubFX plugin caused lmms to crash. When inspecting this issue with QtCreator and trying different Qt versions (even Qt5), I discovered that it crashed due to the deletion of m_ioEngine.

When inspecting the stack trace, the crash occurred because the deletion triggered the QObject destructor. Somehow AudioOut and/or MidiIn became a subclass of the global Engine which is in charge of keeping the lmms state, and not a subclass of the Engine defined in Nio/Engine.h. I decided to put the lmms engine in a namespace to make it hidden to NulEngine which then solved the issue.

It may be useful to check for name clashes or prevent them in advance by defining namespaces for different parts of lmms. I will look if I can make my current changes a bit more clean and perhaps define a namespace for the Nio/ classes rather than the lmms classes (given that more depend on lmms Engine than the nio Engine)

**Comment by tresf** [comment] 2015-07-30 02:40
Thanks.  On our radar per: #2064, #2118

**Comment by tresf** [comment] 2015-08-22 03:21
Duplicate of #2269

**Closed by tresf** 2015-08-22 03:21 UTC
Labels: bug, core
