### ISSUE TITLE
Preview samples with arrow keys.

### ISSUE THREAD

**Issue by KimLennings** [LMMS/lmms#5281] opened 2019-10-28 05:08 UTC
Instead of having to click every sample to preview it, make it so that the sample plays when moving up or down using the arrow keys. This is much less strenuous on the hand and wrist when looking through thousands of samples.

**Comment by PhysSong** [comment] 2019-10-28 23:19
Duplicate of #871, see #4877.

**Closed by PhysSong** 2019-10-28 23:19 UTC
