### ISSUE TITLE
Piano Roll Razor/Glue Tool

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#746] opened 2014-05-21 08:55 UTC
Sometimes the ability to easily cut a note in half (or several notes) would save me great amount of Piano-Rolling time. Also the ability to join notes that are touching tail-to-head would be cool.
I think this infographic says it all:

![razor -vs- glue](https://cloud.githubusercontent.com/assets/491704/3037894/0b940c22-e0c6-11e3-8e25-e2634c2cf5b5.png)

**Comment by oeai** [comment] 2015-01-17 21:48
can this be done with menu entry?

**Comment by unfa** [comment] 2015-01-17 22:56
Or toolbar buttons?
17 sty 2015 22:48 "Ra" <notifications@github.com> napisał(a):

**Comment by Reaper10** [comment] 2015-04-12 00:49
this needs to be in song editor and work with the sample track

**Comment by MayuriIsNumberOne** [comment] 2018-05-07 01:55
It's been years and such a feature to independently cut or merge just like in any other DAW is still not available. Any word on this? It's really frustrating that I can't run FL on Wine and LMMS is the only software  really feel comfortable with and it doesn't have that simple feature. It's really frustrating

**Comment by lukas-w** [comment] 2018-05-07 08:26
@MayuriIsNumberOne This project is run by a small number of volunteers. Complaining about the work they do or don't do doesn't help progress and is not tolerated here.

**Comment by vlad1777d** [comment] 2018-05-08 19:15
Also I think, that instrument system in Piano Roll should be reworked.
For example, to be able choosing several notes without switching between pen and frame.

Left mouse button could draw notes, right - remove, and middle - choose notes with a frame.
Or, as alternative, shift + left mouse button could select several notes by a frame.

**Comment by tresf** [comment] 2019-03-11 20:47
@unfa as always, nice bug report but as part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.  We'll use this bug report as a reference when this feature is finally written.

**Comment by zonkmachine** [comment] 2020-05-24 10:14
This issue was accidentally closed with #5216

**Comment by Spekular** [comment] 2020-05-24 10:50
It was closed even before then since it's consolidated ;)

**Comment by zonkmachine** [comment] 2020-05-24 10:53
;)

**Comment by tresf** [comment] 2020-05-26 17:50
> It was closed even before then since it's consolidated ;)

As the closer of many of these types of bug reports, feel free to reopen whatever you want.  That consolidation was mean to cleanup the hundreds of redundant or never worked on issues.  If something's finally active, it's often nice to reopen the bug report to encourage feedback, etc.

**Comment by oeai** [comment] 2020-05-26 18:03
Sorry guys, it's an offtopic here, but i just received that thread and it is not so much popular as discord, so i'd like to ask you first here.
you know virus etc i designed a mask from paper [https://imgur.com/a/hARRvOI](https://imgur.com/a/hARRvOI)
![mask2en](https://user-images.githubusercontent.com/2557665/82934431-1d134600-9f94-11ea-9b3c-65f26a91d7a4.jpg)
it makes mask more hermetic, so if you don't have a better one, it would be better to use it, but also to your fans and many more people.

**Comment by zonkmachine** [comment] 2020-05-26 18:11
> it's an offtopic here

Yes, that is off topic anywhere on lmms github pages.

**Comment by oeai** [comment] 2020-05-26 18:16
Well it's DIY and you can use Glue i guess .' )

**Comment by zonkmachine** [comment] 2020-05-26 18:19
The old lmms forum has one of those virus threads. Post this there. Not here.

**Comment by zonkmachine** [comment] 2020-05-26 18:23
Thread cleared from off topic content.

**Comment by oeai** [comment] 2020-05-26 18:35
> 
> 
> Thread cleared from off topic content.

this could save someone life and the machine deleted that... that's why they hate machines

**Comment by tresf** [comment] 2020-05-26 18:46
Admins, FYI, you can hide comments too.  @oeai we have a strict policy against off-topic content.  Your contributions to the tracker are valuable, but let's treat it as a bug tracker and use the forums for other items as zonk has recommended, otherwise we'll be forced to remove the access. ❤️

**Comment by tresf** [comment] 2021-02-26 18:46
Repoening per (merged) #4998, #5721, #5845

Pending: #5524

Special thanks to @Spekular, @zonkmachine, @cyber-bridge and reviewers @IanCaio, @russiankumar.

**Comment by allejok96** [comment] 2021-07-24 05:32
Don't know if this is the right time/place, but I just realized that when moving or resizing notes in piano roll or clips in song editor **Alt** is the key to disable quantization. But in the song editor razor it was implemented using **Shift**, and then piano roll razor followed that. So the keyboard logic has been forked (yay).

**Comment by Spekular** [comment] 2021-07-24 05:34
> Don't know if this is the right time/place, but I just realized that when moving or resizing notes in piano roll or clips in song editor **Alt** is the key to disable quantization. But in the song editor razor it was implemented using **Shift**, and then piano roll razor followed that. So the keyboard logic has been forked (yay).

No, it's alt when cutting sample clips. Shift snaps to distance from clip start/end, as opposed to absolute positions.

**Comment by allejok96** [comment] 2021-07-24 05:43
Oh sorry, you're right, I got it all wrong. Alt/Ctrl in SongEditor, but only Ctrl in PianoRoll.

(Any reason for using both Ctrl/Alt? Mac users??)

**Comment by Spekular** [comment] 2021-07-24 05:49
Alt is more convenient since it's a dedicated key, but IIRC the issue is that some linux setups hijack alt+drag to move windows around. Unfortunately ctrl+drag conflicts with the current SE clone shortcut, so you have to click first, then drag. (Which highlights another inconsistency, ctrl vs shift drag to clone clips vs notes).

**Comment by DomClark** [comment] 2021-08-16 19:49
Can this issue be closed again now?

**Comment by Spekular** [comment] 2021-08-16 20:06
Yes, I think so.

**Closed by Spekular** 2021-08-16 20:06 UTC
Labels: enhancement
