### ISSUE TITLE
Crash when opening  projects

### ISSUE THREAD

**Issue by curlymorphic** [LMMS/lmms#4418] opened 2018-06-10 18:52 UTC
While trying to open the demo song "Unfa - Spoken" lmms closes, displaying the following line in the terminal

symbol lookup error: /home/curlymorphic/dev/lmms/lmmaster/build-lmms-Desktop-Debug/plugins/ladspa/sc4_1882.so: undefined symbol: _ZGVbN4v___expf_finite

git master 10 june 2017 commit 1bdaafc4889db9195cef236d7efbea742a607f5e 
Ubuntu studio 18.10 

Symbol lookup errors have also been reported on discord when loading TAP plugins

**Comment by lukas-w** [comment] 2018-06-10 19:03
Closing as duplicate of #4030. Please reopen if that's mistaken.

**Closed by lukas-w** 2018-06-10 19:03 UTC
