### ISSUE TITLE
Colored patterns

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2314] opened 2015-09-04 20:29 UTC
It would be cool if we could personalize the patterns instead of having one color for each type (Automatization, bb, sample tracks and tracks) 

Like so:

http://i.imgur.com/r9pDs1k.png

**Comment by Wallacoloo** [comment] 2015-09-04 20:44
Interesting. This idea needs to be fleshed out a bit more. Is there benefit in being able to color individual note-blocks? Or should we only color all note-blocks of the same instrument identically, as in your screenshot?

**Comment by IvanMaldonado** [comment] 2015-09-04 20:50
We should be able to color individual note blocks so we can color the patterns according to our needs, Pads, chords, bass, leads, etc, we could identify each one by just using colors, and letting the user to choose these colors make this a matter of personal preferency.

**Comment by Spekular** [comment] 2015-09-05 07:50
@tresf should I add this to #1665 ?

**Comment by musikBear** [comment] 2015-09-05 11:13
doublet of : #560 & #1160 amo - both references was closed
-imo it would benefit lmms with both user-colors *and* comment-tracks :+1:

**Comment by tresf** [comment] 2015-09-06 05:09
Duplicate of #1176 which was consolidated (technically still open, but moved to a mega thread).  In regards to updating #1665, I try to link all relevant bug reports to their parent which helps illustrate demand and severity.  I.e. 

**Mega thread**
 * Foo `#123` `#456` `#789`
 * Bar `#678`

This illustrates Foo is more demanded than Bar.

**Closed by tresf** 2015-09-06 05:09 UTC

**Comment by Wallacoloo** [comment] 2015-09-06 05:25
Oh! Sorry if I threw anyone off with my first comment. I was unaware that LMMS allowed one to color B/B patterns!

Seems like this is just an issue of moving the color functionality out of the `BBTCOView` class and into the `TrackContentObjectView` class so that it can be applied to all types of TCOs.

**Comment by tresf** [comment] 2015-09-06 05:34
@Wallacoloo partly.

The colored pattern idea has had some controversy over the years as Vesa had some concerns with backwards compatibilty, dark/light theme support etc and was mostly against the idea.

I've done the shades and tints before in software with great success using some lumens-style assumptions as well as some assumptions about a theme being either dark or light (gray can kill these things) but I agree that it partially exists and should be completely doable.

-Tres

**Comment by musikBear** [comment] 2015-09-06 10:31
> and should be completely doable.

imo , then **do** - users dont have to use if they dont like -its not mandatory at all -right?
