### ISSUE TITLE
Cannot find VeSTige on Linux

### ISSUE THREAD

**Issue by crazyBaboon** [LMMS/lmms#3164] opened 2016-12-17 12:26 UTC
Cannot find the Vestige instrument on Linux. Tried openSuse, Arch, Antergos from their repos (lmms version 1.1.3) . I also compiled the source code from https://github.com/LMMS/lmms/wiki/Compiling-lmms and ran ./lmms and still I could not find the Vestige on the instruments panel (this release I compiled from source code was 1.2.0-rc2).

**Comment by karmux** [comment] 2016-12-17 13:27
Does `cmake ..` says OK about these before compilation?
```
* VST-instrument hoster       : OK
* VST-effect hoster           : OK
```
Which wine packages you have installed?

**Comment by musikBear** [comment] 2016-12-17 14:02
A person with **in depth** knowledge of linux, all the pesty variants and distros *really* need to write a *good* update on this article:
https://lmms.io/wiki/index.php?title=Working_with_VSTs#VSTs_.26_Linux
* What is *wrong* in the article?
* What is missing?


Failing of VST in linux is simply the most common Q on forum, and i have NO insight in the 101 various distros wines and the whatnot in that (imo) absurdly mash of *nonsense*, that has resulted in the un-controlled linux community

**Comment by tresf** [comment] 2016-12-17 17:03
@crazyBaboon can you take a look at this thread and let us know if it helps?

https://github.com/LMMS/lmms/issues/3129#issuecomment-261964858

**Comment by crazyBaboon** [comment] 2016-12-19 21:44
I am unsure about arch and Antergos at the moment, but most likely that is an issue with Wine and not LMMS itself. I don't know. I was able to get Vestige on Ubuntu 16.04 by running the instructions on the following (kinda old, but still working): http://nickhumphreyit.blogspot.pt/2013/01/ubuntu-precise-1204-how-to-install-lmms.html

**Comment by ositanachi** [comment] 2016-12-31 08:33
Has there been any updates to this issue? I'm running Antergos (might try my other laptop) but I've only managed to get VeSTige through wine (downloading the lmms exe).

**Comment by tresf** [comment] 2016-12-31 14:56
@ositanachi were able to resolve this same problem in https://github.com/LMMS/lmms/issues/3129#issuecomment-261964858.  Can you see if the cause is similar?

**Comment by jasonMisaq** [comment] 2017-01-13 09:43
@karmux I believe you will be fine using VSTs and getting Vestige to work in your LMMS if you install both 64 bit and 32 bit versions of Wine for your Linux distro. Please check it out and let me know if the problem is solved.

**Comment by karmux** [comment] 2017-01-13 09:51
@jasonMisaq you probably wanted to tag @crazyBaboon instead.

**Comment by jasonMisaq** [comment] 2017-01-13 10:47
Oh sorry @karmux you're right. I edited the tag. Thanks

**Comment by lukas-w** [comment] 2019-03-09 17:44
Closing as support request.

**Closed by lukas-w** 2019-03-09 17:44 UTC
