### ISSUE TITLE
Exports starts at the very beginning and not at the beginning of the loop.

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2965] opened 2016-08-09 15:38 UTC
I have a song which doesn't start at the very beginning of the song editor.
I set a loop point to be able to start at the beginning of the song  and loop back to the beginning of the song when the end is reached.
When I export the song, it begins with a silent part (18 seconds, the duration between the very beginning of the song editor and the beginning of the loop area). The export should have started directly at the beginning of the loop area ...
The test has been performed on lmms-1.1.3.

**Comment by zonkmachine** [comment] 2016-08-09 18:14
Confirmed. I think that's how it's been intended. The "Loop points" are only for playback while working on a project. The "Export as Loop" in this case means: "Drop trailing reverb/delay".
"Export between loop-points" sounds like a good thing to implement though. This may actually be planned already.

**Comment by zonkmachine** [comment] 2016-08-09 18:52
This is already implemented in current master and will be in next release, 1.2

**Closed by zonkmachine** 2016-08-09 18:52 UTC
Labels: enhancement

**Comment by ycollet** [comment] 2016-08-10 06:33
Thanks for these explanations.
