### ISSUE TITLE
No preview for beat/bassline

### ISSUE THREAD

**Issue by liftarn** [LMMS/lmms#1263] opened 2014-11-03 12:50 UTC
Both piano rolls and sample tracks have previews, but not the beat/bassline.

Example: http://lmms.sourceforge.net/screenshots/1.0.0/lmms-1.0.0-1.png

**Comment by tresf** [comment] 2015-03-08 18:21
Marking as duplicate of the "Cusis Theme" effort #1839 and closing to consolidate bug reports.

**Closed by tresf** 2015-03-08 18:21 UTC
Labels: duplicate, enhancement
