### ISSUE TITLE
LMMS crashing by Piano roll resizing in 4K

### ISSUE THREAD

**Issue by WinLin97** [LMMS/lmms#4592] opened 2018-09-12 18:20 UTC
Hi!

This not requires any comment:
https://drive.google.com/open?id=1MDNOvZvRTRZpmg5Tu_P8EAR6eOXfGYgO

How to recreate?
1. Open LMMS (on fullscreen 4K)
2. Open Piano roll and maximize or resize the window to max vertically.
3. Tadam! LMMS crashed!

**Comment by PhysSong** [comment] 2018-09-13 10:46
Duplicate of #4098.

**Closed by PhysSong** 2018-09-13 10:46 UTC
