### ISSUE TITLE
Windows marked "Stay on Top" cause maximized windows to behave similarly

### ISSUE THREAD

**Issue by Pyrif** [LMMS/lmms#4875] opened 2019-03-04 21:05 UTC
This is an issue I've experienced since RC5 to present in RC8.

To replicate:
-Open LMMS
-Maximize the song editor window
-Open an instrument track window
-Mark the instrument track window as "Stay on Top"
-Double-click on any pattern or empty space on the song editor that opens a new window (Piano Roll, Automation Editor)

There are two possible outcomes:
A. Assuming the new window starts maximized, the icon of this window will appear in the top-left corner of the program and function as intended, but no other graphics from the new window will be written to the screen, and the song editor will grab all inputs.
B. Assuming the new window starts windowed, the graphics of the window will be written to the screen, but when clicked on, will fall behind the song editor window (or whichever window was already maximized).

This "greedy" maximized window behavior has been a nuisance to me, but until now, I was uncertain of how to replicate it.

RC5 & RC8, Win10

**Comment by DomClark** [comment] 2019-03-05 00:11
Sounds similar to #4183. I would guess this is a Qt bug.

**Comment by tresf** [comment] 2019-03-06 16:50
@DomClark did we ever test the fix that worked on Carla/MacOS? https://github.com/LMMS/lmms/pull/4558#issuecomment-421570687

**Comment by DomClark** [comment] 2019-03-06 17:19
I can't reproduce this following the steps above. However, if I first load a VST with embedding enabled, then I can reproduce this starting from the second step (that is, without opening a new LMMS instance). This behaviour occurs even if the VST is removed. @Pyrif Is this the behaviour you observe? Are you sure you can reproduce this before any VST is loaded?

> did we ever test the fix that worked on Carla/MacOS? #4558 (comment)

In relation to this issue and/or #4183? I haven't, but I guess it would work. It would, however, have the unfortunate side-effect that VST embedding would no longer be possible. The issue appears to be with how Qt handles always-on-top behaviour with MDI windows that have native peers, i.e. not very well. I don't think we can address this for 1.2 without impacting existing functionality; I guess we just have to weigh up what is more important here, VST embedding or bug-free always-on-top behaviour. Given that one can turn off VST embedding, we have a workaround available already for those who need it, so I think we should leave this alone for the moment. Unless Pyrif demonstrates otherwise, I think this should be closed as a duplicate of #4183.

If I have the time and ambition at some point, I might look into the Qt bug itself, since they haven't got round to it yet.

**Comment by tresf** [comment] 2019-03-06 17:31
>  I think this should be closed as a duplicate of #4183.

Done.

**Closed by tresf** 2019-03-06 17:32 UTC
Labels: vst
