### ISSUE TITLE
LMMS file clips when closed during playback

### ISSUE THREAD

**Issue by JordanKyser** [LMMS/lmms#3756] opened 2017-08-06 18:02 UTC
This is a bug that I have experienced in 1.2.0-rc2 and 1.2.0-rc3, and may have experienced the bug in 1.1.3, but I may want somebody to test this bug in 1.1.3 just to clarify.

If you close LMMS while on playback, and there is some audio that is being played in the window, it starts to clip until you restart your PC/Mac. I don't know if this is one of those dev bugs, if that is the case, then we should still both figure out how to fix the bug and find a resolution to resolve the issue if the bug persists.

**Comment by gi0e5b06** [comment] 2017-08-06 18:57
Windows only?

**Comment by JordanKyser** [comment] 2017-08-06 20:41
I guess, but Mac users with at least one of the three versions mentioned are welcome to test this bug.

**Comment by musikBear** [comment] 2017-08-07 13:19
Cant reproduce on rc3 win 32 xp with sample-track 
Actually, it could be a sound-card thing
Not sure 'our bug'

**Comment by Sawuare** [comment] 2017-08-18 20:23
Can't re-produce using Windows 10 Pro, 64-bit OS, x64-based processor with LMMS 1.2.0-rc.3.
Actually, closing LMMS while playing audio doesn't produce any audio glitches and is very smooth for me.

@JordanKyser 
I you can re-produce it successfully, can you provide steps for doing so?
Like what @musikBear said, this is probably a problem with your audio system.

**Comment by softrabbit** [comment] 2017-09-10 20:24
I believe one important question here is **which audio output system are you using**? Is it sdl, portaudio, sndio...?

**Comment by zonkmachine** [comment] 2017-12-27 17:11
@JordanKyser Please answer the questions above ^ ^^

**Comment by tresf** [comment] 2018-03-06 22:28
No answer in months, closing.  Please request a re-open when we have exact steps to reproduce.  Note, since this is likely the audio-backend and the audio driver interacting sporadically, we should make sure to detail the exact setup to cause this as well as steps to reproduce, even if those steps are e.g. "Close while playing 20 times, it will eventually happen".

**Closed by tresf** 2018-03-06 22:28 UTC
Labels: needs clarification
