### ISSUE TITLE
"Wave Shaper" effect broken.

### ISSUE THREAD

**Issue by krobbi** [LMMS/lmms#5909] opened 2021-02-14 19:58 UTC
### Bug Summary
The effect "waveshaper" does not behave as expected compared to previous versions.

#### Steps to reproduce
1. Open any project in LMMS 1.3.0-alpha.1.
2. Place the "wave shaper" effect on any sound.
3. The sound will be highly distorted if a "waveshape" knob is set to -1 or below.
4. The sound will quickly fade when the knob is set above 1.
5. There is no effect on the sound if the knob is between -1 and 1.

#### Expected behavior
Lowering the "waveshape" knob in the "wave shaper" effect gradually increases distortion, and increasing the knob fades out the sound, while additionally causing some distortion, as seen in previous versions of LMMS.

#### Actual behavior
The knob has no effect between the values -1 and 1, causes intense distortions when set to -1 or below, and quickly fades out the sound it is applied to when set above 1.

#### Screenshot
![image](https://user-images.githubusercontent.com/70552146/107887514-970ea500-6efe-11eb-8ee1-8c36aacdbcd9.png)

#### Affected LMMS versions
Affects LMMS 1.3.0-alpha.1.33+g4f74151f0 when installed over LMMS 1.2.2.
Standalone installation of LMMS 1.3.0-alpha.1 has not been tested.

#### Logs
N/A

**Comment by zonkmachine** [comment] 2021-02-14 21:06
Confirmed. This is the same issue that was fixed in stable-1.2 in https://github.com/LMMS/lmms/pull/3927 . We have since then moved most of the ladspa effects into submodules and even though this fix was merged upstream the https://github.com/LMMS/lmms/tree/master/plugins/LadspaEffect/swh directory points to a [commit prior](https://github.com/swh/ladspa/tree/692b4001120aea16385d74ce86b0865c6ce7fdf5) to when this fix was merged.
@tresf

**Comment by zonkmachine** [comment] 2021-02-14 21:09
Also, the swh lv2 version see the same issue and it has not been fixed upstream.

**Comment by PhysSong** [comment] 2021-06-04 03:45
It's probably the time to update the swh submodule.

**Comment by tresf** [comment] 2021-06-04 04:14
PR submitted #6040

**Comment by tresf** [comment] 2021-06-04 04:41
Is someone willing to test the desktop installers for the presence/absence of this bug so that we can merge?  They're here: https://github.com/LMMS/lmms/pull/6040#issuecomment-854348864

**Comment by Sawuare** [comment] 2021-06-04 06:13
@tresf There is no sudden crazy distortion below -1 now.

**Comment by Sawuare** [comment] 2021-06-04 06:17
> The sound will quickly fade when the knob is set above 1.

The same happens in 1.2.2.

> There is no effect on the sound if the knob is between -1 and 1.

There is no effect in 1.2.2 either.

I'm not familiar with the plugin or its history so I can't say if those things are bugs or not.

**Comment by tresf** [comment] 2021-06-04 14:34
> @tresf There is no sudden crazy distortion below -1 now.

Ok, that sounds like it fixes that portion of the bug report, essentially making this a duplicate of #3927, but as a regression.

I'll merge the submodule now which will close this bug report.  @krobbi I ask that you reopen a new bug report with any remaining bugs (if any) so that they're not lost when this is closed.

**Closed** 2021-06-04 14:35 UTC
Labels: bug
