### ISSUE TITLE
Play is silent inside piano-roll

### ISSUE THREAD

**Issue by repsej** [LMMS/lmms#1110] opened 2014-08-29 11:11 UTC
Sometimes all notes in a track are silent when pressing play inside the piano roll - but they play fine from the song editor.

Bug found - seems to be ye good ole "off by one" :D

When track(n+1) is muted in the song editor - track(n) is muted inside the piano roll.

Example:

Say I have two tracks: 1) drums and 2) bass

If I mute the bass in the song editor - then the drums are muted when inside the piano roll.

**Comment by tresf** [comment] 2015-01-10 02:35
Bumping to 1.3 because Vesa said we could. :)

**Comment by zonkmachine** [comment] 2015-12-20 23:57
I can reproduce this in 1.0 and 1.1.3 but not in current master f99dba54f913e89c6718c04669d910a6bb0f15fc

**Comment by kungfooman** [comment] 2017-04-12 04:13
I got the same problem in 1.1.3, deleting the Bass Lines fixed it (thanks krafczyk for the info).

**Comment by zonkmachine** [comment] 2017-06-07 01:10
> Oh, I should probably use the Beta version then, since the 1.1.3 seems to be 2 years old.

Correct. You can get the latest 1.2.0-rc3 here: https://lmms.io/download/#windows
Testing is appreciated! :wink:

**Comment by zonkmachine** [comment] 2017-06-07 04:13
This is fixed. Somewhere in the work around LMMS Memory Manager #1088 this was fixed.
I couldn't pinpoint the commit as the build fails around where the Memory Manager was introduced but here are, in my opinion,  the most likely commits to have fixed this.
I'm closing this issue but please reopen if it reappears.

## More likely:


commit 857de8d2c829dc688745f41ba8eddbe148a63a20
Date:   Wed Aug 27 00:59:49 2014 +0300

    Huge structural changes
    Well, this commit got a bit out of hand, what with 26 files changed. Oh well.
    
    Basically, we're using the buffermanager to dispense temporary buffers for playhandles and audioports to use.
    This allows us to change the way playhandles work. Earlier, playhandles of the same track were waiting in line
    to push their output to the audioport. This was of course inefficient, so now they just register themselves to the port,
    then the port handles mixing the buffers.
    
    Caveat: this is still a work in progress, the vol/pan knobs on instruments are temporarily non-functional - will be fixed in
    the next commit, but I have to get some sleep nowcommit 857de8d2c829dc688745f41ba8eddbe148a63a20



commit 1864dcfaa1260e2659c85d1fb63cb2d428e9f1ab
Date:   Fri Aug 29 20:24:24 2014 +0300

    Fix bugs


commit 7bc97f5d5bd9fcb43971f62e546ba464be1e818f
Date:   Sun Aug 31 13:44:28 2014 +0300

    Fixes


## Less likely:

commit dc4bfdc60defdd9b47a21848af70fd350ca7ef28
Date:   Sun Oct 12 00:59:50 2014 +0300

    Various fixes and precautions
    Samplebuffer: reload all samples when samplerate changes. This is because of the way LMMS uses samples: we always resample all samples t$
    LadspaEffect: some safeguards for the non-inplacebroken plugins which use the same buffer for input and output. Theoretically, if some p$
    FxMixer: fix effect processing in multichannel-chains


commit 68b5a21d14352188175b4f95f9041cbaa45b837e
Date:   Tue Sep 2 23:25:05 2014 +0200

    Initialize BufferManager from within Mixer
    
    Avoid crashes caused by worker threads accessing the buffer manager
    before it is initialized. Therefore initialize it from within the
    Mixer constructor which has the side effect that it gets initialized
    in console-only rendering mode as well.


commit 1deb80acc38c4f42a5d7859a8251a9b09caed65a
Date:   Wed Aug 27 23:08:22 2014 +0300

    Finish audioport rehaul, get vol/pan knobs working again, also some bugfixes
    We're now doing the vol/pan stuff in audioport, since this way we avoid the pointless repetition of doing it in the playhandles

**Closed by zonkmachine** 2017-06-07 04:13 UTC
Labels: bug, core
