### ISSUE TITLE
Error Message With VSTHost After LMMS 1.2.0 RC3 Install

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3619] opened 2017-06-08 00:10 UTC
A friend of mine found something and asked if I could mention it here because he does not have an account yet.  I have tried this out as well and experienced the same error.

Using 
Windows 7 (64Bit)
LMMS 1.2.0 RC3 (32Bit)
VSTHost 1.54 / 1.55 / 1.56 (32Bit) (Tried all three versions)

VSTHost works fines, but if you uninstall LMMS 1.2.0 RC2 and install 1.2.0 RC3 when you try to run VSTHost again an error dialog box shows up preventing the program from running at all.

> Unhandled exception "code number" at "code number"
> "bunch of code numbers and equal signs"
> Stack Trace:
> ShowCallStack: DbgHelp DLL missing!
> (Full text has been copied to clipboard)

Not sure if anyone else has experienced this yet?
Not sure why the two of these programs would affect each other, especially because VSTHost is a standalone program (does not install into Windows)

**Comment by musikBear** [comment] 2017-06-08 14:25
Debug Help Library
https://msdn.microsoft.com/en-us/library/windows/desktop/ms679309(v=vs.85).aspx

Cant see why that should have anything to do with either vstHost or lmms

**Comment by tresf** [comment] 2017-06-08 14:46
I downloaded VSTHost 1.5.6 and couldn't reproduce.  I'm not sure technically how LMMS (installed into C:\Program Files\) and VSTHost (extracted to an arbitrary location) can impact each other.  Neither write to system files and neither modify the default `PATH` for Windows.

Furthermore, the bug description is vague.  It should explain exact steps.  For example, if an LMMS project that uses a VST is loaded prior to the crash, it may make the bug more relevant.  Whether you're using 32-bit or 64-bit VSTHost as well as 64-bit LMMS is relevant (don't let us assume).

Regardless, this isn't the VSTHost bug tracker, so you should consider contacting the author of that particular software.

There's also a VSTHostBridge32 and VSTHostBridge64 that is bundled with the software.  If the bug report is specific to those, you need to mention that specifically.

**Comment by musikBear** [comment] 2017-06-09 14:27
Well, something *is* wrong with rc3 in install
I get 3 new error-popups, for 3 different dlls inside the main folder:
libwinpthread-1.dll
Qt5Core.dll
zlib1.dll
And one for
RemoteVstPlugin.exe in the plugin-folder
To me it looks like these files are protected for editing/ deleting
The simple fix is to rename / remove the 4 dll files. It is not even necessary to redo the installationprocess, the popup has a 'retry' option, and the installation of RC3 is smooth and functional, even with these tiny hicups, ofcause the issue needs to be looked at, because some others will not know what to do, and the install should not have these hickups.
@tresf -Was it a x32 you tried with no problems
Did you hard delete all folders (eg got rid of those files, or did you try to install RC3, after a proper **uninstall**?

**Comment by tresf** [comment] 2017-06-09 15:13
> Did you hard delete all folders (eg got rid of those files, or did you try to install RC3, after a proper 

This is the wrong place for this discussion.  If you have problems with the RC3 installer, you need to ask on the support channel on discord and then file a bug.

When DLLs are locked, it's because they're in use.  They aren't protected and our installer does no such thing.  Please keep this on topic.

**Comment by miketurn** [comment] 2017-06-10 00:13
@tresf 
I have updated my initial post with the following
Windows 7 (64Bit)
LMMS 1.2.0 RC3 (32Bit)
VSTHost 1.54 / 1.55 / 1.56 (32Bit) (Tried all three versions)

When launching VSTHost, I am using the vsthost.exe not the VSTHostBridge file.
I uninstalled LMMS 1.2.0 RC2 (32Bit) completely before installing LMMS 1.2.0 RC3 (32Bit)
No plugins used with LMMS, no project loaded, it was a fresh install, so no link there.
VSTHost error occurs right after the install of LMMS 1.2.0 RC3 (32Bit)

I am also aware that this is not the "VSTHost bug tracker" site, the only reason I brought this up here was because it happened right after my RC3 install.  If I mention on the VSTHost site that the program works great until I install LMMS 1.2.0 RC3 (32Bit) I imagine they are probably going to say something similar and point me to mention something here.

Out of all the programs to have a problem with, this is unfortunate because VSTHost is what I use to record with.  I will either have to stick with RC2 or try to find another program that can use realtime effects / record to replace VSTHost, which neither solution sounds that appealing.
I will try to do some more testing to see if I could find anything else, my hope was that others would be able to replicate this as well.

Thank You

**Comment by tresf** [comment] 2017-06-10 00:21
I had not tried with the 32-bit LMMS version.  I will do that and report back my findings.  The problem did not occur with 64-bit LMMS.

**Comment by tresf** [comment] 2017-06-10 01:24
I just tried running the 32-bit VSTHost on 32-bit Windows and it won't load, regardless of whether or not LMMS is installed.  Since this message is identical to that posted in the original bug report, I assume it's related but the steps to reproduce are different.

Perhaps someone on Windows 7 x64 can reproduce on physical hardware.  I can't get anywhere with this, not through ProcessExplorer and not through ProcessMonitor.

![image](https://user-images.githubusercontent.com/6345473/26998822-d76f4400-4d57-11e7-82cb-bc7f8cc4e76e.png)

**Comment by musikBear** [comment] 2017-06-10 12:09
So two different fail sequences in respect to windows version (xp v. >=7)
RC3 runs on xp, after namechange of dll mentioned above  
So far i have noticed significant slower loading of projects
Would you be interested in a sanity test-sequence?

**Comment by tresf** [comment] 2017-06-10 12:19
> So two different fail sequences in respect to windows version (xp v. >=7)
RC3 runs on xp, after namechange of dll mentioned above
So far i have noticed significant slower loading of projects
Would you be interested in a sanity test-sequence?

Please stay on-topic.  The problems you have with your LMMS install belong elsewhere.  I recommend `# support` on Discord.

> forgot: My VSThost runs perfect. No issues after installing RC3

So no issues with Windows XP 32-bit?  Please be as specific as possible.

**Comment by miketurn** [comment] 2017-06-10 18:35
@musikBear 
Thank you for giving this a try, so it works fine in Windows XP 32Bit.

@tresf 
Thank you for trying this out again, so to kind of recap, you mention you tried VSTHost 64Bit out with a 64Bit version of LMMS with a version of Windows that is newer than Windows 7 and it worked.
When you tried VSTHost 32Bit on a 32Bit Windows system, you get this error regardless of if LMMS is installed or not.  First off yes that is the same error message I am receiving (my code numbers are different).  When you tried out VSTHost for the first time on your 32Bit machine, did you have a version of LMMS installed prior (see below)?

My friend is running a very similar setup to mine (all the same OS / software versions) and when he mentioned it to me, he told me to test VSTHost before installing RC3 and then try it again after which I did.  It worked before the install and after the error message occurs.
After this, I tried uninstalling LMMS RC3 completely to see if VSTHost works after the uninstall, but it does not, the error still occurs, so if it is LMMS (not saying it is), a file is being altered that does not go away with an uninstall of LMMS.  This of course makes it hard to test, because I will have to reset my system to try and replicate it again.

My LMMS uninstall process includes....
Windows Program remover
Manually delete Project Folder
Manually delete lmmsrc.xml file (I think this is the proper name of the file)
Not sure if LMMS placing anything elsewhere?

Thanks Again

**Comment by musikBear** [comment] 2017-06-11 13:22
> So no issues with Windows XP 32-bit? Please be as specific as possible.

Specific
The install **failed** specificity naming the aforementioned dlls
I removed them in sequence, and the install continued, and RC3 runs fine, VST-host runs fine too
RC3 32bit
*Basic function test*
* installs
* opens
* preserve settings
* uses locale
* can change UI language
* load older project
* create project from template
* replay
* saves
* exports (new as loops too)

correctly & with no problems on win32 xp

**Comment by miketurn** [comment] 2017-06-12 17:03
Setup a different hard drive and ran another test
Windows 7 (64Bit) fresh install
No LMMS installed
I unzipped VSTHost 1.56 (32Bit) tested and it works fine
This time I installed LMMS 1.2.0 RC3 (64Bit Version)
When I go to open up VSTHost again, the same error occurs

So this error occurs after the installation of both the 32Bit and 64Bit versions of LMMS 1.2.0 RC3

**Comment by tresf** [comment] 2017-06-12 19:25
Found it.  This was caused by this chang in our installer. 
 https://github.com/LMMS/lmms/commit/d2e50df3ce2f8a56fd1750cc077eff3e76a6867d

VSTHost seems to have a problem with setting this registry key.  I recommend pinging the developer and asking him if he can provide a patch.

Workaround:
 1. Open registry editor
 2. Search for `PreferExternalManifest`
 3. Change the value from `1` to `0`
 4. VSTHost will work again.

**Comment by tresf** [comment] 2017-06-12 19:26
Note, this above workaround will make LMMS very small on HiDPI display.

**Comment by tresf** [comment] 2017-06-12 19:29
Alternately if more programs experience this crash, we can disable this installer feature on Windows 7 and older as well.

**Comment by tresf** [comment] 2017-06-12 19:32
Per [winaero.com](http://winaero.com/blog/how-to-fix-apps-that-look-small-on-high-dpi-and-high-resolution-displays/):

> "[...] If you are running Windows 7 or Windows 8.0 RTM, doing the following Registry tweak can cause unexpected side effects like some system functionality breaking or apps crashing."

We'll code a fix for this.  Sorry for the inconvenience this has caused.

**Comment by miketurn** [comment] 2017-06-12 22:04
@tresf 
I gave this solution a try and it works great, I mentioned this to my friend that originally found the error and it worked great for him as well.  He mentioned to thank you and that it was okay it wasn't a huge inconvenience, he was just happy to help, and the same goes for me as well.
Thank you for sticking with this, I am so glad you were able to find this, and even better you were able to provide a working solution without having to wait for the RC4 release.

@zonkmachine 
Thank you as well for adding the bug label and adding it to the RC4 release list.

**Closed** 2017-06-12 22:12 UTC
Labels: bug

**Comment by tresf** [comment] 2017-06-12 22:22
Fixed in b2919d6.  So it turns out Windows 8 detection is [bugged and it's only available in NSIS 3 beta](http://nsis.sourceforge.net/Get_Windows_version#Semi-Obsolete) and including the newer versions wasn't successful (Travis-CI runs `2.46-7`).

Anyway, this calls for some ugly code, but it works:

```nsis
${IfNot} ${AtMostWin7}
:: insert reg key, etc
```

The only downside is this will inject the registry key for Windows 8.0 and higher (versus the [article stating it should be Windows 8.1 and higher](https://github.com/LMMS/lmms/issues/3619#issuecomment-307893846)).   At the time of typing this, Windows 8.0 has less than 2% of the desktop market share.  For the few that still encounter this with `1.2.0` and Windows 8.0, we can link them the workaround.

**Comment by tresf** [comment] 2017-06-12 22:49
> Thank you for sticking with this

Thanks @miketurn for persisting.  This was as strange of a bug as they get and it's of great value to weed this out in the RC phase when the user impact is minimal, manageable.
