### ISSUE TITLE
zasfx left/ right differences 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3415] opened 2017-03-09 14:43 UTC
I noticed a kind of important thing with zasfx. I am not sure it should be called a 'bug' and it is not LMMS that is the reason -so 'Not our bug'
The thing is, that the output of the two stereo-channels, can be significant different in comparison 
Look at this:
![zasfxkanalforskelle](https://cloud.githubusercontent.com/assets/6662066/23754644/05449b04-04de-11e7-9509-94a2719bd8f6.JPG)
Left channel is here causing clipping, but at the same moment right-channel is barely audible.
In zasfx, the balance between the channels can be adjusted, and i have this feeling, that many instruments clips especially in *left* channel, significantly before right channel. 
That forces the loudness of the instrument down, in order to avoid clipping
If this is compared with f.i. Synth1, there is no significant difference between channels, at least not in the magnitude seen in zasfx, not even close to cause *one-channel-clipping*
It look like this 'nervous' channel behaviour is a zasfx thing.
Does anyone Have a good explanation, or know a sound-technical reason for implementing that, or is it a zasfx bug?

**Comment by unfa** [comment] 2017-03-09 17:09
I made several hours of music with LMMS / ZynAddSubFX combo and haven't noticed any problem with one of the stereo channels.

Does it afect all the patches you load?
Have you tried diferent version of LMMS?

Could you deliver an example project (MMPZ) and an exported audio file of it (WAV) for evaluation?

Also - which version of LMMS are you running?

**Comment by musikBear** [comment] 2017-03-10 10:49
@unfa 
> Does it afect all the patches you load?

No, as i wrote it is only some.
> Have you tried diferent version of LMMS?

No, it is not LMMS related. 
> Could you deliver an example project (MMPZ) and an exported audio file of it (WAV) for evaluation?

Just load the shown preset into an empty project and play some notes
> which version of LMMS are you running?

again, its not LMMS, its zasfx-related. As i wrote *'Not our bug'* This is more in the nature of a FYI, and perhaps something to share on forum, but i would like to hear if there is a "sound-technical reason for implementing that" -Thats why i wrote this here first, but sure i can make a mmp with *sine-pad0001* and some notes, but you can reproduce that setup in 15 secd
Saw Strings 0002 & Saw Strings 0005 are also quite typical, btw

**Comment by zonkmachine** [comment] 2017-03-10 11:25
> > which version of LMMS are you running?
> 
> again, its not LMMS, its zasfx-related.

Would you really let someone in the forum get away with that answer?


> with sine-pad0001 and some notes, but you can reproduce that setup in 15 secd
> Saw Strings 0002 & Saw Strings 0005 are also quite typical, btw

Tested, I can't replicate this. The first thing that comes to mind is other issues with zasfx where parts of presets are remembered like arpeggio and fx settings. Could be related or similar.
https://github.com/LMMS/lmms/issues/1644

**Comment by musikBear** [comment] 2017-03-11 11:49
> Tested, I can't replicate this

Then it must be my hw
> Would you really let someone in the forum get away with that answer?

No sorry, my bad! right now its 1.1.90 g33d8c44
I was trying to find out when the bug in copy automation first occurred, so reverted down the install-chain, and i got down to 1.1.90 g33d8c44.
( wont '#'relate *this* post to the automation-pattern issue, because they are totally unrelated, but the number is 3359)

**Comment by zonkmachine** [comment] 2017-03-11 15:29
> > Tested, I can't replicate this
> 
> Then it must be my hw, maybe i better make a file after all..

 - No, sorry. It must not. ;) I don't think we have enough data at this point to draw any conclusions. But you know how to use lmms far better than I do. Is there a key combination that can cause this to happen? I'm writing from a pretty broken keyboard right now, so I know things can get very odd from the hardware side.
 - Make a test project is a good idea at this point, so we can exclude differences there.

> right now its 1.1.90 g33d8c44

OK. Tested in 33d8c44ed9815d59c89f51c52fd590d9c84cdc8e with Sine Pad and the Saw Strings and I still don't see this.

**Comment by tresf** [comment] 2017-03-11 16:27
Testing with the latest beta on  a fresh project... 

 * This issue does NOT exist on Mac with this particular preset
 * This issue does NOT exist on 32-bit Windows XP with this particular preset

Some findings... 

 * @musikBear why does your screenshot show you previewing the note, but also playing through channel 1 and master?  If you're previewing it, shouldn't it only go through master?  What do you have in your project that you're not mentioning?
 * Why is the volume so much higher in your testing?

This preset does a lot of LEFT/RIGHT panning, so it's hard to know without an animation what you're experiencing.

![untitled](https://cloud.githubusercontent.com/assets/6345473/23824910/c3dd07a2-064d-11e7-914d-0ade1af3b1aa.gif)

**Comment by musikBear** [comment] 2017-03-12 14:02
> why does your screenshot show you previewing the note, but also playing through channel 1 and master

No it is the piano-roll that is playing, not a preview. I just have the sidebar opened and drawed a ring around the preset on the screenshot, its not previewed 
Here is a mmpz that shows this behaviour

**Comment by zonkmachine** [comment] 2017-03-12 14:13
> Here is a mmpz in a zip that shows this behaviour

Save as an .mmp and paste it as a gist. 
https://gist.github.com/
Copy the link to the gist and paste it here.

**Comment by musikBear** [comment] 2017-03-12 14:22
Now i have it on LSP
https://lmms.io/lsp/?action=show&file=10487
> Save as an .mmp and paste it as a gist.
-Ya ofcause i could have done that, or even txt -im thick 🗜 
Oh well..

**Comment by zonkmachine** [comment] 2017-03-12 14:41
> Now i have it on LSP

Tested. I can clearly see a difference under stable-1.1.3 but not much under master. The reason for the difference is the new dBFS LED representation.
Your Sine Pad differs from the default one in that it has an 'Auto phaser' under the FX tab and it actually has different modulation depth settings for the right and left channels.

**Comment by Umcaruje** [comment] 2017-03-12 14:54
The preset fluctuates between the left and the right ear and that's how it's supposed to sound. The default zyn sound is dead center so I don't really understand this issue.

**Comment by tresf** [comment] 2017-03-12 15:11
> I don't really understand this issue.

The unit test was bad to begin with.

> it has an 'Auto phaser' under the FX tab

>> zasfx left/ right differences

> > > I noticed a kind of important thing with zasfx

What is paramount is that you learn how to produce a quality bug report please.  Closing as invalid.

**Closed by tresf** 2017-03-12 15:11 UTC

**Comment by musikBear** [comment] 2017-03-12 15:56
> Your Sine Pad differs from the default one in that it has an 'Auto phaser' under the FX tab and it actually has different modulation depth settings for the right and left channels.

That is how it is factory-installed right out of the version 1.1.90 g33d8c44. I have not added anything to the default sine-pad0001, it is as it is in 1.1.90 g33d8c44
Sorry for inconvenience.

**Comment by zonkmachine** [comment] 2017-03-12 16:15
> That is how it is factory-installed right out of the version 1.1.90 g33d8c44

Not over here it isn't. I'm enclosing a simple project with the default 'Sine Pad' I get.

[sinepad.mmp.zip](https://github.com/LMMS/lmms/files/836628/sinepad.mmp.zip)

**Comment by musikBear** [comment] 2017-03-13 12:33
@zonkmachine You are correct, an i have found the reason.
It is a difference in what happens if you use resp.
"Open in song-editor"
and
"Send this preset to active"
I figured that out yesterday, because i simply could not understand how i had different default presets, in respect to yours and trefs'
I have made a new issue on this difference here: #3419, but tresf disagree, that this is an issue at all, i dont since it confused the heck out of me :p , and it is different from instrument to instrument, eg the behaviour is not consistent.

**Comment by zonkmachine** [comment] 2017-03-13 13:48
Maybe it's an issue and maybe it isn't. Sometimes it's a matter of taste and sometimes a matter of historical fact. In this specific case I don't really have an opinion.
But why didn't you bring this up in this thread where the discussion was on going and rushed and created a new issue? Many times when we open issues we do it after some discussion. You can simply ask, 'Should I open a new issue about this?' and then you'll know ahead of posting if it's a good idea. That way we could keep the number of issues down.

![unwatch](https://cloud.githubusercontent.com/assets/6368949/23856324/94c1559c-07f9-11e7-9540-e9f1ccf30971.png)

If you look at the top of the page you'll see the number of persons who subscribe to these issue reports. If every subscriber take just one minute to read every new issue it's still more than two hours of possible developer time used up.

**Comment by tresf** [comment] 2017-03-13 14:12
>  but tresf disagree, that this is an issue at all,

The bug was open for 11 minutes with no message body, which is why it was closed.  Once the body was filled-out, I had left it closed because I did not see evidence that it was a bug.  Since then, the new findings provide enough information to make it a bug.  Please correct it and we'll reopen:

 * If the inconsistency is the bug, fix the bug description to include that
 * Please, a few short steps to reproduce including stock preset names
 * Please identify which behavior is desired

Then we'll reopen. 👍

**Comment by musikBear** [comment] 2017-03-14 12:51
*This* issue should not be reopened. Its a result of the confusing behaviour in #3419, what i saw, was simply the result of a persistent FX, not a general issue with zasfx at all, so *this* issue is **invalid**, and should stay so, and thats also why i opened a new issue, because even though *this* instigated the new issue, the content here *is* invalid, eg there is nothing wrong with zasfx -at least imo.
