### ISSUE TITLE
Resizing the mixer window, and its content, vertically 

### ISSUE THREAD

**Issue by M4rotte** [LMMS/lmms#6820] opened 2023-08-21 19:27 UTC
### Enhancement Summary

Would be nice to have the possibility to resize the mixer window vertically to have a longer fader course.

#### Justification

More precision to set the volume when mixing.

**Comment by DomClark** [comment] 2023-08-22 20:23
Duplicate of #3258.

**Closed by DomClark** 2023-08-22 20:23 UTC
Labels: enhancement
