### ISSUE TITLE
"Assign to new FX mixer channel" button in the instrument panel

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2276] opened 2015-08-17 16:07 UTC
![fx new](https://cloud.githubusercontent.com/assets/491704/9309577/d0c481c6-450a-11e5-993f-2542bef32b56.png)

Often I waste a lot of time creating new channels, assigning instreuments to them, chaning tehir names.

Could all this be done with one button?

1. Create a new FX channel
2. Assign the current instrument to that newly created channel
3. Rename the new channel to match the current instrument

Simple and quick solution, before we make a complete GUI rehaul. What do you think?

**Comment by tresf** [comment] 2015-08-17 16:13
We've already done this in the track context menu.  I'd recommend we bring that context menu over to the FX Widget rather than adding more buttons.

**Comment by unfa** [comment] 2015-08-17 16:16
I also thought about that. Right click on the FX Widget > Assign to a new channel.

**Comment by Umcaruje** [comment] 2015-08-18 11:06
I believe this feature already exists in master per #1627

**Comment by michaelgregorius** [comment] 2015-08-18 17:07
I have just checked in the running application and can confirm that this feature exists in master. Check #1627 for details on how it looks.

**Comment by tresf** [comment] 2015-08-22 00:22
Closing, duplicate of #1627

**Closed by tresf** 2015-08-22 00:22 UTC
