### ISSUE TITLE
Holding control then opening a window then releasing control while the window is open changes the mode.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3833] opened 2017-09-28 11:59 UTC
In LMMS 1.2.-rc.3, the issue happens with the piano roll editor only.
In `master`, the issue happens with the piano roll editor and the song editor.

While holding control, the mode is changed from draw to edit, and the mode returns to edit when control is released. The issue is that after holding control then opening a window then releasing control while the window is open, the mode doesn't return to draw.

**Comment by BaraMGB** [comment] 2017-09-28 12:38
For song editor it should be fixed by https://github.com/LMMS/lmms/pull/3796

**Comment by PhysSong** [comment] 2018-08-06 03:45
> For song editor it should be fixed by #3796

As I mentioned in #4393, #3796 is incomplete.
#4393 should work for the piano-roll. I'll add a similar fix for song editor too.

**Comment by Spekular** [comment] 2020-04-26 09:38
Closing as duplicate of #5394

**Closed by Spekular** 2020-04-26 09:38 UTC
Labels: bug
