### ISSUE TITLE
ReaXcomp crash when saving project >8 bands in an LMMS instance

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6223] opened 2021-11-21 12:34 UTC
(Possibly related issue: https://github.com/LMMS/lmms/issues/6064 which is re: ReaEQ, which is part of the same plugin package ReaPlugs and also has a crash under slightly different circumstances.)

### Bug Summary
Under certain circumstances (ie in a new instance), a previously saved project with ReaXcomp VST plugin crashes if project-wide number of compression bands increased and is greater than 8.

#### Steps to reproduce
1. Add ReaXcomp to instruments/FX-mixer of a project. It does NOT matter how many instances you add or where you add them.
2. Save the project file.
3. Close LMMS and reopen it.
4. Reopen the project file.
5. Open any instance of ReaXcomp and **add** bands, until the project-wide number of bands (ie the total number of bands combining each ReaXcomp instance in your project) is greater than 8. If you already had more than 8 bands project-wide, add an arbitrary number of bands. It doesn't matter.
6. Save project.

#### Expected behavior
LMMS saves smoothly.

#### Actual behavior
LMMS crashes.

#### Screenshot
(Video:)
https://user-images.githubusercontent.com/76674645/142761928-cbfd22e9-defc-46ea-a6e3-75e018090f30.mp4

The end of the video corresponds with LMMS crashing, causing my screen recorder to stop.

#### Affected LMMS versions
1.2.0, 1.3 alpha.

**Comment by PhysSong** [comment] 2022-01-20 02:52
Duplicate of #6064.

**Comment by Monospace-V** [comment] 2022-01-20 02:52
Different VST, different circumstances. Same issue?

**Closed by PhysSong** 2022-01-20 02:52 UTC
Labels: bug

**Comment by PhysSong** [comment] 2022-01-20 02:58
It turns out they are indeed the same issue, see my comment on #6064.
