### ISSUE TITLE
Track restored to large size when saved after switching instruments in instrument window

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#3721] opened 2017-07-23 14:10 UTC
Steps to reproduce:
1. Start LMMS with the default project (with at least one Triple Oscillator).
2. Add another Triple Oscillator (or another instrument).
3. Open the instrument window of one of the instruments.
4. Switch between instruments using the left / right arrow on the top of the instrument window.
4. Save.
5. Load the file that you have just saved.

The last selected instrument will be restored with a very large height that coincides with the instrument window's height.

The main cause is that there are two methods which store different types of heights as the attribute `height` in the node `track` under the parent `trackcontainer`:
1. The method `Track::saveSettings` stores the height of the track under that node.
2. The method `InstrumentTrackWindow::saveSettings` stores the window geometry of the instrument window by delegating to `MainWindow::saveWidgetState`. This step stores the height of the instrument window into the aforementioned node which causes the faulty restoring of the track height.

The switching of the instrument windows is relevant for this bug because at one point this action calls `InstrumentTrackView::getInstrumentTrackWindow` which installs a hook for the serialization so that `InstrumentTrackWindow::saveSettings` is called as well. Without this action no hook is installed and everything is fine. You can see this if you add a break point to `SerializingObject::setHook` and then execute the steps described above.

So everything action that leads to the installation of the aforementioned hook or a direct call to `InstrumentTrackWindow::saveSettings` will likely trigger this bug.

See the closed pull request #3692 for more details.

**Comment by michaelgregorius** [comment] 2017-07-23 16:35
Here's an example of a malformed `track` DOM element in the written project file:
```XML
<track width="262" x="1667" y="0" maximized="0" muted="0" height="472" visible="1"
       type="0" minimized="0" name="TripleOscillator" tab="0" solo="0">
```
The attributes are stored by the following classes / methods.

`Track::saveSettings`: type, name, muted, solo, height

`InstrumentTrackWindow::saveSettings`: tab

`InstrumentTrackWindow::saveSettings` (via `MainWindow::saveWidgetState`): visible, minimized, maximized, x, y, width, height

As you can see the `height` attribute is used twice which leads to the wrong height being used when the track is restored.

To solve this problem it will need to be discussed whether it's correct that all these entities write to the `track` element. It might for example make sense that the instrument window stores its state to an `instrumenttrackwindow` element. It might also be unnecessary that the class `InstrumentTrackWindow` stores its window state at all (see below). So an alternative structure might look like this (if the window still stores its state):
```XML
<trackcontainer>
  <track muted="0" height="56" type="0" name="TripleOscillator" solo="0"> <!-- --> </track>
  <instrumenttrackwindow width="262" x="1667" y="0" maximized="0" height="472" visible="1" minimized="0" tab="0" />
```

Here's the `track` element for the same track for the case where the switching between instruments is not done:
```XML
<track muted="0" height="56" type="0" name="TripleOscillator" solo="0">
```
As you can see only the attributes of `Track::saveSettings` are written. This might also be an indicator that the writing of the widget state of the `InstrumentTrackWindow` is indeed unnecessary.

@tresf If the writing to the `track` element by all these entities turns out to be in fact incorrect then the fix of this problem should be relevant for the 1.2 release as well so that we don't have a released version which writes confusing/mixed data (which needs to be cleaned up later).

**Comment by PhysSong** [comment] 2017-07-24 01:34
@michaelgregorius How about
* Don't save window size for some fixed-size windows,
* or renaming attribute name to something like `windowheigth` and add some codes to `DataFile::upgrade()`
?

**Comment by PhysSong** [comment] 2017-07-25 05:58
I think modifying `void MainWindow::saveWidgetState( QWidget * _w, QDomElement & _de )` to `void MainWindow::saveWidgetState(QWidget * _w, QDomElement & _de, bool saveSize = true)` can be a solution. Since `InstrumentTrackWindow` has fixed size, saving its size isn't required.

**Comment by zonkmachine** [comment] 2017-07-25 10:44
> @tresf If the writing to the track element by all these entities turns out to be in fact incorrect then the fix of this problem should be relevant for the 1.2 release as well so that we don't have a released version which writes confusing/mixed data (which needs to be cleaned up later).

For 1.2.0 I think something like simply stop writing the height data at all would be a good solution.

[Track::saveSettings()](https://github.com/LMMS/lmms/blob/stable-1.2/src/core/Track.cpp#L2055:L2058)

```cpp
/*if( m_height >= MINIMAL_TRACK_HEIGHT )
{
	element.setAttribute( "height", m_height );
}*/
```

**Comment by michaelgregorius** [comment] 2017-07-25 15:12
@PhysSong I also thought about writing the track height as something like `trackHeight` just to differentiate both uses. However, because the attribute would already be part of an entity `track` having something like `<track trackHeight="70" />` would look a bit strange compared to something like `<track height="70" />`.

@zonkmachine Your proposal might be a solution for 1.2 as this version does not have the functionality to restore the track height anyway.

In the end I think the cleanest solution would be to separate the data into different entities. Especially if version 1.2 would become the first "dirty" version to write this mixed data. Does anybody know whether 1.1.3 already writes this mixed data under certain circumstances? I think 1.1.3 does not have the functionality to switch instruments from the instrument window, has it? Although there might be other ways in older versions to hook the critical saving code.


On a related note I think it's generally a bad idea to mix data that's related to the presentation (GUI) side with core data from the business. Ideally core entities like `Track` would have IDs that are just referenced from GUI related data. The GUI related data should be written to a totally separate XML tree. That way we could have data that would be interpreted as "the GUI representation of the track with ID `xyz` has a height of 70".

**Comment by PhysSong** [comment] 2017-08-05 02:44
I can reproduce without instrument switching, in latest master. The steps are:

1. Open any instrument.
2. Close and re-open it.
3. Save.
4. Load the project file saved in step 3.

>Does anybody know whether 1.1.3 already writes this mixed data under certain circumstances?

I don't know exactly, but I guess it could be.
>For 1.2.0 I think something like simply stop writing the height data at all would be a good solution.

@zonkmachine It might be. As @michaelgregorius said, however, `MainWindow::saveWidgetState()` overwrites the `height` attribute. So we also need to stop saving instrument windows' size.

**Comment by PhysSong** [comment] 2017-08-06 07:14
My temporary solution works, do not save wrong height anymore.
I think @michaelgregorius' solution is a fundamental one but should be applied later. When new projects(saved after the change is applied) is loaded with older version of LMMS, some widgets' state won't be correct(like zero-size song editor).

Mixing core data and GUI data is not good, but fixing it may cause compatibility issues. This issue seems very tricky...

**Comment by zonkmachine** [comment] 2017-08-06 12:50
> @zonkmachine It might be. As @michaelgregorius said, however, MainWindow::saveWidgetState() overwrites the height attribute. So we also need to stop saving instrument windows' size.
> (Like #3721 (comment))

Yes, my method doesn't work. I think I must have had some other fix active on `Track::loadSettings(...)`.
I think a temporary fix is motivated here. I get this all the time and there's already been at least one duplicate report. We could add a maximum size on loadSettings to counteract already wrongly saved tracks.

**Comment by zonkmachine** [comment] 2017-09-28 18:19
> or renaming attribute name to something like trackheight/windowheight ...

I had a go and this works for track height.

```

diff --git a/src/core/Track.cpp b/src/core/Track.cpp
index 163e0ef..55021fd 100644
--- a/src/core/Track.cpp
+++ b/src/core/Track.cpp
@@ -2086,7 +2086,7 @@ void Track::saveSettings( QDomDocument & doc, QDomElement & element )
        element.setAttribute( "solo", isSolo() );
        if( m_height >= MINIMAL_TRACK_HEIGHT )
        {
-               element.setAttribute( "height", m_height );
+               element.setAttribute( "trackheight", m_height );
        }
 
        QDomElement tsDe = doc.createElement( nodeName() );
@@ -2182,7 +2182,7 @@ void Track::loadSettings( const QDomElement & element )
                node = node.nextSibling();
        }
 
-       int storedHeight = element.attribute( "height" ).toInt();
+       int storedHeight = element.attribute( "trackheight" ).toInt();
        if( storedHeight >= MINIMAL_TRACK_HEIGHT )
        {
                m_height = storedHeight;
```

> .... and add some codes to DataFile::upgrade()

No. Since the date is potentially wrong and earlier tracks didn't reload saved track height anyway it's better to not upgrade. Since this is a pretty disruptive issue, if no one has a fix in the works, I think we should either revert https://github.com/LMMS/lmms/pull/3692 or I can pull the fix above at least as a temporary solution.

**Comment by zonkmachine** [comment] 2017-09-29 15:33
> I can pull the fix above at least as a temporary solution.

https://github.com/LMMS/lmms/pull/3840

**Comment by michaelgregorius** [comment] 2017-10-17 19:29
It seems that we can close this one with the merge of #3840. @zonkmachine, @PhysSong, what do you think?

**Comment by zonkmachine** [comment] 2017-10-17 20:25
I'm cool with closing this, but didn't you and @PhysSong's analysis go a bit further?
Also, there was this other comment from the https://github.com/LMMS/lmms/pull/3692#issuecomment-314916491.

>  Track Gets Huge Vertical Enlargement; **Notes Randomly Vanish**...

We don't really know what was meant with that comment but there's this case where tracks have gone all blank and that could be interpreted as notes randomly vanishing by a user. Could this be related https://github.com/LMMS/lmms/issues/2957 ?

**Comment by zonkmachine** [comment] 2017-10-26 11:39
Could this be a similar issue working on the Song Editor? I've seen it quite a lot and have wondered what's going on. https://github.com/LMMS/lmms/issues/3913

**Comment by musikBear** [comment] 2017-10-26 13:19
I cant reproduce at all in rc4 on win32 xp
When i reopen the saved project, there is *no* instrument-window opened, both are closed.
I does not matter is i have the song-editor
* open
* closed
* windowed
* full size

In all circumstances there are no instrument window opened, and that confuses me like ****, because if i open older projects, there are often instrument windows opened
One possible difference, is that i have made changes to *default-template*, and resaved/ overwrote as a new *default-template*
*Maby* template has something to do with it(?)

**Comment by zonkmachine** [comment] 2017-10-26 14:42
Was this intended for https://github.com/LMMS/lmms/issues/3913 ?



> I cant reproduce at all in rc4 on win32 xp

Tracks opening with ridiculous size is an issue on master and has been fixed.

**Comment by zonkmachine** [comment] 2017-11-17 04:05
> Track Gets Huge Vertical Enlargement; **Notes Randomly Vanish**...
> 
> We don't really know what was meant with that comment but there's this case where tracks have gone all blank and that could be interpreted as 'notes randomly vanishing' by a user...

Well, there is off course the issue reports about randomly disappearing notes: https://github.com/LMMS/lmms/issues/3964
I'm closing this as this seem to be the most likely candidate to the mysterious vanishing notes bug. I don't get how this would have been releated to the large sized tracks.

**Closed by zonkmachine** 2017-11-17 04:05 UTC
Labels: bug
