### ISSUE TITLE
MIDI Effects control Enhancement 

### ISSUE THREAD

**Issue by 398noe** [LMMS/lmms#5632] opened 2020-08-16 04:08 UTC
I searched “midi effects control” but AFAIK , I couldn’t find such functions.

### Enhancement Summary
MIDI Effects control.

#### Justification
When I want to use iZotope stutter edit 2
https://www.izotope.jp/products/stutter-edit-2/
or keroVee ,
https://www.g200kg.com/jp/software/kerovee.html
they can use MIDI notes for changing efffects in their VSTPlugins by routing MIDI signals to VSTe.
Other DAW(FLStudio Reaper AbletonLive Cubase  and more)  can do,but LMMS doesn’t.

#### Mockup
Instruments > FX > Control > Route MIDI signals

**Comment by Spekular** [comment] 2020-08-16 06:35
Marking as a duplicate of #1202, which is consolidated into #1472.

Thank you for filling out the issue template correctly though! A lot of people who submit issues don't seem to search for duplicates at all, so I appreciate it.

**Closed by Spekular** 2020-08-16 06:35 UTC
Labels: enhancement

**Comment by 398noe** [comment] 2020-08-16 07:25
Thanks you.
