### ISSUE TITLE
Drag & Drop Deletion of Patterns

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#1562] opened 2015-01-06 11:49 UTC
Being able to drag and drop a pattern from the song editor to outside the track area/outside the window area would be an intuitive way to delete patterns imo. Alternatively (as patterns seem to ignore vertical dragging), patterns could be dragged up/down past a certain limit and dropped to be deleted (with a visual cue like fading out to communicate this limit/the "impending deletion" to the user).

**Comment by tresf** [comment] 2015-01-06 13:18
... sounds like something an Apple user would say.

Just remember, if you want to drag-to-nowhere delete, you should propose it everywhere... :+1: 

Android does this for its launcher icons, they can be "tossed" in the direction of a recycling bin.

That said, I don't know if this has much value on a mouse/keyboard GUI, so I would vote to shelve this idea until if/when we get a more touch-centric interface.

**Comment by tresf** [comment] 2015-01-06 13:19
Also, this "trash a pattern" idea is generally something that works with undo, which doesn't currently work for song editor patterns.

**Comment by Spekular** [comment] 2015-01-06 13:31
@tresf the dragging up/down + fade was inspired by my android phone/the
youtube app where you swipe to kill programs/close videos. The drag drop
thing was just something I thought of while using a touchpad, since it's a
pain to right click and select delete.

**Comment by tresf** [comment] 2015-01-06 13:37
> @tresf the dragging up/down + fade was inspired by my android phone/the youtube app where you swipe to kill programs/close videos. The drag drop thing was just something I thought of while using a touchpad, since it's a pain to right click and select delete.

That makes sense, although the entire software interface is pretty bad on a touch interface currently, so again, I think we shelve ideas like this until if/when we can make the interface more touch friendly as a whole. :)

**Comment by Spekular** [comment] 2015-01-06 13:39
@tresf Maybe we add a master "touch enhancements" issue similar to midi
support and close out some issues?

**Comment by tresf** [comment] 2015-01-06 13:40
If you can find enough to justify such a thread, sure.  I'm not sure we have that many.  Tag them here if you find them and we can consider consolidating.

**Comment by Sti2nd** [comment] 2015-01-06 19:02
> Being able to drag and drop a pattern from the song editor to outside the track area/outside the window area would be an intuitive way to delete patterns imo.

Hmmm, if we didn't already have so easy shortcuts from before, Shift + Right click or Middle click, yes it could be something. Then my thinking goes on about autoscroll https://github.com/LMMS/lmms/issues/1523 which couldn't coexist with this feature, which again makes me say no to this.

> since it's a pain to right click and select delete.

Again. Shift + right click works in LMMS 1.1.0
Probably tag invalid?

**Comment by tresf** [comment] 2015-01-06 19:11
> Probably tag invalid?

Normally yes, but I'll let @Spekular decide whether or not to close.  He's started coding his own features, so I feel he's well qualified to make this determination himself! :+1:

**Comment by Spekular** [comment] 2015-01-19 09:20
@tresf Alright, I've finally had time to go through all the issues. I tried to check every UI related one and organize them into groups, so perhaps some of these could be consolidated. Also I think we need a "UI" tag.

There are quite a few drag n drop issues:
-Drag & Drop Deletion of Patterns #1562
-Allow drag-and-drop of project files #1634
-Drag-and-drop instrument behavior #1531
-Drag-and-drop of automatables to Automation Editor #1416
-FX-Mixer: Drag'n'Drop Reordering #605

Then there are some that are less related but still have to do with dragging:
-Odd behavior when clicking and dragging out of visible range on the left side of the instrument keyboard #1556
-SongEditor Shift+Ctrl+Drag to Move Block #1407
-Scroll Song Editor while Dragging #1166
-[Bug] Dragged Instruments are affected by vst windows [ long standing bug, linux] #1020

There are a couple that have to do with colors of various tracks:
-FX-mixer strip color indicating it's type #1214
-Improving Colored Tracks #1176
-Enhancement: Get option to custom color instruments tracks like beat and bass tracks #1160
-[Bug] stable-1.1 Tracks should explicitly remember last colour used. #1006
-Enhancement: Colors as Adition to comment-tracks #560

Three that have to do with various groups:
-Song editor group operations #1212
-Enhancement: Collapsible Song Editor Groups #735
-FX-Mixer: Groups (a way to tidy stuff up) #606

Two about multiple monitors:
-Multiple Monitors #1259
-New FX-Mixer: faders don't work on second screen #1200 (No response here, perhaps close?)

Some have to do with the various browsers and related:
-Playback Should Not Halt when 'Open Project' Dialog is Opened #1384 (Thought this was fixed?)
-List external disk drives in FileDialog on Linux #1118
-Unsaved file shows "Untitled*" in title bar rather than filename #905
-Difficult to explore effects #1120
-Improve search field #760

FX Mixer stuff:
-Mixer peak indicators. #1271
-Show a warning for mixer channels that have no output #1224
-Highlight instruments when assigned FX-mixer strip is selected #1216 (duplicate of #117)
-Signal meters dB indication #1213
-volume levels in dBFS in mixer #1022
-Active instrument window highlights assigned FX mixer channel #117 

Automation Stuff:
-Automation Track UI Recommendation #1405
-1.0.92 Automation-editor -minor stuff #983
-1.0.92 Automation-editor magnification on vertical axis #982
-Visual indication of automated objects ( paint ) #725
-Automation editor still displays mouse cursor frequency linear. #664
-Automation improvement request #119

Keyboard/Shortcut Stuff:
-PianoRoll Shift+Insert/Shift+Delete Shortcut #1643
-Delete in Song Editor like in Piano Roll and Automation Editor #1500
-New default shortcuts (table) #1488
-Enhancement : Hot-keys (key-shortcuts) for piano-rolls Scale and Chord tools #615
-Enhancement: Additional smart keys in piano-roll #625
-Middle mouse = impossible on laptops #621
-User definable shortcut #1475
-Navigating and inserting notes in piano roll using keyboard only #1421
-Change mute keycombo/hotkeys #741

Bugs:
-Changing from Edit to Draw mode does not unselect anything #1561
-(Windows) Non-ASCII String Displaying Bug #1325
-Graphic bug: note automation in pianoroll is over Panning/Volume bar #1156
-Bug look/feel 1.0 win32 'New Project' opens with some 'old' paramters #528
-Sometimes window positions aren't loaded correctly #371

Looks:
-Instrument track activity LED lights when muted #1595
-Modern And Sleek Theme For LMMS #880
-ZynAddSubFX Theme + NTK Support #713
-[enhancement] Alternative views (tile, tabs, etc) #519

Features/Misc:
-No preview for beat/bassline #1263 (Duplicate #1123)
-Show time progression in B&B editor #1123 
-feat. req. Stretch\Shrink\Split pattern #1648
-User-Waveform selection from sample in TripleOscillator #915
-Enhancement: More texts for "What is this" #896
-Enhancement, AFP Move selection in AFP with mouse on GUI #794
-Enhancement: small notespace on all instruments #630
-Enhancement: Status-line & tooltips #561
-Add NSM support #525
-"Variant" Beat/Bassline Editor Proposal #454
-"Siloed" Beat/Bassline Editor Proposal #453
-Toolbar vertical real-estate enhancement #387
-Feature request (usablity): Closing all opened instrument (windows) #266
-Timeline Markers #156
-Input Gain knob for Plugins #118
-More precise zooming #2

Other things (non UI):
-Segfault at end of commandline render #588 (Thought this was fixed)

**Comment by tresf** [comment] 2015-01-19 13:32
@Spekular congratulations you just linked 60 bug reports to this one...

I appreciate the diligence here, but we should be careful not to over-organize our bugs.

MIDI, Jack and Sample Track were good candidates because they have had very little progress in recent history but are continually mentioned in new bug reports.

I don't want to over-consolidate on everything because it makes it harder to track the smaller improvements that our developers are focusing quite a bit of attention on in recent history.

**Comment by tresf** [comment] 2015-01-19 13:34
That said, if there is one category that stands out as all being related, we can do some housekeeping, I just don't want to do it for the sake of having less open bugs.  Many of these bug you've listed above are mini-projects in themselves and will see some attention in the coming months. :+1:

**Comment by Spekular** [comment] 2015-01-19 14:36
@tresf Oooooooooppps. Sorry. Wasn't thinking about that particular feature when I copied the names.
I feel like perhaps the shortcut stuff could be integrated into @Sti2nd 's shortcut reorganization issue, and maybe the some of the colored track/mixer ones could be integrated into my Improving Colored tracks issue? Other than that I don't think there are too many issues here that could be consolidated, except perhaps the drag 'n drop ones.

**Comment by tresf** [comment] 2015-01-19 14:42
@Spekular, thanks tremendously for the initiative.  I agree those are two good candidates.  Please do.  First create the parent ticket linking all children.  Then paste a comment in the children tickets referencing that the issue is consolidated (not closed) with some instructions to the users (feel free to model this after another consolidated item).  Once I see that message, I'll review the child tickets and close as appropriate. :+1: 

In the case of the shortcuts issue, please ask Stian to maintain the original bug report since he's organizing that stuff.  Just paste what you'd like appended and hopefully he'll add it into the original report.

**Comment by Spekular** [comment] 2015-01-20 18:33
@tresf ok, just to confirm: consolidate drag n' drop, consolidate color issues, ask Stian to consolidate shortcut issues? Or consolidate color + shortcuts, collaborating with Stian on the shortcut issues?

**Comment by Sti2nd** [comment] 2015-01-20 19:05
I feel you can just tell me (comment on the thread) as I have already done that (consolidated?) in a way, at the bottom of the table https://github.com/LMMS/lmms/issues/1488

**Comment by Spekular** [comment] 2015-01-20 19:12
@Sti2nd done. I'm just not sure if the other issues should be closed as duplicates of yours and if so how they would be integrated.

**Comment by tresf** [comment] 2015-01-20 19:54
Sorry missed the drag-and-drop part.  Please leave them as-is.  Drag and drop needs improvement as a whole, but this requests are quite specific I feel.

**Comment by tresf** [comment] 2015-08-24 16:26
Closing as won't-fix for now, since patterns don't let you drag them out of the context of their track and this functionality likely won't change for a while.

**Closed by tresf** 2015-08-24 16:26 UTC
