### ISSUE TITLE
lmms/master sometimes not shutting down properly

### ISSUE THREAD

**Issue by Lathigos** [LMMS/lmms#5260] opened 2019-10-20 12:40 UTC
I did not have any time to investigate this further, but I have noticed that in the master branch of LMMS, when closing the main window, the process regularly doesn't properly get shut down and a process remains active in the task manager.

This can best be seen when starting LMMS through a terminal. Usually, when closing the main window, control is given back to the user. However, about 1/3rd of the time closing a window (try it a bunch of times), the process remains active despite the window being closed and one has to send "Ctrl+C" to the application or kill it with a task manager to terminate it. When this happens seems to be entirely random.

Please let me know if this bug is reproducible on a different system. I am using Linux Mint 18.3 x86_64 Cinnamon. It occurs on LMMS/master 1.2.0.549 built using GNU Make 4.1, cmake 3.5.2, QT 5.5.1, g++ version (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010.

**Comment by CYBERDEViLNL** [comment] 2019-10-20 13:25
Duplicate of https://github.com/LMMS/lmms/issues/4668?

**Comment by PhysSong** [comment] 2019-10-21 23:09
> Duplicate of #4668?

I think so.

**Closed by PhysSong** 2019-10-21 23:09 UTC
