### ISSUE TITLE
Basic drum sampler instrument.

### ISSUE THREAD

**Issue by dednikko** [LMMS/lmms#1087] opened 2014-08-22 05:01 UTC
Please create a drum sampler instrument. I envision a minimal version of Native Instruments' Battery,  or similar. Much of the code appears to be written, and needs to be glued together to make a single instrument.

Basic features (based on a modified Audio File Processor):
Load stereo samples to individual drum pads.
Change pitch akin to changing notes played in a sampler, affecting the length of the sample as well.
Unified output to a single effect bus.
Basic filters.
Reverse.
Pan.
Gain.

I also have a few ideas that would make it good for live performance as well as standard programming.
1. Better controlled combo highpass/lowpass filter with a  dead zone in the middle of the knob's rotation (perhaps have values 59-67 all report 63 as the value, so there is no accidental frequency scooping, maybe a separate version of the filter with the dead zone built in and/or selectable dead zone)
2. Change pitch independent of sample playback length, via rubberband.
3. (unique feature?) Add to each sample pad an override toggle that makes it so that when that sample pad is played, all other sample pads stop producing sound.
4. (unlikely?) Add in midi program change support so preset kits could be triggered from a MIDI pad.

I'm no graphic artist, but I could throw together a basic mockup if that is helpful.

**Comment by tresf** [comment] 2015-01-30 16:33
Duplicate of #1460

**Closed by tresf** 2015-01-30 16:33 UTC
Labels: enhancement
