### ISSUE TITLE
VST Shortcircuit: crashes when loading samples

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1389] opened 2014-12-03 22:44 UTC
I am havig trouble with loading samples in Shortcircuit sampler any tine I try to load samples in the Shortcircuit sampler vst lmms will not open the file sertch box even thoe I have set the my sample folder in the Shortcircuit. the VeSTige plugin and lmms crashs.

Shortcircuit plugin
![scss-zone 1](https://cloud.githubusercontent.com/assets/8137561/5290295/3728d540-7b0b-11e4-9499-e7e7a6a2348e.png)
video     https://www.youtube.com/watch?v=jPq4XZhUOio
http://www.vemberaudio.se/shortcircuit.php

**Comment by PhysSong** [comment] 2017-10-07 03:07
@Reaper10 Various VST-related crashes are fixed in #3776, and the fix is included in 1.2.0-rc4. Could you re-test this?

**Comment by tresf** [comment] 2018-01-05 18:24
@PhysSong @Reaper10 has been banned from our tracker so he can't reply to this.  I'll assign to @DomClark for now.

**Comment by DomClark** [comment] 2018-01-06 01:09
I've tested as far back as 1.0.0 and I can't reproduce this. Given that @Reaper10 is banned so can't give any feedback, I vote that we close this issue for now and see if we have any further reports in the future.

**Comment by tresf** [comment] 2018-01-06 01:10
> I vote that we close this issue for now

👍

**Closed by tresf** 2018-01-06 01:10 UTC
Labels: bug, core, vst
