### ISSUE TITLE
Offset in the song editor (ie: wrong start position)

### ISSUE THREAD

**Issue by M4rotte** [LMMS/lmms#7090] opened 2024-02-03 14:33 UTC
Hi,

Didn’t find any existing issue but I may have missed one because I’m not sure what keyword I can use to search in existing issues. But there may be a common root-cause with #4282 although it doesn’t imply a tempo change (just an intuition, didn’t do any troubleshooting, it may be totally unrelated).

I too don’t know how to reproduce, but it happened to me multiple times, randomly. But I tend to think it happen after clip deletion. I never notice it at the exact moment it happens, this is when I realize the sound and the display mismatch that I check what the beginning of the song looks like and see it happened. I just have to reload the song to get the song alignment right (ie: no need to restart LMMS).

I don’t know how to describe it clearly with words but the following pictures should be obvious.

![bug_lmms_song_offset_2](https://github.com/LMMS/lmms/assets/6515724/3ef6978a-a478-48b7-83ce-99da6bb0d149)
![bug_lmms_song_offset_1](https://github.com/LMMS/lmms/assets/6515724/aa711d2b-2415-437c-8462-71fb86c2a1e1)

In the pictures above the start position is at 0 but the display shows an offset. When the song is played it results in the position displayed not matching the actual position. I didn’t notice that this offset increases or varies in any way while the song plays, it seems to stay constant. I’ll try to verify this point next time it will happen.

I should have took a wider screenshot because on those above, it is not visible that the “track moving handles”, which are at the very left of the every tracks, have disappeared.  

The screenshots have been taken a while ago, according to the date of files and the commit history it was very probably at commit 8eba258bdad8e940db9ae84f6362d1749d8bb425 (master branch), but I got a few cases with newer versions since, as with older ones. (I use master branch and always build LMMS before a session if it has had new commits since the last time I used it)

The system is Debian 12 − (Linux x86_64, Qt 5.15.8, GCC 12.2.0)

**Comment by Spekular** [comment] 2024-02-03 15:38
I think this is a duplicate of #6551. When this happens, resizing the song editor horizontally should cause the track drag handles to reappear and realign the playhead.

**Comment by Spekular** [comment] 2024-05-22 15:40
Closing as duplicate of #6334, which precedes #6551 and appears to describe the same issue.
If you'd like to test PR #6338 and see if it fixes the issue, @PhysSong has described the following conditions to reproduce the issue:

> - The editor must be able to be scrolled vertically
> - Enter/Return key should be pressed after renaming

**Closed by Spekular** 2024-05-22 15:40 UTC
Labels: bug
