### ISSUE TITLE
issues with sample loading (and solutions)

### ISSUE THREAD

**Issue by rgndxzzk** [LMMS/lmms#6493] opened 2022-08-20 21:11 UTC
issues with sample loading:
issue A: loading a sample for preview takes way too long
issue B: loading a sample makes lmms unresponsive
issue C: loading a sample to use in song editor is annoying bc of issue A and B

continuation of C: how loading a sample in the song editor goes:
I. click it (loads it for preview) [freezes]
II. move your cursor (stops previewing [unloads it? * ])
III. release click onto song editor, pattern track or sample track [loads it again, freezes]
so it takes twice the amount of time to load it to your project than it takes to preview, cuz it loads it twice

fixes:
1. (best fix -- requires fix 2 -- fixes both a, b, c)
load the sample in segments: cut the sample into many segments: load the first segment, play it, while its playing, load the second segment, play the second, load the third, etc.
(just like how youtube loads a video, instead of loading the whole video immediately, it loads as you're watching)
2. (fixes b)
find a way not to make lmms unresponsive when loading a sample (so you can also cancel loading if you want)
3. (simplest fix -- helps for if u click the wrong sample -- not really a good fix)
when a sample is clicked for preview, wait 3 seconds before loading and previewing it
4. (if * is true, makes loading time not be twice)
once the sample is unclicked (not once the preview has stopped), wait 5 seconds and then unload

update: yeah * is true, when you stop previewing a sample it immediately unloads it

**Comment by Rossmaxx** [comment] 2022-08-21 08:41
Have you tried the 1.3 alpha before writing this? It is a known fact that 1.2 has poor performance when it comes to samples. Most of it has been fixed in the 1.3 alpha and we expect to see more improvements by the time 1.3 gets released

**Comment by rgndxzzk** [comment] 2022-08-21 16:16
> Have you tried the 1.3 alpha before writing this? It is a known fact that 1.2 has poor performance when it comes to samples. Most of it has been fixed in the 1.3 alpha and we expect to see more improvements by the time 1.3 gets released

yeah, its also an issue on 1.3 alpha, im currently using 1.3.0-alpha.1.217

**Comment by allejok96** [comment] 2022-08-28 19:23
Sample performance is still terrible. Every time you copy a sample it creates a new copy in memory. There's lots of ongoing work with this in #6390. I can't say if it will actually load a sample quicker, but at least it will only load each sample once.

**Comment by allejok96** [comment] 2022-09-10 09:44
The core issue of this bug report is that long samples takes a long time to load. Background loading would only fix GUI responsiveness, not the slow/double load time.  A time limit would be annoying and it would not really prevent UI from hanging. As suggested, the best solution would be to load the sample in segments - at least when previewing.

Thus making this a duplicate of #4015 (see also #1471)

**Closed by allejok96** 2022-09-10 09:44 UTC
Labels: enhancement
