### ISSUE TITLE
Note marking behavior

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1119] opened 2014-08-30 11:10 UTC
If no-length notes are marked using ctrl+a they will not be marked, unless they are 'inside' a rectangle area limited by normal notes:
![paste](https://cloud.githubusercontent.com/assets/6662066/4098835/cdc7f2fa-3039-11e4-87e5-074eec15370b.jpg)
Looks like the ctrl+a method scans for normal-notes and determin the area out from these normal-notes borders, and *then* mark **all** (including no-length) inside that rectangle. 
so the arrow marked notes will not be marked

 *Updated Jan 24, zonkmachine*

**Comment by Umcaruje** [comment] 2015-07-02 21:49
Reproduced on Ubuntu 15.04 x64 - Can't select no-length notes using `ctrl + a`.

**Comment by zonkmachine** [comment] 2015-12-19 17:22
I had a go at this one and the fix looks promising. The beat notes are also not marked visually and I'll try and see if I can fix that too.

**Comment by zonkmachine** [comment] 2016-01-16 01:03
This is in 1.0 and maybe introduced pre 0.4.0 ( as the code I've touched in #2491 is there and mostly the same in 0.3.2 )

**Comment by musikBear** [comment] 2016-01-16 11:05
I tested for 1.1.1-g23d2824 from 14. jan 2016 by @tresf 
It is *almost* fixed:
![nolengthcopyfixed](https://cloud.githubusercontent.com/assets/6662066/12371964/886cc452-bc46-11e5-9a84-935702496e71.png)

The whole block was marked, and then copied, and moved one beat. All *no-length-notes*, even those outside the 'normal-note-block limit', was included in both selection, copy and move. 
I tried: 
* D&D copy 
* ctrl+v copy. 
* time-line+sh selection + copy
All with success.

Not fixed:  
**ctrl-a** selections will  **not** include no-length-notes **if** they are outside the 'normal-note-block limit'. (*) 
There is no *visual* difference between selected no-length-notes, and unselected.

(*) Is ctrl+a at all included in 1.2 features ??

**Comment by Umcaruje** [comment] 2016-01-16 11:54
> tested for 1.1.1-g23d2824 from 14. jan 2016 by @tresf 

@musikBear #2491 hasn't been merged yet, so that build is irrelevant for testing. You would need someone to make you a windows build of @zonkmachine's branch so you can test it.

**Comment by zonkmachine** [comment] 2016-01-16 17:34
> There is no visual difference between selected no-length-notes, and unselected.

Fixed this. I think. Right now trailing beat notes are not selected if they go over the length of the beat steps. This only show up if I first copy beat notes, paste them outside of the range and then do a second Ctrl+A.

**Comment by zonkmachine** [comment] 2016-01-17 00:36
I'm not sure what the best behaviour is here. If you open a beat pattern in the PianoRoll editor and copy paste notes so they go over the beat pattern then maybe you're not supposed to be able to mark these notes by Ctrl + A. They won't be reached anyway through playback in the BBEditor unless you increase the length of the beat pattern.

**Comment by musikBear** [comment] 2016-01-17 12:15
> I'm not sure what the best behaviour is here

@zonkmachine  that is perhaps worth a thought, but it could also appear confusingly, for users.

**Comment by zonkmachine** [comment] 2016-01-24 04:51
@tresf @Umcaruje 

I perceive this as three separate bugs.

 1 Beat notes, not enclosed by normal notes, not selected.
 2 Beat notes are not visually marked when selected.
 3 Beat notes not selectable if the extend beyond the length of the beat pattern.

Number 1 and 2 is fixed in https://github.com/LMMS/lmms/issues/2491 . The beat notes had been selected deliberately and, we can assume, for a good reason but since then ( it looks like an old bug ) has bitrotten away a bit.
Number 3 I took a guess at and came up with Pattern.cpp as possible culprit and is nothing I can take on right now.

I think my fixes should be merged, this issue closed and a new issue opened for bug number 3 .

**Comment by Umcaruje** [comment] 2016-01-24 15:43
>I think my fixes should be merged, this issue closed and a new issue opened for bug number 3 .

Sounds good to me. I'm a bit busy atm, but I think I'll get to testing out your PR sometime today.

**Comment by zonkmachine** [comment] 2016-07-20 18:55
Closed in #2491

**Closed by zonkmachine** 2016-07-20 18:55 UTC
Labels: bug, gui
