### ISSUE TITLE
Piano Roll scroll problem

### ISSUE THREAD

**Issue by moacirrf** [LMMS/lmms#5977] opened 2021-04-09 02:14 UTC
Version:1.3.0 alpha
Os Version: Linux Manjaro 21.0, Kde

I think it is a bug.

Step to reproduce
Open piano roll, try scroll, the ruler and the arrow don't keep synchronized, occur when time is 2/4,3/4 etc.
Don't occur  when is 4/4, 3/3 etc..

![lmms](https://user-images.githubusercontent.com/950706/114117995-44c68080-98be-11eb-963a-27a4e1b9c443.gif)

Any tip to fix this?

Thanks

**Comment by Spekular** [comment] 2021-04-09 06:52
Related: #5962 

Can you test the build from #5965 and see if the issue still occurs?

**Comment by moacirrf** [comment] 2021-04-10 03:34
> Related: #5962
> 
> Can you test the build from #5965 and see if the issue still occurs?

This build fixed the issue.

Thanks!

**Comment by Veratil** [comment] 2021-04-10 04:26
Closing as duplicate of #5962

**Closed by Veratil** 2021-04-10 04:26 UTC
Labels: bug
