### ISSUE TITLE
[Bug] Crash while rendering with Focusrite Asio.

### ISSUE THREAD

**Issue by Arber87** [LMMS/lmms#3188] opened 2016-12-29 03:49 UTC
It works fine with Asio4All, but crashes when exporting with Focusrite ASIO.

**Comment by tresf** [comment] 2016-12-29 04:46
@Arber87 can you provide exact steps to reproduce please, including installing and configuring the ASIO plugin?

**Comment by Arber87** [comment] 2016-12-29 20:18
I used the old libportaudio-2.dll with ASIO support on a Windows 7 PC. Export options were wav 
32 bit float, 88200 khz, best interpolation; Maybe i'm doing something incorrectly?

**Comment by tresf** [comment] 2016-12-29 20:38
Exact steps to reproduce are required for anyone else to reproduce, including how to obtain Focrusrite (please specify 32-bit versus 64-bit) and how to configure LMMS to use it.  Without proper steps, this will be closed as invalid.

**Comment by Arber87** [comment] 2016-12-29 20:50
Sorry for the trouble. I understand that it is a non-free driver for their 2i2 interface. You can close the thread.

**Comment by tresf** [comment] 2016-12-29 20:57
> Sorry for the trouble. I understand that it is a non-free driver for their 2i2 interface. You can close the thread.

Non-free is OK, a lot of music components are paid, but the steps you followed to get the crash are still relevant.

If the issue is hardware specific, we can keep it open, until someone from the development team has the time to reproduce.  The more details the better, you can edit your original bug report with the details.

**Comment by Umcaruje** [comment] 2016-12-29 20:57
Well, we don't officially support ASIO with our portaudio drivers and this might even be a bug with the dll that you obtained. I don't think we can really help out with this issue at the time, until we actually ship with ASIO support.

You might have some luck by using a dll from the Bitwig Studio demo installation. Some users on the forums had luck with that.

**Closed by Umcaruje** 2016-12-29 20:57 UTC

**Comment by Arber87** [comment] 2016-12-29 21:10
Thank you kind gentlemen for this wonderful program! Happy Holidays! Proud to be a beta tester!
