### ISSUE TITLE
Add a download manager to download audio / presets ressources from the web

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2794] opened 2016-05-24 06:13 UTC
Add a download manager to download audio / presets ressources from the web.
Something like the download manager from the hydrogen drum sequencer which download drum sound fonts from sourceforge.

**Comment by tresf** [comment] 2016-05-24 11:48
@ycollet we discussed this for quite a while here: #661

The decision was made to shelve this for a while due to money, complexity and lack of help of the solution.  I'll leave this open for a while incase people want to discuss, but unless someone decides to run with it, it'll be marked as a duplicate of #661, which is closed.

**Comment by lukas-w** [comment] 2019-03-09 17:38
Closing as duplicate of #661.

**Closed by lukas-w** 2019-03-09 17:38 UTC
