### ISSUE TITLE
Timestamp broken when loading new project

### ISSUE THREAD

**Issue by KodzghlyCZ** [LMMS/lmms#4830] opened 2019-02-18 20:35 UTC
When I play some project and then I load the other one, the timestamp shows negative time, even if the starting point is set to zero. Not a big deal, but still a bug ;)

---
_Edit: zonkmachine_
**Method to reproduce**

It seem to be a condition to have the stop behavior set to **After stopping keep position**.
The issue doesn't show up all the time so you may have to repeat the method below a number of times.

1. Load Skiessi-Onion
2. Click the timeline to fast forward the song to somewhere in the end.
3. Press play.
4. Press the pause button. (this stage optional).
5. Reload the project or open another song.

![lmmstime](https://user-images.githubusercontent.com/6368949/54841528-bfb8a080-4ccf-11e9-8eaa-3a914c27895a.png)

**Comment by musikBear** [comment] 2019-02-19 14:52
What 
* OS?  
* LMMS? 

-By 'timestamp' you mean the **Timer-position**, and *not* the file-date-time-stamp -correct?
I have occasionally seen wrong values on Timer-position-gadget too, but if you click it twice it is usually fine again

**Comment by KodzghlyCZ** [comment] 2019-02-19 15:12
Yes, I mean timer position. I am using LMMS 1.2.0-RC7 on Windows 10

**Comment by tresf** [comment] 2019-03-06 21:35
@KodzghlyCZ I can't reproduce.  Please provide exact steps to recreate so that we can reproduce, identify and fix!

**Comment by PhysSong** [comment] 2019-03-12 11:26
Possible duplicate of #4282.

**Comment by zonkmachine** [comment] 2019-03-22 17:37
A glitch it is. I updated the issue with a method to reproduce it.

**Comment by zonkmachine** [comment] 2019-10-20 19:31
> Possible duplicate of #4282.

Yes. This looks like the same issue. Closing.

**Closed by zonkmachine** 2019-10-20 19:31 UTC
Labels: bug, duplicate
