### ISSUE TITLE
Beat baseline clone seems to be reference instead of clone.

### ISSUE THREAD

**Issue by Guido1234** [LMMS/lmms#4417] opened 2018-06-10 17:35 UTC
Version 1.2.0 rc6
Steps to reproduce:

Step 1: open LMMS
Step 2: Open "Beat/Baseline 0"
Step 3: Add beats to kicker
Step 4: Clone this track ("kicker")
Step 5: Change the kicker clone.
Step 6: Close beat baseline editor ("Beat/Baseline 0")
Step 7: Clone "Beat/Baseline 0"
Step 8: Open "Clone of Beat/Bassline 0"
Step 9: Remove second kicker.
Step 10: Close "Clone of Beat/Bassline 0"
Step 11: Open "Beat/Baseline 0" 

In the original "Beat/Baseline 0" The second kicker is gone too. It seams that "Clone of Beat/Bassline 0"
is a reference to the original instead of a true copy / clone.

**Comment by lukas-w** [comment] 2018-06-10 18:02
@Guido1234 Thanks for the well-written report. The steps you provide are great for understanding what you're saying.

However, this is intended behaviour and just how LMMS works currently. You can find more information about the workings of the BB Editor in our documentation (https://lmms.io/documentation/Beat_Bassline_Editor):

> **Warning: all the BB tracks you create are linked in such a way that they share the same instruments.** If you delete or toggle-mute an instrument in one BB track, it's deleted from or toggle-muted in all the BB tracks in this project.

There have been suggestions to improve this like #453, which would make instruments belong to the BB track they are contained in, rather than being shared across all BB tracks.

Closing this as invalid because it's not a bug. Anyway, thanks for taking the time to report it. Feel free to join the discussion in #453 or just leave your ":+1:".

**Closed by lukas-w** 2018-06-10 18:02 UTC

**Comment by Cristy94** [comment] 2021-07-06 15:58
I stumbled upon the same issue.

Is there no way in LMMS to copy a baseline and modify it without modifying the original?
