### ISSUE TITLE
LMMS can't encode/decode audio files that contain Arabic letters/symbols in their names.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3901] opened 2017-10-22 16:22 UTC
A string with Arabic letters and symbols for testing: `مُوسيقى`.

**Comment by PhysSong** [comment] 2017-10-22 22:09
Duplicate of #1191

**Closed** 2017-10-22 22:09 UTC
Labels: duplicate

**Comment by Sawuare** [comment] 2017-10-23 03:38
Sorry, didn't search well enough. ;(
