### ISSUE TITLE
Crash KickerOsc

### ISSUE THREAD

**Issue by gi0e5b06** [LMMS/lmms#4129] opened 2018-01-25 14:36 UTC
```
0x00007fffc376bc2b in KickerOsc<DspEffectLibrary::MonoToStereoAdaptor<DspEffectLibrary::Distortion, DspEffectLibrary::Distortion> >::update (this=0x0, buf=0x7fffec56c810, frames=256, sampleRate=44100)
    at /plugins/kicker/KickerOsc.h:68
68                              const double gain = ( 1 - fastPow( ( m_counter < m_length ) ? m_counter / m_length : 1, m_env ) );
#1  0x00007fffc37692dc in kickerInstrument::playNote (this=0x7fffec4562d0, _n=0x7fffeca55538,
    _working_buffer=0x7fffec56c810) at /plugins/kicker/kicker.cpp:194
#2  0x00005555558636ce in InstrumentTrack::playNote (this=0x55555a6c8190, _n=0x7fffeca55538, _workingBuffer=0x7fffec56c810)
    at /src/tracks/InstrumentTrack.cpp:502
```
[test-kickosc.zip](https://github.com/LMMS/lmms/files/1664329/test-kickosc.zip)

**Comment by PhysSong** [comment] 2018-01-26 06:28
Can't reproduce crash, either on `stable-1.2` nor `master`. I can't even open the original project correctly because of additional `notehumanizing` and `noteduplicatesremoving`.
After removing them, I was able to open the project. I played this project, but LMMS didn't crash.

`this=0x0` says the `NotePlayHandle`(`_n`) doesn't have a valid plug-in data. For Kicker, it may happen if and only if `kickerInstrument::playNote` is not called at the first period.
https://github.com/LMMS/lmms/blob/a193ec25f2b6f133e60902cb4c274621fa62ce39/plugins/kicker/kicker.cpp#L173-L175
And I suspect this crash is because of https://github.com/gi0e5b06/lmms/commit/155f960b7a69f44a4202d5659320ea727e624931#diff-fdb615eb3a3b0a959eb14e42c4d9d07dR493. If this guess is right, you shouldn't get crash after disabling "Duplicates remover".

I think this issue should be marked as `invalid` if disabling that effect fixes this crash, since it means official LMMS releases are not affected.

**Comment by PhysSong** [comment] 2018-02-18 03:30
Closing as `invalid`.

**Closed by PhysSong** 2018-02-18 03:30 UTC

**Comment by gi0e5b06** [comment] 2018-04-02 12:26
The problem is about adding/removing NotePlayHandles thread-safely. This is not the case with the current branch and it is the main cause of crashes.

**Comment by lukas-w** [comment] 2018-04-03 07:17
@gi0e5b06 Feel free to create a new issue explaining the problems with thread-safety regarding NotePlayHandles in more detail or to provide steps for reproducing the crash on current `master` or `stable-1.2`.

**Comment by PhysSong** [comment] 2018-04-03 08:59
> or to provide steps for reproducing the crash on current `master` or `stable-1.2`.

You shouldn't be able to reproduce that on current `master` or `stable-1.2`.

**Comment by lukas-w** [comment] 2018-04-03 09:12
Exactly, all the more reason why it's @gi0e5b06's job to provide these steps, not ours. :wink:

**Comment by gi0e5b06** [comment] 2018-04-03 09:34
You can reproduce it by quickly moving patterns when playing them. The GUI thread will remove handles that the rendering thread is still using.

**Comment by PhysSong** [comment] 2018-04-03 09:45
> You can reproduce it by quickly moving patterns when playing them.

Got a crash, but that was #3956.

**Comment by gi0e5b06** [comment] 2018-04-03 11:02
@PhysSong Yes, both are related somehow. #3956 is about handles disappearing. This one is about associated data disappearing.
