### ISSUE TITLE
mallets broken on master build

### ISSUE THREAD

**Issue by Rossmaxx** [LMMS/lmms#6464] opened 2022-07-17 04:26 UTC
### Bug Summary
i tried using mallets on the latest master, only to find out it's broken. 

#### Steps to reproduce
drop mallets on the song editor or the pattern editor and open instrument settings.

#### Expected behavior
mallets should play fine

#### Actual behavior
it gives the error 'stk not installed'. the instrument opens but doesn't give any sound.

#### Screenshot
![image](https://user-images.githubusercontent.com/74815851/179383502-571c79c1-7ee0-4e8d-8a9c-fa0887495412.png)

https://youtu.be/hLBVz5jSoTM

#### Affected LMMS versions
1.3 master - builds #6462 and #6374 (pre merge ci build)

**Comment by Monospace-V** [comment] 2022-07-17 05:04
Confirmed.
I faced a similar issue. To make Mallets work, I copied the data/STK/RawWaves file from my 1.2.0 install to where they're supposed to be in the filepath of my 1.3 install, then forgot about it.
I considered reporting it, but I have a slightly unconventional method of installation, and since this is actually a lack-of-files problem, I thought this specific issue might've been avoided if I installed normally.

**Comment by musikBear** [comment] 2022-07-17 15:15
Mallets issues: 
 Mallets no sound under Tubular Bells #2455 
 (LMMS 1.2.0rc6) Changing the type of Mallets plays weird sounds #4269 
 
Needs an overhaul

**Comment by zonkmachine** [comment] 2022-07-17 22:56
@musikBear Those are, quite obviously, unrelated issues. Please bring it up on Discord instead.

**Comment by musikBear** [comment] 2022-07-18 17:29
> @musikBear Those are, quite obviously, unrelated issues. Please bring it up on Discord instead.

It is meant to be a _summery of issues_ with Mallets

**Comment by zonkmachine** [comment] 2022-07-18 18:04
> > @musikBear Those are, quite obviously, unrelated issues. Please bring it up on Discord instead.
> 
> It is meant to be a _summery of issues_ with Mallets

I understand that. A summary of two issues, one that was closed in 2016 and one that was closed yesterday. It's off topic.

**Comment by musikBear** [comment] 2022-07-20 14:55
> > > @musikBear Those are, quite obviously, unrelated issues. Please bring it up on Discord instead.
> > 
> > 
> > It is meant to be a _summery of issues_ with Mallets
> 
> I understand that. A summary of two issues, one that was _closed in 2016 and one that was closed yesterday_. It's off topic.

lOOl i diddent see they were closed -sorry, no need for the summery. You are right. 👍

**Comment by zonkmachine** [comment] 2022-07-20 15:26
*Moderation: OT discussion deleted*

**Comment by zonkmachine** [comment] 2022-07-21 14:52
> i know this isnt a fix but i would appreciate if a fix for #6464 was included on this pr.

I can't replicate this issue and I'm not really a programmer by any stretch of the imagination but if you hand me the actual commit that caused it I can look into it. Also, please keep this discussion here.

**Comment by Rossmaxx** [comment] 2022-07-22 04:27
> Also, please keep this discussion here.

Oops, mb. 

Also, since all the builds i had the error were from the CI, i think this has something to do with the CI not bundling the stk.

**Comment by tresf** [comment] 2022-08-01 16:51
> This issue is specific to windows. We rely on `MINGW_PREFIX` when trying to bundle STK rawwave files.

To elaborate a bit: https://github.com/LMMS/lmms/issues/3227#issuecomment-1201457137

**Comment by PhysSong** [comment] 2022-08-02 01:45
I wrote an installation logic which should work in most cases(needs testing).
```cmake
# Install STK rawwaves
if(LMMS_HAVE_STK)
	find_path(STK_RAWWAVE_ROOT
		NAMES silence.raw sinewave.raw
		HINTS "${STK_INCLUDE_DIR}/../.."
		PATH_SUFFIXES share/stk/rawwaves share/libstk/rawwaves
	)
	if(STK_RAWWAVE_ROOT)
		file(GLOB RAWWAVES "${STK_RAWWAVE_ROOT}/*.raw")
		install(FILES ${RAWWAVES} DESTINATION "${DATA_DIR}/stk/rawwaves")
	else()
		message(WARNING "Can't find STK rawwave root!")
	endif()
endif()
```

**Comment by tresf** [comment] 2022-08-02 02:35
> I wrote an installation logic which should work in most cases(needs testing).
> 
> ```cmake
> # Install STK rawwaves
> if(LMMS_HAVE_STK)
> 	find_path(STK_RAWWAVE_ROOT
> 		NAMES silence.raw sinewave.raw
> 		HINTS "${STK_INCLUDE_DIR}/../.."
> 		PATH_SUFFIXES share/stk/rawwaves share/libstk/rawwaves
> 	)
> 	if(STK_RAWWAVE_ROOT)
> 		file(GLOB RAWWAVES "${STK_RAWWAVE_ROOT}/*.raw")
> 		install(FILES ${RAWWAVES} DESTINATION "${DATA_DIR}/stk/rawwaves")
> 	else()
> 		message(WARNING "Can't find STK rawwave root!")
> 	endif()
> endif()
> ```

This seems more like a `FindStk.cmake` candidate, no?

**Comment by PhysSong** [comment] 2022-08-02 02:52
> This seems more like a `FindStk.cmake` candidate, no?

The `find_path` part may reside in the file, but the `install` part shouldn't.

**Comment by tresf** [comment] 2022-08-02 03:20
> > This seems more like a `FindStk.cmake` candidate, no?
> 
> The `find_path` part may reside in the file, but the `install` part shouldn't.

Clearly, but this is a "where is STK" problem, which doesn't really belong in installation logic, but rather dependency location.

**Comment by tresf** [comment] 2022-08-02 03:23
```cmake
HINTS "${STK_INCLUDE_DIR}/../.."
```

This would be copying from source, no?  I would expect to copy from installation.  Does `vcpkg` have a way to calculate this?

**Comment by tresf** [comment] 2022-08-02 03:26
e.g. 

> In the case of STK, it has a formula ready on vcpkg, so I'd look there first, quoting the portfile.cmake from vcpkg:
>
> ```cmake
> file(GLOB RAWFILES ${SOURCE_PATH}/rawwaves/*.raw)
> file(COPY ${RAWFILES} DESTINATION ${CURRENT_PACKAGES_DIR}/share/libstk/rawwaves)
> ```

I'd expect to use the bottom, not the top, no?

**Comment by PhysSong** [comment] 2022-08-02 03:27
> This would be copying from source, no? I would expect to copy from installation.

My intention was to use `<STK PREFIX>/include/stk` as a hint when finding `<STK PREFIX>/share/[lib]stk/rawwaves`.

**Comment by PhysSong** [comment] 2022-08-02 03:31
> I'd expect to use the bottom, not the top, no?

Do we even have access to the top? What I'm trying to find is the bottom.

**Comment by tresf** [comment] 2022-08-02 03:38
> > I'd expect to use the bottom, not the top, no?
> 
> Do we even have access to the top? What I'm trying to find is the bottom.

Sorry I'm confusing headers for source. 🤦‍♂️

**Comment by anytizer** [comment] 2023-01-28 08:41
[Reference](https://filipe-teixeira.com/2017/10/missing-files-from-stk-on-lmms/)

Folder [data]/stk/rawaves is missing. Replace it and it works.

Other findings:

- Rename .lmmsrc.xml file.
- Close LMMS and reopen it.
- In the configuration window, you do NOT see options to enter stk path.

In the newly created .xml file, the xml appears.
`<paths stkdir="data:/stk/rawwaves/"/>`

**Comment by Monospace-V** [comment] 2023-01-28 11:03
> [Reference](https://filipe-teixeira.com/2017/10/missing-files-from-stk-on-lmms/)
> 
> Folder [data]/stk/rawaves is missing. Replace it and it works.
> 
> Other findings:
> 
> * Rename .lmmsrc.xml file.
> * Close LMMS and reopen it.
> * In the configuration window, you do NOT see options to enter stk path.
> 
> In the newly created .xml file, the xml appears. `<paths stkdir="data:/stk/rawwaves/"/>`

Correct! This is a default folder which should not have to be user-inputted and is a native part of LMMS that should automatically set.
This folder shouldn't be missing in the first place.

**Comment by anytizer** [comment] 2023-02-09 02:43
`apt install stk` => `/usr/share/stk/rawwaves`, looks like, it has been borrowed from: [thestk/stk](https://github.com/thestk/stk) project. Mallets are functional with this folder placed at data/stk/rawwaves.

**Closed** 2023-06-24 02:58 UTC
Labels: bug
