### ISSUE TITLE
mixer-vst compatibility

### ISSUE THREAD

**Issue by OverweightCreator** [LMMS/lmms#5382] opened 2020-01-25 17:18 UTC
LMMS Version: 1.2.1 RC4, Win64
OS: Win10

Issue:
1)Some plugins with their own built-in mixer can not direct sound to non-master channels of FX mixer
2)Also there is no possibility to attach recorded audio to non-master channel, so it can be special VST effect that you attach to recording and inside it you can choose the channel with the same mechanism as point 1.
Steps to repruduce :
1)install and open mixer in https://www.powerdrumkit.com/ (free drums)
2)Change kick channel from 1 to 2
3)add a chanel to FX mixer in LMMS(we should have second channel since we've changed kick channel inside built-in MT power mixer from 1 to 2)
there is no sound of kick anymore

**Comment by Spekular** [comment] 2020-02-22 12:21
Issue 2 is already solved on master, sample tracks now allow mixer channel selection.

As for point 1, how is this functionality intended to work? Have you tested in another DAW that changing the mixer channel in the VST sends to a different channel in the DAWs mixer? I've never heard of that kind of functionality. I'd expect the mixer to be used inside the VST, and then the sum of those channels would send out as one stream.

**Comment by Spekular** [comment] 2020-02-22 12:23
Marking as response-required. Specifically, @OverweightCreator please confirm that this feature works as you expect it to in another DAW (I believe both FL studio and Ableton have trial versions).

**Comment by zonkmachine** [comment] 2020-02-22 21:03
> LMMS Version: 1.2.1 RC4, Win64

It's also unclear which version you are using. It's either [1.2.0-RC4](https://github.com/LMMS/lmms/releases/tag/v1.2.0-rc4) or [1.2.1](https://github.com/LMMS/lmms/releases/tag/v1.2.1)

**Comment by OverweightCreator** [comment] 2020-02-23 13:31
> Marking as response-required. Specifically, @OverweightCreator please confirm that this feature works as you expect it to in another DAW (I believe both FL studio and Ableton have trial versions).

It forks fine in Reaper. That is common feature for vst drums: you need to deal with each drum with different FX chains, so vst plugin allows you to choose chanel in DAW mixer for each drum. I didn't check it is possible to direct it to ANY chanel, but when I added this VST, a special dialog window offered me to make extra channels, binded to current. Here is example : MT power kit main channel (numer 18 in DAW)makes no sound, next one stands for kick and toms, then one channel for snare and one channel for all of the drum cymbals
![image](https://user-images.githubusercontent.com/42464672/75112913-dbec5c80-5659-11ea-8c2d-2b5620824a55.png)

**Comment by OverweightCreator** [comment] 2020-02-23 13:33
> > LMMS Version: 1.2.1 RC4, Win64
> 
> It's also unclear which version you are using. It's either [1.2.0-RC4](https://github.com/LMMS/lmms/releases/tag/v1.2.0-rc4) or [1.2.1](https://github.com/LMMS/lmms/releases/tag/v1.2.1)

seems that 1.2.1 , but I changed my computer since I asked the question, can't check old one

**Comment by DomClark** [comment] 2020-02-23 20:40
Duplicate of #5108?

**Comment by OverweightCreator** [comment] 2020-02-23 20:45
> Duplicate of #5108?

yeah ,seems to be true,sry

**Comment by DomClark** [comment] 2020-02-23 20:48
> yeah ,seems to be true,sry

No worries, thank you for the suggestion! Closing this now.

**Closed by DomClark** 2020-02-23 20:48 UTC
Labels: enhancement
