### ISSUE TITLE
Song editor scroll back

### ISSUE THREAD

**Issue by midi-pascal** [LMMS/lmms#2145] opened 2015-06-30 11:47 UTC
A little feature missing in the song editor:
The last button "After stopping go back to begin" does what is supposed to do (the marker is back) but the song editor does not scroll back so you have to scroll manually to the beginning of the song.
I think this would be useful.

**Comment by BaraMGB** [comment] 2015-07-01 19:31
I think, the auto-scroll has a bug.

**Comment by BaraMGB** [comment] 2015-07-01 19:39
Oh, I tested only with an empty project. The auto-scroll follows the playhead only if there is something to play. I think that's not a bug it's a feature. But I can confirm the playhead jumps to start but the editor not.

**Comment by midi-pascal** [comment] 2015-07-01 20:18
@BaraMGB That's the point: the playhead is Ok but not the Song Editor. When you have a long piece of music, this is a real annoyance.

**Comment by tresf** [comment] 2015-08-24 14:30
Closing as duplicate of meta-bug **Better Playhead Auto-Scroll #2291**.  Please feel free to comment here if needed.

**Closed by tresf** 2015-08-24 14:30 UTC
Labels: enhancement, ux

**Comment by midi-pascal** [comment] 2015-10-20 22:06
@tresf Sorry to bother you again. I pushed a fix for this issue in the same fork as the one I used for the previous PR.
Now the PR for issue 2401 contains the fix for this one too.
How can I "unpush" this fix from this github fork (https://github.com/LMMS/lmms/compare/master...midi-pascal:new_branch)?
The two issues are completely unrelated so I can push this one to my other fork.
Thanks!

**Comment by tresf** [comment] 2015-10-20 23:15
Well, first, your sf2 changes shouldn't be in your master branch, that master branch should be even with upstream's master, so you'll probably want to fix that eventually.

In regards to the wrong branch, the easiest way is to back up your changes and hard-reset the sf2 branch to the previous good commit, which I just copied the first 7 characters from the last valid commit ID from the `midi-pascal/new_branch` by looking at the commits here:

https://github.com/midi-pascal/lmms/commits/new_branch

(browse to **new_branch** and replace the word `tree` in the URL with the word `commits`)

```
cp src/core/Song.cpp ~/Desktop/ # backup changes
git reset --hard 44e2b9f # force back to the sf2 commit
git push --force # rewrite history on the `new_branch` branch
```

Quite often, people will create an inverse patch, which adds a commit to the history which removes the bad commit.  This is generally the preferred method when on upstream, but on a fork, you can rewrite history until your heart's content, it only affects your stuff.

If you had created the inverse patch, we could have used the `pick/squash` methods detailed in the other thread.

This bug report is already closed, but reminder, remember to put `Closes #1234` in your commit or PR if you wish to automatically close a bug report.

**Comment by midi-pascal** [comment] 2015-10-20 23:44
@tresf Thanks again! My new_branch is clean now. I will try to clean my master branch by myself. One thing I do not quite understand: do I have to create a branch on github for each issue I work on? When I pushed my changes for this issue I thought I could create a new PR from it. It was added to the current PR instead. Hence an other goof...
you can be sure I will follow your recommendations when creating the next PR.

For this issue, I will add the information in the meta-issue. It enhances the usability of the stop options in the song editor (scroll back to the beginning or to the time line position, depending on the option selected with the 3 states button)

**Comment by tresf** [comment] 2015-10-21 00:30
I made the same exact mistake.  Yes, a branch for every PR.  The PR is a living breathing branch.  The upside is we can tweak before it gets accepted.

The downside is you end up with a lot of temporary branches.

**Comment by tresf** [comment] 2015-10-22 13:41
@musikBear, do you have some time to test this feature out?

You can download the win32 version here:
https://github.com/tresf/lmms/releases/download/v1.1.90-ga95909e/lmms-1.0.96-ga95909e-win32.exe

**Comment by musikBear** [comment] 2015-10-23 11:42
> @musikBear, do you have some time to test this feature out?

i will do that

**Comment by musikBear** [comment] 2015-10-23 12:51
The execution fails
![noentry](https://cloud.githubusercontent.com/assets/6662066/10692932/1c311318-7995-11e5-8110-d16410c878a1.png)

so the version does not execute on xpSp3-32
If you make a new binary, then include the patch for sf2. Then i can run a long test on that change too.
If you could let me know if it will be in the weekend, it would be appreciated. 
I wont re-install my 1.1.3 before the next test, then :)

**Comment by tresf** [comment] 2015-10-23 14:35
I'm not going to do the SF2 patch just yet since it has plenty of testing prior to merging.

The entry point error is often associated with very old Windows versions.  You didn't try to run in compatiblity mode, right?  Did you search around for that error to see what could be causing it?

**Comment by tresf** [comment] 2015-10-23 14:39
@musikBear the end may be near.... 

https://msdn.microsoft.com/en-us/library/windows/desktop/aa363808(v=vs.85).aspx

**Comment by musikBear** [comment] 2015-10-23 16:50
oh oh.. does not look nice for xp users -Question is now what percentage of the LMMS usergroup that actually still are on xp, -Has to end, true, but for how many
Can the previous survey enlighten ?

**Comment by tresf** [comment] 2015-10-23 16:51
> what percentage of the LMMS usergroup that actually still are on xp


Don't know, but if our toolchain won't support it, they'll have to download a legacy version.

**Comment by musikBear** [comment] 2015-10-23 16:59
ya- 

but in case it matters.. Mater from 24. sept. was the one i tested waxpins addons. That opened ok. Are there made significant changes in code since then?

**Comment by tresf** [comment] 2015-10-23 17:44
> Are there made significant changes in code since then?

We don't have direct control over our build tools.  We use the `mingw-w64` toolchain to build our software, and that updates regularly.  Whether or not this specific Windows XP crash is attributed to a mingw change has yet to be determined, but we shouldn't spend too much time talking about it here, it is off topic.

In the mean time, if you would like to continue as a tester, you should prepare an environment suitable for running modern builds (This can be Linux, Windows or Mac and Linux and Windows can both be virtualized in something like VirtualBox if you decide to remain on XP as your base system).
