### ISSUE TITLE
Organic artwork proposal

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2404] opened 2015-10-10 05:29 UTC
I worked on a skin for the organic plugin.

![artwork](https://cloud.githubusercontent.com/assets/12549082/10409442/f4dfd056-6ee5-11e5-9d1c-e12cf5e94a15.png)

I still need to change the fonts and add a new drawing for the carrot (I don't know how to draw so if anyone could help, It'll be cool)

**Comment by IvanMaldonado** [comment] 2015-10-13 05:43
Changed the plugin bottom layer.

![layer](https://cloud.githubusercontent.com/assets/12549082/10446713/5ceeab90-7143-11e5-9f90-224299219b6e.png)

**Comment by musikBear** [comment] 2015-10-13 11:49
:+1: sexy ..but 'organic' ..
is *that* instrument worth a rehaul ?
I kind of see it as a 'kept for backward reasons' 
I could be dead wrong.. of cause
![organic](https://cloud.githubusercontent.com/assets/6662066/10453974/39701cb2-71b1-11e5-87f5-592a1ad0ac9c.png)

**Comment by tresf** [comment] 2015-10-16 12:52
> :+1: sexy ..but 'organic' ..
> is that instrument worth a rehaul ?

It is one of the instruments that was never re-skinned, so yes.

> I kind of see it as a 'kept for backward reasons'  I could be dead wrong.. of cause

What does this mean?

> Suited artwork :p ?

No.

**Comment by Spekular** [comment] 2015-10-16 18:51
Perhaps something like this?
![carrot](https://cloud.githubusercontent.com/assets/8918426/10550362/d92c6714-7446-11e5-85d8-1ec47c7b0fc1.png)
Here's a flipped + rotated version in the new UI:
![organic](https://cloud.githubusercontent.com/assets/8918426/10550374/e87c081e-7446-11e5-9076-cb9c8f8b11ab.png)
It's just a png atm but it shouldn't be hard to recreate as an svg if you guys like it. My one issue is that while I like the more modern look it doesn't really fit with the idea of "organic". A logo that's more similar to the current one but tweaked could be nice, I'm thinking similar to Wind Waker's art style, since the little notch in the carrot reminds me of the cloud/twirl/whirl ![cloud/twirl/whirl](http://i.imgur.com/Ig6nRZy.jpg)
Apologies for the images taking so much space, I don't think I can scale them down on github.

**Comment by tresf** [comment] 2015-10-16 18:55
> Apologies for the images taking so much space, I don't think I can scale them down on github.

Zoom out of web page (CTRL + Mousewheel), take screenshot using Snipping Tool (windows), Option + Shift + 4 (mac) or whatever Linux comes with.

Drag or paste into bug report.  Here's an example:

![image](https://cloud.githubusercontent.com/assets/6345473/10550619/f2b5de8a-7415-11e5-972d-137a7b2acc34.png)

**Comment by tresf** [comment] 2015-10-16 19:27
I'm not attached to the pixel-art personally... Perhaps something like this for inspiration (Copyright [BigBase 2013](https://wrapbootstrap.com/logo/organic-logo-WB0933574))

![image](https://cloud.githubusercontent.com/assets/6345473/10551322/478b5f12-741a-11e5-85f1-92b98b0676b0.png)

**Comment by Umcaruje** [comment] 2015-10-16 20:30
>It is one of the instruments that was never re-skinned, so yes.

It was redesigned 2 times: 

![image](https://cloud.githubusercontent.com/assets/6282045/10552611/4ac9e3f2-7455-11e5-9d90-6ea07f8412de.png)

I was the one who did the logo for the newest version: 

![logoogo](https://cloud.githubusercontent.com/assets/6282045/10552621/6216ada6-7455-11e5-9323-50265d549e6e.png)

If you guys like it, I'd probably revamp it and change the color a bit.

**Comment by tresf** [comment] 2015-10-17 00:49
> It was redesigned 2 times [...] I was the one who did the logo for the newest version

My apologies.  Well, in that case, we can close this request out unless there is a specific reason to update it.

**Comment by Spekular** [comment] 2015-10-17 12:11
@tresf 
I'm assuming this was created because of 2293, and I can see a redesign being worth it since this uses the same style with shadows/gradients as the ones that were removed in 3xOsc. That, along with assuming we were keeping the current logo idea, is what led to my first post.

If on the other hand we're going to change the logo to something else I think that the text you linked is a great direction. I tried making a yin-yang with leaves, but I can't really get the curves right and it scales poorly (which are both reasons for the carrot being so pixel-styled). Something like the fair trade logo was the aim if anyone better at design likes the idea.

I also made this:
![outlined](https://cloud.githubusercontent.com/assets/8918426/10558663/aef4bc48-74d8-11e5-9c3e-3b89694a3be7.png)

Which could definitely use some adjustments to shape and color and just about everything.
Based on the current logos only, it seems Umcaruje is our only hope
![og](https://cloud.githubusercontent.com/assets/8918426/10558664/b3b6f732-74d8-11e5-8132-7c1884e21407.png)

.

**Comment by Umcaruje** [comment] 2015-10-17 20:12
>we can close this request out unless there is a specific reason to update it.

Well, if the OP makes a well enough replacement for the current gui, why not. I wouldn't close this just yet.

**Comment by IvanMaldonado** [comment] 2015-10-18 00:30
Hi, I'm working on this skin because I think it's time to make plugins look a little bit more "of these days" (Please don't take me bad, the plugins look really good but the design type is a bit outdated). After seeing #2293 I thought it could be a good idea to re-design some plugins (not all) many people like when software looks different after a release (we're not changing functionality).

![](https://lmms.io/img/screenshots/ss_05_plugins.png)

To me, Zyn, OpulenZ and Organic are the most "old looking" plugins but this is just a personal thought.

@tresf I don't have any specific reason to update it, I just think it could look "newer".

@Spekular Thanks for your support :+1: 

@Umcaruje If you're interested on this, please tell me what else can I do, I'm not a designer but I try my best.

This is my idea, it doesn't have to be this way and I don't have to be the designer. If anyone has a better option, it would be awesome.

**Comment by tresf** [comment] 2015-10-18 04:18
> I think it's time to make plugins look a little bit more "of these days" 

So you're switching to pixel art?

> After seeing #2293 I thought it could be a good idea to re-design some plugins

Contributions are welcome, but redesigning is more than just re-skinning, so if you need to move knobs, etc, you'll find yourself editing some code too.

> To me, Zyn, OpulenZ and Organic are the most "old looking" 

I agree that OpulenZ could probably benefit from a facelift.  Zyn is mostly a waste of time since the actual plugin control are in a separate window, but knock yourself out.  In the case of Zyn, you may want to check out the single-window mockup that @budislav has created (disclaimer, he IS a designer).

![image](https://cloud.githubusercontent.com/assets/6345473/10562527/bc7cb046-752d-11e5-94ca-176875f7a311.png)

**Comment by IvanMaldonado** [comment] 2015-10-18 04:47
@tresf I didn't mean to change anything to Pixel art, as I said I don't have to be the one to make the changes. This was just an opinion. 

I don't plan to change anything about the plugins. 

I know about this awesome design Budislav made, I was just talking about the plugin port (sorry I don't know how to call it). 

Take the organic example here, I didn't change any knob position, im just talking about the skin.

**Comment by Spekular** [comment] 2015-10-18 10:35
@tresf I get the feeling the pixel look is not your cup of tea. And since I can't help but procrastinate, here's yet another logo...
![cube carrot small](https://cloud.githubusercontent.com/assets/8918426/10563669/6d1e4b26-7592-11e5-8a66-b554aad33dba.png)
W/ proposed ui:
![cube in grid](https://cloud.githubusercontent.com/assets/8918426/10563671/860e3ed4-7592-11e5-9147-ee5c854d3ef7.png)
Current vs pixel vs sharp in browser:
![in lmms](https://cloud.githubusercontent.com/assets/8918426/10563677/9a86429e-7592-11e5-8cd2-1d1c3c89f3a2.png)

**Comment by budislav** [comment] 2015-10-18 22:25
In case that anyone has not noticed, I already redesigned all instruments and effects in LMMS. All instruments and effect in LMMS should have the same look (GUI kit) because that is all the part of one software. http://budislavtvp.deviantart.com/art/LMMS-UI-UX-Design-Concept-Single-Window-523696539

![inst_effx](https://cloud.githubusercontent.com/assets/3619927/10567033/a35895ba-75f7-11e5-83c5-10f2d1ac6523.png)

**Comment by IvanMaldonado** [comment] 2015-10-18 22:40
^^^^^^^^^^^^^^^^^^^
I Support this, but I imagine a lot of things are hard-coded such as the windows sizes and knob positions. I would love to help here but I have little knowledge about programming and I imagine everybody is busy fixing bugs. 

What I'm saying here is that it would be good to have a new look for some plugins in the meantime, until budislavTVP effort gets some development. 

And please don't take this as if I'd want lmms plugins to look as I say, choose other artworks if available, I'm just telling my mind and I try to contribute the best way I can. I appreciate everybodys work on this awesome piece of Software.

**Comment by musikBear** [comment] 2015-10-19 14:40
@budislav when you say 
> I already redesigned all instruments and effects in LMMS. 

you mean you have *made images* of a future **unbelievable nice** UI 
You have **not** made an **actual qt** implementation that allow lmms to look like this in run-time -right?
I cant express how much i like your design budislav, so i will just place a like :+1:

**Comment by tresf** [comment] 2015-10-19 14:47
> You have not made an actual qt implementation that allow lmms to look like this in run-time -right?

Of course he hasn't.  He's not coding, he'd designing and his statements are correct.  This is all being tracked in #1911 and the status hasn't changed.

**Comment by budislav** [comment] 2015-10-21 02:40
Appreciate @musikBear. 
Tresf explained you, I am only designer.

**Comment by RebeccaDeField** [comment] 2016-10-27 01:22
@IvanMaldonado Are you still planning on working on this redesign? You could probably create something pretty easily using the source files for the new theme and following plugin design guidelines we are using here #2831. I know people here like to make these types of plugins with their own unique design, but this could give you a good starting point :+1:

**Comment by IvanMaldonado** [comment] 2016-10-27 02:18
@RebeccaDeField I started this topic because I felt this and other plugins could be redesigned to have a better look, so to support my idea, I made this skin so others could see or think on new ideas for the plugins designs. Since I have been told a lot of times here that design is not an easy matter to change and that a lot of work has to be done in order to get something accepted, I decided to stop making designs for the hub and started to make designs for myself. I am currently waiting for the 1.2 to release them.

I can work on this particular case using the design protocol you have created, give me sometime and I will post it here :+1: .

**Comment by RebeccaDeField** [comment] 2016-10-27 03:48
@IvanMaldonado I think it's a good idea to create the designs the way you want them to look, then release it for those that want to use it, how they want to use it. That has worked the best for me as well :)

You know I've always been a huge supporter of all of the themers here, so feel free to keep me up to date with what you're working on in the background.

> Give me sometime and I will post it here

I really appreciate your contribution :)

**Comment by tresf** [comment] 2019-03-06 16:41
Closing as duplicate of #3534.

**Closed by tresf** 2019-03-06 16:41 UTC
Labels: gui
