### ISSUE TITLE
No MIDI drivers on Mac OS

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2737] opened 2016-04-25 14:52 UTC
I have no MIDI drivers available when running on an Apple Macintosh computer, so I can't use any MIDI hardware with LMMS.

Is that correct?

**Comment by tresf** [comment] 2016-04-25 19:03
>  I can't use any MIDI hardware with LMMS.

*  :no_entry: `1.1.x`

*  :white_check_mark: `1.2.x`

Duplicate of #1153.

**Closed by tresf** 2016-04-25 19:03 UTC
Labels: duplicate
