### ISSUE TITLE
Nektar Impact MIDI Support

### ISSUE THREAD

**Issue by JosueCom** [LMMS/lmms#5835] opened 2020-12-08 08:18 UTC
### Enhancement Summary
It would be nice if extra support for Nektar Impact keyboards could be added to lmms. These keyboards are becoming more popular as an entry level midi keyboard.

#### Justification
When using my new Nektar Impact 88+, outside of the keys, most of the extra buttons did not work with lmms. Increasing the volume did not affect lmms in any way, all pads produced the same sounds and couldn't be changed, etc. 

#### Mockup
Potentially an plugin could be added to handle communication between the keyboard extra buttons and lmms. I have no idea.

**Comment by Spekular** [comment] 2020-12-08 09:37
This isn't specific to any one MIDI controller, and controller mapping would fix this for all controllers. Closing as duplicate of #1472

See also: #5356

**Closed by Spekular** 2020-12-08 09:37 UTC
Labels: enhancement

**Comment by JosueCom** [comment] 2020-12-08 20:41
How can one map the controller?

**Comment by qnebra** [comment] 2020-12-09 12:09
This is much more complex than simple scripts, as many lmms functions aren't exposed to midi.
