### ISSUE TITLE
Piano roll pitch bend on duplicated notes applies pitch bend to original notes and vice verse

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6138] opened 2021-08-19 10:09 UTC
### Bug Summary
Placing notes on piano roll and duplicating them (using Shift-drag) and then bending pitch of the duplicate bends pitch of original too, and vice versa.

#### Steps to reproduce
1. Open piano roll and place notes
2. Duplicate notes **with shift-drag** (Ctrl-C and Ctrl-V do not replicate this issue)
3. Switch to pitch bend mode and edit pitch automation of any note

#### Expected behavior
Only the note clicked on should change automation.

#### Actual behavior
The other copy of the note also shows pitch edited.

#### Screenshot
(Video)

https://user-images.githubusercontent.com/76674645/130050814-7e5f359c-fbc2-44b5-867e-f5906e1f1ed8.mp4

#### Affected LMMS versions

1.2.0, 1.3 alpha

**Comment by cyber-bridge** [comment] 2021-08-19 13:35
Duplicate of https://github.com/LMMS/lmms/issues/5940

**Comment by zonkmachine** [comment] 2021-08-19 13:46
Closing as duplicate of #5940

**Closed** 2021-08-19 13:46 UTC
Labels: duplicate
