### ISSUE TITLE
basseditor adding sounds crashing

### ISSUE THREAD

**Issue by tecan** [LMMS/lmms#2040] opened 2015-05-10 15:52 UTC
during playback of the beatline-basseditor adding sounds to it causes crashing.

**Comment by michaelgregorius** [comment] 2015-05-10 16:43
Don't know if it is related to the original problem reported by @tecan but here are some steps that can be used to make the GUI freeze with regards to the B+B Editor (using 2f969c1e1c7194538c9e047b039f39d0b8e304d7):

1. Start LMMS.
2. Click the "Play" button in the Beats+Bassline Editor.
3. Remove the Kicker.
4. Pull some samples into the editor, e.g. "My Samples/drums/bassdrum04.ogg". If I do this twice the application freezes.

Removing the track seems to be the crucial step to make it hang later on. If you don't remove it you can add as many samples / tracks as you want.

The problem seems to be related to the locking of the Track object. I guess that it is already locked and  that we are seeing a deadlock here. Pausing the application in the debugger gives to following stack:

```
0	syscall			0x7ffff43b9f89	
1	??			0x7ffff680fbf2	
2	QMutex::lockInternal()			0x7ffff680be95	
3	Track::lock	Track.h	529	0x54c826	
4	Pattern::addNote	Pattern.cpp	191	0x605d25	
5	Pattern::ensureBeatNotes	Pattern.cpp	569	0x60759e	
6	Pattern::init	Pattern.cpp	124	0x6059dc	
7	Pattern::Pattern	Pattern.cpp	68	0x6056c0	
8	InstrumentTrack::createTCO	InstrumentTrack.cpp	689	0x5fdf6f	
9	BBTrackContainer::createTCOsForBB	BBTrackContainer.cpp	255	0x4df1aa	
10	BBTrackContainer::updateAfterTrackAdd	BBTrackContainer.cpp	92	0x4deb41	
11	Track::create	Track.cpp	1876	0x548c64	
12	TrackContainerView::dropEvent	TrackContainerView.cpp	386	0x5a283b	
13	BBTrackContainerView::dropEvent	BBEditor.cpp	252	0x5afd89	
14	QWidget::event(QEvent *)			0x7ffff70e6c68	
15	QApplicationPrivate::notify_helper(QObject *, QEvent *)			0x7ffff70939fc	
16	QApplication::notify(QObject *, QEvent *)			0x7ffff709bc6c	
17	QCoreApplication::notifyInternal(QObject *, QEvent *)			0x7ffff691bd7d	
18	??			0x7ffff711e7e0	
19	??			0x7ffff711eb75	
...	<Mehr>				
```

By the way having code like this is highly unsafe (as seen in `Pattern::addNote` and likely many other places):
```cpp
instrumentTrack()->lock();
// Do something potentially critical here, e.g. something that throws an exception
instrumentTrack()->unlock();
```

**Comment by Umcaruje** [comment] 2015-07-05 21:49
Reproduced with @michaelgregorius's steps.

**Comment by tresf** [comment] 2015-09-28 14:38
Duplicate of #2378

**Closed by tresf** 2015-09-28 14:38 UTC
Labels: bug, gui
