### ISSUE TITLE
VST window error in Qt5 only (works fine in Qt4) under Fedora 26  

### ISSUE THREAD

**Issue by GuessWhatBBQ** [LMMS/lmms#3717] opened 2017-07-22 09:50 UTC
![screenshot from 2017-07-22 15-42-30](https://user-images.githubusercontent.com/16496608/28490157-be881f98-6ef4-11e7-94b4-72f61c262277.png)
All features are usable but there is no way to bring back the VST's GUI once it is closed from the dash panel like this 
![screenshot from 2017-07-22 15-47-03](https://user-images.githubusercontent.com/16496608/28490172-0962088a-6ef5-11e7-8b23-d6ca9d3ed575.png)
Clicking on the "Show/hide GUI" button afterwards simply yields a blank menu
![screenshot from 2017-07-22 15-48-52](https://user-images.githubusercontent.com/16496608/28490183-4868e56c-6ef5-11e7-824b-5491434db5f2.png)
I've found similar results for all Synths

**Comment by PhysSong** [comment] 2017-07-22 10:19
I think it's a duplicate of #2855.

**Closed** 2017-07-22 15:14 UTC
Labels: duplicate
