### ISSUE TITLE
Zyn crashes when opening GUI while a value is connected to a LFO Controller

### ISSUE THREAD

**Issue by EtornaZ** [LMMS/lmms#4552] opened 2018-08-23 17:30 UTC
Whenever I open the Zyn GUI while I have a Zyn value (Frequency, FM Gain, Resonance, etc) connected to a LFO Controller, LMMS freezes up and then crashes on me. I'm using LMMS 1.2.0 rc6 on a Windows 10 Laptop.

**Comment by DomClark** [comment] 2018-08-23 17:37
Reproduced. Seems to be the same fundamental problem as #4543 - an event loop is run waiting for a reply message from the remote Zyn process, during which a parameter update is sent, processed on the main thread and attempts to lock the communication mutex a second time.

**Comment by DomClark** [comment] 2018-11-25 19:59
Fixed in #4692.

**Closed by DomClark** 2018-11-25 19:59 UTC
Labels: bug
