### ISSUE TITLE
Opening Issue

### ISSUE THREAD

**Issue by The-64-Bit-Kid** [LMMS/lmms#3127] opened 2016-11-18 19:33 UTC
When ever i open the program beta or not it crashes and gives this error...
![untitled](https://cloud.githubusercontent.com/assets/23561305/20443698/d0a5aa60-adc5-11e6-82bd-10d176382d2a.png)

**Comment by DeRobyJ** [comment] 2016-11-20 12:31
Hi, what Windows version are you using?

**Comment by The-64-Bit-Kid** [comment] 2016-12-01 17:50
im using windows 7 ultimate

**Comment by DeRobyJ** [comment] 2016-12-01 17:55
Can you run lmms 1.1.3 normally?

**Comment by DeRobyJ** [comment] 2016-12-01 17:56
Are you using the right version?
if your OS is 32bit, you should use the 32bit version of the program

**Comment by The-64-Bit-Kid** [comment] 2016-12-01 18:49
im using a 64 bit os with 64 bit software

**Comment by The-64-Bit-Kid** [comment] 2016-12-01 18:50
and no because this is the stable version

**Comment by DeRobyJ** [comment] 2016-12-01 18:55
It works fine to me on windows 7, so I don't see why it doesn't work in your computer...

**Comment by The-64-Bit-Kid** [comment] 2016-12-01 19:14
i dunno either

**Comment by tresf** [comment] 2016-12-01 19:21
> It works fine to me on windows 7, so I don't see why it doesn't work in your computer...

This is a known issue, documented in our release notes (scroll to bottom) and a duplicate of #1173, #512.

**Closed by tresf** 2016-12-01 19:21 UTC

**Comment by The-64-Bit-Kid** [comment] 2016-12-01 19:32
so how do i fix it which version should i download

**Comment by tresf** [comment] 2016-12-01 19:56
@The-64-Bit-Kid please do this, in this order (adapted from [here](https://github.com/LMMS/lmms/issues/512#issuecomment-38762674), [and here](http://lmms.io/forum/viewtopic.php?f=7&t=3365) [oh and here](https://lmms.io/forum/viewtopic.php?f=7&t=392), [oh yeah here](https://lmms.io/forum/viewtopic.php?f=7&t=286) but with some additional gotchas)

## Clean Install

 * Reboot your computer (ensures no instances of `lmms.exe` are already running)
 * Uninstall LMMS
 * Locate `C:\Program Files\LMMS\` if present, remove it (if paranoid, move it to your desktop).
 * If you have a `C:\Program Files (x86)\LMMS`, remove it (again, if paranoid, move it instead).
 * Locate `%APPDATA%\.lmmsrc.xml`, remove it (again, if paranoid, move it instead)
 * Reinstall LMMS
 
If LMMS launches, great.  If it doesn't, search for Qt conflicts:

## Qt Conflicts
 * Search your computer for any files named `Qt*.dll` (Windows + F, Qt*.dll, wait for it to finish).
   * Take special note of any DLLs that may be in your `PATH`, such as `C:\Windows`, `C:\Windows\System32`, etc.  You may need to delete them manually or uninstall the application associated with them.
   * Ignore those found in `%APPDATA% or `Program Files`, they're generally save.  Watch out for those installed in `C:\Windows` or `C:\Windows\System32`

## Sound Driver Conflicts
 * This is the most common cause of crashes on startup.
 * First, download the latest sound driver from your sound card (from PC manufacturer website, or directly from the sound card manufacturer.  Note, some HDMI sound devices use drivers from NVIDIA/AMD(ATI)/Intel.
 * If this doesn't help, force removal of the 3rd party driver and use the one provided by Microsoft.  This is how:
   1.  Open Device Manager
   2.  Expand Sound and Game controllers 
   3.  Locate your sound card, Right Click, Remove Device
   4.  Click the Checkbox that says "Remove driver software for this device"
   5.  Reboot
   6.  Windows should automatically search for a sound driver.  This will take a few minutes.
   7.  Windows should install a sound driver from Windows updates.  Once finished, reboot if needed.
   8.  If Windows could not located a sound driver, visit the manufacturer website and manually download a sound driver for your computer, install the sound driver manually, reboot if needed.
   9.  Try LMMS again. 
* If this doesn't help, try replacing the [`libportaudio-2.dll`  in your installation directory with a recompiled one](https://github.com/LMMS/lmms/issues/451#issuecomment-37773385).

If that doesn't work, then you're out of luck.
