### ISSUE TITLE
Searching is completely broken

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6979] opened 2023-11-12 00:16 UTC
### Bug Summary
Searching doesn't even work anymore. and when I somehow got it to actually work (idk how), it looked like this instead of doing hierarchy: 
![image](https://github.com/LMMS/lmms/assets/65266122/0246764b-1fff-4824-9c24-fbfcb54544d9)
I'm pretty sure this is caused by #6962
#### Steps to reproduce
Try and search, it doesn't update at all
#### Expected behavior
Search works
#### Actual behavior
Nope
#### Affected LMMS versions
gc77952173

**Comment by sakertooth** [comment] 2023-11-12 00:37
> Searching doesn't even work anymore

It does work. It just takes a while to do a search across your entire home directory before it can display it to you. Maybe an indicator can be added to let the user know that a search is in progress.

> and when I somehow got it to actually work (idk how), it looked like this instead of doing hierarchy:

I am in favor of this structure. You do not have to continuously click through the folders to see the files you want, but still have them shown in distinct paths.

**Comment by SalutanisOrkonus** [comment] 2023-11-12 01:00
Im not searching the home directory, im searching the samples folder, which
loaded searches instantly, and yes I waited, nothing happened. also that
structure sucks.

**Comment by Veratil** [comment] 2023-11-12 06:59
Closing this as duplicate of #6980

**Closed by Veratil** 2023-11-12 06:59 UTC
Labels: bug
