### ISSUE TITLE
Consecutive notes won't work with sustain

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#3757] opened 2017-08-07 17:39 UTC
Regression caused by #3710, reverting the commit removes the bug.

Steps to reproduce: 
1. Connect any instrument to a midi controller with a sustain pedal/button
1. Hold down the sustain pedal/button
1. Press any key more than one time
1. Only the first key press will register and the consecutive keys won't work or produce any sound until you release the sustain pedal.
 
If you revert the said commit, in case of `stable-1.2`: 
```
git revert d87a8b3da4976b669600972c4e731f8a4f6a6fb5
```
The behavior is as expected, they keys keep playing the same sound and layering over one another.

If my steps are unclear I can provide a video.

Tagging @serdnab as the author of the PR.

**Comment by PhysSong** [comment] 2017-08-08 07:54
Confirmed.

[Here](https://github.com/LMMS/lmms/blob/d87a8b3da4976b669600972c4e731f8a4f6a6fb5/src/tracks/InstrumentTrack.cpp#L277-L282) m_notes[event.key()] is not cleared if sustain pedal is pressed, so the [note-on condition](https://github.com/LMMS/lmms/blob/d87a8b3da4976b669600972c4e731f8a4f6a6fb5/src/tracks/InstrumentTrack.cpp#L250) is not satisfied.

**Comment by PhysSong** [comment] 2017-08-08 07:59
Possible solution:
* Remove if clause which guards `m_notes[event.key()] = NULL;`.
* Store sustained notes in other place.
* Read note handle list from the new place [here](https://github.com/LMMS/lmms/blob/d87a8b3da4976b669600972c4e731f8a4f6a6fb5/src/tracks/InstrumentTrack.cpp#L314).

**Comment by zonkmachine** [comment] 2017-08-08 11:10
> * Remove if clause which guards m_notes[event.key()] = NULL;.

This, tried it and it works. One drawback though. Today, if you strike a midi keyboard and then enable it via the instrument, 'Enable Midi Input' drop-down menu, you will have notes stuck on. You can 'unstick' these notes by hitting the same note again. When I remove the 'if' mentioned above the notes are stuck bad and I have no method to silence them. This is an issue already and should be fixed. Maybe running `InstrumentTrack::silenceAllNotes(` when connecting a keyboard?

**Comment by PhysSong** [comment] 2017-08-08 11:28
**All of** these three things should be done. If not, these issue will take a place.
I'll complete my solution tomorrow and open a PR if needed.

**Comment by zonkmachine** [comment] 2017-08-08 11:37
OK. Slow day over here.. 8)

**Comment by PhysSong** [comment] 2017-08-09 08:10
>Maybe running `InstrumentTrack::silenceAllNotes()` when connecting a keyboard?

I think it should be also called when disconnecting a keyboard. I think `m_sustainPedalPressed` should be set to false too,

Another issue(not caused by #3710): if I hold down the sustain pedal, press notes and disconnect the keyboard, the only method to unstick such notes is pressing the stop button. Moreover, there's no way to turn off MIDI sustain unless I connect the keyboard again.

**Comment by serdnab** [comment] 2017-08-19 02:56
@PhysSong are you on this?
If not I will take a look at it.

**Comment by PhysSong** [comment] 2017-08-19 03:33
>If not I will take a look at it.

I need to investigate some related behaviors, so I'm not on this now.

**Comment by PhysSong** [comment] 2017-08-26 04:04
Fixed via #3774.

**Closed by PhysSong** 2017-08-26 04:04 UTC
Labels: bug
