### ISSUE TITLE
Marking a note and marking its octaves crashes LMMS

### ISSUE THREAD

**Issue by Jernemies** [LMMS/lmms#4631] opened 2018-09-28 16:40 UTC
Title. Mark any note, then right click on it and mark its octave semitones. LMMS crashes without fail so far.
LMMS 1.2.0rc7 64-bit on Win7 64-bit.

**Comment by DomClark** [comment] 2018-09-28 16:42
Duplicate of #4188.

**Closed by DomClark** 2018-09-28 16:42 UTC
