### ISSUE TITLE
zita-reverb breaks projects

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#3780] opened 2017-08-27 16:21 UTC
I have stopped using zita-reverb plugin in LMMS, becasue it made my projects go mute on the Master bus. The only way I found to get the sound back is to remove all zita-reverb instances, save and reload.

I guess it's something with NaNs or whatever.

**Comment by zonkmachine** [comment] 2017-08-27 16:27
Can you upload one of those buggy projects?

**Comment by unfa** [comment] 2017-08-27 16:38
Here's a project that exhibited such behavior:

[unfa-FightingMyself-10.zip](https://github.com/LMMS/lmms/files/1254549/unfa-FightingMyself-10.zip)

I loaded it again after a while and it's fine, but sometimes it's impossible to carry on with such projects.

**Comment by unfa** [comment] 2017-08-27 16:43
Here's a project that exhibited such behavior:

[unfa-FightingMyself-10.zip](https://github.com/LMMS/lmms/files/1254549/unfa-FightingMyself-10.zip)
The faulty zita-reverb is placed on FX-channel 24 (Square bass).

I loaded it again after a while and it's fine, but sometimes it's impossible to carry on with such projects.

**Comment by zonkmachine** [comment] 2017-08-27 19:12
What versions of LMMS do you see this on? We've taken care of 

> I loaded it again after a while and it's fine, but sometimes it's impossible to carry on with such projects.

Yeah, I know what you mean. I'm testing this with our new floating point debug compile option and the project is a bit too big to test zita-reverb specifically as I get other floating point errors in there. If you can replicate the error in a minimal project that would be super. Another problem is that reverb in general tend to aggravate a NaN triggered prior to it so the problem may not be in zita at all. Try the ReverbSC with a long reverb and see if you can trigger this still. Also try cutting out the effects (compressor/narrower) on the Square bass track and see if that makes any difference.

**Comment by unfa** [comment] 2017-09-03 14:36
I never had problems like this with any other reverb plugin in LMMS, only with zita-reverb.
The GxZita-Rev1 Lv2 plugin that I use in Ardour didn't seem to break stuff also.
The standalone Zita-rev1 didn't ever wreck havoc on my either.

Catching this in a small project might be hard, because it's rather random/

**Comment by zonkmachine** [comment] 2017-12-14 11:06
I can confirm the issue but I didn't manage to find the cause. Since other reverbs aren't triggering in the same way after a possible glitch I think it's more likely to be a bug in Zita.

> The GxZita-Rev1 Lv2 plugin that I use in Ardour didn't seem to break stuff also.

But they, most likely, filter out inf/nan glitches so the issue may come in the form of a minute 'tick' sound at project load or something similar.

**Comment by zonkmachine** [comment] 2020-05-10 01:24
I'm calling this one closed in https://github.com/LMMS/lmms/pull/3706

**Closed by zonkmachine** 2020-05-10 01:24 UTC
Labels: bug, upstream
