### ISSUE TITLE
Zyn GUI crashes LMMS in Master

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2269] opened 2015-08-16 00:17 UTC
Every time I press "Show GUI" button to tweak my ZynAddSubFX patch LMMS hangs.

Using latest Git Master.

GDB output: http://pastebin.com/iFcuMWVx

**Comment by Wallacoloo** [comment] 2015-08-16 05:00
This is a known issue due to naming conflicts between lmms' engine class
and ZASFx's engine class. It will be fixed once curlymorphic's zyn 2.5
branch is ready to merge, or you can try out the "temporary fix for
ZynAddSubFx Naming Conflicts" pull request.

**Comment by unfa** [comment] 2015-08-16 20:14
Good to know it's about to be fixed.

I think I got this in the git stable-1.1 too: http://pastebin.com/ZRMmZ4Q7

**Comment by unfa** [comment] 2015-08-17 16:19
Crap. Now this issue has somehow infected my LMMS stable installation. I've installed the Master buid in a prefix to keep them separated, but looks like they arent't completely independent.

I'm trying to downgrade LMMS to get a working build.

**Comment by tresf** [comment] 2015-08-22 00:21
@Wallacoloo can we rename `Engine.cpp` to `Hub.cpp` or `Fulcrum.cpp` or `Focal.cpp` and put this issue to rest?

-Tres

**Comment by Wallacoloo** [comment] 2015-08-22 02:44
@tresf FWIW, my OSC PR happens to fix this issue as well since it removes
the Engine's inheritance from QObject (uses OSC instead of signals). If you
don't want to wait for that PR to be ready though, I have no objection to a
rename. "Core" or "Master" may be ok names.

**Comment by tresf** [comment] 2015-08-22 03:06
I thought of `Core` and I thought it would be confused with `/src/core`, which is hypothetically gui-less.  `Master` may confuse people as well due to it's nature in a code branch as well as it's name in an EQ mixer.

My main concern is that I don't envision 2.5 happening any time soon, so if OSC is close, that is the best of all worlds, IMO. :)

**Comment by Wallacoloo** [comment] 2015-08-22 03:10
I had the same thoughts. I'll try to tidy up the OSC PR this weekend.
Though I am currently without a working monitor for my computer & I don't
know yet if it's fixable, so no guarantees.

**Comment by musikBear** [comment] 2015-08-22 10:13
my devaluated and bend 10cent : an obvious and secure name would be *LMMSengine*.
that retains the old name, and hence let people know what it used to be. 
An added comment in header will further help that process

**Comment by unfa** [comment] 2015-08-29 11:44
I'd be really happy if this was fixed in 30 days, becasue I'm gonna be doing a public presentation with LMMS live, I wouldn't like to show the audience how LLMS crashes ;)

**Comment by tresf** [comment] 2015-08-29 14:34
@unfa our best bet may be to get @Wallacoloo's OSC stuff in to fix the namespace clash (#2252)

**Comment by Wallacoloo** [comment] 2015-08-29 17:11
All it needs is some review and/or testing, I believe. If you want it to
happen, then maybe you can aid in that process @unfa.

@tresf did you receive the email I sent to the address listed on your
github a few days ago? (It was relevant to this discussion)

**Comment by tresf** [comment] 2015-08-29 17:16
> @tresf did you receive the email I sent to the address listed on your
github a few days ago? (It was relevant to this discussion)

tres.finocchiaro@gmail.com (yes, I just did that :+1: )

**Comment by Wallacoloo** [comment] 2015-08-29 17:49
@tresf hmm. That's what I sent it to last time. Just sent it again - check your spam, or whitelist `wallacolooo @ gmail.com`

**Comment by tresf** [comment] 2015-08-29 18:09
No record of the original, but replied.

**Comment by unfa** [comment] 2015-08-30 15:24
@Wallacoloo - I'll e-mail you about testing.

**Comment by Wallacoloo** [comment] 2015-08-30 19:30
Hey @unfa. I wrote a wiki page about testing pull requests. Figured I would link it here for visibility rather than reply directly to your email: https://github.com/LMMS/lmms/wiki/Reviewing-Pull-Requests

"Step 3" (regression testing) isn't straightforward to do with this PR since it touches a lot of code. For that step, just dink around in LMMS using it as you normally do until you feel comfortable that it's no less "stable" than before (hopefully).

**Comment by unfa** [comment] 2015-09-03 16:22
I'm going for it. Thank you, Wallacoloo!

**Comment by tresf** [comment] 2015-11-02 13:59
Adding to the `critical` and `1.2` lists.  This needs fixing prior to the release of 1.2.

**Comment by shimpe** [comment] 2015-12-23 13:44
Forgive me for asking, but is there any progress with this issue? 

Please consider implementing a pragmatic solution (namespace one of the engine classes) if the real solution is too risky or difficult, at least until a "good" solution is ready to be committed.
This bug is quite a showstopper.

**Comment by tresf** [comment] 2015-12-23 13:56
@shimpe thanks for inquiring.

Yes, there has been progress, but there has been no final decision made.

The ideal solution was to use OSC messaging and hit two birds with one stone (so to speak) but @Wallacoloo has since stated about a month ago that he's ["... not cut out for that role"](https://github.com/LMMS/lmms/pull/2252#issuecomment-159802147).

In lieu of Colin's post, we've no choice but to adopt the `LmmsCore` namespace fix (#2118), which can be merged after a rebase.

**Comment by shimpe** [comment] 2015-12-23 15:47
If you like that, there's also the patch I just made where Engine is renamed to LmmsEngine and which solves the issue for me. It's the only change made so it may be easier to check and it merges cleanly with current master. Of course, no obligations :) Until some solution is adopted, it scratches my itch.

**Comment by shimpe** [comment] 2015-12-23 15:48
Oh wait... I seem to have messed up something :( Don't merge yet.

**Comment by shimpe** [comment] 2015-12-23 16:08
Same explanation, different patch (and this time it really works! :) )

**Comment by tresf** [comment] 2015-12-23 16:31
Albeit obscure, I much prefer the 6-file change over the 136-file change.  I'll let others chime in though.

**Comment by shimpe** [comment] 2015-12-23 17:06
I totally understand: it's a better way to avoid conflicts when merging from other branches.

On the other hand I saw some comments from people not wanting to introduce the "typedef construct" so I thought to provide an alternative (luckily for me, qtcreator did 95% of the renaming automagically and the effort on my side was limited to a few files and then building and testing a bit.

In any case thanks to the brilliant analysis of the problem by other people I can now use lmms again. Thanks to all involved.

**Comment by karmux** [comment] 2015-12-28 21:21
I tried out both pull requests but couldn't open ZynAddSubFx GUI with none of them. 

#2494 - Here I still get random crashes when listening to Zyn samples in library. Not able to open two demo songs in a row without a crash. LMMS crashes when trying to open Zyn GUI.

#2118 - Couldn't crash LMMS when listening Zyn samples from library. I could open many demo songs one after another without crash which means it fixes also #2439. For some strange reason it seems that this PR opens projects times faster than #2494. Even projects that don't have any Zyn instrument load several times faster.

In addition to all this awesomeness, this PR has also a killer bug. When I try to open Zyn GUI not only LMMS crashes but my whole KDE desktop and after a second I see login screen.

**Comment by tresf** [comment] 2015-12-30 07:42
Closed via https://github.com/LMMS/lmms/pull/2118 (c5199213068cdce59ddc2cffab07f5bcdecfc325)

**Closed by tresf** 2015-12-30 07:42 UTC
Labels: bug, critical

**Comment by shimpe** [comment] 2015-12-30 07:58
Yay! I'm really happy to see this issue being closed. Thanks.

**Comment by Animtim** [comment] 2016-04-05 09:41
Hi,
I'm sorry to say I still have a bug with Zyn' show gui button making lmms freeze/crash.
I built 1.2.0 RC1 on mageia cauldron and still have this console log when clicking this button:
/usr/lib64/lmms/RemoteZynAddSubFx: error while loading shared libraries: libZynAddSubFxCore.so: cannot open shared object file: No such file or directory

Any idea?

**Comment by Animtim** [comment] 2016-04-05 10:33
Sorry actually it happens only with a system-installed version from the rpm I made, and not with a local not-installed build. So it's probably just a path issue.

**Comment by scottwolff** [comment] 2017-04-05 23:07
On my system with these specs (post 1607 cumulative update):

-----------------------------------------------------------------------------
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-V22RDSM
System Manufacturer	MSI
System Model	MS-7693
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	AMD FX(tm)-6300 Six-Core Processor, 3500 Mhz, 3 Core(s), 6 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. V10.3, 3/28/2013
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	MSI
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume4
Locale	United States
Hardware Abstraction Layer	Version = "10.0.14393.206"
User Name	DESKTOP-V22RDSM\grey2
Time Zone	Central Daylight Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.95 GB
Available Physical Memory	4.46 GB
Total Virtual Memory	16.4 GB
Available Virtual Memory	11.3 GB
Page File Space	8.50 GB
Page File	C:\pagefile.sys
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes
-----------------------------------------------------------------------------------------

I caused my system to lock up while trying to Show Gui.

I was able to get it running by running: As Administrator. So it is a workaround for now in Windows.

**Comment by tresf** [comment] 2017-04-05 23:54
@scottwolff your problem is unrelated to the original problem (his was Linux related).

Since you are running Microsoft Windows, your problem may be a permissions issue with the `.zynaddsubfxXML.cfg` file or the directory it is contained within.

Please look in either `%userprofile%\lmms\.zynaddsubfxXML.cfg` or in your LMMS_HOME directory for this file and ensure your profile has sufficient permissions to read and write to this location.

**Comment by scottwolff** [comment] 2017-04-06 00:05
What would be the appropriate resource to put this information in, for those that were having the same problem as I?

**Comment by tresf** [comment] 2017-04-06 00:10
> What would be the appropriate resource to put this information in, for those that were having the same problem as I?

Well, running as administrator is not a recommended solution, so I suppose that depends on whether or not the above steps help.

**Comment by scottwolff** [comment] 2017-04-06 00:57
![lmms permissions](https://cloud.githubusercontent.com/assets/19482044/24732885/9628b8a6-1a39-11e7-9ebe-6260bfe7bdec.png)

I don't see anything wrong with the permissions. Even after setting the same for LMMS in the program files it still hangs. I was already in the administrators group for my pc.

I deleted the .zynaddsubfxXML.cfg file with the same results.

**Comment by tresf** [comment] 2017-04-06 01:17
@scottwolff thanks for trying.  Probably best to track this issue in a [new topic](https://github.com/LMMS/lmms/issues/new) since it's not a quick fix.  Please provide as many details as you can including what you've tried, what's work and what hasn't.

The next thing I would recommend is performing a disk check as some new solid state drives (SSDs) in Windows can get back security descriptors and cause all sorts of crashes.
