### ISSUE TITLE
Error loading VST plugin via VeSTige (Linux)

### ISSUE THREAD

**Issue by senviro-double3** [LMMS/lmms#6808] opened 2023-08-14 03:36 UTC
### Bug Summary
Good morning/afternoon/evening. I had a problem loading a .dll VST plugin in VeSTige.
I just started learning lmms and there is such an error. 
The installation was carried out as here https://lmms.io/download#linux, Wine was already installed.

#### Steps to reproduce
I tried to download two versions of the plugin 64bit and 32bit, but none of them worked.
If break down the whole process into points:
1) Run in terminal `./lmms-1.3.0-alpha.1.102+g89fc6c9-linux-x86_64.AppImage`
2) Select VeSTige in instrument plugins and add it to Song-Editor
3) Try to load plugin .dll

#### Expected behavior
Plugin loading and opening the plugin window.

#### Actual behavior
LMMS hangs for a few seconds and no change on the screen.

Running with Wine-8.13 didn't solve the problem either.
```
$ wine lmms-1.3.0-alpha.1.102+g89fc6c9-linux-x86_64.AppImage
...
wine: failed to open "/tmp/.mount_Z:\\homDiNx5D/usr/lib/lmms/32/RemoteVstPlugin32.exe.so": c0000135
Remote plugin exit code:  53
remote plugin died! invalidating now.
Remote plugin did not connect.
```

#### Screenshot
![изображение](https://github.com/LMMS/lmms/assets/142191986/c1220910-1a34-432f-8f64-3c335627aa47)

#### Affected LMMS versions
```
lmms-1.2.2-linux-x86_64
lmms-1.3.0-alpha.1.102+g89fc6c9-linux-x86_64
lmms-1.3.0-alpha.1.330+g4ff95072e-linux-x86_64
```

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
$ ./lmms-1.3.0-alpha.1.102+g89fc6c9-linux-x86_64.AppImage
Carla does not appear to be installed. That's OK, please ignore any related library errors.
Jack appears to be installed on this system, so we'll use it.
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
Notice: could not set realtime priority.
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
Lv2 plugin SUMMARY: 0 of 0 loaded in 0 msecs.
Cannot load library /tmp/.mount_lmms-13fJCay/usr/lib/lmms/libcarlapatchbay.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /tmp/.mount_lmms-13fJCay/usr/lib/lmms/libcarlabase.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /tmp/.mount_lmms-13fJCay/usr/lib/lmms/libcarlarack.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine: failed to start L"Z:\\tmp\\.mount_lmms-13fJCay\\usr\\lib\\lmms\\32\\RemoteVstPlugin32.exe.so"
The application cannot be started or there are no applications associated with the given document type.
ShellExecuteEx call failed: File not found.

Remote plugin exit code: 1
remote plugin died! invalidating now.
Remote plugin did not connect.
</pre>
</details>

**Comment by senviro-double3** [comment] 2023-08-16 05:30
I solved the problem by installing the Windows version of LMMS and running it through
`$ wine lmms.exe`
The UI of the VST shrinks a bit, but you can work.

**Comment by senviro-double3** [comment] 2023-08-17 06:44
So the Linux version still doesn't work...
Could there be a problem with Linux VST in WineHQ?
Maybe it's in the version of Wine-8.13?

**Comment by senviro-double3** [comment] 2023-08-17 13:56
<h2>I publish the instructions, my temporary way to solve the problem.</h2>
My method turned out to be quite a crutch, but everything works fine.

My case:
```
WineHQ version: 8.13
OS: Ubuntu 23.04
```

The points:
1) Install Windows version of LMMS from website.
2) Run installing via terminal `wine /path/to/downloaded/lmms_<...>.exe`
3) After installation run lmms.exe `wine ~/.wine/drive_c/Program\ Files/LMMS/lmms.exe`
4) Open settings and set `VST plugin embedding` to `No embedding`
![settings](https://github.com/LMMS/lmms/assets/142191986/a02faef9-0158-4503-bb13-2ed22165c1d1)

5) That's all! Now LMMS with WineHQ works on Linux and no problems with VST.

**Comment by kamkamkamkamkamkamkamkam** [comment] 2023-08-27 19:56
I also have this problem with the AppImage versions of LMMS now, though I'm not entirely sure if it's a problem with the builds or not.

**Comment by Lazerbeak12345** [comment] 2023-09-02 23:42
Might be related to #6408

**Comment by spiderman-idog** [comment] 2023-09-28 19:21
Updated my version of wine and can confirm im having the same issue, my previous version 6.0 (the one that comes with Ubuntu's `apt`) was running most of the stuff fine. But the workaround of running the windows version of lmms is working and can run my plugins again there

**Comment by kamkamkamkamkamkamkamkam** [comment] 2023-10-01 16:45
@spiderman-idog @senviro-double3 using a locally compiled version of LMMS also fixes the issue

**Comment by spiderman-idog** [comment] 2023-10-02 18:10
> @spiderman-idog @senviro-double3 using a locally compiled version of LMMS also fixes the issue

Sorry, I should have mentioned my lmms version, in my initial message I was running a version compiled some weeks ago.
Also, I should have been more specific about my problem, a good chunk of plugins still work as intended, only some plugins stopped working after i upgraded wine (eg: SAM-SPL 64, a sampler, and Cymatics Origin, an effects plugin, both seem to not open, or not show gui and expose the settings).
Ok, so, i compiled again lmms and i still face the same issue. A downgraded wine (Ubuntu's `apt` version), with wine64 also installed works as intended in the main branch.
So, I decided to test one plugin (the SAM-SPL 64 sampler) in different branches of the most recent wine version to see the different results (using the 'embed with the qt api' setting).
- I installed winehq-stable and tried again on the recent build, SAM-SPL refused to load, not even a blank gui, one thing that happened is that wine complained about this `rundll32.exe` thing on the first run.
- Next I tried winehq-devel, it complained again about this `runddl32.exe`, SAM-SPL 64 did open a blank gui once, but did not expose any settings, i think that was just luck because next attempts it did not load again
- Finally, I tried winehq-staging, i dont remember if the `rundll32.exe` message appeared but it consistently opens a blank window instead of refusing to load now, it doesn't expose any settings, but the terminal keeps spitting qt debug messages, [here's how it looks](https://pastebin.com/qf4YSpts).

**Comment by spiderman-idog** [comment] 2023-10-02 18:21
Also, just wanted to add that the official appimage (1.22, 1.30) builds didnt load any vsts at all for me, for this reason i had this version that i compiled some weeks ago

**Comment by kamkamkamkamkamkamkamkam** [comment] 2023-10-10 00:58
It has nothing to do with the Wine version used, this is the terminal output I get when loading a VST in an AppImage build of LMMS
```
wine: failed to start L"Z:\\tmp\\.mount_LOMM-pXtAF78\\usr\\lib\\lmms\\32\\RemoteVstPlugin32.exe.so"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

Remote plugin exit code:  1
remote plugin died! invalidating now.
Remote plugin did not connect.
```
This does not happen in compiled builds of LMMS.

**Comment by kamkamkamkamkamkamkamkam** [comment] 2023-10-10 00:59
> Might be related to #6408

oh, they were right lol

**Comment by kamkamkamkamkamkamkamkam** [comment] 2023-10-10 01:28
I just found another workaround. I noticed that Linux native VSTs are not affected by this bug, which means it's possible to bridge Windows VSTs with something like yabridge in order to use them in LMMS (and any other Linux native DAW).
![image](https://github.com/LMMS/lmms/assets/65249472/a7bd055d-ea46-4aa3-bb07-7396fcb9f1fc)

**Comment by mirk0dex** [comment] 2023-10-10 05:31
What's weird to me is how this issue seemingly came out of nowhere.

Just the day before I had it, everything worked fine. So it must have been a Wine update or something.

**Comment by kamkamkamkamkamkamkamkam** [comment] 2023-10-10 06:22
> What's weird to me is how this issue seemingly came out of nowhere. Just the day before I had it, everything worked fine. So it must have been a Wine update or something.

This has been happening to me for months now across many Wine versions, so it couldn't have been any recent update.

**Comment by mirk0dex** [comment] 2023-10-10 07:52
Yeah, me too. It's been months.

**Comment by LeontKing2** [comment] 2024-04-11 12:14
solution for this is to use wine64 instead of normal wine.

**Comment by LeontKing2** [comment] 2024-04-11 14:07
> I just found another workaround. I noticed that Linux native VSTs are not affected by this bug, which means it's possible to bridge Windows VSTs with something like yabridge in order to use them in LMMS (and any other Linux native DAW). ![image](https://private-user-images.githubusercontent.com/65249472/273749432-a7bd055d-ea46-4aa3-bb07-7396fcb9f1fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDQxNjIsIm5iZiI6MTcxMjg0Mzg2MiwicGF0aCI6Ii82NTI0OTQ3Mi8yNzM3NDk0MzItYTdiZDA1NWQtZWE0Ni00YWEzLWJiMDctNzM5NmZjYjlmMWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEzNTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiODVmODk4OGIwNjQwYmUyNDgyODg5MjkwZjAzNWZiOGNiZGY1NzExYzQzNWJmMGNlMGQzZThiOGQ5ZDA1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6j-e9D4fmS09h1HM2bufi6vMAshX69X06TO9ask6RXM)

hey there. which build of lmms did you use so it can use .so files for vst's?

**Comment by Lazerbeak12345** [comment] 2024-04-11 14:19
> solution for this is to use wine64 instead of normal wine.

It was happening in both for me. On Fedora and Artix the default wineprefix is 64 bit. I also used WineTricks to try it on 32

**Comment by LeontKing2** [comment] 2024-04-13 07:51
By wine64 I mean using the wine64 binary instead of the default one.

**Comment by Rossmaxx** [comment] 2024-05-30 11:14
Fixed in the latest nightly.

**Closed by Rossmaxx** 2024-05-30 11:14 UTC
Labels: bug
