### ISSUE TITLE
LMMS crash (segfault) at startup on FreeBSD 13.1 amd64

### ISSUE THREAD

**Issue by rosorio** [LMMS/lmms#6739] opened 2023-06-16 12:31 UTC
### Bug Summary
LMMS segfault at startup in all versions of FreeBSD 12, 13 and 14

#### Steps to reproduce
In a fresh installed FreeBSD (13.1-RELEASE-p1 GENERIC amd64) with
a XFCE window manager installed and lmms installed from packages
(pkg install lmms).

you start lmms => the splash screen  pops
llms crash with the following message : 
```
Notice: could not set realtime priority.
[1]    78950 segmentation fault (core dumped)  lmms
```  
### LMMS version
LMMS 1.2.2
(FreeBSD x86_64, Qt 5.15.8, GCC FreeBSD Clang 15.0.7 (https://github.com/llvm/llvm-project.git llvmorg-15.0.7-0-g8dfdcc7b7bf6))

### Backtrace
```
 lldb lmms
(lldb) target create "lmms"
Current executable set to 'lmms' (x86_64).
(lldb) run
Process 79486 launched: '/usr/local/bin/lmms' (x86_64)
Notice: could not set realtime priority.
Process 79486 stopped
* thread #1, name = 'lmms', stop reason = signal SIGSEGV: invalid address (fault address: 0x813f50cf0)
    frame #0: 0x0000000801c2fc3e libQt5Core.so.5`QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) + 222
libQt5Core.so.5`QCoreApplicationPrivate::sendThroughApplicationEventFilters:
->  0x801c2fc3e <+222>: callq  *0x30(%rax)
    0x801c2fc41 <+225>: testb  %al, %al
    0x801c2fc43 <+227>: je     0x801c2fbe0               ; <+128>
    0x801c2fc45 <+229>: movb   $0x1, %al
(lldb) bt
* thread #1, name = 'lmms', stop reason = signal SIGSEGV: invalid address (fault address: 0x813f50cf0)
  * frame #0: 0x0000000801c2fc3e libQt5Core.so.5`QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) + 222
    frame #1: 0x000000080089bc04 libQt5Widgets.so.5`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 68
    frame #2: 0x000000080089d0a0 libQt5Widgets.so.5`QApplication::notify(QObject*, QEvent*) + 528
    frame #3: 0x0000000801c2fa20 libQt5Core.so.5`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 176
    frame #4: 0x00000008008c8879 libQt5Widgets.so.5`QWidgetPrivate::setStyle_helper(QStyle*, bool) + 633
    frame #5: 0x00000008008c85af libQt5Widgets.so.5`QWidgetPrivate::inheritStyle() + 511
    frame #6: 0x00000008008c1979 libQt5Widgets.so.5`QWidget::setParent(QWidget*, QFlags<Qt::WindowType>) + 1449
    frame #7: 0x00000008008c0457 libQt5Widgets.so.5`QWidgetPrivate::init(QWidget*, QFlags<Qt::WindowType>) + 711
    frame #8: 0x000000000049d214 lmms`MainWindow::MainWindow(this=0x0000000803694e60) at MainWindow.cpp:100:30
    frame #9: 0x00000000004958f3 lmms`GuiApplication::GuiApplication(this=0x0000000803610c20) at GuiApplication.cpp:116:21
    frame #10: 0x0000000000547ac4 lmms`main(argc=1, argv=0x00007fffffffe890) at main.cpp:759:7
    frame #11: 0x00000000003a6c70 lmms`_start(ap=<unavailable>, cleanup=<unavailable>) at crt1_c.c:75:7
```

**Comment by PhysSong** [comment] 2023-06-17 11:07
Duplicate of #6587.

**Closed by PhysSong** 2023-06-17 11:07 UTC
Labels: bug
