### ISSUE TITLE
In Piano Roll Editor, the "Mark current scale" feature is grayed out; lines are too faint.

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4135] opened 2018-01-27 19:32 UTC
If I select a scale in the Piano Roll Editor using the ![image](https://user-images.githubusercontent.com/9047168/35475531-2233c9aa-03c6-11e8-8783-04be45e62048.png) button, and then right-click on the piano keys, I find that the "Mark current scale" option is grayed out.
![image](https://user-images.githubusercontent.com/9047168/35475543-5dfc0b28-03c6-11e8-8e88-de1902697872.png)

If I use the **Mark semitone** option, the key is marked with a dark green line, which is practically very difficult to tell apart from the surrounding gray.
![image](https://user-images.githubusercontent.com/9047168/35475554-89a18442-03c6-11e8-918d-7dc8160cda09.png)
In this screenshot, the second row is marked.

In the old version, the marking had much better contrast. But again the color was not much different as compared to the lines used to create the grid, so it strained the eye.
![image](https://user-images.githubusercontent.com/9047168/35475588-375db83a-03c7-11e8-9575-23c6753fdbc0.png)
IMHO white dashed lines would offer even better contrast.

**Comment by zonkmachine** [comment] 2018-01-27 20:06
I believe this is a duplicate of https://github.com/LMMS/lmms/issues/3651

**Comment by raindropsfromsky** [comment] 2018-01-28 02:50
Well, only the later half is duplicate.

I recorded two observations here, and the first half is still valid (the menu option itself is grayed out).

**Comment by Umcaruje** [comment] 2018-01-28 14:56
also you're not setting the scale on the right button, the button you screenshoted is the chord selection button.

**Comment by Umcaruje** [comment] 2018-01-28 15:01
![image](https://user-images.githubusercontent.com/6282045/35483598-7243aacc-0444-11e8-9ff8-418234562680.png)

**Closed** 2018-01-28 15:02 UTC

**Comment by zonkmachine** [comment] 2018-01-31 16:21
> Well, only the later half is duplicate.

I may have been in a hurry. This issue is now closed but I'll look into it in a day or so to make sure I get the whole picture. There are quite a few issues on the same theme now.

**Comment by Umcaruje** [comment] 2018-01-31 18:34
>I may have been in a hurry. This issue is now closed but I'll look into it in a day or so to make sure I get the whole picture. There are quite a few issues on the same theme now.

I was in a hurry, I talked to the OP over on discord, they set a chord but not a scale which is why the option was grayed out.
