### ISSUE TITLE
When I hold a note on my computer keyboard, it sometimes does a random Arp.

### ISSUE THREAD

**Issue by JtLively** [LMMS/lmms#3121] opened 2016-11-14 04:34 UTC
Will I have to stop being lazy and use my MIDI controller for this issue for now?

**Comment by tresf** [comment] 2016-11-14 04:40
Possibly related #1644.

**Comment by DeRobyJ** [comment] 2016-11-14 14:42
or maybe #2768

Write your OS and lmms version, please

**Comment by JtLively** [comment] 2016-11-14 17:00
Seems similar. 
Ubuntu Studio and 1.1.3

**Comment by BaraMGB** [comment] 2016-11-14 19:44
That seems to be a qt issue. I noticed this on some systems, too. Once I had the same system (kubuntu? I don't remember) on laptop and desktop PC. The issue appeared only on my laptop. It's really annoying.

**Comment by zonkmachine** [comment] 2017-02-16 15:45
> Seems similar.
> Ubuntu Studio and 1.1.3

Closing as a duplicate of https://github.com/LMMS/lmms/issues/110 and https://github.com/LMMS/lmms/issues/2768 and some others. :)

@JtLively Workaround here: https://github.com/LMMS/lmms/issues/110#issuecomment-274394366

**Closed by zonkmachine** 2017-02-16 15:45 UTC
Labels: duplicate, not our bug
