### ISSUE TITLE
Ability to cut/join patterns in the sequencer

### ISSUE THREAD

**Issue by gi0e5b06** [LMMS/lmms#3829] opened 2017-09-27 12:50 UTC
It would be very useful.

**Comment by Umcaruje** [comment] 2017-09-27 13:00
Duplicate of #746

**Comment by Umcaruje** [comment] 2017-09-27 13:01
Oh, ok #746 asks for this only for Piano Roll but this should be useful in all editors

**Comment by gi0e5b06** [comment] 2017-09-27 14:08
Notes and Patterns are two different things.

**Comment by gi0e5b06** [comment] 2017-09-28 11:25
Not a duplicate at all.
Please re-open it.
@Umcaruje @tresf @lukas-w @zonkmachine @BaraMGB

**Comment by DouglasDGI** [comment] 2019-03-06 16:27
Is this the same as #3633?

**Comment by tresf** [comment] 2019-03-06 16:36
@DouglasDGI yes it is.

**Comment by tresf** [comment] 2019-03-11 20:33
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Closed** 2019-03-11 20:33 UTC
Labels: duplicate, enhancement

**Comment by rulatir** [comment] 2020-05-15 22:32
Seriously, lack of this feature is ABSURD. It is an absolutely ESSENTIAL feature. Done with LMMS, looking for alternatives.

**Comment by Veratil** [comment] 2020-05-15 22:51
> 
> 
> Seriously, lack of this feature is ABSURD. It is an absolutely ESSENTIAL feature. Done with LMMS, looking for alternatives.

We're all volunteers here on an open source project. If you wish to help implement this feature to help out the whole community with it, then we'd love the help!
