### ISSUE TITLE
[LMMS 1.2.2, Linux Mint 20] UI is unclickable after a delay

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#5606] opened 2020-08-01 02:55 UTC
### Bug Summary
After loading in a VST and opening the GUI, LMMS appears to create some sort of invisible window that covers the entire screen. I can't even click my dock.
#### Steps to reproduce
1. Load in a VST
2. turn a couple knobs or play audio from the vst
3. profit ig
#### Expected behavior
I can tweak as usual.
#### Actual behavior
UI is blocked.
#### Screenshot
Cant take a screenshot of something that isnt there
#### Affected LMMS versions
1.2.2 stable

#### Logs
still have no idea how to get logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by GingkathFox** [comment] 2020-08-03 01:05
i think i mightve found the issue? i ran the `lmms` command, and after the bug occurred i got this:

```
QObject::connect: Cannot connect (null)::subWindowActivated( QMdiSubWindow* ) to SubWindow::focusChanged( QMdiSubWindow* )
```

**Comment by PhysSong** [comment] 2020-08-03 02:32
Possible duplicate of #5104/#4885.

**Comment by PhysSong** [comment] 2021-06-05 03:05
Closing as a duplicate of #4885.

**Closed by PhysSong** 2021-06-05 03:05 UTC
Labels: bug, linux, stable branch, vst
