### ISSUE TITLE
size of individual windows irregular

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2194] opened 2015-07-19 16:11 UTC
Master 12.07.15  win32
thought i saw a similar issue, but i cant find it, so this behavior need attention
This happens at random -no reproduction recipe
![scale error](https://cloud.githubusercontent.com/assets/6662066/8766634/ebdea896-2e40-11e5-99ab-30f80204838b.JPG)
 Observe the marked edges. The window is* logically maximized*, but appear 'cut off'
Clicking in the window does not change it size, not does clicking outside
(resize with icons remove the problem)

a related issue appear every time a new PR block is opened in a new project, first time.
The  PR window is a tiny little thing in t l cornor :
![puny pr](https://cloud.githubusercontent.com/assets/6662066/8766673/15654c6e-2e42-11e5-91d0-eeee4ba0baac.JPG)

DDclick in topbar solves this

**Comment by Umcaruje** [comment] 2015-07-19 16:55
Please stop using so many acronyms in your reports. There is 'also' no *need* **for excessive** ***formatting***

When I first read the issue, PR block means Pull Request block, and DDclick is Double D battery click, I have to re-read the issue at least one more time to realize it's Piano Roll block and double click. Please make your bug reports more readable.

**Comment by tresf** [comment] 2015-07-19 17:11
We've all asked several times to clean up the titles. The branch and release need not be in the title.

**Comment by musikBear** [comment] 2015-07-20 11:06
keywords in tittle makes sorting and searching easy and effective. I have always used it, and it is almost pr automatic, but youre boss, so - il try not being automatic, and hamper effective easy sorting -imo, which does not matter.

**Comment by Umcaruje** [comment] 2015-07-20 11:29
@musikBear Search on github does not search only the issue titles, so keywords can be in the description of the issue. As for sorting, that's what labels are for. 

If you want to see all gui bugs that contain a specific word you can do that by adding `label:bug label:gui` next to your search query:
![image](https://cloud.githubusercontent.com/assets/6282045/8774820/c2d0a22c-2ee2-11e5-9d99-2bc669c5106f.png)

Or maybe you want to see all issues that need clarification, and have the word 'windows' in them:
![image](https://cloud.githubusercontent.com/assets/6282045/8774891/4bdc020a-2ee3-11e5-8df1-d21873dd0079.png)


You can easily filter any issue you want using the github tools. Adding branch and release names to the title just makes it harder to read and it takes attention away from the actual problem.

**Comment by musikBear** [comment] 2015-07-20 14:51
> If you want to see all gui bugs that contain a specific word you can do that by adding label:bug label:gui next to your search query:

*That* i did not know! very useful! Thanks

**Comment by M374LX** [comment] 2015-08-11 00:48
#2241, which is apparently related, may contain more useful information.

**Comment by tresf** [comment] 2015-08-24 12:22
@M374LX thanks.  Closing as duplicate of #2241.  @musikBear please reopen if you believe this was closed in error.

**Closed by tresf** 2015-08-24 12:22 UTC
