### ISSUE TITLE
snare04 and snare05 are almost silent

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2594] opened 2016-02-19 20:26 UTC
Even when I open with Audacity, I barely hear something. Happens in master branch at least.

**Comment by zonkmachine** [comment] 2016-02-19 20:35
https://github.com/LMMS/lmms/tree/master/data/samples/drums

These files are some 9 years old in the project and nothing has changed lately. They sound as usual when I open them in audacity here.

**Comment by IvanMaldonado** [comment] 2016-02-19 20:36
I remember using the snare04 in a project and the sound was good for some reason, I opened it again and I can barely hear it as well. I don't know what happened, I used to like snare04 a lot.

**Comment by karmux** [comment] 2016-02-19 20:37
I also saw they are 9 years old but I remember all snares sounded good months ago.

**Comment by zonkmachine** [comment] 2016-02-19 20:54
There's something going on in the beginning of this file. Maybe there's been some change to the file handling software.
![snare04](https://cloud.githubusercontent.com/assets/6368949/13188486/15ce2d56-d752-11e5-8748-210c1307d032.png)

**Comment by tresf** [comment] 2016-02-19 21:10
> Even when I open with Audacity, I barely hear something. Happens in master branch at least.

Reproduced on Windows too (master) except VLC plays it fine.  This is likely something underlying in the vorbis encoder changed and it's affecting `snare04.ogg` and `snare05.ogg`.

Try these.... [snares.zip](https://github.com/LMMS/lmms/files/138698/snares.zip)

**Comment by karmux** [comment] 2016-02-19 22:08
Inside Snare.zip are correct samples.

**Comment by tresf** [comment] 2016-02-20 16:31
Comparing before and after with the VLC re-encoded ones, they're quite different.

![image](https://cloud.githubusercontent.com/assets/6345473/13197769/30934504-d7c5-11e5-96d0-e66c38f6df5a.png)

As @zonkmachine illustrated, the left channel is corrupted, so I'll attempt to paste in a small portion of the right channel to keep the snare with an identical length as projects could sound quite different if envelope, loops, etc are being used.

**Comment by zonkmachine** [comment] 2016-02-20 16:39
> I'll attempt to paste in a small portion of the right channel

But it looks like it's a mono sample made stereo. If it was stereo to begin with they wouldn't be that identical. Just copy the good side over the bad one.

**Comment by zonkmachine** [comment] 2016-02-20 16:41
Option two it to clip it at +/- 1.0 so users who has used it in projects gets what they're used to.

**Comment by tresf** [comment] 2016-02-20 16:47
> But it looks like it's a mono sample made stereo. If it was stereo to begin with they wouldn't be that identical. Just copy the good side over the bad one.

I thought of this too.  I'm pretty sure they're identical, but I don't want to take any chances and the other offender `snare05.ogg` is stereo, so I'll just fix, reencode and upload.  Will close in a min here...

**Comment by zonkmachine** [comment] 2016-02-20 16:52
>> But it looks like it's a mono sample made stereo. If it was stereo to begin with they wouldn't be that identical. Just copy the good side over the bad one.
> 
> I thought of this too. I'm pretty sure they're identical

They're not. See my edit above... If people are used to a corrupt sample then probably the best option is to clip the sample.

**Comment by tresf** [comment] 2016-02-20 16:57
> They're not. See my edit above... If people are used to a corrupt sample then probably the best option is to clip the sample.

I strongly disagree... We need to keep it as close to original as possible or else people who use envelope will complain.

**Comment by tresf** [comment] 2016-02-20 17:15
To put more context around this point... 

Here is the before/after in audacity:

![image](https://cloud.githubusercontent.com/assets/6345473/13197988/00d21146-d7cb-11e5-8c99-0c968a0fa537.png)

I kept the left channel intact with exception of the copying of the right channel over the corrupt portion.

This way people utilizing loop mode, start/stop, attack, etc will get what it **should** have sounded like to begin with.

![image](https://cloud.githubusercontent.com/assets/6345473/13198014/7fb9fcb2-d7cb-11e5-8245-eeaf42b74232.png)

That's the pragmatic reasoning behind this... the actual impact to a track may be different, as it would differ based on the vorbis interpretation of the corrupt sample, which would likely vary between vorbis builds.

**Comment by zonkmachine** [comment] 2016-02-20 17:20
> I strongly disagree... We need to keep it as close to original as possible or else people who use envelope will complain.

But the borked one is the original. No?

**Comment by tresf** [comment] 2016-02-20 17:21
> But the borked one is the original. No?

Correct.

**Comment by tresf** [comment] 2016-02-20 21:48
Yeah, I see your points.  I don't think that "bork" is intentional, which is why it was removed.  In regards to why, that's a good question too.  Someone with better knowledge of the vorbis decoder library could probably do bisect and find out, but that is overkill I think.  We had a similar issue here #2392, fixed with a similar technique.

**Comment by zonkmachine** [comment] 2016-02-20 22:06
Testing files with ogginfo.
Both snare04.ogg and snare05.ogg has the same warning in the output.`
WARNING: Vorbis stream 1 does not have headers correctly framed. Terminal header page contains additional packets or has non-zero granulepos` and they differ in other ways too.
I'll dive into the rest of the files (later...) and maybe we can find more files that could be problematic.

```
zonkmachine@zonkmachine:~/builds/lmms/lmms$ ogginfo data/samples/drums/snare04.ogg 
Processing file "data/samples/drums/snare04.ogg"...

New logical stream (#1, serial: 77a03516): type vorbis
WARNING: Vorbis stream 1 does not have headers correctly framed. Terminal header page contains additional packets or has non-zero granulepos
Vorbis headers parsed for stream 1, information follows...
Version: 0
Vendor: Xiph.Org libVorbis I 20020717 (1.0)
Channels: 2
Rate: 44100

Nominal bitrate: 160,003000 kb/s
Upper bitrate not set
Lower bitrate not set
Vorbis stream 1:
	Total data length: 928 bytes
	Playback length: 0m:00.306s
	Average bitrate: 24,187234 kb/s
Logical stream 1 ended

```

```
zonkmachine@zonkmachine:~/builds/lmms/lmms$ ogginfo data/samples/drums/snare05.ogg 
Processing file "data/samples/drums/snare05.ogg"...

New logical stream (#1, serial: 4eb08a45): type vorbis
WARNING: Vorbis stream 1 does not have headers correctly framed. Terminal header page contains additional packets or has non-zero granulepos
Vorbis headers parsed for stream 1, information follows...
Version: 0
Vendor: Xiph.Org libVorbis I 20020717 (1.0)
Channels: 2
Rate: 44100

Nominal bitrate: 160,003000 kb/s
Upper bitrate not set
Lower bitrate not set
Vorbis stream 1:
	Total data length: 947 bytes
	Playback length: 0m:00.389s
	Average bitrate: 19,452786 kb/s
Logical stream 1 ended

```

```
zonkmachine@zonkmachine:~/builds/lmms/lmms$ ogginfo data/samples/drums/snare06.ogg 
Processing file "data/samples/drums/snare06.ogg"...

New logical stream (#1, serial: 15d22227): type vorbis
Vorbis headers parsed for stream 1, information follows...
Version: 0
Vendor: Xiph.Org libVorbis I 20020717 (1.0)
Channels: 1
Rate: 44100

Nominal bitrate: 90,000000 kb/s
Upper bitrate: 4294967,295000 kb/s
Lower bitrate: 4294967,295000 kb/s
Vorbis stream 1:
	Total data length: 2573 bytes
	Playback length: 0m:00.273s
	Average bitrate: 75,301070 kb/s
Logical stream 1 ended

```

**Closed** 2016-02-20 22:06 UTC
