### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by Quentin-CORBET** [LMMS/lmms#6125] opened 2021-08-09 13:52 UTC
- Exporting in multitrack MIDI
- Exporting in PDF music sheet
- Category for instruments when we have a lot of instruments
- Some brass, woodwinds, percussions and strings VST
- Metadata for projects
- A way to import some VST to the LMMS VST list
- An Android and iOS app to edit some projects when we can't use computer

**Comment by qnebra** [comment] 2021-08-09 14:13
- already exists, unless this is something else
- export midi, open in musescore, export PDF. Why to export PDF sheet in lmms?
- samples or VST?
- Leave it to user, also there are multiple sources of getting free VSTs, there is no need to provide them with lmms
- partially exists in really limited form, would be nice
- would be nice
- nope, not much resources

**Comment by Quentin-CORBET** [comment] 2021-08-09 14:18
Category for instruments exemple
Brass
  trumpet
  trombone
  horn
Strings
  violin
  viola
  cello

**Comment by DomClark** [comment] 2021-08-09 14:20
> Exporting in multitrack MIDI

Duplicate of #5198.

> Exporting in PDF music sheet

LMMS is not notation software. Export to MIDI and use something like MuseScore to turn it into sheet music.

> Category for instruments when we have a lot of instruments

Do you mean track groups? If so, a duplicate of #735. If you mean in the sidebar, you can group your own files however you want, and there aren't many built in instruments to cause a problem.

> Some brass, woodwinds, percussions and strings VST

We are discussing what sort of sample collections we want to distribute with LMMS. See the [assets project](https://github.com/LMMS/assets) for more information. In the meantime, there are many third-party options available that work with LMMS.

> Metadata for projects

I'm not sure what you mean. Can you expand on this? There is the project notes feature you can use to give information about the project for now.

> A way to import some VST to the LMMS VST list

Work in progress - currently supported for LV2 instruments, will be extended to VST later. Duplicate of #4853.

> An Android and iOS app to edit some projects when we can't use computer

Not going to happen any time soon, sorry.

In the future, please follow the issue template that you are presented with when creating a new issue.

**Comment by Quentin-CORBET** [comment] 2021-08-09 14:22
ok thanks

**Comment by qnebra** [comment] 2021-08-09 14:23
I think metadata means "tags" editor for projects. Like:
 Title, Author, Album Title, Genre, Track Number, Cover and others

**Comment by Quentin-CORBET** [comment] 2021-08-09 14:23
yes that's it

**Comment by DomClark** [comment] 2021-08-09 14:32
I can't find an existing issue regarding project metadata. Since that's the only relevant part of this issue, would you mind opening a new issue for it, following the issue template? I'm going to close this issue now; thanks for your suggestions.

**Closed by DomClark** 2021-08-09 14:32 UTC
Labels: enhancement
