### ISSUE TITLE
Play / Pause / Stop key

### ISSUE THREAD

**Issue by binyominzeev** [LMMS/lmms#3288] opened 2017-01-24 11:56 UTC
I was delighted to find out the great feature "Pause" in both Piano Roll and Song Editor so that the cursor doesn't jump back to the beginning of the song every time I stop it in order to change a smaller thing.

However, I think it would make more sense to **have a separate key associated for "Pause" than Space**, which seems to be the same as for "Stop". Thereby it would be possible to use the keyboard for this, without the mouse.

For me, assigning Space to "Pause" would be more comfortable, but I understand if other users would want to preserve it for "Stop". Nevertheless, please, introduce at least a new key for "Pause". Thank you very much!

**Comment by zonkmachine** [comment] 2017-01-24 13:40
I started working on this quite a while back https://github.com/LMMS/lmms/pull/728
Don't remember why I didn't picked this one up again. I remember having this function on Logic and it's really smooth.

**Comment by binyominzeev** [comment] 2017-01-24 13:50
OK, good to know that I can do it already, I just learned it from your link:

https://github.com/LMMS/lmms/pull/728#issuecomment-43367768

I couldn't figure it out by myself. Now I am not bothered by that anymore. Thank you!

**Comment by farvardin** [comment] 2017-05-30 11:41
oh, the stop, then rewind to start was annoying as hell! I'm glad I've learned the button close to the magnifier was for changing this behavior: stop rewind to start / stop rewind to previous position / stop and do nothing else. Maybe it could be set to stop and do nothing else by default.

**Comment by musikBear** [comment] 2017-05-30 15:43
> Maybe it could be set to stop and do nothing else by default.

Duplicate of a duplicate, its been up *many* times to have a key-short for just **stopping** -eg the same behaviour as when **pause** is mouse-clicked

**Comment by PhysSong** [comment] 2020-04-30 04:44
Closing, since there's a new and better feature request #5301.

**Closed by PhysSong** 2020-04-30 04:44 UTC
Labels: enhancement
