### ISSUE TITLE
In piano roll, curser stays in "ctrl-mode" although not pressed anymore

### ISSUE THREAD

**Issue by notiflux** [LMMS/lmms#2479] opened 2015-12-05 14:20 UTC
This bug only sometimes happens to me and I only partially know how to reproduce it. Sometimes, when I want to mark something in the piano roll, after I released the ctrl key, the curser stays in that ctrl-mode and it also acts in the ctrl-mode.

**Comment by musikBear** [comment] 2015-12-06 12:41
duplicate #431

**Comment by zonkmachine** [comment] 2016-08-01 00:42
Duplicate of #431 and fixed...

**Closed by zonkmachine** 2016-08-01 00:42 UTC
Labels: duplicate
