### ISSUE TITLE
Backward comp.: Automation tracks read differently (logscale) in 1.1.3

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#1914] opened 2015-04-02 05:51 UTC
Not sure if I updated from 1.0.4 or 1.1.1 to 1.1.3, but my songs now sound completely different (wrong). Reason: The automation tracks seem to be read logarithmically now.

As an example: When I wanted a lowpass to increase linearly, I had to draw the automation track in a logarithmic curve (since there has been no logscale conversion before 1.1.1, and frequency must be increased logarithmically). Now, with 1.1.3, the scale of the lowpass is being converted logarithmically, but since the automation track is *already* designed that way, the result is undesired.

To fix this, one needs to find out which automation tracks have been drawn before lmms 1.1.3 and which have not. Only the new ones are allowed to be converted logarithmically.

Btw: With 1.1.3, the bug is in a "stable" version. It's a severe bug, because all (~100) of my songs are played incorrect now.

**Comment by Spekular** [comment] 2015-04-02 06:42
It's possible to fix this by right clicking an automated knob and setting
it to linear (I think?) so they're not permanently ruined. Considering
that, I'm not sure there will be a fix for this, as the backwards
compatibility hacks that are implemented right now are making the code
messy, and will be abandoned in 2.0.

**Comment by tresf** [comment] 2015-04-02 12:57
@JohannesLorenz thanks for the bug report.  This is a duplicate of #1642.

The other bug report already has the details necessary to fix the bug, we just need someone to work on it. :+1:

**Closed by tresf** 2015-04-02 12:57 UTC
Labels: duplicate
