### ISSUE TITLE
Could "vertical" zoom of the piano roll view grid cells be added?

### ISSUE THREAD

**Issue by yetoyeto** [LMMS/lmms#5371] opened 2020-01-12 12:45 UTC
Could "vertical" zoom of the piano roll view grid cells be added?

**Comment by Veratil** [comment] 2020-01-12 18:51
Yes, it can! I'll see about working on this after my other PR working in the same code area is merged.

**Comment by yetoyeto** [comment] 2020-01-13 01:13
Thank you. Thank you. That would be helpful.

**Comment by Spekular** [comment] 2020-01-13 12:28
Duplicate of #2294, consolidated in #4877.

**Closed by Spekular** 2020-01-13 12:28 UTC
Labels: enhancement
