### ISSUE TITLE
enhancement -beat and bass editor playhead

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2019] opened 2015-04-27 11:42 UTC
Not sure if mentioned previously (?), but BB-editor need a playhead. It would be good if it was possible to follow the bb-lines 'active' sound
This feature could  be optional enabled  in BB-editor (no need to waste cpu)

**Comment by tresf** [comment] 2015-04-27 12:16
Duplicate of #1954 #1195

**Closed by tresf** 2015-04-27 12:16 UTC

**Comment by musikBear** [comment] 2015-04-27 14:25
i searched beat and baseline playhead, nothing came up
bnwm - as long as this has a ticket

**Comment by tresf** [comment] 2015-04-27 14:29
Third result:

https://github.com/LMMS/lmms/search?q=playhead&state=open&type=Issues&utf8=%E2%9C%93
