### ISSUE TITLE
Export ranges / Export tracks

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1040] opened 2014-07-28 10:37 UTC
In Ardour one can create a set of range markers on the timeline, that will be exported to files named after the marker. Such a feature in LMMS would be a great improvement to workflow when working with sound effects (multiple files out of one project) or game music with many variants.

I can think of a special type of tracks that would use it's clips to define the export ranges/output file names.

What do you think of that?

**Comment by Sti2nd** [comment] 2015-02-07 12:03
https://github.com/LMMS/lmms/pull/1482 and export tracks has also been implemented.

**Comment by tresf** [comment] 2015-02-07 13:45
Agreed.  Duplicate of others. 
 * Timeline markers:  #156
 * Range Export: (PR) #1482

Please add any missing details to #156 if present here but missing there.

**Closed by tresf** 2015-02-07 13:45 UTC
Labels: duplicate, enhancement
