### ISSUE TITLE
Arpeggios, sort mode, and release

### ISSUE THREAD

**Issue by eagles051387** [LMMS/lmms#340] opened 2014-02-19 00:22 UTC
Hello, I'm on LMMS 0.4.14-rc1, and there is a problem with arpeggios.
This existed for a while, but I just did a bit more debugging. When the release of the instrument overlaps with the next note in sequence, a note will either a) fail to play, or b) play two notes together when the instrument is set to "sort" mode.

**Comment by repsej** [comment] 2015-05-23 15:52
This is still an issue (1.1.3 win64) - and I think it has gotten worse recently.  

I've made a very simple example that shows it.

![image](https://cloud.githubusercontent.com/assets/116525/7784754/5bcf5d14-0171-11e5-986a-aa3a6d8397e7.png)

There are just two half notes in the piano roll and the arpeggio time setting is also set to half a note.

Playing this yields a lot of overlapping notes and strange clicking noise.

Worth noticing:
 - Changing the tempo of the song changes the bug behaviour.
 - Changing gate, range, sorting mode dosn't affect the bug.
 - The bug only comes after the first looping (also it disappears from time to time in some strange pattern)

**Comment by repsej** [comment] 2015-05-23 16:01
A short video with some of the arpeggio problems.

https://youtu.be/tDRmTxxEYSA

**Comment by musikBear** [comment] 2015-05-24 11:47
interesting! and tchanging the BMP, other weird things happens
when we get below 50 the 'double-note' is replaced by silence. The playhead moves over the note, but there is no sound.
I think that might be the case also at higher bmp, but there its not possible to discriminate the silence  ?
fi:
at 60 bmp. arp: 2 octaves. TeimeSync : ½-note
beat1 sound
beat2 silence
beat3 sound
beat4 silence
or..
1+ 2- 3+ 4-
second run is different:
1* 2- 3- 4+
where '*' is double note
3..8 as 2.
9.
1* 2- 3* 4+
That is reproduceable, and could(?) give insight in the off-sequence

**Comment by musikBear** [comment] 2016-07-29 13:24
How does current Master do in *this* respect?
Should this actually be marked at least **Bug** or isent it in fact **Critical** ?

**Comment by Umcaruje** [comment] 2016-07-29 15:39
!? This bug isn't critical, neither its even milestoned, so it isn't such a high priority.

**Comment by musikBear** [comment] 2016-07-30 11:51
@Umcaruje #2589 was marked critical, this is same thing, but its fine that its now marked 'bug'. :+1 
Sort-mode *may* also be ok in current Master, because #2589 is closed. 
Could you do a test of sort-mode on Master?

**Comment by zonkmachine** [comment] 2017-10-12 16:53
Closing as a duplicate of https://github.com/LMMS/lmms/issues/2606
The later issue goes into more depth.

**Closed by zonkmachine** 2017-10-12 16:53 UTC
Labels: bug, core
