### ISSUE TITLE
3rd party VST Support on Mac please

### ISSUE THREAD

**Issue by TheDandyFellow** [LMMS/lmms#6425] opened 2022-06-04 19:20 UTC
# Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet.

#### Justification: I love using LMMS. it feels like using FL Studio, but it's different from it in a way that makes it much easier to use in my opinion. It has a much better workflow for me than FL Studio does and it has the best piano roll i've ever had the pleasure of using, and that includes Logic Pro and FL Studio and some other online tools such as Paandorasbox and beepbox which are just piano rolls with instruments. And, the only "Only" problem i have is that i can't use 3rd party VSTs. I'm a Mac user always have been, probably always will be. And i love composing with LMMS and FL Studio. i just like the workflow of LMMS more. I just wish i could use 3rd party VSTs.

Sorry for making my request so long, and thank you for your time

**Comment by Rossmaxx** [comment] 2022-06-08 07:14
I would suggest you wait for it. I don't wanna make you sad but the wait will be pretty long. The team is under the task of reorganising the codebase, which is almost done. Even after the reorg, there's a lengthy list of things to do (i beleive mac vst support is a part of it). They will look into it anyway.

**Comment by TheDandyFellow** [comment] 2022-06-08 08:54
Yeah I can wait, I’ve been using soundfonts. I just wanted to bring it back to their attention. Because (to my knowledge) no ones mentioned it since 2018.

Also Thank you for your time

**Comment by luzpaz** [comment] 2023-07-01 02:28
this ticket should have a `macOS` related label

**Comment by PhysSong** [comment] 2023-07-01 02:41
Duplicate of #3975.

**Comment by luzpaz** [comment] 2023-07-01 14:22
@PhysSong can this ticket then be closed (instead of contributing to bloat in the issue queue) ?

**Closed** 2023-07-01 16:50 UTC
Labels: duplicate
