### ISSUE TITLE
VST Effects & Instruments Issue When Contain Dropdown Menus

### ISSUE THREAD

**Issue by sound8** [LMMS/lmms#6269] opened 2022-01-11 17:11 UTC
I have noticed that any of the VST Effects & Instruments I have come across that contain drop down menus do not seem to allow access to them in LMMS.

A couple effects that come to mind are
Triktik "Krush" - preset drop down
Venn Audio "Utility" - drop down menu in center of plugin
If anyone can think of any please try/mention if they work or not.

Odd thing is this one works
reacontrolmidi (can't use midi effects in LMMS anyways but drop downs work though)
Found in Reaper Bundle   Reaplugs VST

Can't think of any VST Instruments that contain drop down menus at the moment, but if anyone knows of any give them a try as well.

**Comment by Spekular** [comment] 2022-01-11 17:19
Duplicate of #3918 and #4424

**Closed by Spekular** 2022-01-11 17:19 UTC
Labels: bug

**Comment by Monospace-V** [comment] 2022-01-12 10:20
OP: Switch to No Embedding in settings for plugin embed settings. Should fix your issue. Try holding open the drop down menu instead of clicking it, if in QtAPI or Win32API. This works sometimes, not usually.
Requesting you to search for issue duplicates before reporting.

**Comment by Monospace-V** [comment] 2022-01-13 16:10
I'll try to help.

Re 3918: Valid.
Re 4424: While VSTi and VSTfx are different, LMMS does handle them in similar ways, and usually are associated together. For me, it is intuitive to fix my VSTfx problem with a VSTi workaround (or at least test it), but I understand that it may easily seem like they're entirely different things.

Re search engine issues:
The first suggestion is, use google (or any internet search engine) and not just github (which doesn't have relevance search)- we have a forum too, [here](lmms.io/forum/), and using a search engine ensures all available resources are searched, and not just the bug/request tracker.
Next, when searching, put necessary keywords in double inverted commas, which forces them to show up in search results. I suggest only putting words like "lmms" and "vst" in double inverted commas, and few others- this is because, it is possible for someone to phrase 'drop-down menus inaccessible' in many different ways, or mention issues that involve menus that aren't drop down. But lmms and vst will definitely be part of the issue wherever it is, so you want to ensure that ALL results have that.
See [this google search](https://www.google.com/search?q=%22lmms%22+%22vst%22+drop-down+menus). Double-inverted commas on the words that will DEFINITELY show up.

That being said, we have a [forum](lmms.io/forum) that is (usually) up and running, with members who give responses within a single day or two. It is the go-to for basic bugs you need help with, and is ideally the first resort. The github is set aside as something slightly more important.
On the forums, the members can help you more than we can on github. You can post all details of your problem, and if it's easy enough to replicate we'll possible even try to get the bug ourselves, let you know if there are workarounds or the problem's new. (If a problem's unheard of but replicable, we may post it to github, or let you know- or both.) It's not _particularly_ active, admitted, and there are spammers, but we help if we can- from simple "reinstall LMMS and try" suggestions to "We have no clue what's going on but we can't replicate it, so we'll ignore you" (rough, but within reason).
The best part: we don't have problems with repeating ourselves multiple times, same instructions to same problems for different people: because there is no need to keep the forums clear from issues, unlike the github which the devs use and therefore duplicate-posting is redundant and problematic.
