### ISSUE TITLE
Some windows in LMMS have white heading strip (instead of gray-shaded strip)

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4138] opened 2018-01-28 16:18 UTC
Sometimes the heading of the window loses its gray shading, and appears as white strip with black text:
![image](https://user-images.githubusercontent.com/9047168/35484298-26558ef2-0474-11e8-8043-ec3b99f65ea4.png)

![image](https://user-images.githubusercontent.com/9047168/35484311-4f5ba836-0474-11e8-96f4-3573931b64b7.png)

![image](https://user-images.githubusercontent.com/9047168/35484322-8d359fcc-0474-11e8-85c8-6dd02dd75b4f.png)

![image](https://user-images.githubusercontent.com/9047168/35484349-bdcef6e2-0474-11e8-9312-02f6af6d0022.png)

**Comment by Umcaruje** [comment] 2018-01-28 16:19
The last one is weird but the rest is just regular windows window styling.

**Comment by tresf** [comment] 2018-01-28 16:25
We need to be more consistent about how we decorate our modal windows.  GTK offers [popovers](https://askubuntu.com/questions/109321/popup-dialogs-attached-to-window-title-and-not-movable-how-to-detach-modal-dial), which are a bit more modern approach to a simple, modal input-dialog.

In regards to the description of this bug, I'd like it to be reproduced on a non-HiDPI display.  The Windows 8/10 desktops do a very poor job of mixing HiDPI and standard DPI and it creates artifacts in all applications I've used.

**Comment by musikBear** [comment] 2018-01-28 18:29
@raindropsfromsky 
> Sometimes...

vague, and 
* what lmms 
* what os 

i have never seen this in win 32 fyi.

**Comment by tresf** [comment] 2018-01-28 18:32
@musikBear He's on Windows 10 and he's using HiDPI as explained by my post just before yours.

On a side-note, until you've started working with various platforms, please stop demanding OS information from our bug submitters, it just adds unnecessary chatter.

**Comment by BaraMGB** [comment] 2018-01-29 19:25
All these  windows aren't MDI windows. Only MDI windows have the gray shades window decoration.

**Comment by tresf** [comment] 2018-01-29 20:05
> All these windows aren't MDI windows. Only MDI windows have the gray shades window decoration.

Agreed.  I think this is a `wontfix` issue because the software uses some native windowing by default.

**Comment by tresf** [comment] 2018-02-26 18:29
Closing due to lack of response by the OP.  This is just the default behavior for modal dialogs combined with what I believe to be multi-monitor bugs with Qt's font sizing.

**Closed by tresf** 2018-02-26 18:29 UTC
Labels: gui, needs clarification, windows
