### ISSUE TITLE
Can't load VSTs - RemotePluginClient::shmget issue

### ISSUE THREAD

**Issue by kernelcrasher** [LMMS/lmms#2240] opened 2015-08-07 11:32 UTC
I am running 64 bit Arch, with LMMS installed from the repo. I can't get VeSTige to work, loading a VST instrument (for example, DSK Asian DreamZ) results in the following output to the terminal:
```
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
RemotePluginClient::shmget: No such file or directory
```
upon which LMMS freezes and has to be killed. I have tried this with other insturments (such as Synth1) with identical results.

**Comment by tresf** [comment] 2015-08-07 13:08
Duplicate of #1875.

-Tres

**Closed by tresf** 2015-08-07 13:08 UTC

**Comment by hydrix9** [comment] 2015-08-08 03:53
notably the shmget part went away for me when I upgraded to latest wine

**Comment by mkondel** [comment] 2015-08-18 19:01
64 bit Ubuntu 15.04, LMMS 1.1.3 from KXStudio.  I installed the latest beta of Wine, but still get the 'shmget' error.  This is me trying to import mda-vocoder to the master ch:
```
max@max-linux:~$ lmms
Notice: could not set realtime priority.
VST sync support disabled in your configuration
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
RemotePluginClient::shmget: No such file or directory
lmms: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
Killed
max@max-linux:~$ wine --version
wine-1.7.44
max@max-linux:~$ uname -a
Linux max-linux 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
