### ISSUE TITLE
MuseScore Midi to LMMS Import Issues

### ISSUE THREAD

**Issue by famecastle** [LMMS/lmms#5116] opened 2019-08-05 23:13 UTC
There are many issues complaining about the LMMS MIDI importing capabilities. However, I think this one is new (also in the aspect that I am using the latest software versions). I am using the latest stable **LMMS 1.2.0** in combination with the latest **MuseScore 3.2.5** . The latter program version is just for your information, because I think I can locate this issue back to LMMS.

There are several things that don't seem right to me when importing my own MIDI file into LMMS:

- Many tracks have the same name, different instruments, but only one of each track number contains notes.
- Track 2 does not exist. I don't even miss it. I believe, there is no instrument missing.
- The bassline of my piano (track 1) is not imported if I don't insert notes into the first measure at the beginning. (I intend to introduce the bassline later in the score).
- If I however do insert some notes in the beginning, the whole bassline appears except that the newly added notes in the front do not appear!
- Some instruments are not automatically matched with my soundfont. I converted the MuseScore General soundfont (sf3 format) to sf2 and set it in LMMS as my default soundfont. However, I do not consider some wrong instruments as a big deal, since I can easily change this.

I don't have an idea at all of how MIDI file importing/parsing works, but timidity played back my score perfectly (with right sounding instruments, but on timidity's instrument set of course)! Since timidity is open source, quite lightweight and simple, just wondering, is it that hard to make a MIDI importer that does not do said crazy things?
Below is a screenshot. I'm afraid I can't publicly post my MIDI file since it's sort of confidental, but if required, I will do my best to replicate such a MIDI file or reach out to you in a more discrete way.

Below is a screenshot:
![Screenshot](https://user-images.githubusercontent.com/11258821/62500394-71232300-b7e6-11e9-9695-1f8c371530a1.png)

Thank you for your efforts.

**Comment by PhysSong** [comment] 2019-08-06 06:43
Duplicate of #2741 and #815.

**Closed** 2019-08-06 06:43 UTC
