### ISSUE TITLE
Play samples automatically in the browser

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4599] opened 2018-09-19 02:09 UTC
Hi guys. when I was using lmms I realized that the file browser does not automatically reproduce the samples and presets when I move with the keys down and up, what it does is that I have to give many clicks to play them and to top it off I filled the bb editor and the song editor of sounds that I will not use, and that is very annoying, in addition, the browser does not have a lower scroll bar which makes it necessary to extend the browser, since my libraries are organized in many folders. It is something like this:

![antes boton de rep y barra dezp](https://user-images.githubusercontent.com/26127693/45726769-a9018780-bb8e-11e8-8c27-44214614e1b4.png)
So my suggestion is to add in the configurations the option '' to automatically reproduce the samples in the browser with the '' keys. and also add the lower scroll bar that strangely does not appear or is not. regards
![autoreproduccion y barra de dezp](https://user-images.githubusercontent.com/26127693/45726900-61c7c680-bb8f-11e8-9d7e-f0937ea3b971.png)

**Comment by PhysSong** [comment] 2018-09-19 04:58
Currently, there's no way to play samples and/or presets only using keyboards. I think we can add a key to allow playing them.

**Comment by tresf** [comment] 2018-09-24 15:39
Duplicate of #871.  Note, we encourage any help with the codebase, especially for these smaller items.  As you can see from our tracker we have a very large list of enhancement requests.  Closing, marking as duplicate.

> the browser does not have a lower scroll bar which makes it necessary to extend the browser,

This sounds like a bug.  Please file it separately so that we can track it as a bug (instead of an enhancement).

**Closed by tresf** 2018-09-24 15:39 UTC
Labels: duplicate, enhancement, ux
