### ISSUE TITLE
Vestige module is not listed despite it builds successfully

### ISSUE THREAD

**Issue by Bukarus** [LMMS/lmms#2628] opened 2016-03-02 16:31 UTC
I'm using arch linux x64. I'm trying to get lmms version with vestige module, but it doesn't show up.
I have all deps installed, when running cmake, it states that both vst instrument and vst effect are ok, also I see that everything related to vst compiled and linked successfully, but when I'm opening lmms itself, vestige module is not listed on the list. Compiling with gcc 5.3.0.

**Edit: @tresf from conversation on `#lmms` after adding `qDebug()`**

```
"Cannot load library /home/tricobalt/lmms/build/plugins/libvestige.so: (../libvstbase.so: cannot open shared object file: No such file or directory)"
"Cannot load library /home/tricobalt/lmms/build/plugins/libvsteffect.so: (../libvstbase.so: cannot open shared object file: No such file or directory)"
```

**Comment by tresf** [comment] 2016-03-02 19:06
@Bukarus it looks like we're never displaying library load errors from our `plugins` directory.

For troubleshooting, can you please add this to [PluginFactory.cpp#147](https://github.com/LMMS/lmms/blob/master/src/core/PluginFactory.cpp#L147)

`PluginFactory.cpp#L147`
```cpp
qWarning() << library->errorString();
```

This will tell us what the error message is while loading.  For example, if I make a fake plugin:

```bash
touch plugins/libFake.so
```

Then I get the following output in console:

```
"Cannot load library /home/foo/lmms/build/plugins/libFake.so: (/home/foo/lmms/build/plugins/libFake.so: invalid ELF header)"

```

**Comment by tresf** [comment] 2016-03-02 19:07
@Lukas-W should we add some debug info to the console for cases like this?  It seems quite strange that we offer no output when a lib fails to load, especially libs that are placed into the `/plugins` directory.

**Comment by tresf** [comment] 2016-03-02 19:26
Ok... perhaps [new cmake `CMP0015` behavior](https://cmake.org/cmake/help/v3.0/policy/CMP0015.html) going on here... 

What `cmake` version are you on?

@Bukarus can you add this to `/CMakeLists.txt#L11` and see if it fixes it?
```diff
IF(COMMAND CMAKE_POLICY)
	CMAKE_POLICY(SET CMP0005 NEW)
	CMAKE_POLICY(SET CMP0003 NEW)
	IF (CMAKE_MAJOR_VERSION GREATER 2)
+		CMAKE_POLICY(SET CMP0015 OLD)
		CMAKE_POLICY(SET CMP0026 OLD)
	ENDIF()
ENDIF(COMMAND CMAKE_POLICY)
```

**Comment by Bukarus** [comment] 2016-03-02 19:54
Putting libvestige.so to build's parent directory (root of the entire lmms folder) makes vestige appear on the list. Compiling with modified cmakelists (and clean lmms repo clone) didn't make any difference, thought.

**Comment by tresf** [comment] 2016-03-02 20:26
Ok... I think this is a duplicate of https://github.com/LMMS/lmms/issues/2572.

The relevant portion is here:

> ... [`foo.so`] is compiled as a module and not as a shared library (maybe a change in cmake cause this - cmake 3.4.1 ...).

The solution would be similar to [`pulls/#2758`](https://github.com/LMMS/lmms/pull/2578/files), scroll down to the `CMakeLists.txt` portion.

If this is correct, we'll need to fit it for `plugins/VstEffect` too.

**Comment by liushuyu** [comment] 2016-03-03 01:56
>The solution would be similar to pulls/#2758, scroll down to the CMakeLists.txt portion.

Yes,  I also uses Arch Linux x86_64 version,  and this surely worked for me.

**Comment by tresf** [comment] 2016-03-03 03:38
@liushuyu can you please fork and pull request this change or post the diff so that one of us can implement it?  I assume #1875 is still broken afterward, right?

**Comment by Bukarus** [comment] 2016-03-03 19:01
@tresf could you give me instructions how to fix vestige and vsteffects cmakefiles.txt, so I could check if #1875 is still happens?

**Comment by tresf** [comment] 2016-03-03 19:17
> @tresf could you give me instructions how to fix vestige and vsteffects cmakefiles.txt, so I could check if #1875 still happens?

I was hoping @liushuyu would do that.  I don't have a machine ready to test the code on, wherease @liushuyu apparently does. :+1:

**Comment by tresf** [comment] 2016-03-03 20:19
> @tresf could you give me instructions how to fix vestige and vsteffects cmakefiles.txt, so I could check if #1875 still happens?

If I were to try, I'd start by adding [this line](https://github.com/LMMS/lmms/pull/2578/files#diff-8e97a3188216f613f844021537ce7b6cR6) to the `plugins/vestige/CMakeLists.txt` file. :+1: 

If that fixes the listing, I'd repeat for the `VstEffects`, respectively.

**Comment by Lukas-W** [comment] 2016-03-03 20:51
> @Lukas-W should we add some debug info to the console for cases like this?

Yes! It'd be helpful to have a output in the GUI as well but that's an ongoing discussion iirc (about how to do this while keeping engine and gui decoupled).

**Comment by tresf** [comment] 2016-03-03 21:51
> Yes! It'd be helpful to have a output in the GUI as well but that's an ongoing discussion iirc (about how to do this while keeping engine and gui decoupled).

They're being collected alright, not sure how best to log them (#1945, #1525, @Wallacoloo), nor where they're going #1524...

**Comment by liushuyu** [comment] 2016-03-03 23:42
>I was hoping @liushuyu would do that. I don't have a machine ready to test the code on, wherease @liushuyu apparently does. 

First, yes you are right. 😀
 so how to fix? 
Just take a look at #2578, I found the same solution can be applied to Vestige compilation ('Linking',  more precisely). 
What's more, I even tried to change  the link method to 'SHARED' of all the plugins, and expect a crash. But to my 'surprise', LMMS still worked like a charm. XD

**So just change the link method of Vestige from "MODULE" to "SHARED" will work** ( I swear...)

**Comment by liushuyu** [comment] 2016-03-04 03:22
>@liushuyu can you please fork and pull request this change or post the diff so that one of us can implement it? I assume #1875 is still broken afterward, right?

Yes,  #1875 still exists... It takes forever to load the VST plugins under Arch Linux 64-bit (Other platforms have not tested, and I am afraid this could likely to happen on many 64-bit Linux systems) . 🌝

**Comment by tresf** [comment] 2016-03-04 06:41
A Pull Request would be fantastic from someone who's already working on this code (including both `vestige` and `VstEffects` confirmed on a platform exhibiting the issues.  If not, we'll get to it... eventually.

**Comment by tresf** [comment] 2016-03-04 15:22
@Lukas-W your auto-assign stuff, please turn it off. :+1:

**Comment by tresf** [comment] 2016-03-04 18:26
@Bukarus, fixed.  Please issue a `git pull` and you'll have the fix implemented.

@liushuyu much obliged. 🌝

**Closed** 2016-03-04 18:25 UTC
Labels: bug

**Comment by Lukas-W** [comment] 2016-03-05 00:25
> your auto-assign stuff, please turn it off.

Is it *still* doing that? I'll try, but I'll probably have to reach out to support…

**Comment by tresf** [comment] 2016-03-05 00:27
Is this "reversible" crane your doing as well? https://github.com/LMMS/lmms/pull/2632#issue-138433392  :laughing:

**Comment by Lukas-W** [comment] 2016-03-05 00:28
Should be turned off now.

**Comment by Lukas-W** [comment] 2016-03-05 00:32
No, it isn't. Promise :raised_hands:
