### ISSUE TITLE
Song editor: can't set or see loop points

### ISSUE THREAD

**Issue by tukkek** [LMMS/lmms#4199] opened 2018-02-28 17:24 UTC
I'm trying out the latest beta from your download page (AppImage) and I can't see or set loops on the Song Editor. Frankly, I can't see how to write a song without looping so this is pretty much a deal breaker for me unless I find a work-around.

I will add a screenshot next showing that a lot of what used to be UI is now just black. Not sure if that's a feature or a bug for 1.2 or how I feel about it if it is, but that's not a problem - while looping is a must-have.

If I enable loops, even though it doesn't show me the marker, it will still loop the first 16 beats (4 bars?), which I assume is just the default starting value for the marker. Trying to change the marker's position, even though it's invisible, like I would on the latest stable release from Debian, does nothing to change this behavior either (ie. doesn't "move" the invisible marker).

**Comment by tukkek** [comment] 2018-02-28 17:25
![screenshot_20180228_142527](https://user-images.githubusercontent.com/3819826/36802271-3c95cc04-1c93-11e8-8727-86e966c3c01a.png)

**Comment by tresf** [comment] 2018-02-28 19:37
Duplicate of #738 #1011 #572 #497, #1109, #3565, #1187, #1412.  This was supposed to be fixed in #1442, I'm not sure why that fix isn't executing.

**Comment by tresf** [comment] 2018-02-28 19:40
@tukkek please do the following:
* If you have an old version of LMMS installed, please load it up and remove the "theme" setting in the preferences and relaunch again to get it to reset to default.
* Try the AppImage again

If you can reliably reproduce the glitch, send us the `.lmmsrc.xml` file and we'll see why the theme logic is breaking.

If you cannot reliably reproduce the glitch, we'll have to assume that something non-standard happened and we'll mark as duplicates of the rest.

This may be an order of operations bug as well where the theme folder isn't updated until after the UI starts loading.  It may be a regression.

**Comment by Umcaruje** [comment] 2018-03-01 09:41
>This may be an order of operations bug as well where the theme folder isn't updated until after the UI starts loading.

I think this is probably the problem, because next time you open up LMMS the theme folder is properly set. 

You can reproduce this by installing LMMS from a repository, and then running the AppImage. First time around the theme is broken, when you close and open the appimage again, the theme is properly set.

**Comment by tresf** [comment] 2018-03-01 16:13
@Umcaruje thanks for confirmation.  I need help here.  @lukas-w is this just a matter of calling `ConfigManager::inst()->upgrade()` before we use it?  If that's the case, shouldn't we upgrade in the constructor?  There's some order of operations issue happening and it will affect all settings upgrades until it's corrected, I'm just not sure where to start.

**Comment by tresf** [comment] 2018-03-01 17:26
Ok, found it... [`src/core/ConfigManager.cpp#L59`](https://github.com/LMMS/lmms/blob/7c71bc657c34b2722f247e4820000c5e46f4d05f/src/core/ConfigManager.cpp#L59), we're initializing `m_version` and it's never making it inside any of the `upgrade()` steps.  I'll force it to something bogus on init to see how well it works.

**Comment by tresf** [comment] 2018-03-01 18:00
Nope, that was wrong... I think I found it... 

```cpp
	QStringList searchPaths;
	if(! qgetenv("LMMS_THEME_PATH").isNull())
		searchPaths << qgetenv("LMMS_THEME_PATH");
	searchPaths << artworkDir() << defaultArtworkDir();
	QDir::setSearchPaths( "resources", searchPaths);

	// Create any missing subdirectories in the working dir, but only if the working dir exists
	if( hasWorkingDir() )
	{
		createWorkingDir();
	}

	upgrade();
```

We're calling and thus populating our `searchPaths` before running upgrade.  It should be the other way around.  I threw in a `Q_ASSERT` and now I clearly see that `artworkDir()` gets called **BEFORE** `upgrade()` and I can't see it getting called again afterward.

I'm not entirely sure how moving `upgrade()` above that will impact the software though.  I'll make an attempt, but @lukas-w I'd appreciate a second set of eyes as I believe you rewrote this stuff.

**Comment by Anonymouqs** [comment] 2018-03-01 18:35
Just happened today, this glitch also happens in Mac. I was running Stable-1.2 RC5 and the exact same thing happened when I ran it for the first time.

**Comment by tresf** [comment] 2018-03-01 19:09
@Anonymouqs do you run multiple simultaneous versions on Mac?

**Comment by tresf** [comment] 2018-03-01 22:58
PR available at #4206.  Testing appreciated.

**Comment by zonkmachine** [comment] 2018-03-01 23:09
Tested. That made the trick!

LinuxMint 17.3, Switching between 1.1.3 and 1.2.0 with no gui glitches. Pretty!

**Comment by tresf** [comment] 2018-03-02 01:35
Great, thanks for testing.  I've taken a second look an the logic which now comes after the `upgrade();` call doesn't appear like it will negatively affect any other part of the loading process, so I'll merge this.

**Closed** 2018-03-02 01:37 UTC
