### ISSUE TITLE
Improve Loop export - mix the tail onto the beginning of the track

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#3020] opened 2016-09-05 14:25 UTC
Hey!

One think I have to do manually when exporting loops from LMMS is mixing the tail of the track onto it's start, so when it loops, the tail doesn't cut off badly.

LMMS could do this automatically:

1. Export the whole track from start until the last sound fades out.
2. Calculate from the tempo where the last bar ends and cut right after that
3. Paste and mix the cut part onto the beginning of the track

Once played - this should loop seamlessly.

What do you think?

This could be particularly useful when combined with batch multiple-region export. This could be a great tool for making game music based on loops.

**Comment by tresf** [comment] 2016-09-05 14:30
Duplicate of #1484

**Closed by tresf** 2016-09-05 14:30 UTC
Labels: duplicate
