### ISSUE TITLE
Midi keyboard working in style of the normal keyboard

### ISSUE THREAD

**Issue by Devix167** [LMMS/lmms#3185] opened 2016-12-28 02:32 UTC
BEFORE YOU READ: Im new to github and all this so dont be mad if i screw up 😄 

I hate having to re assign the midi keyboard just to play a different instrument. can midi keyboards work like a normal keyboard? like a settings in the menu or something? 🎹

**Comment by tresf** [comment] 2016-12-28 03:53
@Devix167 is there a chance you're request is similar to these?

#1189 #1781 #1918 #1942 (parent bug report: #1472)

**Comment by Devix167** [comment] 2016-12-28 03:57
@tresf 
Sorry about that. I did numerous searches and none of these came up.

**Comment by tresf** [comment] 2016-12-28 06:34
> Sorry about that. 

No apology necessary; needle in a haystack.  Closing as duplicate of #1472.

**Closed by tresf** 2016-12-28 06:34 UTC
Labels: duplicate
