### ISSUE TITLE
LMMS convolution reverb plugin

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2167] opened 2015-07-07 00:06 UTC
LMMS could use a built in convolution reverb plugin AKA impulse reverb, this is for those who don't want to download extra plugins.

**Comment by softrabbit** [comment] 2015-07-07 05:37
Duplicate of #641, please continue that discussion instead of starting a new one.

**Closed by softrabbit** 2015-07-07 05:37 UTC
Labels: duplicate

**Comment by Reaper10** [comment] 2015-07-07 15:55
sorry I did see that closed
