### ISSUE TITLE
1.3 alpha, Click below open vst plugin

### ISSUE THREAD

**Issue by Strantrickt** [LMMS/lmms#5964] opened 2021-03-25 16:30 UTC
![IMG_20210325_192556](https://user-images.githubusercontent.com/55962567/112508168-5d07ad00-8da0-11eb-9dbc-3e3227104e80.jpg)

When ı was clicked

**Comment by IanCaio** [comment] 2021-03-25 22:33
I'm going to have to close this issue. There are not enough details to reproduce the crash and the error message screenshot is in another language.

**Closed by IanCaio** 2021-03-25 22:33 UTC
Labels: bug

**Comment by Spekular** [comment] 2021-03-26 14:53
Via convo on Discord, this is about the crash that occurs when pressing the wrench icon on VSTs. I thought we had an open issue for this, but since I can't seem to find one I've opened #5966.
