### ISSUE TITLE
Piano-Roll wrong behavior with single note creation, when "last note" mode turned off.

### ISSUE THREAD

**Issue by healingdrawing** [LMMS/lmms#5397] opened 2020-02-19 20:38 UTC
### Bug Summary
Piano-Roll created notes get the velocity of last touched notes even if "last note" mode turned off. In same time the note length on time scale as expected have determined size. 1/32 1/16 etc.
#### Steps to reproduce
- create two notes
- first note velocity 100%
- second note velocity 80% etc
- turn off "last note" size in settings, uses length 1/32 1/16 etc, as you wish
- now notes must not clone last note touched , because "last note" mode not used
- touch 100% velocity note uses lmouse click
- create new note in empty space -> the note will have 100% velocity
- touch 80% velocity note uses lmouse click
- create new note in empty space -> at this time note will have 80% velocity
#### Expected behavior
Independant of last (lmouse clicked) touched notes the new note have 100% velocity or last velocity cloned before "last note" mode was turned off last time.
#### Actual behavior
Shadow cloning last (lmouse clicked) touched note velocity , but note size as in settings 1/32 1/16 etc(which is correct , because "last note" turned off).
#### LMMS version used
Version 1.2.1 (Linux/x86_64, Qt 5.9.7, GCC 4.8.4)
[AppImage]
#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by Spekular** [comment] 2020-02-19 22:26
Not a bug, IMO. That dropdown is for selecting note length, as such it doesn't affect other properties of the note.

**Comment by Spekular** [comment] 2020-02-19 22:31
To clarify/elaborate: there's no "last note mode". The existence of such a mode seems to be the basis for your report, but "last note" is simply an option when selecting note length.

**Comment by musikBear** [comment] 2020-02-21 14:27
@Spekular oh *last-note* does indeed preserve everything, length *and* velocity, but in contradiction to oop, the feature works flawlessly
@healingdrawing LMMS preserves the settings last *made*!
Try this:
* In piano-roll set to *last-note*
* insert 3 notes
* for last note, drag the velocity-slide-bar to 30%
* Change *last-note* to ½ note
* insert a note

LMMS inserts a ½note with 30% velocity, because *that* is the *last* setting that was valid before you switched to *fixed-note* (½note)
That is as expected and also as wanted.
Not bug -Feature

**Comment by Spekular** [comment] 2020-02-22 12:04
Closing, as this is intended (and sensible) behavior. If any other devs disagree, feel free to reopen.

**Closed by Spekular** 2020-02-22 12:04 UTC
Labels: bug, invalid
