### ISSUE TITLE
32000 hz Export 

### ISSUE THREAD

**Issue by smokedawg17** [LMMS/lmms#1900] opened 2015-03-24 11:47 UTC
I have been doing allot of research in frequencies and sample rates and it is vital for me to be able to export my files in 32 khz without me having to resample my files. It would be much appreciated for this feature to return to LMMS as i use zynthsubfx to tune to 432 A4 with pythagorean scale at 32 khz for quartz crystal experiments. Thank you in advance

**Comment by tresf** [comment] 2015-03-24 12:51
We don't get too many requests for audio quality enhancements, and this is the first I've seen that requests something less than CD quality (44 Khz, 48 Khz, etc).

I'm sure you have some very valid reasoning, but can you give us a bit of a background so that we understand your needs a bit more?

It appears [Zyn has 32 Khz support](https://github.com/LMMS/lmms/blob/master/plugins/zynaddsubfx/zynaddsubfx/src/UI/ConfigUI.fl#L77) but we'll have to add it to [this area (ExportProjectDialog.cpp#L256)](https://github.com/LMMS/lmms/blob/master/src/gui/ExportProjectDialog.cpp#L256) so make it available in our GUI.  Not sure if this is the only location and what all this impacts.... 

If you don't mind me asking, what platform are you on?  Linux, Windows or Mac?  If Linux, this may be something worth changing and compiling on your own to provide some feedback.



-Tres

**Comment by diizy** [comment] 2015-03-24 13:45
Sorry but not going to happen. Too much trouble for very little benefit. Many (actually probably almost all) filters will malfunction if the sample rate is below 44.1k, as well as many LADSPA effects. Coding in exceptions for these cases would require too much code that would have very little applicability in any non-niche use cases.

LMMS is not designed for quartz crystal experiments. I'd recommend you to use some MIDI sequencer with Zyn running as a standalone program, then you'll be able to set its output samplerate to whatever you want.

**Comment by smokedawg17** [comment] 2015-03-24 14:26
Interesting. Radio broadcasting uses 32khz because the wave length travels farther distances and scientific studies for electromagnetic bacteria treatments (kill bacteria) the human body permits the wave to travel at 32 khz rather then stopping close to the contact. I have gone through great trials and studies to discover the magic in music and it is in tuning your A4 to 432 hz, scaling your notes according to pythagorean ratios, and for computer generated sounds the human body resonates best at 32 khz sample rate as well as being used in radio broadcast. If you are serious about your application i would make it a priority as well as investigate customizing sample rate such as subsynth setting for more research in this sound.

**Comment by smokedawg17** [comment] 2015-03-24 14:31
I am on windows by the way.

**Comment by diizy** [comment] 2015-03-24 16:49
>> If you are serious about your application i would make it a priority

Well the thing is, we're serious about our application, but the purpose of the application is making music, and your use case is extremely niche - you're literally the only person who's ever mentioned this kind of use case for LMMS. So we can't really make your needs a priority, if meeting those needs causes problems for our other, more pressing needs.

>> Radio broadcasting uses 32khz because the wave length travels farther distances and scientific studies for electromagnetic bacteria treatments (kill bacteria) the human body permits the wave to travel at 32 khz rather then stopping close to the contact.

Ok, I think you got some things mixed up here. Firstly, radio signals do not have a sample rate, they use analog signals, which don't have a sample rate because the wave is continuous, not discrete, thus doesn't contain any "samples" at all so can't have a sample rate. Sample rate, as a term, only applies to digital signals.

Also, the sample rate of a digital signal only affects the highest possible frequency that can be coded in that signal. If your signal's sample rate is 32KHz, that means the highest reproducible frequency in that signal is 16KHz. A 44.1KHz signal can contain frequencies up to 22.05KHz, so a 44.1k signal can actually contain any sound that a 32k signal can contain. 

The "human body" can't "resonate at a 32 khz sample rate" because once the sound comes out of your speakers, it does **not have a sample rate**, because again, sample rate does not apply to analog signals, only digital ones. The only difference in a 32khz and 44.1khz signals, once they come out your speakers, is that one can contain higher frequencies than the other.

However, If you want to produce *sounds that are 32khz in frequency*, that just means that you need to have a sample rate higher than 64khz - any sample rate that is higher than 64khz will do.

Further reading:

http://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem

**Comment by smokedawg17** [comment] 2015-03-24 18:31
I appreciate your time to respond, as i look indeed it is said 32 kHz is for transmission related application. Sample rates are relative for creating time dependent signals which effect the aliasing of the sound weather or not sound has a sample rate once it comes out the speaker. I do not mind if you do not wish to include this feature as i have AV linux installed on a usb key with ardour precompiled with vst support to do my personal work and music, but i hope you as a group consider sample rates something more than "any sample rate that is higher than 64khz will do". I wish you all the best, great job on lmms i love it, cant wait to see your future development.

**Comment by diizy** [comment] 2015-03-24 20:20
If you want to create signals without aliasing, you can just use bandlimited waveforms, which Zyn can produce just fine on any sample rate. I still don't really see any reason why you'd necessarily have to use 32khz sample rate...

Anyway, there's currently too many places in the code that depend on the minimum sample rate being 44.1k. Filters, many effects, etc. break down if that assumption is broken. And especially since no one else has ever requested lower sample rates, it's simply not in our best interest to implement. So I'm afraid I'm going to have to close this as won't-fix...

**Closed by diizy** 2015-03-24 20:20 UTC

**Comment by unfa** [comment] 2015-03-30 14:38
That was one of the strangest discussions I ever heard in LMMS community.
No offence :)

As for exploring the science and fixing the common misconceptions about
digital sound (and digital signals at all) I highly recommend a brilliant
short film by Monty Montgomery of Xiph.Org (creators of Ogg Vorbis, FLAC,
Theora and Opus) titled "Digital Show & Tell".

I even made Polish subtitles for it (to prove my love for it):

https://xiph.org/video/vid2.shtml

Best with your music and exploration :)

**Comment by tresf** [comment] 2015-04-05 00:43
@unfa thanks for the link.  Just watched it. :). These types of resources would be nice to gather and offer as resources (or link to a centralized location for these types of things)
