### ISSUE TITLE
Removing a ZynAddSubFX track causes a segmentation fault

### ISSUE THREAD

**Issue by x16x16** [LMMS/lmms#2397] opened 2015-10-02 14:09 UTC
LMMS 1.1.3 (Linux i386, Qt 4.8.6, GCC 4.8.4) on Ubuntu 14.04.3 LTS.
```
Program received signal SIGSEGV, Segmentation fault.
0xb7355bcb in QObject::~QObject() ()
   from /usr/lib/i386-linux-gnu/libQtCore.so.4
(gdb) backtrace
#0  0xb7355bcb in QObject::~QObject() ()
   from /usr/lib/i386-linux-gnu/libQtCore.so.4
#1  0x08215e76 in Engine::~Engine() ()
#2  0xa5b875ee in NulEngine::~NulEngine() ()
   from /home/myusername/lmms/lmms/build/plugins/libZynAddSubFxCore.so
#3  0xa5b8763c in NulEngine::~NulEngine() ()
   from /home/myusername/lmms/lmms/build/plugins/libZynAddSubFxCore.so
#4  0xa5b32a11 in LocalZynAddSubFx::~LocalZynAddSubFx() ()
   from /home/myusername/lmms/lmms/build/plugins/libZynAddSubFxCore.so
#5  0xa5ba5fd8 in ZynAddSubFxInstrument::~ZynAddSubFxInstrument() ()
   from /home/myusername/lmms/lmms/build/plugins/libzynaddsubfx.so
#6  0xa5ba615c in ZynAddSubFxInstrument::~ZynAddSubFxInstrument() ()
   from /home/myusername/lmms/lmms/build/plugins/libzynaddsubfx.so
#7  0x081f43e4 in InstrumentTrack::~InstrumentTrack() ()
#8  0x081f45bc in InstrumentTrack::~InstrumentTrack() ()
#9  0xb734f553 in qDeleteInEventHandler(QObject*) ()
   from /usr/lib/i386-linux-gnu/libQtCore.so.4
#10 0xb7355720 in QObject::event(QEvent*) ()
   from /usr/lib/i386-linux-gnu/libQtCore.so.4
#11 0xb76287f4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/i386-linux-gnu/libQtGui.so.4
#12 0xb762f2d3 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/i386-linux-gnu/libQtGui.so.4
---Type <return> to continue, or q <return> to quit---<return>
#13 0xb733be4a in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/i386-linux-gnu/libQtCore.so.4
#14 0xb733f70d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#15 0xb733fc1c in QCoreApplication::sendPostedEvents(QObject*, int) ()
   from /usr/lib/i386-linux-gnu/libQtCore.so.4
#16 0xb736c23e in ?? () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#17 0xb680d1e3 in g_main_context_dispatch ()
   from /lib/i386-linux-gnu/libglib-2.0.so.0
#18 0xb680d468 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#19 0xb680d528 in g_main_context_iteration ()
   from /lib/i386-linux-gnu/libglib-2.0.so.0
#20 0xb736b93b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#21 0xb76dd60e in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#22 0xb733a823 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#23 0xb733ab49 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/i386-linux-gnu/libQtCore.so.4
#24 0xb73408fe in QCoreApplication::exec() ()
   from /usr/lib/i386-linux-gnu/libQtCore.so.4
#25 0x080b9135 in main ()
```

**Comment by grejppi** [comment] 2015-10-02 15:10
Duplicate of #2049.

**Closed by grejppi** 2015-10-02 15:10 UTC
