### ISSUE TITLE
Allow sample tracks to go to the FX-Mixer

### ISSUE THREAD

**Issue by musiczboy** [LMMS/lmms#5620] opened 2020-08-10 22:19 UTC
I don't know if this has been fixed yet, but for some reason I can't link my sample tracks to any FX-Mixer and this is really important to me. Please add this feature because other users are having problems with this.

**Comment by qnebra** [comment] 2020-08-10 22:44
Fix is already in "master" branch.

**Comment by musiczboy** [comment] 2020-08-11 00:08
> Fix is already in "master" branch.

Can you show me by screenshot or video?

**Comment by musiczboy** [comment] 2020-08-11 00:11
I have 5 different sample tracks and I need 5 different FX-Mixer to mix and I don't want to master my whole track down. How do you do that?

**Comment by qnebra** [comment] 2020-08-11 01:03
> I have 5 different sample tracks and I need 5 different FX-Mixer to mix and I don't want to master my whole track down. How do you do that?

I refer "master" as branch in lmms Git repository.

![image_2020-08-11_030008](https://user-images.githubusercontent.com/11295229/89845440-c377ec00-db7e-11ea-85bc-58266c02165a.png)

This was not in 1.2 because this patch landed in repository after 1.2 was "feature frozen", with only bugfixes allowed in 1.2

**Comment by SecondFlight** [comment] 2020-08-11 03:33
This is indeed implemented in master in #3866. Closing as a duplicate of #133.

**Closed by SecondFlight** 2020-08-11 03:33 UTC
Labels: enhancement

**Comment by musiczboy** [comment] 2020-08-11 14:10
> > I have 5 different sample tracks and I need 5 different FX-Mixer to mix and I don't want to master my whole track down. How do you do that?
> 
> I refer "master" as branch in lmms Git repository.
> 
> ![image_2020-08-11_030008](https://user-images.githubusercontent.com/11295229/89845440-c377ec00-db7e-11ea-85bc-58266c02165a.png)
> 
> This was not in 1.2 because this patch landed in repository after 1.2 was "feature frozen", with only bugfixes allowed in 1.2

Can you show me how to do this step by step using screenshots?

**Comment by Spekular** [comment] 2020-08-11 14:37
@musiczboy this isn't available in any released version, so you can't do this without installing an unstable version of LMMS. If you do, there's no guarantee that everything will work correctly.

If you still want to do it, go to [this comment](https://github.com/LMMS/lmms/pull/5601#issuecomment-665750723) and download the relevant installer for your OS. I recommend installing the new version to a separate directory from your current installation so you can easily switch back if you need to.

**Comment by musiczboy** [comment] 2020-08-11 21:37
> @musiczboy this isn't available in any released version, so you can't do this without installing an unstable version of LMMS. If you do, there's no guarantee that everything will work correctly.
> 
> If you still want to do it, go to [this comment](https://github.com/LMMS/lmms/pull/5601#issuecomment-665750723) and download the relevant installer for your OS. I recommend installing the new version to a separate directory from your current installation so you can easily switch back if you need to.

I cant' find the download. Send me screenshot of where the download is.

**Comment by SecondFlight** [comment] 2020-08-11 21:50
Click on the arrow

**Comment by musiczboy** [comment] 2020-08-11 22:59
> Click on the arrow

I can't find the arrow. Screenshot it so I know where it is and i'm sorry if i'm bothering you because i'm new to github.

**Comment by SecondFlight** [comment] 2020-08-12 14:56
![image](https://user-images.githubusercontent.com/6700184/90030802-7a14c300-dc8a-11ea-975f-36c124e8c338.png)

**Comment by SecondFlight** [comment] 2020-08-12 14:59
![image](https://user-images.githubusercontent.com/6700184/90031087-d5df4c00-dc8a-11ea-8c7b-ca9b074038af.png)

**Comment by Spekular** [comment] 2020-08-12 15:01
Actually, I'd click the .AppImage.exe/.dmg rather than the build link. That gets you a direct download.

**Comment by SecondFlight** [comment] 2020-08-12 15:13
Thanks @Spekular, I've updated the screenshot :)

**Comment by musiczboy** [comment] 2020-08-12 21:28
@SecondFlight @Spekular @qnebra @jmuzz Thanks for your help. Y'all are very kind.

**Comment by musiczboy** [comment] 2020-11-30 18:53
@SecondFlight The download link for the pull request isn't working anymore. Do you know another way to download it?

> 
![image](https://user-images.githubusercontent.com/69486327/100651418-5068d000-333d-11eb-9b3c-79e05146f5da.png)

**Comment by Spekular** [comment] 2020-11-30 18:59
@musiczboy check the same comment on any recently merged PR, or wait a few days until the 1.3 alpha releases.
