### ISSUE TITLE
Request to manipulate MMPZ files to correct VST location paths.

### ISSUE THREAD

**Issue by kriskropd** [LMMS/lmms#4920] opened 2019-03-30 05:18 UTC
MMPZ files seem to store both the parameters for VSTs used as well as a path to those VSTs. However, LMMS doesn't recognize a filter VST if the path in .mmpz file does not match the current existing path for the VST on host. We need to be able to substitute old paths for VST filters (and also instruments) in .mmpz files to match our new locations for said VSTs.

This seems like it should be done with a simple sed command, but alas .mmpz files seem to be data that can't easily be manipulated.

LMMS 1.2.0-rc7 (and relevant for any .mmpz files made with a prior version)

**Comment by PhysSong** [comment] 2019-04-01 13:30
Duplicate of #4646.

**Closed by PhysSong** 2019-04-01 13:30 UTC

**Comment by PhysSong** [comment] 2019-04-02 01:56
Oops, it isn't a duplicate...
Anyway, you can save the file with `.mmp` extension and then edit it like any other XML files.
