### ISSUE TITLE
not work DPI ( not DPI | windows 10)

### ISSUE THREAD

**Issue by LVitall** [LMMS/lmms#2640] opened 2016-03-06 10:38 UTC
Hi,
windows 10
not work DPI ( not DPI )

thanks

**Comment by liushuyu** [comment] 2016-03-06 11:45
>Hi,
>windows 10
>not work DPI ( not DPI )

What did you mean? Did you mean the poor support of HiDPI (High DPI) ?

**Comment by LVitall** [comment] 2016-03-06 11:58
I have two monitors. And video DPI does not work. (very little size of chars in words and buttons) But I found the solution, windows allows you to disable DPI for one of the monitors. In General the problem is solved. But in LMMS is better to do at the software level

**Comment by Umcaruje** [comment] 2016-03-06 15:48
Duplicate of #2510

**Closed by Umcaruje** 2016-03-06 15:48 UTC
Labels: duplicate
