### ISSUE TITLE
Read user files more frequently

### ISSUE THREAD

**Issue by x16x16** [LMMS/lmms#2414] opened 2015-10-16 16:20 UTC
I was wondering if it's possible to re-read the home directory more frequently ‒ not only when LMMS is opened, but also on project load or every time the "My home" menu is called.

**Comment by tresf** [comment] 2015-10-16 17:56
@x16x16, not yet.

This is a duplicate of #2156, marking as such.

**Closed by tresf** 2015-10-16 17:56 UTC
Labels: duplicate
