### ISSUE TITLE
Mallets segfault when stk is not installed

### ISSUE THREAD

**Issue by teeberg** [LMMS/lmms#1660] opened 2015-01-20 05:13 UTC
I wrongly reported this in #1649, but it is indeed unrelated (my bad!).

On current master, installing `libstk0-dev` makes cmake succeed, saying that Stk Mallets are "OK", yet trying to add them to the Song Editor will cause a segfault. Additionally installing the package `stk` (in Ubuntu) fixes the problem.

Commit 1ba308855 on stable-1.1 mitigates the situation a little, but it would need merging into master. Also, it only reports that it can't find files when opening the instrument dialog. And also when closing it. I'd find it more intuitive if it gave one single warning right after adding it to the song editor.

**Comment by tresf** [comment] 2015-01-20 13:03
Thanks.  So what exactly are the steps to reproduce, just `sudo apt-get remove stk` ?

**Comment by diizy** [comment] 2015-01-20 15:04
On 01/20/2015 07:13 AM, Jonas Trappenberg wrote:
>
> I wrongly reported this in #1649
> <https://github.com/LMMS/lmms/issues/1649>, but it is indeed unrelated
> (my bad!).
>
> On current master, installing |libstk0-dev| makes cmake succeed,
> saying that Stk Mallets are "OK", yet trying to add them to the Song
> Editor will cause a segfault. Additionally installing the package
> |stk| (in Ubuntu) fixes the problem.
>
> Commit 1ba3088
> <https://github.com/LMMS/lmms/commit/1ba3088554edf3e2e830ef84992e64a7e85e55ea>
> on stable-1.1 mitigates the situation a little, but it would need
> merging into master. Also, it only reports that it can't find files
> when opening the instrument dialog. And also when closing it. I'd find
> it more intuitive if it gave one single warning right after adding it
> to the song editor.
>

Seems like a distro problem to me. libstk-dev should automatically pull
stk as well.

**Comment by teeberg** [comment] 2015-01-21 03:39
`libstk0-dev` installs all the headers into `/usr/include/stk`, whereas `stk` populates `/usr/share/stk/{rawwaves,tcl}`. I imagine one is for the developer, one for the user.

There is also a third package `libstk0c2a` that both other packages depend on.

I think the best UI for this would be to check for the `/usr/share/rawwaves` directory as part of the configure as well. When cmake says "OK", I would expect it to work without any further doings on my side.

**Comment by diizy** [comment] 2015-01-21 09:14
On 01/21/2015 05:39 AM, Jonas Trappenberg wrote:
>
> |libstk0-dev| installs all the headers into |/usr/include/stk|,
> whereas |stk| populates |/usr/share/stk/{rawwaves,tcl}|. I imagine one
> is for the developer, one for the user.
>

Yes, but the dev-package should pull the main user package as a
dependency. You can't do anything with just the headers.

Still looks like a distro problem to me.

**Comment by tresf** [comment] 2015-03-08 08:00
Marking as won't-fix based on Vesa's remarks.

Please reopen if you feel this was closed in error.

**Comment by teeberg** [comment] 2015-03-08 20:02
According to the ubuntu package descriptions, [stk](http://packages.ubuntu.com/precise/sound/stk) provides example applications whereas [libstk0-dev](http://packages.ubuntu.com/precise/sound/libstk0-dev) provides the development headers. I don't understand why the headers would pull in example applications if you don't need them for development. Since you have a deeper understanding of how the development headers are to be used, if you think this is problematic, I would really appreciate if you could file this upstream.

All I see as a user is that LMMS assumes that some files exist because some other files exist and segfaults as a consequence. In my opinion, that is a bad user experience. Also one that could probably be fixed easily.

**Comment by tresf** [comment] 2015-03-08 21:10
If you have a patch to submit to make the experience better for our users, we'll take it.

This isn't the first "chicken vs. egg" scenario and it is likely not our last.  Just submit the PR and we'll review and di right on this.

I'd your research discovers this IS and upstream bug, please file on our behalf.

**Comment by zonkmachine** [comment] 2015-06-03 06:40
This is a real bug. Lmms goes down bad when trying to drop 'Mallets' into your project if you lack stk.

> So what exactly are the steps to reproduce, just sudo apt-get remove stk ?

Remove stk and then drag-and-drop Mallets in your project.

I went 'git bisect' on this and found a possible culprit:
7588f235ee158f782bf3f687bce53dc9ad079d95 is the first bad commit

The messages I get when running 7588f235ee158f782bf3f687bce53dc9ad079d95 from the terminal and trying to drag Mallets onto the Song window varies.

    QPixmap: It is not safe to use pixmaps outside the GUI thread
    lmms: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0. 
    dagon@dagon:~/builds/lmms$ 

And

    QPixmap: It is not safe to use pixmaps outside the GUI thread
    [xcb] Unknown request in queue while dequeuing
    [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
    [xcb] Aborting, sorry about that.
    lmms: ../../src/xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq'        failed.
    Aborted (core dumped)

**Comment by zonkmachine** [comment] 2015-06-12 00:06
@tresf I think this bug should be reopened.
 @curlymorphic Yo! My bisecting activities of last week hints that there may be some issues with pull request #1557

**Comment by curlymorphic** [comment] 2015-06-12 00:23
Pull request #1557 loads instruments asynchronously to stop race conditions. As a result Instruments cant access the ui while loading, maybe this bug could be handled better by moving gui code from Mallets loader. I will take a look when i have time.

**Comment by tresf** [comment] 2015-06-12 01:40
> @tresf I think this bug should be reopened.

Fair enough. :)

**Closed** 2015-06-12 21:09 UTC
Labels: bug, wontfix
