### ISSUE TITLE
Tempo is unchangeable after importing a MIDI file

### ISSUE THREAD

**Issue by danpla** [LMMS/lmms#2482] opened 2015-12-11 13:13 UTC
After importing a MIDI file, the project tempo is set to the tempo of the imported MIDI file and cannot be changed in any way. You can adjust the value during the playback, but every time you press the Play button or Space, it resets back again. Even reopening the project in restarted LMMS doesn't helps.

Steps to reproduce:
1. Check the tempo of an any MIDI file. Import it in a new LMMS project via double click on the Side Bar. The MIDI is added in Note Editor with Sf2 Player and the project tempo is currently set to default (140).
2. Click Play button or Space. As you see, the tempo is changed to the value from the MIDI file.
3. Stop playback and change the tempo. Play again — it still resets.

LMMS 1.1.3, Ubuntu 14.04 x86-64

**Comment by tresf** [comment] 2015-12-11 13:24
May be a duplicate of this:  https://github.com/LMMS/lmms/issues/403

**Comment by danpla** [comment] 2015-12-11 13:37
Ah, exactly — it's a hidden autotrack in the tempo. #403 is very appropriate.

Sorry for that.

**Comment by tresf** [comment] 2015-12-11 13:38
@danpla no worries.  It's a crappy "feature".  :+1: Closing as duplicate.

**Closed by tresf** 2015-12-11 13:38 UTC
Labels: duplicate
