### ISSUE TITLE
redesign of the track view in song editor

### ISSUE THREAD

**Issue by Rossmaxx** [LMMS/lmms#6411] opened 2022-05-22 12:39 UTC
### Enhancement Summary
while going through some random issues, got some ideas and made a concept of my own. it's not really unique but looks like a nice change.
- changed track height to roughly twice of the original height (not really needed but will get more head room to add stuff).
- added mixer routing (when it comes) and pattern specific volume and pan controls
- stacked some stuff which are originally located side by side (mute/solo, vol and pan(also removed labels))
- changed the settings icon to a triple dot dropdown button (see the discussion #4217)
feel free to drop your opinions and comments.
#### Mockup
![track ui redes 2](https://user-images.githubusercontent.com/74815851/169695267-f2e7b9a3-1bab-4262-bbf5-f496941a4876.JPG)
sorry for the pixelated text and stuff because in that zoom, gimp pixelated the text. also gimp's paintbrush didnt work so had to use ms paint.

**Comment by musikBear** [comment] 2022-05-22 14:05
Duplocate -All has been suggested before:
context: https://github.com/LMMS/lmms/issues/4217
mixer-estate https://github.com/LMMS/lmms/issues/355#issuecomment-87745447 -amo
Stacked diodes .. Cant find it, but i made it..

**Comment by Monospace-V** [comment] 2022-05-22 14:41
Triple dot and drag handle could be confused. Also, dots give the impression of clickable area for control being rather thin.


The Mixer routing option seems very useful, though. (Perhaps, this, but also viewing FX routing editable on/off, when length of SE track name info can be adjusted manually? I'd love that, that'd be the summit of control.) Then would we move "Add to new FX channel" from the context menu to the channel routing display instead? (And, when connection of mixer buses to tracks is done, an "Assign and connect to new channel" button, or a "connect to channel button".)


The thing is, if we extend the height of track and add space for more information, then.. what information can be added? More importantly, what if there are multiple secondary informations, each of which is of more or less equal use, then which do we add? It seems like an addition that would require debate. What sort of information would a person want to see on the track, that pertains to it in the SE the same way the track name does? It's not a bad idea, but is there any such thing?

Looking around,

DAWs like Reaper have the option to directly display the GUI of the instrument, since in Reaper's case it works only with external instruments and has no instruments of its own, the ability to turn recording on, edit automation envelopes of parameters (there's very few other ways to do this), and Invert Phase (possible through Stereo Matrix in LMMS, but I'd love to see an option for this one day). And the usual volume, mute, solo, and track name. (No panning, although, upon selecting the track, pan and volume gain information is displayed.)
![image](https://user-images.githubusercontent.com/76674645/169699218-867993b7-2027-4f9c-baa1-188c4f7065fb.png)
Now, the thing is, nobody would approach Reaper without documentation and/or experience (experience is optional, documentation can be replaced by recklessness, but in general you're going to need to look basic things up in a lot of cases. LMMS is amazing in the sense that occasionally I might need to look up some terms, but it is possible and _easy_ to learn without the documentation open in a browser). A lot of things in Reaper are unclear or implied. If the huge green button allows me to edit the instrument/synth itself, why does it have a huge on/off button and "FX" written on it? Wouldn't it have been clearer to write "Instrument" below the button too?
Without "PAN" clearly written, the panning knob is one the user wouldn't understand unless they hovered over it- in LMMS's case, for a whole second and a half. The pan knob is just another percentage-based knob that for some reason is in the centre by default instead of full left.
I don't think experienced users realise, just how little sense the word "PAN(ning)" makes. But no word makes even lesser sense.
At least the first controls the user sees, should have their purposes clear. All of this may be logical, but logical != intuitive.

Zynewave Podium:
Gain and Pan (with no info, but very fast hover-sensitive tags), solo, mute, record, minimize (now this. If LMMS ever does this, it'd be cool if all tracks could be minimized. Since track height can already be edited with Shift-Drag, then if the default view was minimised, with minimal information like now being shown when minimised but more information being shown on larger sizes-). Control of which VST is being used, which FX are being used, and audio input to be used, if any.
![image](https://user-images.githubusercontent.com/76674645/169699185-e172abf0-7e8b-4205-8d67-11be27473a3d.png)
In Podium, it's a bit more obvious that sound is being panned left or right- instead of a knob, it's a slider, and 0 is "C" and moving the slider says "L27" or "R84" etc. Not to mention how hovering immediately displays the word "Pan" and the exact number, without a delay. But with an interface structured like LMMS' is, the word PAN is useful.

![image](https://user-images.githubusercontent.com/76674645/169699391-f83e8996-a2ad-4549-8aae-c9fdea347d65.png)
_(Minimized.)_

Audacity:
![image](https://user-images.githubusercontent.com/76674645/169700583-e15b74de-636a-4de8-873c-f8ccac7b809e.png)
Same controls as LMMS. Extra details include, due to the nature of Audacity as an audio editing app, the data of the audio concerned (Stereo, samplerate, bit depth).

It's worth noting that, in Podium and Reaper, each instrument track is automatically connected to a Mixer bus, and volume and pan and Mute/Solo controls etc are connected too. So, there is quite a bit of unnecessary information and parameters. I wouldn't call these controls redundant per se, but they're extra.
I don't have FL Studio, but I understand it's pretty minimalistic.
imo labels for simple stuff like mute, solo, volume panning is only somewhat important, but panning especially. For anyone who is used to the interface or to making music it's good, but for beginners, the one thing worse than having a knob named "PAN" that doesn't make much sense, is having an unnamed knob that makes no sense.
Personally, I don't see a point in getting rid of the labels, nor do I see the sense in getting rid of them specifically in what is an _expanded_ view.
As for the extra information, nowhere do I see any more information that makes sense in LMMS, or that is actually useful. Perhaps channel routing details, but that'd just confuse the user as so to why the parameters and the info right below it don't affect each other.

(I still think the coolest thing is our instrument preview button. Not many other DAWs have that. I believe FL has something similar, but nowhere else have I seen this.)

**Comment by Rossmaxx** [comment] 2022-05-22 15:42
> dots give the impression of clickable area for control being rather thin.

How about adding a boundary around the triple dots menu (maybe that can indicate that it is a clickable menu and not a drag and drop area)

> The thing is, if we extend the height of track and add space for more information, then.. what information can be added? More importantly, what if there are multiple secondary informations, each of which is of more or less equal use, then which do we add?

That's left for debate. 

>Without "PAN" clearly written, the panning knob is one the user wouldn't understand unless they hovered over it- in LMMS's case, for a whole second and a half. The pan knob is just another percentage-based knob that for some reason is in the centre by default instead of full left.

The solution to this one can be modifying the knob hover tooltip to the one similar to podium's slider tooltip

>0 is "C" and moving the slider says "L27" or "R84" etc. Not to mention how hovering immediately displays the word "Pan" and the exact number, without a delay.

This as a hover tooltip for pan

> But with an interface structured like LMMS' is, the word PAN is useful.

You are absolutely correct here.
So the word pan can be kept.

> Personally, I don't see a point in getting rid of the labels, nor do I see the sense in getting rid of them specifically in what is an expanded view.

I thought of removing them for real estate (which is getting wasted in my design as of now anyway).

I will make a new mockup and post it in here.

**Comment by Monospace-V** [comment] 2022-05-22 15:48
>How about adding a boundary around the triple dots menu (maybe that can indicate that it is a clickable menu and not a drag and drop area)

Is a good idea, but while it will still give an illusion of thin clickable area (though not quite to the same extent), it will also look unpleasant if there all the time. Perhaps only upon clicking, show the box being highlighted very obviously.

>The solution to this one can be modifying the knob hover tooltip to the one similar to podium's slider tooltip

Inconsistency with respect to rest of interface. Change all tooltips? Messy. But perhaps adding L/R instead of pan? Although in this case a user would never learn the conventional name of the parameter.

>I thought of removing them for real estate (which is getting wasted in my design as of now anyway).

How do you feel about the idea of a minimized view, where labels are hidden; a normal view, where labels are shown; and maybe an enlarged view, like the one you suggest?
I believe height of tracks can already be adjusted with Shift-vertical drag, and this can be saved into the file as of 1.3. Take a look at this feature.

**Comment by Rossmaxx** [comment] 2022-05-22 15:59
> but while it will still give an illusion of thin clickable area (though not quite to the same extent), it will also look unpleasant if there all the time. Perhaps only upon clicking, show the box being highlighted very obviously.

I agree with that one

>perhaps adding L/R instead of pan? Although in this case a user would never learn the conventional name of the parameter.

How about displaying L/R on the song editor and pan on the hover tooltip.

> How do you feel about the idea of a minimized view, where labels are hidden; a normal view, where labels are shown; and maybe an enlarged view, like the one you suggest (but possibly with labels)?

That seems like a good idea. I'll stop worrying about the enlarged one for now and it would be better to work on the minimal one.

**Comment by Spekular** [comment] 2022-05-23 07:55
Closing as duplicate of all the similar issues and consolidating into #4877

**Closed by Spekular** 2022-05-23 07:55 UTC
Labels: enhancement
