### ISSUE TITLE
The first note that's played on the piano roll doesn't sound full.

### ISSUE THREAD

**Issue by DevSynth** [LMMS/lmms#4066] opened 2017-12-22 12:32 UTC
When I play a note (which comes first) on the piano roll, I don't hear it fully and this applies to the Beat and Bassline editor

**Comment by zonkmachine** [comment] 2017-12-22 14:45
Duplicate of https://github.com/LMMS/lmms/issues/2074 ?

**Comment by zonkmachine** [comment] 2017-12-27 17:03
> I don't hear it fully

It doesn't play its full length or it's playing at low volume?
Which version of lmms?

**Comment by tresf** [comment] 2018-03-06 22:23
No reply in months, closing.

**Closed by tresf** 2018-03-06 22:23 UTC
Labels: needs clarification
