### ISSUE TITLE
Porting file input and output out of main event loop.

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5575] opened 2020-07-12 12:53 UTC
The interface freezes on file operations, like write or read, maybe making them asynchronous would be good.

**Comment by SecondFlight** [comment] 2020-08-10 19:00
I'm going to call this a duplicate of #5240 or #3792, even though this is worded a solution and not the problem.

As I understand it, the core issue in this case is that Qt's custom file dialogs are synchronous, not that LMMS is synchronous.

It's possible I'm wrong here, so please add a comment here if you have any additional info about the issue or possible solutions.

**Closed by SecondFlight** 2020-08-10 19:00 UTC
Labels: enhancement

**Comment by mnini** [comment] 2020-08-18 08:38
What about dropping QT? I have an idea, V8 for graphics, and standalone server for audio, communicated by sockets... It will make interface not freezable if there is higher priority on it, and for files, I would drop all libraries and wrote it from scratch, file ops are not that hard in event loop.

With web as interface, I think we'll reach more power out of opensource, because when we compare Qt requirements to adjust interface, to plain javascript and e.g. paper.js as vector interface library, I think every trained monkey can handle second one, but first is still struggle. With complete css and js interface I think we would get most beautiful DAW, and I will personally make sure it will be, if you give me an HTML possibility to do it. Separated sound server have also other advantages...

Even oscilloscope is possible with unix sockets, and it can look amazingly well, don't pretend that everybody doesn't have atleast 16gigs of ram... People have enough capacity to run web interface, we're in 2020.

**Comment by SecondFlight** [comment] 2020-08-18 13:55
Rewrite the entire DAW? It's possible, but we don't have the development resources to do that right now. Most of our developers are focused on making the existing software as good as it can be with the resources we have.
