### ISSUE TITLE
Dragging up/down vertical piano results in stuck notes.

### ISSUE THREAD

**Issue by nitronova** [LMMS/lmms#5028] opened 2019-06-09 23:38 UTC
![image](https://user-images.githubusercontent.com/1452074/59165711-93017180-8ae5-11e9-93c6-3a0c7a41d961.png)

Steps to reproduce:
1. Create a piano pattern on the song editor or beat/bassline editor.
2. Drag mouse down the piano keys.

Expected behavior: Each key presses and releases as I go up and down the piano.

Actual result: Multiple piano keys graphically remain pressed (the keys do not audibly stick)

**Comment by ubailey1** [comment] 2019-06-11 15:32
I can confirm this problem as well. It  seems to be random, like every other loop, some keys dont' play sound

**Comment by musikBear** [comment] 2019-06-11 19:35
Not in win32 1.2.0 rc8 (tested in both SE ans B&E contained PRoll)
Is this with a specific VST?
Please retry with default presets

**Comment by DomClark** [comment] 2019-06-11 19:37
Reproduced.

@musikBear This is in 1.2.0, not 1.2.0-rc8. Please update to the latest version.

**Comment by ubailey1** [comment] 2019-06-11 19:48
I tested in version 1.2

**Comment by BaraMGB** [comment] 2019-06-27 14:52
It's this commit: https://github.com/LMMS/lmms/commit/461faccaa0d9399e137e471d5bfa0f2b43434d9b

**Comment by DomClark** [comment] 2019-07-04 15:06
I think it's a threading issue - previously all MIDI events relating to mouse input were sent from the UI thread, but since that commit some come from the processing thread too. I guess if one drags too quickly, the note-on arrives at the piano model after the note-off. Strangely, this doesn't seem to affect all instruments - single-streamed ones are fine, along with Mallets, Organic, sfxr, and Vibed. I'll investigate.

**Comment by noahb01** [comment] 2019-07-11 03:59
I also notice this issue, especially with zasfx. This occurs under both low and high CPU load, so it doesn't seem to be affected by it. Especially with my FadeButton patch, this bug is particularly annoying as it results in FadeButtons getting stuck in their held-note color even when no note is playing.

**Comment by karmux** [comment] 2019-09-08 09:53
Related to #3005.

**Comment by zonkmachine** [comment] 2019-09-08 12:52
Closed in #5127

**Closed by zonkmachine** 2019-09-08 12:52 UTC
Labels: bug, gui
