### ISSUE TITLE
Can't run BuzMaxi3 VST-limiter in RC5

### ISSUE THREAD

**Issue by teeberg** [LMMS/lmms#4074] opened 2017-12-27 17:30 UTC
Reported in Discord: https://discordapp.com/channels/203559236729438208/242409373505159168?jump=394919444654194689

Some relevant bits of info:

> Also, RC5 seems to be mad at me now and refuses to run BuzMaxi3 VST-limiter correctly (it makes a “click” noise, the sound vanishes, and the CPU-meter goes crazy), although it did work fine just a couple hours ago.

> Though I still wonder why I can't use this VST effect anymore. Others still work correctly (tested a reverb VST), yet this one kills all sounds and makes the CPU meter go crazy. It used to work before I crashed LMMS a couple times this way.

> tried it just now, but it still doesn't work. Interestingly it still works correctly in 1.1.3, so I don't really think the plugin is corrupted

**Comment by DomClark** [comment] 2018-01-06 01:29
I've been unable to reproduce this on my machine, but we determined over Discord that the plugin was producing NaNs in the output. I'm trying to think of an easy way to continue trying to debug this remotely with the reporter if they're still interested.

**Comment by Sauerstoffdioxid** [comment] 2018-01-06 15:05
_Finally made an account._
@DomClark Yes, I am still interested in solving this. Thank you.

Also, for the sake of completeness: I can confirm the plugin itself is not corrupted (works correctly in other software and i re-downloaded it). Using a copy with a different filename didn't change anything, too (I thought that maybe LMMS adressed it incorrectly). Re-installing LMMS didn't fix it either (that's what the last quote of OP is about).

I'm running LMMS 1.2.0RC5 as a parallel install next to 1.1.3 on Windows 10.

**Comment by Sauerstoffdioxid** [comment] 2018-01-12 17:39
Ok, so I was just loading this plugin right now to see if it still didn't work and it seems it miraculously fixed itself. It's working again. 
Though this still leaves the question, _why_ it was broken in the first place. The only thing that changed (related to audio) on my system is that I got a new soundcard, but personally I don't believe that it really was the cause. 
Anyway, the problem seems to be fixed now, so I guess this issue may be closed.

**Comment by DomClark** [comment] 2018-01-12 19:57
Glad you got it working again!
As for why it was broken, that's no way we can really debug this anymore (or even determine clearly whether it was LMMS's fault or not) unless someone else has the problem again, so I'll indeed go ahead and close this issue. Thanks for letting us know. 😃

**Closed by DomClark** 2018-01-12 19:57 UTC
Labels: bug, vst
