### ISSUE TITLE
Create a Pull Request for an AppImage Travis build

### ISSUE THREAD

**Issue by tukkek** [LMMS/lmms#3558] opened 2017-05-16 15:01 UTC
@probonopd can you create a pull request adding your recipe into something the project can use? You mentioned in #2556 that you were willing to make it happen as a Travis artifact build, if there was any interest. I think it's safe to say now that there is a real interest here despite that issue being locked over purely non-technical issues.

**Comment by tresf** [comment] 2017-05-16 15:31
Duplicate of #2556.  Closing.

**Comment by tresf** [comment] 2017-05-17 04:02
Splitting this off so we have a place to discuss prior to the PR. 

```bash
# Fetch portable linuxdeployqt
wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O ~/linuxdeployqt
chmod +x ~/linuxdeployqt

# Fetch portable appimagetool
wget https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O ~/appimagetool
chmod +x ~/appimagetool

# 
# run lmms build steps from wiki
#

# redundant but avoids cleanup per https://github.com/probonopd/linuxdeployqt#usage
make -j4 install

# Make a safe backup, linuxdeployqt will modify stuff :)
cp ../target ../LMMS.AppDir


# Workaround for https://github.com/probonopd/linuxdeployqt/issues/52
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/pulseaudio/:$LD_LIBRARY_PATH

# Bundle both qt and non-qt dependencies into appimage format
~/linuxdeployqt ../LMMS.AppDir/bin/lmms -bundle-non-qt-libs -appimage

# Stuck here, says "$ID.desktop file not found"
~/appimagetool ../LMMS.AppDir
```

@probonopd  can you nudge this in the right direction? 
 * What's the difference between an `AppDir` and and `AppImage`?  Am I doing it right?
 * What steps are missing to convert the `AppDir` to an `AppImage`?  Should it just spit out an `.LMMS.AppImage` file side-by-side the `LMMS.AppDir` or am I using it wrong?
 * What exactly is `$ID.desktop` and how do I define it?

**Comment by tresf** [comment] 2017-05-17 18:22
Updated.  Here's an AppImage created directly from Ubuntu 14.04 adapted using our existing build process.

The above steps are still causing me a bit of grief.  I'll wait to receive some help from @probonopd on Gitter or here before submitting a packaging script.

https://github.com/tresf/lmms/releases/download/v1.2.0-rc2.113/lmms-1.2.0-rc.2.portable.AppImage

**Comment by probonopd** [comment] 2017-05-17 22:06
Hi @tresf thanks for your work on this. Sorry I wasn't able to chime in quicker. To your questions:

> What's the difference between an AppDir and and AppImage? 

The AppDir is a directory that contains the payload application and supporting files and has an executable file called `AppRun` as its entry point. It is what goes inside an AppImage, which is a self-mounting filesystem image that contains an AppDir.https://github.com/AppImage/AppImageSpec/ has more on it.

**Comment by probonopd** [comment] 2017-05-17 22:24
https://github.com/probonopd/lmms/blob/patch-1/.travis.yml has a work-in-progress `.travis.yml` file for generating an AppImage on Travis CI.

**Comment by probonopd** [comment] 2017-05-19 15:46
The file above produced
https://transfer.sh/HKhdZ/LMMS-git.f5fa745-x86_64.AppImage
Please test, and please use the yml file linked above as an inspiration for the pull request.

**Comment by probonopd** [comment] 2017-05-19 15:51
By the way, while I agree `makeself` can do many things, it's not so much about the wrapper format (be it zip, makeself, or AppImage) but how one makes the actual payload binaries that go inside what determines the "out of the box" compatibility with different target systems (distributions). And makeself needs to extract the contents of the entire archive before it can execute the payload, whereas AppImage mounts the filesystem image and then immediately starts executing the application and decompresses in RAM on-the-fly, which is very fast. This can make a rather large performance difference for large applications.

**Comment by flynn16** [comment] 2017-09-18 09:58
Using the script above, I am able to build LMMS with Qt 5.9 and make a working AppImage. `ldd` complained that `libjasper.so.1` (a Qt 5.9 dependency) was not found. I simple ran
```
sudo apt install jasper-dev
```
and after that the AppImage built successfully.

![LMMS AppImage](https://user-images.githubusercontent.com/22479257/30536951-76122ac8-9c9a-11e7-9952-4d68142b2ad3.png)

I thought the GUI of LMMS would scale when compiled with Qt 5.9, but it didn't... From my experience, there is a flag you can set to make everything scale. Try this:
```python
QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)
```

**Comment by tresf** [comment] 2017-09-18 13:21
> ldd complained that libjasper.so.1 (a Qt 5.9 dependency) was not found. I simple ran
> `sudo apt install jasper-dev`

Why are the dev libraries needed?  How would Qt otherwise run without it?  Generally speaking, the `dev` libraries shouldn't be needed for runtime loading, but rather for linking against when building (and we're not building Qt).

We can bundle this library too, but `linuxdeployqt` should handle that, especially considering it's a Qt dependency.  @probonopd is the maintainer of `linuxdeployqt`.

@probonopd are you aware of this `libjasper.so.1` issue?  Is this a know issues with the `linuxdeployqt` tool or perhaps a known issue with Qt5 in general?

> I thought the GUI of LMMS would scale when compiled with Qt 5.9, but it didn't... From my experience, > there is a flag you can set to make everything scale. Try this:

```cpp
QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)
```

This conversation really need to be in https://github.com/LMMS/lmms/issues/2510.  Can you tell us which OSs you've tested this on, but please keep the answers in 2510 as they do not pertain to the `AppImage` support specifically.

**Comment by tresf** [comment] 2017-09-18 13:24
Ok, it looks like the `libjasper` issue is a duplicate of upstream bug report https://github.com/probonopd/linuxdeployqt/issues/109.

**Comment by flynn16** [comment] 2017-09-18 13:54
I added [that line](https://stackoverflow.com/questions/20464814/changing-dpi-scaling-size-of-display-make-qt-applications-font-size-get-rendere#36058882) to `gui/GuiApplication.cpp`. I compiled a LMMS AppImage with Qt 5.9. Then I set an environment variable:
```bash
$ export QT_AUTO_SCREEN_SCALE_FACTOR=1
$ ./LMMS-x86_64.AppImage
```
The beautiful GUI showed up. (Ubuntu 16.04)
![Properly scaled GUI](https://user-images.githubusercontent.com/22479257/30545319-d1dd8d0e-9cbb-11e7-9c42-93454497605a.png)

**Closed** 2017-10-16 19:09 UTC

**Comment by tresf** [comment] 2017-10-16 19:33
AppImage support has been added to the source tree.  It can be performed by doing:

```sh
make install && make appimage
```

Due to the way the dependencies are bundled the install prefix currently must be something sandboxed, e.g. `$HOME/lmms/target`.  It will fail if the default `/usr/` location is used.

Also, this PR doesn't not handle automatic uploads of the AppImage packages.  @probonopd has recommended we use a service such as `transfer.sh` which will hold the file for 14 days to allow for adequate testing.  A barebones `transfer.sh` example is available here for anyone willing to tackle this: https://github.com/LMMS/lmms/compare/stable-1.2...probonopd:patch-1#diff-354f30a63fb0907d4ad57269548329e3R29.
