### ISSUE TITLE
SF2 Player wrong icon when placed

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#7116] opened 2024-02-19 18:22 UTC
### Bug Summary
In new update, when new SF2 player instances are placed, their icon is incorrect. existing ones are fine
#### Steps to reproduce
place SF2 player
#### Expected behavior
Switches to the SF2 player icon
#### Actual behavior
Stays on some default piano icon
#### Screenshot
![image](https://github.com/LMMS/lmms/assets/65266122/b739b559-dcf0-44d5-ba0a-f607994478a6)
newly placed

![image](https://github.com/LMMS/lmms/assets/65266122/eadf3b69-84bc-4a46-b69d-164f79f42de4)
pre-existing

#### Affected LMMS versions
1.3.0-alpha.1.527+g360254fd8

**Comment by messmerd** [comment] 2024-02-19 20:15
This might be caused by #7114
@michaelgregorius

**Comment by SalutanisOrkonus** [comment] 2024-02-19 20:30
also seems to affect slicert

**Comment by michaelgregorius** [comment] 2024-02-19 21:11
I have just checked. For me it affects the following instruments and only if they are pulled into the song editor:
* Sf2 Player
* Watsyn
* ZynAddSubFx

If I load a file that contains these instruments then the icons are shown correctly. I will check what's causing this.

**Comment by michaelgregorius** [comment] 2024-02-19 21:58
Wow, it gets even worse. The underlying problem is that the `InstrumentTrack` that's passed into `InstrumentTrackView::determinePixmap` does not have an `Instrument` assigned in several cases. However, I am now under the impression that some threading problem is mixed in there as well.

Here are the steps to reproduce the threading problem (line numbers refer to commit 360254fd):
1. Set a break point in line 1054 of `InstrumentTrack`, i.e. the line in `InstrumentTrack::loadInstrument` where `m_instrument` is being assigned to.
2. Set a break point in `InstrumentTrackView::determinePixmap`, e.g. inside of the first `if` statement.
3. Drop an instance of "Sf2 Player" onto the Song Editor.
4. The first break point in `InstrumentTrack` is hit in a thread called "lmms::Instrumen" (shown like that in my debugger). Try to step over it.
5. The second break point in `InstrumentTrackView` now gets hit before the code is stepped over. This time we are in the thread called "lmms". I guess it's the GUI main thread.
6. Continue execution.

If you now switch to the application then the icon is shown. I guess the debugger is halted long enough in the main thread so that the `InstrumentTrack` gets an instrument assigned in another thread.

If you delete/disable the break point in `InstrumentTrack::determinePixmap` and follow the coarse steps above then the icon is not shown because the track has no instrument.

It seems that there is no framework which governs the creation of the different core and GUI instances and that on top of it all the stuff seems to happen in different threads.

This might also explain why @SalutanisOrkonus is reporting that SlicerT is broken for them as well while it's not broken for me.

**Comment by michaelgregorius** [comment] 2024-03-02 18:44
Pull request #7132 fixes the problem by reinstating the paint event on the `TrackLabelButton`.

**Closed** 2024-03-13 19:00 UTC
Labels: bug
