### ISSUE TITLE
How to make tracks gradient-less??

### ISSUE THREAD

**Issue by sksar** [LMMS/lmms#2927] opened 2016-07-21 06:45 UTC
I was creating a custom flat theme for lmms, but suddenly i realized that the tracks (BB,piano-roll,automation) have a slight gradient...
How do i override that gradient using css.... also i fount that nearly all of the stuff out there has a slight gradient,, how do i override them?? using css? or do i have to write some other code??

**Comment by tresf** [comment] 2016-07-21 12:27
@sksar which version are you working on?  In the (soon to be) 1.2 version, we've made most of the gradient code CSS-themable, but we don't have a binary (exe, dmg, etc) release for download yet.

Related #2574 #2770 #2867 #2587 #2806

**Comment by sksar** [comment] 2016-07-21 12:55
i am actually working on 1.1.3... i think its not possible using css.....

**Comment by tresf** [comment] 2016-07-21 13:01
> i am actually working on 1.1.3... i think its not possible using css

Correct.

> i installed the 1.1.90 version (on windows xp) and it failed to start...

Duplicate of #2576

> when is the version 1.2 gonna get a final release

We'll have an RC2 with the latest theme changes very soon, just a matter of writing up the release.  Final release is going to be influenced by closing the [outstanding issues](https://github.com/LMMS/lmms/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.2.0) first.

**Comment by tresf** [comment] 2016-07-21 13:02
Closing as duplicate of #2574

**Closed by tresf** 2016-07-21 13:02 UTC
Labels: duplicate

**Comment by sksar** [comment] 2016-07-21 13:05
also can the tracks be made slight transparent now?? i mean in 1.2+

**Comment by tresf** [comment] 2016-07-21 13:13
> also can the tracks be made slight transparent now?? i mean in 1.2+

Adding an alpha channel as a 4th parameter in the CSS color should do the trick, although this is untested.

[Here's a dated download](https://github.com/tresf/lmms/releases/download/v1.2.0-RC2/lmms-1.1.90-geb17044-win32.exe) but should contain the flat stuff you're looking for to get started while you wait for RC2.

![image](https://cloud.githubusercontent.com/assets/6345473/17023826/49a1c1f8-4f23-11e6-9637-80614119a2bc.png)
