### ISSUE TITLE
VyNil randomly blares out a square wave (Mojave 10.14)

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#5392] opened 2020-02-11 18:33 UTC
Buncha issues, copying and pasting from discord cause lazy

### Bug Summary
- Overdrive randomly plays a extremely loud square wave for like a quarter second, and itll go through any effects after the overdrive. also, it only happens when no audio is playing through it. **EDIT: ive confirmed that this happens in the latest stable build too (1.2.1), but its quieter.  
EDIT2: I have a feeling it might be VyNil or Amplifier, ive been able to confirm its not ReverbSC (because i use it on other channels and those dont play the sound), Equalizer, or StereoEnhancer (for the same reason).**

#### Steps to reproduce

Open a project, slap Fast overdrive and VyNil on a instrument, and focus on a different app. I usually have LMMS in a "desktop" all on its own.
![Screen Shot 2020-02-11 at 1 27 32 PM](https://user-images.githubusercontent.com/33764485/74266437-486a7180-4cd2-11ea-89a3-3a0deb0849a6.png)

#### Expected behavior
No loud square wave.

#### Actual behavior
Extremely loud square wave, going through whatever effects are after VyNil or Fast Overdrive.

#### Screenshot
Will update when the bug happens.

#### LMMS versions used
1.2.1.581, 1.2.1

</pre>
</details>

**Comment by SecondFlight** [comment] 2020-02-11 19:12
Hi, could you title these with a shortened summary of the issue? It will make them easier to find later, and more likely to be fixed.

**Comment by zonkmachine** [comment] 2020-02-11 20:59
This sounds like the ViNyl plugin acting up and it's a known issue. https://github.com/LMMS/lmms/issues/3170
@GingkathFox Do you get any problems like this without VyNil in the project?

**Comment by GingkathFox** [comment] 2020-02-11 22:17
@SecondFlight edited :D 

@zonkmachine seems like it, never got the issue while checking out my older projects.

**Comment by PhysSong** [comment] 2020-04-30 03:13
Closing as a duplicate of #3170.

**Closed by PhysSong** 2020-04-30 03:13 UTC
Labels: bug, duplicate
