### ISSUE TITLE
Hang when closing program if pop-up isn't closed after save

### ISSUE THREAD

**Issue by javiercordero** [LMMS/lmms#2730] opened 2016-04-16 14:38 UTC
# Description
LMMS stops working if the pop-up shown on save isn't gone before closing the program. What happens is the main window closes but the save notice stays as the program hangs.

# Specs
- Windows 10 64 bits
- Running LMMS Version 1.1.90 (win32/x86_64, Qt 4.8.7, GCC 4.9.4 20150716 (prerelease))

# Screenshot
http://s24.postimg.org/kr63ag445/LMMS_hang_if_pop_up_not_closed_after_save.png

**Comment by Spekular** [comment] 2016-04-16 15:14
Duplicate of #2718 and #2584.

**Comment by tresf** [comment] 2016-04-16 15:21
@javiercordero, Thanks for the detailed bug report.  Marking as duplicate, but we appreciate the time ad quality you put into this.  :+1:

**Closed** 2016-04-16 15:21 UTC
Labels: duplicate
