### ISSUE TITLE
VST GUI is always on top

### ISSUE THREAD

**Issue by iamvd** [LMMS/lmms#4101] opened 2018-01-08 21:38 UTC
Version 1.2.0-rc5 (Linux/i386, Qt 4.8.6, GCC 4.8.4)
Linux Mint 17.3

This happens with any VST-plugin. As you can see, the contents of the plugin window overlaps all other windows. But the header of the plugin window behaves normally.

![untitled- - lmms 1 2 0-rc5_290](https://user-images.githubusercontent.com/16133181/34692986-e1e3c4e0-f4e3-11e7-8fa6-727683b0305e.png)

**Comment by Umcaruje** [comment] 2018-01-08 23:01
What do your settings say about the VST embedding method? Can you try the AppImage from https://lmms.io/download/#linux

**Comment by iamvd** [comment] 2018-01-08 23:23
The embedding method is "Embed using XEmbed protocol". The issue is that such a behavior was not being appeared on my system in the previous releases (i.e. 1.1.3 and newer).

Unfortunatelly, I currently using a 32bit distribution, so I can't try the AppImage.

**Comment by tresf** [comment] 2018-01-09 00:26
Cannot reproduce with Synth1/Qt 5.9/Ubuntu 14.04 x64.

* What window manager are you using?
* Is `winecfg`, `Graphics`, `Allow Window Manager to control the windows` selected?

![screen shot 2018-01-08 at 7 23 54 pm](https://user-images.githubusercontent.com/6345473/34699121-a6b157be-f4a9-11e7-901b-5286499724cf.png)

**Comment by iamvd** [comment] 2018-01-09 11:12
* DE is MATE 1.12.0 (window manager is Caja).
* Qt version is 4.8.6.
* The "Allow Window Manager to control the windows" option is set.

Should I try to rebuild the program with Qt5?

**Comment by lukas-w** [comment] 2018-01-09 11:26
> Should I try to rebuild the program with Qt5?

@iamvd Yes, please. VST embedding has been rewritten for Qt5 and it's unlikely that we'll put a lot of work into fixing Qt4-only embedding bugs. Going forward with 1.3.0, Qt4 support will be dropped entirely.

It's strange that you report it used to work with 1.1.3 though. Not much has changed since then in the Qt4-specific code. 

It'll be interesting to see whether switchiing to Qt5 fixes this for you. To build with Qt5, pass `-DWANT_QT5=ON` to CMake.

**Comment by iamvd** [comment] 2018-01-09 14:53
Finally I've done with the building process, which required me to resolve lots of Qt5-related dependencies. And now I can say that the VST GUI works just fine.

Nevertheless, the mouse is going crazy, when I dragging the windows :)
![untitled- - lmms 1 2 0-rc5_293](https://user-images.githubusercontent.com/16133181/34726709-a2b93ea6-f576-11e7-9d41-4e8e18aca34e.png)

**Comment by tresf** [comment] 2018-01-09 15:31
@iamvd which Qt5 version?

**Comment by iamvd** [comment] 2018-01-10 14:07
@tresf, 5.2.1
Just ran the program. There are no mouse lags for now.

**Comment by tresf** [comment] 2018-01-10 14:13
@iamvd are you OK if we close this issue?  It sounds like your problems have been resolved by switching to Qt5.  Note, we ship our AppImages with Qt 5.9 so any Qt-specific issues you encounter with 5.2.1 should be tested against the AppImage before filing a new bug.

**Comment by iamvd** [comment] 2018-01-10 14:21
@tresf, no problem.

Many thanks to you, guys, for your support.
Best regards!

**Closed** 2018-01-10 14:22 UTC
Labels: bug, vst
