### ISSUE TITLE
ZASF >Show GUI > Advanced crashes Xorg [ master branch ]

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#2701] opened 2016-03-25 01:09 UTC
Hi guys I am running the latest Master branch from git ( built with -DWANT_QT5=ON )

To reproduce load ZtnAddSubFX into a track and it will play the default sine wave as expected from the LMMS Plugin window, but click on " Show GUI " > " Advanced" and this will immediately crash my /usr/bin/xorg causing a logout . This makes a backtrace quite difficult.
 * note I have not yet tried building with QT4 if this could be relevant? *
other plugins for example Carla-Rack load up and work as expected.

* setting gdb to log to a txt file during the crash shows only this output :- 

Program received signal SIGSEGV, Segmentation fault.
0x00007fffed83b000 in xcb_setup_vendor_end ()
   from /usr/lib/x86_64-linux-gnu/libxcb.so.1

**Comment by tresf** [comment] 2016-03-25 02:08
Not our bug.  Duplicate of #2100. :+1:

**Closed by tresf** 2016-03-25 02:08 UTC
Labels: not our bug

**Comment by mikobuntu** [comment] 2016-03-25 10:17
@tresf  Are you 100% sure this is "not our bug" ?
I ask because I have no such issue with my local installs of ZynAddsubfx, which standalone version is Version: 2.5.3, I also have no issues with the linux VST version and also LV2 version running in other DAWs. This seems to only happen on my system in LMMS .

**Comment by tresf** [comment] 2016-03-25 12:27
> @tresf Are you 100% sure this is "not our bug" ?

The evidence I have is:
 1. Same symptom, X.org crashes
 2. Same version, 2.5.3
 3. Same action triggers the crash


> #2701: I have no such issue with my local installs of ZynAddsubfx, which standalone version is Version: 2.5.3

> >  #2100: I can load ZynAddSubFx standalone just fine.

If I'm wrong, reopen.  :+1:

**Comment by tresf** [comment] 2016-03-25 12:30
@mikobuntu update, @Umcaruje actually opened the [upstream report](https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1449167) (expired) over at Ubuntu, so I'll let him chime in on this. :beer:

**Comment by Umcaruje** [comment] 2016-03-25 13:20
Well, when I talked over with @fundamental over on IRC he said this is a bug that occurred with Xorg, and that there was a patch already submitted over at Xorg, but the Ubuntu version hasn't pulled in that patch yet. 

So I'm pretty sure this is not our bug, since the main dev of Zyn said that its not his bug, and it's Ubuntu/Xorg's bug.

**Comment by fundamental** [comment] 2016-03-25 14:07
@mikobuntu to confirm it is X11, compile one zyn (standalone) with fltk and one zyn (standalone) with ntk. The fltk version calls fl_arc which calls the x11 arc drawing routine. The ntk version simply draws a pixmap with no such x11 call. If the ntk version works and the fltk version crashes xorg, then it is almost certainly a bug in your version of X11.

**Comment by tresf** [comment] 2016-03-25 14:12
> and one zyn (standalone) with ntk

FWIW, Mark helped me through this process here... https://www.kvraudio.com/forum/viewtopic.php?f=47&t=411406#p5746278

**Comment by mikobuntu** [comment] 2016-03-25 22:03
Thanks guys for all your input here, much appreciated. I will test this properly once i can figure what is wrong with my system/zyadd code or perhaps apply the Xorg patch manually?... as I'm having problems compiling the master branch for now, but I'm sure you are all right in it being an Xorg bug. thanks :)

**Comment by zonkmachine** [comment] 2016-08-01 23:47
So annoying. The patch in question was released in xorg-server-1.17.2

Distros/versions that will work:
LinuxMint 18
Ubuntu wily 15.10 or later
Debian Testing ( Not in Jessie... )
