### ISSUE TITLE
Pattern names difficult to read

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3674] opened 2017-06-30 13:38 UTC
![blocknamesrc3](https://user-images.githubusercontent.com/6662066/27737796-c53d0896-5da9-11e7-83cf-7e89b176252f.JPG)

Difference between notes and letters are not sufficient, if they overlap -Maby more dark in the letters? (mouse over tooltips still shows 'open in piano-roll')

**Comment by tresf** [comment] 2017-06-30 13:49
Reproduced.

![image](https://user-images.githubusercontent.com/6345473/27738464-64411616-5d79-11e7-88ad-3cfb3530e9a7.png)

**Comment by michaelgregorius** [comment] 2017-06-30 18:49
A solution to that problem was proposed [in this comment](https://github.com/LMMS/lmms/issues/1839#issuecomment-132791913). At that time @musikBear [preferred a mouse over](https://github.com/LMMS/lmms/issues/1839#issuecomment-132978893) as the solution.

**Comment by musikBear** [comment] 2017-07-01 14:06
@michaelgregorius It is better with a shadowed box 👍 , but mouse-over-tooltip would still be a good addition, also because the current 'message' is self-explanatory, i believe its something most would do intuitively. Right-click also opens context options.
Tooltip is 'free' to use (imo

**Comment by RebeccaLaVie** [comment] 2017-07-01 16:39
I am concerned with how that overlay obscures a lot of the track. I did a bit of research and it might be worth noting that I couldn't find any major DAWs that don't have a space dedicated to the pattern names without any overlap.

A couple examples:
![fl12full_1](https://user-images.githubusercontent.com/7960169/27763858-cdb757c8-5e40-11e7-9c0f-6af801452748.jpg)

![r8c_1606_flexibleuserinterface](https://user-images.githubusercontent.com/7960169/27763860-d0d15116-5e40-11e7-84de-a8f792071528.png)

_My 2 cents_

**Comment by musikBear** [comment] 2017-07-02 12:09
@RebeccaLaVie You are 100% on target !
I looks ugly with the text-box overlay
I think the whole issue is real-estate. LMMS has narrow tracks, compared to the above examples. The real issue is where the notes *overlap* the names, that issue does not exists in 2. image, and 1. 'simply' has a dedicated name-space over the blocks.
This issue has *two* sides:
1) user should be able to read block-names, even where there are lots of notes
2) User need to be able to read full block-name, even in very short blocks

1) is addressed with real-estate over the block, so name and notes never overlab
2) is achieved with mouse-over 
Imo, LMMS needs both.

( **Later** a search method for a named block, (drop-down) would be super)

**Comment by michaelgregorius** [comment] 2017-07-02 18:37
I have experimented a bit and this is what I have come up with so far:
![3674-minimum-size](https://user-images.githubusercontent.com/9293269/27772512-4e8ffcfa-5f64-11e7-927e-cef8a47fc4ce.png)
This screenshot shows some patterns at the default minimum height of 32 pixels.

The first two patterns have names that are different from the instrument name which is why they are rendered in the first place. The first one shows the rendering of a muted pattern while the second one shows a pattern that's not muted. I have decided to elide the text in the middle because I assume that people might user names like for example "Pattern 1" and "Pattern 2" and that way it's still possible to distinguish between such patterns as can be seen in the screenshot.

The current implementation renders a black transparent rectangle beneath the text (RGB(0, 0, 0, 64)). This way it will hopefully also work with different colors.

And this is how it looks with a bigger height and zoom factor where no elision is needed:
![3674-bigger-pattern](https://user-images.githubusercontent.com/9293269/27772531-bcdc7ed6-5f64-11e7-8f64-8e062e2867bf.png)

In my opinion the default height and width of the tracks should be bigger anyway. Rendering everything so small and confined makes it feel like a software with an inferior complex to me. :wink:

**Comment by tresf** [comment] 2017-07-02 19:06
In my experience with text contrast white text with a black stoke does the trick 99.9% of the time.

That said, @michaelgregorius, the proposal looks very nice.

**Comment by Umcaruje** [comment] 2017-07-02 19:16
why don't we just reserve some space in the pattern where the text will go, and just change the note drawing routine to draw underneath that space?

**Comment by michaelgregorius** [comment] 2017-07-02 19:37
@Umcaruje This would be another option which would look similar to @RebeccaLaVie's first example (which I think is FL Studio). However, for that to work we'd really have to increase the default height of tracks because otherwise you'd see almost nothing of the notes (see my first screenshot). This in turn would imply that we need to fix the rendering of the beats and basslines patterns at increased heights.

So the proposed option is the simplest for now.

On a side note: it might be a good idea to make the resize option for the tracks a bit more obvious, e.g. by changing the cursor at the bottom of tracks to an up/down arrow which can be used to change the height of the track. Currently this functionality is very hidden. On the other hand I have just noticed that the changed track heights are not saved anyway.

**Comment by Umcaruje** [comment] 2017-07-02 19:45
>On the other hand I have just noticed that the changed track heights are not saved anyway.

Not to mention that the elements don't center themselves when the track height is changed. It's a pretty broken feature

>This would be another option which would look similar to @RebeccaLaVie's first example (which I think is FL Studio). 

Oh and also my proposal would look very similar to the 2nd option, which is Bitwig :slightly_smiling_face:

**Comment by RebeccaLaVie** [comment] 2017-07-03 02:11
The Bitwig and FL screenshots are essentially the same concepts, only FL uses a lighter gradient in the same space set aside for the text. I think both of those proposals would need to have the default height of tracks increased to really work.

> So the proposed option is the simplest for now.
If we are looking for a temporary solution, I might decrease the height of the overlay and text to make it more compact.

**Comment by Spekular** [comment] 2017-07-03 05:29
I think that in order to be flexible with vertical real estate it should be
possible to show/hide names, or maybe even show above/show inside/hide.

The first system that comes to my mind would be a global setting somewhere
(Song Editor toolbar?) with individual track overrides and the ability to
show/hide one single pattern name with hover.

On Jul 3, 2017 05:11, "Rebecca LaVie" <notifications@github.com> wrote:

The Bitwig and FL screenshots are essentially the same concepts, only FL
uses a lighter gradient in the same space set aside for the text. I think
both of those proposals would need to have the default height of tracks
increased to really work.

So the proposed option is the simplest for now.
If we are looking for a temporary solution, I might decrease the height of
the overlay and text to make it more compact.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LMMS/lmms/issues/3674#issuecomment-312534112>, or mute
the thread

**Comment by musikBear** [comment] 2017-07-03 11:59
> If we are looking for a temporary solution, I might decrease the height of the overlay and text to make it more compact.

That would make i worse. The important thing is reading *named* tracks. For hide resp show, i would actually think that it would be better to hide the *notes* and not the names
Currently a user can only identify a block-segment by the 'bar-code' made up of lines of notes, *and* letters used as *names*
It is obvious to me, that it would be far superior to have both readable names (looks like bitWig has that, FLs is imo way to tiny) tooltip *and* color-options.
@michaelgregorius wider proposal gives the necessary space for much better readability. That looks good! 
No-ones mentions tool-tip, that is needed for small blocks

**Comment by RebeccaLaVie** [comment] 2017-07-03 16:01
@musikBear To clarify, I was talking about making @michaelgregorius's proposed overlay _slightly_ more compact because even FL uses a smaller font and we have to be mindful of real-estate. The font could be bigger than what we have now, but let's not go too far. :+1:

**Comment by tresf** [comment] 2017-07-03 17:09
> I think that in order to be flexible with vertical real estate it should be possible to show/hide names, or maybe even show above/show inside/hide.

I really don't like adding more configuration options to the software, especially something so trivial.  If people don't want names on the patterns, they shouldn't name the patterns.

> The important thing is reading named tracks.

I agree.  The name of the segment is often more important than the thumbnail of it.  The proposed text size looks reasonable and sane.

>  I was talking about making @michaelgregorius's proposed overlay slightly more compact because even FL uses a smaller font

This is a good point.  The more text we can fit in small segments the more useful.  @michaelgregorius can you do a mockup with a slightly smaller font? :)

**Comment by tresf** [comment] 2017-07-03 17:16
And credit where credit is due... the proposal does fix the bug.  (proper 72dpi examples all on modern theme should be used for side-by-side)

![screen shot 2017-07-03 at 1 16 02 pm](https://user-images.githubusercontent.com/6345473/27802449-d55e0794-5ff1-11e7-8203-e61d967dd0d9.png)

**Comment by michaelgregorius** [comment] 2017-07-03 21:26
Here are some renderings at different font sizes. First image is rendered with a point size of 5:
![3674-size-5-aa](https://user-images.githubusercontent.com/9293269/27808133-1d154760-6046-11e7-8fee-103de68bfa64.png)

Point size 6:
![3674-size-6-aa](https://user-images.githubusercontent.com/9293269/27808142-3091717e-6046-11e7-9392-798a19ddfaaa.png)

Point size 7:
![3674-size-7-aa](https://user-images.githubusercontent.com/9293269/27808146-39a98670-6046-11e7-872c-fe3e0a1c8992.png)

In my opinion it starts to become usable with a point size of 6.

I also would not add it to the configuration but we might consider to expose the pattern font in the CSS at a later point.

**Comment by RebeccaLaVie** [comment] 2017-07-04 03:54
> In my opinion it starts to become usable with a point size of 6.

@michaelgregorius I agree with you. I would be curious to know what size we are currently using.

You could probably also get away with increasing the alpha value in the overlay to 75 for a bit more contrast. :+1:

**Comment by musikBear** [comment] 2017-07-04 07:44
Me, the sight impaired 'bat' i am, can only read the Point size 7, but a css option would completely shut me up :)

**Comment by RebeccaLaVie** [comment] 2017-07-04 08:28
@musikBear Yes, a 6pt is pretty small. I would think that is the very minimum. Knowing what size we are using now would give us a much better idea on which size to choose. :)

**Comment by michaelgregorius** [comment] 2017-07-04 17:37
@RebeccaLaVie The current size is 8 points if that makes the decision easier. :)

It's also the size that's shown in the first experimental screenshots from two days ago. Currently the font size of the pattern is bigger than the size used to display the instrument's name which seems a bit off to me anyway.

**Comment by michaelgregorius** [comment] 2017-07-04 19:04
@RebeccaLaVie Here's how it looks with a background of RGBA(0, 0, 0, 75) by the way:
![3674-size-8-alpha75](https://user-images.githubusercontent.com/9293269/27840719-94d44124-60fb-11e7-9f55-d46ad7d3cbef.png)

The notes are still distinguishable from the text so I'd say we get away with this. :)

**Comment by musikBear** [comment] 2017-07-05 12:54
@michaelgregorius  I like the wide one 👍

**Comment by RebeccaLaVie** [comment] 2017-07-09 22:13
> Currently the font size of the pattern is bigger than the size used to display the instrument's name which seems a bit off to me anyway.

From what I can tell, changing the font size of the pattern to 7 will also match the instrument name size.

**Comment by musikBear** [comment] 2017-07-10 10:12
Looking at picture from comment https://github.com/LMMS/lmms/issues/3674#issuecomment-312935850
I think it would better the set the instrument.name font *up* to the size of the block-labels.
But i would, wouldent I.. 🙈 🦇 :mole .. me

**Comment by michaelgregorius** [comment] 2017-07-10 17:02
I have now changed it so that the font properties are taken from the style sheets. The font sizes of the instrument names are defined in pixels (11px) therefore I have set the font size for the patterns to 11px as well. Both style sheets (classic and default) have been adjusted.

The pull request is #3691.

**Comment by michaelgregorius** [comment] 2017-07-11 19:24
Closed via #3691.

**Closed by michaelgregorius** 2017-07-11 19:24 UTC
