### ISSUE TITLE
Pre-rendering unchanged audio channels to save CPU power.

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5640] opened 2020-08-18 08:50 UTC
The automatic or manual freezing of tracks in place, pre-rendered if they are not actively manipulated and you want to save some CPU power. It could lead to easier workflow...

You would have ability to pick up on which effect you want to freeze it, and where it would play live, it doesn't make much space in the RAM anyway, and this is how DAW can sacrifice RAM to CPU.

**Comment by Spekular** [comment] 2020-08-18 08:56
Duplicate of #762.

**Closed by Spekular** 2020-08-18 08:56 UTC
Labels: enhancement
