### ISSUE TITLE
Crash when changing presets

### ISSUE THREAD

**Issue by soppe23** [LMMS/lmms#2962] opened 2016-08-06 18:33 UTC
When using some VST-plugins like Dexed (which I really would like to be able to use in LMMS) and Helm in VeSTige, LMMS freezes and crashes. Usually the plugin becames all black.
I have the newest version of LMMS and plugins. 64-bit machine.

**Comment by musikBear** [comment] 2016-08-07 11:34
Our forum is the correct place for this question:)
http://lmms.io/forum/index.php
However, there are some few cst's that does not work in lmms:
https://lmms.io/wiki/index.php?title=Working_with_VSTs#VST_related_problems

All these and many many more does
https://lmms.io/wiki/index.php?title=Tested_VSTs

**Comment by soppe23** [comment] 2016-08-08 17:32
Oh, I thought this would be the right place :D 
Anyways I'm using Win 10 Home Premium. Guess there's no sp... 
LMMS is version 1.1.3. and VST's are newest versions also.

**Comment by tresf** [comment] 2016-08-08 17:47
> Oh, I thought this would be the right place :D 

It is although this particular bug is a duplicate of #2784.

Thanks for reporting!

**Closed by tresf** 2016-08-08 17:47 UTC
Labels: duplicate
