### ISSUE TITLE
CMake 3.3 support

### ISSUE THREAD

**Issue by Israel-** [LMMS/lmms#2260] opened 2015-08-13 13:38 UTC
Hi everyone,
I have been trying to get lmms 1.1.3 into Ubuntu Wily, with the separate
VST package, but we are having issues with CMake.
Timo and I have been commenting about this:
https://code.launchpad.net/~israeldahl/ubuntu/wily/lmms/lmms/+merge/266928

My guess is that CMake 3.3.X is not handling things correctly in Ubuntu wily.
Your `CMakeLists.txt` looks for:
```cmake
CMAKE_MINIMUM_REQUIRED(VERSION 2.4.5)
```
So there obviously has been many changes since then. Does it work for anyone to use the latest 3.3.X version of cmake in their own environments?

The other issue we might face is the newer `gcc` version.....

But the errors we have found have been related to CMake thus far.

Initially cmake could not find FLUID, even though I include the fluid binary as part of the build depends (in the debian packaging) and it does exist in the build environment in the usual place (`/usr/bin/fluid`) Here is what Timo did to force it to find Fluid:
```cmake
FIND_PACKAGE(FLTK REQUIRED)

SET(FLTK_FLUID_EXECUTABLE "/usr/bin/fluid")
IF(MINGW_PREFIX)
      SET(FLTK_FLUID_EXECUTABLE "${MINGW_PREFIX}/bin/fluid")
ENDIF()
```

After this is fails at
```
CMakeFiles/Makefile2:4654: recipe for target 
'plugins/LadspaEffect/swh/CMakeFiles/hermes_filter_1200.dir/all' failed
```
And other plugins fail as well.
So... anyone have any suggestions for this?

**Comment by tresf** [comment] 2015-08-13 14:35
I've changed the title to CMake 3.3 and put formatting tags around your code.

The best approach at this point is form someone to get a beta version of `Ubuntu 15.10` and try our our build tutorial.

**Comment by tresf** [comment] 2015-08-13 19:33
@Israel- I tried two separate 15.10 ISO images in VirtualBox and neither of them will boot.  If you can assist in obtaining a good bootable ISO, I'd be happy to help.

**Comment by Israel-** [comment] 2015-08-14 00:03
@tresf I am trying to download now to see.
This is the link I used... well I am using zsync
zsync http://cdimages.ubuntu.com/daily-live/current/wily-desktop-i386.iso.zsync
Here is the other (non zsync) link
http://cdimages.ubuntu.com/daily-live/current/wily-desktop-i386.iso
Is this the one you got?

**Comment by tresf** [comment] 2015-08-14 00:59
No, I tried the 64-bit build.  Kubuntu installed fine tho, I'll just reproduce w/ 15.10 amd64 Kubuntu and I will report back...

**Comment by Israel-** [comment] 2015-08-14 01:07
Oh, ok!  I am downloading 32bit... I usually use those for VM.. not sure why, just old habit I suppose.  I will let you know if the 32bit boots...  You know.. it might be EFI issue, but it could just be a bad build. I'll test 32bit and let you know.

**Comment by tresf** [comment] 2015-08-14 14:57
@Israel- 

There seems to be a bug with CMake 3.2's FLTK module "FindFLTK.cmake".

 Specifically, when CMake calls `FIND_PACKAGE(FLTK)` it sets the `FLTK_FLUID_EXECUTABLE` variable to `fluid` rather than `/usr/bin/fluid`.  Since we verify that the full path exists, the check fails even though fluid is detected properly.

The below snippet allows cmake to fallback onto the `which fluid` command, which will return the full path and pass this check.

```cmake
IF(NOT EXISTS ${FLTK_FLUID_EXECUTABLE})
	# Try to detect full path anyway
	EXECUTE_PROCESS(COMMAND which fluid OUTPUT_VARIABLE FLTK_FLUID_EXECUTABLE OUTPUT_STRIP_TRAILING_WHITESPACE)
	IF(NOT EXISTS ${FLTK_FLUID_EXECUTABLE})
		MESSAGE(FATAL_ERROR "Please install the fluid binary which is part of FLTK.")
	ENDIF()
ENDIF()
```

**Comment by tresf** [comment] 2015-08-14 15:00
In regards to the `hermes_filter_1200` issue, I cannot reproduce.

**Comment by tresf** [comment] 2015-08-14 15:05
@Lukas-W @curlymorphic @diizy 

The above patch (https://github.com/LMMS/lmms/issues/2260#issuecomment-131136718) requires modifying `plugins/zynaddsubfx/CMakeLists.txt` in the zyn plugins folder.

Is this OK?  Are we still trying to keep Zyn's codebase in a separate repository?  If so, how would I go about issuing this patch so that both our Zyn repo as well as the LMMS repo sees it?

-Tres

**Comment by Lukas-W** [comment] 2015-08-15 14:36
Since it's the `FindFLTK.cmake` script that's broken, I suggest including a fixed/working version in our source tree at [cmake/modules/](https://github.com/LMMS/lmms/tree/master/cmake/modules) and using that.

**Comment by tresf** [comment] 2015-08-15 15:16
I thought of that, but that overrides what we get upstream, so I seems more volatile, no?

This fallback logic will still allow upstream to set the path, but gives a last-ditch effort in fixing this blunder.

If the fallback is acceptable, I just need to know how we commit such things as we once had a rule not to modify the plugins/zyn tree on lmms/lmms.

**Comment by Wallacoloo** [comment] 2015-08-15 16:16
@tresf is it possible to do as Lukas suggests, but have our
`cmake/modules/FindFLTK.cmake` just be a loose wrapper around the system's
module? I.e  in our module, we load the shadowed FindFLTK that's provided
by the system (if that's possible), and if it doesn't return a full path,
correct the path so that it is absolute?

**Comment by tresf** [comment] 2015-08-15 16:31
@Wallacoloo I think what you are describing is CMake + pkg-config loading multiple .cmake files.  I've read the CMake documentation and I can't figure out if multiple `FindXXX.cmake` files are supported.

http://www.cmake.org/cmake/help/v3.0/command/find_package.html

If they are, this would be a bit cleaner (although we may still want to leave a comment behind as a bread crumb trail that we're mucking with the default `FindFLTK.cmake`) but it would essentially do the exact same thing that the above logic is already doing, and worse -- if the `FindFLTK.cmake` module is NOT installed to the system, `FIND_PACKAGE` would actually false-positively succeed, which can be very confusing to someone trying to build LMMS for the first time.

**Comment by tresf** [comment] 2015-08-19 16:37
So I'm still at a bit of a crossroads with this one... 

Should we roll our own `FindFLTK.cmake` when the 334 line file that ships with CMake already works fine for most other systems?

I could also shim it, so to speak by creating a wrapper `FindFLTK-LMMS.cmake` which in turn calls `FindFLTK.cmake`, but then we still have to change the Zyn source code, which was the point of my original question.

Lastly, I have a Msys Support Pull Request #2205  open that requires yet another change to the ZynAddSubFX codebase, so I'd like some direction on how to provide changes to this tree.  Should I submit them all to the Zyn rep and then pull them into our codebase?  Help appreciated! :+1:

**Comment by tresf** [comment] 2015-08-21 13:31
So I'm comparing `FindFLTK.cmake` in CMake 2.8 versus CMake 3.3 and these files are COMPLETELY different... 

I'm still hoping to get some direction here.
 * This bug can be fixed with a quick if statement in our Zyn code
 * We can file this bug upstream and tell CMake 3.3 users to create a work-around until it makes it downstream
 * We can bundle our own `FindFLTK.cmake` with our software, which will for LMMS to ignore any upstream changes that will inevitably occur down the road.

![image](https://cloud.githubusercontent.com/assets/6345473/9409260/26554498-47e7-11e5-90e7-82819358e871.png)

**Comment by Wallacoloo** [comment] 2015-08-21 13:53
I'd just patch the zyn code. If you're really worried about mergability,
you could store the patch in a separate .patch file somewhere in the lmms
tree and then apply it at compile time.

**Comment by tresf** [comment] 2015-08-21 14:02
Ok... Some more research... 

FLTK ships with its own file called `FLTKConfig.cmake`.  Both CMake 2.8 and 3.3 seem to use this file first, so I compared the two files.  The one one Ubuntu 12.04 has the full path whereas the one in 15.10 does not

[`Ubuntu 12.04 FTLKConfig.cmake`](https://gist.githubusercontent.com/tresf/9b6ae990dfc059ad894d/raw/d26547d7df5b30da3a9dc626d954f567afca4e7a/gistfile1.txt) ... :vs: ... [`Kubuntu 15.10 FLTKConfig.cmake`](https://gist.githubusercontent.com/tresf/9b6ae990dfc059ad894d/raw/d26547d7df5b30da3a9dc626d954f567afca4e7a/gistfile1.txt)


This means, the bug is most likely with the `FLTKConfig.cmake` that ships with FLTK for Ubuntu 15.10, not with CMake itself.

@Wallacoloo thanks for the feedback.  This bug now seems like a newly introduced packaging bug with FLTK's 15.10 package.

I'll guess I'll commit the patch to our Zyn plugins folder, since we're in a bit of `limbo` with this bug.

-Tres

**Comment by tresf** [comment] 2015-08-21 17:26
> If you're really worried about mergability,

Well, more a matter of **how** we merge in Zyn changes in general.  We've historically told people to make changes in the Zyn repo, not the LMMS repo and I haven't seen a good solution that allows this fix to be anywhere else.

-Tres

**Comment by tresf** [comment] 2015-08-21 17:53
Since we have no instructions for how to maintain the zyn branch in our wiki and I'm sick of tagging senior developers on the team, I'm committing to the lmms repo.  I'm sure someone will shoot me later. :gun: Sorry in advance.

**Closed** 2015-08-22 00:40 UTC
Labels: bug

**Comment by Lukas-W** [comment] 2015-08-22 10:11
@tresf I just looked at this again and it looks like `plugins/zynaddsubfx/CMakeLists.txt` is a file that's not even part of the zyn repo, but is LMMS only. So no worries there. Only files in `plugins/zynaddsubfx/zynaddsubfx` are zyn files.

> I'm sick of tagging senior developers on the team

We got senior developers? :bike:
