### ISSUE TITLE
Overlay notes - Enhancement

### ISSUE THREAD

**Issue by moestudio2017** [LMMS/lmms#4303] opened 2018-04-19 15:09 UTC
**I need new function , "Overlay notes"**
This function is based on "Domino" , midi sequencer.
[about Domino](http://takabosoft.com/domino)
###### ※You should translate into English with tools.
If we click OverlayButton(in domino , OnionSkill) , we can show other track's note in same piano roll.
**You can not edit notes which you show from other tracks , but it is possible to play notes at same in piano roll. You can change colors of notes.**
![mu001](https://user-images.githubusercontent.com/32843190/39000066-12c25678-442e-11e8-8009-83253b645744.jpg)
[You may read about onion skill from here and I used picture from here.](http://nijimid.cocolog-nifty.com/blog/2012/06/domino-2f6b.html)

**Comment by lukas-w** [comment] 2018-04-19 15:51
Duplicate of #520.

**Comment by musikBear** [comment] 2018-04-22 11:04
..one more idea for implementing this:
After any selection has been made in any piano-rol, an option:
"use selection as ghost" / a key-combo  -is available.
This block-copy will then insert as drawed blocks, in a distinct different color,  at the position of the play-head, in _any_ piano-roll.
The benefit is, that *n copied blocks* can act as ghost, in *same* piano-roll
Method 'remove-ghosts' should then be an option in piano-roll.

**Comment by zonkmachine** [comment] 2019-01-17 18:11
Closed in https://github.com/LMMS/lmms/pull/4575

**Closed by zonkmachine** 2019-01-17 18:11 UTC
Labels: enhancement, gui

**Comment by vlad0337187** [comment] 2021-03-12 07:40
@zonkmachine 

I saw this new button, but didn't guess what is it for until read in release notes.
Would it be a good idea to rename `Set as ghost in Piano-roll` to something like `Display this notes in all piano-rolls` ?

**Comment by zonkmachine** [comment] 2021-03-12 08:39
Ghost notes seem to be a well known term. I didn't know about it but it was one of the most wished for functions and under that name. Maybe improve the documentation instead?

**Comment by musikBear** [comment] 2021-03-12 16:56
> Maybe improve the documentation instead?

Yes. How many DAWs uses the term *Ghost-notes* -Does anyone know if its other DAWs than FLs?
If its a *general used term*, then *use it*, but if it is *exclusive FLs*, then maybe we should use a different term
