### ISSUE TITLE
(beta 1.2.0-RC5) issues with RemoteVstPlugins32

### ISSUE THREAD

**Issue by acidavid** [LMMS/lmms#4204] opened 2018-03-01 02:06 UTC
RemoteVstPlugins32 still running after closing lmms + issues with loading external (downloaded) VSTs that use to load properly in 1.1.3, lmms freezes when loading projects containing these VSTs (cannot identify which VST(s) causes the issues)
**Windows 10 64-bit, lmms 1.2.0 RC5 64-bit**

**Comment by DomClark** [comment] 2018-03-01 14:46
RemoteVstPlugin continuing to run after exit is a long-standing bug, see #1182. As for VSTs causing LMMS to freeze, could you try loading them in one at a time until you find out which ones are responsible?

**Comment by acidavid** [comment] 2018-03-02 22:42
i tried loading every separate VST i used in a blankl project, saving, closing and relaunching to see if it worked: off of them did individually.im guessing there has to be a combination that isn't compatible but i don't know which one since in 1.1.3, everything worked (and still works since i reverted back to stable 1.1.3) properly.

**Comment by acidavid** [comment] 2018-03-02 22:46
also: #1182 is from 2014 and hasn't been updated in a while and it is referencing a version that came out before 1.1

**Comment by DomClark** [comment] 2018-03-02 23:02
Would you mind sharing your project file so we could take a look at it and try to determine the issue that's causing LMMS to hang? You should be able to just drag and drop it into the reply box. Also, whilst it's true that #1182 is rather old and stale, it is still open which indicates we aren't aware of it having been fixed.

**Comment by acidavid** [comment] 2018-03-02 23:07
[dont steal this xd.zip](https://github.com/LMMS/lmms/files/1776805/dont.steal.this.xd.zip)

**Comment by acidavid** [comment] 2018-03-02 23:08
also i dont have the time now but tmr, i might retry to test the individual plugins on projects that actually load in the beta version to try and see what is the issue

**Comment by acidavid** [comment] 2018-03-02 23:10
also warning you:most of these plugins are downloaded so idk if itll open on your software

**Comment by DomClark** [comment] 2018-03-02 23:28
I've downloaded the plugins used and it hangs on my system too. I'll take a look into this. Thank you for providing the project.

**Comment by acidavid** [comment] 2018-03-02 23:36
you're welcome.i hope we can fix these issues before 1.2 releases because these plugins help me out a lot (more user-friendly than stock plugins)

**Comment by acidavid** [comment] 2018-03-02 23:42
@DomClark if you find the specific issue (unless it's a single specific plugin or smth) can you add it to the milestone page please?i don't want this overlooked

**Comment by DomClark** [comment] 2018-03-02 23:49
@acidavid We try not to overlook any issue, but unfortunately we are short on developers and LMMS is something we work on in our spare time. Rest assured we'll consider your issue, but all issues matter to their reporters and whilst we'd of course like to fix all the bugs for the 1.2 release, it just isn't feasible, and so we can't make any promises. That said, I've been trying to sort out most of the VST compatibility issues for 1.2, so unless this bug turns out to be particularly nasty, you might be in luck.

**Comment by acidavid** [comment] 2018-03-02 23:50
thank you

**Comment by acidavid** [comment] 2018-03-02 23:54
ill test myself and try to find the issue.if u find it hmu please

**Comment by PhysSong** [comment] 2018-03-03 08:02
I've downloaded some plug-ins in the project, but I can't reproduce the issue.

FYI, both RC5 and 1.1.3 fails to load `Audiocation Equalizer (stereo)` on my machine. `RemoteVstPlugin32.exe` crashes somewhere in the VST dll, which seems to be called by `pluginDispatch( effEditOpen, 0, 0, m_window );`.

Tested with 64-bit version of LMMS on Windows 10 and wine 3.0.

**Comment by musikBear** [comment] 2018-03-03 14:37
#2774 kind of related -Are you sure there is not a lmms instance running too, because then they are identical
- I dont think i have seen this in RC5

**Comment by DomClark** [comment] 2018-03-03 16:05
The project seems to open properly for me in `stable-1.2` (tested back to RC5.18).
@acidavid Can you see if the problem still occurs with the build in [this comment](https://github.com/LMMS/lmms/pull/4093#issuecomment-359691895)?
@PhysSong That plugin loads fine for me in both 1.1.3 and RC5, 64-bit on Windows 10. Can you debug any further?

**Comment by acidavid** [comment] 2018-03-04 19:17
@PhysSong Ill try running the audiocation eq on the beta but for me it works fine in 1.1.3

**Comment by acidavid** [comment] 2018-03-04 19:18
i had rc5-win64(idk if 17 or 18, it was the latest on the dl page)

**Comment by acidavid** [comment] 2018-03-04 19:23
this might take a while,avast keeps scanning everything i run from this build since it comes from dropbox

**Comment by acidavid** [comment] 2018-03-04 19:24
done, this build runs all my projects fine but the beta build on the official dl page still doesn't

**Comment by DomClark** [comment] 2018-03-04 19:27
Good to hear - when we release RC6 it should all be working then. The one on the download page is effectively RC5.0 - the number after the dot is the number of commits since the last release, and the one you've downloaded has some extra fixes in, which will be in the next release version, but aren't in the old one.

**Comment by acidavid** [comment] 2018-03-04 19:27
ok,this build is waay more stable
i might use this until release(i have a 1.1.3 projects backup so its safe)

**Comment by acidavid** [comment] 2018-03-04 19:27
thank you for the link!

**Comment by acidavid** [comment] 2018-03-04 19:28
if i dont find any other major problems,ill close the thread!

**Comment by DomClark** [comment] 2018-03-04 19:33
No worries - thanks to @PhysSong for building that version. There's one new bug in there that wasn't around before, where LMMS will crash if you cancel exporting a project with VSTs (which will be fixed in RC6), but otherwise it should behave better than RC5. I'm going to close this issue now since the part that wasn't a duplicate is fixed; if you encounter any new problems, please open a new issue as it's easier for us to keep track of things if issues stay on one topic.

**Closed by DomClark** 2018-03-04 19:33 UTC
Labels: bug, vst

**Comment by acidavid** [comment] 2018-03-05 01:09
thanks

**Comment by acidavid** [comment] 2018-03-05 01:11
if that might interest you: in the version im using(the one from dropbox) i noticed if i open a heavy project with lots o vsts it tends to crash but if i open a lighter project that contains some of the hefty free vsts i use but not all at the same time first, i can then open other projects without it crashing
