### ISSUE TITLE
OSX Mavericks not opening

### ISSUE THREAD

**Issue by jhan1997** [LMMS/lmms#1669] opened 2015-01-22 10:14 UTC
I get this error every time I try to open it on my OSX Mavericks Processor 1.4 GHz Intel Core i5:
```
Process:         LMMS [4627]
Path:            /Applications/LMMS.app/Contents/MacOS/LMMS
Identifier:      net.sourceforge.lmms
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [279]
Responsible:     LMMS [4627]
User ID:         501

Date/Time:       2015-01-22 19:10:59.585 +0900
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  E11475D4-FAA2-602C-9FB1-2030A5E837C6

Sleep/Wake UUID: EE27F80F-F9FD-4C5C-99B7-DC46F466D997

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/../Frameworks/libogg.0.dylib
  Referenced from: /Applications/LMMS.app/Contents/MacOS/LMMS
  Reason: Incompatible library version: LMMS requires version 9.0.0 or later, but libogg.0.dylib provides version 6.0.0

Binary Images:
    0x7fff66a09000 -     0x7fff66a3c817  dyld (239.4) <7AD43B9B-5CEA-3C7E-9836-A06909F9CA56> /usr/lib/dyld
    0x7fff8e1ff000 -     0x7fff8e1fffff  com.apple.Cocoa (6.8 - 20) <E90E99D7-A425-3301-A025-D9E0CD11918E> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff90ac0000 -     0x7fff90ac1ff7  libSystem.B.dylib (1197.1.1) <E303F2F8-A8CF-3DF3-84B3-F2D0EE41CCF6> /usr/lib/libSystem.B.dylib

Model: MacBookAir6,2, BootROM MBA61.0099.B12, 2 processors, Intel Core i5, 1.4 GHz, 4 GB, SMC 2.13f9
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (6.30.223.154.65)
Bluetooth: Version 4.2.7f3 14616, 3 services, 15 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD0256F, 251 GB
USB Device: Internal Memory Card Reader
USB Device: USB Optical Mouse
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6
```

**Comment by tresf** [comment] 2015-01-22 13:19
That is the wrong version of `libogg.0.dylib`.  Please try running this from a terminal:

```bash
otool -L /Applications/LMMS.app/Contents/Frameworks/libogg.0.dylib 
```

And you should get something like this:
```
/Applications/LMMS.app/Contents/Frameworks/libogg.0.dylib:
	@executable_path/../Frameworks/libogg.0.dylib (compatibility version 9.0.0, current version 9.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
```

This should report the correct version as `9.2.0`.  If it does not, you have installed `libogg.0.dylib` from elsewhere and it is conflicting, which is not our bug.  Here's an article about something similar on MacPorts:

https://trac.macports.org/ticket/27625

-Tres

**Comment by jhan1997** [comment] 2015-01-23 05:18
Process:         LMMS [748]
Path:            /Applications/LMMS.app/Contents/MacOS/LMMS
Identifier:      net.sourceforge.lmms
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [283]
Responsible:     LMMS [748]
User ID:         501

Date/Time:       2015-01-23 14:16:44.255 +0900
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  E11475D4-FAA2-602C-9FB1-2030A5E837C6


Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/../Frameworks/libogg.0.dylib
  Referenced from: /Applications/LMMS.app/Contents/MacOS/LMMS
  Reason: Incompatible library version: LMMS requires version 9.0.0 or later, but libogg.0.dylib provides version 6.0.0

Binary Images:
    0x7fff6a65f000 -     0x7fff6a692817  dyld (239.4) <7AD43B9B-5CEA-3C7E-9836-A06909F9CA56> /usr/lib/dyld
    0x7fff8f19a000 -     0x7fff8f19afff  com.apple.Cocoa (6.8 - 20) <E90E99D7-A425-3301-A025-D9E0CD11918E> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff91a5b000 -     0x7fff91a5cff7  libSystem.B.dylib (1197.1.1) <E303F2F8-A8CF-3DF3-84B3-F2D0EE41CCF6> /usr/lib/libSystem.B.dylib

Model: MacBookAir6,2, BootROM MBA61.0099.B12, 2 processors, Intel Core i5, 1.4 GHz, 4 GB, SMC 2.13f9
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (6.30.223.154.65)
Bluetooth: Version 4.2.7f3 14616, 3 services, 15 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD0256F, 251 GB
USB Device: Internal Memory Card Reader
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6


I tried your suggestion, and this is the new error message.

**Comment by eagles051387** [comment] 2015-01-23 06:07
I think the biggest question here is where was this library obtained from?

On Fri, Jan 23, 2015 at 6:18 AM, jhan1997 <notifications@github.com> wrote:

> Process: LMMS [748]
> Path: /Applications/LMMS.app/Contents/MacOS/LMMS
> Identifier: net.sourceforge.lmms
> Version: ???
> Code Type: X86-64 (Native)
> Parent Process: launchd [283]
> Responsible: LMMS [748]
> User ID: 501
>
> Date/Time: 2015-01-23 14:16:44.255 +0900
> OS Version: Mac OS X 10.9.5 (13F34)
> Report Version: 11
> Anonymous UUID: E11475D4-FAA2-602C-9FB1-2030A5E837C6
>
> Crashed Thread: 0
>
> Exception Type: EXC_BREAKPOINT (SIGTRAP)
> Exception Codes: 0x0000000000000002, 0x0000000000000000
>
> Application Specific Information:
> dyld: launch, loading dependent libraries
>
> Dyld Error Message:
> Library not loaded: @loader_path/../Frameworks/libogg.0.dylib
> Referenced from: /Applications/LMMS.app/Contents/MacOS/LMMS
> Reason: Incompatible library version: LMMS requires version 9.0.0 or
> later, but libogg.0.dylib provides version 6.0.0
>
> Binary Images:
> 0x7fff6a65f000 - 0x7fff6a692817 dyld (239.4) /usr/lib/dyld
> 0x7fff8f19a000 - 0x7fff8f19afff com.apple.Cocoa (6.8 - 20)
> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
> 0x7fff91a5b000 - 0x7fff91a5cff7 libSystem.B.dylib (1197.1.1)
> /usr/lib/libSystem.B.dylib
>
> Model: MacBookAir6,2, BootROM MBA61.0099.B12, 2 processors, Intel Core i5,
> 1.4 GHz, 4 GB, SMC 2.13f9
> Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
> Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD,
> 0x483943434E4E4E384A544D4C41522D4E544D
> Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD,
> 0x483943434E4E4E384A544D4C41522D4E544D
> AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117),
> Broadcom BCM43xx 1.0 (6.30.223.154.65)
> Bluetooth: Version 4.2.7f3 14616, 3 services, 15 devices, 1 incoming
> serial ports
> Network Service: Wi-Fi, AirPort, en0
> Serial ATA Device: APPLE SSD SD0256F, 251 GB
> USB Device: Internal Memory Card Reader
> USB Device: BRCM20702 Hub
> USB Device: Bluetooth USB Host Controller
> Thunderbolt Bus: MacBook Air, Apple Inc., 23.6
>
> I tried your suggestion, and this is the new error message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1669#issuecomment-71149015>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment] 2015-01-23 14:18
> I think the biggest question here is where was this library obtained from?

@eagles051387 If you have nothing to add, please go away. :)

> I tried your suggestion, and this is the new error message.

@jhan1997 I didn't make any suggestions, I just linked a macports article that describes why this happens.    Here it is again.

https://trac.macports.org/ticket/27625

Read this article please.  It describes what causes this and possible workarounds.  It sounds like your system has libogg installed elsewhere.  If this is true, we can't fix this, you need to, and the best way is to read up on how to resolve library conflicts in OSX.

**Comment by tresf** [comment] 2015-01-23 14:24
So I believe you or someone you know installed software on your machine with provides `libogg` and LMMS is using that rather than the version we bundle.

If you can locate the other `libogg` on your system, you can determine how it got installed and take action to remove it, but we have no way of knowing where it is or how it got there, so we can't fix this bug for you.

Duplicate libraries isn't new to OSX.  This happens in Linux and Windows too.  Windows users refer to this as "DLL HELL".  To fix this problem you need to research a bit on what you've done that may have placed the wrong `libogg` (and specifically where it is placed) on your system and once you provide that info, we may be able to help from there.  It is very unlikely that this problem is caused by our software, but rather a conflict with software you already have installed.

**Comment by tresf** [comment] 2015-01-30 20:27
Closing as invalid for now.  If you receive more information about your setup and have evidence that we can fix this on our end, please reopen this bug report.

**Closed by tresf** 2015-01-30 20:27 UTC
Labels: support request
