### ISSUE TITLE
Ability to move/copy effects between mixer channges

### ISSUE THREAD

**Issue by Calendis** [LMMS/lmms#5913] opened 2021-02-18 21:39 UTC
(I searched for this suggestion and didn't find it, but I may have missed it as a lot of results came up that were unrelated)

### Enhancement Summary
After adding an effect to either a mixer channel or an instrument and setting all its values, I would like to be able to right click it, copy and then right click in another effects rack (either in a mixer channel or instrument effects) and select 'paste'.

#### Justification
When playing around with mixing several instruments and mixer channels this is something I want to do fairly often. Right now the fastest way is to create a new effect and copy each value from the old effect manually. This gets very tedious with multiple effects

#### Mockup
[copy](https://i.imgur.com/mic3GGf.png)
[paste](https://i.imgur.com/jRhWpox.png)
(self-explanatory)

**Comment by Spekular** [comment] 2021-02-20 12:09
Closing as duplicate of #1278 and #59 which have been consolidated into #4877, will link this from there.

**Closed by Spekular** 2021-02-20 12:09 UTC
Labels: enhancement
