### ISSUE TITLE
VeSTige seems to save the original path of the assigned VST plugin

### ISSUE THREAD

**Issue by JimmyKenMerchant** [LMMS/lmms#6271] opened 2022-01-13 02:42 UTC
### Bug Summary
VeSTige seems to save the original path of the assigned VST plugin in the system
#### Steps to reproduce
1. Make a project using VeSTige with loading any VST instrument (VSTi) plugin.
2. Save the project.
3. Transfer the project (a .mmpz file) to another computer or system, .e.g, Linux to Windows OS. No matter whether another one has the VSTi plugin or not.
4. On another computer or system, open the project.
5. Read error messages and you can see the displayed path is your old one.
#### Expected behavior
VeSTige should search VST plugins using the path you set in "VST-PLUGIN DIRECTORY" on the "Setup LMMS" menu of LMMS.
#### Actual behavior
VeSTige searches VST plugins using the original path in a .mmpz file. The original path may include a user name of the old computer or system.
#### Screenshot
N/A
#### Affected LMMS versions
1.2.2 on Linux x86_64
#### Logs
N/A

**Comment by Monospace-V** [comment] 2022-01-13 03:03
VST-Plugin directory is for VST-FX. Even with FX, I think it saves exact path. Caching VST plugin locations etc so as to run them from any path is a feature that has been suggested before. This is a virtual duplicate of other suggestions, that have mentioned saving relative VST path (issue 4646) (can be done, I think, if VST is saved in Samples folder of lmms), all the way to being able to run a VST if detected wherever in the system it is (issue 4907).
Requesting you to look for others asking the same thing before filing bug reports.

**Comment by JimmyKenMerchant** [comment] 2022-01-13 04:07
> VST-Plugin directory is for VST-FX. Even with FX, I think it saves exact path. Caching VST plugin locations etc so as to run them from any path is a feature that has been suggested before. This is a virtual duplicate of other suggestions, that have mentioned saving relative VST path (issue 4646) (can be done, I think, if VST is saved in Samples folder of lmms), all the way to being able to run a VST if detected wherever in the system it is (issue 4907). Requesting you to look for others asking the same thing before filing bug reports.

this is an issue specified on VeSTige. Saving an absolute path of the old path in a project file may expose a user name of Linux. This issue may cause any privacy breach.

**Comment by JimmyKenMerchant** [comment] 2022-01-13 05:22
Note that the function around this issue seems to be 'vestigeInstrument::loadFile( const QString & _file )' in "master/plugins/vestige/vestige.cpp". I find out Line No. 366 shows the identical error message on opening project file. 'vestigeInstrument::loadSettings( const QDomElement & _this )' uses 'loadFile' and the path is quoted from '_this.attribute( "plugin" )'.

**Comment by Spekular** [comment] 2022-01-13 06:02
Fixed in 1.3.

**Closed by Spekular** 2022-01-13 06:02 UTC
Labels: bug

**Comment by JimmyKenMerchant** [comment] 2022-01-13 11:09
I confirmed this issue is fixed in 1.3.0-a, and 17565ca was the commit. lmms/src/core/PathUtil.cpp makes a virtual relative path, 'uservst:*.dll', and vanishes an original absolute path including a user name. I think it would be complicated and I may suggest a patch for 1.2.2.
