### ISSUE TITLE
Crashing on export, Windows x64 1.2.0-RC1

### ISSUE THREAD

**Issue by joeboestar** [LMMS/lmms#2828] opened 2016-06-06 23:08 UTC
I'm trying to make a song in the latest LMMS beta. However, upon exporting my song to .wav or .ogg, LMMS crashes. I'm not sure if LMMS is still being supported since it hasnt had a stable release in a while but I like using LMMS and I find it easier than FL Studio. I look forward to future updates to this amazing piece of software.

**Comment by tresf** [comment] 2016-06-06 23:30
> I'm not sure if LMMS is still being supported since it hasnt had a stable release in a while but I like using LMMS and I find it easier than FL Studio. I look forward to future updates to this amazing piece of software.

Yes, we're still working hard on it.  We'll get an updated copy (e.g. RC2) out soon.  Sorry for the delay.

**Comment by zonkmachine** [comment] 2017-06-19 08:49
@joeboestar rc4 is under way. I'm closing this as it's probably a duplicate of https://github.com/LMMS/lmms/issues/2457 which has been fixed already. Please reopen if this is still an issue on the latest version: https://lmms.io/download/#windows

**Closed by zonkmachine** 2017-06-19 08:49 UTC
Labels: duplicate
