### ISSUE TITLE
Mallets on master build causes a crash

### ISSUE THREAD

**Issue by eagles051387** [LMMS/lmms#1924] opened 2015-04-05 07:26 UTC
I am running this on mac osx 10.10 but with a build from this morning I am seeing an interesting issue, while trying out a master build running the debug build through lldb 

To reproduce simply add mallets to the project and you instantly get a lock up and lmms crashes instantly.

What lldb shows is the following

VST sync support disabled in your configuration
Couldn't create MIDI-client, neither with ALSA nor with OSS. Will use dummy-MIDI-client.
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
Process 11352 stopped
* thread #13: tid = 0x2145d, 0x0000000100675e2f QtGui`qt_mac_cg_context(QPaintDevice const*) + 47, name = 'InstrumentLoaderThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x24)
    frame #0: 0x0000000100675e2f QtGui`qt_mac_cg_context(QPaintDevice const*) + 47
QtGui`qt_mac_cg_context(QPaintDevice const*) + 47:
-> 0x100675e2f:  movl   0x24(%r12), %ecx
   0x100675e34:  xorl   %ebx, %ebx
   0x100675e36:  testl  %ecx, %ecx
   0x100675e38:  jne    0x100675ed9               ; qt_mac_cg_context(QPaintDevice const*) + 217

**Comment by Wallacoloo** [comment] 2015-04-05 07:32
Could it be a duplicate of #1660 ? Did you install libstk? I believe there is now a warning dialog for when you have only the stk headers & not the shared objects installed, but it's too easy to click "don't show again" and close it.

**Comment by eagles051387** [comment] 2015-04-05 07:35
Let me try and reproduce in stable and see if the same thing happens. Then
I will report back.

On Sun, Apr 5, 2015 at 9:32 AM, Colin Wallace <notifications@github.com>
wrote:

> Could it be a duplicate of #1660
> <https://github.com/LMMS/lmms/issues/1660> ? Did you install libstk? I
> believe there is now a warning dialog for when you have only the stk
> headers & not the shared objects installed, but it's too easy to click
> "don't show again" and close it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1924#issuecomment-89730309>.
>



-- 
Jonathan Aquilina

**Comment by eagles051387** [comment] 2015-04-05 07:39
I can confirm that I have STK already installed according to the apple
specific documentation on the wiki. In process of recompiling for stable to
see if the issue is present there.

On Sun, Apr 5, 2015 at 9:34 AM, Jonathan Aquilina <eagles051387@gmail.com>
wrote:

> Let me try and reproduce in stable and see if the same thing happens. Then
> I will report back.
>
> On Sun, Apr 5, 2015 at 9:32 AM, Colin Wallace <notifications@github.com>
> wrote:
>
>> Could it be a duplicate of #1660
>> <https://github.com/LMMS/lmms/issues/1660> ? Did you install libstk? I
>> believe there is now a warning dialog for when you have only the stk
>> headers & not the shared objects installed, but it's too easy to click
>> "don't show again" and close it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/LMMS/lmms/issues/1924#issuecomment-89730309>.
>>
>
>
>
> --
> Jonathan Aquilina
>



-- 
Jonathan Aquilina

**Comment by Wallacoloo** [comment] 2015-04-05 07:47
The  `QPixmap: It is not safe to use pixmaps outside the GUI thread` errors are pretty interesting too though. I've been getting those on Linux. I looked into them, and at least [one person](http://stackoverflow.com/a/24292473/216292) thinks Qt is incorrect in not making this error fatal.

I've been meaning to look into those for a while now, but since that's being printed from within the Qt libraries, I'm not sure where to put a breakpoint in order to trace down the incorrect LMMS code.

However, I'm guessing that isn't the issue *here*, because multithreading issues like that tend to cause intermittent glitches rather than 100% reproducible crashes.

**Comment by eagles051387** [comment] 2015-04-05 07:53
This seems to be 100% reproducible though. What isnt clear what aspect of
the GUI isnt running in the gui thread.

On Sun, Apr 5, 2015 at 9:47 AM, Colin Wallace <notifications@github.com>
wrote:

> The QPixmap: It is not safe to use pixmaps outside the GUI thread errors
> are pretty interesting too though. I've been getting those on Linux. I
> looked into them, and at least one person
> <http://stackoverflow.com/a/24292473/216292> thinks Qt is incorrect in
> not making this error fatal.
>
> I've been meaning to look into those for a while now, but since that's
> being printed from within the Qt libraries, I'm not sure where to put a
> breakpoint in order to trace down the incorrect LMMS code.
>
> However, I'm guessing that isn't the issue *here*, because multithreading
> issues like that tend to cause intermittent glitches rather than 100%
> reproducible crashes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1924#issuecomment-89730762>.
>



-- 
Jonathan Aquilina

**Comment by Wallacoloo** [comment] 2015-04-05 07:56
Right. The QPixmap messages are likely a red herring here.

**Comment by eagles051387** [comment] 2015-04-05 08:00
Turns out for some reason I have something missing with STK as I get a
warning box that my STK installation seems to be incomplete. Please makes
sure the full stk package is installed!

The one thing I do not get is the crash like i was on master. Let me try
run stable through lldb on mac.

On Sun, Apr 5, 2015 at 9:56 AM, Colin Wallace <notifications@github.com>
wrote:

> Right. The QPixmap messages are likely a red herring here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1924#issuecomment-89731958>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment] 2015-04-05 12:27
May be as simple as the rawwaves missing.  IIRC, the current install script copies them into the bundle.  There may be a better way to do this, but we don't really have Mallets issues, do you may be chasing a unicorn.

**Comment by eagles051387** [comment] 2015-04-05 18:33
I think as you mentioned in your other email I will see if merging 1.1 changes back into master will solve the issues in seeing

**Comment by tresf** [comment] 2015-04-05 21:40
So you are going to try a complicated merge before looking at the rawwaves directory? :)

**Comment by eagles051387** [comment] 2015-04-06 07:00
If you want me to I can but I had tried it and obviously there were merge
conflicts so I recloned my fork as you said in the other post its probably
best left to someone whose versed more so with the changes that have been
made. the funny thing is on my fork I made no changes. Would it be safe to
say that in terms of the conflicts that it is safe to take the changes that
were pulled in from the stable 1.1 branch?

On Sun, Apr 5, 2015 at 11:40 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> So you are going to try a complicated merge before looking at the rawwaves
> directory? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1924#issuecomment-89857811>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment] 2015-04-06 14:12
I just did a clean build with Lion and `master`.  No problems with mallets.

**Closed by tresf** 2015-04-06 14:12 UTC

**Comment by eagles051387** [comment] 2015-04-06 15:22
Could this be related to me doing a debug build

**Comment by tresf** [comment] 2015-04-06 16:27
> Could this be related to me doing a debug build

Just tried, mallets work fine, so not directly.

As @Wallacoloo and myself said, this is mostly likely the rawwaves not being in the right place.  You can set this manually via the config but I still don't understand what you are doing because you seems to have spent a lot of time on Mallets and I'm taking a lot of time reproducing and we don't have bugs open for that plugins.... I digress... 

The rawwaves are copied in here:  https://github.com/LMMS/lmms/blob/master/data/scripts/create_apple_bundle.sh.in#L66


Unfortunately, this never happens if you don't run from the bundle (created on the Desktop currently).  And the bundle likely strips out the debug symbols, putting you in a catch-22.  This is because apple (like Windows) really prefers to be bundled with its dependent libraries.  I do that manually right now via a shell script.  If you know of a better way, please fix the code. :+1:   In the mean time, I still think you are chasing a unicorn, so to speak.

**Comment by eagles051387** [comment] 2015-04-06 17:05
In that case for now this issue can be closed if you deem it fit to be
closed.

On Mon, Apr 6, 2015 at 6:27 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> Could this be related to me doing a debug build
>
> Just tried, mallets work fine, so not directly.
>
> As @Wallacoloo <https://github.com/Wallacoloo> and myself said, this is
> mostly likely the rawwaves not being in the right place. You can set this
> manually via the config but I still don't understand what you are doing
> because you seems to have spent a lot of time on Mallets and I'm taking a
> lot of time reproducing and we don't have bugs open for that plugins.... I
> digress...
>
> The rawwaves are copied in here:
> https://github.com/LMMS/lmms/blob/master/data/scripts/create_apple_bundle.sh.in#L66
>
> Unfortunately, this never happens if you don't run from the bundle
> (created on the Desktop currently). And the bundle likely strips out the
> debug symbols, putting you in a catch-22. This is because apple (like
> Windows) really prefers to be bundled with its dependent libraries. I do
> that manually right now via a shell script. If you know of a better way,
> please fix the code. [image: :+1:] In the mean time, I still think you
> are chasing a unicorn, so to speak.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1924#issuecomment-90132636>.
>



-- 
Jonathan Aquilina
