### ISSUE TITLE
The context menu in FX Mixer faders shows fractional values, but uses % as unit.

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4216] opened 2018-03-05 16:14 UTC
The context menu on the faders of any (input, master) channels of the FX Mixer shows values in fraction, but then uses the % unit.
 
Reset (1%)
Copy value (1.5%)
Paste value (1.5%)

**Desired:** 
Either use fraction values or use true percent values. 
For example, 1.00 means 100%, 1.25 means 125%, 0.75 means 75% etc.

So, the context menu should be either-
Reset (100 %)
Copy value (150 %)
Paste value (150 %)

OR just as a dimensionless fraction:
Reset (1.000)
Copy value (1.500)
Paste value (1.500)

(BTW the tooltip displays values with one decimal. That's not needed. Round it off to whole number.)

**Comment by tresf** [comment] 2018-03-05 16:47
Duplicate of #2340.

**Closed by tresf** 2018-03-05 16:47 UTC
Labels: bug, duplicate
