### ISSUE TITLE
Pattern Editor - Copy and paste of patterns is broken

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#6756] opened 2023-07-01 20:24 UTC
### Bug Summary

Copy and paste of patterns in the Pattern Editor is broken.

#### Steps to reproduce

In the Pattern Editor. With the context menu, copy a pattern from one pattern to the other. Can't do it!

#### Affected LMMS versions

The issue was introduced in b64fe8e7c0afc33ead8c88761efbd71358656890  _Update: On the original PR https://github.com/LMMS/lmms/pull/5627, it's commit ebc808ef5745657aaec2acb8809a007729d6dd17 that is responsible._
@IanCaio 

```
b64fe8e7c0afc33ead8c88761efbd71358656890 is the first bad commit

commit b64fe8e7c0afc33ead8c88761efbd71358656890
Author: IanCaio <iancaio_dev@hotmail.com>
Date:   Sat Oct 10 03:17:25 2020 -0300

    Refactor Clipboard methods (#5627)
    
    * Moves mimeType from StringPairDrag to Clipboard
    
    * Simplifies decodeKey and decodeValue methods
    
    * Adds method to copy a string to clipboard
    
    * Adds method to copy a string pair to the Clipboard
    
    * Adds convenience methods to Clipboard.h to retrieve the QMimeData from the clipboard and checking whether a particular mime type format is present on it
    
    * Uses only the TCOV copy/paste methods on the song editor
    To keep consistency on the behavior of the TCOV copy and paste operations, we now only use the TCOV::copy() and TCOV::paste() methods for copying both individual and multiple TCOs.
    
    * Removes obsolete TrackContentObject::cut() and merge copy() and paste() methods to single function TrackContentObject::copyStateTo()
    
    * Adds Clipboard::getString method to get data for particular mime type
    
    * Makes AutomatableModelView.cpp use the Clipboard class instead of calling Qt clipboard directly


```

**Comment by zonkmachine** [comment] 2023-08-01 18:20
I probed this further. On the PR it's commit ebc808ef5745657aaec2acb8809a007729d6dd17 that is responsible.
`1 changed file with 16 additions and 43 deletions`
```

 Uses only the TCOV copy/paste methods on the SE

	To keep consistency on the behavior of the TCOV copy and paste operations, we now only use the
        TCOV::copy() and TCOV::paste() methods for copying both individual and multiple TCOs. The TCO::copy()
        and TCO::paste() methods are still kept since they are used on the src/track/BBTrack.cpp file.

TODO:
	Since the TCO::copy() and TCO::paste() are now only used for internal operations that have
        nothing to do with Userland clipboard operations, I believe there's no need to change them to
        use the system's clipboard (if they do, cloning a BB Track would clear the clipboard which is a
        somewhat undesired behavior). However, if they don't use the clipboard they shouldn't be relying
        on the Clipboard.h class at all, so a small refactor would have to be done to move away from it.
        I believe renaming would also be interesting since now their behavior resembles more a
        copyState and pasteState operation.
```

**Comment by Rossmaxx** [comment] 2023-08-09 12:18
Been looking at some suspected code for trying to track down the missing stuff but couldn't understand what was missed (mainly because how everything changed after reorg and comparing the diff of that pr and master makes little sense). If you got anything more, please post it here.

**Comment by zonkmachine** [comment] 2023-08-09 13:57
The changes from https://github.com/LMMS/lmms/commit/ebc808ef5745657aaec2acb8809a007729d6dd17 are now in https://github.com/LMMS/lmms/blob/master/src/gui/clips/ClipView.cpp

**Comment by Rossmaxx** [comment] 2023-08-09 15:29
Update: i probed a bit more in the issue tracker and found #6002, apparently, this issue is a duplicate of that one. Closing or are you leaving this here.

> The changes from ebc808e are now in https://github.com/LMMS/lmms/blob/master/src/gui/clips/ClipView.cpp

I looked that file and found very little related code. Might have been moved somewhere in between the refactor.

**Closed** 2023-08-09 15:53 UTC
Labels: bug
