### ISSUE TITLE
Presets are glitchy in library but sound good in B+B editor

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2434] opened 2015-10-31 22:32 UTC
BitInvader/Bell, LB302/AngryLead, Monstro/Phat - these sound really bad under My Presets. Most of the presets sound glitchy (and with much more volume) under My Presets but sound completely clean in B+B editor or while playing. LMMS master with SDL or Pulseaudio on Kubuntu 15.04.

**Comment by tresf** [comment] 2015-11-02 14:38
@karmux is there a chance this is a duplicate of #1644?

The bug stores an arpeggio in memory and then plays it on top of another preset.  This is most obvious when clicking through the file browser and a few arpeggio presets are in the listing.

**Comment by karmux** [comment] 2015-11-05 17:46
@tresf , no I don't think so. If I open LMMS and play sound that don't have any arpeggio then it already sounds bad.

**Comment by musikBear** [comment] 2015-11-06 10:33
@tresf perhaps a comprehensive post for everything that has to do with preview? imo preview needs a re-thinking /workover. 
* crashing with multi-click
* vst-orphans
* artefacts, like the arp issue
are those i remember right now

**Comment by Umcaruje** [comment] 2016-01-24 22:09
@karmux please provide exact steps to reproduce, and if possible an audio recording of the glitched presets.

**Comment by karmux** [comment] 2016-01-25 22:04
@Umcaruje, I recorded BitInvader/Bell and Monstro/Phat from library and then from song editor. Steps to reproduce is just to click on sample.
http://www.upload.ee/files/5511092/glitchy.ogg.html

**Comment by Fastigium** [comment] 2016-02-17 17:27
Reproduced and confirmed for BitInvader/bell.xpf and Monstro/Phat.xpf on Ubuntu 14.04.4 x86_64. Switching the audio interface doesn't seem to matter (tried SDL, alsa and pulseaudio).

Steps to reproduce:

1. Preview the preset by clicking and holding it in My Presets on the left. Note how it sounds.
2. Drag the preset to the song editor to create a new track.
3. Open the instrument panel by clicking the track name.
4. Press and hold the Y key to produce the exact same note as the preview does. Check if it sounds different.

**Comment by tresf** [comment] 2016-02-17 17:42
Can we please get confirmation that this bug is new to the `master` branch and not also present with `stable-1.1` ?

**Comment by Fastigium** [comment] 2016-02-17 18:20
New to `master`; in `stable-1.1` the preview and the song editor version sound identical (SDL audio interface).

**Comment by zonkmachine** [comment] 2016-02-17 18:29
I'll try and bisect this.

**Comment by zonkmachine** [comment] 2016-02-17 19:12
> LB302/AngryLead

There is a noise hit in the beginning of AngryLead. If you drop it on a track that noise is played isolated without the actual preset... but the noise is about an octave lower.

**Comment by zonkmachine** [comment] 2016-02-17 23:12
> There is a noise hit in the beginning of AngryLead.

Because it's got a plate reverb. There's a transient/glitch being fed into the reverb. I interpret this as the noise belonging to the instrument... So the noise is from setting up the sound from the previous preset. [This](https://github.com/LMMS/lmms/issues/1644#issuecomment-185332129) comment from Fastigium is relevant here then.

**Comment by zonkmachine** [comment] 2016-02-17 23:32
> New to master; in stable-1.1 the preview and the song editor version sound identical (SDL audio interface).

I saw this in 1.0.3 . I only got deep into lb302 though and it could off course be up to things of it's own.

**Comment by Fastigium** [comment] 2016-02-18 14:44
Interesting observation: for TripleOscillator presets, this bug appears to occur whenever stacking is enabled, even if it's on octave with range 1 (i.e. it plays exactly the same note as it would without stacking). I made a very simple preset that only plays a sine on 1 oscillator, then saved it both without and with stacking. The stackless version previewed fine, the stacked version sounded like crap and gave a waveform like this:

![crapsine](https://cloud.githubusercontent.com/assets/10221829/13146257/218b2228-d655-11e5-8383-21e6ce4cd5cc.png)

I've been hunting through the code for possible causes, but haven't found any so far. It's a complicated beast, and the commits that introduced it are so huge that it doesn't help much in pinpointing. I can confirm that the merging of #1088 introduced the issue, but haven't bisected further because this computer compiles so slowly :sleeping:

**Comment by tresf** [comment] 2016-02-18 14:53
>  I can confirm that the merging of #1088 introduced the issue

AFAIK, MemoryManager went live with 1.1, so this is also present in stable-1.1, no?

**Comment by Fastigium** [comment] 2016-02-18 15:04
@tresf: `stable-1.1` does not appear to have `include/BufferManager.h`, so I guess not.

**Comment by tresf** [comment] 2016-02-18 15:08
> @tresf: stable-1.1 does not appear to have include/BufferManager.h, so I guess not.

:+1:

**Comment by Fastigium** [comment] 2016-02-18 16:28
Some progress: if I disable the BufferManager by making BufferManager::acquire() a wrapper around MM_ALLOC and BufferManager::release() a wrapper around MM_FREE, the previews are fine again. This suggests that somehow, a single buffer ends up being used in multiple places. Now to find where that happens!

**Comment by Fastigium** [comment] 2016-02-18 19:38
Yaaaaaar! Found it! PresetPreviewPlayHandle keeps a buffer and shares it with the NotePlayHandle it creates. However, when stacking is enabled, that NotePlayHandle releases its buffer and delegates rendering tasks to its subnotes. PresetPreviewPlayHandle still holds a pointer to that released buffer, though, and is attached to an AudioPort, which means that the released buffer is added to the master channel every mixing round. Any PlayHandle or AudioPort may acquire this buffer at any moment and fill it with anything it likes. This causes the crazy distortions as seen on the screenshot above.

I first tried to solve it by checking the usesBuffer() method of the NotePlayHandle in PresetPreviewPlayHandle::play(), but this does not solve another bug: a TripleOscillator preset with a release > 0 in its envelope is cut off hard at mouse button release when no stacking or arpeggio is enabled. In pull request #2586 I fixed both bugs by using a different solution. Testing welcome, I do hope I didn't break anything while fixing this :sweat_smile:

**Comment by karmux** [comment] 2016-02-18 20:30
@Fastigium , awesome! :+1: Previews sound so clean now :smiley:

**Comment by Fastigium** [comment] 2016-02-19 10:47
@karmux Cool! Thanks for testing!

**Comment by musikBear** [comment] 2016-02-19 12:38
@Fastigium et al
:tada: :balloon: :gem:

**Comment by tresf** [comment] 2016-02-19 13:23
@Fastigium per the below change, should this method eventually be removed?  Shall we mark it as such (e.g. `// TODO: Remove`)

```diff
void PresetPreviewPlayHandle::play( sampleFrame * _working_buffer )
  {
-	m_previewNote->play( _working_buffer );
+	// Do nothing; the preview instrument is played by m_previewNote, which
+	// has been added to the mixer
  }
```

**Comment by Fastigium** [comment] 2016-02-19 17:11
@tresf Unfortunately all PlayHandles are required to implement a play() method per https://github.com/LMMS/lmms/blob/master/include/PlayHandle.h#L99. The problem is at a more conceptual level; PresetPreviewPlayHandle is not used as a PlayHandle anymore in my solution. I don't see a way to keep it in use without coupling it more closely with NotePlayHandle, and that seems Bad Practice. To really fix this conceptually, PresetPreviewPlayHandle's functionality should probably be moved into [PreviewTrackContainer](https://github.com/LMMS/lmms/blob/master/src/core/PresetPreviewPlayHandle.cpp#L43) somehow. That's not an entirely trivial operation, though.

**Comment by tresf** [comment] 2016-02-19 17:21
@Fastigium  :+1:

**Closed** 2016-02-23 15:52 UTC
Labels: bug, critical
