### ISSUE TITLE
SFXR output out of range (formerly "Chiptune hating bug")

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1877] opened 2015-03-16 23:49 UTC
This stroke me first in LMMS 1.1.3, then I downgradeed to 1.1.0 (ubuntu1-stable)

I wanted to add a Dual Filter effect to my chiptune track "New View", but a fraction of a second later, everything has gone mute. No sound, no signal on the peak meters in the Mixer, nothing.
I deleted the effect - the sound is back. I tried Calf Filter, GLAME lowpass. I also added C* Plate 2x2, which have worked for a few seconds, and then all has gone mute again. I added Fast Lookahead Limiter, and it didn't trigger the problem, I render the whole track with it fine, however any other plugin I tried (Freeeverb, Calf Reverb) made the master go silent.

Muting the effect plugin bring the sound back. I did a quick tet with JACK Bitmeter - no NANs, no denormals, no infinite numbers. Just pure nothingness.

What's strange, this problem doesn't happen in other projects. I suspect SFXR. I made a track with Monstro alone and it didn't produce such effect, not to mention 2 albums made exclusively with ZynAddSubFX - I think it's clean in this regard.

Here's a project file that manifests the problem:
https://lmms.io/lsp/?action=show&file=6550

**Comment by Sti2nd** [comment] 2015-03-17 08:51
I think it is strange to downgrade to test bugs... you haven't told use this happens in 1.1.0

**Comment by softrabbit** [comment] 2015-03-17 10:22
Confirmed on master. Applying C*Plate 2x2 or CALF Reverb to SFXR on the "kick" track in BB editor kills sound. Dual Filter doesn't, at least not on this system.

Routing the kick track to a mixer channel and putting the plugin there mutes the sound as well, and the channel will remain broken after removing the kick track from it.

Did a fresh project with 2 random SFXR patches, worked fine. A fresh project with just that kicker sound was affected.

I'd say SFXR outputs illegal values if the knobs are in the right position. And that might put some plugins in a bad state. Once you hit infinity no amount of zeroes will resurrect it.

@unfa, would you mind changing the title to "SFXR output out of range" or something like that?

**Comment by musikBear** [comment] 2015-03-17 12:04
could you check and see if you have a next too horisontal red visualisation, just before the sound disapear, then i know the reason. Happend often with previous version of kicker, and low-pass filters
It is actually not silent. The sound is 'just' too low to be audiable. 'just' in quotation, because it is a serious bad situation. Both speakers AND **HEARING!!!!** can be damagded!!
If my gues is correct, then you would get 'normal' replay after several minutes -eg *when the oscilation of this serious slow sound terminates*
Do NOT du this with more than a few % of master volume!

**Comment by softrabbit** [comment] 2015-03-17 12:44
SFXR can't output values outside the +/-1.0 range, they are checked just before putting them in the output buffer. So infinities are taken care of, but NaN (Not a Number) can still get through, as it's neither >1.0 or <-1.0. 

It basically happens like this: Envelope times set to 0 lead to division by 0, which returns NaN. And as NaN is of the contagious kind (any operation including it will return NaN), all plugins with some kind of history involving the input signal (many filters, most reverbs) will be affected. Any plugin operating just on its input value should be fine-ish, as long as the NaN input is a temporary thing.

**Comment by tresf** [comment] 2015-04-13 20:55
Closed via #1887.  Please reopen if this resurfaces or if a scenario was missed (as explained in #1887).

**Closed by tresf** 2015-04-13 20:55 UTC
