### ISSUE TITLE
Vinyl effect does not stop.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4700] opened 2018-11-05 05:28 UTC
Hi guys. While using LMMS in one of my projects, by chance I found an error with the plugin '' Vynil ''.

![efecto vinilo error](https://user-images.githubusercontent.com/26127693/47979301-663d3580-e090-11e8-8ffa-2ab51d2afbb9.png)

And is that the plugin does not stop, not even having the mix stopped, right now I'm not playing the song and the LP disk effect is still sounding, and the only way to turn it off without closing LMMS is to turn it off or remove it, so far I did not have that with any other plugin, technically I do not know what happens but I think this is not normal. that happened to me in LMMS 1.2.0 RC7 in AV Linux on a Laptop. What happens here, can this happen to me with other plugins? Do the plugins still work even when the song is stopped ?. regards

**Comment by PhysSong** [comment] 2018-11-05 06:33
Duplicate of #3170.

**Closed by PhysSong** 2018-11-05 06:33 UTC

**Comment by zonkmachine** [comment] 2019-01-02 17:06
> can this happen to me with other plugins?

Yes. Turn up the `noise` knob on the native Flanger pluggin.


> Do the plugins still work even when the song is stopped ?

Yes and this is why this happens. Unless you have the setting `Keep effects running even without input ` unchecked AND turn up the gate a bit on the sound generating unit.
