### ISSUE TITLE
Double delete in xpressive

### ISSUE THREAD

**Issue by justnope** [LMMS/lmms#4379] opened 2018-05-28 05:16 UTC
XpressiveHelpView will already be deleted by qt. remove:
```

 __attribute__((destructor)) static void module_destroy()
 {
 	XpressiveHelpView::finalize();
 }
```

**Comment by PhysSong** [comment] 2018-05-28 05:28
@justnope As @zonkmachine said, this looks like a duplicate of #3951. Sorry for saying you to open a duplicate issue.

**Closed by PhysSong** 2018-05-28 05:28 UTC
