### ISSUE TITLE
BB Editor opening with wrong width

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#2241] opened 2015-08-08 01:16 UTC
When opening the Beat+Bassline Editor for the first time, it is narrower than it should. When it is moved, however, it changes to the right width, although the track view inside it is not automatically adjusted. The track view is only set to the right width when a note is added on it.

**Update 1:**
The editor opens with the correct width by commenting out the only line of code in the `BBTrackContainerView::loadSettings()` method, which may be a useful hint:
```C++
MainWindow::restoreWidgetState(parentWidget(), element);
```
**Update 2:**
The problems seems to be caused more precisely by `SerializingObject` when the project is loaded. The editor opens with the correct width, however, if the user "adjusts" its width (by moving), saves the project and reloads it.

**Update 3:**
All right, the wrong width value is loaded from the project file (in the case of the empty project when the program starts without any command line parameter, the value is loaded from the default template). This can be demonstrated by manually changing the value of the `width` parameter of a `trackcontainer` tag inside a `bbtrack` block in an uncompressed project file.

**Possible solution:**
When loading a project, check if the value loaded for the width of the Beat+Bassline Editor is lower than the minimum allowed and adjust it if so.

**Comment by Spekular** [comment] 2015-08-10 14:20
Duplicate of #2148?

**Comment by musikBear** [comment] 2015-08-10 15:06
is this related #2194 ?

**Comment by M374LX** [comment] 2015-08-10 16:41
> is this related #2194 ?

Apparently, which means that the same solution might be applicable.

**Comment by tresf** [comment] 2015-08-24 12:26
@M374LX I'm closing as duplicate of #2194 for now.  If we later find out these are unrelated, please feel free to reopen.

**Closed by tresf** 2015-08-24 12:26 UTC
