### ISSUE TITLE
When creating project from templates, some templates are missing

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2571] opened 2016-02-16 20:37 UTC
I compiled lmms-1.1.90 on fedora 23 64 bits.
When I create a new project from template, templates from the directory lmms-1.1.90/share/lmms/projects/Templates/ are missing in the menu list.

**Comment by zonkmachine** [comment] 2016-02-17 02:42
Thanks! ... But this is a duplicate of https://github.com/LMMS/lmms/issues/2525
Please update that one instead if you have new information. Closing.

**Closed by zonkmachine** 2016-02-17 02:42 UTC
