### ISSUE TITLE
LMMS 1.1.2 won't load EasyQ

### ISSUE THREAD

**Issue by EpicTree** [LMMS/lmms#1786] opened 2015-02-25 21:59 UTC
When loading a project file that uses the EasyQ plugin effect, I get a window labeled "Failed loading VST plugin" with the message "The VST plugin EasyQdll could not be loaded for some reason". I have seen this message before, but it usually resolves itself after a restart, or, it is because I have moved a plugin from its registered folder, but I have tried redownloading and installing the plugin, restarting lmms, unplugging my midi controller, and changing the plugin directory, but to no avail.

My system:
OS: Windows 8.1 (64-bit)
CPU: 2.7ghz
RAM: 4 GB DDR3
LMMS Version: 1.1.2 beta Pre-release (64-bit)

Thank you for your help.

**Comment by Sti2nd** [comment] 2015-02-25 22:36
Or any other VSTs unfortunately, this is a general VST bug with the beta version https://github.com/LMMS/lmms/issues/1757

**Comment by EpicTree** [comment] 2015-02-25 23:08
Oh, well thank you for telling me. I will downgrade until a fix appears.

**Comment by tresf** [comment] 2015-02-26 13:49
Duplicate of #1757.

**Closed by tresf** 2015-02-26 13:49 UTC
Labels: duplicate
