### ISSUE TITLE
Need Time Before Recording With Midi Keyboard to Listen to The Metronome.

### ISSUE THREAD

**Issue by Asskadoodle** [LMMS/lmms#3106] opened 2016-11-06 21:54 UTC
I am using LMMS 1.1.3. I have used other music production software in which
after pressing the record button, you are given two measures of time to
listen to the metronome. After these two measures, it starts recording.
Without this feature, I am pretty much guaranteed to screw up the first
measure of the recording. It's like you are trying to play in a band during
a concert without the conductor counting four beats before you start
playing. The band needs the conductor to count before they play or they
won't know the tempo. Some time to listen to the metronome before playing is essential to staying on beat and there is nothing like this in LMMS.

**Comment by zonkmachine** [comment] 2016-11-06 22:02
Hi! This looks like a duplicate of #869

**Comment by Spekular** [comment] 2016-11-06 22:04
I think this would make sense, although it'd be nice to be able configure
the amount of bars you personally want. For now, you can always wait two
bars before you start and then select and drag the recording back.

**Comment by BaraMGB** [comment] 2016-11-07 09:17
Closed because of duplicate https://github.com/LMMS/lmms/issues/869

**Closed by BaraMGB** 2016-11-07 09:17 UTC

**Comment by Asskadoodle** [comment] 2016-11-07 21:42
I appreciate your response.
