### ISSUE TITLE
window focus sound bug

### ISSUE THREAD

**Issue by tecan** [LMMS/lmms#1300] opened 2014-11-14 14:52 UTC
if you press and hold some keys and the window looses focus they get stuck on and you have to click play then stop on the sequence editor (just stop wont stop the sounds for some reason.)

**Comment by tresf** [comment] 2015-02-14 19:05
Duplicate of #1755.

Leaving #1755 open because it has the exact steps to reproduce.

**Closed by tresf** 2015-02-14 19:05 UTC
Labels: bug
