### ISSUE TITLE
Drums click for no reason

### ISSUE THREAD

**Issue by YesImAsh** [LMMS/lmms#7395] opened 2024-07-25 18:04 UTC
### System Information

Windows 10, Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz   2.59 GHz

### LMMS Version(s)

g99c30ea1a nightly

### Most Recent Working Version

g12632e6b5 nightly

### Bug Summary

AudioFileProcessor Does not sound to great. What's with the clicky sound?

### Expected Behaviour

it should not click, but it does

### Steps To Reproduce

Step 1. utilize AudioFileProcessor

DONE

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

https://github.com/user-attachments/assets/7afc2731-9498-4041-b1f0-90abff5e070c

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by bratpeki** [comment] 2024-07-25 18:09
It should click, when you end a note so that the signal's phase isn't set to 0, it creates the click. This is solved by making the release of the synth longer.

I'll take a look at making a new default ADSR envelope and see if it can be on by default.

**Comment by michaelgregorius** [comment] 2024-07-28 14:59
Using the info from the last known good version and the used bad one the commit candidates are (from high probability to low one):
* 2f5f12aaae8453863f62305cb54e4cfe779b661c: "Switch to libsamplerate's callback API in Sample"
* 851c884f58155275e6adbde40f2611d076edd345: "Re-enable disabled GCC warnings where possible"
* 9c0fc8fc6994b87ece6e706104877b715966af9b: "Made it so ZynAddSubFx isn't lowpassed by default"
* 99c30ea1ab7be264096fa76ccb96f43c7f98aeb1: "Fixed alt + left or right causing a crash in PianoRoll"

The last two entries should have a very close to zero probability though.

@sakertooth, @DomClark can you please check if your commit might have caused this problem?

**Comment by sakertooth** [comment] 2024-07-28 15:07
It's probably https://github.com/LMMS/lmms/commit/2f5f12aaae8453863f62305cb54e4cfe779b661c, but I don't know how this bug is only happening on Windows. This bug does not happen on my machine at all, so I can't reproduce whatsoever.

**Comment by michaelgregorius** [comment] 2024-08-04 08:32
Closing this because the problem should have been fixed by pull request https://github.com/LMMS/lmms/pull/7410.

**Closed by michaelgregorius** 2024-08-04 08:32 UTC
Labels: bug
