### ISSUE TITLE
Beat/Bassline tracks and editor don't behave as expected

### ISSUE THREAD

**Issue by irrenhaus3** [LMMS/lmms#2476] opened 2015-12-02 06:18 UTC
Hi everyone,
this is more of a feature request than a bug report, but I noticed some counter-intuitive behaviour involving the pattern editor in 1.1.3.  
* [x] When adding a new instrument to the pattern editor, it starts with the default amount of steps, regardless of the other instruments. By intuition, I would expect an editor with, say, 64 steps for all instruments, to give the newly added one 64 steps as well. Maybe that could be realized with a default setting somewhere in the configs?   (done via #2883)
* [ ] Beat/Bass tracks don't have a "master" volume slider (at least not visible in the song editor) and are therefore very tedious to automate. Fading a beat pattern in or out is not sensibly possible as of now.

That's pretty much it. Thanks for your time. :-)

**Comment by tresf** [comment] 2015-12-02 14:21
These are both relevant, but two completely separate enhancement requests.  We can keep them lumped together for now, but if anyone chooses to work on them, they'll need to be split.

**Comment by Umcaruje** [comment] 2016-08-13 22:13
Closing this out, as the first part of the issue is fixed, and the 2nd part is a duplicate of #2218

**Closed by Umcaruje** 2016-08-13 22:13 UTC
Labels: enhancement, ux
