### ISSUE TITLE
Longer envelope support for AFP

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1592] opened 2015-01-10 19:04 UTC
**Edited @tresf 2015-01-10**

from @Reaper10 

> "I tried to use the Envelope in Envelope settings to try to play a long sample without the volume of the sample  fading away without needing to hold the keys down myself and it didn't work. Is there any way for the Envelope to be made longer then it is now?"

and from @HGRoyal

> [...] when I try to play a sample that is for example 7 seconds long, I will only get may 3 or 4 seconds of the sample.

and from @curlymorphic 

> I can see 2 issues here 
> 1. the AFP envelope wont play the whole sample.
> 2. Infinitely long notes , (as suggested by the use of loop mode ).

---
*Original post*

I tried to use the Envelope in Envelope settings to try to play a long sample without the volume of the sample  fading away without needing to hold the keys down myself and it didn't work.  So can you just add a hold key button so you can play all of the sample without any changing the volume no matter how long it is. this way you can use LFOs, filters, cutoff all loop mode buttons and reverse button, Envelope or anything you want so you don't need to hold the keys down yourself. without needing a midi clip to do it. the would be great for live keyboard players to make live soundscapes using samples.

mockup
(removed)

icon
(removed)

Is there any way for the Envelope to be made longer then it is now?

**Comment by Umcaruje** [comment] 2015-01-10 19:55
Please do not make duplicates for your own issues. The last one already got closed, what do you think will happen to this one?

**Comment by tresf** [comment] 2015-01-10 20:06
IIRC, the problem with the previous bug report was lack of clarity.  This one is a bit better because he explains what he is trying to achieve, which is all we were asking for.

What it sounds like he wants is just a way to hold a given key on the keyboard without switching back to the piano roll or using a midi device.

So @Reaper10, where would you like this button?  Can you give us a mockup?   Note that it will only hold the key as if the note is pressed, it won't do any magic and if envelope cuts it off, we'll have to decide what the behavior is (does it blink and hold again?)

**Comment by tresf** [comment] 2015-01-10 20:08
Also, please try to be generic as possible with your requests.  AFP may be where you need it, but this functionality is better sold as a new feature if you can apply it to all of our instrument plugins. :+1:

**Comment by tresf** [comment] 2015-01-10 20:19
Also, do you want this to happen w/ midi input or mouse input?  I'm a bit confused as to the use case you describe.  Be as specific as possible please.

**Comment by Reaper10** [comment] 2015-01-10 20:48
I tried to use the Envelope in Envelope settings to try to play a long sample without the volume of the sample  fading away without needing to hold the keys down myself and it didn't work.  So can you just add a hold key button so you can play all of the sample without any changing the volume no matter how long it is. this way you can use LFOs, filters, cutoff all loop mode buttons and reverse button, Envelope or anything you want so you don't need to hold the keys down yourself. without needing a midi clip to do it. the would be great for live keyboard players to make live soundscapes using samples.

mockup
![b437d0ae-794e-11e4-8e19-72a30c1e446d 1](https://cloud.githubusercontent.com/assets/8137561/5693169/f7b0a26e-98d6-11e4-83ce-98182822cba3.png)

icon
![icon](https://cloud.githubusercontent.com/assets/8137561/5693171/12930edc-98d7-11e4-9e11-8b08c0cd5790.jpg)

Is there any way for the Envelope to be made longer then it is now?

**Comment by tresf** [comment] 2015-01-10 20:55
Ok... 

I finally think I see what you are asking for... 

You want a longer envelope hold feature.

-Tres

**Comment by tresf** [comment] 2015-01-10 21:00
I tend to agree, the envelope is useful but often the hold is often too short for long samples.

So next, please create a set of samples of varying length and tell us where the hold breaks.  As far as I can see, the hold's max value on AFP samples is "2".  That's not 2 seconds, so we'll have to determine what it is in actual reference to.  Then we'll talk about what needs to be changed to fix this problem.

**Comment by Reaper10** [comment] 2015-01-10 22:01
test 1 sample 2:14 held until 1:50
test 2 sample 3:51  held until 3:35
my beat guess

I still want a way to hold a given key on the keyboard without needing to hold, ie just need to push the key and not hold it down to play the long sample.

**Comment by Reaper10** [comment] 2015-01-10 22:10
Why did you remove my  icon mockup?

**Comment by tresf** [comment] 2015-01-11 15:03
> Why did you remove my icon and my mockup?

For the same reason that the other bug got closed, it's way too confusing and it was the same mockup as used in the closed bug report (and you're copying and pasting your text, which is insulting to those asking questions).

I don't yet think that this is an AFP feature but rather an AFP bug.  If our envelope doesn't allow playing an AFP sample all the way through, we should probably tweak it.  Can you agree with that statement?  Can you also agree that this should be fixed in the envelope area?

**Comment by Reaper10** [comment] 2015-01-11 16:15
Oh okay are you still going make it so you don't have to hold the keys down to play all of the sample?

**Comment by Sti2nd** [comment] 2015-01-11 23:05
Yes

**Comment by tresf** [comment] 2015-01-11 23:13
> Oh okay are you still going make it so you don't have to hold the keys down to play all of the sample?

Ideally.  I think the envelope should offer some type of functionality like this.

**Comment by Sti2nd** [comment] 2015-01-11 23:15
I think I have asked this before. How does the hold button work again, cause 1 isn't 100% of the sample!

**Comment by tresf** [comment] 2015-01-11 23:37
@Sti2nd that is the exact issue we're discussing.  Thanks for joining.

**Comment by Sti2nd** [comment] 2015-01-11 23:53
> that is the exact issue we're discussing. Thanks for joining.

That was a questions, I know what the topic was.

**Comment by curlymorphic** [comment] 2015-01-21 13:36
I can see 2 issues here 

1. the AFP envelope wont play the whole sample.

2. Infinitely long notes , (as suggested by the use of loop mode ).

I don't think this can be done with our current adsr generators, if it could, stopping the note with the  release phase would then be a problem.

I believe what the OP is looking for is the behaviour of a sustain pedal.

**Comment by diizy** [comment] 2015-01-21 13:40
On 01/21/2015 03:36 PM, Dave wrote:
>
> I can see 2 issues here
>
> 1.
>
>     the AFP envelope wont play the whole sample.
>

What do you mean? If you set sustain to full (or >0), the envelope stays
on as long as the note is on.

> 1.
>
>     Infinitely long notes , (as suggested by the use of loop mode ).
>
> I don't think this can be done with our current adsr generators, if it
> could, stopping the note with the release phase would then be a problem.
>
> I believe what the OP is looking for is the behaviour of a sustain pedal.
>

We already have sustain in the envelope. What is actually wanted here?
Longer attack/decay/release? We already allow several seconds for each
of those.

**Comment by tresf** [comment] 2015-01-21 13:44
> What is actually wanted here?

The ability to use envelope to play the entire length, which works well for shorter samples, but doesn't work for longer samples.  I suspect a bug in the envelope knob calculation that only surfaces on the larger samples (i.e. 60 seconds).

**Comment by tresf** [comment] 2015-01-21 13:45
The relevant data, per @Reaper10 

```
test 1 sample 2:14 held until 1:50
test 2 sample 3:51 held until 3:35
my beat guess
```

**Comment by diizy** [comment] 2015-01-21 13:46
On 01/21/2015 03:44 PM, Tres Finocchiaro wrote:
>
>     What is actually wanted here?
>
> The ability to use envelope to play the entire length, which works
> well for shorter samples, but doesn't work for longer samples. I
> suspect a bug in the envelope knob calculation that only surfaces on
> the larger samples (i.e. 60 seconds).
>

Describe the bug please. If you set the sustain to 1.0, the sample
should play as long as you want. Is this not the case? I've never seen
an issue like that and I've used some pretty long samples.

**Comment by Umcaruje** [comment] 2015-01-21 13:50
>Describe the bug please. If you set the sustain to 1.0, the sample
should play as long as you want. Is this not the case? I've never seen
an issue like that and I've used some pretty long samples.

I believe he wants an 'infinite release' so to speak, so he can just trigger the sample and it'd play until it reaches its end, regardless of its length.

**Comment by curlymorphic** [comment] 2015-01-21 13:56
> this way you can use LFOs, filters, cutoff all loop mode buttons and reverse button, Envelope or anything you want so you don't need to hold the keys down yourself.

but playing with loop modes means there is no definable length.

I feel there may have been some confusion over the word sustain.

> I believe what the OP is looking for is the behaviour of a sustain pedal.
> We already have sustain in the envelope.

A   sustain pedal is what a keyboardist uses to hold notes, while letting go of the keys.

**Comment by tresf** [comment] 2015-01-21 14:01
> but playing with loop modes means there is no definable length.

Yeah, this is why we closed the old bug report, the OP is asking for the impossible in some cases.  But to focus on what is broken... the reason we left this one open is because the envelope should have the ability to plan the entire sample's length with the strike and immediate release of a key.  Currently, the envelope falls short on longer samples.  This is why I modified the original bug report to say this:

> "I tried to use the Envelope in Envelope settings to try to play a long sample without the volume of the sample fading away without needing to hold the keys down myself and it didn't work. Is there any way for the Envelope to be made longer then it is now?" 

-Tres

**Comment by curlymorphic** [comment] 2015-01-21 14:10
@tresf sorry for the confusion.  Looking at this one now

**Comment by curlymorphic** [comment] 2015-01-21 14:55
Looked into this, im not sure envelops is the way to go. The only portion of the envelope played after the key is the release phase, and that is not at a constant level.  If the maximum release time was turned up to several minutes then the accuracy on the dial for smaller samples would suffer. 

Some samplers use a technique call singleshot iirc, This basically ignores the adsr and note off , and plays the sample from beginning to end.  It's used for drum hits, but could fit the requirements.

Im not sure if this is a possability , im hoping @diizy may know?

**Comment by diizy** [comment] 2015-01-21 15:13
On 01/21/2015 04:01 PM, Tres Finocchiaro wrote:
>
>     but playing with loop modes means there is no definable length.
>
> Yeah, this is why we closed the old bug report, the OP is asking for
> the impossible in some cases. But to focus on what is broken... the
> reason we left this one open is because the envelope should have the
> ability to plan the entire sample's length with the strike and
> immediate release of a key. Currently, the envelope falls short on
> longer samples. This is why I modified the original bug report to say
> this:
>
>     "I tried to use the Envelope in Envelope settings to try to play a
>     long sample without the volume of the sample fading away without
>     needing to hold the keys down myself and it didn't work. Is there
>     any way for the Envelope to be made longer then it is now?"
>
>

Ok so, it's a matter of poorly worded bug report because I'm only now
hearing of this. If the envelope cuts short then it's indeed, if not a
bug, at least a flaw in the implementation. My guess is that the AFP was
never designed (or tested) for samples that are several minutes long.

The question is, does the same happen on other instruments? Try
replacing the AFP with, say, triple osc playing one note for several
minutes, and see if the envelope cuts off there too. We need exact
parameters for triggering this bug, then figuring out the fix should be
simple when we know where to look.

**Comment by diizy** [comment] 2015-01-21 15:16
On 01/21/2015 04:55 PM, Dave wrote:
>
> Looked into this, im not sure envelops is the way to go. The only
> portion of the envelope played after the key is the release phase, and
> that is not at a constant level. If the maximum release time was
> turned up to several minutes then the accuracy on the dial for smaller
> samples would suffer.
>

That's not really the issue here. Release time is fine. The problem is
apparently with sustain, which should hold the note indefinitely but
reportedly (haven't confirmed myself) cuts off after a couple of minutes.

> Some samplers use a technique call singleshot iirc, This basically
> ignores the adsr and note off , and plays the sample from beginning to
> end. It's used for drum hits, but could fit the requirements.
>

Yes. We already have those, they're called beat notes. They're used in
bb-patterns.

**Comment by curlymorphic** [comment] 2015-01-21 15:23
There is no issue with the sustain. it is working as intended. if the key is held down the sample will play to the end. The issue here is to play until the end even when the note is released.

beat notes sounds like what is required.

**Comment by Sti2nd** [comment] 2015-01-21 16:06
> if the key is held down the sample will play to the end.

Exactly, I thought we were talking about infinity release here, cause OP wants to be able to release the key.

**Comment by diizy** [comment] 2015-01-21 16:15
On 01/21/2015 05:23 PM, Dave wrote:
>
> There is no issue with the sustain. it is working as intended. if the
> key is held down the sample will play to the end.
>

Have you tried it with samples that are several minutes long? That's the
reported condition for the issue.

**Comment by curlymorphic** [comment] 2015-01-21 16:38
Yes. I have just sat here listening to a whole music track at 316 seconds long, with my finger on the Y key. This played back all the way to the end with no problem.

The original poster  wants to be able to do this without holding a key, so his hands are free.

**Comment by tresf** [comment] 2015-01-21 19:00
> poorly worded bug report because I'm only now hearing of this

I'm not sure what term to use for this, and yes, the bug report was written poorly, but I think we all understand at least what is trying to be achieved here.  It sounds like a reasonable request...

Perhaps this isn't what the envelope should be used for, I can't really speak to that, but I can agree with the OP that this is behavior I could benefit from.

**Comment by Spekular** [comment] 2015-01-21 20:50
@Vesa off topic perhaps but is there a way to place beat notes in piano
roll?

**Comment by Sti2nd** [comment] 2015-01-21 22:12
> is there a way to place beat notes in piano
roll?

I tried copy a beat note and put it in an instrument's Piano Roll. It stops playing after one bar. Maybe because the pattern end after one segment?
![image](https://cloud.githubusercontent.com/assets/6373430/5846305/fc22e330-a1c2-11e4-9f86-377a8e5eb96b.png)

**Comment by diizy** [comment] 2015-01-22 05:41
On 01/22/2015 12:12 AM, Stian Jørgensrud wrote:
>
>     is there a way to place beat notes in piano
>     roll?
>
> I tried copy a beat note and put it in an instrument's Piano Roll. It
> stops playing after one bar. Maybe because the pattern end after one
> segment?
>

The length of a beat note is defined by the instrument.

**Comment by tresf** [comment] 2015-08-22 02:37
Duplicate of #2255

**Closed by tresf** 2015-08-22 02:37 UTC
Labels: bug
