### ISSUE TITLE
Same set of instruments appearing together in various beats

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#5820] opened 2020-12-03 21:31 UTC
I am not sure if it is a feature, but I feel that beats instruments should be grouped together in the beats editor list. When one beat editor is active, the instruments that were added in the different set should not be listed there, or be low-lighted (as inactive instrument).

You can still show what instrument has been added, but do not allow to enter/edit them there.

![image](https://user-images.githubusercontent.com/5563341/101089911-1254f180-3573-11eb-81c6-9fea3e82f02b.png)

The list of instruments is "same" for all beats/baseline (0, 1, 2).
Did I explain the issue better?

**Comment by Spekular** [comment] 2020-12-03 21:52
Duplicate of #453

**Closed by Spekular** 2020-12-03 21:52 UTC
Labels: enhancement
