### ISSUE TITLE
Flipping pattern -  New Enhancement

### ISSUE THREAD

**Issue by moestudio2017** [LMMS/lmms#4302] opened 2018-04-19 14:52 UTC
I want to do this without export as a wav and audio file processor.
## I hope that you add function about "**Flipping patterns**".
![1](https://user-images.githubusercontent.com/32843190/38999206-40b8c71c-442c-11e8-9dd9-07fea090dd97.png)
If you click this button .....

![2](https://user-images.githubusercontent.com/32843190/38999231-4ff40250-442c-11e8-8c9a-3a7f7e4f2edf.png)

**You can reverse the front and back of notes**

**Comment by tresf** [comment] 2019-10-03 15:20
Duplicate of #5012.

**Closed by tresf** 2019-10-03 15:20 UTC
Labels: enhancement
