### ISSUE TITLE
LMMS RC7 has some terrible bugs.

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#4680] opened 2018-10-26 16:56 UTC
![寿司ゆき:help](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/11.png) 
When I opened my song which had made in LMMS RC6 , I found that old ZynAddSubFX's preset is no longer available. (Changed into Default Sounds (Only SineSaw))
And some VST Plugins has changed into terrible sounds. I never use such instruments with sounds.

☟It is movie of bug.
https://nanoteam.0am.jp/wp-content/uploads/2018/10/36cb6578926d8b047b203ca08f205594.mp4

How can I do for it?

**Comment by RoxasKH** [comment] 2018-10-26 17:07
I confirm the ZasFX problem, it happened also to me.
For the VST problem, i don't, maybe it's only a located problem or a problem of the vst itself, i personally never had problem with vsts in RC7, apart from some minor things with only some specific vsts (that gave me problems also in other versions).
So, it would be useful to know i guess, for devs to know which VSTs you're talking about, and if they can reproduce the issue someway.

**Comment by moestudio2017** [comment] 2018-10-26 17:14
Used VST is PianoOne.

And I just opened my song's project. No directory was changed , so were VST and ZynAddSubFX.

**Comment by RoxasKH** [comment] 2018-10-26 17:16
That's weird, i never had problems with PianoOne. Have you tried reloading the project again? And increasing the buffer size in your preferences?

I will try to load an old PianoOne project of mine

**Comment by moestudio2017** [comment] 2018-10-26 17:20
I reloaded and buffer was enough.
I solved this problem by resetting of the presets , but I spent more time of fixing.

So , I posted this issues someone to fix a bug.
![寿司ゆき:sneak](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/18.png)

**Comment by RoxasKH** [comment] 2018-10-26 17:29
So, i guess devscould fix zasfx issue, but not PianoOne one because i will try out to reproduce it, but i think it won't happened. Anyway is good to hear that you solve you problem, even if in a tricky way

**Comment by tresf** [comment] 2019-03-17 11:39
Please provide a sample project which reproduces the problem.

**Comment by PhysSong** [comment] 2022-03-23 01:53
Closing due to lack of information. If anyone have the same issues, please let us know so we can reopen.

**Closed by PhysSong** 2022-03-23 01:53 UTC
