### ISSUE TITLE
Port to Qt6

### ISSUE THREAD

**Issue by Snowiiii** [LMMS/lmms#7134] opened 2024-03-03 15:48 UTC
**Port LMMS to Qt6 framework**

So recently KDE Plasma 6 has been released and they Migrated all their Qt5 Stuff to Qt6, I think LMMS should do the Same

This enhancement request proposes migrating the LMMS project from the Qt5 framework to Qt6.
Justification

In this section, I explain why porting to Qt6 would be beneficial for LMMS. Here are some potential points to consider:

**Improved Performance**: Qt6 offers performance improvements over Qt5, which could lead to a smoother and more responsive user experience in LMMS.
    **Modern Features**: Qt6 includes new features and functionalities not available in Qt5. Mention specific features that would enhance LMMS or its development process.
    **Long-Term Support**: Qt6 has a longer LTS (Long-Term Support) lifecycle compared to Qt5, ensuring ongoing support and security updates for LMMS.
    **Community Adoption**: If the Qt development community is actively migrating towards Qt6, mention this as a reason to follow suit for LMMS to stay compatible with libraries and tools.

**Example Benefits:**
   - Improved application performance
   - Access to new Qt features
   - Enhanced development experience
   - Better long-term maintainability
   
 and more!

If we decide to start migrating, I would suggest turning this issue into a draft

**Comment by michaelgregorius** [comment] 2024-03-03 16:12
Hi @Snowiiii! Thanks for the issue but it seems to be a duplicate of #6614 which is much more detailed. Can we close this one?

**Comment by Veratil** [comment] 2024-03-03 16:13
Duplicate of #6614

**Closed by Veratil** 2024-03-03 16:13 UTC
Labels: enhancement
