### ISSUE TITLE
Delete multiple selected blocks.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4693] opened 2018-11-01 22:35 UTC
Maybe someone has already talked about this at other times or this is a duplicate.
But when I want to delete several selected blocks with the selection tool and press the '' delete '' key nothing happens, they are not deleted, and I am forced to delete them separately by pressing the mouse wheel, but this becomes more complicated when They are many blocks. This is a very important feature and one that can not be ignored. I speak of this because stable version 1.2 will be released soon, so I am wondering: is it possible that they can correct this error for the next stable version 1.2?

**Comment by PhysSong** [comment] 2018-11-02 00:08
Duplicate of your own issue #4626.
And I'm sorry to say that the feature won't be part of the 1.2 release. Instead, we can do our best to release 1.3 development versions as soon as possible.

**Closed by PhysSong** 2018-11-02 00:08 UTC
