### ISSUE TITLE
[Feature request] Select, copy & paste multiple tracks in Song-Editor

### ISSUE THREAD

**Issue by qubodup** [LMMS/lmms#2453] opened 2015-11-21 16:56 UTC
Hello thanks for LMMS! I have a feature suggestion, which might or might not make sense (I know Audacity and Kdenlive but not music editing yet).

User story:
I would like to loop a track (because it's just more time-efficient for me to spend more time rendering while I do other things than finding the loop point in Audacity and looping it there) and for that purpose I would like to be able to select/copy/paste all tracks in the Song-Editor (Timeline?).

A mockup video of the suggested feature:
https://youtu.be/8RwUUVyGwro
Note that in the video, selection gets disabled after paste-ing but I don't think that's necessarily what should happen

**Comment by Umcaruje** [comment] 2015-11-22 19:00
Hi @qubodup, thanks for reporting this. Do you think this could be considered as a duplicate of #1212?

**Comment by qubodup** [comment] 2015-11-22 19:53
Probably yes.

I only now realize that this task would be very complex:
* How to handle paste in a different track?
* How to handle removed or added tracks between copy and paste?
* How to handle clips that are in the way? (actually no problem, since lmms allows overlapping clips, confusing or not, it makes this easier).

I would suggest for the first implementation:
* When copying, remember the ID of the track on which each  selected clip is positioned. Make sure to use an ID that won't change if the user changes the name in the meantime(?).
* On paste, ignore which track is being pasted to, just paste to the respective tracks, of which the ID has been recorded to the clipboard. Use the beat hovered by the mouse cursor to determine what beat/x-position to start paste-ing to
* Since clips can overlap, just paste over existing ones.
* Ideally support Cltr+c / Ctrl+v (which is currently not supported by single-clips yet).

Advanced features:
* If at time of paste, clipboard clips have IDs of tracks that don't exist (any more), paste the rest still.
* Make multi-clip operations be tracked by undo history
* Make clipboard independant from history, so that users can go to the paste to it. Selection actions however should be part of the history even though this means you can't go back to the past, copy from there and bring the copies to the future, as selection actions would overwrite the future.
* Allow adding/removing single clips to/from selection using Shift+click (shift is the "add" operator in the piano roll even though ctrl usually does this and shift usually enables box-drag select as far as I know.

**Comment by Umcaruje** [comment] 2016-01-24 21:55
Duplicate of #1212

**Closed by Umcaruje** 2016-01-24 21:55 UTC
