### ISSUE TITLE
CPU usage optimisation - Instrument Usage Map

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2290] opened 2015-08-24 11:39 UTC
__Problem__

For a longer time I'm observing that LMMS is using quite a lot of resources all the time, depending on the size of a project loaded even when no sound is produced.

Straigth off when I load "unfa - Spoken" LMMS consumes 132 - 148 % of the CPU (as displayed by htop). I'm using a 2-core (4 threads) Intel core i7 processor. That's quite a lot of processing being done that produce absolutely nothing and is not supposed to exist.

__Solution__

My idea to help this situation is an Instrument Usage Map.

To put is simple: it's about keeping track of which instruments are playing in which bars of the project. Then the program can use this information to process only those instruments that will actually make a difference, omitting the rest and assuming it's producing digital silence (zeros).

__What say thou?__

Let's talk about this.

**Comment by tresf** [comment] 2015-08-24 13:00
This is a duplicate of your own bug report #1916.

Instrument maps aren't the way to tackle this... a systematic map is...

First, we need to find areas where the GUI is set to the incorrect priority.  This is exactly what was happening in #1932 when the FadeButton animation was occurring on the same thread as the digital signal processing code.  This is devastating to performance.

But I feel the real way to fix this is not to observe CPU usage but rather enforce standards.  Observing CPU usage may be good for optimizing inefficient plugins, but in my experience, our plugins are pretty damn efficient already.

Another thing worth considering is how SDL uses CPU cycles versus ALSA, etc as the audio backends seem to make a difference in CPU spikes and utilization.  Here's some more conversation on this:

https://github.com/LMMS/lmms/issues/1600#issuecomment-69782663

Last, we need people to help study and fix the code, not necessarily converse about it.  This is what the "coupling" and "decoupling" conversations are about.  This is an area we can continue improving on right now.  https://github.com/LMMS/lmms/issues/1862

**Closed by tresf** 2015-08-24 13:00 UTC
