### ISSUE TITLE
lmms hangs when render a project to wav file via command line

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2053] opened 2015-05-16 12:50 UTC
I use lmms compile from git repo (master branch at commit 2f969c1e1c7194538c9e047b039f39d0b8e304d7) on fedora 21 64 bits.
I use lmms from command line to export a project to WAV:

```
lmms -r 01_tardive.mmpz -o 01_tardive.wav -f wav
```

When this command line is used, lmms hangs:

```
(gdb) where
#0  0x00007ffff693b511 in QObjectPrivate::setParent_helper(QObject*) () at /lib64/libQtCore.so.4
#1  0x00007ffff693bf77 in QObject::~QObject() () at /lib64/libQtCore.so.4
#2  0x00007fffda9feb29 in NulEngine::~NulEngine() (this=0x2cb4710, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/collette/repositories/lmms/plugins/zynaddsubfx/zynaddsubfx/src/Nio/NulEngine.cpp:76
#3  0x00007fffda9b0737 in LocalZynAddSubFx::~LocalZynAddSubFx() (this=0x2caeca0, __in_chrg=<optimized out>)
    at /home/collette/repositories/lmms/plugins/zynaddsubfx/LocalZynAddSubFx.cpp:92
#4  0x00007fffda557621 in ZynAddSubFxInstrument::initPlugin() (this=this@entry=0x7fffea5766e0)
    at /home/collette/repositories/lmms/plugins/zynaddsubfx/ZynAddSubFx.cpp:425
#5  0x00007fffda55ae69 in ZynAddSubFxInstrument::reloadPlugin() (this=0x7fffea5766e0)
    at /home/collette/repositories/lmms/plugins/zynaddsubfx/ZynAddSubFx.cpp:379
#6  0x00007ffff6936cdc in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () at /lib64/libQtCore.so.4
#7  0x00000000005951c3 in Mixer::sampleRateChanged() (this=<optimized out>) at /home/collette/repositories/lmms/build/src/moc_Mixer.cpp:108
#8  0x00000000004d1a8f in Mixer::setAudioDevice(AudioDevice*, Mixer::qualitySettings const&, bool) (this=0x8b4c60, _dev=
    0xd026d0, _qs=..., _needs_fifo=_needs_fifo@entry=false) at /home/collette/repositories/lmms/src/core/Mixer.cpp:587
#9  0x00000000004e15e2 in ProjectRenderer::startProcessing() (this=0xcc9360) at /home/collette/repositories/lmms/src/core/ProjectRenderer.cpp:136
#10 0x0000000000485eeb in main(int, char**) (argc=7, argv=0x7fffffffdd08) at /home/collette/repositories/lmms/src/core/main.cpp:539
```

**Comment by ycollet** [comment] 2015-05-16 12:52
Tested with lmms-1.1.3 compiled from sources and it works fine here.

**Comment by Wallacoloo** [comment] 2015-05-16 15:57
Thanks for reporting this. This error seems to be caused by #2049.

**Comment by ycollet** [comment] 2015-05-16 17:02
And maybe also #2035.

**Comment by zonkmachine** [comment] 2017-02-16 16:42
This would have been fixed in https://github.com/LMMS/lmms/pull/2118
Closing. Please reopen if you see this on current master!

**Closed by zonkmachine** 2017-02-16 16:42 UTC
Labels: duplicate
