### ISSUE TITLE
Tuned My Home or add tuned sample library folder

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#5430] opened 2020-03-27 19:32 UTC
Would be good to fix and will make tune of My Samples folders. For example: to enter my sample library I must to make through My Computer in left bar. It's not comfortable. No one can to add new folder now or retune it. Well sometimes users are changing system Home and replacing data location. But in LMMS it not tune. Would it be well to add and new places and tune My Samples library folder.

**Comment by SecondFlight** [comment] 2020-03-27 20:47
Closing as a duplicate of #2842 / #4309. Please let me know if these don't cover your issue.

**Closed by SecondFlight** 2020-03-27 20:47 UTC
Labels: duplicate, enhancement
