### ISSUE TITLE
feature request: scalable GUI

### ISSUE THREAD

**Issue by arcade-legend** [LMMS/lmms#6101] opened 2021-07-20 13:50 UTC
hi

I use lmms on a 4K PC monitor and on a 8K TV.
Both resolutions make the buttons barely readable....

Would it be possible to make a feature to make buttons and menus (menu text) smaller/larger selectable by the user?
Like 50%, 100 %, 150%, 200%, ...
This should also be applied to the buttons/text of the instrument configuration windows, because they are very tiny too in high resolutions and therefore very hard to use.

**Comment by Spekular** [comment] 2021-07-20 15:51
Duplicate of #5376, #2510, #4919

All of these (and other related issues) are found with a search for "gui scaling".

**Closed by Spekular** 2021-07-20 15:51 UTC
