### ISSUE TITLE
QtXmlWrapper::loadXMLfile() Empty data Segault

### ISSUE THREAD

**Issue by lcoenen** [LMMS/lmms#4508] opened 2018-07-29 16:17 UTC
Hey,

I just had a segfault within my project. This is frustrating, I was in the middle of a really good creative moment and then it crashed. It's crashing when I'm trying to open my project again (at about the end of the importing process). I was not using any VST - it looks like a bug in LMMS itself. Here's a copy of the project I was working on. 

[Segfault.mmpz.zip](https://github.com/LMMS/lmms/files/2238953/Segfault.mmpz.zip)

. Here is the message:

    QtXMLWrapper::LoadXMLfile(): empty data

I'm using LMMS 1.1.3. 

Please let me know what I could try to recover my data
Kind regards
Loic

**Comment by lcoenen** [comment] 2018-07-29 16:49
Ok so I greped the source and the problem seems to be in the zynaddsubfx plugins: 

     plugins/zynaddsubfx/zynaddsubfx/src/Misc/QtXmlWrapper.cpp:		qDebug() << "QtXmlWrapper::loadXMLfile(): empty data";

I don't know anything more yet, this function seems to be called from several location and I'd have to recompile everything to make test.

**Comment by tresf** [comment] 2018-07-30 05:18
@lcoenen that message appears with most projects, I believe your crash is related to the strange linking you have with the FX mixer and your midi controller.  I've never seen this before.

When I open the track, it **should** look like this... 
![screen shot 2018-07-30 at 1 16 02 am](https://user-images.githubusercontent.com/6345473/43378639-30b8b05c-9396-11e8-9f45-3c7345f9a4dd.png)

But instead it looks like this... 
![screen shot 2018-07-30 at 1 17 05 am](https://user-images.githubusercontent.com/6345473/43378663-566efc20-9396-11e8-9a45-b24682d4f877.png)

This may be a bug with LMMS, but the more background information you can provide on the controller linking, the better chance the devs will have that they can spot and fix it.

Side note, the [beta of LMMS](https://github.com/LMMS/lmms/releases) is what most of us use these days, so that's the proper version to bug report against if this problem is reproducible.

**Comment by PhysSong** [comment] 2018-07-30 05:37
Just tested the project file. It opens fine with [the latest beta version(1.2.0-RC6)](https://github.com/LMMS/lmms/releases/tag/v1.2.0-rc6) but crashes 1.1.3.
Though I can't spot the issue, I think this won't be matter anymore.

**Comment by tresf** [comment] 2018-07-30 06:14
The project is unplayable per screenshots above.  Probably a duplicate of https://github.com/LMMS/lmms/issues/4446.

**Comment by lcoenen** [comment] 2018-07-30 20:29
@tresf I really don't know. I use a [AKAI Midimix](http://www.akaipro.com/products/ableton-controllers/midimix)  with Jack and sometime a [mididings](http://das.nasophon.de/mididings/) mapping to turn the solo lights on and off. I got this issue from the beginning - everytime I plug the mixing table in, all the knobs are going back to zero - not only the mixer, but also other knobs used in the synths. These are just regular MIDI controller sending controller messages. This is super annoying, because everytime I reopen a project I have to slightly turn every control to get it to previous position. 

I will try the beta version, though. Thank you all for your great work :)

**Comment by lcoenen** [comment] 2018-07-30 20:42
Bad news guys I just tried to open it with the 1.2 beta - it worked for a bit, and then it just crashed with the same error message. In fact I think it have to do with the settings of the AudioFileProcessor - everything was going all right, but then I realized the sample wasn't playing, so I turned the knobs used to set the startpoint, loopback point and endpoint, and then it crashed at that exacts moment. 

![image](https://user-images.githubusercontent.com/1237971/43422322-417502fa-9441-11e8-973e-249a1af82ae7.png)

**Comment by lcoenen** [comment] 2018-07-30 20:51
Ok so definitely it looks like it's crashing when there's a mismatch between the three knobs when they're linked to MIDI knobs. The program start by settings them to zero, which doesn't really makes sense to set the loop points.

**Comment by tresf** [comment] 2018-07-30 21:05
I'm reopening this.  I think it was closed prematurely.

**Comment by PhysSong** [comment] 2022-03-23 01:34
Duplicate of #2149.

**Closed by PhysSong** 2022-03-23 01:34 UTC
Labels: needs clarification
