### ISSUE TITLE
BB patterns swapped in saved files

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2866] opened 2016-06-21 09:22 UTC
Version 1.1.3-gcbf6d24 (Linux/x86_64, Qt 4.8.6, GCC 4.8.4)

I'm working on a project, and saving next versions. Then I close LMMS and reload the project.

The contents of some B+B patterns is swapped. I don't know if this is a saving or loading issue.

LMMS alters the drums arrangement by itself ;)

**Comment by zonkmachine** [comment] 2016-07-30 08:43
Closing this as a duplicate of #2470

**Closed** 2016-07-30 08:44 UTC
Labels: duplicate
