### ISSUE TITLE
"Add MP3 Import" (fccbe5d) seemingly bogus

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6955] opened 2023-11-02 01:44 UTC
### Bug Summary
Latest push "Add MP3 Import" does not, in fact, actually seem to do anything. I cannot use MP3s at all still.
#### Steps to reproduce
Download Nightly, try to load MP3 into program, can't.
#### Expected behavior
I can use an MP3 in a sample track or AudioProcessor
#### Actual behavior
Still can't
#### Screenshot
![image](https://github.com/LMMS/lmms/assets/65266122/f7415c99-dc11-448f-ab27-a47ed760b2ce)
MP3s still marked with "?"
![image](https://github.com/LMMS/lmms/assets/65266122/34bef7ff-cc7e-49f6-b247-38d382184403)
MP3 not under available filetypes

#### Affected LMMS versions
gfccbe5d51

**Comment by LostRobotMusic** [comment] 2023-11-02 02:04
Thanks for the report.  This appears to not be an issue with the PR (compiling LMMS from source will work perfectly fine), but rather an issue with LMMS's automated build system for the nightly branch.  This is likely due to an outdated sndfile library version for the automated builds.

**Comment by SalutanisOrkonus** [comment] 2023-11-05 19:27
I hope that gets fixed, really wanna use MP3s so I dont have to convert everything just to use a song

**Comment by LostRobotMusic** [comment] 2023-11-12 07:50
Closing this since the issue is the outdated libraries in the LMMS website's automated builds rather than an issue with the PR or LMMS's code.  The outdated library issue should be filed separately (it's possible there already is one, I'm not sure).

**Closed by LostRobotMusic** 2023-11-12 07:50 UTC
Labels: bug
