### ISSUE TITLE
Global Tuning

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5639] opened 2020-08-18 08:47 UTC
Ability of setting a root note of project, somewhere away from 440Hz, so it will affect every synth in the project...

**Comment by musikBear** [comment] 2020-08-18 16:19
That already exists 
![image](https://user-images.githubusercontent.com/6662066/90538645-1fde9b00-e17f-11ea-89fa-760f1d963773.png)
Observe that lmms even has implemented that you can exclude presets from this:
![image](https://user-images.githubusercontent.com/6662066/90538771-4b618580-e17f-11ea-9d30-12af5496a3ca.png)
That is very important for all percussion instruments!
But the request is invalid -We have it :)
Asks for closing!

**Comment by mnini** [comment] 2020-08-18 19:33
It only works in whole notes in my setup... I need three floating point of hertz to achieve exact correctness, and with automatization it would be even better.

**Comment by Spekular** [comment] 2020-08-18 20:00
I'm going to consider this a duplicate of #1387.

Wikipedia says the following about MIDI Tuning Standard

> This higher resolution allows a logarithmic representation of pitch in which the semitone is divided into 1282 = 214 = 16384 parts, which means the octave is divided into 196608 (logarithmically) equal parts. These parts are exactly 100/16384 cents (approximately 0.0061 cents) in size, which is far below the threshold of human pitch perception and which therefore allows a very accurate representation of pitch.

**Closed by Spekular** 2020-08-18 20:00 UTC
Labels: enhancement
