### ISSUE TITLE
Song editor mode is changed permanently with Ctrl key(master branch)

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#3795] opened 2017-09-07 04:59 UTC
To reproduce:
1. Set the song editior to draw mode.
2. Press Ctrl key, in order to change to select mode(temporarily).
3. Click any other subwindows(ex. piano roll, bb editor, etc.)
4. Release Ctrl. 

Now the song editor is in the select mode, which is undesirable. Note that it isn't there in 1.2 branch, since this behavior was introduced in #3649, which was merged into `master` branch.

**Comment by PhysSong** [comment] 2017-09-07 05:03
Tagging @BaraMGB as the author of that PR.

**Comment by BaraMGB** [comment] 2017-09-07 07:32
Thank you. I will look into this.

**Comment by musikBear** [comment] 2017-09-07 15:13
duplicate of piano-roll situation: 
Sti2end made a list over problem with icon-hangs/ changes here
https://github.com/LMMS/lmms/issues/906#issuecomment-48371989
Dont know if the issue is the same, but maby ?

**Comment by BaraMGB** [comment] 2017-09-12 19:59
Closed by https://github.com/LMMS/lmms/issues/3796

**Closed by BaraMGB** 2017-09-12 19:59 UTC
