### ISSUE TITLE
Sample length cut through AudioFileProcessor is reverted to original form when exporting project as track

### ISSUE THREAD

**Issue by rknonchalance** [LMMS/lmms#3096] opened 2016-10-29 07:47 UTC
If this issue has been reported already please close this or mark as invalid/duplicate.

I'm using LMMS 1.2.0 Beta RC1 64bit on Windows 7 (which always crashes whenever I close the program, but that's not the main issue). I've used WAV samples on AudioFileProcessor and use only portions of the sample by cutting them on the sample length box where the waveform of the said sample was shown by dragging the left and right sides of the box. It works OK, but when I click on File > Export and then export the file as WAV (44100Hz, Sinc Best [Slow!], Oversampling 1x, and Export as loop [remove end markers] checked) I notice that immediately as it exports the sample length box changes to show the original sample in full, before I dragged the two ends of the box to shorten it. On one project file this affected the exported track, where the clipping that was initially removed through AFP was included on the export.

Of course I could simply cut the sample with Audacity as I had done as a workaround, but others might not have the patience to do so. This has happened to me on two isolated projects with two isolated samples. Might provide photo evidence for this as well.

**Comment by Spekular** [comment] 2016-10-29 08:47
Dupe of one I opened IIRC, will try to find the soecific one so don't close yet

**Comment by zonkmachine** [comment] 2016-10-30 13:17
Thank you for reporting this, we're already on the case. I close this as a duplicate.

**Closed by zonkmachine** 2016-10-30 13:17 UTC
Labels: duplicate
