### ISSUE TITLE
When placed, VeSTige plugin has a chance of not working

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6858] opened 2023-09-09 21:53 UTC
### Bug Summary
When you place a VeSTige plugin into the song editor, it has a chance of just not making sound or working, the only way to fix being just making a new one and hoping that one works.
#### Steps to reproduce
Place VeSTige into song editor. If anything specific causes it, I don't know, but it feels completely random.
#### Expected behavior
It just works
#### Actual behavior
Doesn't make sound half the time, whether from on the plugin window, or in the VST itself
#### Affected LMMS versions
alpha.1.357+gde062d6c5, and most likely others. Pretty sure it's a new issue after some recent push

**Comment by SalutanisOrkonus** [comment] 2023-09-14 01:57
turns out this seems to also apply to SF2 Players, so it might just affect everything

**Comment by DomClark** [comment] 2023-09-18 19:46
Reproduced. It looks like this bug has been around for a long time, but since #5970 was merged, appears much more often. The issue is that `PlayHandle`s are not added to the audio engine if the CPU load is too high, and #5970 improved the load tracking (previously the computed load value was too low due to a bug). For most instruments, this only affects individual notes, but some instruments (including VeSTige and Sf2 Player) register an `InstrumentPlayHandle` upon creation, which means that if the CPU load is too high when the instrument is added, it will never make any sound. The fix would be to add `InstrumentPlayHandle`s to the audio engine always, regardless of the current load.

**Comment by DomClark** [comment] 2023-09-18 22:34
@SalutanisOrkonus Could you test #6875 (download it at https://lmms.io/download/pull-request/6875) and see if that fixes this issue for you?

**Closed** 2023-09-18 23:18 UTC
Labels: bug
