### ISSUE TITLE
Audio Multiple Outputs

### ISSUE THREAD

**Issue by KrukWeekend** [LMMS/lmms#4332] opened 2018-04-28 18:40 UTC
I just used the libportaudio64bit.dll of github and instantly was offered ASIO as an output option, which gets me channels 1-2 of my interface software returns.  However my interface has 8 software returns, and depending on the program I am looking at, I can choose them mono or stereo.  
For instance the Studio One program has no problems busting them up into Mono or stereo, while OBS only sees them as paired inputs (stereo inputs).  
So what do I have to do or can anyone give me a good few files which would be needed to reprogram to make lmms offer multiple software returns as an option?

**Comment by lukas-w** [comment] 2018-04-28 19:14
Duplicate of #4064.

**Closed by lukas-w** 2018-04-28 19:14 UTC
