### ISSUE TITLE
Automation of Master Volume not working when loading LMMS1.1 saved project into LMMS1.2

### ISSUE THREAD

**Issue by bobemoe** [LMMS/lmms#4268] opened 2018-03-20 14:47 UTC
1. Open new LMMS 1.1.3 project
2. CTRL-drag the "Master Volume" to a new automation track
3. Draw something to the automation values (e.g fade in)
4. Play the track, observe the master volume being automated.
5. Save as .mmpz
6. Open the .mmpz in LMMS 1.2.0-rc5.39
7. Play the track, observe the master volume NOT being automated!

Expected of course to see the same behaviour as before with the volume being automated, noticed also the master slider seems "locked", you can drag it but instantly jumps back to a fixed value, which seems unrelated to the automation!

**Comment by zonkmachine** [comment] 2018-03-20 16:35
I can replicate this. I'll bisect this later.

**Comment by zonkmachine** [comment] 2018-03-20 17:56
```
$ git bisect bad 
75077f6200a5aee3a5821aae48a3b8466ed8714a is the first bad commit
commit 75077f6200a5aee3a5821aae48a3b8466ed8714a
Author: Lukas W <lukaswhl@gmail.com>
Date:   Thu Apr 6 23:10:00 2017 +0200

    Fix automation processing in BB tracks (#3481)
    
    Fixes #3464
```
@lukas-w

**Comment by PhysSong** [comment] 2018-03-21 01:48
After re-saving the project in 1.2, I can find a point in the *global automation*.
```xml
      <automationpattern name="Master Volume" prog="0" len="0" mute="0" tens="1" pos="0">
        <time value="100" pos="0"/>
        <object id="7752786"/>
      </automationpattern>
```
When saved from 1.1.3, the part looks like this:
```xml
      <automationpattern name="Master Volume" prog="0" len="0" mute="0" tens="1" pos="0">
        <object id="7752786"/>
      </automationpattern>
```
`AutomationPattern::addObject`(called by `AutomationPattern::resolveAllIDs`) adds an initial value. So it adds a point into (hidden) global automation pattern. You can find the pattern when re-opened by 1.1.3, too.
The issue with #3481 is that have changed priority for automation processing. Global automation patterns are processed at the very end since #3481, thus have highest priority.

I also found that this bug occurs only if the project file is created from new project(in other cases, `object id` section doesn't exist).

**Comment by PhysSong** [comment] 2018-03-22 03:19
After removing/renaming `templates/default.mpt`, one can reproduce this bug without using LMMS 1.1.x(or older one). #3481 is included in RC3, and factory `templates/default.mpt` was created after RC3. Unless the file have is manually added, it should be reproduced using only RC3.

The main problem is the order of processing:
https://github.com/LMMS/lmms/blob/87e6b48df73518b4c43db118374f2d94e034edde/src/core/Song.cpp#L817-L820
The fix may be simple since changing the order will solve the bug.

Anyway, I think creating initial values for global automations doesn't make sense unless an user do that manually(and that is the other cause of this issue). That could be fixed by modifying `AutomationPattern::addObject` slightly.

**Closed** 2018-06-01 13:12 UTC
Labels: bug
