### ISSUE TITLE
Seeker on automation editor should sync with Seeker on Song Editor

### ISSUE THREAD

**Issue by Praveen-Rai** [LMMS/lmms#5403] opened 2020-02-23 14:28 UTC
Automation tracks can be added at any point in a song. The automation editor has its own measure, meaning it starts with 1 irrespective of the actual measure in the Song Editor. If one wants to change the mixer volume at certain point in the song, one needs to calculate the measure in the Automation Editor, navigate to the measure and change the parameter. The other option is to create another automation track.

For e.g. Refer to the image below : 
![AutomationEditorSeeker](https://user-images.githubusercontent.com/39744031/75113720-2085f100-5676-11ea-894f-eccd6cf80a7b.JPG)

The automation track begins at measure 7 in the song. I've create a fade-In from 1-3 in Automation Track, which corresponds to 7-9 in main song. Here's where it gets mathematical, i wish to create a fade-Out between measure 13 & 15 in the song. Which means i should create Fade-Out between measure 6 & 8 in Automation Editor.

All this could be lot easier if we can create a seeker in the automation editor, which moves along with the seeker in the main song editor. We can also have commands to create a point at the current seek position, to further ease it.

**Comment by Spekular** [comment] 2020-02-23 16:01
Duplicate of #5008

**Closed by Spekular** 2020-02-23 16:01 UTC
Labels: enhancement

**Comment by Spekular** [comment] 2020-02-23 16:08
Also relevant: #3305
