### ISSUE TITLE
New Sounds on Step Sequencer Only 1 Bar

### ISSUE THREAD

**Issue by drunkenjesus** [LMMS/lmms#950] opened 2014-07-08 01:37 UTC
Kinda surprised I didn't see this mentioned when I scanned through this forum

Whenever you extend the "Beat & Bassline Editor" beyond the default one bar then drop a new sound or instrument on it afterwards, only one bar of steps show up so if you put in any hit's they loop every bar, you can still use the piano roll with the sounds but I like to sketch out a drumline with the step sequencer then send it to piano roll to adjust the velocity afterward

Also a somewhat minor issue, when you use the mousewheel to adjust the velocity on step's it's really hard to see how much you're reducing more contrast in the blues would help a lot with that

**Comment by Umcaruje** [comment] 2015-06-30 23:28
Duplicate of #250

**Closed by Umcaruje** 2015-06-30 23:28 UTC
Labels: duplicate
