### ISSUE TITLE
Equalizer: Lowpass filter broken at 48dB

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#4394] opened 2018-06-03 09:38 UTC
-🅱oublas- reported on Discord that the Lowpassfilter at 48dB is broken. I made some pictures to illustrate that:

Edit: I can reproduce this only in the latest master branch. In stable-1.2 it seems to be fine.
----------------------------------------------------------------------------------------------------------------------------

This is the EQ of an earlier version:
![eqshould](https://user-images.githubusercontent.com/6502580/40885220-71e86392-6722-11e8-84e2-12212368fa49.png)

This is the current EQ behavior:
![eqbroken](https://user-images.githubusercontent.com/6502580/40885222-7e0c591c-6722-11e8-8f4c-ccdb51808db5.png)

**Comment by Spekular** [comment] 2018-06-03 10:10
I tried reproducing this when I saw it on Discord, and again after seeing this issue, but I can't get it to happen. Win 10 64 bit on RC6 64 bit:

![image](https://user-images.githubusercontent.com/8918426/40885472-ddf2b1f6-6726-11e8-81f3-a7f0ad394ea4.png)

This screenshot is 3xOsc white noise played on the instrument keyboard, but it also works fine when I play a clip in the song editor as you did, and when I put a filter on a sample rather than 3xOsc.

**Comment by BaraMGB** [comment] 2018-06-03 10:12
@Spekular can you test master?

**Comment by Spekular** [comment] 2018-06-03 10:18
I can try, but I haven't tried compiling LMMS since the whole sub-modules thing was added, and even before that I struggled a bit with it 😅. I'll give it a shot as long as it doesn't eat up too much of my time.

**Comment by BaraMGB** [comment] 2018-06-03 10:28
Since that sub-module thing I clone everything in a seperate folder.

``git clone --recurse-submodule -b master https://github.com/LMMS/lmms.git myNewFoldername``

works well for me.

**Comment by Spekular** [comment] 2018-06-03 10:56
It seems to be even more broken than for you 
![image](https://user-images.githubusercontent.com/8918426/40885786-77fc0ef4-672d-11e8-8d6e-17f360b20f5c.png)

Ubuntu 16.something LTS, if that matters. Compiled from master.

**Comment by PhysSong** [comment] 2018-06-03 11:02
Can anyone try reverting 1e777cf94570a85139c11a41143dc2544ca4319e and then re-test?

**Comment by Spekular** [comment] 2018-06-03 11:15
I'm trying but
`git revert 1e777cf` gives `error: Your local changes would be overwritten by revert.`
So I tried `git reset --hard`
But then a revert gives `fatal: Not a git repository: /home/spekular/Desktop/lmms/.git/modules/plugins/FreeBoy/game-music-emu`
So I tried `git init`, but then I'm back to `local changes would be overwritten`.

Gonna redo the whole clone I guess.

**Comment by Spekular** [comment] 2018-06-03 11:26
Reverting that commit fixed it for me.

**Comment by PhysSong** [comment] 2018-06-03 11:46
Then I guess it's a regression from #4260. Tagging @curlymorphic.

**Comment by zonkmachine** [comment] 2018-06-03 12:09
Here's a line that mix 'hp/lp': https://github.com/LMMS/lmms/blob/1e777cf94570a85139c11a41143dc2544ca4319e/plugins/Eq/EqEffect.cpp#L127

**Comment by PhysSong** [comment] 2018-06-03 12:15
@zonkmachine Good find! I think L125 and L127 should be dropped.

**Comment by curlymorphic** [comment] 2018-06-03 12:55
Please dont drop the lines, I will issue a fix shortly

**Comment by curlymorphic** [comment] 2018-06-09 12:10
Closed by #4396

**Closed by curlymorphic** 2018-06-09 12:10 UTC
