### ISSUE TITLE
Feature Request: Indepently functioning BBE tracks

### ISSUE THREAD

**Issue by RWBYKing** [LMMS/lmms#4319] opened 2018-04-24 06:45 UTC
To the dev team,

To preface: If I am stepping on any toes by requesting this, I do not do so intentionally. I am new to this community, and as such, do not know any of the unwritten rules. Also of note, I should have RTFM before trying to use this software, but I didn't. I have read most of it now, but not before some hiccups, as detailed below.

I ask for this feature because I have accidentally deleted three different phrases in my BB editor due to trying to clear a separate track of the instruments used in the first one. By now, I hope that I have learned my lesson well enough.

The main reason why I believe that this feature would benefit the program is that it provides a more intuitive user experience. If you go to the trouble of making an entirely new track, why should the new track be linked to the old one? Additionally, if you want to make a track that contains instrumental phrases from a different track, isn't that why you have the clone function? It all just seems rather blatantly counter-intuitive.

Sincerely,
A Confused Newbie

**Comment by lukas-w** [comment] 2018-04-24 07:28
@RWBYKing You spent a lot of time describing the reasons for the change you suggest, but almost none at all describing what the actual change is. Can you describe in more detail the behaviour you wish to see? Maybe this is already covered by #453 or #454.

**Comment by musikBear** [comment] 2018-04-24 15:15
i believe RBW has deleted BB-track in song-editor, and to his horror he realizes, that he also now has lost the actual notes in BB-editor.
So this is **Worse: How Newbies Fix This** from  #453

**Comment by RWBYKing** [comment] 2018-05-16 02:53
@musikBear You are correct. That is the problem I was encountering.

@lukas-w I do suppose that the 'hide unused tracks' button that was suggested in #453 would be a workable compromise. It's less intrusive for the wider userbase and easier to implement, so I think I'd be able to live with a slightly-less-than-optimal UX in my personal case.

**Comment by lukas-w** [comment] 2018-05-16 06:56
@RWBYKing Your answer still doesn't describe what would be the "optimal UX in your personal case".

As the only hint you've given about the improvement you suggest – the issue's title "Indepently functioning BBE tracks" – fits #453's description pretty well, I'm closing this as duplicate of #453. Feel free to correct me on this.

**Closed by lukas-w** 2018-05-16 06:56 UTC
Labels: enhancement, gui

**Comment by lukas-w** [comment] 2018-05-16 21:14
> have different groups of instruments for different tracks

This still sounds exactly the same to me as what's described in https://github.com/LMMS/lmms/issues/453#issue-29404765, which proposes "to allow the list of instruments to be stored specific to a Beat/Bassline". If that's any different from what you have in mind, please explain.
