### ISSUE TITLE
AFP closes when I bind the Start and End knobs.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#7302] opened 2024-06-03 00:42 UTC
### System Information

Debian Sid Cinnamon

### LMMS Version(s)

Nightly Version

### Most Recent Working Version

Versión 1.3.0-alpha.1.629+g43fbcca9c (Linux/x86_64, Qt 5.12.8, GCC 9.4.0).

### Bug Summary

I don't know if I'm using AFP properly, but I wanted to emulate a basic wave table by linking the Start and End knobs in loop mode, but when I link both knobs, LMMS crashes or closes unexpectedly. (This bug only happens when I have a sample in AFP, but not when it is empty) I was even testing with other knobs from other plugins and this didn't happen, I thought this happened only when both knobs have inaccurate values, for example: I don't see any problems when I link the volume to the pan.

https://github.com/LMMS/lmms/assets/26127693/856a3250-6c86-44cf-bb8b-a5aa458641fb

I want to know if I am using AFP wrong, or if it is a bug? 

### Expected Behaviour

That AFP doesn't mess up when I link the Start knob to Ends.

### Steps To Reproduce

1- Open LMMS
2- Import a sample in AFP
3- Link the Start knob with End, and move one of the knobs
4- LMMS hangs or closes unexpectedly 

### Logs

Carla appears to be installed on this system at /usr/lib[64]/carla so we'll use it.
Jack appears to be installed on this system, so we'll use it.
Lv2 plugin SUMMARY: 286 of 517  loaded in 3112 msecs.
For details about not loaded plugins, please set
  environment variable "LMMS_LV2_DEBUG" to nonempty.
Lv2 Plugins blacklisted: 61 of 517 
  If you want to ignore the blacklist (dangerous!), please set
  environment variable "LMMS_IGNORE_BLACKLIST" to nonempty.
Connection established.

Stream successfully created

/tmp/.mount_lmmswCg7xU/AppRun: línea 24:  9545 Violación de segmento  QT_X11_NO_NATIVE_MENUBAR=1 "$DIR"/usr/bin/lmms.real "$@"

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by zonkmachine** [comment] 2024-06-03 06:26
Duplicate of https://github.com/LMMS/lmms/issues/2149

**Closed** 2024-06-03 06:27 UTC
Labels: duplicate
