### ISSUE TITLE
Switches bound to controller don't affect recording

### ISSUE THREAD

**Issue by etuardu** [LMMS/lmms#1895] opened 2015-03-23 14:46 UTC
LMMS 0.4.10 (Linux/i386, Qt 4.8.2, GCC 4.7.1)
Debian 7.8 (wheezy), kernel Linux 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1+deb7u2 i686 GNU/Linux

In the settings window of a track, I'm able to connect a switch to a midi controller (a pedal recognized as channel: 1, controller: 65).
I can hear it's working fine while I play and I can see the switch's green light indicator turning on and off as I press and release the pedal.
I tried to bind e.g. the "chords" switch in FUNC; or the REL switch in ENV/LFO - RESO (this one is what I actually need to control the sustain with the pedal!) and they all works as expected as I play the keyboard and while I record it.
Still, the recorded track is not affected by the switches.
In the piano roll the notes appear just as the switches were off.

Thanks for any help!

**Comment by tresf** [comment] 2015-03-23 14:50
Possible duplicate of #1159? (Parent #1472)

**Comment by tresf** [comment] 2015-03-23 14:52
> LMMS 0.4.10 (Linux/i386, Qt 4.8.2, GCC 4.7.1)

Wait a second.... If your version is correct, this is a very old version (~2011).

Do you have an option to try a newer version?

-Tres

**Comment by Umcaruje** [comment] 2015-07-05 21:15
@etuardu can you confirm this issue on the latest version of lmms (1.1.3)?

**Comment by Umcaruje** [comment] 2015-08-24 21:10
No response for over a month. Closing.

**Closed by Umcaruje** 2015-08-24 21:10 UTC
Labels: needs clarification
