### ISSUE TITLE
Factory files separator incorrectly placed if factory directory has subdirectories.

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#3183] opened 2016-12-27 21:54 UTC
My Samples/drums, My Samples/drumsynth and My Presets/ZynAddSubFX.
I have my own folders under samples/misc and there is no separator at all.
I'm using up to date master.

**Comment by DeRobyJ** [comment] 2016-12-28 11:41
duplicate of #1150, seems that the fix didn't do it :(

**Comment by zonkmachine** [comment] 2019-11-01 02:13
This seem to be a remaining  issue from fixing #1150. Earlier fixed in #2665 and #1505.
From testing the issue it appeared to be the user added directories that already seemed counted for in 
`top_index` when computing position for the delimiter.
https://github.com/LMMS/lmms/blob/fd203c3f7b8d2d7126c7dda51e47761d13de4972/src/gui/FileBrowser.cpp#L778

Either `top_index` need to go down or `m_dirCount`. `top_index` is computed with one call to the Qt function childCount() and there didn't seem to be a way to easily omit directories from that call. The easiest way was to remove one of the two instances where `m_dirCount` is increased. One of them did the trick but I can't answer for precisely how that code works.

Fix in https://github.com/LMMS/lmms/pull/5296

**Comment by zonkmachine** [comment] 2019-11-04 23:40
I'm still wrestling to fully understand the issue here but I think it's essentially related to https://github.com/LMMS/lmms/issues/1925 which was fixed in https://github.com/LMMS/lmms/pull/1934.

**Comment by karmux** [comment] 2019-11-13 01:16
TripleOscillator now:
![Screenshot_20191113_090643](https://user-images.githubusercontent.com/2575235/68724107-94374d00-05f5-11ea-8999-2fdf02aae699.png)
(works correctly when there are no user directories but just files)

Zyn now has missing factory preset separator when there is user subfolder. Otherwise everything are marked as user files (factory files + user files) and nothing after separator.

**Comment by zonkmachine** [comment] 2019-11-16 14:47
This is what it looks like to me on lmms-1.2.1 (left) and on lmms-1.2.1 with fix (right).

![output](https://user-images.githubusercontent.com/6368949/68994850-bb0cb200-0887-11ea-8aa9-73233a0a185a.png)

**Comment by zonkmachine** [comment] 2020-01-22 19:25
Closed in https://github.com/LMMS/lmms/pull/5378

**Closed by zonkmachine** 2020-01-22 19:25 UTC
Labels: bug
