### ISSUE TITLE
RemoteVst still running after LMMS exit

### ISSUE THREAD

**Issue by DaAwesomeP** [LMMS/lmms#1182] opened 2014-09-29 02:34 UTC
They were taking up RAM. I noticed this in Task Manager. There were quite a few of them - one for each of the VSTs I had open in vestige in the most recent project. I had to force quit them.

Windows 8 Pro 32-bit

**Comment by zonkmachine** [comment] 2018-01-27 14:26
I close this bug as a duplicate of https://github.com/LMMS/lmms/issues/2774

**Comment by lukas-w** [comment] 2018-01-28 09:41
@zonkmachine I think these are separate issues. #2774 is about `lmms.exe` still running after exit, while this one is about `RemoteVstPlugin.exe` still running.

**Comment by DomClark** [comment] 2018-11-25 20:32
I'm closing this as a duplicate of #4408 as that issue has more recent discussion and a proposed fix.

**Closed by DomClark** 2018-11-25 20:32 UTC
Labels: bug, core, vst
