### ISSUE TITLE
Instrument height wrong with four or more effect units

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#5851] opened 2020-12-18 18:46 UTC
When you add four or more effect units i an instrument it's height gets stretched.
This is on master since a966d25ad2613058586699bb1bf3e11e788acd7d

Method to replicate (updated to [comment](https://github.com/LMMS/lmms/issues/5851#issuecomment-1891090358)):
* Drag the preset "Kicker/SnareMarch.xpf" into the Song Editor.
* Open the instrument.

![instrumentsize](https://user-images.githubusercontent.com/6368949/102648979-bdb39800-4168-11eb-95f1-c5da95453665.png)

**Comment by zonkmachine** [comment] 2021-01-17 05:00
>  This is on master since [a966d25](https://github.com/LMMS/lmms/commit/a966d25ad2613058586699bb1bf3e11e788acd7d)

@JohannesLorenz

**Comment by JohannesLorenz** [comment] 2021-01-17 09:51
I just used 3osc, switched to FX tab and added 5 effects. No resize.

Can you please describe the exact steps required to repoduce? Maybe it's even fixed 1 month later, now that @PhysSong fixed the instrument window caching.

**Comment by PhysSong** [comment] 2021-01-17 11:16
You can try saving and reloading after adding a lot of effects.

**Comment by zonkmachine** [comment] 2021-01-17 13:06
you are right, I can't replicate this. Not now and not on master at the time of this PR. I think I may have been in the middle of a bisect and forgot about it. At least that would explain it. Closing.

**Comment by PhysSong** [comment] 2021-01-17 13:30
I still can. You should add 4 or more effects and save to a project file and reload this. Otherwise, you won't get this bug with the latest `master`.

**Comment by michaelgregorius** [comment] 2024-01-14 22:20
This issue can still be reproduced. One quick way to do so with a stock master was described in #6268:
1. Drag the preset "Kicker/SnareMarch.xpf" into the Song Editor.
2. Open the instrument.

**Comment by JohannesLorenz** [comment] 2024-08-04 23:14
@PhysSong you are self-assigned for more than one year. I just did a quick test with adding `sizeHint()` and `minimumSizeHint()` to `EffectRackView` which fixed it. I hope you are OK with me assigning this to myself.

**Comment by JohannesLorenz** [comment] 2024-08-08 21:53
OPs, feel free to test my PR #7428 that fixes this issue.

**Comment by zonkmachine** [comment] 2024-08-08 21:54
> OPs, feel free to test my PR #7428 that fixes this issue.

Testing is ongoing. No problems so far. I'll comment in the PR.

**Closed** 2024-08-10 03:30 UTC
Labels: bug, gui

**Comment by JohannesLorenz** [comment] 2024-08-10 07:54
@Rossmaxx did merging the PR not close the issue automatically?

**Comment by Rossmaxx** [comment] 2024-08-10 08:37
It did right

**Comment by Rossmaxx** [comment] 2024-08-10 08:38
Well, it showed it as i closed it because i pushed merge on the PR. Might be it.

**Comment by JohannesLorenz** [comment] 2024-08-10 09:16
@Rossmaxx Makes sense. Thanks for explaining.
