### ISSUE TITLE
Saving then quitting leaves the "project saved" popup open and not responding

### ISSUE THREAD

**Issue by whitephoenix0** [LMMS/lmms#2718] opened 2016-04-03 01:13 UTC
Screenshot of issue: https://i.imgur.com/GV8AkHh.jpg 
System info: Windows 10 64-bit running LMMS 1.2.0 RC1 64-bit

Steps to reproduce (on windows): 
1. Open LMMS
2. Open a project
3. Save project 
4. Close LMMS quickly

Description: When you save a project and then quickly close LMMS it leaves behind the project saved popup until you either kill LMMS in task manager or click "close program" in the windows not responding dialog. I tested this also on Linux with LMMS version 1.1.3 and the issue was not present, so I assume that this is a windows exclusive issue. Keep up the awesome work guys.

**Comment by DeRobyJ** [comment] 2016-04-03 09:10
I think it's duplicate of #2584

**Comment by Spekular** [comment] 2016-04-03 11:58
Confirmed here too. Windows 7 64-bit with 32-bit RC.

**Comment by whitephoenix0** [comment] 2016-04-03 15:57
@DeRobyJ I don't think so. This happens even if you don't load VSTs. In fact I just tried deleted everything from the song editor. Even if I reopen the saved blank project it does the same thing.

**Comment by zonkmachine** [comment] 2016-04-03 16:20
@whitephoenix0 @DeRobyJ  @Spekular 
Can you please check what your working directory is?
Edit->Settings->Paths( second icon to the left )

**Comment by whitephoenix0** [comment] 2016-04-03 19:40
@zonkmachine C:\Users\me\lmms\, I also changed my artwork and vst-plugin directory

**Comment by DeRobyJ** [comment] 2016-04-03 21:19
Same working directory.
And in my first post in that issue I wasn't talking about vsts :v

**Comment by whitephoenix0** [comment] 2016-04-03 21:44
Oh, yeah. It goes away with file->quit so it must just be the same issue

**Closed** 2016-04-03 23:53 UTC
