### ISSUE TITLE
Effect in carla-rack are not exported

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2213] opened 2015-07-26 07:25 UTC
I use lmms-1.1.3 compiled from sources on fedora 21 64 bits + carla from master repository (compiled from sources).

I have a carla-rack with a synth (first rack) + a delay effect (second rack).
When played with lmms, the synth + delay are rendered correctly.
When exported using the export dialog, only the synth is exported. The delay seem disabled.

**Comment by Umcaruje** [comment] 2015-08-03 19:57
Can you specify what exact synth and delay effect are you using, so I can try to reproduce this issue.

**Comment by ycollet** [comment] 2015-08-04 19:16
Hello,

I used nekobi for the synth and TAP Stereo echo for the effect.

Best regards,

YC

**Comment by ycollet** [comment] 2015-08-04 19:23
I opened carla-rack to check what were the synth and the effect and the 
synth was here and the effect was here too.
Now, I just reopened carla-rack via lmms and I just have the synth. The 
effect has disappeared.

Here is the content of the console:

Trying to start carla-plugin using 
"/local/stow/carla-devel/share/carla/resources//carla-plugin"
LRDF Support not available (LADSPA-RDF will be disabled)
Using "carla" theme
Carla 1.9.6 (2.0-beta4) started, status:
   Python version: 3.4.1
   Qt version:     4.8.6
   PyQt version:   4.11.3
   Binary dir:     /local/stow/carla-devel/lib/carla
   Resources dir:  /local/stow/carla-devel/share/carla/resources
ALL OK!
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been 
edited
Carla assertion failure: "pData->pipeRecv != INVALID_PIPE_VALUE" in file 
../utils/CarlaPipeUtils.cpp, line 1012
Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file 
../utils/CarlaPipeUtils.cpp, line 1093
Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file 
../utils/CarlaPipeUtils.cpp, line 1093
Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file 
../utils/CarlaPipeUtils.cpp, line 1093
Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file 
../utils/CarlaPipeUtils.cpp, line 1093
Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file 
../utils/CarlaPipeUtils.cpp, line 830
Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file 
../utils/CarlaPipeUtils.cpp, line 1093
Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file 
../utils/CarlaPipeUtils.cpp, line 1093
Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file 
../utils/CarlaPipeUtils.cpp, line 830
Really deleting  "sf2/Power mute.sf2"
fluidsynth: warning: No preset found on channel 0 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 1 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 2 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 3 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 4 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 5 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 6 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 7 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 8 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
fluidsynth: warning: No preset found on channel 10 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 11 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 12 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 13 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 14 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 15 [bank=0 prog=0]

**Comment by ycollet** [comment] 2015-08-06 19:17
I recompiled lmms-1.1.3 with carla-1.9.6 (instead of carla-master) and the result is the same. The last effect is missing most of the time.

**Comment by karmux** [comment] 2017-06-03 19:09
I can't reproduce with exact same plugins. LMMS 1.2.0-master and Carla 1.9.7.

**Comment by zonkmachine** [comment] 2018-01-20 13:19
> I recompiled lmms-1.1.3 with carla-1.9.6 (instead of carla-master) and the result is the same.

@ycollet Can you please try this with the latest lmms-1.2 release candidate? (currently rc5)

> The last effect is missing **most of the time**.

So it's an intermittent issue.

**Comment by tresf** [comment] 2018-03-06 22:51
No reply from OP in years.  Closing.  Please request a reopen if this can be reproduced on a newer version.  At the time of writing this, 1.2.0 beta or higher.

**Closed by tresf** 2018-03-06 22:51 UTC
Labels: needs clarification
