### ISSUE TITLE
Automation Error/bug (maybe computer issue)

### ISSUE THREAD

**Issue by Maserat52** [LMMS/lmms#4287] opened 2018-04-07 22:46 UTC
In LMMS I commonly use automation, but whenever I do now, the screen freezes. The audio still plays, but everything else stops responding. Not sure if this has to do with my computer or not, but thought this might be an LMMS issue.

I use a MacBook Air (13-inch, Mid 2012).

**Comment by tresf** [comment] 2018-04-08 01:54
Sounds similar to #2504

**Comment by Maserat52** [comment] 2018-04-08 16:08
Sorry, hadn’t noticed.

**Comment by lukas-w** [comment] 2018-04-18 05:57
Assuming this is a duplicate of #2504. Please reopen if I'm mistaken.

**Closed by lukas-w** 2018-04-18 05:57 UTC
