### ISSUE TITLE
no stk-package in LMMS 1.3

### ISSUE THREAD

**Issue by YaroslavNovikov** [LMMS/lmms#6489] opened 2022-08-18 15:45 UTC
Installation LMMS 1.3 without errors. When trying use mallets I get this message. And, without stk-package this instrument has no sound
![nostk](https://user-images.githubusercontent.com/60749597/185437598-6c425c85-e7c1-4f7a-9dd0-3b55a4f6bcc8.png)
.

**Comment by Rossmaxx** [comment] 2022-08-19 05:22
duplicate of #6464

**Closed** 2022-08-19 10:37 UTC
