### ISSUE TITLE
Add microphone input to sampler track/AudioFileProcessor

### ISSUE THREAD

**Issue by YesImAsh** [LMMS/lmms#7434] opened 2024-08-06 08:59 UTC
### Enhancement Summary

It is what it is, it converts audio signals from microphone input, and sends it to a sample track, or an afp (if you're using that to record)
In other words, it records audio
I honestly dont get why this hasn't been added

people can record live instruments, sing, ALL this cool stuff is possible 

### Implementation Details / Mockup

There will be a record button with a microphone icon.

My theory is that there will be a microphone value between -100 to 100
depending on the audio signal of the microphone input, is what the value gets set to

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by qnebra** [comment] 2024-08-06 09:17
Three already existing requests for sample recording:

https://github.com/LMMS/lmms/issues/7033
https://github.com/LMMS/lmms/issues/6963
https://github.com/LMMS/lmms/issues/5520

**Comment by YesImAsh** [comment] 2024-08-06 09:21
Given how old those enhancement requests are, i can assume that its not gonna be added anytime soon let alone at all?

**Comment by szeli1** [comment] 2024-08-06 09:53
> Given how old those enhancement requests are, i can assume that its not gonna be added anytime soon let alone at all?

It will be added, #5990 had recent commits and comments from 2 weeks ago.

**Comment by YesImAsh** [comment] 2024-08-06 10:37
cool

**Comment by sakertooth** [comment] 2024-08-06 11:43
Duplicate of the issues mentioned above.

**Closed by sakertooth** 2024-08-06 11:43 UTC
Labels: enhancement
