### ISSUE TITLE
Cannot open any VSTs

### ISSUE THREAD

**Issue by CtrlFreak1337** [LMMS/lmms#2488] opened 2015-12-17 12:44 UTC
This includes Synth1. I'm on Ubuntu 15.10, running LMMS 1.1.3, and I have wine installed. I'm using the version from the KXStudio repository (just lmms, lmms-vst-full does not exist on amd64). I can drag a VeSTige track into the song editor, but trying to open one just pulls up the generic "The VST could not be loaded" message. For Synth1, I've tried loading both the default and 64 versions, both with the same result. Is something wrong with my system or setup? Should I delete the KXStudio version and just download the one from Universe?

After reinstalling lmms-vst-full:i386, it now at least attempts to load VSTs instead of immediately dropping to the load failed message, but it hangs and stops responding, and can only be closed.

**Comment by tresf** [comment] 2015-12-27 02:22
This is most likely a duplicate of #1875 which we've yet to fix (most likely a bug between the shared memory logic and wine).

If this isn't a duplicate of #1875, when it is a packing issue with KXStudio.  Either way, it's a duplicate of another documented issue.

**Closed by tresf** 2015-12-27 02:22 UTC

**Comment by CtrlFreak1337** [comment] 2015-12-27 02:32
Alright, thanks for getting back to me.

**Comment by tresf** [comment] 2015-12-27 02:34
Probably a better duplicate bug report is here: #2448
