### ISSUE TITLE
request: zoomable UI

### ISSUE THREAD

**Issue by opensourcefree** [LMMS/lmms#6537] opened 2022-10-10 02:35 UTC
Hi

I want to request a feature to zoom in/out the entire UI so we can zoom to exactly the size we want for any monitor and in a cross-platform way.

You can see it for example in Ableton Live which is also using QT 5.

https://m.youtube.com/watch?v=KT9yjBweEl0

Thanks
Lisa

**Comment by allejok96** [comment] 2022-10-10 19:30
Duplicate of #5376

**Closed by allejok96** 2022-10-10 19:30 UTC
Labels: duplicate
