### ISSUE TITLE
1.2.0 crashes when clicking on 'Add effect'

### ISSUE THREAD

**Issue by kaervin** [LMMS/lmms#4709] opened 2018-11-15 15:40 UTC
As the title says,  when clicking on 'Add effect' anywhere lmms 1.2 rc7 crashes.
It is the fresh appimage version downloaded from the website.
It does work with 1.1.3 I have installed from the Ubuntu repo.
Here is my terminal output:
```
./lmms-1.2.0-rc7-linux-x86_64.AppImage
Carla appears to be installed on this system at /usr/lib[64]/carla so we'll use it.
Jack appears to be installed on this system, so we'll use it.
/tmp/.mount_lmms-1hZ8dS9/usr/bin/lmms.real: /tmp/.mount_lmms-1hZ8dS9/usr/lib/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)
Notice: could not set realtime priority.
VST sync support disabled in your configuration
```

**Comment by kaervin** [comment] 2018-11-15 15:48
I should also note that the program pretty much freezes, and I have to forcibly quit it by ctrl+c

**Comment by kaervin** [comment] 2018-11-15 15:56
I'll try running a debug build tomorrow to see if it tells me anything.

**Comment by kaervin** [comment] 2018-11-16 04:37
compiling it myself fixed the issue.

**Comment by SecondFlight** [comment] 2018-11-16 14:42
That's... strange. Looks to be the same as https://github.com/LMMS/lmms/issues/3736 and https://github.com/LMMS/lmms/issues/4419, both of which didn't go anywhere as the original posters quit responding.

**Comment by kaervin** [comment] 2018-11-16 17:04
Well, I wouldn't even know how to figure out what was wrong, since it just works when I compile it myself.

**Comment by kaervin** [comment] 2018-11-17 06:45
Ok, running it with the config of my home folder, it does crash.
Comparing the two, there are some differences. The difference that causes the crash is:
crash: vstdir="/home/kaervin/"
not-crash: vstdir="/home/kaervin/lmms/plugins/vst/"

I figured out why this happens too.
In the file plugins/VstEffect/VstSubPluginFeatures.cpp, in the function
void VstSubPluginFeatures::addPluginsFromDir( QStringList* filenames, QString path ) const
it recursively scans through my home folder.
Too bad there is a symlink path somewhere in there, which leads exactly to my home-folder, and you can imagine what happens then...
Anyway, there are multiple ways to fix this, which kind of has to be decided by someone who makes choices around here.
A good fix I would think would be, to remember all the visited symlinks, and when encountering them a second time to not go through them again.

**Comment by DomClark** [comment] 2018-12-09 18:14
Duplicate of #3528.

**Closed by DomClark** 2018-12-09 18:14 UTC
Labels: bug
