### ISSUE TITLE
LMMS crashes on launch on Windows 10

### ISSUE THREAD

**Issue by BenMcLean** [LMMS/lmms#3033] opened 2016-09-11 15:06 UTC
When I try to launch LMMS 1.1.3 Windows 10 64 bit version on my ASUS Q551LN-BBI706 laptop, I get the "The application has requested the Runtime to terminate it in an unusual way." box (which I see from various other issues has happened in the past, but not lately and not on Windows 10 AFAIK) and then a "Debug or Close" window. By selecting "Debug" with Microsoft Visual Studio as my debugger, I get this info:

```
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\lmms.exe'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\apphelp.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\QtCore4.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\QtGui4.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\comdlg32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\QtXml4.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\SDL.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libogg-0.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libportaudio-2.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libsamplerate-0.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libsndfile-1.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libvorbis-0.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libvorbisenc-2.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libvorbisfile-3.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\zlib1.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.14393.0_none_4151bdeb4bbdd21f\comctl32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\winspool.drv'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libpng16-16.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libFLAC-8.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\userenv.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\UIAutomationCore.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\sxs.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\oleacc.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.appcore.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\amplifier.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\audiofileprocessor.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\bassbooster.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\bitinvader.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\delay.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\dualfilter.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\dynamicsprocessor.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\flpimport.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\hydrogenimport.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\kicker.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspabrowser.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspaeffect.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\lb302.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\libZynAddSubFxCore.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libfftw3f-3.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libwinpthread-1.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\malletsstk.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\midiimport.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\monstro.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\nes.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\OPL2.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\organic.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\papu.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\patman.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\peakcontrollereffect.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\sf2player.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libfluidsynth.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libglib-2.0-0.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\dsound.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libgthread-2.0-0.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\sfxr.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\sid.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\spectrumanalyzer.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\stereoenhancer.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\stereomatrix.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\tripleoscillator.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\vibedstrings.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\vstbase.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\vsteffect.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\watsyn.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\waveshaper.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\zynaddsubfx.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\vestige.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libfltk.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\libjpeg-9.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\QtSvg4.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\alias_1407.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\allpass_1895.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\am_pitchshift_1433.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\amp_1181.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\bandpass_a_iir_1893.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\bandpass_iir_1892.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\bode_shifter_1431.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\bode_shifter_cv_1432.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\butterworth_1902.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\calf.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\caps.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\chebstortion_1430.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\cmt.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\comb_1190.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\comb_1887.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\comb_splitter_1411.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\const_1909.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\crossover_dist_1404.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\dc_remove_1207.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\decay_1886.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\decimator_1202.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\declip_1195.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\delay_1898.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\delayorama_1402.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\diode_1185.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\divider_1186.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\dj_eq_1901.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\dj_flanger_1438.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\dyson_compress_1403.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\fad_delay_1192.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\fast_lookahead_limiter_1913.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\flanger_1191.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\foldover_1213.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\foverdrive_1196.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\freq_tracker_1418.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\gate_1410.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\giant_flange_1437.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\gong_1424.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\gong_beater_1439.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\gsm_1215.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\gverb_1216.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\hard_limiter_1413.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\harmonic_gen_1220.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\hermes_filter_1200.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\highpass_iir_1890.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\hilbert_1440.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\imp_1199.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\impulse_1885.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\inv_1429.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\karaoke_1409.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\ladspa-util.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\latency_1914.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\lcr_delay_1436.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\lowpass_iir_1891.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\ls_filter_1908.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\matrix_ms_st_1421.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\matrix_spatialiser_1422.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\matrix_st_ms_1420.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\mbeq_1197.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\mod_delay_1419.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\multivoice_chorus_1201.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\notch_iir_1894.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\phasers_1217.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\pitch_scale_1193.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\pitch_scale_1194.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\plate_1423.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\pointer_cast_1910.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\rate_shifter_1417.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\retro_flange_1208.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\revdelay_1605.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\ringmod_1188.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\satan_maximiser_1408.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\sc1_1425.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\sc2_1426.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\sc3_1427.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\sc4_1882.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\sc4m_1916.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\se4_1883.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\shaper_1187.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\sifter_1210.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\sin_cos_1881.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\single_para_1203.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\sinus_wavewrapper_1198.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\smooth_decimate_1414.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\split_1406.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\step_muxer_1212.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\surround_encoder_1401.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\svf_1214.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_autopan.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_chorusflanger.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_deesser.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_doubler.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_dynamics_m.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_dynamics_st.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_echo.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_eq.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_eqbw.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_limiter.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_pinknoise.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_pitch.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_reflector.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_reverb.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_rotspeak.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_sigmoid.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_tremolo.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_tubewarmth.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tap_vibrato.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\tape_delay_1211.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\transient_1206.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\triple_para_1204.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\valve_1209.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\valve_rect_1405.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\vocoder_1337.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\vynil_1905.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\wave_terrain_1412.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\xfade_1915.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Program Files\LMMS\plugins\ladspa\zm1_1428.dll'. Module was built without symbols.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\MMDevAPI.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\AudioSes.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\wdmaud.drv'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\ksuser.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\avrt.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\msacm32.drv'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\msacm32.dll'. Cannot find or open the PDB file.
'lmms.exe' (Win32): Loaded 'C:\Windows\System32\midimap.dll'. Cannot find or open the PDB file.
The thread 0x1c0c has exited with code 0 (0x0).
The thread 0x2374 has exited with code 3 (0x3).
The thread 0x202c has exited with code 3 (0x3).
The thread 0x1f54 has exited with code 3 (0x3).
The thread 0x2528 has exited with code 3 (0x3).
The thread 0x1978 has exited with code 3 (0x3).
The thread 0x1efc has exited with code 3 (0x3).
The thread 0x23a8 has exited with code 3 (0x3).
The thread 0x23a0 has exited with code 3 (0x3).
The thread 0x23b4 has exited with code 3 (0x3).
The thread 0x23b0 has exited with code 3 (0x3).
The thread 0x23d0 has exited with code 3 (0x3).
The thread 0x23dc has exited with code 3 (0x3).
The thread 0x1900 has exited with code 3 (0x3).
The thread 0x2348 has exited with code 3 (0x3).
The thread 0x2550 has exited with code 3 (0x3).
The thread 0x24c8 has exited with code 3 (0x3).
The thread 0x21d0 has exited with code 3 (0x3).
The thread 0x1270 has exited with code 3 (0x3).
The program '[9196] lmms.exe' has exited with code 3 (0x3).
```

No idea whether that's relevant or helpful or not. It's strange that this says "Win32" when I am trying to use the 64 bit version.

I tried reinstalling my audio drivers and rebooting. No effect.

**Comment by Spekular** [comment] 2016-09-11 15:20
Are you sure you downloaded the 64-bit version? If you got the 32-vit version that wpuld explain the logs.

As for the issue itself, have you checked if the 1.2-rc works?

**Comment by BenMcLean** [comment] 2016-09-11 15:27
Yep, I'm sure. I just uninstalled, downloaded the 64 bit version, "lmms-1.1.3-win64.exe" uninstalled that, tried again, got same messages with "Win32" in there.

**Comment by Spekular** [comment] 2016-09-11 15:31
Well that's definitely weird. I guess I'd try the 32-bit version or the Release Candidate next.

**Comment by tresf** [comment] 2016-09-11 15:34
@BenMcLean this is most likely a duplicate of

### 1.1.3 Known issues with this release

 * Windows
  * Software fails to load on some systems (Please see bug #1173, #512)

This is mentioned in our release notes.  https://github.com/LMMS/lmms/releases/tag/v1.1.3

P.S. Please ignore the `win32` messages.

**Comment by Umcaruje** [comment] 2016-09-11 15:35
This is a known issue. Please check out issues #512 and #1173

**Comment by Umcaruje** [comment] 2016-09-11 15:35
@tresf ninja'd

**Closed by Umcaruje** 2016-09-11 15:35 UTC
