### ISSUE TITLE
FL VSTi not running

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#4413] opened 2018-06-08 17:50 UTC
I tried to use a FL VSTi i have, and LMMS (or Windows?) says `QuickFontCache DLL not found!`
After closing that, another box pops up that says `Runtime error 216 at 04AD64AE`.

Windows 10, 64-bit
LMMS 1.2.0 RC6 64-bit
The VSTi is attached. There are two versions(?), and both throw the same error.
[VST DAWS-Software-20180608T174121Z-001.zip](https://github.com/LMMS/lmms/files/2085479/VST.DAWS-Software-20180608T174121Z-001.zip)

**Comment by GingkathFox** [comment] 2018-06-08 17:54
I tried again, and another box popped up:
`Runtime error 216 at 04BA64AE

**Comment by DomClark** [comment] 2018-06-08 19:39
I can't reproduce this - it loads fine for me. A quick internet search suggests you are missing some files required for FL studio - try reinstalling FL and see if that fixes things.

**Comment by GingkathFox** [comment] 2018-06-08 20:50
thats the problem:  the VSTis just appeared.

**Comment by DomClark** [comment] 2018-06-08 20:53
That's your problem then; these are designed to load FL itself as a VST, so if you don't have FL they won't work.

**Comment by SecondFlight** [comment] 2018-06-08 20:53
Sorry, I'm not sure what you're saying. Do you have FL Studio installed? As I understand it, the FL Studio VST is just a bridge to the full application.

**Comment by SecondFlight** [comment] 2018-06-08 20:55
Alright, I'll close this issue then. If you still have trouble after installing FL, let us know. If you don't own FL you can still install the demo. I'm not 100% sure the demo works as a VST but I don't see why it wouldn't.

**Closed by SecondFlight** 2018-06-08 20:55 UTC
