### ISSUE TITLE
Should Save preset allow use of / ( forward slash ) in preset name ?

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#1831] opened 2015-03-06 21:26 UTC
![slash](https://cloud.githubusercontent.com/assets/335217/6536620/1ede7a50-c447-11e4-8a68-cf6455d0e135.png)

As you can see I have tried to save a preset with the name " Bass/lead " , but the forward slash is seen as a new directory ( that doesn't exist ) on Linux.

I suspect this would be hard to fix, and it is no real big problem, but I thought I should point it out tho.

And I imagine this could make file sharing quite impossible too ......

Oh one thing, maybe have at least a warning when someone tries to save a preset with a / in the name instead of just the file permission warning ??

thanks Mikobuntu ;)

**Comment by tresf** [comment] 2015-03-06 21:35
I've never used a desktop application that allowed a backslash to silently create directories for the user... Usually, people click the "New folder" icon and go from there.  I would say we shouldn't stray much from the norm.

![image](https://cloud.githubusercontent.com/assets/6345473/6536820/cbf977f4-c41e-11e4-9e4a-60e54211e038.png)


-Tres

**Comment by mikobuntu** [comment] 2015-03-06 21:59
@tresf Yes I can see your logic, but my case is " what if the user forgetfully ( or chooses to ) use a slash in their filename ? " ( that is what I had absent mindedly done because the preset I created could be used for a bass and a lead synth hence the forward slash ... * note I was not trying to create a new directory *
![slash2](https://cloud.githubusercontent.com/assets/335217/6537135/cefabc74-c44b-11e4-9baa-3af902362f0e.png)

I'm just thinking that it might be useful to at least include a message in the error window that the user may have used a slash in their preset File_name:

**Comment by tresf** [comment] 2015-03-06 22:29
> I'm just thinking that it might be useful to at least include a message in the error window that the user may have used a slash in their preset File_name:

This is really a duplicate of #671.  The question is, how much do we coddle the users on this stuff?

The error is completely correct... it can't write to that file.

If we used the OS save-as dialogs, we might get some better output... Here's what QT Linguist shows in your use-case:

![image](https://cloud.githubusercontent.com/assets/6345473/6537588/4aa297b4-c426-11e4-9753-9b87e6d98a45.png)

But this is because QT falls back onto the OS dialogs rather than invoking the cross-platform QT dialogs.

**Comment by eagles051387** [comment] 2015-03-07 06:33
Couldnt we do like on windows where it pops up a message saying what things
are not allowed in a file name and / is one of them on the windows list


On Fri, Mar 6, 2015 at 11:29 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> I'm just thinking that it might be useful to at least include a message in
> the error window that the user may have used a slash in their preset
> File_name:
>
> This is really a duplicate of #671
> <https://github.com/LMMS/lmms/issues/671>. The question is, how much do
> we coddle the users on this stuff?
>
> The error is completely correct... it can't write to that file.
>
> If we used the OS save-as dialogs, we might get some better output...
> Here's what QT Linguist shows in your use-case:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/6345473/6537588/4aa297b4-c426-11e4-9753-9b87e6d98a45.png>
>
> But this is because QT falls back onto the OS dialogs rather than invoking
> the cross-platform QT dialogs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1831#issuecomment-77648318>.
>



-- 
Jonathan Aquilina

**Comment by mikobuntu** [comment] 2015-03-07 12:02
@tresf Sorry I never noticed the other post ( the tracker is getting quite huge now ) Tho that is a valid point about how much do we coddle the users on this stuff. @eagles051387 A dialogue in the warning window may be sufficient ( separate popups can be annoying ),maybe  just a matter of adding some text, generally warning users to be careful of OS specific characters?

**Comment by eagles051387** [comment] 2015-03-07 14:17
Windows doesnt pop up a seperate dialgoue but more of a tool tip which then
disappears when you remove the offending slash or any other offending
symbol.

On Sat, Mar 7, 2015 at 1:02 PM, Mikobuntu <notifications@github.com> wrote:

> @tresf <https://github.com/tresf> Sorry I never noticed the other post (
> the tracker is getting quite huge now ) Tho that is a valid point about how
> much do we coddle the users on this stuff. @eagles051387
> <https://github.com/eagles051387> A dialogue in the warning window may be
> sufficient ( separate popups can be annoying ),maybe just a matter of
> adding some text, generally warning users to be careful of OS specific
> characters?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1831#issuecomment-77686495>.
>



-- 
Jonathan Aquilina

**Comment by mikobuntu** [comment] 2015-03-07 14:23
@eagles051387 Ah yeah I see now, perhaps our own builtin tooltips could be used in this way ?

**Comment by tresf** [comment] 2015-03-07 14:29
We may need to eventually split up the Save Dialog vs. Open Dialog, but for now, I've consolidated this into #1834.

-Tres

**Closed by tresf** 2015-03-07 14:29 UTC
