### ISSUE TITLE
Triple OSC new UI proposal 

### ISSUE THREAD

**Issue by LocoMatt** [LMMS/lmms#2243] opened 2015-08-08 17:39 UTC
Hello, I decided to redesign my old UI for Triple OSC. With some help of my brother here is it. I'm waiting for your advices and opinions. If you like it I can bring source files to implement it into LMMS.
![triple](https://cloud.githubusercontent.com/assets/6965480/9151524/fee05d1c-3e04-11e5-999a-f33531e46fed.PNG)
**EDIT** 
 > changed name from Triple OSC to full name (Triple Oscillator)
 > changed fonts
 > PD/SPD - fixed to PO/SPO
 > sine shape block rotated by 180 degree
 > some text aligns
![triple](https://cloud.githubusercontent.com/assets/6965480/9160931/486edd6a-3f3f-11e5-8104-6e10634c6840.PNG)
>added citrus
>changed sine and noise wave
>new user shape icon
![synnth](https://cloud.githubusercontent.com/assets/6965480/9294749/d9172d88-4456-11e5-8654-614780e5aa02.PNG)

**Comment by grejppi** [comment] 2015-08-08 18:06
SPO, not SPD.

**Comment by grejppi** [comment] 2015-08-08 18:09
Also, PD should be PO.

It stands for (Stereo) Phase **Offset**.

**Comment by LocoMatt** [comment] 2015-08-08 18:20
Oh my bad, here's fixd 
![triple](https://cloud.githubusercontent.com/assets/6965480/9151662/e765214e-3e0a-11e5-8ffd-c71920fc86e7.PNG)

**Comment by StakeoutPunch** [comment] 2015-08-08 19:09
Looks brilliant! Do you have pictures of it implemented with the current default theme?

**Comment by grejppi** [comment] 2015-08-08 19:51
Some more things...
* The bitmap fonts are not the correct size, so the labels look blurry,
* OSC1+OSC2 and OSC2+OSC3 do not align, and
* The sine waveform is inverted.

**Comment by LocoMatt** [comment] 2015-08-08 21:26
@StakeoutPunch Yeah it's already working.
@grejppi Updated
![triple](https://cloud.githubusercontent.com/assets/6965480/9152347/c15313ca-3e24-11e5-9a90-06576cde880b.PNG)

**Comment by tkotobu1048** [comment] 2015-08-09 02:17
Gooood!

**Comment by musikBear** [comment] 2015-08-09 10:21
orange is a color that rarely works in design. It has to do with the feeling of alert and actually fear.
It is genome in-coded -orange is a 'leave this place now' signal
soo.
no- from me.

**Comment by LocoMatt** [comment] 2015-08-09 14:39
New version for @musikBear 
![11111](https://cloud.githubusercontent.com/assets/6965480/9155331/2f2698a0-3eb5-11e5-9ef1-57d16f55b468.png)

**Comment by LocoMatt** [comment] 2015-08-09 17:29
And here's a new version for everyone else
<img>forSureNotYellow.png</img>
@edit 
Oh, my bad
![triple](https://cloud.githubusercontent.com/assets/6965480/9156042/b9322e76-3ecc-11e5-9d43-fca9d734b547.PNG)

**Comment by tresf** [comment] 2015-08-10 03:39
The artwork and color choice I find to be pleasing, however the icon I do not find to fit in our plugins section very well as it is just words, which offer nothing over the words already there, IMO.

@musikBear 

> orange is a color that rarely works in design. 

Hmm... 
http://www.colormatters.com/color-and-marketing/59-color-symbolism/the-meanings-of-colors

Probably more accurate to simply say that you don't like the color. :smile: 

That said, I wouldn't be opposed to embracing the orange and embrace the citrus.



*Foods* for thought...


![screen shot 2015-08-09 at 11 35 12 pm](https://cloud.githubusercontent.com/assets/6345473/9159078/b622fbfc-3eef-11e5-9d79-80cb339340b1.png)

**Comment by tresf** [comment] 2015-08-10 03:41
Also, I always prefer a before/after side-by-side comparison when we do these things... I think it is important for us to know what exactly we're replacing when we look at a new idea.

I also recommend the original post is regularly edited (with a note saying so) for those just landing on this thread.

**Comment by tresf** [comment] 2015-08-10 03:48
P.S. Here's the email archive from when we redid AudioFileProcessor, for those interested... 

http://linux-multimedia-studio-lmms.996328.n3.nabble.com/AudioFileProcessor-WIP-td5729.html

**Comment by LocoMatt** [comment] 2015-08-10 07:20
Ok I've updated 1st post with newest image and "changelog". Reffering to logo, at the beginning I was thinking about lemons or oranges but lemons might look like stolen idea (FL Studio - Sytrus), well only oranges left, but I didn't run this idea into life because I'm not sure how to do this :P Eventually we can choose another color (let's stay with white+color) of whole UI but we should choose it together.

**Comment by musikBear** [comment] 2015-08-10 14:34
> New version for @musikBear

mmm.. the complementary color for orange is not all that pretty either :p - infact according th Goethe's color theories, that will the case for any 'unpleasant' color
:D 
I just gave my 2 bits, and i have no weight behind anything i say - Perhaps i should go into politic..

**Comment by tresf** [comment] 2015-08-10 14:45
> **in (point of) fact:** (phrase) used to emphasize the truth of an assertion, especially one contrary to what might be expected or what has been asserted.

> "i have no weight behind anything i say"

Well that is quite contradictory. :smile_cat: 

> the complementary color for orange is not all that pretty either :p - infact according th Goethe's color theories, that will the case for any 'unpleasant' color

Ok, now you've thrown out two primary colors.  We have 4 left. :art:

**Comment by StakeoutPunch** [comment] 2015-08-10 15:25
After reading the description of orange on the site Tres linked, I think that orange is the perfect color to capture and symbolize the often rough sound resulting from the simplicity of triple oscillator ;P

**Comment by tresf** [comment] 2015-08-10 16:52
![orange2](https://cloud.githubusercontent.com/assets/6345473/9177321/97412f78-3f5e-11e5-9814-568cbdf5aa43.png)

CC0 orange I just made, if interested.  I can send the SVG as well. :+1:

**Comment by Spekular** [comment] 2015-08-10 17:55
Looks great. If we're going to be doing a big redesign, maybe we can use
the SVG in the plugin art rather than a bitmap? I guess it could be pretty
hard to implement compared to "just" creating the art, but I thought I'd
throw it out there.

**Comment by LocoMatt** [comment] 2015-08-10 17:57
So I asked my bro for any ideas and he came up with something like this
![triple](https://cloud.githubusercontent.com/assets/6965480/9178292/bc49b8f2-3f96-11e5-83df-8d11ba54836c.PNG)
![logo](https://cloud.githubusercontent.com/assets/6965480/9178569/1fd634c6-3f98-11e5-8016-3f026f65a247.png)
and here how does it looks with your idea
![synnth](https://cloud.githubusercontent.com/assets/6965480/9178998/f9e23e84-3f99-11e5-8758-d7ebd67770cc.PNG)
![logo44](https://cloud.githubusercontent.com/assets/6965480/9179001/fbb82228-3f99-11e5-8c28-9b3a6e4a5d65.png)

**Comment by eagles051387** [comment] 2015-08-10 18:02
I would change the wording of the description to say Three powerful
oscillators you can modulate in *different* ways. instead of several.

On Mon, Aug 10, 2015 at 7:57 PM, LocoMatt <notifications@github.com> wrote:

> So I asked my bro for any ideas and he came up with something like this
> [image: triple]
> <https://cloud.githubusercontent.com/assets/6965480/9178292/bc49b8f2-3f96-11e5-83df-8d11ba54836c.PNG>
> [image: logo]
> <https://cloud.githubusercontent.com/assets/6965480/9178569/1fd634c6-3f98-11e5-8016-3f026f65a247.png>
> and here how does it looks with your idea
> [image: synnth]
> <https://cloud.githubusercontent.com/assets/6965480/9178998/f9e23e84-3f99-11e5-8758-d7ebd67770cc.PNG>
> [image: logo44]
> <https://cloud.githubusercontent.com/assets/6965480/9179001/fbb82228-3f99-11e5-8c28-9b3a6e4a5d65.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/2243#issuecomment-129549560>.
>



-- 
Jonathan Aquilina

**Comment by SecondFlight** [comment] 2015-08-10 18:44
It's so beautiful :)

**Comment by tresf** [comment] 2015-08-10 18:55
> I would change the wording of the description to say Three powerful
oscillators you can modulate in *different* ways. instead of several.

Several is more accurate.  Different assumes exclusivity, such as in the scenario that you would like to module them in the same way.  Furthermore, this isn't about cleaning up bad wording in the software, this is about a theme.  If you want to cleanup wording, issue a PR and make yourself useful, we need read help around here, not a commentator.

> So I asked my bro for any ideas and he came up with something like this

I like his direction (with the three varieties) although at a distance, it looses its distinction and almost mistaken for a bundle of leaves versus an orange (not that it matters, orange leaves are nice looking as well).

**Comment by michaelgregorius** [comment] 2015-08-10 19:16
If you decide to go with something like the three differently colored oranges / orange slices I'd propose to also reflect the three colors in the oscillator sections to differentiate them a bit more. This would also connect the logo with the instrument a bit more.

**Comment by cubician** [comment] 2015-08-10 19:16
I like the one with the three fruits, however, Tres is right about them
looking like leaves from a distance. Make the rind or secondary color
(Whatever it is) much brighter to create more contrast and make it clear
that they're fruit.
I like this a lot better so far.

On Mon, Aug 10, 2015 at 12:55 PM, Tres Finocchiaro <notifications@github.com

**Comment by LocoMatt** [comment] 2015-08-11 19:04
New idea
![triple](https://cloud.githubusercontent.com/assets/6965480/9207189/4c798bfc-406c-11e5-9a78-e2a41b989b1f.PNG)

**Comment by michaelgregorius** [comment] 2015-08-11 19:19
Have you considered coloring the oscillator section according to the colors of the three slices? For example:
* OSC1 in orange
* OSC2 in yellow
* OSC3 in lime?

If you do so you might also color the "OSC1 + OSC2" label with a gradient that goes from orange to yellow and the "OSC2 + OSC3" label with a gradient that goes from yellow to lime. I think something like this might be a good indicator of how things are connected but at the same time a good indicator of how they are separated.

**Comment by tresf** [comment] 2015-08-11 21:08
Nice use of realestate on that latest one @LocoMatt.

**Comment by Wallacoloo** [comment] 2015-08-12 00:18
I like the big logo in the background.

I don't know about individually coloring each oscillator & adding gradients
to the modulations. If you could pull it off without it looking childish or
clashy, it seems like a good idea, but I certainly couldn't pull that off :P

**Comment by cubician** [comment] 2015-08-12 03:07
Forgive my MS Paint, but here's an idea.
Instead of a gradient, have a diagonal cut between colors that goes through
the +.

I also (tried) to recolor things so they all correspond with the
oscillators.

​

**Comment by michaelgregorius** [comment] 2015-08-12 15:40
@cubician I cannot see your MS Paint art. :wink: Have you forgotten to upload it?

**Comment by grejppi** [comment] 2015-08-12 16:50
@cubician, @michaelgregorius: attachmemts are ignored when replying by email.

**Comment by cubician** [comment] 2015-08-12 17:10
Haha. Okay, responding through github. Here's my MS paint art.

![unnamed](https://cloud.githubusercontent.com/assets/8443754/9230954/b1578cb0-40e2-11e5-9402-337b22bf5d25.png)

**Comment by midi-pascal** [comment] 2015-08-12 17:20
:+1: Really nice indeed!

**Comment by mikobuntu** [comment] 2015-08-12 19:42
These are all really good ;) I quite like the 1 above with the Orange, lemon and lime which are transparent in the oscillators section ( maybe raise the transparency, so that they can be seen slightly more easily? ) 
And slightly off topic, but as you guys seem to have your graphical art abilities in order someone would maybe be interested in updating the Carla plugin artwork. I did the originals merely as place holders at the time. ;)

**Comment by Spekular** [comment] 2015-08-12 20:25
Maybe it could be red behind the text and not gray. Or maybe that's too
many colors? :shrug:

**Comment by LocoMatt** [comment] 2015-08-12 20:32
Thanks everyone for ideas but I'll stay with my main idea and current verion. I'll make some adjustments soon.

**Comment by unfa** [comment] 2015-08-16 00:53
Whoa, I really like this design. Also the sliced orange icon is my favourite.

I think the color coding of the oscilators is a nice idea, however it could cause eyesore, maybe the backgrounds should be desaturated more? The cytrus triad icon fits well the color-coded oscilator panels, otherwise I'd prefer the sliced orange design.

![twist](https://cloud.githubusercontent.com/assets/491704/9291462/02ab1fbe-43c2-11e5-8c89-3697bec75f27.png)

**Comment by unfa** [comment] 2015-08-16 00:59
Btw: The sine wave icon isn't really a sine wive. Maybe it should be altered?

![path4140](https://cloud.githubusercontent.com/assets/491704/9291473/cce02fa4-43c2-11e5-9953-a47c9bd13c60.png)

**Comment by unfa** [comment] 2015-08-16 01:00
Also the __?__ icon could be replaced with this: 
![path4152](https://cloud.githubusercontent.com/assets/491704/9291476/fe013e98-43c2-11e5-8a64-83e15a6664b9.png)

**Comment by Wallacoloo** [comment] 2015-08-16 05:09
+1 on the sine wave. I'm neutral on the "?" Button.

**Comment by michaelgregorius** [comment] 2015-08-16 07:57
I agree with @unfa on the "?" icon. To me it looks like a "surprise" button or like the application itself doesn't know what will happen if you press the button.

The problem with the sine wave seems to be that the wave selection buttons currently have a ratio of 1:1. However, to display a sine wave without distortion you need a button with a ratio of 2*pi:2 = pi:1.

Also please notice that the display of the different wave forms is inconsistent. The sine and the square waves are represented as one complete cycle of the wave while the triangle wave for example is represented as half a cycle.

**Comment by musikBear** [comment] 2015-08-16 09:53
(.. and im just pleased with the dampened color aggression of the orange   :angel:

**Comment by grejppi** [comment] 2015-08-16 10:54
@michaelgregorius: The triangle wave is a full cycle, just shifted so it might look like a half cycle.

And everyone: please show some respect and leave the design and mockups to @LocoMatt.

**Comment by LocoMatt** [comment] 2015-08-16 18:38
Fixed sine wave icon, noise wave icon and better fitting of citrus.
Also I liked @unfa idea with user shape so here's version with changed icon 
![synnth](https://cloud.githubusercontent.com/assets/6965480/9294745/b05d625e-4456-11e5-93f2-90491fae98a3.PNG)

**Comment by StakeoutPunch** [comment] 2015-08-16 19:40
I agree with @grejppi. While some of the design ideas are great, it is extremely difficult to incorporate them all and still keep the super clean UI concept. The too many drivers scenario comes to mind.

**Comment by unfa** [comment] 2015-08-16 20:22
I really like this latest version. Juicy! Makes me wanna mess with some oscillators...

BTW: I really like the flat elegant knobs in the plugin window nand the rest of the UI - is that a custom skin or what? Really slick. I've put some effrot into the current knobs in LMMS, but those simple flat circles really look appealing. I'm not into the Ableton Live's minimalism degree in GUI, but I like how it's approached here.

**Comment by LocoMatt** [comment] 2015-08-16 20:31
@unfa Thanks for your approvment :) 
And yes, this skin is custom made by myself. I wanted to finish this and post also as gui proporsal but I'm to lazy :P

**Comment by musikBear** [comment] 2015-08-20 12:15
Me == :japanese_goblin:
Right now the weirdest thought struck me:
*Why are presets-forms small on x-axis and large on y-axis, while our screens are just the opposite*

Inter-es-ting .. (?)

**Comment by tresf** [comment] 2015-08-20 12:42
> Right now the weirdest thought struck me:
Why are presets-forms small on x-axis and large on y-axis, while our screens are just the opposite

I think you're trying to start off-topic dialog here, but I'll bite... 

We've discussed on several occasions to widen our default instrument plugins.  It's on the radar, but there's little priority around it at this point.  It would certainly make sense to tackle during one of the more drastic UI overhauls.

**Comment by tresf** [comment] 2015-08-20 12:43
Back on topic... @LocoMatt can you being a pull request for the graphical enhancements so that we can get this integrated for the future `stable-1.2` release?

If you need any help with the pull request, just ask, we have plenty of people with plenty of experience in that area. :+1: 

-Tres

**Comment by michaelgregorius** [comment] 2015-10-25 21:53
I have tested #2293 against the current master where it looks as follows:
![triple-osc-redesign](https://cloud.githubusercontent.com/assets/9293269/10718107/d537d8d4-7b6a-11e5-9f64-21d27cd81f07.png)

Can this one be merged?

**Comment by Wallacoloo** [comment] 2015-10-26 01:36
I'll be brutally honest here - I really prefer the current Triple Oscillator design:

![tripleosc](https://cloud.githubusercontent.com/assets/1210751/10719312/3b258bf6-7b7e-11e5-95ef-4d033577d84a.png)

When put alongside the AFP, they have a clear design similarity (mainly in the color - blues and grays):

![afp](https://cloud.githubusercontent.com/assets/1210751/10719317/593d683e-7b7e-11e5-8e9e-0e530b95fd76.png)

Where in contrast, all the other LMMS plugins are essentially a free-for-all. They have nothing in common; many of them clash with eachother.

I *much* prefer the more minimalistic design of the current AFP & TripleOsc. Most importantly, the colors contrast really well and they don't distract or get in your way. Coincidentally, they also match with Qt's window borders (blue when focused, gray otherwise). 

IMO, if we're redesigning skins, we should be working towards making our plugins look visually consistent. They currently lack any overall coherent "look and feel". If you look at something like budislav's mockups, one of the major things that make his designs look so good is the consistency. Everybody has differing opinions on what looks good individually, but consistent look-and-feel across all of LMMS is a more objective way by which we can measure the validity of a new design.

Regardless, I don't have a huge stake in this, so I certainly won't hold anyone up if there's a consensus to merge this.

**Comment by musikBear** [comment] 2015-10-26 14:00
>  we should be working towards making our plugins look visually consistent. They currently lack any overall coherent "look and feel". If you look at something like **budislav's mockups**, one of the major things that make his designs look so good is the consistency.

Oh yes oh yes oh :+1: 

Psst .. also.. isent this a little too  close to IL.'s *Sytrus'* logo.. ?

**Comment by tresf** [comment] 2015-10-26 14:45
> IL.'s Sytrus' logo

It's "FL Studio", not IL and no, ImageLine doesn't own a trademark (or service mark) on a slice of orange and our plugin doesn't even remotely resemble theirs.

> Psst

?

> I'll be brutally honest here - I really prefer the current Triple Oscillator design:

I think the new one adds a bit of spark to the interface.  To quote @unfa, "I really like this latest version. Juicy! Makes me wanna mess with some oscillators...". 

> IMO, if we're redesigning skins, we should be working towards making our plugins look visually consistent. They currently lack any overall coherent "look and feel".

It was decided quite a while ago that plugin authors were allowed to skin their plugins as they like, similar to how [it is done for VSTs](https://cloud.githubusercontent.com/assets/6345473/10731734/2a03e738-7bcd-11e5-8cfa-76290da97aed.png).    In regards to @budislav's mock-ups, that is a very long-term goal and when finished, will all-but eradicate the individual identity of our plugins.  So yes, this is something we will aim to achieve, but that identity trade-off is something we haven't yet discussed fully.  If we decide to tackle the plugin consistency prior to that initiative -- we certainly can -- but someone would have to discuss, decide and then spearhead that initiative, which would likely also incorporate better instrument resizing, etc.  I'm a big fan of this, but it shouldn't prevent individual artwork from making it in to the repo IMO.  We need to encourage positive engagement and I feel this plugin is a great step in that direction (and does so tastefully, no pun intended).

> match with Qt's window borders (blue when focused, gray otherwise).

Yeah, we need to address that default MDI window color because it really hinders our theming capabilities.

> consistent look-and-feel across all of LMMS is a more objective way by which we can measure the validity of a new design.

If we decide to start mandating this, we need to decide this now before more work goes into the plugin artwork.  In regards to AFP vs. TripleOsc, that was just a coincidence, if you look through [this thread](http://linux-multimedia-studio-lmms.996328.n3.nabble.com/AudioFileProcessor-WIP-td5729.html), you can see how AFP got to where it is today.  TripleOsc AFAIK was done by Vesa without a tremendous amount of feedback as he was spearheading the 1.0 re-theme initiative.

**Comment by StakeoutPunch** [comment] 2015-10-26 16:41
Objectively speaking, the new TripleOsc UI is more minimalistic by design from a lack of gradients. I think the design is a bit cleaner in general as well. Then again, I am very partial to flat UI design in general (@Umcaruje and I have been working on an all-inclusive flat theme for LMMS). Here is a side by side comparison of the most recent screenshot of 3OSC and AFP:
![image](https://cloud.githubusercontent.com/assets/6579031/10735355/8f5200f4-7bd5-11e5-9ceb-8875c3c7eb57.png)

>but someone would have to discuss, decide and then spearhead that initiative, which would likely also incorporate better instrument resizing, etc.

Moving icons to a sprite sheet should probably also be on the list of etcs. Is there a meta issue open about theme support?

**Comment by tresf** [comment] 2015-10-26 18:05
> Should there [be] a meta issue about theme support?

We have one, sort of... https://github.com/LMMS/lmms/issues/880.

We can certainly make a meta-thread if we can split off specific tasks.  The sprite idea has its pros and cons.  The cons are mostly the C++ work to get the X/Ys mapped out, etc.  The pros are less pixel fidgeting (depending on who you ask).  I think we should eventually focus on the streamlining items that @Wallacoloo mentioned while trying to keep a bit of identity to the interfaces.

**Comment by softrabbit** [comment] 2015-10-28 10:21
Is it just my aging eyes, or is the new proposal harder to read than the old one? The worst spot would be the "AM" button IMO.

**Comment by tresf** [comment] 2015-10-28 12:32
@softrabbit Yes, slightly harder to read. If you are looking at the side-by-side in @StakeoutPunch's screenshots, it is very hard to read due to some blurriness in his screenshot.  [This one](https://cloud.githubusercontent.com/assets/9293269/10718107/d537d8d4-7b6a-11e5-9f64-21d27cd81f07.png) is much better.

**Comment by musikBear** [comment] 2015-10-28 16:31
> Is it just my aging eyes, or is the new proposal harder to read than the old one? The worst spot would be the "AM" button IMO.

I also thought so, but optioned away from posting, because i have babbled on and on about this accessibility-issue so many times, but in all honesty: Should a new design really lower existing accessibility? 
Imo. no, it should not.

**Comment by tresf** [comment] 2015-10-28 16:44
> but in all honesty: Should a new design really lower existing accessibility? Imo. no, it should not.

Let's focus on what CAN be done rather than what CAN'T be done.  i.e. 

> Dear @LocoMatt can you make the PM/AM/MIX/SYNC text slightly larger?

How hard was that?

**Comment by LocoMatt** [comment] 2015-10-29 15:40
I can see that there's a lot of people who know better how it should look. Ofc I can make font bigger and etc. but it's not my obligation. If you wish you can make new design. I don't care that I spent many hours on this. 
If you want to introduce it into LMMS, I can update pull request this weekend. I don't want to discuss about this anymore.

**Comment by tresf** [comment] 2015-10-29 16:46
> I don't want to discuss about this anymore.

This is the exact place for discussion.  You can choose to respond, or you can dismiss the questions.  The incentive is on you, so if you don't care, neither do we, just close it out and move on.

**Comment by IvanMaldonado** [comment] 2015-10-29 19:02
LMMS plugins should also be themeable in my opinion. This way everybody could make the plugins look as they feel.

**Comment by tresf** [comment] 2015-10-29 19:07
@IvanMaldonado they are, you just need to create the skeleton directories in `$HOME/lmms` or `%USERPROFILE%\lmms`

**Comment by StakeoutPunch** [comment] 2015-10-29 23:25
>LMMS plugins should also be themeable in my opinion.

They are. See https://github.com/StakeoutPunch/LMMS_Themes/tree/master/uiX_um_fork/plugins

You do have to dig into the source to see what the file names should be, and then put them in a folder called /plugins in your theme. This is a hacky solution, and I'm sure that the directories used could be improved (IE /plugins/pluginname vs all plugin related theme artwork in /plugins).

**Comment by michaelgregorius** [comment] 2015-10-30 17:11
@LocoMatt I can totally understand that at a certain point you don't want to discuss anymore because obviously with the number of people involved it's not possible to please everyone. However, I would also find it sad if your work was lost. Therefore I'd like to ask whether you can make the source files available in case someone else wants to do some last finishing touches.

On a sidenote: to me it also shows that the fixed size of the plugins is a problem because for some plugins you have to cram a lot of stuff in a small space.

**Comment by tresf** [comment] 2015-10-30 17:17
> Therefore I'd like to ask whether you can make the source files available in case someone else wants to do some last finishing touches.

Thanks for mentioning this.  This is a requirement on all official artwork moving forward.  It should be committed to https://github.com/LMMS/artwork.

> On a sidenote: to me it also shows that the fixed size of the plugins is a problem because for some plugins you have to cram a lot of stuff in a small space.

Agreed.

**Closed** 2016-01-26 23:16 UTC
Labels: enhancement, gui
