### ISSUE TITLE
Preset saving system bug

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#4927] opened 2019-04-02 16:31 UTC
The title really doesn't explain it very well. What i want to make devs notice, is that if you save a preset of an instrument that has one of its knobs linked to a controller in the project you saved it, if you then try to load it in a new project that has no controllers, just clicking on it in the sidebar will make LMMS freeze or crash and close itself.

I think it should be more clever if when you save a preset this way it autoremoves and don't save the information about the connection to a controller.
Or a better way would be to make the preset create a new controller with the same characteristics in the project where you load it and autoconnect the knob to it.

I'm on Windows 10 64-bit and i'm using LMMS 1.2.0 RC8

Here i upload an example, just put it in you presets folder and try to load it from the sidebar
[Glitchy.zip](https://github.com/LMMS/lmms/files/3034989/Glitchy.zip)

Thanks

**Comment by CYBERDEViLNL** [comment] 2019-04-02 16:59
Confirmed. Automation track connections are also stored in the preset, they are unused but don't seem to crash LMMS.

**Comment by noahb01** [comment] 2019-04-11 00:08
I've fixed the crashing issue with pull request #4937.

**Comment by SecondFlight** [comment] 2019-04-24 16:00
Should this be closed via #4939? Or are there still more issues that need addressing?

**Comment by noahb01** [comment] 2019-04-24 16:45
My pr fixes the crash, but perhaps we should keep this issue open because we probably shouldn’t be saving controller connections in the first place, which my pr does nothing to fix.

On the other hand, this issue is directly about the crash, which has been fixed, so I’m in favor of closing it.

**Comment by SecondFlight** [comment] 2019-04-25 14:27
Yeah, I agree. This issue is describing a bug, and leaving it open to serve as an enhancement will likely cause confusion.

@noahb01 Feel free to create a separate enhancement request, since you likely know a lot more about what's going on. I'd agree that either 1) controller connections should not be saved or 2) controllers should be added when the preset is added.

**Closed by SecondFlight** 2019-04-25 14:27 UTC
Labels: bug, core
