### ISSUE TITLE
feat. req. Stretch\Shrink\Split pattern

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#1648] opened 2015-01-17 15:57 UTC
To split pattern - just set a pointer on timeline and split one selected note pattern for two fragments

Stretch\Shrink is not the same it should convert notes in pattern moving them and stretching too or shrinking - it is like resizing picture and split is like crop, this should act like for each pattern part i can set different tempo.
for example if i've played some part slower then needed, then i''l have to move all notes of whole pattern, but if i've played properly, then all i need is set a new tempo for this pattern - that's what shrink\Stretch should do - maybe not so easy to do.

**Comment by tresf** [comment] 2015-01-17 18:28
#746

**Comment by Sti2nd** [comment] 2015-01-18 17:29
Strech/Shrink would add and remove one bar to all notes in a pattern?

**Comment by oeai** [comment] 2015-01-18 18:51
No, this is a one of possibilities, but i thought that this can be done with split
and shrink\stretch should add or remove 1 quant per bar and lower\increase size of note.
this should make tempo of this pattern higher or lower.

For example 5 bars 4\4 with temp 120 i want to stretch for temp 140 while all other paaterns are already written in 140. my pattern will be slower than all others, i need to remove about 20% of empty space and set lower longitude of notes. 
a kind of the way this can be done now is to set something else instead of 4\4 you'll see that pattern will be increased or decreased, but if you got only 1 pattern to change - you can't, because it will be reset to default of whole song.

Simple shrink\resize for few bars in the beginning or end of pattern is also needed i believe, maybe this should be a usual behavior for mouse use and ALT+resize can make it for tempo\notes length a little different way

**Comment by Sti2nd** [comment] 2015-01-18 18:57
> my pattern will be slower than all others,

Well, I don't follow you on your last comment since a one bar instrument pattern is a one bar long pattern not matter what tempo you choose. Maybe you are suggesting shrink/strecth on sample track patterns?

What I thought you were suggesting is a feature where the notes inside the pattern filled up the newly created space, a bit similar to the shortcut Shift + resize selection in Piano Roll.
- If you have one bar long note in the pattern, when you drag the pattern out the note follows
- If you have two half bar long notes in a pattern, when you drag the pattern out they both become half a bar longer.

**Comment by oeai** [comment] 2015-01-18 19:34
no it's not for sampletracks
this is the case when you need to play notes faster then it is or slower and length of notes should be changed as well

**Comment by Sti2nd** [comment] 2015-01-19 14:14
Alt is busy, still not sure what you want. Have you tried resizing in Piano Roll and holding down Ctrl?

**Comment by tresf** [comment] 2015-01-19 14:30
@Sti2nd there are multiple requests in this bug report (which is a problem) but from a stretch/shrink perspective, I believe he's referring to this:

**Normal:**
![image](https://cloud.githubusercontent.com/assets/6345473/5801875/97465e58-9fbd-11e4-85d3-ef169bb39ff0.png)

**Shrink:**
![image](https://cloud.githubusercontent.com/assets/6345473/5801883/a6f6cfb8-9fbd-11e4-8dbd-dece2d22ef22.png)

**Stretch:**
![image](https://cloud.githubusercontent.com/assets/6345473/5801892/b9dd6240-9fbd-11e4-9305-ab1417a9cf67.png)


A picture is worth 1,000 words, so we should really be spending more time on quality bug reports. :)

**Comment by Umcaruje** [comment] 2015-01-19 15:13
That is allready possible in the Piano Roll, just select all notes and hold shift when you resize them :)

**Comment by tresf** [comment] 2015-01-19 15:15
> That is already possible in the Piano Roll, just select all notes and hold shift when you resize them :)

Hot damn.  How long has that been around?

**Comment by Spekular** [comment] 2015-01-19 15:31
I knew about the shift drag functionality, but I assumed this bug report
was about porting that to song editor as well.

**Comment by Umcaruje** [comment] 2015-01-19 15:34
>Hot damn. How long has that been around?

I learned about it acidentally, while I used 1.0, but I believe it was around in 0.4.15. I can check.

**Comment by Umcaruje** [comment] 2015-01-19 16:01
Yup, it existed in 0.4.15 too : 
![0.4.15](http://i.gyazo.com/cb2336a9e4950f27c3cb554dd08a7683.gif)

**Comment by tresf** [comment] 2015-01-19 16:43
Thanks @Umcaruje.  Elite GIF skills there... :)

@oeai is this safe to close? We have a split bug report open and milestoned already and the stretch and shrink appears to be enabled and working well, unless we are wrong in our assumptions. :)

**Comment by Sti2nd** [comment] 2015-01-19 16:52
You could potentially extend the stretch/shrink functionality from Piano Roll so that resizing a pattern in Song Editor will make use of the Shift shortcut and also stretch the notes.

**Comment by tresf** [comment] 2015-01-19 16:54
> You could potentially extend the stretch/shrink functionality from Piano Roll so that resizing a pattern in Song Editor will make use of the Shift shortcut and also stretch the notes.

Yes, this would be nice... Is that what he's saying?

**Comment by Sti2nd** [comment] 2015-01-19 17:37
This is my best guess. It seems like that is what he is saying after reading again

**Comment by oeai** [comment] 2015-01-19 18:10
yes. i think it is thanks =)

**Comment by tresf** [comment] 2015-01-19 18:38
Closing.  "Split" is a duplicate of #746.  The other features are already implemented.

On a side-note, I'm glad these bug reports come in... otherwise I'd never know the feature exists! :)

**Comment by tresf** [comment] 2015-01-19 18:42
Created #1658 for song editor functionality.

**Closed by tresf** 2015-01-19 18:42 UTC
Labels: enhancement
