### ISSUE TITLE
zoom bug

### ISSUE THREAD

**Issue by Z3R0C** [LMMS/lmms#3834] opened 2017-09-28 13:55 UTC
![bildschirmfoto vom 2017-09-28 15-17-00](https://user-images.githubusercontent.com/32363130/30969500-e4c2d830-a462-11e7-93b0-133826e76e48.png)

hi,

in every second project i get this zoom bug. if i save, close and open a project again, it can be there. thats like bingo. i have this problem with all larger projects every time.

![bildschirmfoto vom 2017-09-28 15-29-17](https://user-images.githubusercontent.com/32363130/30970354-3f9489fa-a465-11e7-9ec1-e6b737d6dd4f.png)

2. all VST`s are'nt in his window frames. thats ok for me. so i can move the VST's to other workspaces or  screens.

zeroc

**Comment by zonkmachine** [comment] 2017-09-28 14:09
Thanks! I believe this is a duplicate of issue https://github.com/LMMS/lmms/issues/3721.
Closing.

**Closed by zonkmachine** 2017-09-28 14:09 UTC
