### ISSUE TITLE
Record Track in a separate channel

### ISSUE THREAD

**Issue by DimitriyPS** [LMMS/lmms#5550] opened 2020-06-30 19:59 UTC
### Enhancement 
Necessary to output the "Record Track" to a separate channel. This is necessary for the exclusive control of track frequencies when composing a work.

#### Justification
I am trying to replace FL Studio with LMMS in my work. I immediately ran into the problem that adding a “Record Track” I cannot output it to a separate channel, I cannot filter it separately, I cannot impose effects on it. LMMS is a very interesting program, but this limitation alone does not allow me to switch to its use.

#### Mockup
![000](https://user-images.githubusercontent.com/11189223/86171364-455b0b00-bb25-11ea-8d6e-67c44c6a0251.jpg)

**Comment by DomClark** [comment] 2020-07-01 00:15
Duplicate of #133. This is implemented on `master` and should be available in 1.3 when it is released. See #3866.

**Closed by DomClark** 2020-07-01 00:15 UTC
Labels: enhancement
