### ISSUE TITLE
Audio File Processor should detect loop points in wav files

### ISSUE THREAD

**Issue by SeanTheBermanator** [LMMS/lmms#5634] opened 2020-08-16 16:46 UTC
#### Forcing the user to define the loop points practically a second time can be a time consuming/wasting task. Adding loop point detection will make edits a whole lot easier. It's very hard to replicate a good loop, which leads to noticeable clicks.

**Comment by Spekular** [comment] 2020-08-16 16:52
Marking as a duplicate of #5583 since wav support is mentioned in the comments. Also relevant: #2154

**Closed by Spekular** 2020-08-16 16:52 UTC
Labels: enhancement

**Comment by PhysSong** [comment] 2023-06-25 03:03
Consolidated into https://github.com/LMMS/lmms/issues/6745.
