### ISSUE TITLE
Synth1 preset settings are lost at upgrade from 1.1.3 to 1.2.0-RC5

### ISSUE THREAD

**Issue by GoAm** [LMMS/lmms#4084] opened 2017-12-30 18:47 UTC
I finally did an upgrade from 1.1.3 Stable to 1.2.0-RC5 today.
Loaded an old project of mine and discovered that all used presets in Synth1 was replaced by Internal "Synth1 brastring".

Don't know if this happens with other VST's but I mainly use the Synth1 and this is why I discovered it.

*EDIT*
The presets are not saved if I pick them out again and save the project in 1.2.0-RC5

System setup:
Win 10 prof.
LMMS 1.2.0-RC5 64-bit

**Comment by DeRobyJ** [comment] 2018-01-03 22:22
> The presets are not saved if I pick them out again and save the project in 1.2.0-RC5
I can't reproduce this part: I loaded Synth1, I chose a preset from an external zip bank, saved the project, closed lmms, re-opened and the project loaded the preset correctly

Win 7 Sp1
LMMS 1.2.0-RC5 64-bit

**Comment by DomClark** [comment] 2018-08-13 19:56
@PhysSong Might this be fixed by #4401?

**Comment by PhysSong** [comment] 2018-08-14 02:37
> Might this be fixed by #4401?

Too little information here. However, we can know if so or not once RC7 is released.

**Comment by DomClark** [comment] 2018-12-09 19:57
@GoAm Can you try 1.2.0-rc7? The issue may have been fixed.

**Comment by GoAm** [comment] 2018-12-11 20:04
The presets were loaded quite fine in Synth1 in rc7. 👍

**Comment by DomClark** [comment] 2018-12-11 20:14
Good to hear! Closing as fixed.

**Closed by DomClark** 2018-12-11 20:14 UTC
Labels: vst
