### ISSUE TITLE
Piano roll: playing a note and clicking outside

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#1866] opened 2015-03-12 22:47 UTC
Steps to reproduce:
1. Add an instrument pattern on the song editor
2. Open the pattern on the piano roll
3. Click on the piano keyboard at the left side of the piano roll
4. Press and hold a key on the PC's keyboard to play a note
5. While still holding the key, click anywhere on an editor other than piano roll
6. Release the held key on the PC's keyboard

The played note will not stop.

The same happens if one clicks on the are containing the buttons below the title bar on the piano roll instead of clicking on other editor.

Simply clicking on the stop button still does not stop the note. However, the note can be stopped by: 
1. Pressing and releasing the same key on the PC's keyboard
2. Clicking on the corresponding key on the piano keyboard of the piano roll
3. Playing the song, pattern, or BB then stopping

The best place to handle this is maybe `QWidget::focusOutEvent()`.

**Comment by tresf** [comment] 2015-03-12 23:42
Near duplicate of #1755.

**Comment by musikBear** [comment] 2015-03-13 11:01
not win32 1.1.3

**Comment by Lukas-W** [comment] 2015-06-15 08:24
Fixed via #2027 aaed66ecebd7053b9784e6523dd02b61ecf44bd2

**Closed by Lukas-W** 2015-06-15 08:24 UTC
Labels: bug
