### ISSUE TITLE
Broken Ticks on knobs (windows RC)

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#3001] opened 2016-08-26 01:42 UTC
I noticed while using the Triple OSC and Monstro that the parameter knobs had no tick marks on startup 
![artwork](https://cloud.githubusercontent.com/assets/20342439/17991390/40c71cfe-6b0c-11e6-87d1-1da4b23c1c18.png)
![artwork](https://cloud.githubusercontent.com/assets/20342439/17991392/4faa3e36-6b0c-11e6-8e48-c8efcd360a9d.png)
I've only played around with the knobs a little bit, but this is the result:
![triple osc broke](https://cloud.githubusercontent.com/assets/20342439/17991425/9f0c85ec-6b0c-11e6-8c16-ea8da6ec6c54.PNG)
It may seem superfluous, but i find those tick marks to be really handy, and they don't show any tick marks when not adjusted. Note: this is the windows RC, not the bleeding edge master.

**Comment by tresf** [comment] 2016-08-26 02:17
Duplicate of https://github.com/LMMS/lmms/issues/1187.

**Closed by tresf** 2016-08-26 02:17 UTC
