### ISSUE TITLE
BB editor needs option to unlink clips

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4616] opened 2018-09-25 07:06 UTC
When I use bb editor, I have to create a separate track in each variation I make in a clip. and that is very annoying, and more when you have to make complex percussions full of variations, that complicates the work and makes the environment look charged and messy.

![desvincular](https://user-images.githubusercontent.com/26127693/45997560-09e8fe00-c06e-11e8-85aa-69d8eaa0c28b.png)

In this picture you only see two tracks and two clips, because I'm just starting a project. but when it comes to making batteries and complex percussions the song editor is full of tracks and clips making the project is very loaded and lms in some cases hang.
I suggest that in the bb editor, implement the option of: '' unlink clip '', and in this way in the bb editor can create different rhythms and independent variations in a single track of the bb editor, and not load the entire environment with clues and clips. regards

**Comment by musikBear** [comment] 2018-09-25 14:34
No, you are stuck in only one way of using BB. Read the wiki, where philosophies in BB-tracks are split in 3 different usages:
https://lmms.io/wiki/index.php?title=Composing_Bass_Lines_and_Drum_Sequences#Philosophies_of_pattern_design

**Comment by Gabrielxd195** [comment] 2018-09-25 22:29
I understand that is the philosophy of the bb editor, but to be this way, when creating complex percussions with many variations, the editor of bb editor clips songs is filled, and this loads the whole environment leaving it messy and heavy. lmms need to improve that, or implement another feature that allows you to do the aforementioned.

**Comment by Gabrielxd195** [comment] 2018-09-25 22:29
> No, you are stuck in only one way of using BB. Read the wiki, where philosophies in BB-tracks are split in 3 different usages:
> https://lmms.io/wiki/index.php?title=Composing_Bass_Lines_and_Drum_Sequences#Philosophies_of_pattern_design

I understand that is the philosophy of the bb editor, but to be this way, when creating complex percussions with many variations, the editor of bb editor clips songs is filled, and this loads the whole environment leaving it messy and heavy. lmms need to improve that, or implement another feature that allows you to do the aforementioned.

**Comment by tresf** [comment] 2018-09-29 16:53
Exact duplicate of #454.  Please search first.

**Closed by tresf** 2018-09-29 16:53 UTC
