### ISSUE TITLE
1.3 Alpha Lost conection usb keyboard Alesis Q49

### ISSUE THREAD

**Issue by A350** [LMMS/lmms#5961] opened 2021-03-22 13:33 UTC
In alpha version 1.3 , the conection usb keyboard it gets lost soon after

**Comment by qnebra** [comment] 2021-03-22 17:15
Any more details about? Like system, affected versions (I see here alpha). And you are sure this isn't caused by system getting into sleep mode?

**Comment by A350** [comment] 2021-03-22 17:21
Not, no sleep mode.. happens after a few minutes My OS is Debian 10 Buster. My keyboard is conected usb mode

**Comment by qnebra** [comment] 2021-03-22 17:40
Also, how soon after? Minute, five minutes? Laptop, PC. Just wanted to clear out any OS and hardware related things before going into "this is lmms bug".

**Comment by A350** [comment] 2021-03-22 17:43
5 minutes aprox. after . is a PC computer

**Comment by IanCaio** [comment] 2021-03-25 22:35
Could you test with another DAW or software? This is sounding like an issue on the system or hardware end instead of LMMS.

**Comment by A350** [comment] 2021-03-25 22:37
uhm.. in LMMS 1.2 no have this problem. Only in 1.3 alpha

**Comment by IanCaio** [comment] 2021-03-26 09:20
> uhm.. in LMMS 1.2 no have this problem. Only in 1.3 alpha

I see, that's weird. The hard thing about reproducing this bug is that we'd need someone with the same keyboard to try it, or at least attempt to reproduce it with another USB keyboard on the same system. Maybe one of the other devs or users have one and could try testing it. Would be even better if they could test it under Debian 10, even if under a VM (though the VM environment could behave a little different when it comes to how hardware is handled).

Unfortunately I don't have any USB keyboard, but let's wait to see if somebody who does can test. What I think is weird is that I don't think any part of the LMMS codebase actually tries to connect/disconnect to the keyboard, all keyboard events are handled through Qt afaik. So even though this happens only on alpha, I still think there's something else going on (that for some reason doesn't affect the stable install).

**Comment by qnebra** [comment] 2021-03-26 19:36
Weird thing baffling me about this issue is that there isn't much changes in terms of "midi device handling" between 1.2 and 1.3 from what I know. 

Also, you had drivers installed? Just asking.

**Comment by A350** [comment] 2021-03-26 19:42
I have never had problems in different versions of LMMS, it is strange. But in 1.3 I have to disconnect the usb and reconnect it to make it work again, but the connection is lost after a few minutes. I run the appimage in BunsenLabs, based on Linux Buster.

About drivers, it's plug and play

**Comment by A350** [comment] 2021-04-02 21:55
I think I have managed to "fix the problem" I have disabled the option "enable compact track buttons" in config panel.

You want that option complicates the task for me, I don't know.

[https://i.imgur.com/athrAzn.png](url)

**Comment by A350** [comment] 2021-04-02 22:09
I think I have managed to "fix the problem" I have activated the option "enable one instrument-track-windows-mode" in config panel.

is possible ?

**Comment by qnebra** [comment] 2021-04-02 22:36
If your controller wasn't disconnecting then it is fix, somehow. Just check it.

**Comment by IanCaio** [comment] 2021-04-02 22:46
> I think I have managed to "fix the problem" I have activated the option "enable one instrument-track-windows-mode" in config panel.
> 
> is possible ?

I'm not sure why it fixes the problem, IIRR that option is just to limit the amount of instrument widgets to 1. Are you sure that was the change that fixed it? If so, I'd use it for now. Also, that at least gives us some direction on where to look because that will be a hard bug to track, it being hard to reproduce and all.

**Comment by A350** [comment] 2021-04-02 22:53
yeah well .. i have made some changes and correct i dont think that was a solution.

I think it has been solved, in MIDI settings.

Automatically assign MIDI controller to select track

NONE


https://i.imgur.com/CITJNLe.png

**Comment by qnebra** [comment] 2021-04-02 23:02
But it set to "none" by default. Propably I doesn't remember correctly, but it wasn't reset to default state after controller is disconnected and lmms restarted?

**Comment by A350** [comment] 2021-04-02 23:05
I don't know, maybe I had set my keyboard, but not assigning it as default, it has been solved.

I feel my English, I am Spanish

**Comment by qnebra** [comment] 2021-04-02 23:08
It isn't. Check if keyboard keeps disconnecting. Then propably it is some workaround for issue.

**Comment by IanCaio** [comment] 2021-04-02 23:15
@A350 Is it possible that you had the wrong MIDI controller selected in the "Automatically assign MIDI controller to select track" dialog and maybe it was connecting it instead of your MIDI keyboard?

Changing it to "None" fixed it then? If so, I think we can close this issue.

**Comment by A350** [comment] 2021-04-02 23:19
OK, closed. For me it works best in unassigned default MIDI controller to selected track, because it creates some kind of conflict.

**Closed** 2021-04-05 10:51 UTC
Labels: bug
