### ISSUE TITLE
Loading Linux VST .so file into LMMS

### ISSUE THREAD

**Issue by qubodup** [LMMS/lmms#2498] opened 2015-12-30 22:30 UTC
Hello, I'd like to try Dexed and Tunefish in LMMS on Linux, since there are Linux binaries of these VSTs.

On Arch Linux, I install Dexed via AUR which only installs /usr/lib/vst/Dexed.so

How do I make LMMS use this VST?

I set Edit > Settings > Paths > VST-Plugin Directory to /usr/lib/vst/ and restarted to no avail.

I navigated to /usr/lib/vst/ in the Root directory file browser and double-clicked and dragged the .so file without effect.

I do have wine as suggested by https://lmms.io/wiki/index.php?title=Working_with_VSTs#VSTs_.26_Linux but I have the impression that article refers to Windows VSTs.

Is there a way to use Linux native VSTs in LMMS? "A Host For Native Linux VST Plugins ?" ( http://www.linuxjournal.com/node/1000192 ) indicates no but on the other hand it's more than 8 years old now.

**Comment by grejppi** [comment] 2015-12-30 23:12
Duplicate of #416.

**Closed by grejppi** 2015-12-30 23:12 UTC
