### ISSUE TITLE
Building with Xcode 8.0

### ISSUE THREAD

**Issue by kevinchau321** [LMMS/lmms#3051] opened 2016-09-24 19:14 UTC
Just updated my Xcode, which seems to introduce an error:

```
...
[100%] Built target ZynAddSubFxCore
make[2]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework', needed by `plugins/RemoteZynAddSubFx'.  Stop.
make[1]: *** [plugins/zynaddsubfx/CMakeFiles/RemoteZynAddSubFx.dir/all] Error 2
make: *** [all] Error 2
```

I see in the SDK folder: MacOSX.sdk folder and a link called MacOSX10.12.sdk to said folder
I tried making another link called MacOSX10.11.sdk (which is what the compiler is asking for), but run into this error:

```
[100%] Linking CXX executable ../RemoteZynAddSubFx
ld: can't map file, errno=22 file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugins/RemoteZynAddSubFx] Error 1
make[1]: *** [plugins/zynaddsubfx/CMakeFiles/RemoteZynAddSubFx.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by kevinchau321** [comment] 2016-09-24 19:26
seems to build after rerunning cmake. This is still a bug though right?

**Comment by tresf** [comment] 2016-09-25 14:11
@kevinchau321 can you clarify the steps that were performed to produce these results?

 * If a fresh build does not produce these results, then it is a residual problem with your build environment.
 * If a fresh build does reproduce these results, then it may be a bug win our code.

The error you have suggests you are building against mixed environments.  This may occur if you upgrade XCode without cleaning out your build environment; expected  when upgrading to MacOS 10.12 Sierra (released Sept 20th 2016 -- 5 days ago from this posting).

Furthermore, dependencies from Homebrew or MacPorts may need to be reinstalled.  Being a timely process, this won't occur overnight for most developers.  In the mean time, if you can help determine if this is a really a bug with our codebase, please update the bug report with that informaiton.

**Comment by eek** [comment] 2016-09-30 09:54
I have the same issue:

`luarocks install cutorch`

generates `Error: Build error: Failed building.` because of

`nvcc fatal   : The version ('80000') of the host compiler ('Apple clang') is not supported`

I'm on MacOS Sierra (10.12) with XCode 8.0 and have already ran `xcode-select --install`

Any ideas on fixes?

**Comment by tresf** [comment] 2016-09-30 11:47
> Any ideas on fixes?

You are welcome to work together here, but FYI, this is an LMMS bug tracker.

**Comment by taupter** [comment] 2016-10-01 04:19
There is currently an incompatibility between XCode 8 and Qt, as can be seen [here](https://bugreports.qt.io/browse/QTBUG-55649).
For the moment, untill Qt updates this is a fix:

Step 1:
Open the file:
`<Qt installation folder>/5.7/clang_64/mkspecs/features/mac/default_pre.prf`

Step 2:
Replace:
`isEmpty($$list($$system("/usr/bin/xcrun -find xcrun 2>/dev/null")))`
With:
`isEmpty($$list($$system("/usr/bin/xcrun -find xcodebuild 2>/dev/null")))`

**Comment by tresf** [comment] 2016-11-22 14:08
Closing as this is an upstream bug.  @taupter please feel free to comment here if the upstream bug sees resolution.

**Closed by tresf** 2016-11-22 14:08 UTC
Labels: not our bug

**Comment by taupter** [comment] 2016-11-23 02:19
I'm having trouble compiling LADSPA calf. It seems to be related to a stricter compiler.

[ 69%] Building CXX object plugins/LadspaEffect/calf/CMakeFiles/calf.dir/src/modules_eq.cpp.o
clang: warning: optimization flag '-finline-functions' is not supported
In file included from /Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:23:
In file included from /Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/giface.h:25:
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/primitives.h:377:5: warning: control may reach end of non-void function [-Wreturn-type]
    }
    ^
In file included from /Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:24:
In file included from /Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/modules_eq.h:30:
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/metadata.h:54:10: warning: 'calf_plugins::filter_metadata::is_cv' hides overloaded virtual function
      [-Woverloaded-virtual]
    bool is_cv(int param_no) { return param_no != par_mode && param_no != par_inertia; }
         ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/giface.h:608:10: note: hidden overloaded virtual function
      'calf_plugins::plugin_metadata<calf_plugins::filter_metadata>::is_cv' declared here: different qualifiers (const vs none)
    bool is_cv(int param_no) const { return true; }
         ^
In file included from /Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:24:
In file included from /Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/modules_eq.h:30:
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/metadata.h:64:10: warning: 'calf_plugins::filterclavier_metadata::is_cv' hides overloaded virtual function
      [-Woverloaded-virtual]
    bool is_cv(int param_no) { return param_no != par_mode && param_no != par_inertia; }
         ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/giface.h:608:10: note: hidden overloaded virtual function
      'calf_plugins::plugin_metadata<calf_plugins::filterclavier_metadata>::is_cv' declared here: different qualifiers (const vs none)
    bool is_cv(int param_no) const { return true; }
         ^
In file included from /Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:24:
In file included from /Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/modules_eq.h:30:
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/metadata.h:502:26: warning: 'calf_plugins::organ_metadata::get_commands' hides overloaded virtual function
      [-Woverloaded-virtual]
    plugin_command_info *get_commands();
                         ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/giface.h:605:26: note: hidden overloaded virtual function
      'calf_plugins::plugin_metadata<calf_plugins::organ_metadata>::get_commands' declared here: different qualifiers (const vs none)
    plugin_command_info *get_commands() const { return NULL; }
                         ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:340:16: error: explicit instantiation of 'calf_plugins::equalizerNband_audio_module' must occur in
      namespace 'calf_plugins'
template class equalizerNband_audio_module<equalizer5band_metadata, false>;
               ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/modules_eq.h:37:7: note: explicit instantiation refers here
class equalizerNband_audio_module: public audio_module<BaseClass>, public frequency_response_line_graph {
      ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:137:10: warning: array index 3735928559 is past the end of the array (which contains 29 elements)
      [-Warray-bounds]
    if (*params[AM::param_lp_active] > 0.f)
         ^      ~~~~~~~~~~~~~~~~~~~
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:340:16: note: in instantiation of member function
      'calf_plugins::equalizerNband_audio_module<calf_plugins::equalizer5band_metadata, false>::process_hplp' requested here
template class equalizerNband_audio_module<equalizer5band_metadata, false>;
               ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/giface.h:452:5: note: array 'params' declared here
    float *params[Metadata::param_count];
    ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:155:10: warning: array index 3735928560 is past the end of the array (which contains 29 elements)
      [-Warray-bounds]
    if (*params[AM::param_hp_active] > 0.f)
         ^      ~~~~~~~~~~~~~~~~~~~
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/giface.h:452:5: note: array 'params' declared here
    float *params[Metadata::param_count];
    ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:86:25: warning: array index 3735928563 is past the end of the array (which contains 29 elements)
      [-Warray-bounds]
        float hpfreq = *params[AM::param_hp_freq], lpfreq = *params[AM::param_lp_freq];
                        ^      ~~~~~~~~~~~~~~~~~
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:340:16: note: in instantiation of member function
      'calf_plugins::equalizerNband_audio_module<calf_plugins::equalizer5band_metadata, false>::params_changed' requested here
template class equalizerNband_audio_module<equalizer5band_metadata, false>;
               ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/giface.h:452:5: note: array 'params' declared here
    float *params[Metadata::param_count];
    ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:86:62: warning: array index 3735928564 is past the end of the array (which contains 29 elements)
      [-Warray-bounds]
        float hpfreq = *params[AM::param_hp_freq], lpfreq = *params[AM::param_lp_freq];
                                                             ^      ~~~~~~~~~~~~~~~~~
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/giface.h:452:5: note: array 'params' declared here
    float *params[Metadata::param_count];
    ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:341:16: error: explicit instantiation of 'calf_plugins::equalizerNband_audio_module' must occur in
      namespace 'calf_plugins'
template class equalizerNband_audio_module<equalizer8band_metadata, true>;
               ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/modules_eq.h:37:7: note: explicit instantiation refers here
class equalizerNband_audio_module: public audio_module<BaseClass>, public frequency_response_line_graph {
      ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:342:16: error: explicit instantiation of 'calf_plugins::equalizerNband_audio_module' must occur in
      namespace 'calf_plugins'
template class equalizerNband_audio_module<equalizer12band_metadata, true>;
               ^
/Users/taupter/Projects/LMMS/lmms/plugins/LadspaEffect/calf/src/calf/modules_eq.h:37:7: note: explicit instantiation refers here
class equalizerNband_audio_module: public audio_module<BaseClass>, public frequency_response_line_graph {
      ^
8 warnings and 3 errors generated.
make[2]: *** [plugins/LadspaEffect/calf/CMakeFiles/calf.dir/src/modules_eq.cpp.o] Error 1
make[1]: *** [plugins/LadspaEffect/calf/CMakeFiles/calf.dir/all] Error 2
make: *** [all] Error 2

**Comment by tresf** [comment] 2016-11-23 02:38
@taupter please wrap your code tags in \`\`\`.  I've done this for you as courtesy.

The only error I see is this one, it may help your investigation:

* `calf/src/modules_eq.cpp:340:16:` error: explicit instantiation of `calf_plugins::equalizerNband_audio_module` must occur in namespace `calf_plugins` template class `equalizerNband_audio_module<equalizer5band_metadata, false>;`

**Comment by tresf** [comment] 2016-11-23 03:26
@taupter here's some further write-up on this issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60786 also [here](http://docwiki.embarcadero.com/RADStudio/Berlin/en/Explicit_instantiation_of_'namespace::templated_class'_must_occur_in_namespace_'namespace'_(C%2B%2B)).

What I don't entirely understand is how upstream [`calf-studio-gear/calf`](https://github.com/calf-studio-gear/calf/blob/master/src/modules_filter.cpp) is dealing with this problem as the code in question doesn't seem to have changed all that much.
