### ISSUE TITLE
No sound from VST plugins; RemoteVstPlugin->bufferSize() returns 0

### ISSUE THREAD

**Issue by grejppi** [LMMS/lmms#381] opened 2014-02-24 22:43 UTC
This happens on Linux (64-bit and 32-bit). Windows is not affected.

Some VST plugins do not output any sound, but otherwise seem to run properly. This might sound like a crazy coincidence (no idea if it is) but they are always plugins that **do not have their own editor GUI**. Plugins with a GUI work just fine.

Examples:
- [All mda effects](http://mda.smartelectronix.com/)
- [All mda synths](http://mda.smartelectronix.com/synths.htm) of which only Piano and ePiano work properly. Piano and ePiano are also the only mda plugins with a GUI.

I can't even find anything in the code that would set the buffer size...

**Comment by gilles504** [comment] 2015-08-30 14:23
not sure if it's the same issue... but I found this thread while experiencing the same problem. VST plugin without sound. It was solved with the "audio mode HQ" parameter.

**Comment by DomClark** [comment] 2018-11-17 21:01
@grejppi Do you still experience this issue? I can't reproduce it (LMMS 1.2.0-rc7, Ubuntu 14.04, Wine 3.0.1).

**Comment by grejppi** [comment] 2018-11-18 15:37
@DomClark no, I can't reproduce it either (LMMS 1.2.0-rc7, Ubuntu 16.04, Wine 1.7.44, 64-bit)

**Comment by DomClark** [comment] 2018-11-18 17:03
In that case I'll close this issue for now. We can reopen it if it crops up again.

**Closed by DomClark** 2018-11-18 17:03 UTC
Labels: bug, core, vst
