### ISSUE TITLE
LMMS crashes on launch "SIGSEGV".  (Artix Linux)

### ISSUE THREAD

**Issue by Fl0wdnb** [LMMS/lmms#6588] opened 2022-12-18 02:38 UTC
### Bug Summary
LMMS (regardless whether the aur git, archlinux, appimage or github source) seems to be segmant faulting on Artix Linux (archlinux support package **must** be enabled to install program). I am running Artix Linux with MATE in case GTK vs. Qt applies to this topic.
#### Steps to reproduce
Terminal output from running the command "lmms" (without root).
#### Expected behavior
LMMS is supposed to launch and run properly
#### Actual behavior
LMMS has decided to segfault for some unknown reason

#### Affected LMMS versions
Current (Github/AUR/Archlinux stable + testing versions as of 12/17/2022). Installed version: LMMS 1.3.0-alpha.1.237+g17aa7dbef, however the issue is still present in the current stable version as well)

#### GDB Logs
<details>
(gdb) thread apply all backtrace

Thread 23 (Thread 0x7fffdcf996c0 (LWP 27110) "AudioEngine::fi"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff62e053c in QtLinuxFutex::_q_futex(int*, int, int, unsigned long long, int*, int) (val3=0, addr2=0x0, val2=0, val=<optimized out>, op=0, addr=<optimized out>, addr=<optimized out>, op=<optimized out>, val=<optimized out>, val2=<optimized out>, addr2=<optimized out>, val3=<optimized out>) at thread/qfutex_p.h:114
#2  QtLinuxFutex::futexWait<QBasicAtomicInteger<unsigned int> >(QBasicAtomicInteger<unsigned int>&, QBasicAtomicInteger<unsigned int>::Type) (expectedValue=<optimized out>, futex=<optimized out>) at thread/qfutex_p.h:133
#3  futexSemaphoreTryAcquire_loop<false>(QBasicAtomicInteger<unsigned long long>&, unsigned long long, unsigned long long, int) (timeout=-1, nn=8589934593, curValue=<optimized out>, u=...) at thread/qsemaphore.cpp:219
#4  futexSemaphoreTryAcquire<false>(QBasicAtomicInteger<unsigned long long>&, int, int) (timeout=-1, n=<optimized out>, u=...) at thread/qsemaphore.cpp:262
#5  QSemaphore::acquire(int) (this=0x5555565c9798, n=<optimized out>) at thread/qsemaphore.cpp:326
#6  0x00005555556c3e94 in lmms::AudioEngine::fifoWriter::write(std::array<float, 2ul>*) ()
#7  0x00005555556c4e71 in lmms::AudioEngine::fifoWriter::run() ()
#8  0x00007ffff62e42da in QThreadPrivate::start(void*) (arg=0x555556a0b4d0) at thread/qthread_unix.cpp:330
#9  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#10 0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 22 (Thread 0x7fffdd9fe6c0 (LWP 27109) "lmms::MidiAlsaS"):
#0  0x00007ffff5d140bf in __GI___poll (fds=0x7fff840029e0, nfds=2, timeout=250) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00005555557b3974 in lmms::MidiAlsaSeq::run() ()
#2  0x00007ffff62e42da in QThreadPrivate::start(void*) (arg=0x555556989a40) at thread/qthread_unix.cpp:330
#3  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#4  0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
--Type <RET> for more, q to quit, c to continue without paging--

Thread 21 (Thread 0x7fffde1ff6c0 (LWP 27107) "SDLAudioC3"):
#0  0x00007ffff5d141b6 in __ppoll (fds=0x555556a53e50, nfds=3, timeout=<optimized out>, sigmask=sigmask@entry=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:42
#1  0x00007ffff7f0b4f3 in ppoll (__ss=0x0, __timeout=<optimized out>, __nfds=<optimized out>, __fds=<optimized out>) at /usr/include/bits/poll2.h:64
#2  pa_mainloop_poll (m=m@entry=0x555556a4eaf0) at ../pulseaudio/src/pulse/mainloop.c:871
#3  0x00007ffff7f1542c in pa_mainloop_iterate (m=0x555556a4eaf0, block=<optimized out>, retval=0x0) at ../pulseaudio/src/pulse/mainloop.c:945
#4  0x00007ffff763737f in  () at /usr/lib/libSDL2-2.0.so.0
#5  0x00007ffff7573dd8 in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007ffff767d48b in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#8  0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 20 (Thread 0x7fffeaffd6c0 (LWP 27100) "SDLAudioP2"):
#0  0x00007ffff5d141b6 in __ppoll (fds=0x555556a42600, nfds=3, timeout=<optimized out>, sigmask=sigmask@entry=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:42
#1  0x00007ffff7f0b4f3 in ppoll (__ss=0x0, __timeout=<optimized out>, __nfds=<optimized out>, __fds=<optimized out>) at /usr/include/bits/poll2.h:64
#2  pa_mainloop_poll (m=m@entry=0x555556a40a60) at ../pulseaudio/src/pulse/mainloop.c:871
#3  0x00007ffff7f1542c in pa_mainloop_iterate (m=0x555556a40a60, block=<optimized out>, retval=0x0) at ../pulseaudio/src/pulse/mainloop.c:945
#4  0x00007ffff76371a9 in  () at /usr/lib/libSDL2-2.0.so.0
#5  0x00007ffff757341d in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007ffff767d48b in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#8  0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

--Type <RET> for more, q to quit, c to continue without paging--
Thread 19 (Thread 0x7fffe81066c0 (LWP 27099) "PulseHotplug"):
#0  0x00007ffff5d141b6 in __ppoll (fds=0x555556a3a270, nfds=3, timeout=<optimized out>, sigmask=sigmask@entry=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:42
#1  0x00007ffff7f0b4f3 in ppoll (__ss=0x0, __timeout=<optimized out>, __nfds=<optimized out>, __fds=<optimized out>) at /usr/include/bits/poll2.h:64
#2  pa_mainloop_poll (m=m@entry=0x55555698cac0) at ../pulseaudio/src/pulse/mainloop.c:871
#3  0x00007ffff7f1542c in pa_mainloop_iterate (m=m@entry=0x55555698cac0, block=block@entry=1, retval=retval@entry=0x0) at ../pulseaudio/src/pulse/mainloop.c:945
#4  0x00007ffff7f154e1 in pa_mainloop_run (m=0x55555698cac0, retval=0x0) at ../pulseaudio/src/pulse/mainloop.c:963
#5  0x00007ffff7637ff3 in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007ffff767d48b in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#8  0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 18 (Thread 0x7fffebfff6c0 (LWP 27098) "lmms::AudioEngi"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555674d054) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555674d054, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff5c9c51f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555674d054, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff5c9ecd0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555674d000, cond=0x55555674d028) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555674d028, mutex=0x55555674d000) at pthread_cond_wait.c:618
#5  0x00007ffff62eb764 in QWaitConditionPrivate::wait(QDeadlineTimer) (deadline=..., this=0x55555674d000) at thread/qwaitcondition_unix.cpp:146
#6  QWaitCondition::wait(QMutex*, QDeadlineTimer) (this=<optimized out>, mutex=0x7fffebffed40, deadline=...) at thread/qwaitcondition_unix.cpp:225
#7  0x00005555556c7e94 in lmms::AudioEngineWorkerThread::run() ()
#8  0x00007ffff62e42da in QThreadPrivate::start(void*) (arg=0x7fffe4008100) at thread/qthread_unix.cpp:330
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#10 0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 17 (Thread 0x7fffdffff6c0 (LWP 27097) "lmms::AudioEngi"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555674d054) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555674d054, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff5c9c51f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555674d054, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff5c9ecd0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555674d000, cond=0x55555674d028) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555674d028, mutex=0x55555674d000) at pthread_cond_wait.c:618
#5  0x00007ffff62eb764 in QWaitConditionPrivate::wait(QDeadlineTimer) (deadline=..., this=0x55555674d000) at thread/qwaitcondition_unix.cpp:146
#6  QWaitCondition::wait(QMutex*, QDeadlineTimer) (this=<optimized out>, mutex=0x7fffdfffed40, deadline=...) at thread/qwaitcondition_unix.cpp:225
#7  0x00005555556c7e94 in lmms::AudioEngineWorkerThread::run() ()
#8  0x00007ffff62e42da in QThreadPrivate::start(void*) (arg=0x7fffe4006540) at thread/qthread_unix.cpp:330
#9  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#10 0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 16 (Thread 0x7fffdf7fe6c0 (LWP 27096) "lmms::AudioEngi"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555674d054) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555674d054, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff5c9c51f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555674d054, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@ent--Type <RET> for more, q to quit, c to continue without paging--
ry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff5c9ecd0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555674d000, cond=0x55555674d028) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555674d028, mutex=0x55555674d000) at pthread_cond_wait.c:618
#5  0x00007ffff62eb764 in QWaitConditionPrivate::wait(QDeadlineTimer) (deadline=..., this=0x55555674d000) at thread/qwaitcondition_unix.cpp:146
#6  QWaitCondition::wait(QMutex*, QDeadlineTimer) (this=<optimized out>, mutex=0x7fffdf7fdd40, deadline=...) at thread/qwaitcondition_unix.cpp:225
#7  0x00005555556c7e94 in lmms::AudioEngineWorkerThread::run() ()
#8  0x00007ffff62e42da in QThreadPrivate::start(void*) (arg=0x5555566b9810) at thread/qthread_unix.cpp:330
#9  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#10 0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 11 (Thread 0x7fffeb7fe6c0 (LWP 27091) "lmms:disk$0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5555566b7728) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x5555566b7728, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff5c9c51f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x5555566b7728, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff5c9ecd0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5555566b76d8, cond=0x5555566b7700) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x5555566b7700, mutex=0x5555566b76d8) at pthread_cond_wait.c:618
#5  0x00007fffe8d0799e in cnd_wait () at ../mesa-22.2.3/src/c11/impl/threads_posix.c:135
#6  0x00007fffe8cbaf8c in util_queue_thread_func () at ../mesa-22.2.3/src/util/u_queue.c:287
#7  0x00007fffe8d078cc in impl_thrd_routine () at ../mesa-22.2.3/src/c11/impl/threads_posix.c:67
#8  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
--Type <RET> for more, q to quit, c to continue without paging--

Thread 3 (Thread 0x7ffff1b166c0 (LWP 27082) "QXcbEventQueue"):
#0  0x00007ffff5d140bf in __GI___poll (fds=fds@entry=0x7ffff1b15c48, nfds=nfds@entry=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff596226b in poll (__timeout=-1, __nfds=1, __fds=0x7ffff1b15c48) at /usr/include/bits/poll2.h:39
#2  _xcb_conn_wait (c=0x55555620c3a0, vector=0x0, count=0x0, cond=<optimized out>) at /usr/src/debug/libxcb/libxcb-1.15/src/xcb_conn.c:508
#3  0x00007ffff5963d1d in _xcb_conn_wait (count=0x0, vector=0x0, cond=0x55555620c3e0, c=0x55555620c3a0) at /usr/src/debug/libxcb/libxcb-1.15/src/xcb_conn.c:474
#4  xcb_wait_for_event (c=0x55555620c3a0) at /usr/src/debug/libxcb/libxcb-1.15/src/xcb_in.c:703
#5  0x00007ffff252d092 in QXcbEventQueue::run() (this=0x5555562094d0) at /usr/src/debug/qt5-base/qtbase/src/plugins/platforms/xcb/qxcbeventqueue.cpp:228
#6  0x00007ffff62e42da in QThreadPrivate::start(void*) (arg=0x5555562094d0) at thread/qthread_unix.cpp:330
#7  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#8  0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7ffff23176c0 (LWP 27081) "QDBusConnection"):
#0  0x00007ffff5d140bf in __GI___poll (fds=0x7fffec0053e0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff556d1ff in g_main_context_poll (priority=<optimized out>, n_fds=3, fds=0x7fffec0053e0, timeout=<optimized out>, context=0x7fffec001cf0) at ../glib/glib/gmain.c:4543
#2  g_main_context_iterate.constprop.0 (context=0x7fffec001cf0, block=1, dispatch=1, self=<optimized out>) at ../glib/glib/gmain.c:4233
#3  0x00007ffff5515132 in g_main_context_iteration (context=0x7fffec001cf0, may_block=1) at ../glib/glib/gmain.c:4303
#4  0x00007ffff64d820c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffec000b70, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#5  0x00007ffff6485d2c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7ffff2316d10, flags=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#6  0x00007ffff62e71ff in QThread::exec() (this=this@entry=0x7ffff247c560 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#7  0x00007ffff2420cba in QDBusConnectionManager::run() (this=0x7ffff247c560 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at /usr/src/debug/qt5-base/qtbase/src/dbus/qdbusconnection.cpp:179
--Type <RET> for more, q to quit, c to continue without paging--
#8  0x00007ffff62e42da in QThreadPrivate::start(void*) (arg=0x7ffff247c560 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread_unix.cpp:330
#9  0x00007ffff5c9f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#10 0x00007ffff5d21a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7ffff4e19cc0 (LWP 27039) "lmms"):
#0  0x00007ffff648d0bb in QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) (this=this@entry=0x5555561f6b40, receiver=receiver@entry=0x555556795e70, event=event@entry=0x7fffffffd4a0) at kernel/qcoreapplication.cpp:1172
#1  0x00007ffff7978b5a in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=0x5555561f6b40, receiver=0x555556795e70, e=0x7fffffffd4a0) at kernel/qapplication.cpp:3608
#2  0x00007ffff648d578 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555556795e70, event=0x7fffffffd4a0) at kernel/qcoreapplication.cpp:1064
#3  0x00007ffff79a53fa in QWidgetPrivate::setStyle_helper(QStyle*, bool) (this=<optimized out>, newStyle=0x0, propagate=<optimized out>) at kernel/qwidget.cpp:2659
#4  0x00007ffff79b0405 in QWidget::setParent(QWidget*, QFlags<Qt::WindowType>) (this=0x555556795e70, parent=<optimized out>, f=...) at kernel/qwidget.cpp:10501
#5  0x00007ffff799d19a in QWidgetPrivate::init(QWidget*, QFlags<Qt::WindowType>) (this=0x55555673ff00, parentWidget=<optimized out>, f=...) at kernel/qwidget.cpp:1046
#6  0x00005555557eb937 in lmms::gui::MainWindow::MainWindow() ()
#7  0x00005555557db4e1 in lmms::gui::GuiApplication::GuiApplication() ()
#8  0x000055555568b2bb in main ()
(gdb) 

</details>

**Comment by RiedleroD** [comment] 2022-12-18 09:23
possibly duplicate of #6587, have you tried the workaround from there?

**Comment by Fl0wdnb** [comment] 2022-12-18 18:14
I can confirm that was the issue. I have downgraded kwidgetsaddons to the current artix version and all is working again.

**Closed** 2022-12-18 18:15 UTC
Labels: bug
