### ISSUE TITLE
Infinity range of knobs (and faders?)

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1663] opened 2015-01-20 17:40 UTC
Idea: Instead of showing the whole range from 0-100db (if the knob/fader supports that), you decide what to show 0-10db for example, and then the user can choose to scroll further up. It would be like a dynamic knob?

**Comment by diizy** [comment] 2015-01-20 20:20
On 01/20/2015 07:40 PM, Stian Jørgensrud wrote:
>
> Maximum volume gain of the native amp is 200% and quite often I need
> more. So I either use several amplifier effects (have used up to four
> in a row) or I just use the LADSPA amplifier which supports gain up to
> 10, that would be 1000%, right?
>
> If the reason is to preserve the fine adjustment I suggest adding an
> additional gain knob.
>

The issue will become moot once we convert all volume knobs to use dBV
units.

**Comment by Sti2nd** [comment] 2015-01-20 20:23
:+1:

**Comment by tresf** [comment] 2015-08-24 16:15
Closing as a duplicate of the dBV UI conversions, which is a WIP.

**Closed by tresf** 2015-08-24 16:15 UTC
Labels: enhancement, gui
