### ISSUE TITLE
Delete the selection in automation track

### ISSUE THREAD

**Issue by vivi2004** [LMMS/lmms#5259] opened 2019-10-20 07:40 UTC
Actually we can just move the selection in automation track, and I often need to delete what I selected, so please add it.

**Comment by Spekular** [comment] 2019-10-20 08:30
Closing as duplicate of/merging with #5157

To me, a fequesr for selection in automation editor implies move/copy/cut/paste/delete functionality, otherwise the selection is useless.

**Closed by Spekular** 2019-10-20 08:30 UTC
