### ISSUE TITLE
the LMMS font sizes are too small to read.

### ISSUE THREAD

**Issue by nelsonkane** [LMMS/lmms#3504] opened 2017-04-17 17:44 UTC
I see where a lot of people have complained about this.
It looks like LMMS doesn't want users directly contacting the company. 
Oh well! :)

**Comment by tresf** [comment] 2017-04-17 18:50
> LMMS doesn't want users directly contacting [them]

I'm sorry if you feel this way.  The developer team prefers users to file bugs directly on our tracker.  Perhaps you can share where you got this impression and we can correct it.

> the company

There is no company.

> I see where a lot of people have complained about this.

Correct.  The fix is not straightforward and requires a lot of work.  We're all volunteers here.

Thanks for submitting.  Closing as duplicate of the bug report here: #2510

**Closed by tresf** 2017-04-17 18:50 UTC
Labels: duplicate
