### ISSUE TITLE
Issue submission guidelines

### ISSUE THREAD

**Issue by claell** [LMMS/lmms#4889] opened 2019-03-12 15:35 UTC
As discussed in #4877 issue submission guidelines / templates sound reasonable, so I am creating this issue to create and discuss them.

They can probably be split into a template for bug reports and one for feature requests / enhancements.

If @tresf is ok with it, I can search for some good default templates for a start and then those can be adjusted to fit this projects needs.

---

### Bug template (WIP):
Found https://github.com/stevemao/github-issue-templates/blob/master/no-duplicates/ISSUE_TEMPLATE.md which seems to be a good starting point.
```md
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

Also try to choose a meaningful title so it is easier to know what the issue contains.

## Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* LMMS version used:
* Operating System and version:
```

### Feature request template (WIP):

```md
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

Also try to choose a meaningful title so it is easier to know what the issue contains.

Please try to specifically describe the feature you would like to have added and if possible also the affected part of the project.
```

**Comment by tresf** [comment] 2019-03-12 16:41
Thanks however this is a duplicate of #4884.  Let's focus our efforts there.

**Closed by tresf** 2019-03-12 16:41 UTC

**Comment by claell** [comment] 2019-03-12 16:45
Alright, did only search issues, not PRs, so sorry for causing extra work.

**Comment by claell** [comment] 2019-03-12 16:46
And I apparently did not search for issue templates, so this is also a duplicate of #4196
