### ISSUE TITLE
High-dpi / high-resolution support, GUI scaling

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#455] opened 2014-03-14 07:50 UTC
This is again something that has been discussed in mailing lists which I'm posting here so that it exists in the issue tracker. This is all post-1.0.0 stuff and in no hurry to get implemented, though.

High-dpi screens are getting more common, and this presents a challenge to applications to function in diverse resolutions. Some desktop environments provide the option to automatically scale the GUI of applications, but it would be even better if the application does it themselves, or provides the option for the user to set the scaling factor.

I'm thinking the latter would be the best choice here, since it would also benefit people with impaired vision to be able to scale up the GUI. 

So this would require two steps:
1. create a global "scaling factor" property, which varies from 1.0 (no scaling) to maybe 2.0, 2.5 or so - 2x size should be enough for all screens, although we can increase that size in the future if need arises.
2. modify all graphic and UI elements to take the scaling factor in account in all coordinates, sizes, pixmaps, etc.

This would also mean we should implement support for .svg in the pixmap embedding code. But that doesn't mean everything should be in .svg - we should use it where it makes sense and not compromise on visual style. I'm thinking a smart way to do this would be to modify embed.cpp so that when it's given a request to search for eg. "add_automation", instead of just searching for "add_automation.png" it will first search for .svg, if that isn't found, it searches for a png. 

For the latter part, I'm thinking we can provide two versions of every png image: normal and 2x size. The way it would work is, in regular 1x scale, the regular "automation.png" would be used, but if the scaling factor is >1, then it would search for "automation.x2.png" and scale it down according to the scaling factor. This is because with bitmaps, scaling down is always cleaner than scaling up.

Most of the current UI elements already have either a .svg version or a 2x size png, which is good. But some don't. For the future, I'd like to request that all graphics contributions should either provide a .svg, or both 1x and 2x sized versions of a png. I've tried to ask this before but I haven't really enforced it as a rule - we should probably take a more strict approach to it in the future.

**Comment by tresf** [comment] 2015-11-13 14:25
The font issues are mostly a duplicate of #455.  #455 has specific files that can be fixed right now to help support better font scaling and is a place people can help right away.

The Qt5 "HiDPI" stuff is as described a "free" benefit from switching from Qt4 to Qt5, so that is mostly addressed here #2108.

The rest (svg support, etc) will come with time through long-term work with theme updates such as #1839, #880, #1911.

Closing for now, but please feel free to reference or reopen at a later time.

**Closed by tresf** 2015-11-13 14:25 UTC
Labels: enhancement, gui
