### ISSUE TITLE
Metronome breaks at high tempos

### ISSUE THREAD

**Issue by Lenticat64** [LMMS/lmms#6599] opened 2022-12-27 20:57 UTC
### Bug Summary
At high tempos, the metronome begins to break. Starting at 300BPM, it can no longer keep a beat.
#### Steps to reproduce
Set tempo to 300BPM, turn on metronome, and hit play.
#### Expected behavior
Keep a steady beat. (PAH pah pah pah)
#### Actual behavior
Cannot keep a steady beat. (PAH pahpah PAH pah)
#### Screenshot
N/A
#### Affected LMMS versions
LMMS 1.3.0-alpha.1.102+g89fc6c960 on Windows 10 22H2. I did not test on other versions.

**Comment by sakertooth** [comment] 2022-12-27 21:25
Every time the metronome is ready to play, it does an allocation for memory for a sample handle. This allocation can be acceptable at smaller tempos, but if the tempo is, say, 300 BPM, then it has to not only allocate this handle 5 times every second, but also de-allocate it at that same rate, which can easily slow things down. I suspect this to be the reason the metronome is not on beat, but I may be wrong, as it does depend on your system, among other things.

Does the CPU usage increase as well when using the metronome? I have had this happen to me as well and noticed the increase.

The remedy for this in the codebase is to not allocate ``SamplePlayHandle`` using ``new`` (and also potentially make the handle more lightweight), but I see this as a long-term goal, so I'm not sure how quickly this can be remedied.

**Comment by Lenticat64** [comment] 2022-12-27 22:04
The CPU usage is increasing from 0.8% without to 1.8% with, playing the same track both times.

Unsure if this is relevant, but my specific CPU is a Ryzen 3600X.

**Comment by DomClark** [comment] 2022-12-28 16:08
Duplicate of #4038.

**Closed by DomClark** 2022-12-28 16:08 UTC
Labels: bug
