### ISSUE TITLE
Vocoder FX plugin: Distorted output

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2005] opened 2015-04-24 12:57 UTC
The orr. hijacked thread was this one #2003 
Would someone on windows follow the suggested workflow, (
@tresf post
>Clunky... 
   
and confirm, that vocoder *also* works in windows.  It does not for me on xp
https://soundcloud.com/musikbear/vocoderrecord
(Hardware could ofcause also be an issue)

**Comment by tresf** [comment] 2015-04-24 12:59
You should clarify the LMMS version you would like tested.  The track that I posted was composed and rendered on Windows 7 using the 1.0.x build.

-Tres

**Comment by tresf** [comment] 2015-04-24 13:00
Also, you should copy/paste the relevant information from that bug report into this one so people know how to reproduce the issue.

**Comment by Spekular** [comment] 2015-04-24 13:13
I've tested an autotune and vocoder in 1.0 on Win 7 and they worked fine
for me, using a Q6700 (2.66Ghz quad core) with 4Gb RAM. Perhaps you're
using bad inputs?

**Comment by musikBear** [comment] 2015-04-24 14:35
> composed and rendered on Windows 7 using the 1.0.x build.

>tested an autotune and vocoder in 1.0 on Win 7 and they worked fine

witch makes this thread redundant.  Obviously vocoder works, just not for me, and thats just my problem, not related to the project
Thanks for testing :+1: 
Suggest mark: 'not our bug'

**Comment by tresf** [comment] 2015-04-24 14:40
> witch makes this thread redundant. Obviously vocoder works, just not for me, and thats just my problem, not related to the project

@musikBear to be fair, both tests passed in the 1.0 branch.

Please test if this is newly introduced with 1.1 branch and we can proceed from there.

**Comment by musikBear** [comment] 2015-04-24 15:20
I can actually get 'something' where at least the words are recognizable, but it is in a different way, or at least something else is needed too.
As i ..'investigated' this, i realized that there is a huge unknown in this:

*What **instrument** was used*!! 

I get very different results with different instruments. Best first result with 'Nescaline', but then i started to experiment with added white noise, and that is making it much better.
Is there simply something i had NO idea about, and that you guys simply too for given -Eg the instrument need to have a percentage of white noise, **added** to the actual notes?
Eg the **Instrument** needs to be build in a very exact way?
(This turns into a 'help-request' -But on the other hand, we need to get a good recipe, for the wiki :p

**Comment by Umcaruje** [comment] 2015-04-24 15:38
@musikBear where do you pan your vocal track? [The vocal should be panned to left, and the carrier (your instrument) to the right.](http://www.sirlab.de/linux/download_vocoder_ladspa.html)

**Comment by musikBear** [comment] 2015-04-24 15:51
@Umcaruje oh yes, thats done, and as i say, i now have reasonable good output, and as i experiment more with EQs and percentage of noise, i get better and better results. What absolutely do NOT work at all is sine. Saw gives the highest clearness, and there must be at least one in a very low register. The higher the register, the worse is the distortion. I will upload a demo more, because it is very much better, but it does need a neat bit of tinkering -not at all out of the box, (for me)
Does sine in 3oc really produces a good result for you?

**Comment by musikBear** [comment] 2015-04-25 13:58
zasfx experiments gives this. A lot of work with the carrier is needed to get good result. One strange thing, was that distortion improves the result significantly(?)
https://soundcloud.com/musikbear/voco3
No extra curriculum-points for guessing what happen in the end..  :p
(why, im not sure... :|
I have noticed *huge* cpu spikes, if the notes ends before the carrier ends. That i have no explanation for either
I still like to know, if anyone has been able to use an out-of-box factory instrument, and if so -What was it?
@tresf - What instrument do you use the your linked track, as the carrier?

**Comment by tresf** [comment] 2015-04-25 14:26
3xosc, but it was done with TalkBox, before Vocoder was fixed.  I can export the preset if needed.

**Comment by musikBear** [comment] 2015-04-25 15:55
> but it was done with TalkBox, before Vocoder was fixed.

ahh - yes i see, then its a whole different thing, and not all that relevant, but i think i have an ok result now, but its *no-way* out of the box. I spend an hour+ tinkerling with dials and effects 
Do you think current vocoder is 'broken'?

**Comment by softrabbit** [comment] 2015-04-25 16:13
@musikBear, sine is a bad choice for the carrier. It just doesn't have enough overtones. Saw has more of them and distortion adds overtones, so they work better. And note stacking also helps. Bottom line: there has to be something for the vocoder's filters to work on. It comes with the design.

As for the CPU spikes, it's probably denormals or something like that creeping in. The 1.0 series wasn't protected against them but 1.1 is AFAIK, which version do you use?

**Comment by musikBear** [comment] 2015-04-26 09:45
> Saw has more of them and distortion adds overtones, so they work better

Make sense, also adding overtones in zasfx, was also one of the ways i improved the output

>The 1.0 series wasn't protected against them but 1.1 is AFAIK, which version do you use?

win32 1.1.3 off. release
If 1.1 should protect against denormals, then there might be something wrong there?

I will update the wiki, and outline some of the trickery that make better vocoder result

**Comment by softrabbit** [comment] 2015-04-26 17:18
Looks like it was decided to not require SSE on 32-bit builds just yet, which means denormal protection is off. Maybe time to reopen that issue...

I did try to get CPU spikes using the vocoder in a 32-bit Linux build, but didn't see any. @musikBear, could you share a project somewhere with that problem? And what is your CPU? Some handle denormals better than others.

**Comment by musikBear** [comment] 2015-04-27 10:17
> @musikBear, could you share a project where you encounter that problem somewhere? And what is your CPU? Some handle denormals better than others. 

Sure I have attached a mmpz project here:
http://lmms.io/forum/viewtopic.php?f=1&t=2260

CPU: Intel Core 2 Duo E6750, 2.667GHz, 1333SB 1.116,00

**Comment by softrabbit** [comment] 2015-04-27 19:08
I couldn't see an attachment in the forum, but no worries, I got CPU spikes. Had to try an older CPU than yesterday, and the AMD Phenom was clearly affected. 

I built LMMS with ```-mfpmath=sse``` to ensure all math is in the SSE unit, where denormal protection works, and the spikes were gone. So it's pretty much confirmed that it's a denormal problem.

**Comment by tresf** [comment] 2015-04-27 19:25
@softrabbit is this something we consider wont-fix, or do we have the ability to correct this problem?

**Comment by Wallacoloo** [comment] 2015-04-27 22:07
@softrabbit so no matter how the vocoder is built, the performance is all down to whether or not LMMS is built with sse? That indicates that the vocoder effect is outputting denormalized values then, and its the processing of those *within LMMS* that causes the spikes, right? 

If that is the case, we could explicitly check for denormalized fx outputs and flush them to zero before doing any processing. Of course, that's useless when LMMS is built with SSE and configured to do that already, so it'd be best to wrap that in an #ifdef. If this is indeed the case, would it actually be worth it to do this, or would it noticeably degrade performance in the 99% of cases where plugins don't output denormals?

**Comment by softrabbit** [comment] 2015-04-28 08:54
@Wallacoloo, the vocoder is part of the LMMS distribution, and it's built with whatever ```CMAKE_C_FLAGS``` are passed to the LMMS build process, unless overridden in some CMakeList along the way (looks to me it isn't). So it's either the vocoder or LMMS per se that causes spikes. 

@tresf, it should be a matter of adding a flag or two to the build recipes, i.e. making SSE math the default for 32-bit builds. All win32 users have SSE capable CPUs, as the present win32 build requires it, so at least changing the ```build_mingw32``` file should be OK. Linux packagers would still be free to build whichever way they want, but maybe the default could be upgraded there too? Of course there has to be a prominent notice in the release notes, so those wishing to stay 486 compatible can do so.

Switching over might make LMMS slightly slower (5-10%) on some hardware, but OTOH there might be a similar speedup on other hardware.

**Comment by musikBear** [comment] 2015-04-28 09:27
> I couldn't see an attachment in the forum, but no worries,

arhh ..no that was disabled during the spam attack - i should have checked - sorry
well here it is..
https://lmms.io/lsp/?action=show&file=6759
Perhaps others like to see the setup

**Comment by tresf** [comment] 2015-09-17 12:17
@softrabbit does https://github.com/LMMS/lmms/pull/2323 help address this issue?

**Comment by softrabbit** [comment] 2015-09-17 16:33
> does #2323 help address this issue?

The performance part of it, yes. And the sound quality problem was sorted earlier, so I'm closing.

**Closed by softrabbit** 2015-09-17 16:33 UTC
