### ISSUE TITLE
support dawproject format

### ISSUE THREAD

**Issue by RustoMCSpit** [LMMS/lmms#7232] opened 2024-04-29 09:37 UTC
### Enhancement Summary

https://github.com/bitwig/dawproject

an open source cross-platform format

### Implementation Details / Mockup

i should be able to import and export the file type

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Rossmaxx** [comment] 2024-04-29 09:38
Duplicate of #6909

**Closed** 2024-04-29 09:38 UTC
Labels: enhancement
