### ISSUE TITLE
Rendering past 100%

### ISSUE THREAD

**Issue by kLik-kLak** [LMMS/lmms#2234] opened 2015-08-03 05:38 UTC
![o_gawd](https://cloud.githubusercontent.com/assets/2879917/9119687/8ff69f54-3c67-11e5-9ef9-a9d437a42653.png)

the image pretty much speaks for itself...

**Comment by kLik-kLak** [comment] 2015-08-03 05:58
<a href='http://postimg.org/image/h3v8l2as1/' target='_blank'><img src='http://s8.postimg.org/h3v8l2as1/horey_fuuuuk.jpg' border='0' alt="horey fuuuuk" /></a>
when it got to 196% my pc started glitching out and this crackling popping noise started, at this point I killed it with task manager...

**Comment by Wallacoloo** [comment] 2015-08-03 06:06
Oh dear...

It looks like you are using stable 1.1.3, as opposed to the version in git,
right? There was a PR a few weeks ago that fixed export percentage
calculations in the presence of loop points, but it looks like there is
more going on here.

**Comment by kLik-kLak** [comment] 2015-08-03 06:11
<a href='http://postimg.org/image/uugqmfy7l/' target='_blank'><img src='http://s24.postimg.org/uugqmfy7l/late.jpg' border='0' alt="late" /></a>

**Comment by PhysSong** [comment] 2018-02-10 11:18
Closing since this issue is too old and the OP haven't provided any way to reproduce this.

**Closed by PhysSong** 2018-02-10 11:18 UTC
Labels: bug
