### ISSUE TITLE
Unable to drag and drop controls into Automation Tracks

### ISSUE THREAD

**Issue by a2aaron** [LMMS/lmms#3745] opened 2017-08-02 15:15 UTC
This bug seems to only occur on the beta versions (`Version 1.2.0-rc3`) and NOT on stable (`Version 1.1.3`)

OS: macOS 10.12.5
Kernel: Darwin 16.6.0
RAM: 8 GB, DDR3, 1600 MHz
CPU: Intel Core i5 @ 3.2 GHz
GPU: NVIDIA GeForce GTX 675MX

How to reproduce
1. Open any LMMS project (even default)
2. Hold `cmd` and attempt to drag any control into an Automation track
3. The cursor briefly flashes the green plus symbol for one frame but disappears immediately
4. Dropping the control fails without it being added to the track.

On stable this bug does not occur, and right clicking and going to "Edit song-global automation" still seems to work fine in all version I've tested.

There's also some strange weirdness with dragging a control as well. Often, the icon will lag behind (in fact, if you move your cursor rapidly and stop, the icon still moves as it catches up). This also does not happen on stable.

![Bug on beta](https://user-images.githubusercontent.com/15718048/28880682-ce34a7ae-7773-11e7-8323-5bbcecac93a8.png)

![Bug not appearing on stable](https://user-images.githubusercontent.com/15718048/28880688-d3d3a818-7773-11e7-861a-8623e6a4623e.png)

**Comment by a2aaron** [comment] 2017-08-02 15:57
I built LMMS from source (on master branch). When trying to drag the control the standard output gets spammed with `QNSView mouseDragged: Internal mouse button tracking invalid (missing Qt::LeftButton)` and `QPixmap::grabWidget is deprecated, use QWidget::grab() instead`.

**Comment by tresf** [comment] 2017-08-02 17:21
Stable uses Qt4.  Beta uses Qt5.  This issue has a workaround, use Option + Alt.  Much more information around this is documented here: https://github.com/LMMS/lmms/issues/2890#issue-163523982

What I discovered it is comes down to the Apple SDK version that seems to influence this the most.   I truly believe this is an upstream Qt5 issue, but since the latest SDK and latest Qt5 didn't exhibit it for us, we never opened a bug report.  Perhaps this is something lower-level that we can help Qt resolve, but what you'll notice in #2890 is that if the modifier key is changed from Option to Shift, it works without problems, so this appears to be a compatibility that is perpetuated by our default shortcuts.

**Comment by tresf** [comment] 2017-08-02 17:28
**Edit:**:  Also, the mouse-cursor dragging inside plugins on MacOS is unusable.  It suffers a similar race condition where the mouse scrambles to catch up and causes graphical anomalies.  To reproduce, open BitInvader and drag the waveform around.  I haven't documented this issue yet, but anyone is welcome to. `</offtopic>`

**Comment by tresf** [comment] 2024-06-07 18:12
Reopened https://github.com/LMMS/lmms/issues/2890.  Closing this one as it appears to be the same issue.

I can report this on nightly, so I think we still have a bug somewhere.

**Closed** 2024-06-14 18:39 UTC
Labels: macos
