### ISSUE TITLE
Multiple directories for VST/SF2/LV2/etc.

### ISSUE THREAD

**Issue by JGHFunRun** [LMMS/lmms#6150] opened 2021-09-07 04:27 UTC
### Enhancement Summary

Allow for the user to have multiple VST/SF2/LV2/etc. directories that are detected instead of just one. (also support for a custom LV2 directory is needed in general)

#### Justification

Many systems have at least 2 directories where VSTs and other plugins are installed, this would allow them to all be used instead of having to copy/move files around

**Comment by Spekular** [comment] 2021-09-07 10:30
Duplicate of #4907, which is the third result when searching"multiple VST". The second result is #5433, which includes this as a sub issue.

**Closed by Spekular** 2021-09-07 10:30 UTC
Labels: enhancement
