### ISSUE TITLE
Additional permission regarding my contributions

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#3346] opened 2017-02-13 01:00 UTC
I have reviewed some sections of GPLv3 and I have come to an interesting [conclusion](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854921). GPLv3 introduces a procedure about what happens if you violate the license. GPLv2 has a different procedure. I do not find desirable any of both. Therefore, I would like to add an additional permission regarding all my GPLed contributions. Other developers are free to follow my path.

As you may see in the reference above, I am still drafting the permission, so input is welcome:

>You are granted this additional permission:
>
>Without waiving any right to claim damages because of your copyright infringement, your license from the following copyright holders is reinstated permanently if you cease all violation of this License.
>* Javier Serrano Polo

**Comment by tresf** [comment] 2017-02-13 01:43
Thanks for sharing.  Interesting problem you've identified there.

I don't care for the GPL because it's too viral and stifles innovation and is incompatible with LGPL which I find to be much more sensible, but that argument is a broken record.  Since the vast majority of our GPL references area simply a "mention", this specific disclaimer will read quite strangely out of context, so I'm interested in seeing how this is executed.  Thanks for sharing, I'm also interested in the Debian and/or FSF's response.

**Comment by jasp00** [comment] 2017-02-15 01:14
>and is incompatible with LGPL

GPL is compatible with LGPL, the combined work is under GPL.

**Comment by tresf** [comment] 2017-02-15 02:41
> GPL is compatible with LGPL, the combined work is under GPL.

Offtopic, but no.

**Comment by jasp00** [comment] 2017-02-15 22:27
Unless you are talking about mixing LGPLv3 and GPLv2, [it is](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility). Could you point me to your source?

**Comment by tresf** [comment] 2017-02-16 04:38
> Unless you are talking about mixing LGPLv3 and GPLv2, it is. Could you point me to your source?

No, it's not.  It makes LGPL become GPL, which is only compatible if you didn't really need LGPL in the first place.  That chart is stupid.  The color should be bright yellow, not a slight variation hint of green.

**Comment by tresf** [comment] 2017-02-16 04:49
Perhaps I should have said LGPL is incompatible with GPL, which is what I meant.  My point in this off-topic rant is that GPL is too discriminatory for the marketplace, which is what puts food on the table.

**Comment by jasp00** [comment] 2017-02-16 20:56
>in this off-topic rant

Not that off-topic; this issue is related to a defect/feature of GPL. Your points certainly belong to the tracker, because this is the license of the project. Business models concerning LMMS and reasons to fund the project are relevant. Let us open a different issue.

**Comment by tresf** [comment] 2017-04-07 17:17
You really can't modify a license by putting a friendly disclaimer in it.  Unless you are the sole author, how do we know which components are yours and which are others?  I'd recommend you start dual-licensing your work.  I'm not sure the blurb accomplishes anything except a false peace of mind for you and only you.

**Comment by jasp00** [comment] 2017-04-09 17:19
>You really can't modify a license by putting a friendly disclaimer in it.

I am not modifying the license, but supplementing with a compatible term.

New version:

>This License is supplemented with this term:
>
>Without waiving any right to claim damages because of your copyright infringement, your license from the following copyright holders is reinstated permanently if you cease all violation of this License. If this License allows to require preservation of legal notices, you are required to preserve this term, unless it is implied by this License; otherwise, you are merely requested to preserve this term.
>
>* Javier Serrano Polo

**Comment by tresf** [comment] 2017-04-10 16:44
> I am not modifying the license, but supplementing with a compatible term.

Hmm... from what I'm reading:

1. The term is a part of the license conditions, and the GPL clearly states you are not allowed to modify the license.  To me, this is a modification to the license.
1. You can't revert the penalties defined in GPL2 and you can't permanently (perpetually) reinstate a license.  It's not your right to reinstate the GPL2 license.
1. If you are the sole copyright holder you can do whatever you want, but under a separate license and all contributors will be operating under your dual license.

Modifying terms seems to be in direct conflict with GPL2, so I recommend you take this up with FSF and get it amended to e.g. GPL4 (unless GPL3 already fixes this problem).

If you're right, I recommend you have it amended to the FAQ section so that others facing this problem can also include the same text.

Since the purpose of GPL2 is to "exercise the right to control the distribution of derivative or collective works based on the Program.", any court will rule that the terms affect distribution, and anyone is in violation by modifying this.

However, if obtaining a new license is as easy as... just obtaining the code again, I'm not sure what the issue is with GPL2 to begin with.  You could just ask someone to hold on to it for a few seconds and then you can request a license on their behalf.  The perpetuality seems outright unenforceable and I don't think our bug tracker is the place for this.  It seems better targeted at the FSF.

**Comment by jasp00** [comment] 2017-04-10 21:41
>To me, this is a modification to the license.

It is a supplement, not a modification, and it is not an invalid further restriction; thus it is legal. What term do you believe is modified?

>You can't revert the penalties defined in GPL2 and you can't permanently (perpetually) reinstate a license.

Regarding my contributions, I can. What term do you believe says otherwise?

>It seems better targeted at the FSF.

This is independent of FSF activities.

**Comment by tresf** [comment] 2019-03-11 19:52
> I am not modifying the license, but supplementing with a compatible term.

Getting all authors to retroactively agree to these "compatible terms" is too hard.  Adding author-specific "terms" is a mess.  We appreciate the thought and let this thread be evidence of your "compatible terms".  Closing as `wontfix`.

**Closed by tresf** 2019-03-11 19:52 UTC
Labels: conversation

**Comment by jasp00** [comment] 2019-03-12 06:57
>Getting all authors to retroactively agree to these "compatible terms" is too hard.

No such a thing is required.

>Adding author-specific "terms" is a mess.

No, it is not. I will use `debian/copyright`.

>let this thread be evidence of your "compatible terms".

Code is the authoritative source.

Thoughts about parts of LMMS being licensed under MIT would be appreciated (#4443).

**Comment by tresf** [comment] 2019-03-12 16:42
> Code is the authoritative source.

No, our code is GPL2+.  We're not adding developer additions, sorry.

**Comment by jasp00** [comment] 2019-03-12 17:16
Are you forbidding me to add my permission in `debian/copyright`?

**Comment by tresf** [comment] 2019-03-12 17:20
> Are you forbidding me to add my permission in debian/copyright?

Yes, please.  Are other projects allowing this one-off stuff?

> Code is the authoritative source.

No, not when intertwined.  It requires a low-level look at the commit history.  Just stop.

**Comment by jasp00** [comment] 2019-03-12 17:23
>Just stop.

As you wish.
