### ISSUE TITLE
VST-host sync doesnt work

### ISSUE THREAD

**Issue by andydld** [LMMS/lmms#4498] opened 2018-07-20 12:15 UTC
When you use the AcidBox-VSTi in "host sync"-mode, it starts and keeps playing since the plugin is loaded. LMMS doesnt control the play/stop (but it should). You can try this with the demo-version:

https://www.audioblast.me/acidbox.html

With other DAWs this works like excepted.

I talked to AudioBlast, the maker of AcidBox and they wrote to me the following lines:

"in fact, LMMS (or Vestige) doesn't transmit the host "transport bar" flags : the play / stop / loop etc.. are never sent to the plugin.
If you have access to the source code of LMMS/Vestige, search for kVstTransportPlaying and kVstTransportChanged ! "

Tested with LMMS 1.2.0 RC6 on Windows 10 und Windows 8.1.

**Comment by lukas-w** [comment] 2018-07-20 12:50
Possibly a duplicate of #4351.

**Comment by DomClark** [comment] 2018-07-20 14:55
@andydld Have you enabled "Sync VST plugins to host playback" in settings? If not, try doing so, restart LMMS and see if the problem persists.

**Comment by andydld** [comment] 2018-07-20 15:11
With activated "Sync VST..." the problem has changed. After loading AcidBox and click play on LMMS nothing happens within the plugin. After changing from "host sync" to another mode and switch back to "host sync" and an click on play, the pattern starts playing, but it seems, thats an wrong speed. If i then click stop and play again, nothing happens again.

**Comment by andydld** [comment] 2018-07-25 06:32
Just one more feedback from AudioBlast:

"I also activated the "Sync VST to host playback" in LMMS and it's a little better, but LMMs has a problem with the "transport bar changed"  flag : it sends continuously "changed" when playing, that's not the "standard" for VST hosts, this flag should be used for these cases only :

changing from stop to play
changing from play to stop
manually changing the transport bar position
looping

The continuous "changing" flag (many changes per seconds) makes the Acidbox crazy"

**Comment by PhysSong** [comment] 2018-08-06 13:50
AudioBlast's feedback suggests that we use `kVstTransportChanged` in an improper way here:
https://github.com/LMMS/lmms/blob/b5dc70c20a3c4d8881bfd1bfc119b2a2581b706a/plugins/vst_base/RemoteVstPlugin.cpp#L1539-L1546

@DomClark Can you look into this?

FYI, this is how Ardour uses the flag: https://github.com/Ardour/ardour/blob/bdf8edc4198494505fb59f92ffc1aef9c1e2136f/libs/ardour/session_vst.cc#L274-L279
```cpp
if ((timeinfo->flags & (kVstTransportPlaying | kVstTransportRecording | kVstTransportCycleActive))
    !=
    (newflags        & (kVstTransportPlaying | kVstTransportRecording | kVstTransportCycleActive)))
{
	newflags |= kVstTransportChanged;
}
```

**Closed** 2018-09-11 13:01 UTC
Labels: bug, vst
