### ISSUE TITLE
Issue with Zoom in Surge VST

### ISSUE THREAD

**Issue by TT1972** [LMMS/lmms#5656] opened 2020-08-25 10:59 UTC
Hi, 
I have a small issue when using the Zoom function within the Surge VST Plugin. The VST will get cropped at the initial size.
Not sure if this is an issue of LMMS or the Plugin itself. 
![LMMS_surge](https://user-images.githubusercontent.com/9975194/91166446-ad1b7580-e6d2-11ea-8957-26d7e2683dc1.jpg)

**Comment by DomClark** [comment] 2020-08-25 11:44
We don't currently resize embedded plugin windows correctly when the plugin itself changes size. This is due a limitation of our IPC system, which is unable to consistently report size changes from the remote plugin to the host. You can work around the bug by changing the plugin embedding mode in settings to "no embedding".

Closing as duplicate of #4087 (see also #4461, #5350).

**Closed by DomClark** 2020-08-25 11:44 UTC

**Comment by TT1972** [comment] 2020-08-25 15:12
Thank you very much for the info.
