### ISSUE TITLE
Add a Panning knob on Mixer channels.

### ISSUE THREAD

**Issue by aziagiles** [LMMS/lmms#6635] opened 2023-02-08 16:50 UTC
# Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet.

**Comment by LostRobotMusic** [comment] 2023-02-08 19:51
"Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet."

Read what you post before you post it please.  Closing as duplicate of #1974.

**Closed by LostRobotMusic** 2023-02-08 19:51 UTC
Labels: enhancement
