### ISSUE TITLE
Playback cursor for Beat+Baseline Editor

### ISSUE THREAD

**Issue by knobo** [LMMS/lmms#1954] opened 2015-04-13 21:55 UTC
Is it possible to make a playback cursor for BBE, or make the tombs flash each time they play a note?

**Comment by Wallacoloo** [comment] 2015-04-13 22:12
I second both of those suggestions. They sound like very useful features to have.

**Comment by tresf** [comment] 2015-04-14 01:16
Duplicate of #1195

**Closed by tresf** 2015-04-14 01:16 UTC
Labels: duplicate

**Comment by tresf** [comment] 2015-04-14 01:17
I realize that bug title doesn't appear to be a dupe, but the part about the steps being indicated I think is close enough to call it one. :)

> The other thing is an extension of the above issue/improvement but one that extends to the piano roll editor as well. With the piano roll if you press play in the dedicated window you can see a playhead/marker so you can see what is being played and where you are in the pattern. However, when you play the whole track from the timeline window and open a piano roll to edit something there is no playhead any more in the piano roll. Again, you have to resort to blind editing if you want to do some editing at the same time as hearing the other instruments.

Thanks for the bug report :)
