### ISSUE TITLE
Mixer channels replacing bug

### ISSUE THREAD

**Issue by LocoMatt** [LMMS/lmms#1764] opened 2015-02-15 12:44 UTC
When I'm moving fx channels using alt+arrow key my 1st channel glitches. It only happens when I hold the arrow key (when I move it one by one it works fine)
Here's video
https://www.youtube.com/watch?v=ZvPsX0y4hR4&feature=youtu.be

**Comment by Umcaruje** [comment] 2015-02-15 12:52
Reproduced on Ubuntu 14.10 x64
LMMS `stable-1.1` branch.

**Comment by waxspin** [comment] 2015-04-23 01:49
Taking a look at this one.

**Comment by tresf** [comment] 2015-04-23 02:28
@waxspin thanks.  FYI, not sure if the code is related, but this was just recently fixed #1584 via #1678.

**Comment by waxspin** [comment] 2015-09-11 01:11
Yes, it seems to be fixed as of the latest master at the very least.

**Comment by Umcaruje** [comment] 2016-03-13 22:18
Yup, this seems to be fixed on master. @LocoMatt could you check if this is fixed in the latest RC? you can get it here: https://github.com/LMMS/lmms/releases/tag/v1.1.90

**Comment by LocoMatt** [comment] 2016-03-14 16:56
Works fine, Win7 x64

**Comment by Umcaruje** [comment] 2016-03-14 17:53
ok great, closing :+1:

**Closed by Umcaruje** 2016-03-14 17:53 UTC
Labels: bug, gui
