### ISSUE TITLE
Kilohearts Plugins Compatibility

### ISSUE THREAD

**Issue by Vhami** [LMMS/lmms#5026] opened 2019-06-09 20:15 UTC
Hey LMMS Users!

·I just have noticed that when i try to open a kiloheart plugin it automatically crush the whole DAW or only apear the name of the plugin in the mixer but not the plugin,
this only happen with Kiloheart plugins and i hope this issue can be fixed in a near future.

Thanks for your time :)

Cheers,Vhami.

**Comment by DouglasDGI** [comment] 2019-06-09 20:18
What LMMS version are you using?  If you update to 1.2 stable (at https://lmms.io/download), does it still crash?

**Comment by Vhami** [comment] 2019-06-09 20:27
Yeah i updated 15 minutes ago and it still crash or it directly doesn't appear the plugin,just the name

like this:

![Captura](https://user-images.githubusercontent.com/39219607/59163789-cce27000-8b05-11e9-8629-1f85a6323c95.PNG)

**Comment by DomClark** [comment] 2019-06-12 15:26
I can't reproduce this. I've tested all the free plugins they offer and they all load and function correctly. Are you using the 64-bit version of LMMS? Apparently the latest versions of their plugins only support 64-bit hosts.

**Comment by Vhami** [comment] 2019-06-12 18:51
Yes, im using a 64-bit version...
i don't know why i can't use this plugins

**Comment by DomClark** [comment] 2019-06-12 19:29
What operating system are you using?

**Comment by Vhami** [comment] 2019-06-14 14:33
Windows 10 (the last build) 64-bit

**Comment by DomClark** [comment] 2019-06-14 15:16
Do the plugins load properly in any other hosts? I find [VSTHost](http://www.hermannseib.com/english/vsthost.htm) to be a useful lightweight program to test with.

**Comment by Vhami** [comment] 2019-06-14 15:46
yes,i tried with fl studio and ableton and they work properly

**Comment by DomClark** [comment] 2019-06-14 16:00
Are you using the latest version of the plugins (1.7.3 at the moment)? If not, try updating them. That version works for me. Otherwise, restart your computer and reinstall LMMS, then try loading them again.

**Comment by Vhami** [comment] 2019-06-14 23:52
DAMN they work now!

i just optimize my hard drive and now it loads every plugin from kiloheart properly :D

Btw thanks for suggest and help me with this problem :)

**Comment by DomClark** [comment] 2019-06-14 23:54
No problem. Glad to hear they're working. I'll close this issue now.

**Closed by DomClark** 2019-06-14 23:54 UTC
Labels: bug, vst
