### ISSUE TITLE
Error: TCO Long are deformed.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#5018] opened 2019-06-08 07:19 UTC
I do not know how to describe this error, but I give you this image:

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/26127693/59143772-41010480-899c-11e9-9efb-059d8e040b0f.gif)

Try this error like this:

1- Create several tracks from different editors.
2- Extract the tco by cloning or extending as long as possible.
3- Make zoon by the mouse wheel.

I experienced this error several times and although nobody would do it on purpose, I had many crashes of lms and the system. This error will test it in LMMS 1.2.0 rc8 within AV Linux 2019.

**Comment by zonkmachine** [comment] 2019-07-13 10:54
Is this https://github.com/LMMS/lmms/issues/3378 ?

**Comment by PhysSong** [comment] 2019-07-31 05:45
> Is this #3378?

I think yes. Closing this one as a duplicate of #3378.

**Closed by PhysSong** 2019-07-31 05:45 UTC
