### ISSUE TITLE
Project can have no more than 12 functional BitInvader tracks

### ISSUE THREAD

**Issue by JohnDorsey** [LMMS/lmms#2438] opened 2015-11-07 19:27 UTC
when more than 12 BitInvader tracks are added to a project, new BitInvader tracks cannot be played in the piano roll. New tracks do play normally when the entire song is played, and individual notes will play when clicked in the piano roll, but the piano roll will not make a sound when the open BitInvader track is played.
This occurs regardless of order in the song editor, parameters, enabled/disabled status. this is not effected by their order in the editor, only their order of creation. rearranging the tracks, saving, and restarting LMMS, does not effect which tracks are functional.

**Comment by Umcaruje** [comment] 2015-11-22 13:56
Can't reproduce on elementary OS Freya x64, running a fresh build of LMMS master.

@JohnDorsey can you please offer steps to reproduce and state your OS and LMMS version?

**Comment by JohnDorsey** [comment] 2015-11-23 16:43
Unfortunately, I am no longer able to reproduce the problem myself. Since I
quit working on my large 8-bit remix, I have had operating system updates
and an intel HD graphics driver update...
I am quite positive that the problem did occur very reliably at the time I
reported it.

I had, and still have, LMMS 1.1.3 for windows.
right now the full name of the version is LMMS 1.1.3 (win32/x86_64, QT
4.8.7, GCC 4.9.3 20150305 (prerelease)). I do not know if that changed.
I had, and still have, Windows 8.1, 64 bit, build 9600. (calls itself
6.3.9600 in command prompt)

I have an intel core 17-5500U CPU with driver version 6.3.9600.16384
I have Realtek HD audio driver version 6.0.1.7288 using audio codec ALC233.
my audio interface is set to Simple DirectMedia Layer.

I had not moved or changed the project. it's a compressed project.
I've tried to recreate the problem by adding an additional 20 or so
BitInvader tracks and changing up their settings.

while trying to recreate this problem, I noticed another one. occasionally,
when you close the piano roll for one track and open it on another and hit
play, it will play the first track through the speakers instead. I had
noticed this before, and discovered that the solution was to play the song
editor itself for a few seconds. then the piano roll would go back to
functioning normally.
I wonder if the problem I reported is an extreme form of this problem,
where the piano roll mistakenly plays the sounds of an empty track.
however, the solution for the first problem did not fix this.

**Comment by tresf** [comment] 2015-11-23 18:50
Closing as invalid.  Thanks for the followup.

> while trying to recreate this problem, I noticed another one. occasionally,
when you close the piano roll for one track and open it on another and hit
play, it will play the first track through the speakers instead. I had
noticed this before, and discovered that the solution was to play the song
editor itself for a few seconds. then the piano roll would go back to
functioning normally. I wonder if the problem I reported is an extreme form of this problem,
where the piano roll mistakenly plays the sounds of an empty track.
however, the solution for the first problem did not fix this.

If you determine the cause please file a new bug report. :+1:

**Closed by tresf** 2015-11-23 18:50 UTC
Labels: needs clarification
