### ISSUE TITLE
Export to WAV imprints outdated info about LMMS version

### ISSUE THREAD

**Issue by ShurikMur** [LMMS/lmms#1688] opened 2015-01-25 04:03 UTC
V 1.1.0, win 32

Info tag in exported WAV file:
Field: Software
Value: LMMS (libsndfile-1.0.26pre5)

And one more small issue: the length of exported sound file = length from 0 to the end of last part in a song editor, even if the last part(s) is muted and do not renders into actual sound.

**Comment by mikobuntu** [comment] 2015-01-25 11:19
" (libsndfile-1.0.26pre5) "
This is displaying the libsndfile version, nothing to do with the actual LMMS version.
thanks Mikobuntu ;)





  
    
    
  
  
 		 	   		  =

**Comment by tresf** [comment] 2015-01-25 13:00
> the length of exported sound file = length from 0 to the end of last part in a song editor, even if the last part(s) is muted and do not renders into actual sound.

Thanks for pointing this out. Please adjust your bug report or file a new one for this as @mikobuntu pointed out the version information is irrelevant to the LMMS version.

**Comment by tresf** [comment] 2015-01-25 14:14
I don't see anything hard-coded to use the song length versus then rendered length... 

Export is the same as playing except the flag `m_exporting` is set to true per [`Song.cpp#L643`](https://github.com/LMMS/lmms/blob/master/src/core/Song.cpp#L643) and written via [`AudioFileDevice::writeDate(...)`](https://github.com/LMMS/lmms/blob/master/src/core/audio/AudioFileDevice.cpp#L78) interface.

This is the only place I see the song length calculated:
[`ProjectRenderer.cpp#L169`](https://github.com/LMMS/lmms/blob/master/src/core/ProjectRenderer.cpp#L169)

But the rendering doesn't see to even use that value, it is initialized via [`ProjectRenderer.cpp#L82`](https://github.com/LMMS/lmms/blob/master/src/core/ProjectRenderer.cpp#L82) and just processes until done from what I can see in [`Song::processNextBuffer()`](https://github.com/LMMS/lmms/blob/master/src/core/Song.cpp#L198) (right?)

**Comment by tresf** [comment] 2015-01-29 21:15
I'm closing this out for now as the version information in file is irrelevant to LMMS version.  As far as the invalid song length, if that becomes an issue, please file a new bug report (or reopen this one) and we can investigate as to the cause.

**Closed by tresf** 2015-01-29 21:15 UTC
