### ISSUE TITLE
Certain LMMS Instrument Presets Load With A Taller GUI Window

### ISSUE THREAD

**Issue by sound8** [LMMS/lmms#6268] opened 2022-01-11 17:07 UTC
When dragging in certain stock LMMS Instrument Presets from the Browser, the instrument window GUI load with a taller height.  They strangely end up having a large grey box in between the Instrument GUI and the keyboard graphic at the bottom of the window.

This can be seen by loading the stock Kicker preset "SnareMarch"
I have not tested them all, but this is not the only one, I believe one of the Monstro stock presets does this as well.

No big deal, but just trying to help LMMS be as clean as possible.

**Comment by Spekular** [comment] 2022-01-11 17:24
Duplicate of #5851.

**Closed by Spekular** 2022-01-11 17:24 UTC
Labels: bug
