### ISSUE TITLE
LMMS crashes when I try to minimize a plug-in really quickly

### ISSUE THREAD

**Issue by Lxg3nD** [LMMS/lmms#6136] opened 2021-08-18 09:01 UTC
Particularly the keyzone classic Plug-In but bigger Plug-Ins crash way, way more. Please fix this issue, Thank You.

**Comment by DomClark** [comment] 2021-08-18 11:21
I can't reproduce this. Could you provide more detailed instructions on how to trigger it, or even a short video demonstrating the bug?

**Comment by Lxg3nD** [comment] 2021-08-18 11:47
https://user-images.githubusercontent.com/89130928/129892697-ff1c9306-21aa-4a0c-b73f-3ff6b01d1b71.mp4

i wasn't able to show the crash but it freezes lmms and says lmms is not responding when i click minimize on the plugin

**Comment by Spekular** [comment] 2021-08-18 13:10
Can you test if this still occurs in the alpha version?

**Comment by Lxg3nD** [comment] 2021-08-18 17:49
so far no problem on the alpha

**Comment by Spekular** [comment] 2021-08-18 19:10
I'll close this for now then. Reply here again if it happens with the alpha and we'll reopen then :)

**Closed by Spekular** 2021-08-18 19:10 UTC
Labels: bug
