### ISSUE TITLE
'lmms' terminated by signal SIGSEGV 

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#6596] opened 2022-12-24 06:27 UTC
### Bug Summary
Basically every time I try and open LMMS it crashes and this is the error I get 

#### Steps to reproduce
Install LMMS on Linux

#### Affected LMMS versions
Latest from pacman repos.

**Comment by PhysSong** [comment] 2022-12-24 07:05
Possible duplicate of #6587.

**Comment by PhysSong** [comment] 2023-01-06 13:05
@whatthemaggie Can you check if the workaround from #6587 work for you?

**Closed** 2023-05-06 04:12 UTC
Labels: bug, response required
