### ISSUE TITLE
RC5 inWin10x64 retarding system & many CMD in taskmanager

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#4117] opened 2018-01-16 12:07 UTC
LMMS RC5 doesn't crush unlike the previous RCs but retarding system In Win10x64 on i3/4GbRAM very hard! CPU usage reaches 90%. If expand LMMS branch In taskmanager may to see there are many running CMDLine processes. Is it right?

**Comment by tresf** [comment] 2018-01-16 13:26
Crush what exactly?  Can you show evidence that "Many running CMDLine process" have derived from LMMS?

**Comment by NETMANSKY** [comment] 2018-01-16 19:25
![12](https://user-images.githubusercontent.com/14283492/35007936-109bd9e8-fb0c-11e7-8b0c-28add179ddb4.png)
![13](https://user-images.githubusercontent.com/14283492/35007937-10e86dc6-fb0c-11e7-8dc4-b838e2bc14f4.png)
![14](https://user-images.githubusercontent.com/14283492/35007938-111a42ec-fb0c-11e7-8fa0-76c61c1de875.png)

**Comment by NETMANSKY** [comment] 2018-01-16 19:28
![15](https://user-images.githubusercontent.com/14283492/35008143-9be919ca-fb0c-11e7-99f8-50b1a2889be8.png)

**Comment by NETMANSKY** [comment] 2018-01-16 19:31
As you see LMMS playback. In prevouse RC it wasn't

**Comment by NETMANSKY** [comment] 2018-01-16 19:31
CMDlines

**Comment by tresf** [comment] 2018-01-17 15:25
@NETMANSKY thanks for sharing.  Do you have your VSTs located inside a folder with non-ANSI characters?  This may be a duplicate of #2662.  The `Console Window Host` would then be a bug with the way the path is fed into LMMS.  Can you tell us the name of the folder that contains the VSTs?

**Comment by DomClark** [comment] 2018-01-17 16:43
The `Console Window Host` is actually a child process of `RemoteVstPlugin(32).exe` (or `RemoteZynAddSubFx.exe`) - the Windows Task Manager doesn't show the relationships in that much detail, but here's a screenshot from Process Hacker:
![conhost](https://user-images.githubusercontent.com/1873225/35053425-f6ff0f32-fba1-11e7-8cc8-032ec3da36f1.png)
The purpose of the process is to provide console handling for processes target at the Windows CUI subsystem (as opposed to the GUI subsystem), and it starts automatically along with the parent process. Since `RemoteVstPlugin` hardly uses the console, only printing the occasional debug message, they shouldn't be using many resources at all despite the large quantity of them. So, yes, this behaviour is normal, and from your screenshot, it seems that LMMS itself is the main culprit for CPU usage (although your RAM usage also appears to be rather high so perhaps there's a lot of paging going on, but I can't really comment on the extent of the effect that would have).

As for why the remote plugins are built for the CUI, I'm not really sure; I've tried changing them to be GUI processes and everything behaves exactly the same.

**Comment by NETMANSKY** [comment] 2018-01-17 18:14
@tresf As I understood LMMS 1.2.x support recursive view of folder. This feature allows to place VSTs in a different folders of parent folder. My parent VST folder is %HOME%vst\... All characters created in Latin code but not Cyrillic or another code. Home folder name has Latin characters too.

**Comment by NETMANSKY** [comment] 2018-01-17 18:20
Similar projects in Reaper don't slow down my system. Yeah, they launching longer but not overloading :(

**Comment by NETMANSKY** [comment] 2018-01-23 07:14
Continued now! I launch LMMS by CMD to kill remotevst before and after work because sometime they hanging in memory after LMMS is closed. And now in work LMMS broke left channel and after I closed LMMs there appeared this picture (attached). LMMS hanged...
![16](https://user-images.githubusercontent.com/14283492/35262551-2b56209e-0026-11e8-94dd-71f97f994dbd.png)

**Closed** 2018-09-11 13:01 UTC
