### ISSUE TITLE
Windows MiDi selection

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#2622] opened 2016-02-29 19:54 UTC
i found what was wrong with midi
the midi selection interface must be set for each instrument right now in w10 rc2
![lmms 3](https://cloud.githubusercontent.com/assets/2557665/13406836/a2fa2720-df36-11e5-880f-26fee108f423.png)
i propose to move it into settings and set as default for all current devices
and if user wants he can set it manually for each channel, so this menu will stay there,
but just add another one maybe looking like this
![lmms 4](https://cloud.githubusercontent.com/assets/2557665/13407004/71493404-df37-11e5-8d32-06aa2c72084d.png)

**Comment by tresf** [comment] 2016-02-29 19:57
Duplicate of  #1189 #1781 #1918 #1942.

**Closed by tresf** 2016-02-29 19:57 UTC
