### ISSUE TITLE
Turn Autosave ON by default (and some other improvements)

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#181] opened 2014-01-28 01:01 UTC
Simple as that.

I guess no user will be happy for saving extra 100 kB of disk for the cost of loosing extra 5 hours of work ;)

Make Autosave Feature ON by default!

And if you can - make it also save w few files, and prevent it from overwriting (without a warning!) itself when having two or three instances open. Every instance could have a random session ID and save the autosave files with this session-ID prefix like:

```
 57567-recovery-01.mmpz
 57567-recovery-02.mmpz
 57567-recovery-03.mmpz
 96817-recovery-01.mmpz
 57567-recovery-02.mmpz
 12422-recovery-01.mmpz
 29500-recovery-01.mmpz
```

Also a dedicated folder for autosave files could be nice, and a button for opening file browser in that directory would be great too.

**Comment by unfa** [comment] 2015-03-30 20:15
Or maybe the autosave can be handled by a separate thread, that operates on low priority (high nice value) so that it won't block DSP processing during playback?

**Comment by softrabbit** [comment] 2015-03-30 20:23
Autosave _is_ disabled during playback, right? https://github.com/LMMS/lmms/blob/master/src/gui/MainWindow.cpp#L1343

**Comment by musikBear** [comment] 2015-03-31 10:38
> Autosave is disabled during playback, right?

autosave should be disabled in all situations except idle. And definitively be optional.
If autosave kicks in as you are moving a block in edit-mode, The block 'drops' off, In automation editor, you draw wrong. It is completely annoying, and **must** be optional, also a user time setting for like 5, 10, 15, 30 mins between autosave, would be advice able - *But* !!
*Definitively optional* as it is now 
I think a tiny icon in main bar, just flashing a couple of times, would be better, then the user has the choice to do a version save, or a regular save, or nothing.
Here are autosave profiles for cpu usage (0.4.9 i believe it was.. Toby gracefully gave me a exe where it was disabled, then it became optional)
![spikedrecoversavewithmanualtask](https://cloud.githubusercontent.com/assets/6662066/6917197/b894d0fe-d7a2-11e4-9b6c-fedf6b60f122.jpg)

**Comment by Sti2nd** [comment] 2015-03-31 15:43
Wait, what is wrong with using your processor again?

**Comment by musikBear** [comment] 2015-04-04 14:27
@Sti2nd  -you are right, nothing wrong with that, but (on my system at least) this process results in lmms un-responsiveness, and a break in the functionality for ~1-2 secd -Thats the bad thing, about it, but i have a new angle on this, i just have to formulate this new proposal for a new kind of autosave.

**Comment by musikBear** [comment] 2015-07-08 11:00
I have redone the auto v manual saving on @Umcaruje Master of 01.07.15
![recovervauto](https://cloud.githubusercontent.com/assets/6662066/8568625/add5ea84-256f-11e5-8971-598e7b754ff0.PNG)
there is still quite some usage, and also influence on the work being done in lmms at the time of auto-save-event.
imho autosave takes place far to often
Other programs auto-backup every 5-10 min
But again: Why not make this a user option ?
Another quite strange decision is to use the name '*recover.mmp*' 
Why is the recover-file-name, not a string-concat of the  hardcoded  string 'recover' **and** the user project-name
So 'MyProject.mmpz' is saved as recover-files as **MyProject_recover.mmp**
Users **are loosing the recover.mmp**, because they try to open a new file, after a fail, and then the recover-feature is useless
Recover need to be 
* user-optional like 1..20 minutes
* preserved as a concat-named string
If it should be a real fail-safe

**Comment by Spekular** [comment] 2015-07-08 20:49
+1 for thise suggestions.

**Comment by zonkmachine** [comment] 2015-07-19 02:13
I've fixed some of the issues mentioned in this thread. Nothing merged yet though.
Work done here #2176 

> Or maybe the autosave can be handled by a separate thread, that operates on low priority (high nice value) so that it won't block DSP processing during playback?

:+1:  I don't know how problematic it is though considering that we're multi platform and here we have to call the OS directly so this would probably be done differently depending on what OS we're working against. And I suck on OS's. I basically use my mouse to whack the computer...
@musikBear I don't think just watching the CPU usage history tells us that much. If you install BOINC which is a system that let's you lend your free CPU time to render projects online and now watch your usage you will see it just flat out at max ( or whatever percentage you allow it to ) but you won't notice any difference in how the computer behaves. This is because the processes are run at a very low priority. See unfas comment above.

**Comment by musikBear** [comment] 2015-07-19 11:05
@zonkmachine no the measures are more empiric, eg comparing prior to current. I can however tell you that in the case of autosave in lmms, there has always been a serious connection to usability and lag. Back when autosave first was implemented, the lag was so awful that it was impossible to do editing (I got a lot on that story, because Toby extremely kindly made me a special .exe back then :)

**Comment by zonkmachine** [comment] 2015-07-19 13:48
I trust you all on the "it's been bad" part. I haven't actually used autosave myself until now. I also haven't addressed any of the problems concerning performance when the autosave kicks in but I can see it can be a bit of a problem to fix. The autosave needs to take a snapshot of a project before it changes so it has to work hard and fast. Someone who has really big projects like Unfa will be most impactd. Maybe we need different priority levels of autosave. First a low priority one that  will try and save a couple of times with low priority to not interfere at all and then after failing too many times hands over to the big bad 'now we really need to save this' function to finish the job.

**Comment by tresf** [comment] 2015-07-19 14:01
If you're using signals and slots to set priority: http://doc.qt.io/qt-4.8/qthread.html#Priority-enum

There are several places in our code which are fired by a particular priority and should be lowered (or raised).  

Here's a good conversation on it:

https://github.com/LMMS/lmms/issues/1600#issuecomment-69928753

-Tres

**Comment by zonkmachine** [comment] 2016-01-20 23:11
> If you're using signals and slots to set priority: http://doc.qt.io/qt-4.8/qthread.html#Priority-enum
> 
> There are several places in our code which are fired by a particular priority and should be lowered (or raised).
> 
> Here's a good conversation on it: #1600 (comment)

Thanks! I'll look into this. For the auto save I think running it on a low priority means you'd need some method to counter for when the project is modified while a save is going on. Something like two saves and a successful compare of checksums equals a new recoverfile.

> If autosave kicks in as you are moving a block in edit-mode, The block 'drops' off, In automation editor, you draw wrong.

@musikBear I don't see this. Do you still get this?


I've started optimising the logic of the auto save here #2512 to see if I can counter possible performance issues.

**Comment by musikBear** [comment] 2016-01-21 17:48
@zonkmachine Autosave will still make the pc 'hang' for a few seconds. The event looks like this
![recoverspikes1_1_3_1](https://cloud.githubusercontent.com/assets/6662066/12488718/483c6970-c06d-11e5-9f71-c4e065f66e47.png)
on your binary g23d2824.
Yellow is a manual save, the two red are autosaves
But imo the worst problem is that autosave still overwrites 'recover.mmp'. The idea about having a timestamp, or similar concatenations, added to the filename, has not been implemented. eg #2174 #2176 has been closed without fix.

**Comment by zonkmachine** [comment] 2016-01-21 18:28
> Yellow is a manual save, the two red are autosaves

Yes. But what about when you drag something and the autosave kicks in?


> But imo the worst problem is that autosave still overwrites 'recover.mmp'. The idea about having a timestamp, or similar concatenations, added to the filename, has not been implemented. eg #2174 #2176 has been closed without fix.

#2174 was closed as what I perceived as the main cause of that particular issue was that LMMS didn't warn before closing and deleting a recovered project and this was fixed. The rest of that issue is covered here already. #2176 was closed as it was a good place to stop. Many bug fixes and I've explained it in the first post of that issue. For now I'm into performance issues only. Multiple save files will have to wait but will probably come true around 1.3

> on your binary g23d2824.

I don't know this one. Link?

**Comment by musikBear** [comment] 2016-01-22 12:20
> Yes. But what about when you drag something and the autosave kicks in?

yes, and all other running programs are heavily influenced too
> For now I'm into performance issues only

Understood
> I don't know this one. Link?

Its your repository that Tresf made into a windows binary. I thought it was your id-stamp tresf used. I have no idea what the id-stamp covers, though 8|

**Comment by grejppi** [comment] 2016-01-22 13:14
23d2824 is the commit that build was made from.

**Comment by zonkmachine** [comment] 2016-01-22 16:54
> yes, and all other running programs are heavily influenced too

#2512 should make your work in lmms be less affected by the autosave, but for the case where other applications are affected that's not something I can fix easily.
You could try something like: http://www.wikihow.com/Change-Process-Priorities-in-Windows-Task-Manager and run LMMS in it's entirety on a lower priority but I've never done this in Windows and I don't know how the saves could be compromised by this.


> 23d2824 is the commit that build was made from.

Thanks! I thought searching a commit hash was the thing but you're apparently supposed to use it a s a link directly.

**Comment by musikBear** [comment] 2016-02-10 10:31
Following 2512 with high interest, because fail-save is an important feature. If i understand correctly @zonkmachine  *you* have managed to omit autosave events during editing, and an autosave will only happen, if lmms is truly idle. I like that! :+1: 
There are still things that need to be 'fixed' Especially concatenated saving-names, and a user scheduled time-interval between each autosave, and then it properly wont be an issue any more at all, because a tiny delay every 5 mins or so, is not a big deal. Word also flashes a short 'Please wait' as it autosave :p 
I cant resist making one of my, for some, notorious stupid input,  alternative thinking imo :p 
So.. **In case** autosave never reach a reasonable usability: 
Autosave could be omitted, and replaced by a tiny red diode, that simply would start to flash, after a user-set period of time, just *telling* the user, that a *manual* save would be a wise thing to do.

**Comment by zonkmachine** [comment] 2016-02-10 14:07
> If autosave kicks in as you are moving a block in edit-mode, The block 'drops' off, In automation editor,
> you draw wrong.?

Sorry, I didn't get your answer to this so I ask again. Do you drop still drop things? Yes/No

> @zonkmachine you have managed to omit autosave events during editing, and an autosave will only happen, if lmms is truly idle. I like that! :+1:

Auto saves already will happen only when lmms is idle. It's just more likely to be idle when you press the stop button so I force a save there. The problem is that (a) these are workarounds for the ineffective saves and not real fixes, and (b) The auto save function is getting a bit over complex under my care.

**Comment by musikBear** [comment] 2016-02-11 15:13
> The auto save function is getting a bit over complex under my care.

I think you done fine. Placing an auto-save event just after pressing *stop* is good, imo.

> Do you still drop things? Yes/No
@zonkmachine 

Yes, when i wrote *no difference* that was also for the dragging of a block ao. drawing in automation. Incidentally, any *other* proggie running, will also do a 'hickup' 
I have a *cracy* idea, that im going to fiddle with tonight at home, but thats propl. just one of my *usuals*
In short: What happens if **mmpz** is chosen.

**Comment by zonkmachine** [comment] 2016-09-11 07:42
#3032 I had a go at fixing recover files for multiple instances of LMMS. It's currently a bit rudimentary but working. Feedback, testing and ideas welcome. Here or there... :pig:

**Comment by jasp00** [comment] 2016-09-11 14:08
The solution to recover projects should be:

1. Fix the undo/redo system.
2. Save journal entries to disk as they are created, like a database, including undo/redo entries.
3. On recovery, replay the journal.

**Comment by zonkmachine** [comment] 2016-09-11 16:01
That makes sense but is probably not within my coding abilities. That would solve any performance issues discussed here previously, wouldn't it? How much work would that involve?
The undo/redo system should be fixed anyway so that's a separate post.

**Comment by jasp00** [comment] 2016-09-12 19:48
>That makes sense but is probably not within my coding abilities. That would solve any performance issues discussed here previously, wouldn't it? How much work would that involve?

You have the abilities, it is a matter of lots of free time.

**Comment by zonkmachine** [comment] 2017-02-01 16:10
> Make Autosave Feature ON by default!

As of c54171ba488e4798172e0f7f09edfe7d05e1bceb auto-save is on by default. The default behaviour is also to save while playing which can be disabled if you experience any issues with this.

Leave this issue open for now.

**Comment by Umcaruje** [comment] 2017-05-07 12:42
>As of c54171b auto-save is on by default. The default behaviour is also to save while playing which can be disabled if you experience any issues with this.

it seems that this is not the case anymore, it was probably changed again somewhere in the subsequent commits.

**Comment by zonkmachine** [comment] 2017-05-07 12:45
OK, I'll look into it.

**Comment by tresf** [comment] 2018-02-07 03:54
This was closed a while ago by https://github.com/LMMS/lmms/pull/3551.  Closing.

**Closed by tresf** 2018-02-07 03:54 UTC
Labels: enhancement, ux
