### ISSUE TITLE
better copy and pasting for song editor

### ISSUE THREAD

**Issue by sorath72** [LMMS/lmms#1698] opened 2015-01-27 00:09 UTC
I don't know if its me but when creating patterns in the song editor. You need to always have to copy little by little each and every single pattern. Why not the ability to stretch the patterns to make them repeat. Sellecting all of the song patterns and being about to paste them too would help allot. I noticed allot of people have been making there music in the song editor but can't seem to know how they copy and paste their entire song which a system that prevents you from selecting the entire patch of patterns created in the song editor. Is there a way to make it like the beat editor?

**Comment by tresf** [comment] 2015-01-27 02:18
Duplicate of #821.

Related: #1641 (Open)

**Comment by tresf** [comment] 2015-01-27 02:18
Our plan is to have this fixed in 1.2.  We'll have a beta out in a few weeks.  Thanks for submitting!

**Closed by tresf** 2015-01-27 02:18 UTC
Labels: duplicate
