### ISSUE TITLE
Global Tempo Automation Failing with VSTs

### ISSUE THREAD

**Issue by OutbackMan** [LMMS/lmms#5319] opened 2019-11-12 23:59 UTC
#### Bug Summary
Creating a global tempo automation track causes silence and intermittent sounds to be played for VSTs.
Based off discussion from: [LMMS Forum Support](https://www.lmms.io/forum/viewtopic.php?t=31041)

#### Steps to reproduce

1. Download a VST, e.g. [Spitefire LABS VSTs](https://www.spitfireaudio.com/labs)
2. Insert a series of notes using the piano roll with this VST. It is easier to hear the effects of the tempo automation if using short repeated notes, e.g 16th notes, however any note length will work.
3. Create a global tempo automation track whose line follows that of a 'mountain', e.g. a curve that goes up and down.

#### Expected behavior
The tempo of the notes played slowly increases until time reaches the maximum point of the automation curve at which **the tempo of the notes slowly decreases**. The tempo of the notes played steadies when the automation curve is a flat line.

#### Actual behavior
The tempo of the notes played slowly increases until time reaches the maximum point of the automation curve at which **silence is mostly heard, with intermittent notes played**. The tempo of the notes played steadies when the automation curve is a flat line.

#### Screenshot
![JJKs8cd](https://user-images.githubusercontent.com/32256825/68720732-58f04a80-0604-11ea-82e2-e146d1728b0a.png)

#### LMMS version used
Windows x64 1.2.1

**Comment by PhysSong** [comment] 2019-11-13 00:40
Possibly related: #3775

**Comment by Spekular** [comment] 2019-11-13 08:28
There's also #5122 and #3640.

**Comment by DomClark** [comment] 2019-11-15 21:54
Reproduced. I'm fairly sure this is a duplicate of #5122. I intend to fix that issue soon, and will reopen this issue if that doesn't fix it.

**Closed by DomClark** 2019-11-15 21:54 UTC
Labels: bug
