### ISSUE TITLE
Custom/Multiple sample directories

### ISSUE THREAD

**Issue by hellocatfood** [LMMS/lmms#4524] opened 2018-08-05 23:18 UTC
According to the LMMS wiki the only way to add a folder of samples is to copy the samples to the "My Samples" folder location. On Ubuntu Linux this is /usr/share/lmms/samples or /$LMMSLOCATION/lmms/samples.

To avoid forcing the user to move/copy files to a new location can there be an option to specify custom locations to search for samples? Or, a user could drag a folder onto the sidebar and it'll be added as a browsable tab.

**Comment by PhysSong** [comment] 2018-08-06 02:09
> can there be an option to specify custom locations to search for samples?

There's no sample-specific one. You can change `LMMS working directory`, but it will change the default project path and some more things.
I don't know what you exactly want. Is that about browsing or search paths? If you mean browsing issue, that's covered by #1043. The search path issue is covered by #4309, too.

**Comment by musikBear** [comment] 2018-08-06 14:41
@PhysSong > I don't know what you exactly want

He want that he could make a list over folders, that lmms should browse and create a combined overview in **Samples**.
I understand the need.
Its really a duplicate of 
* Allow several sample paths (#2842)*
Imagine you have several programs, that can use samples. Lets say we have 5 folders in total, that does contain samples.
He want lmms to be able to use everyone, and any any samples in all 5, even though 4 of these folders are on other partitions, than lmms. Its a sane request, because it removes the need for duplicate samples.
This also has connection to searching for missing samples on the hd
So related to Meta #4309

**Comment by hellocatfood** [comment] 2018-08-06 17:57
@musikBear thanks for understanding and sorry for the duplication.

If something like this were to be implemented could the additional sample paths be set per project rather than globally?

With regards to tabs in the sidebar I was thinking it could eventually look something like this

![bitmap](https://user-images.githubusercontent.com/151947/43732798-7f295786-99aa-11e8-81c4-bbfbb58e46a5.png)

**Comment by lukas-w** [comment] 2019-03-09 18:21
Closing as part of #4309.

**Closed by lukas-w** 2019-03-09 18:21 UTC
Labels: duplicate
