### ISSUE TITLE
Including samples in project files

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5647] opened 2020-08-18 09:09 UTC
Every time I download some project from internet, there's something like missing sample error, to make projects easier to share, I would include packing them down with project file...

**Comment by Spekular** [comment] 2020-08-18 09:13
Duplicate of #4922. Last warning.

**Closed by Spekular** 2020-08-18 09:13 UTC
Labels: enhancement

**Comment by mnini** [comment] 2021-06-28 18:12
It's down 1000 issues, and github doesn't support fulltext search.
