### ISSUE TITLE
Spacebar quantises current closed piano clip

### ISSUE THREAD

**Issue by Madadog** [LMMS/lmms#6657] opened 2023-02-27 04:56 UTC
### Bug Summary
Pressing 'space' causes unexpected quantization on piano roll clips under specific circumstances.

#### Steps to reproduce
1. Create a piano roll clip with notes in some quantization (e.g. 1/16)
![Screenshot_20230227_111736_sequence](https://user-images.githubusercontent.com/53168336/221451071-d7643edc-a1cf-4d56-8d7f-4a90335af031.png)
2. Pick a lower quantization value (e.g. 1/8)
3. Close the piano roll window via the X in the corner, then press the spacebar (do not select any other windows (e.g. Song-Editor, Mixer, etc)).

The clip will now be quantized.
![Screenshot_20230227_111843_sequence_after2](https://user-images.githubusercontent.com/53168336/221451639-7918d143-dff5-421a-8d2b-28e10c4e0302.png)

Notably, clicking any other windows (Song-Editor, Mixer, BB editor, etc) or the background of LMMS after closing the piano roll window will stop this bug, causing spacebar to play/pause/do nothing as expected, at least until the piano roll window is closed again.

#### Expected behavior
Spacebar should either do nothing or play/pause the whole track.

#### Affected LMMS versions
This occurs on version `lmms-1.3.0-alpha.1.184+g3964c53a0-linux-x86_64` and on the current master `lmms-1.3.0-alpha.1.277+g2baa23ee1-linux-x86_64`.
It does not occur on stable (lmms-1.2.2)

**Comment by Spekular** [comment] 2023-02-27 07:06
Duplicate of #6260.

**Closed by Spekular** 2023-02-27 07:06 UTC
Labels: bug
