### ISSUE TITLE
Make Native Instruments don't click

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#4945] opened 2019-04-14 11:52 UTC
So speaking of LMMS compared to other DAWS (here i speak about FL), i've seen that Native Istruments (so like Triple Oscillator, Organic and so) clicks and to avoid that, you need to adjust envelope that, for beginners, could be difficult and make them thinking LMMS is not a good DAW and choosing something other even if LMMS is awesome (that's a very well-known problem for beginners as i know). In FL, native instruments when played don't click.

Envelope should be touched only on a specific purpose for changing the sound not everytime to avoid clicks. So in my opinion when Envelope should be active by default with this settings
![Cattura](https://user-images.githubusercontent.com/40141826/56092430-51c15c80-5ebc-11e9-9625-54f1f5568744.PNG)

What do you think about it?
Thanks

P.S: Oh, and this is works for samples as well

**Comment by Spekular** [comment] 2019-04-14 13:38
Duplicate of #3086.

**Comment by musikBear** [comment] 2019-04-14 15:55
*much* older duplicate than 3086 : #2092

**Closed** 2019-04-15 01:40 UTC
