### ISSUE TITLE
The "master pitch control" doesn't work all the time.

### ISSUE THREAD

**Issue by Hussam-Eddin-Alhomsi** [LMMS/lmms#3580] opened 2017-05-27 22:57 UTC
I have a _sample track_ and an _instrument plug-in track_ in a normal LMMS project.
The **MASTER PITCH** control in **GENERAL SETTINGS** > **MISC** is off by default for both of them, but it doesn't do its job. Both are getting affected by the **master pitch** slider when I change it. I tried turning the control on and off but that doesn't seem to have an effect.
It worked once with an _instrument plug-in track_, but I wasn't able to make work another time.

**Comment by Hussam-Eddin-Alhomsi** [comment] 2017-05-27 23:00
.

**Comment by Hussam-Eddin-Alhomsi** [comment] 2017-05-27 23:02
Closed the issue by mistake.

**Comment by zonkmachine** [comment] 2017-05-28 00:41
I believe this is a duplicate of https://github.com/LMMS/lmms/issues/2612

**Comment by Umcaruje** [comment] 2017-05-28 11:00
Duplicate of #2612

**Closed by Umcaruje** 2017-05-28 11:00 UTC
