### ISSUE TITLE
File Registration Handler failed to Auto open unicode named *.mmpz file under Windows 10

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6030] opened 2021-05-26 01:51 UTC
If you save the file in unicode characters (at least: in devnagari unicode names), the file handler won't open the .mmpz file.
If filename or folder name has unicode characters, it denies to open when you double click the lmms .mmpz file.

But If you open the software and open the file manually, it works normally.

#### Expected behavior
Clicking on **<unicode-name>.mmpz** should open the the LMMS software with the selected file pre-open within the software.
My OS: Windows 10
LMMS: 1.3 nightly build

**Comment by PhysSong** [comment] 2021-05-26 02:16
Duplicate of #5178.

**Closed by PhysSong** 2021-05-26 02:16 UTC
Labels: bug
