### ISSUE TITLE
write load-errors to a file

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2400] opened 2015-10-05 10:21 UTC
I tried to fix a users project, and in that process i had this
![lmmserrorreport](https://cloud.githubusercontent.com/assets/6662066/10278130/1c2da112-6b5b-11e5-9391-0b2e2f40bb95.png)
That information could be useful in a text-file too.
I doubt there is any reason for unique name, so it could just be a single file that was overwritten, every time a load error occurred.

**Comment by Umcaruje** [comment] 2015-10-11 19:17
@musikBear please clarify this issue or I'll close it.

**Comment by tresf** [comment] 2015-10-11 23:18
This is really about getting stdout/stderr on Windows working without launching from something like msys/cygwin, which I think was originally part of the "better debugging" initiative but this particular enhancement lost focus.

In other words, pipe the output to a file, except on CMD/Win, since stdout isn't working yet.

**Comment by musikBear** [comment] 2015-10-12 11:18
yes piping, either to a file, or to user clipboard, then user has the small task to insert the clipboard content into a file of his own choice, or just use the 'notepad'-feature inside lmms. I think clipboard is simpler than file-handling (?) or..

**Comment by tresf** [comment] 2015-10-12 21:16
Duplicate of your own bug report https://github.com/LMMS/lmms/issues/2177

**Comment by musikBear** [comment] 2015-10-13 11:24
nae.. it is not :p 2177 is about the previous anonymous and useless vst crash message
'a vst failed to load'
This is already fixed, as seen in the image (in fact i would close 2177 because of that?)
The anonymous message are replaced with good solid useful information. 
I *here* suggest the info could be useful as text string, and advise two different implementation: Filepipe or clipboard

**Comment by tresf** [comment] 2015-10-13 14:39
Fine, closed #2177 per request.  Moving my comments from there to here because they are relevant here, since you want copy-able text output.

Another stop-gap solution may be to simply make this alert dialog have selectable text.

> Yes, better overall windows debugging in general is what we need.
>
> This is a two-step process...
>
> * First is making a separate debug installer downloadable for our users.
> * Second is finding (and documenting) a way to capture the debug symbols on Windows so that they can be provided in a bug report.
>
> Another item that would help this is to get lmms compiling on Windows **edit:** [it compiles per our tutorial but debug builds are still broken](https://github.com/lmms/lmms/wiki/Compiling-lmms-(on-Windows)).

**Comment by tresf** [comment] 2015-10-16 13:17
Here's an article about a hack to make a Windows GUI application write to the console:

https://gist.github.com/tresf/b13d1aadc2db80742a8a

**Comment by tresf** [comment] 2015-10-16 17:28
@musikBear you can copy these now, just use your mouse.  Closing as invalid.

![image](https://cloud.githubusercontent.com/assets/6345473/10548569/bfaf5716-7409-11e5-94e8-9bf933b4e73e.png)

**Closed by tresf** 2015-10-16 17:28 UTC
Labels: needs clarification
