### ISSUE TITLE
ZynAddSubFx show gui freeze lmms

### ISSUE THREAD

**Issue by Animtim** [LMMS/lmms#1760] opened 2015-02-11 22:07 UTC
Trying to show the gui of ZynAddSubFx freeze lmms, with this error:
 /usr/bin/../lib64/lmms//RemoteZynAddSubFx: error while loading shared libraries: libZynAddSubFxCore.so: cannot open shared object file: No such file or directory

But of course /usr/lib64/lmms/libZynAddSubFxCore.so is here, so I don't know why it can't see it..

On Mageia 5 beta, lmms 1.1.2 (I updated the spec, builds not yet in the repo.. regular build except  -Werror is disabled..)

**Comment by curlymorphic** [comment] 2015-02-11 22:59
Ive tried this on ubuntu 14.10 and can't reproduce this.

Steps taken

1 git clone -b stable-1.1 https://github.com/LMMS/lmms.git.
2 git log, to check this contains commits for 1.1.2
3. build and run on local machine.
4. added Zyn instrument
5. click show GUI
6. observed the GUI opened normally

hope this is of some use.

**Comment by tresf** [comment] 2015-02-26 13:56
Likely a duplicate of #1758.  Let's track this bug together there so that we can work together on identifying the problem as well as the solution. :+1:

**Closed by tresf** 2015-02-26 13:56 UTC
Labels: duplicate
