### ISSUE TITLE
Audio File Processor crashes LMMS when Automation track makes Loopback Point > Endpoint

### ISSUE THREAD

**Issue by FigyTuna** [LMMS/lmms#4773] opened 2019-01-15 06:41 UTC
**System Info:** LMMS 1.1.3 from apt on Ubuntu 18.04.1 LTS

**Description:** LMMS crashes when, I assume, the Loopback Point is set to be greater than the Endpoint on an Audio File Processor (henceforth AFP). LMMS usually prevents this from happening but it seems that an automation track modifying either of those values gradually can still cause it to crash.

**Steps to reproduce:**
* Start LMMS.
* Open up this project file -> [bug.zip](https://github.com/LMMS/lmms/files/2758204/bug.zip). (Or recreate it by having an AFP with a sample loaded play a long note. On the AFP, Enable Loop, either kind of loop will do, and set the Loopback point to .5 or so. Add an automation track that brings the Endpoint from 1 to 0 over the course of the playing note using a Cubic Hermite progression).
* When loading this file I often found that it would only crash if I manually brought the Loopback Point back up to about .5 on the AFP before playing.
* Click the main play button.
* If the program does not crash, bring the Loopback Point up again and retry. It usually happens after the second try.

**Expected results:** The Loopback Point should decrease automatically while the Endpoint is brought down, keeping it lower than the Endpoint.

**Actual results:** The expected results occur at first, then LMMS crashes.

**Additional Information:**
Doing the reverse (automating the Loopback Point to go above the Endpoint) either also crashed LMMS or resulted in LMMS hanging until I killed it.
It seems to be important that modifying these values with automation happens gradually, instantly changing them doesn't crash LMMS.
Adjusting the Loopback Points / Endpoints by hand does not crash LMMS.

**Comment by DouglasDGI** [comment] 2019-01-15 14:24
I reproduced this on 1.2 a few months ago.

**Comment by DomClark** [comment] 2019-01-15 15:50
Duplicate of #2149?

**Closed** 2019-01-15 20:42 UTC
