### ISSUE TITLE
VSTi plugins don't show in Subwindow on Qt5 build (probably only X11)

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#2855] opened 2016-06-16 13:11 UTC
![screenshot_20160616_145731](https://cloud.githubusercontent.com/assets/6502580/16117528/ebcd8316-33d2-11e6-8455-a5438f0f44eb.png)

Qt 5 bug:

the vst window will not be caught by the subwindow. With Qt4 we use QX11EmbedContainer for catching the vst window in our subwindow. QX11EmbedContainer is gone in Qt5. 

https://github.com/LMMS/lmms/blob/master/plugins/vst_base/VstPlugin.cpp#L228

```

#ifdef LMMS_BUILD_LINUX
    if( m_pluginWindowID == 0 )
    {
        return;
    }

    m_pluginWidget = new QWidget( _parent );
    m_pluginWidget->setFixedSize( m_pluginGeometry );
    m_pluginWidget->setWindowTitle( name() );
    if( _parent == NULL )
    {
        vstSubWin * sw = new vstSubWin(
                    gui->mainWindow()->workspace() );
        if( isEffect )
        {
            sw->setAttribute( Qt::WA_TranslucentBackground );
            sw->setWindowFlags( Qt::FramelessWindowHint );
            sw->setWidget( m_pluginWidget );
#if QT_VERSION < 0x050000
            QX11EmbedContainer * xe = new QX11EmbedContainer( sw );
            xe->embedClient( m_pluginWindowID );
            xe->setFixedSize( m_pluginGeometry );
            xe->show();
#endif
        } 
        else
        {
            sw->setWindowFlags( Qt::WindowCloseButtonHint );
            sw->setWidget( m_pluginWidget );

#if QT_VERSION < 0x050000
            QX11EmbedContainer * xe = new QX11EmbedContainer( sw );
            xe->embedClient( m_pluginWindowID );
            xe->setFixedSize( m_pluginGeometry );
            xe->move( 4, 24 );
            xe->show();
#endif
```

**Comment by tresf** [comment] 2016-07-05 23:10
May be a duplicate of this upstream bug:  https://bugreports.qt.io/browse/QTBUG-40320

**Closed** 2017-12-18 21:15 UTC
Labels: compatibility, gui, linux
