### ISSUE TITLE
Group the automation clips in the tracks

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4614] opened 2018-09-25 05:31 UTC
Hi guys. using lmms in my musical projects, in each track it had effects and many of those effects had to automate them, but then it filled the whole editor of automation clips, and everything looked messy and confusing. then I came up with the idea of suggesting that each track be a grouper of their own automations of their own effects (as happens in ardor more or less), and in that way the environment is more organized and easier to find the effects .

This is the current image of automations in lmms.
![antes agrupar automatizaciones](https://user-images.githubusercontent.com/26127693/45994128-4150ae00-c060-11e8-93a5-a5c4db2184fc.png)

In this project I barely have a track of a pad and several clips of automation, but imagine a project of professional degree full of clues and automations ?, It would be a total disorder and apart also makes lms more slow. my idea is more or less like this:

![despues agrupar automatizaciones](https://user-images.githubusercontent.com/26127693/45994242-b58b5180-c060-11e8-9c1d-6334a2ebc340.png)

As you can see, with the idea implemented, the projects would be ordered like this.
First, create an automation clip, then drag it with the mouse by pressing '' ctrl '' to the icon of the track where the assigned effect was, automatically when you drop the clip on the icon, this deployment arrow is created, when touching it, the tracks and automation clips of the editor are shown as of the menu, when closing it they hide.
I think it would be more orderly to have it like that. what do you think chichos. Blessings

**Comment by Spekular** [comment] 2018-09-25 06:36
Nit a bad idea, but seems like a duplicate of #735 to me.

**Comment by Gabrielxd195** [comment] 2018-09-25 06:43
I did not clearly understand what he said # 735 but I see both parents, the only thing that in his case, he did not suggest the arrow of the group, I do. And independently of whoever the idea is, lmms needs it, it's something basic that is needed.

**Comment by musikBear** [comment] 2018-09-25 14:31
Duplicate -this is about collapse-able / expandable tracks
eg  #735

**Comment by tresf** [comment] 2018-09-29 16:49
> Duplicate -this is about collapse-able / expandable tracks
> eg #735

👍

**Closed by tresf** 2018-09-29 16:49 UTC
