### ISSUE TITLE
Pasted pattern in the song editor sometimes don't show up

### ISSUE THREAD

**Issue by sorath72** [LMMS/lmms#5073] opened 2019-07-09 22:28 UTC
Well the thing is this. Everytime I try to copy and paste into the song editor. It will sometimes not always just sometimes not display or at least disapear a part of what I copied and pasted from the selected patterns. It seems to happen at random so I can't reproduce the bug as you need to really work on copy and pasting stuff in lmms in windows 10 to know what I mean here. I think it even happened to me when working on linux version too I think it was peppermint 10 and manjaro I tried it on before. IF anyone has this same anoying issue. Then thank you I am not alone. I just

**Comment by musikBear** [comment] 2019-07-10 12:43
It may 'just' be a graphical *glitch*
If it is, you should see the missing parts after you have *scrolled* the screen 
Also the *visual*-missing part should playback *normally*, even though you cant *see* them

**Comment by Sauerstoffdioxid** [comment] 2019-07-10 16:35
> It will sometimes not always just sometimes not display or at least disapear a part of what I copied and pasted from the selected patterns
Could You please specify this a little bit more? Does A) just a part of one copied pattern not show, or B) does the whole copied pattern disappear?
If A: That would sound somewhat like what musikBear described.
If B: I had it happening to me, that when dropping something onto the line of the current playback position, it wouldn't actually copy. Do you remember if this could be what happened to you too?

**Comment by noahb01** [comment] 2019-07-11 03:52
I have also intermittently seen this bug (latest master). When you ctrl-drag a pattern in the song editor, there is a small chance that it does not copy. Rather, it makes a blank pattern (the little gray box) somewhere random on the timeline (but always before the pattern you try to copy). Dragging the pattern around on the timeline and copying again always works and allows you to copy the pattern normally.

**Comment by musikBear** [comment] 2019-07-11 15:11
> I have also intermittently seen this bug

That is the drag with a thing like this. It is not reproduceable. 
Way back ..must have been in 1.0x (2015) i managed to record the odd behavior with a lousy cell-phone. *That* issue has never showed itself >1.1.3
But here is the strange short video:
https://www.youtube.com/watch?v=4U6EtpvfUcA

**Comment by sorath72** [comment] 2019-07-11 15:13
Yes its exactly like what musikbear described about that the pattern doesn't copy itself but will always put a gray or black box on the start of the pattern copied. Its like it doesn't retain what you copy in memory maybe? It happens multiple times on the same track for me until I go and do another track and then its fine. Its like not reproduceable like musikbear says but it is a pain when working on songs and ctrl select and then paste doesn't work on a certain pattern. Sometimes it will happen when I copy a entire few track patterns and then one of them will ether show up as a gray box like it happened to me once and sometimes it won't copy everything you selected.

**Comment by DomClark** [comment] 2020-06-13 22:25
Duplicate of #3964

**Closed by DomClark** 2020-06-13 22:25 UTC
