### ISSUE TITLE
Automatization copy loses a connection

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#4409] opened 2018-06-07 21:26 UTC
If you copy an automatization pattern by dragging then all connections are losing.

**Comment by DomClark** [comment] 2018-06-07 21:28
Sounds like a duplicate of #3781.

**Comment by Sawuare** [comment] 2018-06-07 21:39
> Sounds like a duplicate of #3781.

It is.

**Closed by Sawuare** 2018-06-07 21:39 UTC
