### ISSUE TITLE
AFP playback speed knob

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2345] opened 2015-09-12 16:06 UTC
The AFP could use a playback speed knob. What is the playback speed knob, It slows down or speeds up the sample playback and drops or highers the pitch by the same amount.  The pitch knob of the AFP is not affected this more for recreating the when in the old days when someone would take the tape machine and record at one speed and then play it back at another speed.

**Comment by tresf** [comment] 2015-09-12 16:11
Duplicate of #1466, #1794.  Stop polluting our tracker.

**Closed by tresf** 2015-09-12 16:11 UTC

**Comment by Reaper10** [comment] 2015-09-12 16:17
Should I just add this to new tape machine plugin #1794 ?

**Comment by tresf** [comment] 2015-09-12 16:47
GET OUT
