### ISSUE TITLE
Marked notes bleed into note velocity

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6807] opened 2023-08-13 05:04 UTC
### Bug Summary
One row of marked notes in the piano roll bleed into the velocity editor for notes

#### Steps to reproduce
Mark notes either manually or using the Scale setting feature, and scroll so that a marked note is at the top of where the velocity section is
#### Expected behavior
it doesn't, like it did before
#### Screenshot
![image](https://github.com/LMMS/lmms/assets/65266122/5b08299e-3742-4510-bdb6-dda630fa24f3)

#### Affected LMMS versions
ge87d44b42

**Comment by musikBear** [comment] 2023-08-13 15:29
> One row of marked notes in the piano roll bleed into the velocity editor for notes

If you mean that you can see what notes are selected because the velocity bars get coloured blue, then it is VERY much pr design!
It is an important feature that make you separate marked notes, and also set identical velocity through marking. It is anything but a bug, it is a much needed feature.
See https://www.youtube.com/watch?v=ldMf5RURxGA&list=PLMvza7ri1L0eduljUjLSsXRvIJ8rD8Ohs&index=27&pp=gAQBiAQB

**Comment by SalutanisOrkonus** [comment] 2023-08-13 15:38
I'm not talking about the selected notes, I'm talking about the marked scale (the light grey piano roll sections) now overlapping with the velocity section in a recent update
![image](https://github.com/LMMS/lmms/assets/65266122/62df031c-fbc8-4103-9f38-5b8f7eed83b6)

**Comment by Veratil** [comment] 2023-08-13 15:52
Can you share which scale and such you're using so we can easily reproduce it, too? Will make it faster to find if it's just a simple off by one bug.

**Comment by SalutanisOrkonus** [comment] 2023-08-13 16:10
Seems to work with all scales, and also if you just mark a note manually.

**Comment by Veratil** [comment] 2023-08-13 16:26
It might be a result of changes from #6761. Thanks!

**Comment by zonkmachine** [comment] 2023-08-18 14:28
Fixed in #6812

**Closed by zonkmachine** 2023-08-18 14:28 UTC
Labels: bug, good first issue
