### ISSUE TITLE
1.0.92 Crash during chord arpeggio & playback

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#989] opened 2014-07-14 13:25 UTC
win 32xp 
http://snag.gy/2J65g.jpg
https://www.sendspace.com/file/qm0nsh
This file crash lmms almost emediately after you set arpeggio ON in the 3oc
I think its related to #985, but wheares 985 happen during 'stressy' mouse-moving of a note, and hence could be caused by either note-moving in piano-roll, or arpeggio-code, *this* crash is in normal use.
arpeggio is bugged

**Comment by tresf** [comment] 2015-11-02 14:19
> Hmm. This happens in master, not in stable-1.1.

The backtrace @grejppi provided and the original bug report conflict as they are from different branches.

Closing this specific bug out as invalid since no one else has been able to reproduce what @musikBear is reporting on the branch he was using at the time of bug creation.

That said, @grejppi's/@diizy's QVector research for the master branch is still relevant, so we may need to cross-reference some of the relevant comments in a future bug.

**Closed by tresf** 2015-11-02 14:19 UTC
Labels: bug, invalid
