### ISSUE TITLE
Can't reproduce a Sample Track from the "middle"

### ISSUE THREAD

**Issue by SimoneIervasi** [LMMS/lmms#2596] opened 2016-02-20 08:30 UTC
Hi! I don't know if this is properly a real issue. Every time i use a Sample Track in my projects (especially for Acapellas and vocals track), if i want to listen the sample file i have to play it from the beginning; e. g. in Audacity i can play the audio file from every point. I think this option would be very useful.
Thanks, Simone

![cattura](https://cloud.githubusercontent.com/assets/7381335/13195516/9fc49e20-d7b4-11e5-80a0-488413436fb9.PNG)

**Comment by Umcaruje** [comment] 2016-02-20 12:06
@SimoneIervasi please search the issue tracker before you post. 

Duplicate of #1471

**Closed by Umcaruje** 2016-02-20 12:06 UTC

**Comment by SimoneIervasi** [comment] 2016-02-20 12:42
@Umcaruje  Sorry 👍
