### ISSUE TITLE
Sound cuts off sometimes, performance issues (master branch)

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#643] opened 2014-04-24 21:22 UTC
I haven't pinpointed any likely cause, but this has only started happening recently (disclaimer: could also be caused by some plugin I'm using, not necessarily a recent commit).

Usually seems to only happen when the CPU usage is high, always while playing back a project. The sound plays normally, then suddenly all output cuts off. It shows up in the mixer as well - master channel goes blank, while others still show output. There's no output on the commandline, LMMS doesn't crash nor hang.

This is with ALSA backend, haven't tested on other backends yet.

I'll see if I can come up with a test project that could replicate this issue reliably...

**Comment by SecondFlight** [comment] 2019-03-12 13:25
This bug report isn't written in such a way as to be reproducible.

I realize that may be the nature of the bug, but as per the discussion on #1333 which was determined to be a duplicate of this, I'm not convinced this is actually a bug. The issue described in #1333 is consistent with the automatic disabling of plugins to save CPU.

We can't reproduce it with the report given, it might not be a bug in the first place, and this issue hasn't been reported since (or if it has, it hasn't been linked to this bug and will still be open elsewhere if we close it). I vote to close this issue.

I'll leave it open for the time being in case there are any objections.

**Closed** 2019-03-13 01:55 UTC
Labels: bug, core, performance
