### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by vktec** [LMMS/lmms#3838] opened 2017-09-28 19:52 UTC
When working with multiple monitors, it's really nice to be able to have one window on each monitor. For example, when working with Ardour, I tend to have the main window open on one monitor and the mixer on the other.

This is more of a wish for the future than anything else, since I don't expect it will be easy to separate LMMS' single-window interface into multiple bits, but I thought it would be worth suggesting.

**Comment by lukas-w** [comment] 2017-09-28 19:59
We already have an issue for this, so I'm closing this is a duplicate of #1259. Also, see #3532 for a PR that tries to improve the situation. It'll probably make it into 1.3.

**Closed by lukas-w** 2017-09-28 19:59 UTC

**Comment by vktec** [comment] 2017-09-28 20:03
Excellent! Thanks @lukas-w.
