### ISSUE TITLE
Scrolls to playhead start when autoscroll disabled

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1735] opened 2015-02-02 14:53 UTC
**Edited @tresf per @Sti2nd Feb 2nd**

Steps to reproduce

 1. Go to Piano Roll and disable autoscroll
 2. Scroll the window to the right, so that the playhead cannot be seen.
 3. Start and stop

---
cant explain this in text, so 
 http://youtu.be/H6ftZ2Jfaek 
summerized, it shows that piano-roll scrolls toan illogical pos. in respect to the play-head-setting, and behavior.

**Comment by Sti2nd** [comment] 2015-02-02 20:45
First of all, the title must be more specific. Second, it is not hard to explain in text. "Window scrolls to where playhead started even when autoscroll is disabled".

Steps to reproduce
* Go to Piano Roll and disable autoscroll
* Scroll the window to the right, so that the playhead cannot be seen.
* Start and stop

**Comment by tresf** [comment] 2015-02-06 23:43
I'm not sure this is valid... 

@musikBear what about the `After stopping keep position` setting?  Isn't that what you want?  Should we assume those that have autoscroll turn off want this to switch automagically?

![image](https://cloud.githubusercontent.com/assets/6345473/6089391/ee2b9744-ae2f-11e4-915b-2d74d8cc1650.png)

**Comment by musikBear** [comment] 2015-02-07 10:44
>what about the After stopping keep position setting? Isn't that what you want?

No, the demo shows a situation where i try to find the notes that goes **with a sequence of existing notes**, so i want playhead to go back to that pos where the existing notes *starts*
Iow - i want *view-posistion* to be *independent* of playhead-posistion, and that is exactly what **"After stopping, go back...."** option should do. The view-behavior, in this situation,  is not logical.
This is valid alright :p

**Comment by Sti2nd** [comment] 2015-02-07 10:53
Auto scrolling is turned off, so it is a littlebit strange indeed. Maybe three modes for the autoscroll button?

**Comment by tresf** [comment] 2015-02-07 14:01
@Sti2nd can you please explain?

**Comment by Sti2nd** [comment] 2015-02-07 14:04
The reason musikBear consider it a bug is because he turns of autoscrolling and then suspects that no autoscrolling will happen whatsoever, but that isn't the case, as he points out. When you stop the playhead, it scrolls to where it stops (dependent on the playhead mode)

**Comment by tresf** [comment] 2015-02-07 14:05
So the bug should be "autoscroll setting ignored when stop is pressed?"

**Comment by tresf** [comment] 2015-02-07 14:07
I'm still confused, doesn't the "after stopping keep position" remedy this?  What am I missing?  Do we just need saner defaults when auto-scroll is disabled?  Shall we assume people want the position marker changed when autoscroll is disabled?

**Comment by tresf** [comment] 2015-02-07 14:07
Or is this more of a matter that autoscroll off shouldn't ever change the viewport?

**Comment by Sti2nd** [comment] 2015-02-07 14:30
> So the bug should be "autoscroll setting ignored when stop is pressed?"

Yes.

**Comment by tresf** [comment] 2015-08-24 14:26
Closing as duplicate of meta-bug Better Playhead Auto-Scroll #2291.  Please feel free to comment here if needed.

**Closed by tresf** 2015-08-24 14:26 UTC

**Comment by Umcaruje** [comment] 2016-05-01 09:38
@midi-pascal could you take a look at this one? Its the same problem we had in your PR: 
>My opinion is that when autoscroll is off, the song editor should never scroll, in any case. What autoscroll really means is 'follow the playhead'. And as a user, when I turn it off, I expect that the song editor never scrolls back to where the playhead is, regardless of its behavior.

>>If the setting is one of the other two the song editor scrolls back to where it should (beginning of the song or to the time line respectively).

>The thing is, those buttons alter how the playhead behaves, and not the song editor. It should be independent.

**Comment by midi-pascal** [comment] 2016-05-01 09:45
@Umcaruje Sure. I will check this one.

**Comment by midi-pascal** [comment] 2016-05-01 13:21
@Umcaruje Very easy to fix this one: 1 line of code! :smile:

**Comment by midi-pascal** [comment] 2016-05-01 22:19
@Umcaruje Merge?

**Comment by Umcaruje** [comment] 2016-05-01 22:21
@midi-pascal make a PR?

**Comment by midi-pascal** [comment] 2016-05-01 23:33
@Umcaruje Oups! Done #2750 :wink:

**Comment by Umcaruje** [comment] 2016-05-02 10:40
Merged :+1: Amazing work @midi-pascal :beers:

**Comment by musikBear** [comment] 2016-05-03 08:36
@midi-pascal Big :cake: from dk.
