### ISSUE TITLE
Crash when cursor is over AFP

### ISSUE THREAD

**Issue by dullmachine** [LMMS/lmms#4091] opened 2018-01-04 18:48 UTC
When a sample is opened, if the cursor is over the blue area in AFP, LMMS will crash instantly.

Umcaruje backtrace: https://gist.github.com/Umcaruje/b47ba8b2764896135f9b537046d0580d

**Comment by tresf** [comment] 2018-01-04 19:21
This may be a duplicate of https://github.com/LMMS/lmms/issues/3926.

**Comment by PhysSong** [comment] 2018-01-04 23:52
Closing as a duplicate of #3926, since the backtrace says this is the same bug.

**Closed by PhysSong** 2018-01-04 23:52 UTC
