### ISSUE TITLE
License of aeffectx.h

### ISSUE THREAD

**Issue by grejppi** [LMMS/lmms#2797] opened 2016-05-24 23:07 UTC
This concern was recently raised on an IRC channel. The reverse engineered VST header from LMMS has become a popular alternative to the Steinberg SDK in the Linux audio community. However the license of it (GPLv2+) can be seen as too restrictive for a header file with such a wide utility.

@LMMS/developers, @jasp00, would you consider relicensing it under a more permissive license?

**Comment by jasp00** [comment] 2016-05-25 00:16
If a GPLv2+ header is popular and widely used, that means the license choice is a success. AFAIK, it is either this header or Steinberg SDK. The point of the header is to help free software; other projects (proprietary programs) can use Steinberg SDK. I would like to know which free projects need the relicensing; "more users" is not a reason to me.

Anyway, the initial header was derived from VeSTige (GPLv2+), which used code from (X)FST (GPLv2+) (copyright Paul Davis, Torben Hohn and Kjetil S. Matheussen). We tried to get a license exception to use Steinberg SDK without success, so I doubt relicensing is possible. Although someone else could reverse engineer [Airwave](https://github.com/phantom-code/airwave) to obtain a new header with a more permissive license.

**Comment by Wallacoloo** [comment] 2016-05-25 00:35
Not an author of that file, but as a user who's had to use hex editors on Linux audio software distributed in binary form in order to fix bugs, I am against any effort to relicense this.

This isn't *as* much of a concern here, since the header only contains structs and constant parameters - no methods or associated source files ([the header](https://github.com/LMMS/lmms/blob/master/include/aeffectx.h), for reference). So from a free software point of view, the user only really loses the ability to rearrange the struct fields or add/remove padding if this is licensed less restrictively. This would come into play if there are latent bugs caused by incorrect ordering of the fields as they stand today or if we're currently relying on undefined behavior that might break in the future - if this is the case, the user *may lose the ability to fix those problems*.

It's low risk, but I think it still warrants the need for a clear rationale - why would one want to relicense this (and who wants to)? Seems like relicensing is already out of the picture though anyway.

**Comment by falkTX** [comment] 2016-05-25 06:22
I have a small plugin framework that uses vestige, https://github.com/DISTRHO/DPF.
This framework has a very liberal license, which applies to ladspa, dssi and lv2 plugins.

This means plugins can be released under any license.
If building for VST though, the plugin ends up "upgrading" to GPL.

**Comment by jasp00** [comment] 2016-05-25 22:47
> If building for VST though, the plugin ends up "upgrading" to GPL.

Which is good for free software. I am sure a proprietary plug-in will have little trouble adapting DPF to compile with Steinberg SDK.

**Comment by falkTX** [comment] 2016-05-25 22:53
DPF already builds with the real VSTSDK.

That's not the issue here.
The issue is that using GPL limits us to its own license.
Public domain, LGPL, MIT/ISC/BSD and other types of code get "upgraded" to GPL.

So in a way GPL is actually *limiting* us, by restricting the licenses in which we can release our own software.
As soon as a project uses a little bit of GPL code, it automatically converts entirely into GPL - doesn't matter if 99% of code is BSD and 1% is GPL.

**Comment by jasp00** [comment] 2016-05-26 19:40
Speaking for myself, I would like derivatives to be free and GPL-compatible. Public domain, LGPL, etc., do not achieve that goal regarding their derivatives. I am fine with the license restriction. Public domain, LGPL (with exception to not include some sources), MIT... projects can use Steinberg SDK without the upgrade to another license.

**Comment by tresf** [comment] 2016-05-26 19:54
> Public domain, LGPL, etc., do not achieve that goal regarding their derivatives.

I tend to agree with @jasp00 here.

What is the use-case of a non-Steinberg and non-GPL VST header that the original VST header doesn't satisfy?

Also, has anyone reached out to Steinberg in recent years asking for permission?  As software culture changes (e.g. Microsoft jumping more actively into open source), the question may be worth asking to Steinberg over again.

> So in a way GPL is actually limiting us, by restricting the licenses in which we can release our own software.

I tend to agree and I feel this way about several GPL projects actually, but isn't this the inherent nature of the vast majority of GPL software?  If @jasp00's intent was to prevent the close-sourcing of his library, doesn't conversation prove he's achieved that?

**Comment by jasp00** [comment] 2016-05-27 19:11
> has anyone reached out to Steinberg in recent years asking for permission?

Asked in the forum.
https://www.steinberg.net/forums/viewtopic.php?f=149&t=97816

**Comment by BaraMGB** [comment] 2016-05-27 19:24
I fear Steinberg got no interest in spread vst 2.4 anymore. Therefore an open source license is very unlikely.

**Comment by grejppi** [comment] 2016-05-27 19:32
> I fear Steinberg got no interest in spread vst 2.4 anymore. Therefore an open source license is very unlikely.

VST 2.4 is still in wide use, and the VST3 SDK still contains the 2.4 headers.

**Comment by jcelerier** [comment] 2017-12-28 13:28
> If a GPLv2+ header is popular and widely used, that means the license choice is a success.

From what I could read, the GPL doesn't cover stuff like function / structure / constant / macro declaration, only the definition: http://lkml.iu.edu/hypermail/linux/kernel/0301.1/0362.html which is basically the relevant parts of affectx.h. Besides, given the recent legal developments WRT API copyrightability (eg Google copying the *whole* Java API from Oracle falling under "fair use"), maybe this isn't as important as previously (IANAL though).

**Comment by jcelerier** [comment] 2017-12-28 13:42
continuing with a bit of search on this, I'm not even sure that using the *original* VST SDK headers would be a problem, given this court case : http://www.zdnet.com/article/ruling-expressly-denies-express-logic-its-copyrighted-api-logic/

Here's the header being copied for instance: https://github.com/tony/gpc/blob/master/3rd_party/threadx/visual-studio/tx_api.h

**Comment by tresf** [comment] 2018-01-05 18:43
@jcelerier thanks for your feedback on this topic.  I agree that this ruling can have an impact on US rulings.  I'm going to close this issue out because the primary author -- @jasp00 -- hasn't shown a whole lot of interest in changing the one we ship so from an LMMS perspective, we won't be fixing this on our end, at least not in the foreseeable future.

```cpp
/* aeffectx.h - simple header to allow VeSTige compilation and eventually work
 *
 * Copyright (c) 2006 Javier Serrano Polo <jasp00/at/users.sourceforge.net>
```

> **@jasp00 wrote:**
> Speaking for myself, I would like derivatives to be free and GPL-compatible. Public domain, LGPL, etc., do not achieve that goal regarding their derivatives. I am fine with the license restriction. Public domain, LGPL (with exception to not include some sources), MIT... projects can use Steinberg SDK without the upgrade to another license.

**Closed by tresf** 2018-01-05 18:43 UTC
