### ISSUE TITLE
TAL plugins menu i cant see and select

### ISSUE THREAD

**Issue by superfirak** [LMMS/lmms#5351] opened 2019-12-21 08:51 UTC
When i click BPM Factor or Modulation Type in Tal-Filter-II, menu doesn't show. In tal noisemaker the waveform selection menu the same, doesn't show.
![resim](https://user-images.githubusercontent.com/8155284/71305649-40840480-23e8-11ea-8c4d-47c165180669.png)

**Comment by DomClark** [comment] 2020-01-06 00:30
Duplicate of #3918

**Closed by DomClark** 2020-01-06 00:30 UTC
Labels: bug
