### ISSUE TITLE
Show GUI Button on ZynAddSubFX crashes program (Windows 10)

### ISSUE THREAD

**Issue by Spark01** [LMMS/lmms#2819] opened 2016-06-03 12:37 UTC
When pressing the "Show GUI" button for ZynAddSubFX, ZynAddSubFX crashes, leading to LMMS crashing as well. I realize there is a bug report for this on Apple but as far as I know there is no bug report for this happening on Windows 10.

**Comment by liushuyu** [comment] 2016-06-03 13:19
What version of LMMS are you using? What are your computer specifications?

**Comment by Spark01** [comment] 2016-06-03 15:22
I'm using 1.1.90. My computer is 64-bit ( although I am using x86 LMMS, but that shouldn't be a problem as far as I know ) with 8 GB RAM and an Intel i7 2.60GHz CPU. If that's what you mean by specifications. If there is any other information that's relevant that I need to include, let me know and I will add it.

**Comment by DeRobyJ** [comment] 2016-06-03 16:25
I think a new RC needs to be published, the version on the site is pretty old.
I'll check x86 lmms on win7 in a moment with the old RC

**Comment by tresf** [comment] 2016-06-04 06:35
> I think a new RC needs to be published, the version on the site is pretty old.

Agreed.

**Comment by BaraMGB** [comment] 2016-06-04 07:10
> I can open and close the GUI with no problem.
Does it happen on x64 version too?

I tested on Windows 7 - 64bit. I can stress the button without any crashes.

**Comment by BaraMGB** [comment] 2016-06-04 07:37
Okay, tried to install lmms32 on Windows 10 64bit . Lmms hangs on splash on "prepairing automation editor".

**Comment by tresf** [comment] 2017-05-06 14:44
Marking as duplicate of https://github.com/LMMS/lmms/issues/3488.  There are several issues that can cause this and most are either permission related (in the case of #3488 fixed with repairing his drive) or audio back-end related, which requires better debugging capabilities on Windows.

If someone has the ability to provide [debugging information](https://github.com/lmms/lmms/wiki/Compiling#debugging) around this or any Windows crash problem we'd happily reopen.

**Closed by tresf** 2017-05-06 14:44 UTC
