### ISSUE TITLE
Fonts are nearly unreadable

### ISSUE THREAD

**Issue by es20490446e** [LMMS/lmms#1913] opened 2015-03-31 16:11 UTC
Interface doesn't follow system font size, and there's no option for configuring it through a graphical interface. This makes the text nearly unreadable in high resolutions.

![screenshot](https://cloud.githubusercontent.com/assets/9594332/6923247/c6950b0a-d7d0-11e4-95a4-524cd4588295.png)

**Comment by es20490446e** [comment] 2015-03-31 16:12
Also reported to https://bugs.launchpad.net/lmms/+bug/1438771.

**Comment by tresf** [comment] 2015-03-31 16:14
Thanks for reporting.

We're well aware and we need some help in this regard.  Closing as duplicate of #541, #1839

**Closed by tresf** 2015-03-31 16:14 UTC
Labels: duplicate
