### ISSUE TITLE
Crash: Controls window of LFO controller is not destroyed upon closing a project

### ISSUE THREAD

**Issue by Fastigium** [LMMS/lmms#2624] opened 2016-03-01 15:42 UTC
Another SIGSEGV crash while making music with the `master` branch. Steps to reproduce:

1. Open the controls window of an LFO controller (create one if necessary)
2. Open a different project (either load one or create a new one)
3. Notice how the controls window is still there
4. Cause a redraw of the controls window (even moving the mouse cursor over it will do)
5. Crash!

As this is more of a GUI problem, I won't assign myself to it. Feel free to pick this up while I continue hunting for crashes. Should nobody take it, I'll fix it in due time.

Why I consider this bug critical: you can work on your project for a long time without triggering the crash. This means you can lose a large amount of work.

**Comment by Fastigium** [comment] 2016-03-06 15:22
@zonkmachine Should you feel like more bisect work, this problem isn't there in `stable-1.1` :wink:

**Comment by zonkmachine** [comment] 2016-03-06 15:31
I'll try it but I can't reproduce it as described. I don't see the controls window still there but I get a crash and I guess that's the juicy part. I'm on the case...

**Comment by zonkmachine** [comment] 2016-03-06 17:13
:tractor:  Good run. No ambiguity.

```
cd0176b5afe18eef71bc45c66ec2017a109a0602 is the first bad commit
commit cd0176b5afe18eef71bc45c66ec2017a109a0602
Author: Michael Gregorius <michael.gregorius.git@arcor.de>
Date:   Wed Jul 29 22:35:06 2015 +0200

    Controllers are rendered more dynamically
    
    ControllerRackView now uses a layout to organize the ControllerViews.
    The ControllerViews in turn use layouts to organize their widgets
    (labels and push button). ControllerView now inherits from QFrame
    instead of QWidget. The (static) background image for controllers was
    deleted because the ControllerView can now be resized dynamically.
    
    Song: Added specific signals for added and removed controllers. Also
    removed a TODO by putting the functionality to remove all controllers in
    a method (removeAllControllers).
    
    Deleted Controllers now don't unregister from Song during deletion. This
    has to be done by the client (Hollywood principle - "Don't call us, we
    call you.").
    
    TODO: For some strange reason I cannot programmatically resize the
    controller rack to make it fit the controllers on my screen.
```

Ping @michaelgregorius ! :wink:

**Comment by michaelgregorius** [comment] 2016-03-06 18:08
Fixed with #2642.

@zonkmachine: Thanks for bisecting!

**Comment by Umcaruje** [comment] 2016-03-06 18:17
@Lukas-W the auto-assign stuff still isn't off

**Closed** 2016-03-06 18:56 UTC
Labels: bug, critical

**Comment by Lukas-W** [comment] 2016-03-06 20:56
Meh
