### ISSUE TITLE
Invalid soundfont path causes segmentation faults that make a project impossible to open later

### ISSUE THREAD

**Issue by JohnDorsey** [LMMS/lmms#6307] opened 2022-02-12 22:06 UTC
### Bug Summary
A project's Soundfont2 player allows a folder's path to accidentally be specified instead of an sf2 file's path. After saving, the .mmpz project can never be re-opened due to an assertion that always fails after fluidsynth refuses to open the invalid path.

#### Steps to reproduce
Clumsily click around in the default file selection dialogue on Ubuntu+xfce+Thunar. _Maybe_ highlight a folder before bailing out using the X button to close the dialogue. Maybe it was the global preferences dialogue and not the sf2 dialogue. I can't remember exactly what I did, because there were no error messages or other signs of trouble when I did it, and then a day or two passed before I discovered that the project was broken.

#### Expected behavior
1. Inputs for filepaths should be validated when a new one is chosen, so that it is impossible to accidentally update them to an invalid one.
2. Invalid inputs for SF2 path should be allowed without causing a total crash. The sf2 player should play silently, just like it does when the soundfont file path is properly formatted but the file is missing.
3. This project would be easy to repair if LMMS had a command-line option to convert a compressed project to an uncompressed one. It would allow me to fix the invalid value by hand in a text editor. The .mmp project type should be the default type, for the same reason.

#### Actual behavior
Soundfont player raises no objections when I first input data that will break my project. Now all attempts to open the project (using the open dialogue while no project is loaded or while another project is loaded, or from the command line) fail as shown in the logs.

#### Screenshot
It might not be relevant, but by taking a screenshot very fast, it's possible to see that this is usually the last thing on the progress bar before the crash.
![LMMS-54-1-cropped](https://user-images.githubusercontent.com/13240548/153729724-aeb2df87-ceae-45b6-8699-a5f3dd2ba0ce.png)
This is the dialogue used for choosing soundfont files in the sf2 player.
![LMMS-54-2-cropped](https://user-images.githubusercontent.com/13240548/153729734-6a1920e9-3120-4c92-bd42-e2bf5f529326.png)
This is the dialogue used for choosing the default soundfont file location in preferences.
![LMMS-54-3-cropped](https://user-images.githubusercontent.com/13240548/153729759-7e5fc650-eae1-4469-a3d2-f7d11873be5b.png)

#### Affected LMMS versions
LMMS 1.2.1 (with Thunar file manager 1.8.14, on Xubuntu).

#### Logs

This is the original console output from when I first discovered the problem:

john@*******:~$ lmms ~/Documents/lmms/projects/fmu-54-00.mmpz
Notice: could not set realtime priority.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
fluidsynth: error: fluid_sfloader_load(): Failed to open '/home/john/Documents/lmms/samples/': File is not regular, refusing to open it.
fluidsynth: error: Unable to open file '/home/john/Documents/lmms/samples/'

** (lmms:192806): CRITICAL **: 16:57:07.280: ipatch_container_init_iter: assertion 'IPATCH_IS_CONTAINER(container)' failed
Segmentation fault (core dumped)

Now some weeks have passed. I have changed some settings, including properly setting a default soundfont location. LMMS still fails to open the project in the same way, but now includes other information:

Notice: could not set realtime priority.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
fluidsynth: warning: No preset found on channel 0 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 1 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 2 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 3 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 4 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 5 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 6 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 7 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 8 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
fluidsynth: warning: No preset found on channel 10 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 11 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 12 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 13 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 14 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 15 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 0 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 1 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 2 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 3 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 4 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 5 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 6 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 7 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 8 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
fluidsynth: warning: No preset found on channel 10 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 11 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 12 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 13 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 14 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 15 [bank=0 prog=0]
Really deleting  "soundfonts/Orchestra Soundfont 2 COMBO.sf2"
fluidsynth: warning: No preset found on channel 0 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 1 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 2 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 3 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 4 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 5 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 6 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 7 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 8 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
fluidsynth: warning: No preset found on channel 10 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 11 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 12 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 13 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 14 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 15 [bank=0 prog=0]
fluidsynth: error: fluid_sfloader_load(): Failed to open '/home/john/Documents/lmms/samples/': File is not regular, refusing to open it.
fluidsynth: error: Unable to open file '/home/john/Documents/lmms/samples/'

** (lmms:1228546): CRITICAL **: 15:18:55.512: ipatch_container_init_iter: assertion 'IPATCH_IS_CONTAINER(container)' failed
Segmentation fault (core dumped)

On the same system, this is what the console output looks like when opening a compressed project containing a soundfont player with a valid soundfont specified:

$ lmms ~/Documents/lmms/projects/TestProjectWithSf2Piano.mmpz
Notice: could not set realtime priority.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
fluidsynth: warning: No preset found on channel 0 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 1 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 2 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 3 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 4 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 5 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 6 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 7 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 8 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
fluidsynth: warning: No preset found on channel 10 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 11 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 12 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 13 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 14 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 15 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 0 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 1 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 2 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 3 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 4 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 5 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 6 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 7 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 8 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
fluidsynth: warning: No preset found on channel 10 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 11 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 12 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 13 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 14 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 15 [bank=0 prog=0]
Really deleting  "soundfonts/Orchestra Soundfont 2 COMBO.sf2"
fluidsynth: warning: No preset found on channel 0 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 1 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 2 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 3 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 4 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 5 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 6 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 7 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 8 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
fluidsynth: warning: No preset found on channel 10 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 11 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 12 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 13 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 14 [bank=0 prog=0]
fluidsynth: warning: No preset found on channel 15 [bank=0 prog=0]

Also on the same system, this is what the console output looks like when a different compressed project containing no soundfont players is opened without problems:

$ lmms ~/Documents/lmms/projects/fmu-55-00.mmpz
Notice: could not set realtime priority.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB

**Comment by JohnDorsey** [comment] 2022-02-13 00:52
No lines matched,
The src attribute of the sf2 player was an empty string.

After saving the dump as an mmp, and manually typing the full path into the src attribute, I was able to recover my project! Thank you!
I missed the purpose of the dump option on my first read through of the manual, it does exactly what I needed.

**Comment by PhysSong** [comment] 2022-02-13 01:28
Duplicate of #5483 which is already fixed in 1.2.2(#5487), closing.

**Closed by PhysSong** 2022-02-13 01:28 UTC
Labels: bug
