### ISSUE TITLE
User controller activation in preset not restored

### ISSUE THREAD

**Issue by gi0e5b06** [LMMS/lmms#3906] opened 2017-10-23 15:35 UTC
The peak controller is controlling the cutoff frequency.
The user controller checkbox is not restored when adding the preset (to the song editor).
The xml data in the preset seems fine.
![preset-user-controller](https://user-images.githubusercontent.com/30031949/31897911-02e387a6-b818-11e7-9211-bbbd19a77696.jpg)

**Comment by PhysSong** [comment] 2017-10-23 21:48
Duplicate of #193.

**Closed by PhysSong** 2017-10-23 21:48 UTC
