### ISSUE TITLE
LB302: when trying to play two notes together a "random" is chosen

### ISSUE THREAD

**Issue by repsej** [LMMS/lmms#2565] opened 2016-02-13 20:26 UTC
To reproduce:
1) Add an LB302 instrument
2) Make a simple set of notes as seen in the image attached
3) Press play
4) Try changing the bmp to get more or less errors

At some speeds it almost alternates between the two notes ... can sound a little funky :D

(I guess that the LB302 cannot really play two notes at the same time but this is hardly the desired way to handle it :)

![image](https://cloud.githubusercontent.com/assets/116525/13029841/b9519964-d297-11e5-81dd-aa4d2e303ebf.png)

**Comment by repsej** [comment] 2016-02-15 07:46
Made a small song that shows the bugs.  

All melody in this song are made by the bug :D

(the bass has a simple chord progression to make it less hard on the ears)



[lb302-bug.zip](https://github.com/LMMS/lmms/files/130275/lb302-bug.zip)

**Comment by DeRobyJ** [comment] 2016-02-15 11:46
Well LB302 is a monophonic instrument, so it shouldn't be used with more notes at a time.
You can still have different lb302 tracks! :)

**Comment by zonkmachine** [comment] 2016-02-15 15:21
If it would have been an analogue synth it would probably have responded by sending out the highest note only. It could behave better here but I've got a hunch it could be a bit tricky to fix.

@repsej Brilliant track!

**Comment by repsej** [comment] 2016-02-15 23:00
This bug is actually quite good at creating interesting melodies and themes that slowly change ... much better than the randomize function in the arpeggio section (which is just boringly random).

I've now listened to my track for half an hour ... and it keeps changing :D

Sounds a bit like a drunk chimp with a keyboard.

<joke>
Maybe this should just be regarded as a feature of the LB302 ?? ^^
</joke>

**Comment by repsej** [comment] 2016-02-15 23:20
Had to take a quick glance at the code.

I do not think it's an intentional feature.  There's no mention of rand, seed or stuff like that .. (of cause that could be handled different in LMMS (?)).

I think that this bug/feature comes from a fun mixture of multi-threading and the data structures for the notes.

**Comment by grejppi** [comment] 2016-02-16 14:08
What exactly makes this a bug?

LB302, like most monophonic synths out there, blindly reacts to every note event it gets. LMMS plays different notes in different threads, so in case of multiple notes at the same time the one that gets played depends only on which thread just happens to finish last.

You called the effect
> much better than the randomize function in the arpeggio section

and I'm confused. Do you want to trade off an interesting effect for boring predictability?

**Comment by repsej** [comment] 2016-02-17 09:49
It is a bug ...  but, it's a very interesting one when you know it's there :)

And, even when you know it's there, it's usefulness is more aiming at performance artists than electronic musicians.

Say I've made a melody piece (for another instrument) that mostly contains single notes and a few chords.  Switching this track to using the LB302 (unaware, like most users, that it's a single note instrument) would cause the melody to change now and then ... it might only happen when I export the track.

For 99.9% of all users it's a bug ^^

**Comment by grejppi** [comment] 2016-02-17 13:40
@repsej Do you have definitive proof that 99.9% of LMMS users can't tell the difference between polyphonic and monophonic instruments, or are you just trying to back up your opinion?

**Comment by repsej** [comment] 2016-02-17 14:12
There is (as far as I know) only one monophonic instrument in LMMS.  And inside the program the only place it is mentioned that it is monophonic is in the list of instruments.  Thus, for users (like me) who mostly use the presets - that word is never (or rarely) seen.  

Until I filed this bug report I hadn't noticed that LB302 was monophonic (nor did I know what that would mean).

If fixing the bug is too difficult - maybe an easier "fix" is to write a warning on the graphics for the LB302 instrument.  "Warning: playing more that one note at a time leads to random behaviour" ... or something like that.

**Comment by tresf** [comment] 2016-02-17 14:32
> Do you have definitive proof that 99.9% of LMMS users can't tell the difference between polyphonic and monophonic instruments, or are you just trying to back up your opinion?

Regardless, unless it's the instruments desired behavior, he's correct, it's a bug. :beers:

**Comment by michaelgregorius** [comment] 2016-02-17 20:29
> Regardless, unless it's the instruments desired behavior, he's correct, it's a bug.

I think the problem is that it's not bound to a single instrument but a rather general problem with how LMMS renders the tracks:

> LMMS plays different notes in different threads, so in case of multiple notes at the same time the one that gets played depends only on whichever thread just happens to finish last.

To me that sounds like the rendering of notes that start at the same time is non-deterministic for monophonic instruments in LMMS. I would consider that a bug because this will likely affect the rendering of a song as well. If you render a song several times it will sound different each time.

**Comment by grejppi** [comment] 2016-02-18 15:59
@michaelgregorius It still won't have an effect when playing one note at a time, which... just happens to be the only way LB302 is designed to be used.

I honestly think unpredictability is what gives LB302 its character, intentional or not.

**Comment by zonkmachine** [comment] 2016-02-18 16:11
> .... just happens to be the only way LB302 is designed to be used.

This is the thing. When we press on the "ship this" button people will not have read that memo. They can just pop in an lb302 instead of the 3 Osc they had before and 'Boom', they're using it in a way you're not supposed to. It's behaving in an unusual way for a monophonic synthesizer.

**Comment by tresf** [comment] 2016-02-18 16:47
> I honestly think unpredictability is what gives LB302 its character, intentional or not.

"It's not a bug, it's a feature!" :)

I tend to agree with the bug diagnosis.  If we really like the unpredictability of it, we can enhance the instrument to allow racing to occur as an additional checkbox.

**Comment by michaelgregorius** [comment] 2016-02-18 20:40
I agree with @tresf. Unpredictability should be an option of an instrument and not caused by the implementation of the software.

@grejppi Sure a monophonic synth only plays one note at a time. However, most synths will even remember the order that notes are pressed and play a note as long as no other note is triggered. If you press one key on a monophonic synth it will play. If you keep that key pressed and play a second key now that note will sound (perhaps after a glide if configured). If you lift your finger from the second key in most cases the first note will sound again. This is for example helpful to play trills or fast runs.

**Comment by tresf** [comment] 2016-02-18 20:43
If we're worried about backwards compat, we can shim in [an upgrade line](https://github.com/LMMS/lmms/blob/master/src/core/DataFile.cpp#L795) as well. :+1:

**Comment by grejppi** [comment] 2016-02-18 21:26
@michaelgregorius
> However, most synths will even remember the order that notes are pressed and play a note as long as no other note is triggered. If you press one key on a monophonic synth it will play. If you keep that key pressed and play a second key now that note will sound (perhaps after a glide if configured). If you lift your finger from the second key in most cases the first note will sound again.

And this is what LB302 does. The only thing is that if there are multiple notes starting **at the same time**, the one that gets played is not clearly defined.

The threads are spawned in the order the notes are placed in the pattern, which is what 99.9% of the DAWs I have used that have a piano roll do. However, threads gonna thread, so there will be racing.

I see little point in patching LB302 to work around it.

**Comment by Umcaruje** [comment] 2016-02-18 22:29
>Sure a monophonic synth only plays one note at a time. However, most synths will even remember the order that notes are pressed and play a note as long as no other note is triggered. If you press one key on a monophonic synth it will play. If you keep that key pressed and play a second key now that note will sound (perhaps after a glide if configured). If you lift your finger from the second key in most cases the first note will sound again. This is for example helpful to play trills or fast runs.

LB302 functions exactly like that: https://www.youtube.com/watch?v=Vy3HkeLlBlo

This issue is about when you play chords with LB302 (2 or more notes that hit at extactly the same time) it chooses a random note. As @grejppi I don't think this behaviour shouldn't be fixed as it can produce interesting effects. If you don't want this to happen, __don't play chords with a monophonic instrument__. It's not what they were made for.

**Comment by tresf** [comment] 2016-02-19 02:58
I'm closing this as `wont-fix`, but mostly because it's beating a dead horse at this point and we simply won't be fixing it in the foreseeable future.  I don't agree with the removal of the `bug` category, but I also have suffered the issue described on several occasions and it is was not `interesting` or `characteristic` from a composer's perspective.

@repsej thanks for the excellent bug report and please continue to do so. :+1:   This can be reopened at any time deemed necessary. :beer:

**Closed by tresf** 2016-02-19 02:58 UTC
Labels: won't fix
