### ISSUE TITLE
Mixer bugs and unpleasant changes

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#7508] opened 2024-09-18 18:24 UTC
### System Information

Debian Sid Cinnamon 

### LMMS Version(s)

Night Version

### Most Recent Working Version

Versión 1.3.0-alpha.1.695+g01294192c (Linux/x86_64, Qt 5.12.8, GCC 9.4.0).

### Bug Summary

https://github.com/user-attachments/assets/8b2b44ad-0ce0-473a-ae7e-7d2b7a65619a

I am aware of the changes made to the mixer and I did the test but I experienced some bugs and unpleasant visual changes such as:

1- The name labels do not stretch according to the mixer window.
2- The effects boxes are cut in half except for the master box.
3- The send arrows go out of the channel frame.
4- The LED indicators take up all the horizontal space, which makes all the channels look cut in half.

### Expected Behaviour

Personally, it looked better before, more spacious but with the only defect that the name labels did not stretch.

### Steps To Reproduce

Open LMMS and do the test.

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Rossmaxx** [comment] 2024-09-19 04:32
@sakertooth you might wanna look at this since you started work on mixer.

**Comment by Rossmaxx** [comment] 2024-09-19 05:11
I can confirm that this is a recent regression. I experience this too on linux mint.

**Comment by Rossmaxx** [comment] 2024-09-19 05:26
I could narrow down the `EffectView` regression to #7453 

@DanielKauss @michaelgregorius

**Comment by sakertooth** [comment] 2024-09-19 05:27
Yeah @Rossmaxx, was just gonna say that. I haven't bisected yet, but I had a hunch that #7453 is the culprit since it made changes to the sizing of the effects in `EffectRackView::update`.

**Comment by Rossmaxx** [comment] 2024-09-19 05:40
Another update: Dragging the effect and dropping it somewhere else seems to fix the layout.

**Comment by sakertooth** [comment] 2024-09-19 17:09
>  3- The send arrows go out of the channel frame.
>  4- The LED indicators take up all the horizontal space, which makes all the channels look cut in half.

Both these issues should be fixed now.

> 1- The name labels do not stretch according to the mixer window.

I see you added an enhancement for this in another issue, but yeah this didn't change.

>  2- The effects boxes are cut in half except for the master box.

I believe #7511 should fix this, but @Rossmaxx still has straighten out a few loose ends I think.

**Comment by sakertooth** [comment] 2024-11-01 21:22
Closing, as these issues were fixed recently.

**Closed by sakertooth** 2024-11-01 21:22 UTC
Labels: bug
