### ISSUE TITLE
ZynAddSubFX, Show gui, Crash

### ISSUE THREAD

**Issue by VanquishVictor** [LMMS/lmms#2605] opened 2016-02-24 17:58 UTC
Hi,

I have LMMS in my Linux computer, it is genuine and I have installed the most up to date version. But every time I go to ZynAddSubFX and click 'show gui' the whole software crashes. 
Is there a way to solve this? I would really appreciate it.

**Comment by tresf** [comment] 2016-02-24 18:13
@VanquishVictor where did you get LMMS from?  Which version?  Old builds from our `master` branch exhibited this problem, but we generally advise installing from our `stable` branches.  Our current stable build is `stable-1.1` and the version number is `1.1.3`.

Depending on your build, could be a duplicate of #2269 or #2100.

**Comment by VanquishVictor** [comment] 2016-02-25 14:30
LMMS came with the Linux software, version 1.1.3, 
I have these details. ![details1](https://cloud.githubusercontent.com/assets/17458488/13322415/3294a8b0-dbcc-11e5-8e50-225f92536118.jpeg)
I have no idea on build though

**Comment by tresf** [comment] 2016-02-25 14:35
> LMMS came with the Linux software, version 1.1.3, 

Then the bug is with your Linux software.  You should contact them. :+1: This is an issue tracker for our source code, so if you can't provide information to troubleshoot, we can't help.  This isn't a general help forum.

**Closed by tresf** 2016-02-25 14:35 UTC
Labels: support request
