### ISSUE TITLE
Automations lose it's connection and the shape if you copy them in the Song editor

### ISSUE THREAD

**Issue by Nicolai-YT** [LMMS/lmms#4681] opened 2018-10-27 09:01 UTC
If you copy Automations in LMMS 1.2.0 RC7 in the song editor
the connections of the automations get lost and the automation shape is also lost.

Would be nice if this could be fixed.

**Comment by PhysSong** [comment] 2018-10-27 13:07
Duplicate of #3781.

**Closed by PhysSong** 2018-10-27 13:07 UTC
