### ISSUE TITLE
No Note copy/paste 

### ISSUE THREAD

**Issue by ben83bb** [LMMS/lmms#6002] opened 2021-04-28 12:50 UTC
Lmms 1.3.0 Alpha

If i want to copy Notes by right clicking in the BB-Editor form one Instrument to another. I cant paste it to the other Instrument. It has no effect.

**Comment by qnebra** [comment] 2021-04-28 14:42
Why you want to do that? For me it is quite illogical that copy & paste options are in BB-Editor.

**Comment by ben83bb** [comment] 2021-04-28 15:32
In LMMS 1.2.2 i can copy n paste same Notes to other instruments.
The Reason why i want to have this Option is, that i want to clone Notes and set them in different Octaves

**Comment by IanCaio** [comment] 2021-04-28 16:17
I did some testing here, pasting works fine when you paste on the Song Editor, but pasting inside the BB editor is in fact not working as it used to work on Stable.

There was a serious refactoring of the Clipboard functionality plus some improvements (like selection Copy/Paste, pasting in the timeline, etc) and with them the way the Copying and Pasting code works changed. Something along the changes probably turned out incompatible with the BBEditor, I'm not sure. I'll have to investigate it a bit further.

For now you can use the Piano Roll and copy and paste the notes directly as a workaround.

**Comment by IanCaio** [comment] 2021-04-28 17:08
I tracked the problem down to this conditional on `TrackContentWidget::canPasteSelection`:

https://github.com/LMMS/lmms/blob/89f0a98e3da855a13b30db3cc961de7268d38920/src/gui/widgets/TrackContentWidget.cpp#L347-L352

One of the changes on the clipboard refactoring is that pasting a single TCO or multiple ones both use the same method. This was done to avoid duplication of code and to allow a more flexible Copy/Pasting UI. The problem is that one of the conditionals of the selection pasting was that it couldn't be done on TrackViews that used `fixedTCOs`, which was probably done because the BBEditor uses the TCO position to define which BBTrack that TCO is part of, so pasting selections over the BBTrack could cause issues with TCOs being placed in different or even inexistent BBTracks (which is also why `setAcceptDrops` is false on the BBEditor).

I still have to think what a good solution would be, because simply allowing the selection to be pasted isn't safe because of the same reasons it wasn't safe before. There will probably have to be another conditional for when the TrackView is from the BBEditor which would check if there's only one TCO being pasted and that it's size is the same as the BBTCO size.

I'm leaving this fix for after the refactor, but at least it's already clarified where the problem lies. Thanks for bringing it to attention @ben83bb !

**Comment by zonkmachine** [comment] 2023-08-09 15:46
@IanCaio In https://github.com/LMMS/lmms/issues/6756 I bisected your original branch down to this guilty commit (https://github.com/LMMS/lmms/commit/ebc808ef5745657aaec2acb8809a007729d6dd17). Closing that one as a duplicate.


> I tracked the problem down to this conditional on `TrackContentWidget::canPasteSelection`:
> 
> https://github.com/LMMS/lmms/blob/89f0a98e3da855a13b30db3cc961de7268d38920/src/gui/widgets/TrackContentWidget.cpp#L347-L352
> 

I can confirm that removing the fixedTCO condition turns copy/paste on again in the Pattern Editor. I don't know what other issue this may bring. Can you look into patching this now?

**Closed** 2023-08-12 14:54 UTC
Labels: bug
