### ISSUE TITLE
A question/complaint about the ZynAddSubFX GUI in LMMS

### ISSUE THREAD

**Issue by uzr123x** [LMMS/lmms#5854] opened 2020-12-21 12:00 UTC
When you click on ZynAddSubFX's "Show GUI" you encounter an ancient (to put it mildly) interface that's based on FLTK toolkit, and it looks so out of place in LMMS that no other synth's GUI can come close to it in terms of being visually crude and inconvenient in the year 2020. I don't think one needs to demonstrate it, just take a look yourself.

Perhaps utilizing Zyn Fusion GUI is a way to go? Have people here considered switching to Fusion as the default Zyn's UI in LMMS?

**Comment by Spekular** [comment] 2020-12-21 12:54
Closing as duplicate of #4179

**Closed by Spekular** 2020-12-21 12:54 UTC
Labels: enhancement
