### ISSUE TITLE
 lmms-1.2.0-rc6-mac10.13.dmg wont run on High Sierra

### ISSUE THREAD

**Issue by erknie** [LMMS/lmms#4541] opened 2018-08-15 09:18 UTC
Just download 
lmms-1.2.0-rc6-mac10.13.dmg
and installed it on Mac OS X 10.13.6 and tried to run it.
It said "You can’t open the application “LMMS” because it may be damaged or incomplete"

How do I run it?

**Comment by PhysSong** [comment] 2018-08-15 10:02
Possible duplicate of #3760.

**Comment by erknie** [comment] 2018-08-15 10:47
Yes the fault is very similar to the fault with 1.2rc3 on the Mac, however there is no solution proposed in #3760 the thread was closed.

That means Mac users haven't been able to run lMMS 1.2 from their hard drive for at least 9 months which seems odd.  1.13 runs ok, but it doesn't seem to have soundfont support compiled in.

I tried copying 1.2rc6 from the .dmg to /Applications and to my Desktop folder by drag copy and various command line copy attempts which all failed to create an executable copy. The version on the .dmg runs, so why won't the copy on the hard drive execute?

**Comment by eagles051387** [comment] 2018-08-15 20:10
Is there an error message that pops up saying the application wasn’t installed from the App Store? If that is the case you need to go into the system settings, security and on the bottom you will have an option to allow it to run as well you can change your settings regarding apps

**Comment by erknie** [comment] 2018-08-15 21:03
I have my security setting set to allow Apps to be installed from anywhere, and the app runs from the .dmg something breaks when you try and copy it elsewhere. I have never seen another app do this and I have installed dozens of different apps  from .dmg volumes.

**Comment by Agrrox** [comment] 2018-08-16 06:02
LMMS 1.2.0-RC6 runs on my system with macos High Sierra (10.13.6) with occasional crashes. Maybe there are some permission that prevent application from running on your system?

**Comment by PhysSong** [comment] 2018-08-16 06:16
@Agrrox It doesn't look like related to this issue. Could you search for existing GitHub issues(both open and closed) first? If you can't find relevant one, please open a new issue with crash reports.

**Comment by tresf** [comment] 2018-08-29 06:02
I recommend standard troubleshooting, 1. Purge old folder.  2. Run First Aid on your disk.  3. Reboot.  4. Reinstall. (I assume all updates are installed)

I've had intermittent issues with High Sierra especially on my MacBook pro where DMGs just failed to mount or failed to copy.  Some update must have fixed it because the problem went away a few days after I bought it.

Regardless, it's most likely a problem with your computer.

If by chance there is an incompatibility between the version we build and your CPU, it may be worth running directly from the binary... Show Package Contents, Contents MacOS, then drag `lmms` into a terminal window.

**Comment by erknie** [comment] 2018-09-12 05:41
I tried it on  a different computer which is running El Capitan and the same problem, LMMS will run from the mounted lmms-1.2.0-rc6-mac10.8.dmg volume, but as soon as a try and drag copy it anywhere on the hard disk, the icon changes to non executable (white circle with a slash through it)
I am always installing apps from .dmg images, never seen this happen before.

**Comment by PhysSong** [comment] 2018-09-12 08:01
Have you tried https://support.apple.com/kb/ph25088?locale=en_US? Also, can you open the application using the command line, e.g. #4021?

**Comment by PhysSong** [comment] 2022-03-23 01:39
If you can, could you check with 1.2.2 releases?

**Closed** 2022-04-06 02:34 UTC
Labels: bug, response required

**Comment by stackdump** [comment] 2023-08-13 13:04
I'm seeing this issue on Mac os v 13.5 

Installed this version [
](https://github.com/LMMS/lmms/releases/download/v1.2.2/lmms-1.2.2-mac10.14.dmg)

tried installing w/ hombrew (same issue)

**Comment by tresf** [comment] 2023-08-13 14:44
> I'm seeing this issue on Mac os v 13.5
> 
> Installed this version [ ](https://github.com/LMMS/lmms/releases/download/v1.2.2/lmms-1.2.2-mac10.14.dmg)
> 
> tried installing w/ hombrew (same issue)

Please try the following:

```bash
sudo xattr -r -d com.apple.quarantine /Applications/LMMS.app
```
