### ISSUE TITLE
Some projects do not allow commercial usage

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#2761] opened 2016-05-07 19:33 UTC
Projects under CC BY-NC or Yellow OpenMusic cannot be included in distributions such as Debian, works are considered non-free. One long term goal is to not ship license restricted songs with LMMS.

**Comment by tresf** [comment] 2016-05-07 19:51
Agreed, songs, samples and presets.  Duplicate of https://github.com/LMMS/lmms/issues/1273#issuecomment-62189752, https://github.com/LMMS/lmms/issues/1693.

Somewhat related https://github.com/LMMS/samples#commit-rules

**Closed by tresf** 2016-05-07 19:51 UTC
Labels: duplicate
