### ISSUE TITLE
RemoteVstPlugin fails to build with with -flto

### ISSUE THREAD

**Issue by plater** [LMMS/lmms#5179] opened 2019-09-09 12:16 UTC
I've disabled vst build in openSUSE meanwhile but maybe it's easy for someone familiar with lmms to find a fix. I've attached the entire build log. See:
https://build.opensuse.org/package/show/multimedia:apps/lmms to view the patches.
Build failure point:
```
Arbuthnot:/home/abuild/rpmbuild/BUILD/lmms-1.2.0/build/plugins/vst_base # cd /home/abuild/rpmbuild/BUILD/lmms-1.2.0/build/plugins/vst_base && /usr/bin/wineg++ -I/home/abuild/rpmbuild/BUILD/lmms-1.2.0/build -I/home/abuild/rpmbuild/BUILD/lmms-1.2.0/include -I/usr/include -I/usr/include/wine/windows -L/usr/lib64/libwine.so /home/abuild/rpmbuild/BUILD/lmms-1.2.0/plugins/vst_base/RemoteVstPlugin.cpp -std=c++0x -mwindows -lpthread -lole32 -m32 -nodefaultlibs /usr/lib/wine/libwinecrt0.a -L/usr/lib/wine/ -luser32 -lkernel32 -lgdi32 -fno-omit-frame-pointer -fno-exceptions -Wall -Werror=unused-function -Wno-sign-compare -Wno-strict-overflow -Wno-array-bounds -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=4 -DNDEBUG -fPIC -DPIC -pie -o ../RemoteVstPlugin
In file included from /usr/include/wine/windows/objbase.h:252,
                 from /usr/include/wine/windows/ole2.h:25,
                 from /usr/include/wine/windows/wtypes.h:13,
                 from /usr/include/wine/windows/winscard.h:22,
                 from /usr/include/wine/windows/windows.h:70,
                 from /home/abuild/rpmbuild/BUILD/lmms-1.2.0/plugins/vst_base/RemoteVstPlugin.cpp:64:
/usr/include/wine/windows/objidl.h:6100:15: error: ‘union _userSTGMEDIUM::<unnamed struct>::__WIDL_objidl_generated_name_0000000C’ invalid; an anonymous struct may only have public non-static data members [-fpermissive]
 6100 |         union __WIDL_objidl_generated_name_0000000C {
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
winegcc: g++ failed
```
[rpmbuildlog.txt](https://github.com/LMMS/lmms/files/3590381/rpmbuildlog.txt)

**Comment by PhysSong** [comment] 2019-09-09 13:30
It seems like it's a bug with Wine >= 4.14: https://bugs.winehq.org/show_bug.cgi?id=47710
According to https://github.com/doitsujin/dxvk/issues/1182#issuecomment-528132013, `-D__WIDL_objidl_generated_name_0000000C=` is a possible workaround.

**Comment by plater** [comment] 2019-09-10 14:18
With -D__WIDL_objidl_generated_name_0000000C="" included in the CXXFLAGS I get a link time error about an undefined ExitProcess due to the vst section choking on Link Time Optimization. This is a pity because everything else except vst builds with it. I've discovered that I can build the vst plugins without wine which is the best option for me, works with LTO as well.

**Comment by PhysSong** [comment] 2019-09-10 23:17
> I get a link time error about an undefined ExitProcess due to the vst section choking on Link Time Optimization.

That sounds like https://bugs.winehq.org/show_bug.cgi?id=41712

**Comment by plater** [comment] 2019-09-11 06:44
> > I get a link time error about an undefined ExitProcess due to the vst section choking on Link Time Optimization.
> 
> That sounds like https://bugs.winehq.org/show_bug.cgi?id=41712

Can confirm it is.

**Comment by Reflexe** [comment] 2019-10-12 10:18
I think we can close this issue? @PhysSong

**Comment by PhysSong** [comment] 2019-10-12 11:03
The `-flto` part is still not fixed, but I'm not sure if it's worth fixing it.

**Comment by tank-trax** [comment] 2020-06-21 04:19
try commenting out

`/*__WIDL_objidl_generated_name_0000000C */`

I had to do this to compile [Carla](https://github.com/falkTX/Carla/issues/914)

**Comment by plater** [comment] 2020-06-21 05:48
I've revisited openSUSE's lmms build and the only build flag I have to remove is -m64 to allow the wine-32 build to succeed. grepping the build log finds 167 instances of -flto=auto so I don't understand the issue with lto. The only modification to the build is sed out -m64 and add -D__WIDL_objidl_generated_name_0000000C="" to the build flags.

**Comment by thmo** [comment] 2021-05-09 12:55
The problem is still there on Fedora 34/i686, I think (for lmms 1.2.2):
```
# wineg++  ../../../plugins/vst_base/RemoteVstPlugin.cpp -I../../../include -I../../../i686-redhat-linux-gnu -lole32 -lpthread -std=c++0x -mwindows -O2 -m32 -flto=auto
/usr/bin/ld: /usr/bin/../lib/wine/libwinecrt0.a(exe_entry.o): warning: relocation against `strlen@@GLIBC_2.0' in read-only section `.text'
/usr/bin/ld: /usr/bin/../lib/wine/libwinecrt0.a(exe_entry.o): in function `__wine_spec_exe_entry':
(.text+0x19): undefined reference to `GetCommandLineA'
/usr/bin/ld: (.text+0x4c): undefined reference to `HeapAlloc'
/usr/bin/ld: (.text+0x107): undefined reference to `ExitProcess'
/usr/bin/ld: a.out.so: hidden symbol `HeapAlloc' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/g++ failed
```
with these wine packages installed:
```
# rpm -qa 'wine*'
wine-filesystem-6.7-1.fc34.noarch
wine-core-6.7-1.fc34.i686
wine-devel-6.7-1.fc34.i686
```
Compilation succeeds when omitting  `-flto=auto` switch or adding `-fno-lto` (the warning is still there, but probably unrelated).

NB: Adding `-D__WIDL_objidl_generated_name_0000000C=""` does _not_ fix the issue for me (which is to be expected, as [this](https://bugs.winehq.org/show_bug.cgi?id=47710) has been fixed in wine 5.0 already).

**Comment by luzpaz** [comment] 2023-07-03 00:35
Is this issue impacted at all by https://github.com/LMMS/lmms/issues/6672#issuecomment-1616318593 ?

**Comment by Rossmaxx** [comment] 2024-05-30 11:19
I'm closing this for now as we switched to use wine >= 6.0 and i persume the regression to not be there. If it arises again, feel free to reopen.

**Closed by Rossmaxx** 2024-05-30 11:19 UTC
Labels: bug, upstream
