### ISSUE TITLE
Segmentation fault when previewing samples

### ISSUE THREAD

**Issue by Achifaifa** [LMMS/lmms#1829] opened 2015-03-06 15:32 UTC
When I try to preview certain samples, I get a segfault. Some of them are samples I imported myself, but I found one that gives this behaviour and it's included by default.

Steps to reproduce: Open lmms. Click on samples, and try to preview misc > metalish_dong01.ogg. The appliciation immediately crashes. The only thing the console says is "segmentation fault".

I'd love to fiddle and try to fix it myself but the error message in the console is pretty vague.

**Comment by tresf** [comment] 2015-03-06 17:02
When you close and reopen LMMS from scratch does this still occur?  It may be caused by incorrectly cached preset settings.  I cannot reproduce the crash here using version 1.1.0 (stable-1.1 branch) on Windows 64-bit.

**Comment by Achifaifa** [comment] 2015-03-06 17:38
Yes, I have tried it several times (With projects open, with no projects open, with default config, etc) and it crashes every time. 

Forgot to mention, I'm using 1.0.3 in Debian 386 (The version in the Jessie repository). Maybe it has been fixed or it's just an issue with the OS.

**Comment by tresf** [comment] 2015-03-06 17:51
@Achifaifa this is most likely a bug with that particular build as we have no historic record of this crash in `1.0.3`.

**Comment by Achifaifa** [comment] 2015-03-06 19:28
Good to know, I think I'll try keeping it updated manually rather than using the repository. Thanks :)

**Comment by tresf** [comment] 2015-03-06 19:48
Thanks for the report.  I'll close it as invalid for now, but feel free to reopen if needed. :+1:

**Closed** 2015-03-06 19:48 UTC
Labels: invalid

**Comment by tresf** [comment] 2015-09-30 20:25
FYI - This was re-addressed via https://github.com/LMMS/lmms/issues/2391.
