### ISSUE TITLE
Play a note "mid-note"

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#3460] opened 2017-03-28 07:10 UTC
Hi, I would like to report a problem on the piano roll, when we make a note round or longer and quickly want to go back to any position of the note, it does not play and you have to start from the beginning of the note. The same happens with the example tracks, this is in the current version 1.1.3 but in version 1.2.0 rc2 improved this but only with the example track, but with the midi notes the problem persists. What do you think?. Have a good time

**Comment by musikBear** [comment] 2017-03-28 15:39
> make a note round or longer and quickly want to go back to **any position** of the note,

No. that is not possible. a note is initiated when the play-head 'meets' the note, so starting in any other pos of the note will not work
All DAW i know of, works this way.

**Comment by zonkmachine** [comment] 2017-03-28 15:53
> 1.2.0 rc2 improved this but only with the **example track**

Sample Track, yes. That's a different situation.

**Comment by jasp00** [comment] 2017-03-29 05:37
>No. that is not possible

Hard to do rather than impossible.

**Comment by zonkmachine** [comment] 2017-12-11 21:09
**Won't fix**?

How does ardour, bitwig do this?

**Comment by michaelgregorius** [comment] 2017-12-28 00:01
This issue should be covered by #2539. The problem of missing "Note On" events is described in [this comment](https://github.com/LMMS/lmms/issues/2539#issuecomment-178814297). The issue also contains a discussion about ["MIDI Chase"](https://steinberg.help/cubase_pro_artist/v9/en/cubase_nuendo/topics/playback/playback_chase_c.html) as a potential solution.

**Comment by tresf** [comment] 2018-09-29 16:45
> This issue should be covered by #2539. The problem of missing "Note On" events is described in this comment. The issue also contains a discussion about "MIDI Chase" as a potential solution.

That issue description is completely different though.  @michaelgregorius can you please help consolidate these two issues?

**Comment by michaelgregorius** [comment] 2018-10-11 17:53
@tresf The issue description of #2539 is indeed different but the problem described in that issue is caused by something similar. Whereas this issue describes that no "Note On" event is triggered if you start playback with the play head in midst of a note, #2539 describes that no "Note Off" event is sent when the loop end happens to be in the midst of a note.

This observation made in https://github.com/LMMS/lmms/issues/2539#issuecomment-178814297 is very similar to this issue:
> I also noticed that LMMS does not play the sound of a track if its "Note On" event starts before the loop.

How shall we consolidate these two issues? Shall we create a new issue which describes the problems described by this issue and #2539 or shall we edit one of the two issues to contain all information?

**Comment by tresf** [comment] 2018-10-11 18:08
> or shall we edit one of the two issues to contain all information?

This is my preferred approach.

**Comment by michaelgregorius** [comment] 2018-12-07 09:59
Closing this issue as it has been linked and merged into #2539 because that issue has a longer discussion with more information.

**Closed by michaelgregorius** 2018-12-07 09:59 UTC
Labels: core, ux
