### ISSUE TITLE
Option to save complete projects.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4817] opened 2019-02-07 23:06 UTC
Currently I have no problems with the "save projects" option. However, when you share LMMS projects with other users (and more if they are from other platforms), the workflow is affected. When exchanging projects I have experienced the following problems:

- The project is saved in a single file.
- I can not unzip or extract the project files.
- I have to reconfigure the route and the parameters of each sample, sound sources or complements.
- Only presets of internal instruments are saved.
- AFP samples and their parameters are not saved.
- I can not save SF2 or other sound sources.
- I can not save the sample tracks.
- Among others.

But these problems can be solved with an option dedicated to the '' full proyect '' in LMMS, this option would have certain characteristics, such as:

- Option '' Save Complete Project '' in the '' Files '' menu.
- Display a dedicated dialog box with a menu with the following options:

 1- Option to save project as compressed zip file.
 2- Option to save Sf2 files and other sound sources within the project.
 3- Option to save the Vst plugins within the project.
 4- Option to save afp samples within the project.
 5- Option to save sample tracks within the project.

This characteristic behaves in this way:

- Save internal project files in a dedicated folder, instead of a simple mmpz file.
- Possibility to save the entire project within a Zip archive.
- Possibility of extracting and modifying the internal files of the project.
- Possibility of recovering the files, in case of damage to the project file.

Within the project folder, the files are organized in this way:

- Project file in the main folder.
- Sub folders: '' Samples '', '' Vst '', '' Soundfont '', '' Presets ''.
- Sub folder dedicated to the ''example tracks''.
- Sub folder dedicated to presets.
- Sub folders dedicated to the Midi files of each track.

Thus, the parameters and configurations remain intact:

- Maintain the parameters of Vst and Sf2.
- Maintain the parameters of the Afp samples.
- Maintain the parameters of the instruments.
- Maintain the position and configuration of the example tracks.
- Maintain the routes of all project files.
- Detect the project files and assign them automatically to their place.

Obviously the '' Complete Project '' would occupy too much memory space and hard disk, so for security reasons, to open the project would be necessary a characteristic '' safe mode '' in a dialog box with the following options :

- Enable the Vst plugins.
- Load the Soundfonts.
- Load the samples of Afp.
- Load the example tracks.
- Buttons of '' Ok '', '' Cancel ''.

All this seems a hell of long hours of programming, but if this feature is implemented, would be imnovador, the workflow in LMMS would improve enough because it would save a lot of time in the exchange of projects, and it would not be necessary to reorder and reconfigure the project files , when you change operating systems. I do not know you guys, I'm a beginner in this, for me this idea does not seem bad to me. What do you think about it? regards

**Comment by lukas-w** [comment] 2019-02-08 12:32
Closing as duplicate of #1257.

**Closed by lukas-w** 2019-02-08 12:32 UTC
