### ISSUE TITLE
LMMS crash start. 

### ISSUE THREAD

**Issue by Mialder** [LMMS/lmms#4036] opened 2017-12-05 15:56 UTC
Hello! Sorry, im from Ukrain. and I do not know English well. Im start LMMS with gdb and that's what I got:
Thread 1 "lmms" received signal SIGSEGV, Segmentation fault.
0x00007fff8bba7787 in QMetaObject::className() const ()
   from /usr/lib/libQt5Core.so.5

What can I do?
Arch linux x64.

**Comment by tresf** [comment] 2017-12-05 16:09
Where did you get LMMS from?  Did you build from source or use a package manager?

Have you tried removing `~/.lmmsrc.xml`?
Have you tried reinstalling Qt5?

We also have a portable version for Linux here if interested:
https://github.com/tresf/lmms/releases/download/v1.2.0-rc4/lmms-1.2.0-rc4.117-linux-x86_64.AppImage

This comes bundled worth Qt5 so it should fix any issues that may have occurred by the package managers.

**Comment by Mialder** [comment] 2017-12-05 16:40
Im get LMMS from AUR using yaourt. 
Im remove ~/.lmmsrc.xml - nothin.
The reinstallation qt5 did not help either.

**Comment by tresf** [comment] 2017-12-05 16:43
@Mialder then you'll have to contact them, this isn't our bug.  We didn't build it, we can't fix it.  We don't provide LMMS to any 3rd party websites, mirrors, etc.

That said, the portable version is in very good shape and I recommend trying it.  Just `chmod +x` and then double-click it as you would any application.

**Comment by Mialder** [comment] 2017-12-05 16:46
Ok. Thanks for the help, anyway. I'll try to install "community" from the repository. If it does not help, I'll try the installer for your link.

**Comment by PhysSong** [comment] 2017-12-06 01:39
From #4030: 
```
#0  0x00007fffb89d6787 in QMetaObject::className() const () at /usr/lib/libQt5Core.so.5
#1  0x00007fffb9743590 in  () at /usr/lib/libQt5Widgets.so.5
#2  0x00007fffb96e4137 in  () at /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff7de751a in call_init.part () at /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7de7626 in _dl_init () at /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7debafe in dl_open_worker () at /lib64/ld-linux-x86-64.so.2
#6  0x00007ffff3cc9144 in _dl_catch_error () at /usr/lib/libc.so.6
#7  0x00007ffff7deb31a in _dl_open () at /lib64/ld-linux-x86-64.so.2
#8  0x00007ffff5985e86 in  () at /usr/lib/libdl.so.2
#9  0x00007ffff3cc9144 in _dl_catch_error () at /usr/lib/libc.so.6
#10 0x00007ffff5986587 in  () at /usr/lib/libdl.so.2
#11 0x00007ffff5985f22 in dlopen () at /usr/lib/libdl.so.2
#12 0x00007ffff692a548 in  () at /usr/lib/libQtCore.so.4
#13 0x00007ffff6925319 in  () at /usr/lib/libQtCore.so.4
#14 0x00007ffff69254b9 in QLibrary::resolve(char const*) () at /usr/lib/libQtCore.so.4
#15 0x00005555556e7556 in disableAutoKeyAccelerators(QWidget*) (mainWindow=mainWindow@entry=0x555555d29e50) at /home/martin/lmms-build/lmms/src/gui/MainWindow.cpp:75
```
Closing this as a duplicate of #4030.

**Closed by PhysSong** 2017-12-06 01:39 UTC
