### ISSUE TITLE
Can't Open a Project

### ISSUE THREAD

**Issue by cactusguy2013** [LMMS/lmms#2229] opened 2015-08-01 22:19 UTC
I saved a project I was making and next time I opened LMMS it open the settings menu that opens when you first open LMMS and I just clicked ok and when I opened that project this error came up:

The file C:/Users/Christopher/lmms/projects\ProgressiveHouseBass.mmpz seems to contain errors and therefore can't be loaded.

But all my other projects will open.

**Comment by softrabbit** [comment] 2015-08-03 06:49
Could you put the file somewhere for download and examination?

**Comment by musikBear** [comment] 2015-08-03 10:45
and this belongs in forum 'Troubleshooting' 
http://lmms.io/forum/viewforum.php?f=7
right now, you need to look for a file : **recover.mmp** 
MOVE that file!!
Do not open other projects
You may also have a file named 
**ProgressiveHouseBass.mmpz.bak**
Keep that safe
If the current project has a size < 3-5kb, it is most likely completely empty. If you know what you did as you saved the file, it would be very interesting to learn that

Personally, i have never had this issue, but have tried to help a handfull of peeps now, with exactly that problem. The mppz has NO data at all

**Comment by cactusguy2013** [comment] 2015-08-04 07:35
The file ProgressiveHouseBass.mmpz has a size of 14kb and unfortunately there is no file ProgressiveHouseBass.mmpz.bak nor a file recover.mmp.

**Comment by cactusguy2013** [comment] 2015-08-04 07:42
And you should be able to download this softrabbit http://www.mediafire.com/download/fieve0a8bex4qww/ProgressiveHouseBass.mmpz

**Comment by michaelgregorius** [comment] 2015-08-04 18:12
I have just checked the provided file `ProgressiveHouseBass.mmpz` with `hexdump` and it only contains zeros:
```
[Downloads]$ hexdump ProgressiveHouseBass.mmpz
0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
0003790 0000 0000 0000 0000 0000 0000 0000     
000379d
```
So in case this file was indeed written by LMMS and was not corrupted by some other process something has gone _really_ wrong.

**Comment by tresf** [comment] 2015-08-22 03:20
Insufficient steps to reproduce.  Closing as invalid.  Please reopen if you can offer steps to reproduce.

**Closed by tresf** 2015-08-22 03:20 UTC

**Comment by Monospace-V** [comment] 2022-04-16 12:13
I got a similar error. Mine was also on a ~14 kb file. The bak file was recoverable. But I couldn't reproduce. The file name was "[Nevada-Vicetone2.mmpz](https://drive.google.com/file/d/1b3pd_3-8dxaTEoxH_nBBNzBmHSRdmAAl/view?usp=sharing)" and it is this large:
![image](https://user-images.githubusercontent.com/76674645/163674207-2abb6cab-3eb9-4eba-a248-3930cfe36ead.png)
And is full of blank spaces, much like the above file.
[This](https://drive.google.com/file/d/1icOIMjQ46u8TANzyIVhPb5VdtBDIsqme/view?usp=sharing) is the bak file. I don't remember exactly what changes I made, so I'm afraid I cannot help here. Plus, even re-saving randomly without any changes seems to change the size of the mmpz file.

**Comment by musikBear** [comment] 2022-04-16 16:41
Looks like a file that was deliberately overwritten with NULL. There are several programs that does that, _Shredders_.
Firefox also have a shredding-feature..
Serious odd fail : |
Saved with low battery ?

**Comment by Monospace-V** [comment] 2022-04-17 02:40
I use a desktop computer, and don't have Firefox.

**Comment by Monospace-V** [comment] 2022-04-19 10:56
I got the error ~99 kb of a project. Triggered when my computer BSOD'ed at me when I woke it up from sleep. It was a recover.mmp I discarded a moment too fast. (Can I modify the number of recover.mmps I can save?) I'm not sure if it was the same problem, but the error was still this.

**Comment by zonkmachine** [comment] 2022-04-19 12:23
> Can I modify the number of recover.mmps I can save?

No

**Comment by musikBear** [comment] 2022-04-19 15:31
> I got the error ~99 kb of a project. **Triggered when my computer BSOD'ed at me when I woke it up from sleep**. It was a recover.mmp I discarded a moment too fast. (Can I modify the number of recover.mmps I can save?) I'm not sure if it was the same problem, but the error was still this.

I thought you used **win10**. BSOD should not happen on win10 afaik ?....
Thats a surprise!

**Comment by Monospace-V** [comment] 2022-04-19 15:45
> I thought you used **win10**. BSOD should not happen on win10 afaik ?.... Thats a surprise!

https://www.google.com/search?q=bsod+windows+10&tbm=isch
Windows 10 is infamous for its BSODs. To the average user, they're not typical, but this is my third BSOD in the past two years (and I suppose it could've been worse, but sometimes my computer doesn't even wake up from sleep and needs to be restarted).
I don't suppose you're familiar with the vague stopcode "REGISTRY_ERROR".
But that's a separate problem... I hope.

**Comment by tresf** [comment] 2022-04-19 16:04
> But that's a separate problem... I hope.

Agreed.  We're getting a bit off-topic.  Although "BSOD" may be red or surface in other areas, the idea of a critical OS failure is present on all versions of all operating systems and if this occurs during a write operation, can result in a partial-write.  Software which utilized high CPU as well as software which talks directly to hardware is even more prone to these types of crashes.

What's important to know from a project-perspective is if the issue is avoidable or not, which is often hard to determine, hence this bug report being open for 7 years before ultimately being closed. 🍻
