### ISSUE TITLE
LV2 Combo Boxes/Dropdowns jumbled causing incorrect export.

### ISSUE THREAD

**Issue by consolegrl** [LMMS/lmms#6859] opened 2023-09-10 05:11 UTC
### Bug Summary
LV2 combo box/dropdown options are not stable across loading or exporting. The LV2 combo options seem to always load and export in a different order.

Details:
When I export a project using the MDA MultiBand [compressor] plugin (or any LV2 plugin with a combo box) the 'Output' option I've selected from the 'Listen' combo box gets jumbled. The reason this is a problem is because the Listen setting on this LV2 determines what to output to the track. I keep setting it to 'Output' but always after the export completes it changes to some other value and the rendered audio has used that other value. As a result the audio will be either high-passed, low-passed, or band-passed and doesn't sound anything like the expected output. Every time I export it jumps to a new value.

#### Steps to reproduce
1. Have the 'MDA MultiBand' LV2 plugin (or any LV2 plugin with a combo box/dropdown)
2. Make some full-spectrum test track (so its easy to hear the diff in step 6)
3. Apply the 'MDA MultiBand' plugin (or any LV2 plugin with a combo box/dropdown) to one of the mixer tracks.
4. Set it to 'Output' and listen in LMMS
5. Export track with default settings.
6. Listen to exported audio, its totally different.
7. Be sad :(

#### Expected behavior
The selection made in the combo box on the 'MDA MultiBand' LV2 plugin does not change just before exporting begins, or ever, until the user changes it themselves.

#### Actual behavior
The selection in the combo box on the 'MDA MultiBand' LV2 plugin changes seemingly at random, when loading or exporting the project.

#### Screenshot
Pre-Export
![combo_jumble_pre](https://github.com/LMMS/lmms/assets/5942029/12629e11-2926-433c-b225-79185c7e44d9)

Post-Export
![combo_jumble_post](https://github.com/LMMS/lmms/assets/5942029/0b686684-b7dd-4a54-a07b-bfe53454b0fa)

Pre-Export Example #2
![combo_jumble_pre2](https://github.com/LMMS/lmms/assets/5942029/d5d6b3c7-5a5e-4b77-8cab-daf785313222)

Post-Export Example #2
![combo_jumble_post2](https://github.com/LMMS/lmms/assets/5942029/39d593d4-a4e6-443c-a0f9-b3db66496391)

#### Affected LMMS versions
1.3.0-alpha (master)

**Comment by zonkmachine** [comment] 2023-09-10 14:23
Same as this issue? https://github.com/LMMS/lmms/issues/6847

**Comment by consolegrl** [comment] 2023-09-11 04:53
@zonkmachine Related I believe, but this isn't just saving, it's exporting as well when this happens.

**Comment by M4rotte** [comment] 2023-09-11 22:51
I confirm. After the export has finished. Without even reopening the file the value in drop-down menu has changed. And, as @consolegrl said, the change is one before the export because that’s those erroneous value which are used for the export.

**Comment by zonkmachine** [comment] 2023-09-12 14:22
Testing this now and I really think it's the same issue. When I export just one note on Calf Wavetable (I loop 99 times to be able to catch what's going on), the menus are scrambled twice. First when the export has started and then once more at the end of the export.

**Comment by M4rotte** [comment] 2023-09-13 18:55
The problem also appears in the recovery functionality.

**Comment by zonkmachine** [comment] 2023-09-13 18:57
> The problem also appears in the recovery functionality.

Which is performing ordinary file load so this is expected.

**Comment by JohannesLorenz** [comment] 2023-09-13 21:00
One major difference between the issues reported is that in the other issue (#6847), it is says that only the combo changes and the sound is unchanged. However, here, it says that the sound does change.

If I take the example of the OP of this thread, save it and reload it, then I do get sound changes. So I think the description in #6847 was just wrong.

**Comment by JohannesLorenz** [comment] 2023-09-13 21:27
Not related to #6799 , as suggested.

**Comment by JohannesLorenz** [comment] 2023-09-24 15:40
Funnily, this bug has already been fixed on #6484 for a year, and today that branch was merged to master. I tested the issue from the original post here as well as #6847 and could not reproduce either. Please feel free to test with a fresh master, otherwise I will close this in a few days.

**Comment by zonkmachine** [comment] 2023-09-24 22:06
> One major difference between the issues reported is that in the other issue (#6847), it is says that only the combo changes and the sound is unchanged.

No, it's maybe not mentioned explicitly but the sound changed according to the setting changes.

> Funnily, this bug has already been fixed on #6484 for a year, and today that branch was merged to master. I tested the issue from the original post here as well as #6847 and could not reproduce either. Please feel free to test with a fresh master, otherwise I will close this in a few days.

I have tested #6859 and #6847 and both seem fixed.

**Comment by zonkmachine** [comment] 2023-09-24 22:07
Closed as fixed in https://github.com/LMMS/lmms/pull/6484

**Closed by zonkmachine** 2023-09-24 22:07 UTC
Labels: bug
