### ISSUE TITLE
some vsts do not open after saving them

### ISSUE THREAD

**Issue by killjoyrekt** [LMMS/lmms#3819] opened 2017-09-22 19:31 UTC
I just tried to use the orion sound module and everytime that i use it, it works fine until i save and open the project again, this crashes lmms and makes it unresponsive. After i force quit the application, a popup says that the instrument failed to load (it says maize sampler player) also, anything made with maize sampler player doesnt work and reacts the same way as the orion sound module. pls help

**Comment by tresf** [comment] 2017-09-22 19:36
@killjoyrekt thanks for the bug report.  This is most likely a duplicate of #3776 or #3805 (#1008, #1183, #3274).  These patches will be made available in the next beta version, 1.2.0-RC4.  We'll post an update on Facebook as soon as it's released.

I'm going to mark this as duplicate.  Please ask us to reopen it if RC4 does not fix your issue.

**Closed by tresf** 2017-09-22 19:36 UTC
