### ISSUE TITLE
All-in one editor windows and editing toolbar

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1969] opened 2015-04-17 18:53 UTC
In A Better Transport #1357 I  moved a lot of stuff so now you have room for a the all editing toolbar:

The copy, cut, paste options should be in the Edit Menu.
The Razor/Glue Tool #746  should be on all toolbars and work on audio clips and not just on midi clips. The eraser is  delete for all clips and automation or midi, double click to a clip to open the clip. The zooms are an all purpose ie you can use them on anything and everything in Song or B&B Editor.

Toolbar Keyboard Shortcut Table:

Add Tracks Keyboard Shortcut:

Add Sample Track  keyboard shortcut could be ALT T.
Add B&B Track  keyboard shortcut could be ALT B.
Add Automation Track  keyboard shortcut could be ALT A.

Zoom Tool Keyboard Shortcut: 
To zoom in up and down keyboard shortcut could be CTRL 1 in CTRL 2 out.
To zoom in side to side keyboard shortcut could be ALT 1 in ALT 2 out.
To rest all zooms  keyboard shortcut could be CTRL 0.

Automation Lines Tool Keyboard Shortcut: 
Line Type 1 keyboard shortcut could be CTRL 3.
Line Type 2  keyboard shortcut could be CTRL 4.
Line Type 3 keyboard shortcut could be CTRL 5.

Edit Tool Keyboard Shortcut:
Edit Mode Tool keyboard shortcut could be CTRL E.
Draw Mode Tool keyboard shortcut could be CTRL D.
Eraser Mode Tool keyboard shortcut could be ALT E.
Razor Mode Tool keyboard shortcut could be ALT R.
Glue Mode Tool keyboard shortcut could be ALT G.
Mute Clip Tool keyboard shortcut could be CTRL M.

B&B Editor Toolbar
![b b editor toolbar](https://cloud.githubusercontent.com/assets/8137561/7208344/ca1ff0cc-e505-11e4-8c55-8dab326c1f5d.PNG)

Song Editor Toolbar
![song editor toolbar](https://cloud.githubusercontent.com/assets/8137561/7208371/f573be98-e505-11e4-96dd-3b9fd31f6203.PNG)

The all in one editor windows:

IE Reason
![automation_small 1](https://cloud.githubusercontent.com/assets/8137561/7208467/aff2fd92-e506-11e4-8c7b-7022389e8b1a.jpg)
![reason_part3_midi2 1](https://cloud.githubusercontent.com/assets/8137561/7208492/d8011be8-e506-11e4-97cf-af6118ffdce2.jpg)

This will help in New UI Concept - Single Window #1911, if this work it'll simplify the this will help in New UI Concept - Single Window.

The Simplified Single Window
![the simplified ui single window](https://cloud.githubusercontent.com/assets/8137561/7212861/f4c3cc26-e533-11e4-8f79-d8334f09beb7.png)

**Comment by Umcaruje** [comment] 2015-04-17 19:07
Why would you have controls from the automation editor in the B&B editor? 

This doesn't make any sense

**Comment by Reaper10** [comment] 2015-04-17 19:27
You have the controls from the automation editor in the B&B editor for when you have a automation track in the B&B editor this way the toolbar is all in one .

**Comment by tresf** [comment] 2015-04-17 19:29
@Umcaruje is right in this instance.  We wouldn't combine the toolbars unless the editors allowed it.

**Comment by Reaper10** [comment] 2015-04-17 19:34
This will help in a New UI Concept - Single Window #1911

**Comment by Reaper10** [comment] 2015-04-17 23:31
just an idea

**Comment by Reaper10** [comment] 2015-04-18 00:05
This will help in Simplifying the  Single Window.

The Simplified Single Window
![the simplified ui single window](https://cloud.githubusercontent.com/assets/8137561/7212861/f4c3cc26-e533-11e4-8f79-d8334f09beb7.png)

**Comment by tresf** [comment] 2015-04-18 00:12
Stop bumping your own posts with no content.  Deleted, deleted, deleted.

**Comment by tresf** [comment] 2015-04-24 14:33
This is really a direct duplicate of #1911.  We know we'll need to move our buttons for single-window and we don't need another bug report to track the granular details of that unless we start development, which we haven't.

In regards to the keyboard shorcuts, we have #1488 to track that.

Lastly, please taking screenshots of commercial software.

**Closed by tresf** 2015-04-24 14:33 UTC
