### ISSUE TITLE
Cutting tool or block divider

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4633] opened 2018-09-29 01:59 UTC
Hi guys. In lms you need a cutting tool or block splitter in the song editor, to divide any type of block of all editors. For this function it would be necessary to put a button in the song editor and a shortcut key. more or less it would look like this:

![antes cortador de clips](https://user-images.githubusercontent.com/26127693/46239543-c04b2c80-c367-11e8-81c9-75441fd43620.png)

The tool would work like this:

1. First we place the reproduction pointer in the part of the block where we will make the cut.
2. Then we select the block with the selection tool
3. Then we press the cut or divide button in the song editor.

Once the cut is made, the block is divided. and the pencil tool is automatically inserted.
![despues cortador de clips](https://user-images.githubusercontent.com/26127693/46239658-47e56b00-c369-11e8-8b82-2809268534a1.png)

And you can already use the two parts of the file, they are divided and independent.
![despues cortador de clips divididos](https://user-images.githubusercontent.com/26127693/46239666-867b2580-c369-11e8-88fe-cb38ad5dbb48.png)

This tool is much needed, it would be quite useful. regards

**Comment by Daniele71** [comment] 2018-09-29 14:36
I agree and I'm wonder why a so basic feature is still missing..

**Comment by musikBear** [comment] 2018-09-29 16:16
duplicate? -surely i have seen this before, but cant find it...

**Comment by tresf** [comment] 2018-09-29 16:16
Duplicate of https://github.com/LMMS/lmms/issues/746.

> I agree and I'm wonder why a so basic feature is still missing..

Because no one's coded it.  Don't be ridiculous. :D

**Closed by tresf** 2018-09-29 16:17 UTC
