### ISSUE TITLE
Beat/Bassline editor: Color dots to track color

### ISSUE THREAD

**Issue by OlliO6** [LMMS/lmms#6650] opened 2023-02-18 14:48 UTC
I suggest coloring the green dots you place in the beat/bassline editor to the color of the track. Like e.g. automation tracks already do in the beat/bassline editor.

So this...
![image](https://user-images.githubusercontent.com/104021024/219871505-79661bf7-c284-43e1-8e6f-8908d1bb8bbf.png)
Would become like this...
![Screenshot 2023-02-18 154145](https://user-images.githubusercontent.com/104021024/219872044-eab61e3c-eba5-4c2f-b656-cd8bf013b79a.png)

Edit: Changing the background color could also be a solution.

**Comment by RoxasKH** [comment] 2023-02-20 10:49
Beat&baseline editor “dots” are at the moment loaded as images and not dinamically, so changing the color is not an option I think, especially on a custom theme like the one you are using.
The idea is kind of good I guess, but it’ll need to have those drawn dinamically.
Obviously I’m not that much in the code (and I think qt has some kind of image manipulation, although I don’t think it’d be that useful) so correct me if I’m wrong.

**Comment by allejok96** [comment] 2023-05-03 20:43
Duplicate of #2314 consolidated into [the TODO list](https://github.com/LMMS/lmms/issues/4877)

**Closed by allejok96** 2023-05-03 20:43 UTC
Labels: enhancement
