### ISSUE TITLE
Microtonal

### ISSUE THREAD

**Issue by powolny** [LMMS/lmms#5931] opened 2021-03-03 22:30 UTC
Microtonal
Microtone tuning is only available on the ZynADDSubFX
Perhaps it is worth doing a global microton tuning.
Fractional notes sound clearer.

Marcin

**Comment by qnebra** [comment] 2021-03-03 22:36
https://github.com/LMMS/lmms/pull/5522

**Comment by Spekular** [comment] 2021-03-03 22:58
Duplicate of #1387

**Closed by Spekular** 2021-03-03 22:58 UTC
Labels: enhancement
