### ISSUE TITLE
Allow saving external samples into the .mmp file

### ISSUE THREAD

**Issue by russiankumar** [LMMS/lmms#5551] opened 2020-07-01 05:08 UTC
### Enhancement Summary
This is an idea borrowed from Blender. Blender allows saving external textures, data, etc etc in the project file, which allows for easier sharing over the internet, or say opening the project on a laptop (when the project was made on a desktop) where you don't have enough storage space to store your massive sample library. I don't believe any other DAW has this and it would be a really nice feature to have.

#### Justification
- Projects are a lot more portable this way, meaning you can work on-the-go even if you made the project on a production desktop, which is always a good thing
- Collabing would be a lot easier too, which is something valued in the music industry
- Few (if any) DAWs have this feature

#### Mockup
There's no mockup for this since it's not graphical interface related.

### Final Notes
I think a menu option under the File menu saying "Attach samples" or "Attach files" (naming can be decided later) can be used to access this feature. We could also have this exist only in a .mmp file, so .mmpz files are not affected and remain small-sized.

I myself have already authored a pull request (#5543), so I believe if I am guided by the pros on some aspects of this, I may be able to figure this out myself. But until I figure out something, this feature request is open to all for review, and potential development by someone else.

**Comment by Spekular** [comment] 2020-07-01 09:35
Duplicate of #4922

**Closed by Spekular** 2020-07-01 09:35 UTC
Labels: enhancement

**Comment by qnebra** [comment] 2020-07-01 12:19
Well, Cakewalk save project in that way. When user save project in Cakewalk program create new folder with desired filename, and inside this location it save project file and copy of corresponding samples.
