### ISSUE TITLE
Oversampling changes pitch with .ds files

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6314] opened 2022-02-18 10:53 UTC
The last similar issue of pitch change with oversampling was for AFP files in general, and closed at the end of 2019. This one is specific to .ds files.

### Bug Summary
Oversampling, on export, changes the output pitch of a ds (drumsynth) file note in an AFP instance.

#### Steps to reproduce
1. Open the sidebar and navigate to My Samples
2. Open the drumsynth folder, drag in any of the samples
3. It creates an AudioFileProcessor instrument track. Open the Piano Roll of this track and place a note there
4. Export a wav file on normal settings
5. Export a wav file with settings set to a non-default oversampling.
6. Listen and compare.

#### Expected behavior
Both sound more or less the same

#### Actual behavior
Their pitches are different

#### Affected LMMS versions
1.3 alpha. (1.2.0 is also affected, but in a different way, and I have reason to believe that specific odd bug was fixed.)
1.3 alpha makes it clear that the problem is a pitch difference.

![image](https://user-images.githubusercontent.com/76674645/154668973-c639ebb0-8afa-4ceb-b308-957137032707.png)
(Downloaded from the recent PR that uses automation track for MIDI program change events)

**Comment by RiedleroD** [comment] 2022-02-18 19:11
wth I can reproduce… but why? It's just a sample, and regular ones don't have this issue.

I'll investigate further

**Comment by softrabbit** [comment] 2022-02-18 21:05
Duplicate of #6087, I believe. There's a bunch of magic numbers in the drumsynth code and they should be adapted to fit the sampling rate.

**Comment by zonkmachine** [comment] 2024-04-10 19:03
Issue confirmed, but it looks like it was fixed in https://github.com/LMMS/lmms/commit/ce722dd6b6cdfa5c7378161ce7d1fa98bfe5fec2 / https://github.com/LMMS/lmms/pull/6610

**Comment by zonkmachine** [comment] 2024-04-12 16:20
^Closed as fixed. Please reopen this issue if you can still replicate it on master.

**Closed by zonkmachine** 2024-04-12 16:20 UTC
Labels: bug
