### ISSUE TITLE
[Song Editor] Select + Delete doesn't work

### ISSUE THREAD

**Issue by notorand-it** [LMMS/lmms#1853] opened 2015-03-10 16:45 UTC
In v1.1.3, while in the song editor, if I select a group of "phrases" with the selection tool (drag the rectangle to select), then I cannot simply hit DEL or LeftButton+Delete to delete.
I am forced to delete the phrases one by one.
I would say that deletion should apply to all selected phrases.

**Comment by tresf** [comment] 2015-03-10 16:51
Yes, we are aware.  This is really a duplicate of #46, which has been closed.  We expect to roll out a beta version of the 1.2 branch in the coming month or so. :+1: 

Closing, marking as duplicate of #46.

**Closed by tresf** 2015-03-10 16:51 UTC
Labels: duplicate

**Comment by farvardin** [comment] 2020-03-01 19:14
This issue was closed, and all the other ones related to this, but it's still not possible to delete multiple blocks in the song editor, even in version 1.2.1

**Comment by DomClark** [comment] 2020-03-23 23:11
Unfortunately this didn't make it into the 1.2 series, but has been implemented on the master branch and will appear in 1.3.
