### ISSUE TITLE
note-block context menu : Clean all notes If vol <= 1

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2155] opened 2015-07-03 13:57 UTC
If someone would implement a new item in _note-block context menu_ allowing the user to delete notes in _that specific block_, if note-volume <=1, then LMMS has ghost-notes!
( '0' may be too hard a rule, '0.1' would properly be fool-safe

First a dev need to chime in and say if this can be done relatively 'easy', and without conflicts, then  this can function as perfect ghosts-notes, in combination with other already existing features:

Take the block you want as ghost
Duplicate it to the track where you want to compose over the ghosts
Mark all
Drag volume to 0
Move these note one semitone up
Unmark all
Compose -except, dont place notes _on_ the existing notes, instead place notes one semitone below 'ghosts'
Close piano-roll
Open my requested new method
Delete all 0-vol notes ('ghosts')
Job done

But -can _'delete all notes with volume < 1'_ be implemented ?
Or does noone care :p

**Comment by curlymorphic** [comment] 2015-07-16 12:14
This does not sound like a correct solution to me, more of  work around, with the key feature to this workaround being an unimplemented hack.

If there is a valid use for this function, or if it can be decided that this is a valid use case, I can see no reason why this could not be implemented with relative ease in the piano editor.

**Comment by tresf** [comment] 2015-07-16 12:29
@musikBear can you please remove the creeper wording from the title and body. ![image](https://cloud.githubusercontent.com/assets/6345473/8722645/b5bbcf90-2b94-11e5-85eb-fd1db27b8f6d.png)

**Comment by tresf** [comment] 2015-07-16 12:30
> First a dev need to chime in and say if this can be done relatively 'easy', and without conflicts, then this can function as perfect ghosts-notes, in combination with other already existing features:

First, you explain the problem, how to reproduce, and in this case your proposed workaround. :+1:

**Comment by musikBear** [comment] 2015-07-16 15:03
@curlymorphic i understand what you mean. There is no real general benefit from deleting notes < 1 in *other* circumstances, that is true.
I actually also thought of two different ways to accomplish the same thing
The first has to do with the behavior in piano-roll's volume-section.
Current right-mouse implementation will delete the notes if the mouse **passes** the bar. 
If the delete behavior was redesigned  to *selection* and restricted to collision with the bar, the same workflow could be achieved. This behavior could be more general useful, but also a more complex method.

The 2. thought i had, was addressing the behavior in general selection.
Current design will de-select all selected notes in piano-roll, when a new note is inserted. 
If the selections could be preserved, until the user made a deliberate action, then it would also be possible to get rid of the 'ghosts' after composing.
Again this method could have several general usages, but i again saw this as a more complex implementation.
If you have any thoughts around this, in respect to complexity and or usability, i would be very interested. (unfortunately your fine tutorial on QT, made me realize, that i do not have hw remotely sufficient for working on lmms, besides that i am also only capable in AS for flash, cpp has a much higher complexity level, but my inadequateness is not relevant here :)

**Comment by zonkmachine** [comment] 2017-12-12 12:39
> then LMMS has ghost-notes!

Right. If I understand this correct you are suggesting a method to implement 'ghost notes' but this already has an issue of it's own. Closing this as a duplicate of https://github.com/LMMS/lmms/issues/520.

**Closed by zonkmachine** 2017-12-12 12:39 UTC
