### ISSUE TITLE
Render Loop Is Not Seamless

### ISSUE THREAD

**Issue by toliaferrode** [LMMS/lmms#2852] opened 2016-06-16 04:15 UTC
I often have to edit my loop in Audacity to get a nice seamless loop with no popping of any kind because on exporting a loop LMMS adds silence before the loop starts.

**Comment by tresf** [comment] 2016-06-16 04:18
Possible duplicate of https://github.com/LMMS/lmms/issues/1484

**Closed** 2016-06-16 19:50 UTC
Labels: duplicate
