### ISSUE TITLE
popup 'project version mismatch' imo anoying

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2656] opened 2016-03-09 18:26 UTC
Its this one
![projvermismatch](https://cloud.githubusercontent.com/assets/6662066/13645543/bcd85f44-e62b-11e5-8cfe-a74fff6f9fca.png)
The user cant do anything, except clicking it away. Why does lmms show that popup?
Even the project used *here* made on 0.4.0 'cool-songs/Chris-RaveRiff.mmpz' *loads* and plays just fine. Imo popping that message will only worry some users, and for no reason. Stoneage projects still work.
The fact that cool-songs has projects from 2003 is a different issue :angel:

**Comment by tresf** [comment] 2016-03-09 18:28
Duplicate of https://github.com/LMMS/lmms/issues/432.

**Closed by tresf** 2016-03-09 18:28 UTC

**Comment by tresf** [comment] 2016-03-09 19:27
@musikBear 

A few items about this bug report... 

 1. Search before submitting.  This is a feature was implemented in #432 as a collaboration between @Spekular and myself.  It's intended.
 2. Your title is horrible.
   * Current title:

   > popup 'project version mismatch' imo anoying

   * Better title:

   > Remove project version warnings for bundled tracks

 3. Which brings us to WHY these messages appear... They appear because the tracks haven't been tested in a newer build of LMMS.  This is evident when plugins fail to load, etc.  For example, `Zakarra-MainstreamMemory.mmpz` has three files that fail to load.

 4. And to our final point... how you can help and make this bug report relevant?  Best way is to override the software version (force `1.2.0`) and then fix these tracks.  If you can fix the tracks, a developer can do the versioning.

Remember, 1. Describe the problem, 2. Explain how to reproduce, 3. Try to leave your opinion and emotions for last. :+1:   We shouldn't be lecturing senior bug reporters about good bug reports, you should be setting the example for the rest of the world. :earth_asia:

**Comment by musikBear** [comment] 2016-03-09 21:21
I agree, i should have noted a way to reproduce, i just thought everyone knew. My bad. Added.
I dont know how i should have searched for the issue. 432 does not contain the words on the popup. Even the word popup is not in the text. I have often problems finding a ticket. Even those i know exists.
