### ISSUE TITLE
Time Signature suddenly resets during first 2 measures

### ISSUE THREAD

**Issue by JohnDorsey** [LMMS/lmms#3029] opened 2016-09-10 00:44 UTC
On occasion, an LMMS project will become "damaged" in some way, and get a 2 measure long area at the beginning of the project during which a certain number is repeatedly reset to an old value you set it to in the past. I've also had this happen with the master volume.

this project reliably demonstrates the bug:
[reset proof empty project (with BAK).zip](https://github.com/LMMS/lmms/files/465121/reset.proof.empty.project.with.BAK.zip)

if you set the time signature to any value and play the project, it will become 11/8.
if an automation track is created to hold the time signature at some other value, the project will fight that automation track, and the time signature will visibly flicker between 11/8 and the value in the track.

after the first few measures, the project seems normal in every way.

**Comment by tresf** [comment] 2016-09-10 01:41
@JohnDorsey thanks for the bug report.  This is most likely a duplicate of https://github.com/LMMS/lmms/issues/1252. Please confirm and close this bug report if needed.

**Closed** 2016-09-10 18:31 UTC
