### ISSUE TITLE
Map Midi Keys With Sample Sounds

### ISSUE THREAD

**Issue by myeh2k** [LMMS/lmms#2370] opened 2015-09-22 01:59 UTC
I want to know if I am able to set keys on my midi keyboard (Korg NanoKey2) to play different sounds, almost like a sound board.

For example:
C3 = Sound1.wav
D3 = Sound2.wav
E3 = Sound3.wav

**Comment by tresf** [comment] 2015-09-22 02:27
@myeh2k no, not currently.  This is a duplicate of a few bug reports, namely https://github.com/LMMS/lmms/issues/1460 https://github.com/LMMS/lmms/issues/2134 https://github.com/LMMS/lmms/issues/1087 https://github.com/LMMS/lmms/issues/1381

Partly achievable via https://github.com/LMMS/lmms/pull/2185 although this would still be very manual and this specific pull hasn't been merged yet.

Closing, making as duplicate.  Also, our [forums](http://lmms.io/forum/) are probably a better place to ask general help questions. :+1:

**Closed by tresf** 2015-09-22 02:27 UTC

**Comment by tresf** [comment] 2015-09-22 02:28
Also, I'd like add that a potential work-around in our current version is to make a soundfont which contains the desired samples at the desired notes, but making a soundfont can be some work.
