### ISSUE TITLE
MIDI output (maybe input too) routing in instrument lost if channel does not exist on startup

### ISSUE THREAD

**Issue by jackokring** [LMMS/lmms#2454] opened 2015-11-21 22:24 UTC
Just a minor point, but it does insist on a load order, or could be detrimental on opening a song on new computer before config (for which you'd need to see the MIDI).

Create a beats pattern say with kicker.
Open instrument MIDI tab.
Select MIDI output active.
Select a MIDI interface from an available extra route.
Save project.

Close the MIDI device via shutting down the MIDI sink.

Open the project.
Look at MIDI assignment of instrument.

Open the external MIDI sink.
Play.

**Comment by tresf** [comment] 2015-11-21 22:37
@jackokring thanks for the bug report.  Can you please adjust your original post to illustrate step-by-step instructions to reproduce?

It may seem obvious, but the bug description should always exist in the body of the bug report.  The title should be used as a quick summary to locate it in the tracker listing.

**Comment by softrabbit** [comment] 2015-11-22 09:41
Duplicate of #1731?

**Comment by Umcaruje** [comment] 2016-01-24 22:07
>Duplicate of #1731?

@jackokring hasn't responded, and the problems do sound similar, closing, marking as duplicate. Feel free to reopen if you think I was wrong.

**Closed by Umcaruje** 2016-01-24 22:07 UTC
