### ISSUE TITLE
Changing BPM on sliced samples is broken

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#6465] opened 2022-07-19 12:07 UTC
### Bug Summary
As the title says, when you change the BPM of your song after having correctly sliced one or more samples according to your needs, will mess up with the sample, considering the start of the clip the original start of the sample and not where you sliced it/them.
Having this behaviour will need a rerender of the sliced part everytime you wanna change bpm and it's not comfortable.

#### Steps to reproduce

1. Open LMMS and load up a sample, then set the bpm as the sample sayd to have it playing in time.

![immagine](https://user-images.githubusercontent.com/40141826/179744620-235d1535-ab5f-4656-be1b-d120c5aeb712.png)
![immagine](https://user-images.githubusercontent.com/40141826/179744745-baa761ae-424b-400c-88aa-081cc8348209.png)

2. Slice the sample as you please

![immagine](https://user-images.githubusercontent.com/40141826/179745074-f05e5b82-3324-43b3-9978-bd547a443175.png)

3. Now change the BPM of the track as you may prefer (imagining you've changed idea on how fast you want the song to be)

![immagine](https://user-images.githubusercontent.com/40141826/179745360-b1d8cb18-a87c-44ef-943c-f31e8beec476.png)

As you can see the end result is broken and not what you chose to slice out of the original sample.

#### Expected behavior
The expected behaviour can be seen in FL Studio following the same steps

Sliced sample before changing the BPM
![immagine](https://user-images.githubusercontent.com/40141826/179746208-b2d41f61-ff96-4de5-9be4-96ada6a24797.png)

After changin the BPM
![immagine](https://user-images.githubusercontent.com/40141826/179746302-4ea060a3-d467-4de5-8b62-df48d2f65a0e.png)

#### Affected LMMS versions
LMMS 1.3.0 Alpha 1.102, Windows 10 Home 64bit

**Comment by Spekular** [comment] 2022-08-19 03:09
Unrelated to the knife tool and duplicate of #4153

**Closed by Spekular** 2022-08-19 03:09 UTC
Labels: bug

**Comment by allejok96** [comment] 2022-09-01 15:26
I was going to agree with you @RoxasKH that this bug report brings to light something not mentioned in the other one...

Then I realized that @Spekular is right. Both bugs are due to SampleClip storing it's length and offset as a TimePos. A TimePos is affected by BPM, but it stays constant in relation to the rest of the song.

If sample clip instead stored it's length and offset as number of sample frames it would stay constant in relation to the sample itself, but vary in relation to the rest of the song.

Probably the easiest solution would be to just recalculate these two values on a BPM change.
