### ISSUE TITLE
"Crunchy sound" using the Peak Controller

### ISSUE THREAD

**Issue by SimoneIervasi** [LMMS/lmms#2534] opened 2016-01-30 13:34 UTC
Hi! I've got this problem: everytime i use the Peak Controller (for sidechain-pumping compression) the sound becomes dirty, full of "crunchy noise", it happens especially with basses (and low frequencies in general).
Thanks for the attention.

Simone

**Comment by eagles051387** [comment] 2016-01-31 07:13
Good Morning Simone,

Can you provide the necessary steps to reproduce and maybe a sample file
where you are seeing this occur please.

Jonathan Aquilina

**Comment by SimoneIervasi** [comment] 2016-02-01 14:22
I think it's a duplicate of #1281   
However i'll try to make a sample for let you hear the crinkle noises i'm talking about.

**Comment by Umcaruje** [comment] 2016-07-31 23:23
>I think it's a duplicate of #1281

Indeed. And the issue is closed as fixed. Closing

**Closed by Umcaruje** 2016-07-31 23:23 UTC
Labels: needs clarification

**Comment by cnuptak** [comment] 2016-11-04 22:35
on lmms 1.1.3 still have this bug

**Comment by Spekular** [comment] 2016-11-05 09:00
IIRC the fix is in 1.2.
