### ISSUE TITLE
Dual filter highpass problem

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#4612] opened 2018-09-24 17:10 UTC
I'm having problem with the dual filter effect, what should i do?
When i activate an highpass on the master at 1hz at some point of the track with an automation, it does a strange thing, like volume turn down and the highpass is not at 1hz.
On dual filter, the mix button is totally to the left (so the highpass filter), and i have automations to decide the frequency, too. My automations chain is 'highpass activated (start at 1hz)', 'frequency go up', 'highpass disactivated', 'turn frequency to 1hz' and so on, for multiple times. Like in the image below.

![fx automations](https://user-images.githubusercontent.com/40141826/45966777-60cde380-c02c-11e8-866d-c38e2fd78406.png)

The first time the highpass is activated nothing happens, but from the second one happened the thing i said before. You can hear it here in a snippet on the track i'm working on at like 01sec: https://soundcloud.com/h4ckton3/a-1/s-ITbUR

It happen also on other parts of the track anytime the highpass is reactivated. I also post here an image of the waveform at that point if it could help (you can see it's weird).

![wave](https://user-images.githubusercontent.com/40141826/45967037-10a35100-c02d-11e8-8d71-2ad655f7580f.png)

What it could be? I guess maybe is the effect that answer too slow to the automation control (i hope you can get what i mean, i'm not english).

I really need to fix that, because my track is nearly finished and that's the only problem it has.
Thanks

**Comment by RoxasKH** [comment] 2018-09-28 17:46
Installing RC7 didn't solve it. I can avoid it by using several highpass filters on the master, but it's only turning around it. If someone will manage to fix it, please tell me

**Comment by RoxasKH** [comment] 2018-09-28 18:29
I don't reall get what you're saying (i'm not english), but as you can see in my automation chain, cutoff return to 1hz while the highpass is not activated, and only then i activate the highpass and cutoff turn gradually up,... Also this is how i wan the track to be to so i don't want cutoff to return down bef the drop.

P.S: Maybe i haven't understood well, if so, try explain it to me better, please

**Comment by RoxasKH** [comment] 2019-01-28 19:55
I really hope this will be solved, because i've just remastered the track i had this problem on, and after making all sounds good, even if i use 5 different instances of dual filter on the master, i can't totally solve the problem, and so i can't publish it. Also mantaining highpass filters always activated even with cutoff at 1 will make the track losing some bass frequencies.

**Comment by RoxasKH** [comment] 2019-01-28 21:05
I'll try reproduce it on an lmms-only project as soon as possible.

**Comment by RoxasKH** [comment] 2019-01-29 18:21
@zonkmachine Here it is
[DualFilterProblem.zip](https://github.com/LMMS/lmms/files/2809075/DualFilterProblem.zip)

**Comment by RoxasKH** [comment] 2019-01-29 18:23
The last two automations tracks are the Highpass Filter ones, and they are the ones that cause the problem

**Comment by noahb01** [comment] 2019-11-05 03:16
Potentially related to #1048.

**Comment by noahb01** [comment] 2019-11-05 03:18
What I experience is that when a filter rapidly has it's cutoff dropped to near-zero, it resonates like that for a few samples.

**Comment by zonkmachine** [comment] 2020-12-11 00:57
@RoxasKH I couldn't work with that large project and didn't see what you meant with it. I would appreciate a minimal version of that one to demonstrate just the bug and nothing else.

I tried and create a minimal project with just the described components and this is what I came up with:[dualfilter.mmp.zip](https://github.com/LMMS/lmms/files/5676425/dualfilter.mmp.zip)
It's a super beat with a high pass filter under automation and which has it's bypass controlled by an lfo. I do see glitches with it and it may be the same thing as you're describing. It's not a floating point error as it passed just fine under a debugger.

**Comment by RoxasKH** [comment] 2020-12-11 17:19
@zonkmachine I massively reduced the project, tell if it's still too much and i'm gonna recreate it even littler.
It wasn't so noticeable in your project so i'm not sure if it's the same thing.

[DualFilterProblem.zip](https://github.com/LMMS/lmms/files/5680603/DualFilterProblem.zip)

**Comment by softrabbit** [comment] 2021-04-08 14:10
This is a bit like plugging and unplugging wires, which can give you awful pops and clicks on the output if your gear is on.  

I believe the problem is that when the filter is bypassed, it won't be fed any audio. That might leave it in an less ideal state as the output depends on what has come before, and the stuff before is whatever there was when the filter was disabled. Am I making any sense here?

I'd suggest automating the wet/dry knob instead as a workaround.

**Comment by michaelgregorius** [comment] 2024-05-01 21:04
The problem is fixed by pull request #7237 which extends the `Effect` base class with a new virtual method that can be overridden to react to state changes with regards to being enabled/bypassed.

Currently only `DualFilterEffect` overrides this method by resetting it's two filters to get rid of the pops described in this issue.

While testing this I got one segmentation fault in `Effect::isRunning` but i was not able to reproduce it. So I would appreciate if this could be thoroughly tested.

**Closed** 2024-05-05 08:05 UTC
Labels: bug
