### ISSUE TITLE
VCV Rack VST hangs LMMS

### ISSUE THREAD

**Issue by liftarn** [LMMS/lmms#4320] opened 2018-04-24 20:36 UTC
When loading the [VCV Rack](https://github.com/VCVRack/Rack) VST it causes LMMS to hang.
Running on Win 10 64 bit.

**Comment by justnope** [comment] 2018-05-19 10:04
It works in 1.2.0-rc5. could you download it from https://github.com/LMMS/lmms/releases and check if you still have this issue?

**Comment by DomClark** [comment] 2018-05-20 15:19
I can reproduce this in RC5, it hangs on the `IdVstGetParameterDump` and `IdSaveSettingsToFile` messages at least (called when opening the control dialog and saving the project, respectively). I won't have time to investigate for another month; if anyone else wants to have a look in the meantime, feel free.

**Comment by justnope** [comment] 2018-05-20 16:03
Fixed in PR #4366 
Download https://gist.github.com/justnope/6c1ea70edaf83cb1acec4a1dc60dc92b and let me know if it works.

**Comment by DomClark** [comment] 2018-06-07 12:05
I can confirm that this seems to be fixed in RC6.

@liftarn Try downloading our latest beta version, and if you still experience the bug, please re-open this issue.

**Closed by DomClark** 2018-06-07 12:05 UTC
Labels: bug, vst
