### ISSUE TITLE
LMMS crashes upon opening certain plugins

### ISSUE THREAD

**Issue by Calendis** [LMMS/lmms#2618] opened 2016-02-29 03:47 UTC
A few plugins crash LMMS when I open them. I am on openSUSE 42.1 Leap using LMMS Version 1.1.3 I haven't tested every single plugin, but here's the ones I found that cause a crash.

All plugins beginning with LADSPA: GLAME
`lmms: symbol lookup error: /usr/lib64/ladspa/--this depends--.so: undefined symbol: init_iir_stage`

LADPSA: Mag's Notch Filter
`lmms: symbol lookup error: /usr/lib64/ladspa/notch_iir_1894.so: undefined symbol: init_iir_stage`

LADSPA: GSM simulator
`/usr/lib64/ladspa/gsm_1215.so: undefined symbol: gsm_create`

LADSPA: Pitch Scaler
`/usr/lib64/ladspa/pitch_scale_1193.so: undefined symbol: pitch_scale`

LADPSA: Higher Quality Pitch Scaler
`/usr/lib64/ladspa/pitch_scale_1194.so: undefined symbol: pitch_scale`

LADSPA: Hermes Filter
`/usr/lib64/ladspa/hermes_filter_1200.so: undefined symbol: blo_h_tables_new`

**Comment by tresf** [comment] 2016-02-29 03:55
@Calendis thanks for the bug report.  Where did you obtain LMMS?

A quick Google search shows this may be caused by the wrong ELF class (32-bit vs. 64-bit).  Can you do some investigation on your `lmms` binary?

http://superuser.com/questions/791506/how-to-determine-if-a-linux-binary-file-is-32-bit-or-64-bit

**Comment by Calendis** [comment] 2016-02-29 04:09
Running file on my lmms binary ouputs: ` /usr/bin/lmms: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 3.0.0, BuildID[sha1]=35f5f59ce43f2236cd98cd11e5a095b17a58141b, stripped
 `
I'm running a 64-bit OS, so this seems to be the right binary. I installed it from the openSUSE repositories.

**Comment by tresf** [comment] 2016-02-29 04:41
> It is probably worth noting that LMMS 1.1.3 on Ubuntu did not suffer from this problem when I was using Ubuntu.

Thanks for checking.  Yeah, I've never seen this on any platforms before. 

Can you also doubly verify the same for the LADSPA plugins (I understand this is redundant since they're in the lib64 folder).

Furthermore if you try these LADSPA plugins in Audacity, does audacity crash too?  If so, it may be a packaging problem with LADSPA on openSUSE rather than LMMS.

To give you some background information, the lines you are referring to are [part of the upstream source code](https://github.com/swh/ladspa/search?utf8=%E2%9C%93&q=init_iir_stage), so chances are, we'll file this away as `not-our-bug` from an LMMS perspective.

**Comment by Calendis** [comment] 2016-03-13 18:37
Sorry for the unresponsiveness on my part. Anyway, the plugins in the lib64 folder are indeed 64 bit, according to file. Interestingly Audacity won't let me enable the plugins, so I cannot even attempt toad them. I can load other ladspa plugins just fine. It does seem like it is not your bug.

**Comment by Umcaruje** [comment] 2016-03-13 18:44
>I can load other ladspa plugins just fine, so it does seem like this is not your bug.

Thanks for following up, I'm gonna close this.

**Closed by Umcaruje** 2016-03-13 18:44 UTC
Labels: not our bug
