### ISSUE TITLE
add either scroll or 'next-page' to vst-preset-overview

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1670] opened 2015-01-22 13:34 UTC
Current overview accomendate 145 presets, but several vsts has banks with 256, these presets can be loaded, but they cant be seen in the overview.

**Comment by tresf** [comment] 2015-01-22 13:41
@musikBear are you referring to this?

![image](https://cloud.githubusercontent.com/assets/6345473/5856579/7ac2e7d6-a212-11e4-8a52-873a388921bf.png)

**Comment by tresf** [comment] 2015-01-22 13:50
@musikBear I don't see any hard limit to this preset area... are you sure it's not a bug with the VST you are using?

As you can see here, the for loop doesn't have any limitation hard-coded into it... [`vestige.cpp#L584`](https://github.com/LMMS/lmms/blob/stable-1.1/plugins/vestige/vestige.cpp#L584).  Can you improve your bug report to have instructions on how to reproduce the exact message?  If not, we'll close it out as invalid.

-Tres

**Comment by musikBear** [comment] 2015-01-23 11:06
no this
![paste](https://cloud.githubusercontent.com/assets/6662066/5873565/2f3146e6-a2f8-11e4-94b7-1fdef25b6c87.jpg)

one
Overview. If there are many slots, they cant be seen

**Comment by tresf** [comment] 2015-01-23 12:17
Steps to reproduce would be nice.

**Comment by musikBear** [comment] 2015-01-23 14:02
? steps :question: 
click it
There is 145 slots
Vsts has up 256 slots
-i tried TAL noicemaker

**Comment by tresf** [comment] 2015-01-23 14:12
**WHAT YOU SHOULD DO**

1. Decide you are going to answer the question properly
2. Edit the original post with step-by step instructions to reproduce the problem
3. Review your steps for items that may be misleading.
4. Post something in the nature of "Updated original post with step-by-step instructions to reproduce this problem"
5.  The above steps give the developers the ability to investigate, debug and possibly fix the issue.
6.  The fix is provided in a future version of LMMS, the world is a better place.

**WHAT YOU ARE DOING**

? some THING :cactus: 
do this
Then a number 99999
-how ABOUT trains birds and fun stuff
S*tuff*

**Comment by tresf** [comment] 2015-01-30 21:33
Ok, I've discovered the cause of this bug... @musikBear needs a bigger screen... 

The actual problem is QT's dropdown menu doesn't seem to have the overflowing capabilities of a menu that is bigger than the screen.  I think this is a `wontfix` issue, personally.

![image](https://cloud.githubusercontent.com/assets/6345473/5983670/603d89ca-a89d-11e4-90de-e7a5dc53abc8.png)

**Comment by Umcaruje** [comment] 2015-07-04 21:09
I think this should be closed as a won't fix too.

**Comment by tresf** [comment] 2015-08-24 16:00
Closing.  Hopefully QT5 will have some better menu overflow... or perhaps we find a new container for hundreds of items... :)

**Closed by tresf** 2015-08-24 16:00 UTC
Labels: won't fix
