### ISSUE TITLE
Issue re: Non-Embedded VSTs

### ISSUE THREAD

**Issue by davisjacobym** [LMMS/lmms#4833] opened 2019-02-20 00:52 UTC
So, in testing rc8, I discovered that while using the non-embedded setting for VSTs (helps with some VST GUI incompatibilities, hence its usefulness), LMMS will remain behind opened VST windows at all times. In previous versions, switching to LMMS from a VST window would be no different than switching from one program to another.

If my explanation is not very clear, feel free to contact me in the LMMS Discord server for further elaboration.

**Comment by DomClark** [comment] 2019-02-20 00:53
Duplicate of #4802. If you could cast a vote on the poll there, that would be great.

**Closed by DomClark** 2019-02-20 00:53 UTC
