### ISSUE TITLE
Enhancement: Pitch envelope and LFO

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#532] opened 2014-03-28 22:33 UTC
Would be awesome to have a pitch envelope and LFO functionality for instruments.
It would have same controls like volume, cutoff and reso tabs have. Could be placed after the reso tab.

**Comment by Umcaruje** [comment] 2015-07-03 22:22
Duplicate of #1466

**Closed** 2015-07-03 22:27 UTC
Labels: core, duplicate, enhancement
