### ISSUE TITLE
Extend pitch range

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2250] opened 2015-08-11 15:56 UTC
played with some notes in piano-roll. I moved them with sh+up/dwn
That is quite interesting.
This effect cant be achieved now, but if pitch-**range** was significantly increased, then that effect would be very easy to make.
If **range** can be extended, then i suggest that it is done, f.i. with a 'multiply' factor next to the current dial. In that way current dial and spindle, wouldent have to be changed at all.

**Comment by michaelgregorius** [comment] 2015-08-11 16:39
I have just checked the code. Seems like only one line would need to be changed (initialization of `m_pitchRangeModel` in the constructor of `InstrumentTrack`). Backwards compatibility would likely not be a problem because we would increase the range, i.e. offer more options to the user without restricting existing ones. So, shall we go for it? What should be the new maximum value? 36? 48? 60?

I'd vote against having a multiplier next to the range dial. In my opinion it would not be very intuitive and would only complicate the GUI. Due to the current fixed size of the plugins there is not much space left anyway. 

While we are on the topic: some VSTs offer the possibility to set the range for upward and downward bends individually. I think this might be an interesting feature for LMMS as well but as stated above currently there is not much space left on the instruments.

**Comment by musikBear** [comment] 2015-08-12 11:29
> Seems like only one line would need to be changed (initialization of m_pitchRangeModel in the constructor of InstrumentTrack).

Thats super.

> I'd vote against having a multiplier next to the range dial. In my opinion it would not be very intuitive and would only complicate the GUI. Due to the current fixed size of the plugins there is not much space left anyway.

It could be as simple as a displayed value on top of the dial it self.
left-mouse-click would enhance by one right-click would decrease by one. The space on GUI would not be influenced at all :)

**Comment by AndiEcker** [comment] 2015-08-12 13:42
I always found the Pitch Range knob very confusing, first because it is the
only knob in LMMS that is changing the scale of another knob (the Pitch
knob) and second if you have a big range value on the Pitch knob and on the
Pitch Range knob too and then after decreasing the Pitch Range value it
will also affect (decrease) the value of the Pitch knob.

Last year I requested to change this to have a percentage value on the
Pitch knob (instead of the actual note pitch) - please see this feature
request http://sourceforge.net/p/lmms/mailman/message/32465882/ (there is
also a lmms project attached that is demonstrating the problems).

Would be grate if this feature request can be taken into account if you
change the functionality of the Pitch knob?

Really loving LMMS!!! Keep up your great work!!!

**Comment by tresf** [comment] 2015-08-12 13:46
> I always found the Pitch Range knob very confusing, first because it is the
only knob in LMMS that is changing the scale of another knob (the Pitch
knob) and second if you have a big range value on the Pitch knob and on the
Pitch Range knob too and then after decreasing the Pitch Range value it
will also affect (decrease) the value of the Pitch knob.

I'm not sure how else to do it when you want a wide variety of precision over a pitchbend.  If we change this, I would recommend we change it on a UI perspective only so that it makes more visual sense.

**Comment by tresf** [comment] 2015-08-25 13:42
@musikBear is this about automation?

![image](https://cloud.githubusercontent.com/assets/6345473/9467875/8b722332-4b0c-11e5-8c5c-1d70478fa542.png)

Is the idea simply to allow the pitch knob's value to remain constant while giving the user the ability to tweak the range knob as a multiplier AGAINST the pitch value instead of a multiplier INFLUENCING the PITCH dial?  Is this just about keeping the pitch dial in a standard rotation scale?

If that is the case, I would agree with the "Multiplier" proposal, but make it a toggle, similar to how we have the timeline widget a toggle.

I don't think permanently increasing the pitch knob range itself is a good idea.

![image](https://cloud.githubusercontent.com/assets/6345473/9468022/5582b0ba-4b0d-11e5-8050-41a01a6f8d28.png)

Making the spinbox a toggle would require some work under the covers though.  I'm not sure how the pitch data model would react.

-Tres

**Comment by michaelgregorius** [comment] 2015-08-25 17:00
@tresf Isn't this just about increasing the maximum value for the pitch range from 24 to something like 36 or 48? So that it's possible to automate the pitch of an instrument in a wider range?

**Comment by musikBear** [comment] 2015-08-26 11:08
@michaelgregorius exactly that.

**Comment by tresf** [comment] 2015-08-26 11:56
Range does exactly that.

**Comment by michaelgregorius** [comment] 2015-08-26 17:10
@tresf I think @musikBear's intention is to extend the maximum value for "Range" from 24 to something bigger like 36 or 48. Please see also my [previous comment](https://github.com/LMMS/lmms/issues/2250#issuecomment-129961825) from some days ago.

**Comment by tresf** [comment] 2015-08-26 17:24
@michaelgregorius your post goes into how possible this is to implement but does nothing to address the need or even want for the change.

A range of `2` brings the pitch to `100` cents, so the only use-case I can see is to automate the pitch knob and change the range to a percentage (via aforementioned use case).

**Comment by michaelgregorius** [comment] 2015-08-26 17:43
@tresf I think I interpret the range differently. If I set the range to 24 and then automate the pitch to go from 100% to -100% (I think it's actually labelled differently in the automation editor) then I will get a note dive over four octaves for a constant note. But as also noted by @AndiEcker the range and the pitch knob seem to be interconnected in a weird way (well at least to me it seems weird). Perhaps this is the cause for the confusion because there are more ways to look at it. :smile:

My interpretation stems from the way it's more or less implemented in most VST plugins. You set the pitch range in the synth, e.g. 12 semitones. If you then move the pitch wheel on your MIDI keyboard to the maximum you will get the pitch modulation that was just dialled in, in case of the example one octave. I was under the impression that this issue is about being able to go further than 24 semitones in the LMMS instruments.

**Comment by Wallacoloo** [comment] 2015-08-26 18:03
Late to the conversation, but I would expect that there's *got* to be a better way of manipulated pitch than via two separate pitch + pitch range knobs embedded in the instrument controls. That has always seemed convoluted to me.

Consider this: We make it so that there is *only* the pitch knob and no pitch range in the instrument controls. But the knob has no limits - you can turn it a full revolution, two revolutions, etc, and keep going.  Each full revolution corresponds to +/- 1 octave, and some color element on the knob can reflect which octave you are on (e.g. black for octave 0, yellow for octave +1, orange for +2, green for -1, blue for -2, etc. Beyond that, one would have to determine the octave by using the tooltip).

The automation editor might have to change to adapt to unbounded parameters, but that's doable.

For when you're actually using a knob with physical limits to control pitch (i.e. the pitchbend knob on a midi keyboard), the range of this physical knob is controlled via some setting in LMMS' midi options (or maybe the instrument midi tab, but this is really a property that ought to be associated with the keyboard device, not the synth).

**Comment by michaelgregorius** [comment] 2015-08-26 18:24
@Wallacoloo I think it should rather be a property of the synth. For example, let's say I want a large pitch band range for one instrument (lead uses an octave) and a smaller range for another one (bass uses two semitones). Why should I go to the LMMS MIDI options every time I want to play that instrument via my keyboard instead of setting the values once in the instruments, save my session and then being able to have that settings available each time I play that instrument.

Also, why do it differently than everyone else? I think familiarity with certain concepts is an important factor for example when someone knows one or more other DAWs and wants to check out LMMS.

I think putting stuff like this into the instruments/patches is also what gives most VSTs their own character: How does the instrument behave in poly mode? How does it behave in mono mode? What filters does it offer? How many LFOs, ADSRs and MSEGs does the instrument offer? What options are there to retrigger the LFO? Which parameters can be automated? In my opinion most of LMMS internal instruments seem quite similar because many of these decisions and features are already implemented outside of the plugins (ADSRs, LFOs, filter, etc.).

**Comment by tresf** [comment] 2015-08-26 18:28
> @tresf I think I interpret the range differently. If I set the range to 24 and then automate the pitch to go from 100% to -100% (I think it's actually labelled differently in the automation editor) then I will get a note dive over four octaves for a constant note. But as also noted by @AndiEcker the range and the pitch knob seem to be interconnected in a weird way (well at least to me it seems weird). Perhaps this is the cause for the confusion because there are more ways to look at it. :smile:

Right, and the dual mode `MULT` mock-up I provided does exactly that.  It keeps allows existing functionality while providing the ability to make the pitch wheel at fixed increments, so a two or three octave slide is determined by the `MULT` knob (or spinner) rather than the `PITCH` knob, which is IMO how it should be.  This also allows to tweak the `MULT` knob mid-song for some strange live multiplier effects in bend range.

**Comment by tresf** [comment] 2015-08-26 18:35
Current Mode
```

                  (__)
                  PITCH
-100 cents * range    +100 cents * range
```

Click "RANGE" turns to MULT
```

                  (__)
                  PITCH
     -100%* mult         +100% * mult
```

**Comment by michaelgregorius** [comment] 2015-08-26 19:39
@tresf Seeing your ASCII art and playing with it in the software I think now I understand what @AndiEcker meant with the strange behavior. If you set range to 24 and set the pitch to for example 90 cents this means that the pitch dial is only moved slightly to the right because 90 / (24 * 100) = 90 / 2400 = 3.75%. However if you now set the range to 1 the dial will move almost completely to the right because 90 / 1 * 100 = 90%.

My question now would be what's the reason to not implement it like this (hope I interpreted you ASCII art correctly):
```

                  (__)                                        (__)
                  PITCH                                      /RNGE\
       -100%              +100%                             0      24 (or 36 or 48)



                          MODE THAT MOST USERS ARE USED TO ;)
```
So the range would only determine the usable scale for the instrument or patch and the pitch position would determine where on that scale you are. So if the range is set to 24 and you dial in 50% each note will play an octave higher than entered.

I think adding another mode would only complicate things for the user (and in the code). Is it about backward compatibility? I saw that it is possible to put a global automation on the range value but how many songs are out there where this is used?

**Comment by tresf** [comment] 2015-08-26 20:07
@michaelgregorius I think the answer to your question is the very use-cases where existing functionality works and works well.

The concept of having a `1,000` cent pitchbend means that you can visually see and understand that `1,000` cents is granular pitchbend control over about 10 notes.

If you think of pitch in a cents measurement, it's a nice way to fine-tune an instrument.  I've had many sounds and instruments which 10 cents makes much more sense than 10%, and it is a unit of measure that makes... well... make sense to me in the context of that workflow. :+1: 

However, from an experimental perspective, as well as a bend-a-full-octave-or-many-octaves workflow, cents are TOO granular.

Will the switched functionality confuse people?  Perhaps.  Should % be default?  Probably.  I just think if we put the time into improving this, we can have our cake, **and** eat it too, so to speak.

**Comment by Wallacoloo** [comment] 2015-08-26 21:09
@michaelgregorius 
> I think it should rather be a property of the synth. For example, let's say I want a large pitch band range for one instrument (lead uses an octave) and a smaller range for another one (bass uses two semitones). Why should I go to the LMMS MIDI options every time I want to play that instrument via my keyboard instead of setting the values once in the instruments, save my session and then being able to have that settings available each time I play that instrument.

Given that possible use case, I agree that the wheel range control would be better placed in the instrument's midi tab than some global setting.

> Also, why do it differently than everyone else? I think familiarity with certain concepts is an important factor for example when someone knows one or more other DAWs and wants to check out LMMS.

We would do it differently because the currently accepted implementation is flawed as evidenced by this thread's existence (and from personal experience: editing the range knob AFTER automating the pitch knob creates non-intuitive results, and the pitch knob becomes unwieldy to edit by mouse if the range is large).

Further, there are two sets of users we have:  
1. People who are experienced in many DAWs. These people are accustomed to the existing industry workflow.
2. People who have never used a DAW. These people have no idea what to expect.

For group 2, I really think most newcomers would find a single unbounded "pitch" knob to be more intuitive than two separate pitch + range knobs.  
For group 1, they may be slightly surprised for a few seconds, but it's a small enough change to where I think they would all accept it, and many would prefer it.

I don't think there would be a net gain nor loss in userbase size from a change like this.

**Comment by Wallacoloo** [comment] 2015-08-26 21:11
> Perhaps. Should % be default? Probably.
@tresf I disagree. If you're seriously considering changing the default, take a poll of at least a few users first (I don't think you'll find any consensus saying that percentage is more intuitive than cents).

**Comment by tresf** [comment] 2015-08-26 21:13
Is the proposals I'm reading to put the pitch range on the midi tab?

I use pitch quite a bit for fine-tuning instruments... I'm not sure that is a tab that would make contextual sense to me.

-Tres

**Comment by tresf** [comment] 2015-08-26 21:14
> If you're seriously considering changing the default, take a poll of at least a few users first

I'd rather not for such a small change.  The consensus of those making the decisions (you know, those that do the work) is fine with me.  This isn't a democracy, we can't afford for it to be.

**Comment by Wallacoloo** [comment] 2015-08-26 21:31
@tresf you don't have to take a census - just survey a few people on IRC, etc. Using percentages to represent pitch just seems totally counter-intuitive to me *personally* (I have yet to hear anybody ever say something similar to "play A4 and then bend it up 90% of 8 semitones").

@tresf The proposal: (forget about midi keyboards until the next paragraph). The proposal is to ditch the existing range knob, and just make the pitch knob unbounded. If you want to pitchbend up one octave, then you turn the knob one revolution clockwise. Bend down 2.5 octaves? Then turn the knob 2.5 revolutions CCW.

This lets you do everything that can be done with the current pitch + range knob in nearly every setting except for when using a physically bounded pitch wheel (i.e. the one on your midi keyboard), but in a much simpler way (one knob). To deal with the case where the pitch knob is actually being driven by a physical pitchbend wheel, you introduce a range knob into the instrument's midi tab. This range knob *only* affects controls that are received from the pitchbend wheel & does not interfere with automation, etc.

------
My keyboard does not have a pitchbend wheel, so this scheme might not be entirely compatible with the way one connects a pitchbend wheel in lmms. e.g. if the current way of connecting the pitchbend wheel is via linking the instrument's pitch wheel directly to the midi controller, then this wouldn't work. Would be curious as to the current procedure for connecting physical pitch wheels.

**Comment by michaelgregorius** [comment] 2015-08-26 22:00
@Wallacoloo I have just tried it. The pitch bend wheel of the keyboard is mapped directly to the pitch dial in LMMS. So the pitch wheel at the physical maximum position results in the dial being completely to the right and the pitch wheel at physical minimum results in the dial being completely to the left. This is done independent of the range value that's set, i.e. even if you change the value the (visual) result is still the same.

I think many people use the pitch bend for some more expressive playing by the way. So you normally experiment with a patch and get a feeling for it. I hope there is no one who thinks "I want it to go to 87.3%". :wink: @tresf on the other hand seems to use it for some static pitch fine tuning if I understand correctly?

Last but not least, if you records some notes with most VST with a certain pitch range set and then change the range afterwards it will just sound different and most likely not very nice. But I think most people accept that. I still have the feeling that LMMS tries to do too much and to preserve everything as it was before and that might be why it seems to be so complicated. However, I can't really put my hand on it, it's more of a gut feeling.

**Comment by tresf** [comment] 2015-08-27 02:51
I use pitch to [fix detuning](https://soundcloud.com/tres-finocchiaro/that-hill-rev-08) as well as [pitch bending](https://soundcloud.com/tres-finocchiaro/heart-beat-rev-01).

But I'm not advocating for a new default, I'm just trying to help put some use-case context around this proposal.  The proposal was to change 10-cents to something else and I said, we can already change it to something else, so what is the value-add to this?  Because someone likes the number 24 more?  :)

**Comment by Wallacoloo** [comment] 2015-08-27 04:45
> The pitch bend wheel of the keyboard is mapped directly to the pitch dial in LMMS.

Guess I'll have to shelve my idea for the time being.

Back to @musikBear's original post. If we raise the limit of the range knob to 60, that gives us 10 full octaves to sweep. i.e. almost exactly 20 Hz to 20 kHz (which is the approximate range of human hearing) if you choose the right note to bend (E5). So it actually has meaning as a limit, whereas I believe 24 was arbitrary - increasing the limit to something greater than 60 is fairly useless since it would only serve to allow one to bend beyond the limits of human hearing.

**Comment by tresf** [comment] 2015-08-27 04:59
@Wallacoloo I think I over read this thread.  Yeah, more range shouldn't hurt.

-Tres

**Comment by tresf** [comment] 2015-08-27 05:00
... although I still think having an automation graph for pitch on a percentage scale would make the idea of range very interesting from an experimental perspective.

**Comment by tresf** [comment] 2015-08-27 05:02
@michaelgregorius please accept my apologizes... I had misinterpreted the request.  Good conversations none-the-less, but sorry for the confusion it has caused.

**Comment by michaelgregorius** [comment] 2015-08-27 16:49
@tresf No need to apologize! As you have already stated it's a good conversation and sometimes I think that these "confusions" are just a normal part of software development when discussing requirements and specifications. :smile:

**Comment by tresf** [comment] 2015-08-27 17:17
So that said, I think @musikBear's original proposal is just fine. :+1:

**Closed** 2015-09-12 17:02 UTC
Labels: enhancement, ux

**Comment by Wallacoloo** [comment] 2015-09-12 17:03
Well, #2297 (merged) fixes this by extending the maximum pitch range to +/- 5 octaves (was previously +/- 2).
