### ISSUE TITLE
VSTs that does not work in RC7

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4816] opened 2019-02-07 16:25 UTC
@DomClark -You has been given the tittle "resident-VST-expert" :) , so i tag you for this VST with odd RC7win32 behavior.
http://www.vst4free.com/free_vst.php?plugin=Marimbaphonic&id=2013

* The 'Dynamic' dial resets it self to a different value that it was saved as
* The LMMS Dial-array is empty. There are no controllers, so automation is impossible.
* The 'preset-collection' is empty, even though a special folder with internal presets are part of the download.

I think it would be beneficial, if specific VSTs with issues in LMMS, all are consolidated in one thread

**Comment by zonkmachine** [comment] 2019-02-10 02:35
> * The LMMS Dial-array is empty. There are no controllers, so automation is impossible.

Confirmed. Maybe it's not implemented in Marimbaphonic? It's a simpler sample based pluggin, a rompler. It should be tested in some other studio to verify that the controls can be automated.



> * The 'preset-collection' is empty, even though a special folder with internal presets are part of the download.

I find no preset collection. In the zip I find the .dll and a directory named Marimbaphonic.instruments containing a file named Marimbaphonic.mse. This is probably a media file containing the samples that Marimbaphonic uses. It's 50 MB large.

**Comment by zonkmachine** [comment] 2019-02-10 10:23
Tested another vst by the same creator and it has the same issues.
http://www.vst4free.com/free_vst.php?plugin=VibroMaster&id=2126

**Comment by DomClark** [comment] 2019-02-14 17:21
Tested Marimbaphonic in Tracktion and Reaper and it has the same behaviour there. This seems to be how the plugin is meant to behave, and not an LMMS issue. Closing.

**Closed by DomClark** 2019-02-14 17:21 UTC
Labels: vst
