### ISSUE TITLE
Playhead in BB Editor.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4701] opened 2018-11-05 05:54 UTC
The BB Editor is very good at making percussions and organizing the song. but it needs a playback head as the song editor and the piano roll have it. more or less what I want to explain I say in this image:

![cabezal en editor de ritmo](https://user-images.githubusercontent.com/26127693/47980234-b3230b00-e094-11e8-875b-863281393399.png)

As you can see, when the rhythm created lasts more than 1 second it becomes a problem because you can not direct the playback as you do in the song and piano roll editor, this problem is more serious with the samples track and the automation blocks because to be able to direct the head.

I suggest that you implement the playback head and the buttons that complement its function, for a better functioning of the BB Editor. regards

**Comment by PhysSong** [comment] 2018-11-05 06:33
Duplicate of #1195.

**Closed by PhysSong** 2018-11-05 06:33 UTC
