### ISSUE TITLE
Adding a better sampler

### ISSUE THREAD

**Issue by killjoyrekt** [LMMS/lmms#3831] opened 2017-09-28 09:03 UTC
Hi guys I was just wondering if it would be possible to add a new better sampler that would change the pitch of the sample without changing the speed. The current one does this. Like when i want to use samples of drums with different pitch they sound slightly different in length. Hopefully this could be possible. Thanks.

**Comment by lukas-w** [comment] 2017-09-28 09:57
Duplicate of #1734.

**Closed by lukas-w** 2017-09-28 09:57 UTC
