### ISSUE TITLE
In App Audio Recording

### ISSUE THREAD

**Issue by Failfer** [LMMS/lmms#7629] opened 2024-12-20 06:38 UTC
### Enhancement Summary

Mainly a question, most people i've seen talk about lmms have a compliant about it not having an in app recording feature. Is there a design or technical reason why this hasn't been done.

### Implementation Details / Mockup

I couldn't find any Issue's on the github here set for the recording feature, though I am quite new and just may not see them. Is the reason why recording isn't built in that we see it best to delegate that task to other software and focus on other features or what's the reasoning. If not should we start trying to add that feature.

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Rossmaxx** [comment] 2024-12-20 07:15
Duplicate of #1297 and being worked on in #5990

But we won't see recording in the latest release as the PR is stuck in PR hell.

**Closed** 2024-12-20 07:15 UTC
Labels: enhancement
