### ISSUE TITLE
problems loading the menu, from the Element plugin (vst)

### ISSUE THREAD

**Issue by Small-Develop** [LMMS/lmms#6674] opened 2023-03-16 02:18 UTC
Hello, thanks for the excellent work done in lmms, I have used the KV_Element plugin (https://kushview.wpengine.com/element/) and when loading, it loads them well, the problem is that when you secondary click on the vst (in the interface) does not show the drop-down menu well, it shows it and closes it fast, which does not allow the menu to be displayed well, it does the same in Element FX, (vst effects) I suppose it is a problem in vestige, I have checked it with nanohost (https://www.tone2.com/nanohost.html) and DarkWave Studio 5.9.4 (https://www.experimentalscene.com/software/darkwave-studio/) and on both daws, it shows the menu alright giving secondary click, also when resizing the element interface, it is not possible,
  is not allowed by vestige, which limits the size of the plugin interface or vst. thank you.

here the reference image of the open menu, in nanohost.
<a href="https://ibb.co/SVwf2xS"><img src="https://i.ibb.co/NW2TX3R/Captura2.png" alt="Captura2" border="0"></a>

**Comment by superpaik** [comment] 2023-03-17 12:46
Some vst doesn't work very well with LMMS if embedded. You should set "Pluggin Embedding" to "No embedding" on "General settings"
If that's the case, please consider closing the issue.
![imatge](https://user-images.githubusercontent.com/68785450/225908214-1c8edd1a-0714-4587-a5f9-f28a020a84c6.png)

**Comment by zonkmachine** [comment] 2023-03-17 13:28
The old JUCE drop-down menu bug. It's described [here](https://github.com/LMMS/lmms/issues/3918) and has been fixed in JUCE but projects depending on that library need to update to a later version. The workaround with **No embedding** above is the way to go. Try and see if there is a newer version of Element around. Here are some development versions of Element-0.47.0: https://builds.kushview.net/#element/windows/

Closing as duplicate of https://github.com/LMMS/lmms/issues/3918

**Closed by zonkmachine** 2023-03-17 13:28 UTC
Labels: enhancement

**Comment by zonkmachine** [comment] 2023-03-17 16:05
Element issue tracker here: https://gitlab.com/kushview/element/-/issues

**Comment by Monospace-V** [comment] 2023-03-26 03:57
> ... and has been fixed in JUCE but projects depending on that library need to update to a later version.

I'm wondering if there's some plan for LMMS to go around this? A lot of my VSTs are old or unmaintained, and there is no likelihood of a JUCE version update.

**Comment by zonkmachine** [comment] 2023-03-26 12:26
> I'm wondering if there's some plan for LMMS to go around this? A lot of my VSTs are old or unmaintained, and there is no likelihood of a JUCE version update.


Discussion of a possible workaround starts here: https://github.com/LMMS/lmms/issues/3918#issuecomment-398159466
