### ISSUE TITLE
MIDI import clamps pitch bend

### ISSUE THREAD

**Issue by slawekwaga** [LMMS/lmms#5045] opened 2019-06-18 16:03 UTC
Midi file has pitchbend extending one semitone. Hovever on import on LMMS the pitchbend values are clamped to (-100,100) area. Most notable on MAP30 midi from DOOM 2.

**Comment by PhysSong** [comment] 2019-06-21 07:19
Looks like a duplicate of  #1967.

**Comment by SecondFlight** [comment] 2019-06-21 14:22
Good catch.

**Closed by SecondFlight** 2019-06-21 14:22 UTC
Labels: duplicate
