### ISSUE TITLE
8 of lmms' default instruments will not record notes in piano-roll

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3828] opened 2017-09-25 19:18 UTC
LMMS RC3 0.49  win32
To reproduce 
* Insert any of the 8 instruments (list below) in a new project
* make one TCO and click either one of the record-buttons
* play some notes
No notes are recorded

These are the 8 instruments
lb303
mallets
opulenz
organic
sfxr
VST
Vibed
zasfx

**Comment by tresf** [comment] 2017-09-25 19:34
Is #3827 a duplicate?  If so, please close it.

**Comment by zonkmachine** [comment] 2017-09-25 19:36
I believe this was fixed in https://github.com/LMMS/lmms/pull/3803

**Comment by tresf** [comment] 2017-09-25 19:41
@zonkmachine thanks.  @musikBear can you please carefully read #3757 and decide if it's the same problem?

**Comment by musikBear** [comment] 2017-09-26 13:04
> Is #3827 a duplicate? If so, please close it.

@tresf No, 3827 shows that the instruments that DO record, can do that apparently in *random* positions, even though the playhead moves correctly linearly over piano-roll -It is what the gif shows.
The 2 issues are not the same

**Comment by PhysSong** [comment] 2017-09-27 03:52
This is https://github.com/LMMS/lmms/pull/3774#issuecomment-325090531, should be fixed in rc3.52

**Comment by tresf** [comment] 2017-09-27 04:13
@PhysSong thanks for the link.  Closing as duplicate of https://github.com/LMMS/lmms/pull/3774#issuecomment-325090531.  @musikBear please request a reopen if this still exists in RC4 once released.

**Closed** 2017-09-27 10:20 UTC
Labels: duplicate
