### ISSUE TITLE
Add the ability to view devlogs

### ISSUE THREAD

**Issue by YesImAsh** [LMMS/lmms#7420] opened 2024-08-03 06:53 UTC
### Enhancement Summary

The ability to view Devlogs in LMMS
The reason why we need this is because sometimes, crashes and errors can occur in the most unexpected time. You weren't paying attention to what you did wrong and therefore dont know how to replicate the bug. The Devlogs should get you covered

### Implementation Details / Mockup

It basically stores data in a new .txt file called "Devlogs" 

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Rossmaxx** [comment] 2024-08-03 07:45
There is a method to see if you are on linux, use `gdb <path_to_lmms>` and from gdb, type `run`. After a crash, you can type `bt full` for the full backtrace.

**Comment by YesImAsh** [comment] 2024-08-03 08:05
is there one for windows?

**Comment by DomClark** [comment] 2024-08-10 17:25
Duplicate of #3876 (see also #5468).

**Closed by DomClark** 2024-08-10 17:25 UTC
Labels: enhancement
