### ISSUE TITLE
Red line in Automation Editor can be drawn strangely

### ISSUE THREAD

**Issue by JohnDorsey** [LMMS/lmms#2485] opened 2015-12-16 02:01 UTC
When the Automation editor window is open above the song editor window, and the song is playing, and the mouse pointer is moved the Automation Editor window and onto the Song Editor window...
The red line in the automation editor indicating the height of the pointer on the window will remain frozen at the height it was when the pointer left the edge as expected, except for wherever the playhead is behind that window. every place that the playhead moves, the red pixel from the line is unfrozen, and is moved to the new height of the mouse pointer as the mouse pointer moves around on the song editor.
for instance, if the mouse pointer is moved up and down on the song editor, it will draw a wavy red line in the automation editor, but only as fast as the playhead moves beneath it.

**Comment by tresf** [comment] 2015-12-16 02:32
Sounds like a duplicate of #1052

**Comment by JohnDorsey** [comment] 2015-12-16 02:59
It is very similar, my bad. I did try to check and make sure this hadn't been reported already. The only difference here is that it doesn't require the mouse pointer to even be on top of that window. but it's probably all the same bug to fix. and it didn't need a second report. sorry.

**Comment by tresf** [comment] 2015-12-27 02:23
Closing as duplicate of #1052

**Closed by tresf** 2015-12-27 02:23 UTC
Labels: duplicate
