### ISSUE TITLE
LMMS crashing when trying to load Carla

### ISSUE THREAD

**Issue by jaddison06** [LMMS/lmms#5718] opened 2020-10-18 02:42 UTC
Pretty much the title, when I try to drag either Carla Rack or Carla Patchbay in LMMS crashes immediately with this message:
/tmp/.mount_lmms-1iw12mb/usr/bin/lmms.real: symbol lookup error: /tmp/.mount_lmms-1iw12mb/usr/lib/lmms/libcarlabase.so: undefined symbol: carla_get_library_filename

I'm using LMMS 1.2.2 AppImage on ElementaryOS (Ubuntu based), and Carla is from apt

**Comment by jaddison06** [comment] 2020-10-18 02:43
Just saw #5707 , looks like it might be related

**Comment by PhysSong** [comment] 2020-10-18 03:43
Duplicate of #5692.

**Closed by PhysSong** 2020-10-18 03:43 UTC
