### ISSUE TITLE
LMMS IMPOSSIBLE TO READ

### ISSUE THREAD

**Issue by QuirkyCowfish** [LMMS/lmms#3529] opened 2017-05-02 19:21 UTC
I have a surface pro 4 and just downloaded LMMS and everything is super tiny impossible to see what everything is. It works fine on my desktop I don't understand why this is an issue. I had this problem with an older version of photoshop a while ago, I was able to fix it, used the same method on LMMS and it did not work. HELP!!

![wtf](https://cloud.githubusercontent.com/assets/28314741/25635109/fc35dcd4-2f4a-11e7-81f6-2c91562c02aa.JPG)

**Comment by tresf** [comment] 2017-05-02 19:30
> HELP!!

We don't have a fix yet.  Duplicate of #2510.  I'm closing this out as a duplicate, but the issue still remains open over at #2510.

**Closed by tresf** 2017-05-02 19:30 UTC
Labels: duplicate
