### ISSUE TITLE
Playback interrupts hardly when plaing from piano roll and moving cursor over it

### ISSUE THREAD

**Issue by ShurikMur** [LMMS/lmms#1659] opened 2015-01-19 21:07 UTC
Version 1.1.0, win 32, audio output: SDL (can't select anything else...)

Using almost any VST instrument (anything beside built-in instruments), moving a mouse over piano roll while playing causes playback interrupts (with a short period of silence) up to several times a second, that's hurting ears as hell and almost destroying creative process.
Moving a selected note also produces glitchy interrupted sound of that note.
Buffer size doesn't matter.
CPU load bar is blinking green near zero, so it is not looks like a slow CPU problem.

**Comment by tresf** [comment] 2015-01-19 22:18
Possible duplicate of #967.

Can you confirm that you are using Windows?  This should be better in 1.2.  Until then, you may want to try changing the CPU priority of RemoteVSTPlugin.exe per #967.  Please confirm.

**Closed** 2015-01-19 22:19 UTC
Labels: duplicate

**Comment by ShurikMur** [comment] 2015-01-19 22:32
Yes, alerting CPU priority levels of VSTs, as proposed in #967, works.
Hope the issue will be fixed permanently in the next versions.
Thanks!

**Comment by tresf** [comment] 2015-01-19 22:37
@ShurikMur we should have some beta versions of 1.2 available in the coming weeks.  Please check our downloads page for the yellow download button to appear.  We value our test results greatly prior to release.  Thanks for the quick response.
