### ISSUE TITLE
Nescaline & Freeboy need to have noise CH disabled pr. default

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4331] opened 2018-04-28 12:40 UTC
both instruments has special noise-generator, and it is wrongfully default enabled.
in Nescaline it is CH4 that is the noise-generator.
It should be disabled default

In Freeboy 
CH 1 (oneshot-effects)
and
CH4 (noise channel)
Should be default disabled

Users complain about 'awful distorting instruments' because of this oversight.

**Comment by SecondFlight** [comment] 2018-05-13 21:12
I vote to close this issue based on the discussion in the PR linked above. I would just do it but I'm still pretty new here.

**Comment by Wallacoloo** [comment] 2018-05-14 00:07
I had never used these instruments. However, I just opened them to understand this issue better - I will admit that not knowing anything about the instruments, I thought I had a problem with the sound configuration in LMMS when I first played a note on Nescaline. The default patches are distorted in such a way that _does_ resemble the same sound I get when using pulseaudio with too small a buffer.

Now, having not used these plugins much, I also don't know what sounds people most frequently create with them. But for Nescaline, changing CH4's `freq` to a higher value, or setting `SWP` to something positive makes it very obvious that the noise is part of the patch, and not sound issues.

For Freeboy, the noise sounds a bit more distinct than buffer underruns sound, but setting the noise channel's SSL value to something other than zero does make it more obvious that the noise is part of the instrument. Freeboy's CH1 doesn't sound distorted at all though - so I'm not sure what the issue is with that.

Anyway, I'm of the opinion that if new patches could be created that are more clearly distinct from the sound created by buffer underruns / driver problems, but still showcase the characteristic of sound an experienced user would use the instrument for, then we should use such patches. If such patches aren't possible (e.g. if the instrument is overwhelmingly used to imitate underrun-like sounds), then things are fine as-is.

In either case, this original issue report really isn't very helpful. For this type of subjective thing, we _need_ users themselves presenting their view on why the default patch should be changed. Second-hand reports that don't present any substantiated argument _aren't useful_.

**Closed** 2019-05-09 17:51 UTC
Labels: good first issue, ux
