### ISSUE TITLE
Please add a better alternative to the dead ZynAddSubFx + more issues

### ISSUE THREAD

**Issue by Ashvith** [LMMS/lmms#5355] opened 2019-12-25 08:29 UTC
I am sorry if I am violating the way of writing in a Git thread , but please , please , add a better plugin than the ZynAddSubFX. It's portmanteau is defective I think , and sometimes , it takes a toll on even a decent machine.
May I suggest Helm or Surge? Or maybe ZynFusion , which looks like the new version of ZASF ?
Link below-
https://zynaddsubfx.sourceforge.io/zyn-fusion.html
Also , instead of VeSTige system of using VST , can you go with the Track system?
The one in which we can "make a new track" , then set it's type as either instrument , audiofiles or beats ?
Just add automation below it , and by drop down menu , we can choose which automation to edit. 
Also , just remove the 'My Home' column. I think 'My Computer' does the job right?
I am sorry if this thread is irritating , but I just felt like the controls could have been a little 'minimal' and universal , and also , it has been so long since the last update , that is why.
Criticism is welcome by the way.
Edit 1- Also please add multi VST folder location , this one needs a real look-in please.
And as for LADSPA plugins , sadly some of them seem to be breaking today's devices.
I am not sure , which ones , because I did not touch LMMS for quite a long time.

**Comment by Spekular** [comment] 2019-12-25 09:37
The ZynFusion part of this is a duplicate of #4179 

A lot of the rest are invalid IMO:

> add a better plugin than the ZynAddSubFX

What does "better" mean, and why would we replace Zyn? Replacing Zyn would break existing projects, and both Helm and Surge can already be used as VSTs.

> sometimes , it takes a toll on even a decent machine.

You can't have your cake and eat it too. It's unavoidable that more complex patches will use more CPU.

Regardless, unrelated issues shouldn't be merged into one.

**Closed by Spekular** 2019-12-25 09:37 UTC
Labels: enhancement

**Comment by Ashvith** [comment] 2019-12-26 06:04
What do you have to say about synth w?
Looks like a great plugin.
I do not know the exact process of integrating a plugin , and also , I am new to git , so i am really sorry.
