### ISSUE TITLE
Blocks can disapear at random

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2191] opened 2015-07-18 16:02 UTC
win32 Master 12.07.15
So far i have no ways to reproduce. This happens at random

The situation is that blocks can exist but not being recognized, and not saved
as seen in related #2147 (which need to be reopened) a block can exist in song-editor, but not being recognized as a real object
But! It replays inside its own pianoroll -eg there is no warning, that this block is fake!
If the project is saved with such a 'faker-block', the block is simply not included in the saved file, and will have disappeared, the next time the project is opened.
How a block can replay, but not being copy or saveable, that is the thing that needs to be investigated.

**Comment by Umcaruje** [comment] 2015-07-18 18:29
@musikBear I consider this a duplicate of #2034 - do you agree?

>as seen in related #2147 (which need to be reopened) 

You know you can reopen your own bug reports, right? There's that shiny 'Reopen' button on the end of the page. There is no need to post duplicates for your own bug reports.

**Comment by musikBear** [comment] 2015-07-19 10:21
> I consider this a duplicate of #2034 - do you agree?

@Umcaruje 
No, this is different. From 2034 tresf says
>  His problem is the opposite as it reads, his blocks are being **explicitly deleted** and they still play.

in *This* bus a block will be *lost* even though it playback **in pianoroll!!!!* but **properly** not in song-editor. *That* part i still havent nailed. 
So in summery:
2034 describes blocks that are user-deleted (explicitly deleted) and are 'invisible' but DO play!
*This* describes blocks that are *visible* **before** normal saving, but are *completety gone* visible as well as logical, when the project is reopened - The block in question is lost, for good.
*This* bug is however intimate linked to 2147, because the appearance of 2147 will result in *both*.

iow
If a block cant be copied (video & 2147) *that* same block will be lost, next time the project is reopend (*this* report)
The real problem is that, so far,  there is no obvious event-based reason for the appearance of the bug -It is random, and i cant figure out a test-methodical sane way to hunt for it, other that just use lmms...

**Comment by musikBear** [comment] 2015-07-22 14:56
I have managed to capture the second copy-behavior where empty blocks appear when full-'faker'-blocks are dropped

This picture shows the large noteblock hold in ctrl+lm, and ready to be dropped

![vlcsnap-2015-07-22-16h40m53s393](https://cloud.githubusercontent.com/assets/6662066/8828295/b541ca7c-3091-11e5-9373-24e47cff7308.png)

Here the copy-block are being placed in a different track

![vlcsnap-2015-07-22-16h42m22s487](https://cloud.githubusercontent.com/assets/6662066/8828302/bf5bdf70-3091-11e5-807b-bc0ab38b3af8.png)

Here it has been dropped, but there is only an empty container-block, there is no block with the notes

![vlcsnap-2015-07-22-16h41m46s503](https://cloud.githubusercontent.com/assets/6662066/8828314/cc093d6c-3091-11e5-87ee-5cefa49ce5d2.png)

The 'parent-block' played in both piano-roll, *and in song-editor*!
But it did not behave as a logic noteblock, after the project was saved and reopend, the parent-block was not included in the file.

I also have low-Q video of the full behavior

**Comment by tresf** [comment] 2015-07-22 15:32
I think the symptoms can be explained a bit easier to understand.  By "CTRL + LMB" you simply mean, Copy/Paste, right or is this bug only reproducible with shortcut keys?

And by "empty container block", you mean "Paste to another track", right?  I would recommend you clean this up a bit so others can reproduce.  The dedication is noble, but we'll need to have the clear steps to reproduce, and a good bug report should be updated to reflect that.

**Comment by tresf** [comment] 2015-07-22 15:33
Also, in this case, they don't disappear, they are pasted as blank blocks and therefore are displayed incorrectly, right?  Or do they eventually disappear?

**Comment by musikBear** [comment] 2015-07-22 15:41
you cant reproduce - its a completely random occurrence
wheater or not it is the same with context-option copy/paste, i will have to test if it re-occur, i expect it will
> Also, in this case, they don't disappear, 
It is, as written the PARENT block that disappear 
Not the block that was *copied*, but the block that was copied **from**
It does not exist **logically**

**Comment by tresf** [comment] 2015-07-22 15:47
> It is, as written the PARENT block that disappear 

"source" and "destination" would be a more proper term, "parent" is confusing and inaccurate as there is no child/parent relationship with copied patterns.

Either way, the title and description needs improvement and that's on you.

**Comment by tresf** [comment] 2015-08-27 05:20
I understand this is a problem that randomly crops up from time to time, but to fix it, we need steps to reproduce.  Please reopen when you have a properly written steps to reproduce.  If it can only be created randomly, then please accept that we will close this at a random time in the near future (when someone stumbles upon the offending code).

**Closed by tresf** 2015-08-27 05:20 UTC

**Comment by musikBear** [comment] 2015-08-31 10:58
This will be an issue for 1.2, IF! Master still has this problem. 
I just looked in a project and to my surprise, a block that i worked om yesterday, was not there anymore 
..and yes - i *did* save before closing ..

**Comment by tresf** [comment] 2015-08-31 12:30
When you have steps to reproduce, we'll work on this.

**Comment by StakeoutPunch** [comment] 2015-08-31 13:47
>I think that is because you have high access-rights (Owner). I do not have that button :)

![image](https://cloud.githubusercontent.com/assets/6579031/9580109/f9500cde-4fbc-11e5-98da-2413b024e175.png)

**Comment by musikBear** [comment] 2015-09-01 11:24
@StakeoutPunch nice reference, but i may be stupid, but not a complete idiot :package: 
![noreopen](https://cloud.githubusercontent.com/assets/6662066/9602900/bd5d07b8-50ac-11e5-899d-c9644426fd27.jpg)

**Comment by musikBear** [comment] 2015-09-03 13:13
I have news in respect to the behavior.
Unfortunately, not a method to reproduce, but i have found a way to make lmms recognize the dodgy block.
A block with the fault has this 'no-copy' & 'no-saving' behavior, but it is still **movable** 
After it has been **moved** a couple of bars in song-editor, it is again recognized by lmms, and ca *now* both be copied and will also be saved.
This is imo interesting, and perhaps a dev can see something in this, that could point to where the actual flaw comes from?
