### ISSUE TITLE
Sample track not audible when not playing it from the start in the song editor

### ISSUE THREAD

**Issue by derander1** [LMMS/lmms#3376] opened 2017-02-21 20:38 UTC
As the title says, if you want to listen to your song via song editor, and you start somewhere after a sample should start playing, the entire sample will be skipped.

Maybe it has something to do with my sample being a minute long?

**Comment by tresf** [comment] 2017-02-21 21:03
Duplicate of https://github.com/LMMS/lmms/issues/131; #1471.

**Closed by tresf** 2017-02-21 21:03 UTC

**Comment by derander1** [comment] 2017-02-21 21:13
Ah sorry, I really thought I checked all before posting

**Comment by tresf** [comment] 2017-02-21 21:36
> Ah sorry, I really thought I checked all before posting

No worries.  Long story short, 1.2.0-RC2 has it fixed for the Windows/MacOS users.  Just scroll down to Beta Versions.  https://lmms.io/download/

**Comment by derander1** [comment] 2017-02-22 06:49
Ahh thats a bit unfortunate, I was palnning on using this on linux

**Comment by tresf** [comment] 2017-02-22 06:51
You still can we just don't have binaries available yet for Linux, you'd have to build from source.
