### ISSUE TITLE
Crackling sound in master branch

### ISSUE THREAD

**Issue by midi-pascal** [LMMS/lmms#2708] opened 2016-03-26 19:10 UTC
The sound is crackling while playing pieces. 
I updated today from master, cleaned, rebuild and reinstalled from scratch.
This problem was not occurring one week ago or so (not sure though), the sound was perfect.
I tried a bit with some other instrument plugins and it seems the crackle happens especially at the beginning of each note with sounds having a neat attack. This is specially audible using Kicker.

Same project plays perfectly with 1.1.3 (not crackle)

Ubuntu 14.04 64bit
master branch

To reproduce:
Import a Midi file.
Just play (no effect added)
or
Start a blank project
Add Kicker
Open the instrument view
Play with the small keyboard

**Comment by zonkmachine** [comment] 2016-03-26 22:47
> This is specially audible using Kicker.

I actually tweaked kicker a weak ago and this for backward compatibility but I don't see this crackle.
https://github.com/LMMS/lmms/pull/2678

**Comment by midi-pascal** [comment] 2016-03-26 23:13
@zonkmachine This is not kicker-specific. The crackling is just more audible with it because the sounds have a straight attack but I can ear the crackle while playing a piece through Sf2 or fiddling with other instrument plugins (mallets, for example). I would eliminate a hardware or external library problem since the same crackling piece plays just fine with Lmms 1.1.3 on the same machine. Other sound software do not show the problem either. I am perplex on this one.

**Comment by zonkmachine** [comment] 2016-03-27 01:00
I got it too now and it began in 32b7e0418b55d2fb6e45bff9a32103e532a9dab5
@Fastigium

**Comment by midi-pascal** [comment] 2016-03-27 01:31
@zonkmachine I am pleased to know I am not the only one encountering this issue and also to have detected it before 1.2 is out. This is a major issue since it impacts all  instrument plugins.

**Comment by zonkmachine** [comment] 2016-03-27 01:54
![crackle](https://cloud.githubusercontent.com/assets/6368949/14063379/fa34c2a0-f3ce-11e5-8c6f-5bdbe0c89354.png)

It's little glitches going to zero and I get them with instruments that share a channel. ( This without testing it extensively though ). I add a simple project that has this noise in current master. If you change mixer channel on one of the instruments the noise goes away.

[issue-2708.zip](https://github.com/LMMS/lmms/files/190737/issue-2708.zip)

**Comment by Fastigium** [comment] 2016-03-27 07:30
On it, guys, thanks for the quick heads-up! On first sight, I may have been too enthusiastic removing [`m_fxChannels[_ch]->m_lock.lock()`](https://github.com/LMMS/lmms/commit/32b7e0418b55d2fb6e45bff9a32103e532a9dab5#diff-b6cdb0811e7a10721f0bfb60ea98f525L551). I'll try to reproduce and see if reintroducing that lock fixes it. Strange that this didn't turn up in testing #2675, though admittedly that testing was focused on other issues :grin:

**Comment by Fastigium** [comment] 2016-03-27 08:09
Hm, I can't reproduce the issue. I tried @zonkmachine's project, I tried playing with Kicker's small keyboard, I tried importing a MIDI file, all glitch-free here. Nevertheless, I still suspect the lock removal, so I made a pull request that reintroduces the lock: #2709. Please let me know if that fixes things for you!

**Comment by midi-pascal** [comment] 2016-03-27 11:29
@Fastigium Yep! This PR definitely solves the problem. :+1: Pure crystal sound is back :smile:

**Comment by Fastigium** [comment] 2016-03-27 12:07
@midi-pascal Glad to hear that!

@tresf I would merge #2709 now if not for the Travis build failing on the QT4 Mac build. Is that a freak random error or does it require action of some kind?

**Comment by Umcaruje** [comment] 2016-03-27 12:37
>@tresf I would merge #2709 now if not for the Travis build failing on the QT4 Mac build. Is that a freak random error or does it require action of some kind?

I restarted that particular build now, Travis tends to glitch from time to time, so a restart is all that is needed.

**Comment by Umcaruje** [comment] 2016-03-27 13:02
@Fastigium everything passes now :+1:, looks ok to merge to me.

**Comment by Fastigium** [comment] 2016-03-27 13:02
@Umcaruje Heh, I have just merged it, thanks :yum:! Closing this issue now!

**Closed by Fastigium** 2016-03-27 13:02 UTC
Labels: bug

**Comment by tresf** [comment] 2016-03-27 13:08
:+1:

**Comment by Fastigium** [comment] 2016-03-27 15:44
Special kudos to @zonkmachine, whose reproduction and pinpointing work made this a breeze to fix :+1:

**Comment by midi-pascal** [comment] 2016-03-27 15:51
:+1: to @zonkmachine
