### ISSUE TITLE
Support for HDPI Monitor Resolution

### ISSUE THREAD

**Issue by mgm1992** [LMMS/lmms#2919] opened 2016-07-15 18:25 UTC
Viewing on a device with an HDPI Monitor results in tiny UI elements. This makes usability difficult without altering the system resolution (which in turn 'knocks out' the rest of the OS UI appearance).

The current GUI could be enhanced to support HDPI monitors so that the GUI does not appear like the attached image. 
![untitled-1](https://cloud.githubusercontent.com/assets/2804392/16884539/e4ed2c1c-4ac1-11e6-932c-f689ff29dbd1.jpg)

**Comment by jasp00** [comment] 2016-07-15 19:03
Duplicate of #2510.

**Closed by jasp00** 2016-07-15 19:03 UTC
Labels: duplicate
