### ISSUE TITLE
Equaliser not showing audio spectrum / showing only input/output result instead of both randomly

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6218] opened 2021-11-14 03:53 UTC
### Bug Summary
The equalizer sometimes doesn't display anything on the spectrum analyzer despite corresponding audio output. It may not show on the spectrum analyser in these cases, but it shows in the per-band output, see screenshot.
Corresponding lmms forums bug report [here](https://lmms.io/forum/viewtopic.php?f=7&t=34938), it has a video to show what exactly is happening.

#### Steps to reproduce
1. Download the following file:
[tipo sueño.zip](https://github.com/LMMS/lmms/files/7533147/tipo.sueno.zip)
2. Add an equalizer to master (or open the equalizer on the instrument)
3. Open the solo'ed beat/bassline and play it
4. Open equaliser controls from master
5. Wait

#### Expected behavior
Equaliser always show output on spectrum analyzer for audio

#### Actual behavior
Equaliser shows output only sometimes

#### Screenshot
![image](https://user-images.githubusercontent.com/76674645/141666642-59e0ce4c-2df7-4344-81db-e784947efb83.png)
Screenshot of equalizer display^

[Video](https://youtu.be/gETUL5MTx6I) displaying bug

![image](https://user-images.githubusercontent.com/76674645/141666758-a75670f2-4ade-4f2f-b020-bb8fbf4a9b10.png)
Screenshot of piano roll of sequence in question

#### Affected LMMS versions

1.2.0, 1.3 alpha

**Comment by allejok96** [comment] 2021-11-14 07:54
Duplicate of #6122

**Comment by Monospace-V** [comment] 2021-11-14 09:58
Notes don't seem particularly "short" in this case, that's why I took a screenshot of the piano roll here. but not sure.

**Comment by allejok96** [comment] 2021-11-15 15:39
Perhaps the description of 6122 is misleading. The spectrum view analyzes *sound* not notes. While the notes in your example are long, you can hear they only produce a very short click sound. Like illustrated in 6122, the randomness of this bug comes from the way the algorithm works. It checks the audio signal every few milliseconds and if a sound happens between two checkpoints, it won't be detected. There are ways to fix this though.

**Comment by PhysSong** [comment] 2022-01-19 04:26
> Duplicate of #6122

> Perhaps the description of 6122 is misleading.

Yes, it is.

**Closed by PhysSong** 2022-01-19 04:26 UTC
Labels: bug
