### ISSUE TITLE
Saving an .XYZ preset from LMMS' Zyn implementation crashes it.

### ISSUE THREAD

**Issue by GeekyGami** [LMMS/lmms#6274] opened 2022-01-14 03:40 UTC
### Bug Summary
On Windows, when going under instruments>save in Zyn's interface, to save as a Zyn specific preset, Zyn crashes entirely.
This means .xyz files cannot be saved.
#### Steps to reproduce
Be on Windows, on version 1.3.0-alpha-1.102
Add in a Zyn instrument.
Open up Zyn's interface.
At the top of it, under instrument, click Save Instrument.
#### Expected behavior
Saving dialog for the preset.
#### Actual behavior
Zyn freezes and then crashes.
#### Affected LMMS versions
1.3.0-alpha-1.102, only under Windows.
Linux is unaffected.

**Comment by Monospace-V** [comment] 2022-01-14 06:00
Can replicate on 1.2.0, 1.3 alpha. Is a duplicate of https://github.com/LMMS/lmms/issues/4455.
After Zyn crashes, opening Zyn's GUI again and hitting Instrument > Save seemed to work _once_ but I couldn't get it to work again.
Requesting you to check tracker for duplicates before posting a bug report.

**Closed** 2022-01-14 06:50 UTC
Labels: bug, duplicate
