### ISSUE TITLE
Custom VST Doesn't show up plugin list when a channel is clicked on.

### ISSUE THREAD

**Issue by darkmastermindz** [LMMS/lmms#4585] opened 2018-09-09 17:46 UTC
Usually in a DAW, there is a list of the plugins you can use or have installed on the left side of the screen and you can drag them into the timeline view.

**Comment by SecondFlight** [comment] 2018-09-09 23:08
It's not clear to me what you're reporting. Please clarify with screenshots and steps to reproduce. Thanks!

**Comment by musikBear** [comment] 2018-09-10 14:37
@SecondFlight He expect that VSTs that are *installed* on his system, automatically get a folder in lmms.
@darkmastermindz That does not happen in lmms. you can *manually* add a folder for saved VST-xpf files, in your own presets, and *that* folder will appear in the sidebar. The files will however not be VST-type-files, but will be lmms-presets-files, that then initiate the *correct* VST, when you open the preset. That is lmms' way to handle vst-presets. Other DAWs may do it differently, but lmms does it **that** way!

**Comment by Spekular** [comment] 2020-03-31 08:54
Closing and consolidating into #5433

**Closed by Spekular** 2020-03-31 08:54 UTC
Labels: enhancement

**Comment by messmerd** [comment] 2026-01-14 08:58
This is blocked by #1837 since it would require VST plugin scanning.

I'm assuming the user is requesting VST plugins to show up in the sidebar like native LMMS plugins and LV2 plugins currently do, so I've changed the title to make it more clear.
