### ISSUE TITLE
1.0.2 Tab-plugin?

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#724] opened 2014-05-15 15:06 UTC
Has some 'old'  plugins been  dropped? Opend a 2009 project and got a missing plugin error:
http://snag.gy/4QJCq.jpg
That will break backward compatibillity -Have that -ever- been a part of the package..? 8|  
.. If so, Should they be added again, even if they were inferior?
*edit*
Could that error message be more informative? Fo9e instance tell the user -whitch- pluging that tried to load the missing effect. That would make the 'repair' much more simple for the user.

**Comment by Umcaruje** [comment] 2015-06-30 11:27
I'm closing this as a won't fix, since not many people will open their 2009 projects inside lmms, and the problem is only in one plugin, so its fairly easy to fix the issue by replacing it inside your project.

**Closed by Umcaruje** 2015-06-30 11:27 UTC
Labels: won't fix
