### ISSUE TITLE
VSTi: Can't change value of dropdown select box

### ISSUE THREAD

**Issue by SDwarfs** [LMMS/lmms#4424] opened 2018-06-12 21:22 UTC
The following has been tested with LMMS 1.1.3, 1.2-rc5 and 1.2-rc6 under Windows 10, but also tested LMMS 1.1.3 under Windows 7.
The VST-Plugin used is TAL NoiseMaker (4.2.2.0, 64-bit), which has several dropdown select boxes (e.g. to change the wave form of the oscillators between SAW, PULSE, NOISE etc). When clicking on the option the drop down menu opens, but is flickering (closed immediately) and cannot be changed through the integrated VSTi-GUI. It can however be changed using the "VST Plugin Controller" and by loading presets.
However, the plugin is working fine in Cubase LE Elements 8 installed on the same computer. So it does not seem to be an issue of the operating system or the VST itself. And I assume it's related to dropdown select boxes in general, i.e. not restricted to this special VST plugin.

**Comment by DomClark** [comment] 2018-06-12 23:23
Sounds like a similar issue to #3918. I'll investigate and see if they are indeed related.

**Comment by SDwarfs** [comment] 2018-06-13 08:47
@DomClark: #3918 is indeed related. I downloaded the Helm-VST and had the same issues with the menu which is to change the "type" under "Distortion" from initial value of "sft clp" to something else. So it's now sure that this issue is not a bug in this special VST-GUI, but in VeSTige.

**Comment by musikBear** [comment] 2018-06-13 15:22
@SDwarfs 
Looks like this could be a 64x issue. I can use the DD's fine on RC6 with the x32 TALnm:
![tal_nm_32_dropdowns](https://user-images.githubusercontent.com/6662066/41361015-50160fee-6f2e-11e8-8779-5cc8ffd46a55.JPG)

**Comment by SDwarfs** [comment] 2018-06-13 17:58
@musikBear 
I tried the 32bit-Version of TAL NoiseMaker with Windows 10 (64bit) and LMMS 1.2-RC6 too, but I had no luck. I tried both, 32bit and 64bit Version of LMMS.
Which Version of TALnm did you use? And do you also use the 32bit Version of LMMS? Which Operating System? And do you have a 32bit or a 64bit Operating System installed?

**Comment by SecondFlight** [comment] 2018-06-13 19:56
He's on 32-bit Windows XP, which means his LMMS and TAL Noisemaker are both 32-bit as well. He will have to say which version of TAL Noisemaker he's using.

**Comment by DomClark** [comment] 2018-06-13 21:56
I've downloaded the plugin and tested it out. It appears to work fine under "No embedding"; the issues appear when the UI is embedded within LMMS. This is the same as with Sylenth and Helm. The menu bug appears to be slightly different in this case compared to the other two - in Helm the menu doesn't appear at all, or only appears very briefly; in Sylenth the menu appears but disappears as soon as the mouse is moved; in TAL Noisemaker the menu appears, flickers as the mouse is moved, and disappears once the mouse leaves the dropdown box. I guess they're all related, but I have no idea if TAL Noisemaker or Sylenth use Juce, which appeared to be the cause of the Helm bug, or whether any of them are fixable. I think this issue should be left open since it isn't clear if this is genuinely the same issue as with Helm. I'll do some investigation.

**Comment by SDwarfs** [comment] 2018-06-13 21:59
Ok, I got an old version of TAL Noisemaker (32bit) from:  https://web.archive.org/web/20170228183957/https://tal-software.com/downloads/plugins/TAL-NoiseMaker.zip -- and it's working. So @musikBear  possibly has some old version, too. So it's somehow related to a change in the Plugin.

**Comment by SDwarfs** [comment] 2018-06-13 22:14
@DomClark - I can confirm that its working with "No embedding" Option (Edit->Settings->MISC: "Plugin Embedding" = "No embedding").

**Comment by musikBear** [comment] 2018-06-14 15:40
TALnm v3.10 32 bit, so yours @SDwarfs are indeed newer. 
(it actually a good plugin!
About HELM, it did not preserve changed dials, when i tested it, and i did put it on the no-good list, for that reason.

**Comment by DomClark** [comment] 2018-12-09 15:19
Closing as duplicate of #3918. We will try to address this for 1.3, in the meantime use "No embedding" for 
the "Plugin embedding" option.

**Closed by DomClark** 2018-12-09 15:19 UTC
Labels: bug, vst
