### ISSUE TITLE
Could not open C:/Users/Administrator/Document/LMMS/recover.mmp .. 

### ISSUE THREAD

**Issue by jbwaylett** [LMMS/lmms#5539] opened 2020-06-16 01:13 UTC
I get pop up window every few minutes stating:

"Could not open C:/Users/Administrator/Document/LMMS/recover.mmp for writing. You probably are not permitted to write to this file. Please make sure you have write-access to the file and try again".

I am signed in as Administrator and am opening LMMS as Administrator. I have full rights and access to the directory LMMS. So, I should not be getting this pop up window.

Need some help figuring this out. It seems to be a bug but I can't find the root cause.  

#### Steps to reproduce

![image](https://user-images.githubusercontent.com/66980635/84720766-ee620d00-af4c-11ea-9a02-2acb161c16dc.png)

LMMS version 1.2.1

**Comment by Spekular** [comment] 2020-06-16 07:10
If you navigate to the recovery file in explorer and check it's file permissions, what do you find? Does the issue still occur if you delete the file?

**Comment by jbwaylett** [comment] 2020-06-17 00:13
The recovery file does not exist. It does not get set up. I can load a midi
file into LMMS and start working on it but the message window keeps coming
up with the warning. Very strange.



____________________

John B. Waylett
www.johnwaylett.com

[image: https://www.youtube.com/channel/UCn7wkz2WEGwKjhMujvDyE_w/videos]
<https://www.youtube.com/channel/UCn7wkz2WEGwKjhMujvDyE_w/videos>    [image:
https://www.facebook.com/johnbwaylett/]
<https://www.facebook.com/johnbwaylett/>    [image:
https://www.linkedin.com/in/johnwaylett/]
<https://www.linkedin.com/in/johnwaylett/>

<http://www.johnwaylett.com>

**Comment by Spekular** [comment] 2020-06-17 09:15
Is it actually located in `C:/Users/Administrator`, or is "Administrator" a placeholder for your account name? Or is your account name actually "Administrator"?

I ask because my recovery file is in `C:/Users/[my username/[...]`.

Also, why are you running LMMS as an administrator? It should work fine without doing so, and using "run as administrator" may even be the cause of this issue. Please test running it normally and see if the problem still occurs.

**Comment by jbwaylett** [comment] 2020-06-17 11:07
Hi and thanks for your help. Much appreciated. The only User accounts I
have set up are Administrator, Public and Default. I only use
Administrator. All my files are under Administrator (i.e. Documents,
Videos, Music, .....). When I open LMMS all looks fine. When I import a
midi file I very soon get the message, even when I stop running LMMS as
Administrator.
See screen shot. Same thing.


[image: image.png]







____________________

John B. Waylett
www.johnwaylett.com

[image: https://www.youtube.com/channel/UCn7wkz2WEGwKjhMujvDyE_w/videos]
<https://www.youtube.com/channel/UCn7wkz2WEGwKjhMujvDyE_w/videos>    [image:
https://www.facebook.com/johnbwaylett/]
<https://www.facebook.com/johnbwaylett/>    [image:
https://www.linkedin.com/in/johnwaylett/]
<https://www.linkedin.com/in/johnwaylett/>

<http://www.johnwaylett.com>

**Comment by jbwaylett** [comment] 2020-06-19 02:02
Is there some way I can escalate this issue? It may be me but I can't see
what I could be doing wrong.
No matter what I do I keep getting the same message.
Thanks,
John

**Comment by Spekular** [comment] 2020-06-19 06:48
Unfortunately I'm about out of ideas, but here's two more shots in the dark:
- Try installing and using LMMS on a different Windows account, that isn't named Administrator. Perhaps this is a reserved name in some way and that's causing issues.
- Try checking what the file permissions for C:\Users\Administrator\Documents\LMMS to ensure your current user has access to the folder.

**Comment by jbwaylett** [comment] 2020-06-19 13:54
I changed to a non-administrator account. I uninstalled and re-installed
LMMS via this non-administrator account.
The same problem occurred .. this time for for the non-administrator
account.

[image: image.png]

Are there any LMMS SW developers that have seen this behavior before?
This is so strange.




____________________

John B. Waylett
www.johnwaylett.com

[image: https://www.youtube.com/channel/UCn7wkz2WEGwKjhMujvDyE_w/videos]
<https://www.youtube.com/channel/UCn7wkz2WEGwKjhMujvDyE_w/videos>    [image:
https://www.facebook.com/johnbwaylett/]
<https://www.facebook.com/johnbwaylett/>    [image:
https://www.linkedin.com/in/johnwaylett/]
<https://www.linkedin.com/in/johnwaylett/>

<http://www.johnwaylett.com>

**Comment by zonkmachine** [comment] 2020-06-19 15:52
> Are there any LMMS SW developers that have seen this behavior before?

Yes, but it's always been easy to fix. On Linux I can easily recreate this issue by changing the LMMS working directory to `/`, the root directory, which an ordinary user don't have writing access to. You can change this in `Edit/Settings/Paths`. The quick fix for you would be to turn off the Auto-save function. You do this in `Edit/Settings/Performance settings`. Unfortunately I know preciously little about Windows so I don't think I can help you sort this out other than describe where this message originate in LMMS.
The Auto-save function writes a backup copy of the project you're currently working on to a file named `recover.mmp` which lives in the LMMS working directory. If the Auto-save function is turned on and the user launching LMMS has write access to the working directory, `recover.mmp` is created after the set backup time interval. This is by default 2 minutes. If it can't write to this file you will get the pop-up message you're seeing. Since you do have write access to the directory, maybe there is an old `recover.mmp` file there with other access rights which doesn't allow LMMS to write to it, or delete it after a session, on closing LMMS.

**Comment by jbwaylett** [comment] 2020-06-20 19:00
Ok .. thanks for your help. I will try your suggestions.
Best regards,
John
____________________

John B. Waylett
www.johnwaylett.com

[image: https://www.youtube.com/channel/UCn7wkz2WEGwKjhMujvDyE_w/videos]
<https://www.youtube.com/channel/UCn7wkz2WEGwKjhMujvDyE_w/videos>    [image:
https://www.facebook.com/johnbwaylett/]
<https://www.facebook.com/johnbwaylett/>    [image:
https://www.linkedin.com/in/johnwaylett/]
<https://www.linkedin.com/in/johnwaylett/>

<http://www.johnwaylett.com>

**Comment by PhysSong** [comment] 2020-10-03 05:27
@jbwaylett Is this problem still relevant?

**Comment by jbwaylett** [comment] 2020-10-03 13:35
No tks




John B. Waylett
www.johnwaylett.com
519-500-4002

**Closed** 2020-10-03 13:59 UTC
Labels: bug
