### ISSUE TITLE
Midi Import hang

### ISSUE THREAD

**Issue by lmmsuser1001** [LMMS/lmms#1971] opened 2015-04-17 23:20 UTC
In version 1.1.3 (win32) the import of larger midi files hangs always at 66%.

In version 1.0.0 (win32) the import does not hang but the drum channels are not imported.

Does a workaround exist (for example converting midi files to a lmms project file with an external tool)?

**Comment by Wallacoloo** [comment] 2015-04-17 23:24
Could you provide a midi file for which this problem occurs? That would
make it easier for us to verify and track down the error.

**Comment by lmmsuser1001** [comment] 2015-04-17 23:38
Unfortunately, it is not possible to attach a midi file.

But most of the files that you can download from the link below will hang (e.g. Twenty_4_Seven-Take_Me_Away.mid) on win XP.

http://www.eurokdj.com/ringtones/index_midis.php

**Comment by softrabbit** [comment] 2015-04-18 06:30
Importing drums has improved a bit in master, but there are probably files where it still sucks badly.

**Comment by musikBear** [comment] 2015-04-18 09:56
sometimes it help to convert the problem file to 'midi1' 
Anvill-studio (free) can do that

**Comment by softrabbit** [comment] 2015-04-18 13:35
Looks like the example file has so short notes in the drum track that LMMS rounds them down to 0 ticks and ignores them. I'm thinking a simple addition of ```ceil()``` in https://github.com/LMMS/lmms/blob/master/plugins/MidiImport/MidiImport.cpp#L398 should do it.

Didn't get a hang on Linux with master branch, but the window did go dark while importing, which might be related to the hang, e.g. LMMS not responding to some OS message or whatever.

**Comment by DeRobyJ** [comment] 2015-04-18 15:44
I've had this problem too. Sometimes, if you're luck, you just have to wait 3 o 4 minutes. But most of the times it will stop responding forever.

**Comment by Wallacoloo** [comment] 2015-04-18 16:34
Sounds like we aren't calling qApp->processEvents() regularly during the
import process.

**Comment by softrabbit** [comment] 2015-04-21 07:56
And the import really is awfully slow. I compared Rosegarden (3 seconds) and LMMS (25 seconds) opening the file mentioned above. 

After some poking around I believe most of the time (~18 seconds in my test or some 70-ish %)  is spent in this if clause: https://github.com/LMMS/lmms/blob/master/plugins/MidiImport/MidiImport.cpp#L435. Even if there is a huge number of pitch bends or something in that file, I think it's worth a closer look.

**Comment by michaelgregorius** [comment] 2015-04-27 21:28
I did some profiling with Valgrind and it turns out that there are two main causes for the slow import of the aforementioned MIDI file (`Twenty_4_Seven-Take_Me_Away.mid`):
* The call to `TextFloat::displayMessage` in `AutomationPattern::addObject`. It seems like `TextFloat::displayMessage` is called over and over again during the import (for that file).
* The calls to `createDetuning` in `Note::Note` and `Note::loadSettings`. The main problem with `createDetuning` seems to be the sheer number of `DetuningHelpers` that are created during the import. The instances are created using the `MemoryPool` but even that seems to be of no help here. It might be that this problem can only be alleviated by changing the design. Does every note really need its own `DetuningHelper`?

If you comment out the aforementioned calls the import just flies.

The calls to `createDetuning` in the `Note` class also slow down the loading of LMMS project files by the way. You can reproduce this by profiling the loading of `DnB.mmpz` with Valgrind. So solving this problem would kill two birds with one stone and give users faster loading of projects and faster import of MIDI data.

**Comment by softrabbit** [comment] 2015-04-27 21:51
@michaelgregorius, see https://github.com/softrabbit/lmms/commit/1e29da4aae9f0491de7d19919a6504c06ed64fe1 for my thoughts on ```AutomationPattern:addObject``` in this context.

**Comment by Wallacoloo** [comment] 2015-04-27 21:57
@michaelgregorius That's very useful info - thanks for sharing it here. I don't know enough about the internals to answer the DetuningHelper question, but all I can say is to be careful when using Valgrind as a profiler. On top of executing each instruction, it does a whole host of dependency tracking (in order to catch uses of uninitialized variables) and such *for every instruction*. This means that because of the overhead, an integer division might take only 3% longer than an integer add, vs 300% longer when run outside of valgrind. Similar issues occur with its heap allocator, which results in new/delete operations taking much longer than they typically would in normal execution.

So it's quite possible that the two bottlenecks you mentioned could be anomalies that only become significant under valgrind and not in regular use. I'd recommend an alternative, but my experience with profiling is fairly minimal beyond that.

**Comment by tresf** [comment] 2015-04-28 13:40
FYI, in regards to the MIDI files.... for uploading files, it looks like GitHub will have a storage solution very soon.... 

https://github.com/early_access/large_file_storage/

Thought it was slightly on-topic in regards to hosting some of these files. :)

**Comment by michaelgregorius** [comment] 2015-04-28 19:01
@Wallacoloo I think Valgrind was pretty accurate in this case. Here is what I did in my profiler run using a release build:

1. Start the application
2. Import the MIDI file
3. Close LMMS

After the analysis of the results I then commented out the calls to `TextFloat::displayMessage` and the two calls to `createDetuning` in `Note::Note`, recompiled and tested the import in a release version without Valgrind. It became a lot quicker immediately. So these two code areas in fact seem to be some bottlenecks.

The way I understand it Valgrind simulates the CPU (instructions) and should therefore know exactly which instructions are executed and what cost are associated with each instruction. However, I don't what exact models they use, i.e. whether they model the different microprocessor architectures, etc.

Does anyone know a good free stochastic profiler by the way? These usually don't have that much impact on the execution time and performance but still provide a good picture of what's happening.

**Comment by Espyo** [comment] 2015-04-28 19:58
I just want to drop in some help as well. An example of a MIDI file I used to be able to open just fine, but now can't, as per all that's been discussed so far, is the Koopa Cape MIDI on this page http://www.vgmusic.com/music/console/nintendo/wii/ (check under Mario Kart Wii).

**Comment by michaelgregorius** [comment] 2015-04-28 20:50
@Espyo Do you mean that the Koopa Cape MIDI file just opens slowly or that you cannot open it at all? Just asking because on my local master build the file is imported successfully.

Again if I comment out the call to `TextFloat::displayMessage` in `AutomationPattern::addObject` the performance during import is a difference like night and day.

I assume that the current implementation of `AutomationPattern::addObject` was meant to be used in interactive cases where the user wants to create a connection that is already there and that it was not meant to be called from "non-interactive" code like the MIDI import. The question is whether the information provided by the displayed message is really useful to the user in the first place. If he connects something that's already connected and the system is able to handle this case gracefully, i.e. doing nothing will have the exact effect that the user intended, then why tell him that the connection is already there? It almost comes across like "You did something really stupid and I will even tell you." :smile: So the simplest solution might be to remove the message altogether.

If the message should be kept for interactive cases (and my assumption is correct in the first place) there are two ways I can think of to handle the problem:
1. Let `AutomationPattern::addObject` return a boolean that indicates whether the model was added and remove the call to `TextFloat::displayMessage`. In case the model is not added the caller may decide what to do. In an interactive context the message could still be shown whereas in an non-interactive context, e.g. the MIDI import, the result is just ignored and no message is shown (and performance is good).
2. Add a boolean parameter to `AutomationPattern::addObject` which indicates whether it's called from an interactive context which means that the message should be shown or a non-interactive context which means that no messages are shown.

I would prefer the first solution because it keeps the usage of `AutomationPattern::addObject` more flexible, i.e. it would be simpler to implement some third, forth, etc. kind of behaviours in other callers. It also provides a better separation between presentation and functionality.

**Comment by Espyo** [comment] 2015-04-28 20:57
@michaelgregorius Sorry, should've been more detailed. Yeah, that MIDI is one of the cases where it slowly imports, and then hangs on the 66% mark.

**Comment by michaelgregorius** [comment] 2015-04-29 19:26
@Espyo No problem. :) The problem with the failing import should be fixed in master.

**Comment by tresf** [comment] 2015-04-29 19:54
@michaelgregorius, ok to close?

**Comment by michaelgregorius** [comment] 2015-04-30 08:49
@tresf I guess it should be OK to close the issue. I have create two new issues which cover the performance problems.

**Closed** 2015-04-30 11:00 UTC
Labels: bug, gui

**Comment by Umcaruje** [comment] 2015-04-30 11:11
>I have create two new issues which cover the performance problems.

:+1:
