### ISSUE TITLE
Bring back Middle Click for Starting Loop Points.

### ISSUE THREAD

**Issue by Xeno-Idaltu** [LMMS/lmms#6373] opened 2022-04-14 01:59 UTC
On 1.3.1-Alpha this feature has been disabled.

I honestly don't know why something so useful, simple, and already the most efficient was thrown away in favor of the new simplistic feature.

Its hard to set Loop Points because we have to zoom out and bring the bar to where we want it to be, this is counter intuitive. On big projects I used to set loops without all that hassle. Developers didn't even gave us the option to at least use Shift+LeftClick to set the Beginning of a loop. LeftClick sets both Beginning/Ending loop points..

##

Since LMMS will take a very long time to fix this issue, I'd like to know what I need to do to bring back this feature. I tried by reading old posts but LMMS-1.2's code is different from LMMS-1.3

**Comment by Spekular** [comment] 2022-04-14 10:31
Duplicate of #5505

**Closed by Spekular** 2022-04-14 10:31 UTC
Labels: enhancement
