### ISSUE TITLE
Macro knobs: for automating like 50 things all with one track =D 

### ISSUE THREAD

**Issue by TheDichotomist** [LMMS/lmms#498] opened 2014-03-21 22:36 UTC
i know you guys are probably getting sick of reading stuff from me but i think i finally have something you guys can pull off for a future milestone =D 

new controller type: Macro controller

just a knob or fader that you connect multiple things to, from there you can connect that to automation or lfo. the reason this is useful is because each thing connected will have an editable min/max value assigned to it so as the macro's position value increases (say to 100% ) each thing connected to it will move to it's assigned max value (say 50% for one connected parameter and 78% for another.) . if you need further information i'll be here... or you can google it. this is a feature in ableton live and fl studio. thought it might be easier to pull off than everything else i asked for in the past =D

**Comment by Umcaruje** [comment] 2015-06-27 11:25
Duplicate of #1332

**Closed by Umcaruje** 2015-06-27 11:25 UTC
Labels: duplicate
