### ISSUE TITLE
Cannot get VSTs loading whatsoever

### ISSUE THREAD

**Issue by ornithologistnightmare** [LMMS/lmms#2970] opened 2016-08-11 16:22 UTC
Long story short: I'm an idiot who's trying to get the classic Roland Alpha Juno hoover sound. Unfortunately, ZynAddSubFX doesn't do phase width modulation or have a DC offset and I don't know of any other instrument that can load a wave file instead and get a good unison effect (even with the chorus plugins).

I tried to avoid VSTs as much as possible given that they haven't worked for months in my partially-ruined 64-bit "Debian" setup, but it seems like it's all I can do (AFAIK I can't get portamento by using samples through AudioFileProcessor and having VST support would be extremely convenient to have). I've been on 1.1.3 for a while (I used the Packman builds to get VeSTige); it was fine until I updated various Wine and QT5 libraries. The error came when I tried to load a DLL; RemoteVstPlugin.exe.so hung and nothing really worked. I had 32-bit Wine tools installed, and my version was and still is 1.8.3-2 (IIRC 1.8.2 was the patched one).

Today I tried to build the latest master (1.1.91); to my surprise - given my experience with building programs in general - it worked. I even managed to get VeSTige, but RemoteVstPlugin.exe.so was missing. I added it and:

```
Remote plugin did not connect.
Error while writing.
```

Same error as before. The only difference was that the process was automatically killed and I got no dialog box. I also got this:

```
QXcbConnection: XCB error: 3 (BadWindow), sequence: 34246, resource id: 23232675, major code: 40 (TranslateCoords), minor code: 0
Error while reading.
Unexpected poll error.
Error while writing.
```

I've also noticed that I can't see libwine.so in /lib/i386-linux-gnu/ and /lib/x86_64-linux-gnu/ for some strange reason; I can't seem to get it at that place through packages (installing and reinstalling). Doing an apt-file search brought up no desired results. However, after further experimentation, I can load VSTs as plugins (though their GUIs don't show up).

After trying in vain through Carla, what now? I don't think that this one is fit for the forums or whatever; I doubt that I'll get the help I need.

Version 1.1.91 (Linux/x86_64, Qt 5.6.1, GCC 6.1.1 20160724)

**Comment by musikBear** [comment] 2016-08-12 12:40
I think you may find help in our forum. The one thing i can tell you is that zasfx do have PM 
![zasfxmods](https://cloud.githubusercontent.com/assets/6662066/17622381/4e9c96d2-609a-11e6-8471-963f052e6136.JPG)

and you also have a handle to the depth of modulation in lmms
https://www.youtube.com/watch?v=4gqAlCXt7DI

**Comment by tresf** [comment] 2016-08-12 15:48
> I think you may find help in our forum.

No, the OP's request is 100% development related, he's welcome and encouraged to stay on GitHub.  Forum users are much less likely to help.

**Comment by DeathHammer000** [comment] 2016-08-12 18:00
>phase modulation

Phase width modulation is different.

![Juno wave](http://3.bp.blogspot.com/_6VFosdOGMs4/Sjgt3sduiTI/AAAAAAAAABo/g5PUbx8jfGc/s320/Picture+5.png)

This is the wave I'm trying to get; I'm gonna try to use [this tutorial](http://superdupercollider.blogspot.co.uk/2009/06/more-dominator-deconstruction.html) but with different software (programming and I don't get on well, and I'll have to master SC and slightly fix the code to make it work given that I've already tried to run it in the IDE and got nothing - unless it's just me using the wrong software again). The only way I see fit is to get the VST support working and go mad.

**Comment by ReceivedChunky** [comment] 2016-08-17 16:11
did my name change do something?

**Comment by tresf** [comment] 2016-08-17 16:19
> did my name change do something?

Looks fine from here. :+1:

**Comment by ReceivedChunky** [comment] 2016-08-19 13:01
k thx

**Comment by ReceivedChunky** [comment] 2016-08-30 18:39
->be me
->know nothing about making music
->have VSTs
->mess around with VSTs
->get some ideas
->move from Qt4 to Qt5 and get new Wine when upgrading system
->VST support breaks
->wait for a year, upgrading system
->actually have some ideas regarding music
->VST support still broken
->try to build latest LMMS
->it works
->play around with new features
->VST support **still** doesn't work
->finally give up and create GitHub issue
->get suggestions
->not what I needed
->two weeks go by
->b-but hey, at least ZynAddSubFX is sweet



![don't worry i'm fine] (http://i3.kym-cdn.com/photos/images/newsfeed/001/096/564/2f7.jpg)

**Comment by Spekular** [comment] 2016-08-31 07:46
\>Be me, op
\>Greentext on Github
\>Can't even arrows right

Kidding ofc. I'm probably being stupid, but is there a reason you can't just create a custom waveform in the correct shape and load that in one of the available plugins?

**Comment by ReceivedChunky** [comment] 2016-08-31 13:29
(how did you turn off the markdown i demand to know)

already tried. see original post.

**Comment by tresf** [comment] 2016-08-31 14:30
> how did you turn off the markdown

```
\>Be me, op
\>Greentext on Github
\>Can't even arrows right
```

**Comment by Spekular** [comment] 2016-08-31 21:18
Oh wow it's in the first paragraph, not the greatest reading comprehension on my part. Sorry!

**Comment by ReceivedChunky** [comment] 2016-09-01 05:51
\>my failures in maymaytexting bring some activity

i am saved

**Comment by lukas-w** [comment] 2017-08-31 19:56
Closing as duplicate of #2855 – VST support on Linux is broken with Qt5.

**Closed by lukas-w** 2017-08-31 19:56 UTC
