### ISSUE TITLE
Problem of High Resolution Display.

### ISSUE THREAD

**Issue by heavenity** [LMMS/lmms#4962] opened 2019-04-26 12:43 UTC
I want to use LMMS at 4k display.
But whenever I open pianoroll , LMMS always crash suddenly.
What should I do for it?And is this problem going to be solved?
*LMMS 1.20 rc8

**Comment by DomClark** [comment] 2019-04-26 12:46
This sounds like a duplicate of #4098.

**Closed** 2019-04-26 12:47 UTC
Labels: duplicate
