### ISSUE TITLE
LMMS needs markers

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1703] opened 2015-01-27 18:00 UTC
LMMS needs markers on the top of the song editor to mark out different parts of a song.

FL Studio  markers
![4148ot_05_01 1](https://cloud.githubusercontent.com/assets/8137561/5923806/d1c06e98-a61b-11e4-9da0-2f93054b998d.png)

Pro Tools marker
![markercolor-11 1](https://cloud.githubusercontent.com/assets/8137561/5923830/fcab2288-a61b-11e4-8a1a-15a0d76d8bbc.jpg)

**Comment by tresf** [comment] 2015-01-27 18:04
Duplicate of #156.

**Closed by tresf** 2015-01-27 18:04 UTC
