### ISSUE TITLE
Exprtk damages your whole worktree

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5064] opened 2019-06-29 14:00 UTC
If your worktree collection is from ~May 2019 or older (almost everyone who uses worktrees), adding a new worktree will work, but updating the submodule may bring the following issue:

```
$ git submodule update --init --recursive
Cloning into '...'...
Username for 'https://github.com':
Password for 'https://JohannesLorenz@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/ArashPartow/exprtk/' not found
fatal: clone of 'https://github.com/ArashPartow/exprtk' into submodule path '...' failed
Failed to clone 'plugins/Xpressive/exprtk'. Retry scheduled
```

One bad (but working) solution is to remove your whole worktree collection.

What I now tried was editing .git/modules/plugins/Xpressive/exprtk/HEAD manually, entering a valid ID from ArashPartow's repo, e.g. 12fc5dfa3314db2c3085d297c864b0bf947fa4d1 . **This did not work either.** It should have worked...

Purpose of this issue is to find a solution. Also, since @ArashPartow deletes master commits without thinking of the consequences (it's not the first time), I think we should fork (LMMS/exprtk) to not have problems again and again.

**Comment by ArashPartow** [comment] 2019-07-01 02:18
> I think we should fork (LMMS/exprtk)

@JohannesLorenz  I agree with this - I'm always happy to provide PRs on changes in ExprTk to LMMS.

Apologies for any inconveniences that have arisen.

**Comment by tresf** [comment] 2019-07-01 02:41
Maintaining a fork is still a mess, just a controlled mess.  We'd have to keep an active branch for every sub-module commit in risk of history deletion and the inability of a fast-forward.

Also this only fixes the future, not the past.

The best way to address this is upstream.  Forking has it's purpose, this seems like a band-aid.  I'd almost rather destroy the sub-module and just use the tip of head through a cmake script at build time, assuming all risk that it offers.

This project needs less repositories IMO

**Comment by JohannesLorenz** [comment] 2019-07-03 06:45
There are other possibilities.
* @ArashPartow you could [block force pushes](https://help.github.com/en/enterprise/2.16/admin/developer-workflow/blocking-force-pushes-to-a-repository). Please first block a test branch, check if you can still push. If it works, block your master branch.
* LMMS should compile with only the core. Why fetching 10 submodules if you're on a PR that does not require one?

**Comment by tresf** [comment] 2019-07-03 13:58
> LMMS should compile with only the core. Why fetching 10 submodules if you're on a PR that does not require one?

There's nothing [restricting this now](https://github.com/LMMS/lmms/blob/28a522806bb1a670b460f0bfbf8d6147910dea72/plugins/CMakeLists.txt#L19).

**Comment by tresf** [comment] 2019-07-03 16:22
> There's nothing restricting this now.

I just remembered that master fetches submodules automatically so this is probably incorrect.  I'm not sure how best to solve this problem, but the easiest and grossest way is to simply bundle the source code in the project 🤢

**Comment by JohannesLorenz** [comment] 2019-07-03 18:12
> I just remembered that master fetches submodules automatically

You mean the [CheckSubmodules](https://github.com/LMMS/lmms/blob/master/cmake/modules/CheckSubmodules.cmake#L110) CMake module? If yes, couldn't that submodule read `LMMS_MINIMAL`?

**Comment by tresf** [comment] 2019-07-03 18:17
> couldn't that submodule read `LMMS_MINIMAL`

Yes.  It's still not 1:1 though.  Some submodules, such as rpmalloc is always required.

It does have support for `SET(SKIP_SUBMODULES "foo;bar")`. I suppose the reverse could be created,e.g. `SET(INCLUDE_SUBMODULES "rpmalloc;foo;bar")

**Comment by JohannesLorenz** [comment] 2019-07-04 20:56
FINALLY I found it out. The problem is not only that there were commits deleted, but also that the submodules were pointing to some dangling `tresf/exprtk` (which explains github wants credentials).

I fixed it like this:

```
# go to your worktree collection master, then
cd plugins/Xpressive/exprtk
git reset --hard 992835d50af709655c73f7e2d9238bc899640c75 # reset to his first commit ever
git remote set-url origin https://github.com/ArashPartow/exprtk # may have been "tresf/exprtk"
git pull --ff-only origin master
# now back to your damaged worktree...
# edit .gitmodules, exchange "tresf/exprtk" by "ArashPartow/exprtk"
git submodule deinit plugins/Xpressive/exprtk
git submodule update --init --recursive plugins/Xpressive/exprtk
```

**Comment by JohannesLorenz** [comment] 2019-07-13 11:16
@ArashPartow Are you going to block force pushes in your repository settings, like I described? I consider this a requirement for all LMMS submodules.

**Comment by tresf** [comment] 2019-07-13 15:09
@JohannesLorenz we can't control the submodules in which we depend.  We can choose to fork, but it's more maintenance on our project.  99% of the time, developers just need `master` to "work" out of the box, the historical stuff is mostly for diving into regressions and bug introductions, which we can proceduralized.

I'm not trying to minimize the need for `worktree` here, but I'm trying to stop demands against a repository that we can't control.  We're at the mercy of @ArashPartow here so as long as we depend on his library.  Furthermore, we can even make a project decision to abandon Xpressive as an official plugin and fork it to a sub-project using this thread as justification, but we can't easily rewrite history, and the setting which disables force-pushing can be toggled back off.  Let's not go making demands of projects in which we depend.

What's probably more important is that the plugins in which we depend (Xpressive is not a dependency of LMMS, but rather a dependency of an optional plugin in LMMS) don't force-push and there are only a few of those (`rpmalloc`, `qt5x11embed`, `weakjack` (arguably optional), `mingw-std-threads`) which have had a solid track record.

I just don't think it's fair to tell @ArashPartow how to run his repo (unless by some chance, he agrees).

**Comment by JohannesLorenz** [comment] 2019-07-29 20:39
> What's probably more important is that the plugins in which we ACTUALLY depend

The problem is that we depend on all, currently, more or less. IIRC there's that minimal build option, but as soon as you want to do a change in one, you have to update all, including one that is regularly force-pushed.

I'm against forks of all kinds. We could let the user selectively choose which submodules to update and which not, like `cmake -DMODULES=calf,caps` (MINIMAL should still be allowed, and taking all could be a sane default). Then, cmake should not attempt to pull any not specified (optional) submodules.

> I just don't think it's fair to tell @ArashPartow how to run his repo (unless by some chance, he agrees).

Agreed, but it's also not fair to force coders to mess around hours with git because of a problem which could easily be solved otherwise. Especially think of new coders who have even trouble with git's basics.

But even if we ignore this, the fact that you have to compile many files that you don't need is already enough reason for me to fix this in CMake and ignore force pushes in the submodules that way. Saves you bandwidth, laptop power, time... I'm for closing this and opening a feature request "Enable selecting submodule choosing in CMake".

**Comment by tresf** [comment] 2019-07-30 14:43
> But even if we ignore this, the fact that you have to compile many files that you don't need is already enough reason for me to fix this in CMake and ignore force pushes in the submodules that way.

The way to avoid compilation is to pre-compile.  We could switch to `linuxbrew` I've started (and abandoned) `scoop` and of course `homebrew`.

Perhaps we just make the cmake submodules script smart enough to handle this problem.  Unfortunately, it would never make it back in time, but it could patch this with a warning and a fallback checkout.  I understand that this won't help people using worktrees.

**Comment by JohannesLorenz** [comment] 2019-07-30 23:38
I'm against precompiling our own stuff. Anyways, for all the LADSPA stuff + zyn, users can probably use the precompiled Lv2 libraries on their system, so this will solve it for those. But for expressive, I think we really need a CMake solution.

I'll close this soon, we now have #5105 for CMake.

**Comment by ArashPartow** [comment] 2019-08-04 21:41
@tresf and @JohannesLorenz: 

Apologies for the late reply.

In regards to the issue above - I'm happy to add a release tag (in semvar format) to the ExprTk repository which you can use to do a clone/checkout on within the build process. 

I'm thinking that should result in a much more deterministic and robust process than checking out the tip of some arbitrary master.

Do let me know if you're interested in this solution.

**Comment by tresf** [comment] 2019-08-05 15:54
@ArashPartow yes, that would be great.

@JohannesLorenz can you provide @ArashPartow with the missing commit hash(es)?  Also, if there are any commits pointing to my copy that need the same effort, please let me know (or I'd happily grant anyone access to my copy)

**Comment by ArashPartow** [comment] 2019-08-05 22:17
@tresf:  I'll do that and update this thread. But please do note the tag will be on the tip of the current master . The previous hashes in question are no longer there. 

Going forward the LMMS build system should from now on checkout the specific tag it is interested in and not any specific hash.

**Comment by tresf** [comment] 2019-08-06 12:58
> The previous hashes in question are no longer there.

I'm sorry I was under the impression you were willing to (1) reconstruct the historical commits (e.g. from an undamaged fork), (2) commit them to a branch and then (3) create a release off of that branch.

Maintaining tags will certainly help as it discourages this from happening in the future, but it won't fix the historical worktree problems.

> the LMMS build system should from now on checkout the specific tag it is interested in and not any specific hash.

I believe git only stores the commit hash, regardless of how it's checked out.  I could be wrong but here's what git shows when I checkout a tag for our `adplug` submodule:

```
Previous HEAD position was 3ed6617 Fix `-Waggressive-loop-optimizations`
HEAD is now at efe452d Prepare 2.3.1 release
```

... and the diff:

```diff
diff --git a/plugins/OpulenZ/adplug b/plugins/OpulenZ/adplug
index 3ed6617ec..efe452df4 160000
--- a/plugins/OpulenZ/adplug
+++ b/plugins/OpulenZ/adplug
@@ -1 +1 @@
-Subproject commit 3ed6617ec00022dfab574c27710d9071a6032c87
+Subproject commit efe452df461d51dc741fbe063b8bf357dc7d0f10
```

**Comment by JohannesLorenz** [comment] 2019-08-06 13:39
> I believe git only stores the commit hash, regardless of how it's checked out.

I was under that impression, too. That's also why submodules are not on any branch (but the HEAD is marked `detached`) when you have checked them out, even if the one who pushed the main repo specified a branch.

I also agree that this might help in the future, but it won't prevent force pushes that override tags.

@ArashPartow We normally use this workflow: Develop on your side branch, and once you have something stable enough merge it to master. This allows you to make as many commits/rebases/force-pushes on you branch as needed, but not on master (what ever happened on master will be frozen). I think this will be a lot less work for you than adding tags, pushing tags, let us somehow check which tags we need to use etc. Why don't you want to try this workflow?

**Comment by tresf** [comment] 2019-08-06 15:22
> Why don't you want to try this workflow?

Preventing force-pushing is for multi-user projects.  If he's the sole maintainer of the project, you're just asking him to put a rule to prevent him from force-pushing, which is the same as him just promising not to force-push.

Force-pushing is fine in many circumstances, but when an important commit gets wiped out or the commits were written to 3rd party projects, that's when it causes problems.

If it fixes the history by making branches, I'd love to help with this effort.  I'm sure @ArashPartow would prefer to NOT keep around historical branches.  What I'm curious about is if it'll help, especially the releases part.  @JohannesLorenz I vaguely remember this issue cropping up even when the commit was on another branch.  I would like to know if placing a commit into the releases area remedies this.

**Comment by ArashPartow** [comment] 2019-08-06 21:23
@tresf and @JohannesLorenz:  

How about this approach: - I create a repo called exprtk_lmms, which will only include a single file (exprtk.hpp) initially based off  what is in the actual repo as of when it's created and then never force push on that.

LMMS can then use that repository - would that be simpler/viable option?

**Comment by JohannesLorenz** [comment] 2019-08-07 16:24
I don't know why you propose so complicated things while disabling force-pushes is so easy and common, and when I ask I don't get an answer @ArashPartow 

Anyways... As long as we keep exprtk an LMMS submodule, I'm OK with **any** solution, since I'll just not init that submodule per #5105 . I'm OK with closing the issue or keeping it open. I unsubscribe from this issue, please don't tag me here unless really required.

**Comment by tresf** [comment] 2019-08-07 16:31
> disabling force-pushes is so easy and common

It's a toggle switch, it's for safety (NOT for integrity) and it's easy to turn off.  It doesn't fix history.  It doesn't fix moving forward.

> why you propose so complicated things while 

Who's?  I've honored his request to keep tags.  If I can shove back into a branch commits that we need, it could fix this, right?  There are two tasks:

1. Fix the past
2. Prevent this from happening in the future

Since @ArashPartow has already promised to help prevent this in the future, beating up the "disable force" option seems pointless.

**Comment by tresf** [comment] 2019-08-07 16:46
https://github.com/ArashPartow/exprtk/commits/f32d2b4 ✅exists
https://github.com/ArashPartow/exprtk/commits/aad301a ✅exists
https://github.com/ArashPartow/exprtk/commits/21bb5ec ✅exists

https://github.com/tresf/exprtk/commits/f32d2b4 🚫was missing

@JohannesLorenz is there a chance the only issue is my fork?  I probably cleaned it up on accident.  I've recreated it.  I'm still going through the commit history to see if there are any others missing.

**Closed** 2020-01-11 17:21 UTC
