### ISSUE TITLE
mouse-over readout in fx-mixer

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2172] opened 2015-07-08 10:16 UTC
It can be a little difficult to read the vertical labels in fx-mixer.
Perhaps a mouse-over-readout, like in this mockup
![mouseover](https://cloud.githubusercontent.com/assets/6662066/8568099/119d2500-256b-11e5-90e6-97ab16b876d5.PNG)
could be a nice feature

**Comment by michaelgregorius** [comment] 2015-07-11 16:24
In my opinion using some mouse over pop ups / tool tips does not really solve the problem. I think the cause of the problem is that the labels are vertical in the first place and that some other newer features, e.g. the send mechanism, seem to have been implemented without the labels in mind. This becomes rather obvious in the image above where the labels are partly covered by the channel display and mixed with the send arrows.

I think it would really help if the mixer would enable the user to make use of the increased space that's available on many modern systems. For example it should be possible to change the size of the mixer and the channels in both directions. Additional vertical space could for example be used by the meters.

I have a branch where I played a bit with the mixer and here are some of the results:
![lmms - new mixer crop](https://cloud.githubusercontent.com/assets/9293269/8634342/9a97c3e2-27f5-11e5-881e-7155498e33c8.png)

With solo enabled:
![lmms - new mixer solo crop](https://cloud.githubusercontent.com/assets/9293269/8634347/acb157d2-27f5-11e5-8fe0-a4b7b36a3160.png)

I guess most of the changes are rather obvious but for completeness here is a list of them:
* Channels are wider.
* The meters are rendered in code (using simple rectangles with gradient brushes) instead of relying on pixmaps of static size. You've got a 4K display and want to have it completely covered by the meter? No problem. :blush:
* Labels are now shown horizontally at the bottom. If the text is too long it is elided but the tool tip will still show the full name. If it was possible to expand the channels horizontally the label could make use of that space to display more of the content. 
* I have replaced the pixmaps that are used for solo and mute. In my opinion it's now much more obvious which button does what. I think they still need improvement, e.g. to make a better distinction of whether a button is enabled or not.
* I have gotten rid of the (in my opinion) ugly LCDs to display the channel numbers.

The widgets to configure the sends have been commented out in the current version of the code in my branch. So what's currently missing is a concept for the sends. I have to admit that I don't understand the current concept and that it also does not seem obvious to me. This might either be an indicator that it needs to be improved or that I am stupid. :wink: Can someone please explain it to me?

P.S.: Sorry for hijacking this thread. :wink:

**Comment by grejppi** [comment] 2015-07-11 17:13
@michaelgregorius: Mind opening a new issue for your redesign? It looks like something that could be developed further.

**Comment by Umcaruje** [comment] 2015-07-11 17:38
I agree with @grejppi. Your redesign looks really promising.

**Comment by Wallacoloo** [comment] 2015-07-11 21:16
I absolutely agree with the vertical text decision. Seriously - vertical text is such an anti-pattern that its use here is nearly useless. **I don't actually identify channels based on the label text**, because trying to read a dozen+ tilted lines of text is frustrating. Instead, I end up identifying channels more by their meter readout as the song is playing and some amount of memorization.

Widening the mixer slots does indeed seem like the best solution. At least making them resizable is progress - It opens up possibilities for future in which we can experiment with different sizing patterns that compromise readability for screen space.

One thing I'd be interested in trying, since you're still pretty tight on horizontal space even in your new version, is making the label text occupy two lines and then applying some word-wrap algorithm.

**As far as how sends currently work**: click on a channel. All other channels will now either have an arrow pointing up, a SEND button which is unlit, or a lit SEND button with an arrow pointing down and a volume knob.

For any non-selected channel: If the arrow is pointing up, it means that channel is sending its output to the currently selected channel. If the SEND button is lit and the arrow is pointing down, then that means the currently selected channel is sending its output to that other channel.

As far as implementing sends in your mixer, my recommendation would be to omit the SEND button, since it's somewhat redundant. Instead, perhaps have gray arrows pointing down on all the channels for which it's possible to send the output (you can't have two channels both send to eachother), and make clicking on that arrow turn it green and enable sending. Mouse-over on the arrow would display something like "send is [enabled/disabled]". Just one possible idea.

Great work with the redesign though. I'd definitely like to see some or all of it make its way into master eventually. When you're ready for more discussion, I'd say skip creating an issue for it and just create a PR clearly marked as "in-progress", since you already have a fairly complete implementation.

**Comment by michaelgregorius** [comment] 2015-07-11 22:28
Hi all,

I don't want to create a PR yet as the sends are not working in my branch. However, I have just pushed the branch to GitHub. So if you want to play with it or finish the implementation of the sends feel free to clone it. :smiley: You can find it here:
https://github.com/michaelgregorius/lmms/tree/fx-mixer-redesign

Please note that there are still some rough edges in the code, e.g. some parts are just commented out instead of being deleted, because it started just as a quick experiment.

I will be on vacation for the next two weeks and will likely also be quite busy in the week following the vacation. See you in a few weeks then!

**Comment by musikBear** [comment] 2015-07-12 12:25
> P.S.: Sorry for hijacking this thread. 

Not a hijack imo, more like a deepened view on the same issue, and it looks very good

But i still think that a here-and-now solution could be mouse-over, because implementing a brand new fx-mixer, could be rather huge (or?)

**Comment by michaelgregorius** [comment] 2015-07-12 15:16
Quick fix implemented in #2181.

**Comment by Umcaruje** [comment] 2015-07-19 22:54
Closed via #2181

**Closed by Umcaruje** 2015-07-19 22:54 UTC
Labels: enhancement, gui
