### ISSUE TITLE
Music editor isn't redrawn properly when maximized on 16:9 monitor

### ISSUE THREAD

**Issue by MrMadguy64** [LMMS/lmms#4591] opened 2018-09-12 12:08 UTC
LMMS 1.1.3 64bit
Windows 7 64bit professional.

Same version works properly on 4:3 monitor (same video card) and on Linux (Mint 19, LMDE 3).
Changing scale helps to solve this problem.

Initial state:
![original](https://i1.imageban.ru/out/2018/09/12/001490de6ee68549b0ca710b3f4c1407.png)
What I see:
![actual](https://i2.imageban.ru/out/2018/09/12/387b4aea6bd886c5263ebc5bddec9393.png)
What I should see:
![expected](https://i6.imageban.ru/out/2018/09/12/e3ed1ba705a8c1dfc83f6c95e96022b1.png)

**Edit** @PhysSong: Fixed image link using GitHub

**Comment by PhysSong** [comment] 2018-09-12 12:09
I believe this is a duplicate of #70.

**Comment by PhysSong** [comment] 2018-09-13 10:47
Please feel free to request reopening this issue if this is not a duplicate of #70!

**Closed by PhysSong** 2018-09-13 10:47 UTC
Labels: duplicate
