### ISSUE TITLE
am synth support

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1881] opened 2015-03-17 17:19 UTC
This is a question is the am synth going to be built into LMMS like ZynAddSubFX is?

am synth
http://code.google.com/p/amsynth/
![amsynth_151_fedora 1](https://cloud.githubusercontent.com/assets/8137561/6693280/c687e7b8-cc9f-11e4-97cb-60d8a161012b.png)

**Comment by Sti2nd** [comment] 2015-03-17 18:35
no

**Comment by tresf** [comment] 2015-03-17 18:49
Once we get LV2 support, possibly.  It is open source and released under a compatible license so it is a good candidate.

**Comment by tresf** [comment] 2015-03-17 18:51
Duplicate of #562.  Please feel free to reopen this topic once LV2 support has been added.

**Closed** 2015-03-17 18:51 UTC
Labels: duplicate
