### ISSUE TITLE
1.2.0 RC5 AppImage crashing on startup

### ISSUE THREAD

**Issue by Calendis** [LMMS/lmms#4118] opened 2018-01-16 22:31 UTC
Whenever I open the AppImage obtained from the website, it loads the splash screen and crashes, never displaying the main LMMS UI. I ran from a terminal, and it gave this output. I shouldn't be missing any dependencies, because AppImages don't have dependencies, right?

`Carla does not appear to be installed.  That's OK, please ignore any related library errors.
/tmp/.mount_lmms-1hqlQgJ/AppRun: line 17: ldconfig: command not found
Jack does not appear to be installed.  That's OK, we'll use a dummy version instead.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-plantain'
Notice: could not set realtime priority.
VST sync support disabled in your configuration
Cannot load library /tmp/.mount_lmms-1hqlQgJ/usr/lib/lmms/libcarlarack.so: (libcarla_standalone2.so: cannot open shared object file: No such file or directory)
Cannot load library /tmp/.mount_lmms-1hqlQgJ/usr/lib/lmms/libcarlapatchbay.so: (libcarla_standalone2.so: cannot open shared object file: No such file or directory)
Cannot load library /tmp/.mount_lmms-1hqlQgJ/usr/lib/lmms/libcarlabase.so: (libcarla_standalone2.so: cannot open shared object file: No such file or directory)
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied
cannot open sequencer: Permission denied
cannot open MIDI-device: No such file or directory
Couldn't create MIDI-client, neither with ALSA nor with OSS. Will use dummy-MIDI-client.
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM dmix
/tmp/.mount_lmms-1hqlQgJ/usr/bin/lmms.real: symbol lookup error: /tmp/.mount_lmms-1hqlQgJ/usr/lib/libportaudio.so.2: undefined symbol: jack_client_open
`

**Comment by Calendis** [comment] 2018-01-16 22:33
open /dev/snd/seq failed: Permission denied cannot open stands out to me, but I am not the developer so I am only guessing. I am running on a Chromebook Acer 11 in a Ubuntu Zesty chroot. Installing LMMS from the repositories or the KXStudio repositories works fine

**Comment by tresf** [comment] 2018-01-16 22:38
Can you please confirm this is a duplicate of  https://github.com/LMMS/lmms/issues/4094#issuecomment-356172525

**Comment by Calendis** [comment] 2018-01-16 22:48
Ah, my bad. I hadn't used GitHub in so long I forgot to go through the ettiquette of searching for my bug first! :s 
I am quite sure this is a duplicate.

**Comment by lukas-w** [comment] 2018-01-17 06:32
Closing

**Closed by lukas-w** 2018-01-17 06:32 UTC
