### ISSUE TITLE
Time signature resets when playing.

### ISSUE THREAD

**Issue by dhulipala** [LMMS/lmms#3787] opened 2017-09-01 17:03 UTC
The time signature denominator keeps resetting to 4 when I hit the play button or when new tracks are added. Attached zip contains a screen-recording and the version of LMMS I am using. Is this a bug, or am I doing something wrong? Please review.

[time_sig_reset.zip](https://github.com/LMMS/lmms/files/1270963/time_sig_reset.zip)

![image](https://user-images.githubusercontent.com/26237353/29980016-697556ae-8f0d-11e7-9709-838cdad8853f.png)

**Comment by PhysSong** [comment] 2017-09-02 02:52
Can you try
1. Right click the dominator LCD.
2. Click something like "Remove global automation".
?

**Comment by Sawuare** [comment] 2017-09-09 13:11
@PhysSong Your suggestion would work if the problem is only when playing the song, but @dhulipala says it happens when adding tracks too, which is odd. 🤔 

@dhulipala Are you sure this happens when adding tracks? If you are,  what track types does it happen with?
I couldn't play the file you attached.
Can you zip the project file with this behavior and attach it to your first comment? It will help with testing.

**Comment by dhulipala** [comment] 2017-09-10 02:25
I have attached the project file. 

I think I understand what the issue is now. This is an issue with MIDI tracks only. 

Here is what happens:
1. Import midi track - midi has time sig of 10/4.
2. Change time sig in LMMS to 10/16.
3. Hit play - the time sig resets to whatever is in midi.

I guess this is expected behavior - and I should have my midi at the same signature as in LMMS.

[padava-01.zip](https://github.com/LMMS/lmms/files/1290202/padava-01.zip)

**Comment by PhysSong** [comment] 2017-09-10 04:10
Reproduced when playing, but can't reproduce when adding tracks. If you want to change the time signature or the tempo, you can remove song-global automations and try again.

Can you try with LMMS 1.2.0-rc3 and post the result, what happens if you add tracks with LMMS 1.2?

**Comment by musikBear** [comment] 2017-09-10 13:43
.. but added tracks would be influenced just as the ones that are in the midi. If you change the BPM it will also reset. That is the nature of MIDI-files
*Remove-global-automation* **is** the solution

**Comment by Spekular** [comment] 2017-09-11 16:07
I don't think it's intuitive for an imported midi file to lock the tempo
with no indication though. Global automations certainly ought to be visible
and I'd argue that perhaps importing BPM from MIDI should be optional.

**Comment by musikBear** [comment] 2017-09-12 13:44
>  Global automations certainly ought to be visible

I remember we have agreed on *removing* global-automation completely. Its a bad feature, and should be killed. The discussion has already been done once..

**Comment by DouglasDGI** [comment] 2019-03-09 18:36
I'll go ahead and close this one, let me know if it shouldn't be.  A solution for the problem has been found (remove song-global automation), the time signature reset on track addition hasn't been reproduced, there hasn't been a response in 18 months, and further discussion of dealing with song-global automation would probably go in its own thread.

**Closed by DouglasDGI** 2019-03-09 18:36 UTC
Labels: enhancement, ux
