### ISSUE TITLE
Import midi files create holes in tune flow, uncomfortable for scaling later.

### ISSUE THREAD

**Issue by healingdrawing** [LMMS/lmms#5396] opened 2020-02-18 02:11 UTC
[normal10midi.zip](https://github.com/LMMS/lmms/files/4217010/normal10midi.zip)

### Bug Summary
After importing midi files the song editor notes not solid, which is wrong behavior, because 99% of midi files after import need to be remastered(scaled + quantized).  
And in result user at least need to manually copy past correctly notes to first pattern from all other patterns and delete original parts created by import function, before can scaling tune, that it looks correct inside piano roll.
#### Steps to reproduce
Just import any midi files with silence inside flow of some instruments, enough long that cover at least one song editor pattern.  
#### Expected behavior
solid tune patterns, one track one pattern. At least because LMMS have no tools for join(with fill empty pattern) / split(along song editor pattern steps) functionality.  
#### Actual behavior
Some imported tracks not solid.
#### Screenshot
![Screenshot_20200218_043153](https://user-images.githubusercontent.com/39751647/74697511-f06cc700-520b-11ea-8175-466fb792e28f.png)

#### LMMS version used
Version 1.2.1 (Linux/x86_64, Qt 5.9.7, GCC 4.8.4)  [.AppImage]
#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by musikBear** [comment] 2020-02-18 16:14
ye, just as i told you on discord, this will be fixed if a 'glue'-feature is implemented. It is suggested, so one day.. :p 
> After importing midi files the song editor notes not solid

I dont really agree that you should expect one continuous block/ segment with all notes. We do not have that in LMMS either, anly if/ when we record notes during transport, then pauses in the flow of notes are seen as long empty sections in the block, but if you insert notes, dont you do that in many small blocks with breaks in between?
![image](https://user-images.githubusercontent.com/6662066/74754595-23e23c80-5272-11ea-95a5-e27de10ab820.png)

**Comment by healingdrawing** [comment] 2020-02-19 20:06
New cloning functionality sounds enough good.  
It can be named for example "clone solid for scaling" etc.

**Comment by Spekular** [comment] 2020-02-22 12:06
Closing as duplicate of #3633 since OP confirmed that a merge functionality would satisfy them.

**Closed** 2020-02-22 12:07 UTC
Labels: bug
