### ISSUE TITLE
Notes sticking when playing in song editor

### ISSUE THREAD

**Issue by xuvatilavv** [LMMS/lmms#3122] opened 2016-11-14 13:16 UTC
Version: 1.1.3

The final note played in my countermelody track sticks playing both when the block of notes ends and when playback is paused or stopped any time after the first block has finished. I'm not sure but it seems like the note that sticks is sometimes the last note played and sometimes the next note to be played after the pause/stop point.

This occurs both when playing  from the beginning of the track whether it's right after loading the file or after moving things around first. Occasionally moving things beforehand will prevent the behavior, although inconsistently.

The same notes and layout seemed to have worked normally earlier today without any changes in the software.

If I open the project and delete everything except one block of the countermelody, the behavior shows, but if I then save and load the project and try again it does not.

I was able to reproduce this in a clean project using the same notes, but not with a simpler rhythm so I've attached the project file.

[bug.zip](https://github.com/LMMS/lmms/files/589273/bug.zip)

**Comment by tresf** [comment] 2016-11-14 13:35
When you say "worked previously", I assume this stament is in regards to `1.1.3` whereas you are testing `1.2.0-RC1` or latest master?  Please edit your post to reflect that.

Can the bug be reproduced without your project file?  If so, please give numbered steps to reproduce.  If not, your attachment is sufficient.

**Comment by DeRobyJ** [comment] 2016-11-14 14:40
I see you're using VST.
Can you reproduce the bug using a built-in instrument plugin?
The problem might be VST-related

**Comment by xuvatilavv** [comment] 2016-11-14 14:52
I'm working on testing it more right now, will update the main post when I've got it more narrowed down.

For now:
Version 1.1.3, I haven't updated.

I haven't been able to reproduce with other rhythms. I have been able to reproduce it using the same rhythms in a new project. The problem seems to only happen if I don't open or close the piano roll after loading the project.

I'm using the Synth1 VST, it's happening with some patches in its default sound bank, but not others. I'm currently testing to see if it shows up with non-VST instruments.

**Comment by BaraMGB** [comment] 2017-01-09 22:14
>I installed the beta version from https://lmms.io/ (listed on the site as 1.2.0-RC1 and in-software as 1.1.9) and, using the same project files, the issue doesn't seem to be there.

I close this as solved. If the issue is appearing again feel free to reopen.

**Closed by BaraMGB** 2017-01-09 22:14 UTC
