### ISSUE TITLE
Add linked copies for patterns in song-editor

### ISSUE THREAD

**Issue by GsLogiMaker** [LMMS/lmms#7115] opened 2024-02-19 04:32 UTC
### Enhancement Summary
LMMS needs the option to create linked copies of patterns in the song-editor. When one instance of a pattern is edited, all linked instances would experience the same changes.

#### Justification
Creating songs with repeating segments that are supposed to be the same is a nightmare in LMMS. Making one change across all instances of a pattern involves making the change in one, then finding and deleting all other instances, replacing them with the new version. This is especially tedious and difficult in longer, more complicated songs.

#### Mockup
A new `Linked copy` option would need to be added to the context menu of the patterns (Please excuse the crudeness of the example):
![Screenshot from 2024-02-18 22-00-29](https://github.com/LMMS/lmms/assets/87501052/6f6c58c8-b9af-49e9-a18b-566a59790e67)

Patterns already have a fast copy mechanic, where the user can hold ctrl and drag a pattern to make a copy. Another shortcut like this could be made for linked copies, with the user holding ctrl+shift and drag to make a linked copy.

Optionally, it might be useful to have a visual indicator for patterns that are linked.
![Screenshot from 2024-02-18 22-04-49](https://github.com/LMMS/lmms/assets/87501052/3b1dc575-f743-492a-816f-6ecb119a3bfa)

**Comment by Spekular** [comment] 2024-02-19 04:40
Duplicate of #3100.

**Closed by Spekular** 2024-02-19 04:40 UTC
Labels: enhancement

**Comment by qnebra** [comment] 2024-02-19 15:07
Also "Pattern Editor" is already a thing. There is no point in duplicating already existing functionalities.
