### ISSUE TITLE
Hug playback lag

### ISSUE THREAD

**Issue by djnotes** [LMMS/lmms#6488] opened 2022-08-17 12:13 UTC
### Bug Summary
This version (LMMS 1.3.0-alpha.1.218+g9faa1d90c) has huge lag on Linux. It takes about 3-4 seconds for the pressed key to sound, or for the highlighted MIDI note in Piano roll to sound.

#### Steps to reproduce
Go to Piano Roll and play some notes from keyboard. You can also play anything in the song editor. The indicator is not in sync with the sound that you hear.

#### Expected behavior
Realtime playback of the pressed keys or indicated notes.

#### Actual behavior
The sound of the playback always lags behind the actuall notehead by 3-4 seconds.

#### Screenshot
![image](https://user-images.githubusercontent.com/9320387/185114198-88f7df99-4e0a-4227-8dc5-cf98011cb2cf.png)

#### Affected LMMS versions

LMMS 1.3.0-alpha.1.218+g9faa1d90c
The previous one (build) had this issue too.

#### System Info
Fedora 36

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
Don't know where to find these!
</pre>
</details>

**Comment by RiedleroD** [comment] 2022-08-18 16:03
I can only guess, but try selecting a different audio backend (the setting applies after closing LMMS)

**Comment by djnotes** [comment] 2022-08-19 12:58
I switched the audio backend to ALSA and device to default. Now it works without those lags. Thank you. So, is this a bug or the natural expected behavior of PulseAudio (previous settings)?

**Comment by RiedleroD** [comment] 2022-08-21 17:31
pulseaudio is very buggy in general, I don't recommend it. It's definitely not intended behavior, even though pa is known for introducing relatively large delays to the audio pipeline.

**Closed** 2023-01-06 13:17 UTC
Labels: not our bug
