### ISSUE TITLE
Don't ever overwrite or delete recover files

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2174] opened 2015-07-09 11:50 UTC
I just lost some serious progress because I closed LMMS after recovering from a crash and forgot to save the project. LMMS deleted the recover.mmpz file and my progress is lost forver. It'd be great if it didn't do that, and name the recover files with Process ID and date like this:

recover_PID7632_2015-07-09-1348.mmpz

It'd make all recover files be there if needed. They are not very big, could be automatically removed after a month or something. That'd greatly increase the crash recovery probability and make it resistant to running multiple LMMS instances that overwrite recorver.mmpz causing data loss.

**Comment by zonkmachine** [comment] 2015-07-09 17:01
Ouch! Sorry about your data loss. Been there...

The line removing the recovery file is here:
https://github.com/LMMS/lmms/blob/master/src/gui/MainWindow.cpp#L1259

How does other programs do it?
I can recall seeing recovery files popping up in other programs and they would make some "noise" like adding a red border saying recovery file. I think a good way to deal with this would be to just add the usual question on closing. If I modify a new project and press 'close' I get "The current project was modified since last saving. Do you want to save it now?"
Maybe something like: "You are about to close a recovered file but it is currently in an unsaved state and will be lost if you don't save it. Do you want to save it now?"

**Comment by unfa** [comment] 2015-07-09 17:12
Thanks, I managed to redo it more or less. Anyway, I'd like to expand the autosave funcionality a bit.

**Comment by zonkmachine** [comment] 2015-07-09 18:02
OK. I'm going to look into how recover files are handled.

**Comment by zonkmachine** [comment] 2015-07-09 18:53
Which version of LMMS are you using?

**Comment by zonkmachine** [comment] 2015-07-09 19:18
In master, if I put a "recover.mmp" in the top of my ~/LMMS directory, I can not make LMMS delete it without first asking me to save it. If I just open and then close it, the manly way with Ctrl + C from the command line, it will not delete the file but remind me the next time.

In 1.0.0 however I can see the behaviour of Issue #722, which has already been fixed, but nothing else.
Do you have a method to reproduce the behaviour you saw?

**Comment by zonkmachine** [comment] 2015-07-09 21:10
I'm going to hack this a bit to give us a question box on closing a recovery file.

**Comment by musikBear** [comment] 2015-07-10 11:05
so sad @unfa - if you had seen what i suggested the other day
 #181
you would have liked it
I reference to this because i think it has very strong relation to this thread, and the handling of recover in a whole

**Comment by tresf** [comment] 2016-01-19 13:37
Closed via #2176

**Closed by tresf** 2016-01-19 13:37 UTC
Labels: enhancement, ux
