### ISSUE TITLE
LMMS crashes when opening automation track

### ISSUE THREAD

**Issue by jypiou** [LMMS/lmms#1901] opened 2015-03-24 14:58 UTC
Hi all,
I've recently created an automation track and each time I wan to edit it, LMMS crashes and the log is the following on the console :
`QtXmlWrapper::loadXMLfile(): empty data 
ASSERT: "it == time_map.end()-1" in file /build/buildd/lmms-1.0.0+stable/src/gui/AutomationEditor.cpp, line 1600
Abandon (core dumped)`

I'm running Ubuntu 14.04 and LMMS 1.0.0.

Thanks
jy

**Comment by tresf** [comment] 2015-03-24 20:43
We no longer officially support the `stable-1.0` branch.  Can you confirm this also occurs on `1.1.3`?

**Comment by softrabbit** [comment] 2015-03-26 08:46
Looks like it's fixed since 1.0.1, a year ago. https://github.com/LMMS/lmms/issues/721#issuecomment-43181241

**Comment by jypiou** [comment] 2015-03-26 08:48
Yes, you're right, it is fixed.
This will probably regularly come up as 1.0.0 is in the stable repositories of ubuntu.

Thanks !
jy

**Comment by tresf** [comment] 2015-03-26 12:34
> This will probably regularly come up as 1.0.0 is in the stable repositories of ubuntu.

Yeah, we have some area for improvement there per #1620.

Closing as duplicate of #721.

**Closed by tresf** 2015-03-26 12:34 UTC
Labels: duplicate
