### ISSUE TITLE
Piano roll crashes when window is scaled too large

### ISSUE THREAD

**Issue by haicat** [LMMS/lmms#4098] opened 2018-01-08 09:22 UTC
Tested on 1.2.0-rc5

LMMS will crash when the piano roll window is scaled too large. I found that it seems to be when it's scaled to around 1600-ish pixels in height.

**Comment by musikBear** [comment] 2018-01-08 17:03
is this related to HD monitors (4K etc)?

**Comment by tresf** [comment] 2018-01-08 17:12
@musikBear it's related to the pixel-width of the monitor, which would be perpetuated by a higher-resolution monitor, yes.

**Comment by tresf** [comment] 2018-01-09 01:18
I can't reproduce the crash on Linux, but I have a feeling it's related to the fact that we don't stop drawing the piano keys after we've left the playable area.

![screen shot 2018-01-08 at 8 17 22 pm](https://user-images.githubusercontent.com/6345473/34700407-fcc51c10-f4b0-11e7-8c7a-3ff6d2b6efce.png)

**Comment by PhysSong** [comment] 2018-01-15 06:02
Though I don't have large enough monitor to reproduce this issue, I was able to find possible cause for this issue.
https://github.com/LMMS/lmms/blob/46512fdf19f42150d2728feb439b1c8441ce93dd/src/gui/editors/PianoRoll.cpp#L3165-L3175

`m_startKey` becomes negative if piano-roll is too large and it may break some modular logics
([example](https://github.com/LMMS/lmms/blob/46512fdf19f42150d2728feb439b1c8441ce93dd/src/gui/editors/PianoRoll.cpp#L2615)). If this is the reason, I have three solutions/workarounds:
1. Limit the height of piano roll editor. This can be a simplest solution and prevent piano roll editor from strange visualization.
2. Fix problematic modular logics. It won't be difficult, but will make code a little be messy.
3. Bound the value of `m_startKey` to be always positive. It is simple, too.

**Comment by PhysSong** [comment] 2019-06-22 03:31
I will implement the first solution if no one is on it.

**Comment by JohannesLorenz** [comment] 2019-07-21 23:47
Solution (3) means adding a block similar to the `if( m_startKey > m_totalKeysToScroll )` one? I think that's better than (1), since it has the same effect, but does not restrict the size. Per (2), I'm not sure what you mean, but as it's a `stable-1.2 fix`, I'd avoid a "messy" solution. :smile:

**Comment by PhysSong** [comment] 2019-07-26 01:31
I implemented the first fix, then realized it looks somewhat unintuitive. I'll try (3) and compare with (1).

**Comment by PhysSong** [comment] 2019-07-26 14:07
What I mean by (1) is restricting the size of the note area, not the whole editor. BTW, no one is clear as much as I expected. Each way changes 10~20 lines and (3) was a bit more minimal.
I'll upload diffs that I used tomorrow.

**Comment by JohannesLorenz** [comment] 2019-07-26 15:38
Yeah, feel free to upload both patches/branches. It's probably easiest to compare the user experience when testing them live.

**Comment by PhysSong** [comment] 2019-07-27 03:56
https://gist.github.com/PhysSong/3f02b3fa36474850e002974e7893c09b

**Comment by PhysSong** [comment] 2020-04-21 06:52
Another attempt:
```diff
diff --git a/src/gui/editors/PianoRoll.cpp b/src/gui/editors/PianoRoll.cpp
index 924463995..4cfc63506 100644
--- a/src/gui/editors/PianoRoll.cpp
+++ b/src/gui/editors/PianoRoll.cpp
@@ -890,7 +890,7 @@ void PianoRoll::drawDetuningInfo( QPainter & _p, const Note * _n, int _x,
 	_p.setPen( noteColor() );
 	_p.setClipRect(WHITE_KEY_WIDTH, PR_TOP_MARGIN,
 		width() - WHITE_KEY_WIDTH,
-		keyAreaBottom() - PR_TOP_MARGIN);
+		keyAreaBottom() - keyAreaTop());
 
 	int old_x = 0;
 	int old_y = 0;
@@ -1310,8 +1310,7 @@ void PianoRoll::leaveEvent(QEvent * e )
 
 int PianoRoll::noteEditTop() const
 {
-	return height() - PR_BOTTOM_MARGIN -
-		m_notesEditHeight + NOTE_EDIT_RESIZE_BAR;
+	return keyAreaBottom() + NOTE_EDIT_RESIZE_BAR;
 }
 
 
@@ -1351,7 +1350,7 @@ int PianoRoll::keyAreaTop() const
 
 int PianoRoll::keyAreaBottom() const
 {
-	return height() - PR_BOTTOM_MARGIN - m_notesEditHeight;
+	return qMin(height() - PR_BOTTOM_MARGIN - m_notesEditHeight, KEY_LINE_HEIGHT * NumKeys);
 }
 
 
@@ -2391,9 +2390,7 @@ void PianoRoll::mouseMoveEvent( QMouseEvent * me )
 
 
 			int key_num = getKey( me->y() );
-			int visible_keys = ( height() - PR_TOP_MARGIN -
-						PR_BOTTOM_MARGIN -
-						m_notesEditHeight ) /
+			int visible_keys = ( keyAreaBottom() - keyAreaTop() ) /
 							KEY_LINE_HEIGHT + 2;
 			const int s_key = m_startKey - 1;
 
@@ -3111,8 +3108,7 @@ void PianoRoll::paintEvent(QPaintEvent * pe )
 	}
 
 	p.setClipRect( WHITE_KEY_WIDTH, PR_TOP_MARGIN, width() -
-				WHITE_KEY_WIDTH, height() - PR_TOP_MARGIN -
-					m_notesEditHeight - PR_BOTTOM_MARGIN );
+				WHITE_KEY_WIDTH, keyAreaBottom() - keyAreaTop() );
 
 	// now draw selection-frame
 	int x = ( ( sel_pos_start - m_currentPosition ) * m_ppt ) /
@@ -3200,9 +3196,7 @@ void PianoRoll::resizeEvent(QResizeEvent * re)
 						height() - PR_TOP_MARGIN -
 						SCROLLBAR_SIZE );
 
-	int total_pixels = OCTAVE_HEIGHT * NumOctaves - ( height() -
-					PR_TOP_MARGIN - PR_BOTTOM_MARGIN -
-							m_notesEditHeight );
+	int total_pixels = OCTAVE_HEIGHT * NumOctaves - ( keyAreaBottom() - keyAreaTop() );
 	m_totalKeysToScroll = total_pixels * KeysPerOctave / OCTAVE_HEIGHT;
 
 	m_topBottomScroll->setRange( 0, m_totalKeysToScroll );
```

**Comment by Spekular** [comment] 2020-04-23 21:26
Can confirm that this diff caps the note area correctly (letting the note *edit* area grow). The line numbers didn't match up for me but I manually merged the diff here: https://github.com/Spekular/lmms/tree/SongEditorCrash

Unfortunately, I can't reproduce the crash (neither with a 1.2 build on linux, nor 1.2.0 or 1.2.1 on windows) so I can't confirm if it's fixed.

**Comment by Veratil** [comment] 2020-04-23 21:39
> Unfortunately, I can't reproduce the crash (neither with a 1.2 build on linux, nor 1.2.0 or 1.2.1 on windows) so I can't confirm if it's fixed.

If you move the subwindow titlebar to the bottom of the screen and resize up multiple times you should be able to get it to crash (without the patch).

**Comment by Spekular** [comment] 2020-04-23 21:41
I used this method on linux (laptop), but all I get is a misaligned keyboard, no crash. On windows (desktop) I'm able to resize without cheating, but the result is the same, no crash.

**Comment by Veratil** [comment] 2020-04-24 05:06
> Another attempt:
> --snip--

There's a few oddities when playing with the window and resizing with this patch:
* there's always one key not displayed, so the scroll never goes away
* when the window is sized very large, trying to resize the note edit area you have to go about an octave above the line before it starts to resize
* not sure if this is normal or with this change, but the very top key is half hidden
* when resizing down, the note edit area gets reduced to minimum 50 pixels rather than saving it's size

**Comment by Veratil** [comment] 2020-04-24 05:11
With my PR #5449, comparing:

* all keys will be visible (except one, see below)
* resizing note area works as expected
* mine seems to be missing B8, A#8 is half hidden
* note edit area stays the same
* bonus: I can resize the window so the note edit area handle is hidden, as well as the keys; scrolling doesn't work so you have to resize up to then resize the note area down 🤔

**Closed** 2020-05-12 10:57 UTC
Labels: bug
