### ISSUE TITLE
Equalizer plugin analyzer refresh rate is low when not touching the controls

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2846] opened 2016-06-13 19:26 UTC
First of all: the new Equalizer is AWESOME!! (and for multiple reasons, but that;s a digression)

Take a look how frequently Equalizer refreshes the spectrum analysers, while I click on the controls.

I captured the video wih Simple Screen Recorder with 60 FPS to better illustrate the effect (it's dramatic!):

https://youtu.be/D8r6R2t1Z0c

Shouldn't it refresh smoothly all the time?

**Comment by grejppi** [comment] 2016-06-13 20:07
Duplicate of #2736.

**Closed by grejppi** 2016-06-13 20:07 UTC
Labels: duplicate
