### ISSUE TITLE
Lmms 1.2.0-RC1 64bit crashing and export problems

### ISSUE THREAD

**Issue by dalton99** [LMMS/lmms#2792] opened 2016-05-23 05:18 UTC
Whenever I exit out of the program a or run it for a while it said that because it has crashed, and when I try to export it won't export some of the piano roles leaving them out of the recording.

**Comment by liushuyu** [comment] 2016-05-23 05:36
What operating system do you use? And can you paste the back trace ?

**Comment by tresf** [comment] 2016-05-23 14:19
> Whenever I exit out of the program  [it crashes]

Duplicate of https://github.com/LMMS/lmms/issues/2633.  Related #2772. 

> or run it for a while it said that because it has crashed

Related: #2675, #2626, #2497

> when I try to export it won't export some of the piano roles leaving them out of the recording.

This is a separate issue and needs to be tracked as such.  Please list exact steps to reproduce including a sample of your project file in a new bug report.

Closing as duplicate.  Again, please open one bug report per issue so that we can track, fix and close accordingly. :+1:

**Closed by tresf** 2016-05-23 14:19 UTC
