### ISSUE TITLE
LOMM is distorted and delayed.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#7353] opened 2024-06-26 23:54 UTC
### System Information

Debian Sid Cinnamon

### LMMS Version(s)

Nightly Version

### Most Recent Working Version

Versión 1.3.0-alpha.1.642+g6634cec12 (Linux/x86_64, Qt 5.12.8, GCC 9.4.0).

### Bug Summary

LOMM is an excellent plugin and I use it a lot, but it has a serious distortion and lag problem. When I open a project for the first time or when I select a preset with LOMM integrated, this plugin occasionally lags or distorts.

In this video I show you LOMM distorting a bus of bass tracks and another of well-mixed leads, but it sounds distorted more on the left side than on the right and you don't see the indicators move either.

https://github.com/LMMS/lmms/assets/26127693/0293c6d8-8a4e-4350-b615-f57ee0402b25

In this other video I show you LOMM as a multiband compressor (My favorite) on the Master Track, but this time it is distorting the entire track and it is heard more on the left side.

https://github.com/LMMS/lmms/assets/26127693/7a7f1e11-6f9e-43d4-8262-cebf0ce90c9a

In this case I have some presets exported with LOMM integrated, when I click with the mouse (because the presets are not previewed with the keys) on some occasions the presets sound distorted or the effect is delayed in the preview.

https://github.com/LMMS/lmms/assets/26127693/d413e5ac-54f6-445e-995e-de2759986a4d

Also when I export a song I hear a clip at the beginning or a delay on the track where LOMM is integrated, or distortion on the track, bus or master. In this case I don't have proof video, but do it yourself.

### Expected Behaviour

May LOMM not be delayed or distorted.

### Steps To Reproduce

1- Open an LMMS project with LOMM integrated into a track, bus or the master.
2- Create a preset with an instrument with integrated LOMM and do the test.
3- Before playing the entire song, move the cursor to the part of the track that contains integrated LOMM.
4- Close LMMS and open it again.
5- Go to the presets section and look for the ones you created previously.
6- You will notice the distortion or delay of LOMM.

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by LostRobotMusic** [comment] 2024-06-27 02:28
In your first video, the distortion is not a bug and has nothing to do with LOMM.  The distortion is because your track is clipping.  This happens any time the volume goes above 0 dBFS.  The oscilloscope at the top of LMMS turns red whenever your track's volume goes above 0 dBFS.  It is physically impossible for your speakers to play back audio above that volume, so LMMS (and all other DAWs) clips the audio to those limits when that maximum volume is surpassed.  To avoid clipping, you need to do anything that ensures the volume remains below 0 dBFS.

Your second video doesn't contain any audio.  Please provide a method to reproduce the issue if possible.

Your third video is a bug I've run into with several presets in the past, not with LOMM but with all sorts of effects.  I'm pretty sure LMMS's preset previewing is bugged.  I don't know if there's an existing issue for this.

**Comment by Gabrielxd195** [comment] 2024-06-27 03:28
@LostRobotMusic It seems like you didn't pay attention to the videos because the explanation is very clear and all three videos have audio, but I also made the mistake of not showing a video of the instrumental sounding good. Here a sample:

https://github.com/LMMS/lmms/assets/26127693/5c577729-71e2-4a3a-8c44-42ff84835403

The instrumental sounds good when there are no errors, there are no mixing errors, it sounds loud but not to the point of distorting as much as it happens in the previous videos, nor is it the low power of my computer. I did not make any corrections to the instrumental or touch any button to leave it as evidence, the only thing I did was play the entire instrumental before recording the video because these errors only happen when I open LMMS for the first time and when I play a preset that has LOMM included.

Examine the videos well and compare it with the latter so that you notice the changes, there are no mixing errors, the distortion and delay error is present in LOMM.

**Comment by LostRobotMusic** [comment] 2024-06-27 05:17
I did pay attention to the videos and responded to each individually.  The distortion is caused by clipping, not LOMM.

Your new video shows that there is in fact a bug present in the first video, though that bug results in incorrect volumes or broken compression, not any distortion of any kind.  This is now fixed in #7355.

**Closed** 2024-06-30 11:37 UTC
Labels: bug
