### ISSUE TITLE
Huge issue in 1.2.0-RC3

### ISSUE THREAD

**Issue by scalenetracks** [LMMS/lmms#3653] opened 2017-06-22 08:22 UTC
I just updated to 1.2.0-RC3 about 5 minutes ago. I tried continuing to work on my new track, however, I was faced with a huge problem. On 1.1.3, I would use the feature of being able to copy a loop over to another section of the song with the Command Key + Click and drag onto the spot you want it. This does not work on 1.2.0-RC3! I try doing this, but it does not show a "+" symbol when I drag it onto a blank area on the song editor, and it does not copy the segment/loop.

Pretty frustrating! I like the theme that the new version has, I just don't like how this major feature is missing.

Just to help, if this means anything, I am running LMMS from macOS Sierra 10.12.5 (newest version)

**Comment by musikBear** [comment] 2017-06-22 10:04
@scalenetracks need clarification 
You say 'loop'
You mean a **Beat&Bass-editor Block**, inserted in song-editor
Eg The ***third*** described Here: http://lmms.io/wiki/index.php?title=Song_Editor#Working_with_Segments
The **Beat/Bassline Tracks** is what you call a 'loop' -Right?

**Comment by zonkmachine** [comment] 2017-06-22 10:23
> I am running LMMS from macOS Sierra 10.12.5 (newest version)

@scalenetracks I think this is a possible duplicate of https://github.com/LMMS/lmms/issues/2890

**Comment by tresf** [comment] 2017-06-22 13:27
@scalenetracks please use Command + Alt + Click for copying until this is fixed.  This is a duplicate of #2890.

**Closed by tresf** 2017-06-22 13:27 UTC
