### ISSUE TITLE
Windows title bar question and suggestion/opinion perhaps.

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#123] opened 2014-01-24 00:09 UTC
Hi is it possible to have the highlighted colour of the windows title bar changed from the blue to perhaps a darker grey ? And also i would like to see the minimize, maximize, close buttons switched to the left hand side and obviously the icons to the right. I say this for 2 reasons, (1) as a linux Ubuntu only user i keep going to the left hand side automatically ( force of habit ) to close etc a window (2) And as the app was originally created as a linux only app in the beginning i think it would be more fitting. 

I know im biased in my opinion here, it would be interesting to hear everyones opinion on this, if it is even possible to do

thanks Mikobuntu :)

**Comment by tresf** [comment] 2015-03-08 18:21
Marking as duplicate of the "Cusis Theme" effort #1839 and closing to consolidate bug reports.

**Closed by tresf** 2015-03-08 18:21 UTC
Labels: duplicate, enhancement
