### ISSUE TITLE
Automation causes crash ASSERT: "it == time_map.end()-1"

### ISSUE THREAD

**Issue by arminarmin** [LMMS/lmms#2535] opened 2016-01-30 13:39 UTC
Greetings,
hope I´ll get some Instructions for fixing that problem. Need to say that LMMS ist really really awesome,according its an os-program! Thanks alooot for free software!

Problem: I want to automate a DryWet-Knob of a delay-effect for further steps in the song. I open the automation-editor, scrolling to part 42 and want to set a curve from 0 to 1 till step 64. LMMS doesn´t connect the automation to the start-point, you have an empty automation range from 0to42 and then it crashes.. :(

The terminal says:
ASSERT: "it == time_map.end()-1" in file /build/buildd/lmms-1.0.0+stable/src/gui/AutomationEditor.cpp, line 1600

Thanks anyway :)
Armin

**Comment by softrabbit** [comment] 2016-01-30 18:10
Duplicate of #540, and fixed in 1.1, which is the current stable version. You seem to be running 1.0.0, which has been EOL since July 2014. You're options as I see them are upgrade or live with it. Or, if you totally have to run 1.0, backport the fix, see commit 2505c770bb756cacd87b6d6f4a13730b3c142087 (i.e. remove the assert line).

**Closed by softrabbit** 2016-01-30 18:10 UTC
Labels: duplicate

**Comment by arminarmin** [comment] 2016-01-30 18:13
Hey,
thanks for your answer! I´m confused.. Had this idea about the version but looked at the LMMS-Website and couldn´t find the new version.
I´m using Ubuntu and they only deliver verison 1.0

Thanks alot!

**Comment by softrabbit** [comment] 2016-01-30 18:45
You're probably on 14.04, judging from your LMMS version. You could try the KXStudio repositories (http://kxstudio.linuxaudio.org/Repositories#Ubuntu), but be warned: **this might affect other packages on your system.**

**Comment by arminarmin** [comment] 2016-01-30 20:01
Yes, I´m on 14.04.
Did the things, installed the kxstudio package over Ubuntu Software Center, then updated LMMS, now I have v1.1.3, it works fine! 
But as we talk now about, this issue with packages, do I have to mind anything? Is my system stable in the future? Is there any program or something I can check for dependencies and stuff..

Thanks ;)
