### ISSUE TITLE
AFP gets wrong path for .ds files 

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#2412] opened 2015-10-13 18:04 UTC
Noticed a project I loaded was missing samples in master. And then I noticed previewing .ds files and loading them from the file browser bar didn't work. Using the file browser in AFP works. A ```printf``` at the top of ```DrumSynth::GetDSFileSamples``` showed different paths being passed for a test file:

```data:/samples/drumsynth/acoustic/Brush1.ds```, the one that fails
```/home/raine/src/lmms/target/share/lmms/samples/drumsynth/acoustic/Brush1.ds```, install directory prepended, the one that works

**Comment by tresf** [comment] 2015-10-16 12:50
Hmm... This may be duplicate of the LADSPA bugs we're getting reports of (#2403) and we've had a few changes since 1.1 that impact the search paths, namely: #1908, #1719.

**Comment by tresf** [comment] 2015-10-16 14:25
I'm 99% sure this is introduced with #1719 as it replaces the data directory with `data:` in the string (e.g. dc1f8dc) Tagging @Lukas-W as there seems to have been a few use-cases that were missed.

**Comment by tresf** [comment] 2015-10-16 14:37
Initial investigation shows `QDir` is what is used to resolve `plugins:`, `data:`, etc.  I'm guessing AFP isn't calling `QDir`, which means the selection dialog was fixed, but the AFP plugin was not.

Some plugins seem to call `QDir` whereas other don't, so I'm not sure if the fix needs to be in [AFP source](https://github.com/LMMS/lmms/blob/master/plugins/audio_file_processor/audio_file_processor.h#L56) or in [FileBrowser source](https://github.com/LMMS/lmms/blob/master/src/gui/FileBrowser.cpp#L476)...

**Comment by Lukas-W** [comment] 2015-10-17 11:12
Thanks for reporting @softrabbit and for investigating @tresf.

I guess this is what @zonkmachine tried to describe in [his comment](https://github.com/LMMS/lmms/pull/1719#issuecomment-125638856) back in July in #1719. I wonder why he didn't explain the problem any further or opened an issue for it.

**Comment by zonkmachine** [comment] 2015-10-17 17:08
@Lukas-W 

> I wonder why he didn't explain the problem any further or opened an issue for it.

Because I thought the bug was on my side.

**Comment by softrabbit** [comment] 2016-02-09 17:49
@Lukas-W, are you sure you fixed this? I still see this behavior in master.

**Comment by Lukas-W** [comment] 2016-02-09 21:36
Still works for me on 1290e33.

**Comment by softrabbit** [comment] 2016-02-10 09:50
OK, will dig deeper into this. To be sure, I blew away and recreated my target and build directories before pulling the latest souce and building, configured with ```cmake .. -DWANT_QT5=false -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=DEBUG```. Running from build directory, like this:
```
$ ../target/bin/lmms --version
LMMS 1.1.3-g1290e33
(Linux i386, Qt 4.8.6, GCC 4.8.4)
$ lsb_release -a |grep Description
Description:	Ubuntu 14.04.3 LTS
$ uname -or
3.13.0-58-generic GNU/Linux
$ ../target/bin/lmms ../target/share/lmms/projects/Demos/Skiessi/Skiessi-Onion.mmpz
```
Open the instrument for one of the .ds tracks, e.g. the fifth track, ```old_kik.ds```. I have a flatline in AFP and it displays the filename ```drumsynth/r_n_b/old_kik.ds```. Clicking the folder icon, the correct file is preselected and when I choose ```Open``` the file loads fine.

So I reinstated the printf I mentioned in the original message (```	printf("GetDSFileSamples: %s\n",dsfile);``` in [DrumSynth::GetDSFileSamples] (https://github.com/LMMS/lmms/blob/master/src/core/DrumSynth.cpp#L259)), and it outputs this:
```
GetDSFileSamples: data:/samples/drumsynth/r_n_b/old_kik.ds
GetDSFileSamples: data:/samples/drumsynth/misc/electro_snare_layer.ds
GetDSFileSamples: data:/samples/drumsynth/misc/electronic_rim.ds
GetDSFileSamples: data:/samples/drumsynth/misc/it's_like_that_snare.ds
GetDSFileSamples: data:/samples/drumsynth/misc/it's_like_that_snare.ds
GetDSFileSamples: data:/samples/drumsynth/misc_hats/lighthat.ds
GetDSFileSamples: data:/samples/drumsynth/misc_hats/live_sound_hh.ds
GetDSFileSamples: data:/samples/drumsynth/electro/S_8bit.ds
GetDSFileSamples: data:/samples/drumsynth/electro/S_8bit.ds
GetDSFileSamples: data:/samples/drumsynth/electro/K_8bit.ds
GetDSFileSamples: data:/samples/drumsynth/electro/K_8bit.ds
```

**Comment by Lukas-W** [comment] 2016-02-10 22:07
Aha, that's a different issue. Your original report was about preview and opening from the sample browser bar. This is about loading a project that has the file saved as a relative path. Looking into it,

**Comment by softrabbit** [comment] 2016-02-10 22:56
@Lukas-W, maybe a bit on the terse side, but the original report does mention loading a project...

**Comment by Lukas-W** [comment] 2016-02-10 22:58
Yeah, fair enough

**Comment by Lukas-W** [comment] 2016-02-10 22:59
@softrabbit Can you confirm ca8f80d fixes it?

**Closed** 2016-02-10 22:58 UTC

**Comment by softrabbit** [comment] 2016-02-11 09:25
Yes, it works now. Looks to me like this took care of #2468 as well :+1:

**Comment by Lukas-W** [comment] 2016-02-11 09:51
Thanks for testing!
