### ISSUE TITLE
Automation editor in playBack -Moving Playhead?

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#857] opened 2014-06-15 22:58 UTC
Searched board, but could not find ref. to this glitch. 
Think playhead should move, or be REmoved :p 
Joke aside, it would be a good thing if playhead moved, because user could see where an artefact actually came from during automation-Thoughts?

**Comment by tresf** [comment] 2016-09-26 15:49
Duplicate of #3052.  #857 one came first, but #3052 is more comprehensively written.

**Closed by tresf** 2016-09-26 15:49 UTC
Labels: enhancement, gui
