### ISSUE TITLE
Multiple Beat/Basslines Overwrites Other Instruments

### ISSUE THREAD

**Issue by htmlguy** [LMMS/lmms#2415] opened 2015-10-17 14:53 UTC
I am new to LMMS. When I create a beat/bassline, it works just fine, but if I create another one with different instruments, I find that the first beat/bassline I created has been overwritten with empty tracks of the instruments I chose for the second beat/bassline.

I am not sure whether this is a bug or just me being unfamiliar with the program.
I am using LMMS 1.13 on windows 10, but have found that the same issue occurs on LMMS on my Trisquel GNU/Linux box (I don't know what version of LMMS that one is.)

**Comment by tresf** [comment] 2015-10-17 15:00
Overwritten is a bit inaccurate.

The behavior is intended (and confusing in my opinion), and the "issue" you describe is a duplicate of enhancement request #453

**Closed by tresf** 2015-10-17 15:00 UTC

**Comment by htmlguy** [comment] 2015-10-17 15:18
Now Ctrl+Z cannot undo my removal of instruments from the beat/bassline editor.
I seem to have lost my work, but now I know how to avoid this in the future.
Thanks for the help, though!
