### ISSUE TITLE
Piano-roll will always autoscroll in 'record while playing the song or bb track' mode

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#656] opened 2014-04-28 15:17 UTC
(win32) insignicant, but a glitch. 
Reproduce
disabe auto-scrolling in song-editor
Open a pattern in piano-roll 
disabe auto-scrolling in piano-roll 
do a 'record-playback' with the 3. playback-button (triangle+circle)
The pattern will still scroll.
The 3 modes for play-head-stop-posistion is also somewhat wrong here, and loop-markers in piano-roll are ignored.

Second record-button ('red circle') does not scroll -eg it works correct, and stop-possistions are also correct, and so is loopmarker respons.
Can the 'red circle' buttons correct behavior perhaps be reused, for the faulty 'triangle+circle' button?

**Comment by Umcaruje** [comment] 2015-06-29 14:31
@musikBear can you please elaborate this feature a bit more, or offer some screenshots or video. Is it reproducible in 1.1.3?

**Comment by musikBear** [comment] 2015-06-29 18:30
yes for 1.1.3 
i will make a vid tomorrow

**Comment by musikBear** [comment] 2015-06-30 10:44
@Umcaruje 
Here is the video
http://youtu.be/zYSLStvKrQo

**Comment by Umcaruje** [comment] 2015-06-30 10:53
Ok yeah this is a bug, thanks for the clarification.

**Comment by tresf** [comment] 2015-08-24 14:26
Closing as duplicate of meta-bug Better Playhead Auto-Scroll #2291.  Please feel free to comment here if needed.

**Closed by tresf** 2015-08-24 14:26 UTC
Labels: bug, gui

**Comment by Umcaruje** [comment] 2016-05-02 11:25
@midi-pascal take a look at this one too :wink: ?

It seems like autoscroll is ignored when we use the record while playing button(![screenshot from 2016-05-02 12 43 31](https://cloud.githubusercontent.com/assets/6282045/14952788/ce9e6036-1063-11e6-863f-5e0a584cac26.png)).

Autoscroll works as expected in the song editor, but in the piano-roll it constantly auto-scrolls, and the setting gets ignored. Another thing that I noticed is that in this mode, the song editor does not smooth scroll.

**Comment by midi-pascal** [comment] 2016-05-02 21:14
@Umcaruje For sure I will!

**Comment by midi-pascal** [comment] 2016-05-04 00:01
@Umcaruje From what I can see up to now, the scrolling mechanism in the piano roll is rather broken at some places and not implemented at others. I was able to disable the unwanted scrolling but the time line does not behave according to the settings: it does not return at its previous position when it should.
I will fix all this but it will take more time than I thought because I will have to add the missing logic in the piano roll.

**Comment by messmerd** [comment] 2026-01-14 07:03
I couldn't reproduce it on master, though it's possible I wasn't testing it correctly
