### ISSUE TITLE
Resizable Mixer

### ISSUE THREAD

**Issue by M4rotte** [LMMS/lmms#6902] opened 2023-09-27 19:28 UTC
I’d appreciate to have the possibility to increase/decrease Mixer windows height, with its content.

It would permit to make visible longer Mixer channel names, and to have a longer volume slider, which would give more precision. As for the peak-meter.

I hope my description is meaningful without a mock-up. Do not hesitate to question me if something isn’t clear. I also keep in mind it’s absolutely not a priority and I do not even know about the difficulty to implement that, or even the possibility to do so.

**Comment by zonkmachine** [comment] 2023-09-27 19:59
Duplicate of https://github.com/LMMS/lmms/issues/3258 ?

**Comment by michaelgregorius** [comment] 2023-09-27 20:49
> Duplicate of #3258 ?

Seems so. And #3258 in turn has been moved into the "Better Workflow" issue: #4877. Here it is represented as "Make the Mixer window vertical resizable".

**Comment by Veratil** [comment] 2023-09-27 21:06
Closing as duplicate.

**Closed by Veratil** 2023-09-27 21:06 UTC
Labels: enhancement
