### ISSUE TITLE
ZynAddSubFX crashes when opening its GUI if the LMMS Pitch knob is connected to a Peak Controller

### ISSUE THREAD

**Issue by DouglasDGI** [LMMS/lmms#4618] opened 2018-09-25 22:58 UTC
The title says it all.  Please tell me if this is a duplicate issue.  I am using RC6 currently.

**Comment by DomClark** [comment] 2018-09-25 23:00
Duplicate of #4552.

**Closed by DomClark** 2018-09-25 23:00 UTC
