### ISSUE TITLE
The piano roll clip does not fit or stretch

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4615] opened 2018-09-25 06:00 UTC
Hello people. how are you?. In lmms, the sample track clips, bb editor and automations are flexible and can be freely extruded and contracted, but the piano roll clips do not. these last ones can not be extended or contracted, neither adapt to the measure of the first until the last note in a midi clip, but it only adapts to a clip of a second, which causes that creates unnecessary empty spaces making the Melody is out of time.
it looks more or less like this:

![espacios vacios imnecesarios](https://user-images.githubusercontent.com/26127693/45995262-5b40bf80-c065-11e8-9c97-d75616f6312e.png)

In an enlarged image it looks like this.

![espacios vacios imnecesarios aumentado](https://user-images.githubusercontent.com/26127693/45995294-82978c80-c065-11e8-8658-6a1cc7b308d5.png)

As you can see, at the end of the clip, there is only a short note, but the clip's range extends much more, leaving an empty space. in other daw I have seen that the midi clips adapt to the measurement of the first note until the last one, in lmms it is not like that. If possible, they should correct this error and add a grid system. Blessings

**Comment by musikBear** [comment] 2018-09-25 14:27
No -you have misunderstood the concept of measures.
A song-editor block **must** always fit in *bars* !
Your issue is caused by a wrong time-signature!
I have explained the time-signature issue in this video:
https://youtu.be/39uFMAoFOPU

**Comment by Spekular** [comment] 2018-09-25 15:13
No, there's no misunderstanding, this is a valid feature request. It's by
no means unusual to have piano roll patterns that aren't exact multiples of
four bars, even in a 4/4 song. This issue proposes (assuming I understand
it correctly) that the pattern's length be reflected more finely in the
song editor.

**Comment by jibin1573** [comment] 2018-09-26 04:03
If you are talking about the notes in the Pianoroll, then you should chose 1/196 (Quantization),to record absolutely everything. And if it is about free dragging the selected notes, then Alt+drag the note left or right in time without snapping to the grid. This also works for a selection of notes. The note(s) will "free-drag" and snap to the nearest 1/192 time increment (max Quantisation in LMMS).

(Please ignore this if I have misunderstood you)

**Comment by Gabrielxd195** [comment] 2018-09-26 22:51
> Si está hablando de las notas en el Pianoroll, debe elegir 1/196 (Cuantización) para grabar absolutamente todo. Y si se trata de arrastrar libremente las notas seleccionadas, entonces Alt + arrastre la nota hacia la izquierda o hacia la derecha en el tiempo sin ajustar a la cuadrícula. Esto también funciona para una selección de notas. La (s) nota (s) se "arrastrarán libremente" y se ajustarán al incremento de tiempo 1/192 más cercano (Cuantización máxima en LMMS).
> 
> (Por favor, ignóralo si te he entendido mal)

I'm not talking specifically about the notes of the piano roll, but the clip or block of piano roll in the song editor. but anyway, thanks ... first of all, if you look closely, lmms does not have an adjustable grid system like ardour, qtractor, etc. the lmms grid measures exactly 1 second away and you can neither increase nor decrease them ... in the song editor you can freely extricate and collapse the blocks of sample track, bb editor, automation by touching their edges and pressing '' ctrl '' (these blocks do not have to be exactly 1 second, they adapt to the content, and do not leave empty spaces), but with the piano roll block the same thing does not happen, the piano roll blocks last exactly 1 second, you can not Extract or collapse in the song editor, even by pressing '' ctrl '', that is, they are blocked. You can try it right now. for example: enter the piano roll and place a note of 1/4 second at the beginning, go to the song editor and you will see that the piano roll block takes exactly 1 second when you only have a 1/4 note, you will see that inside the block is the note but also a large empty space that could be eliminated by contracting the block, or that the block automatically adapts to the length measure that is between the first and the last placed note. This is very basic I do not know how you have not noticed, or have not understood the comment, I have mentioned this other times. You can do the test in other daw and you will see that this problem is non-existent.

**Comment by Gabrielxd195** [comment] 2018-09-27 23:27
> @ Gabrielxd195 por favor, eche un vistazo a este hilo también, si es similar: [# 1658](https://github.com/LMMS/lmms/issues/1658)

This thread is more or less similar, but the difference is that this user proposes the removal and rearrangement of the midi notes from within the piano roll (which by the way would be quite useful, but it would have to be implemented as an option, either by pressing a button or changing some configuration). whereas what I propose is the improvement of the clip or block of piano roll, but from the song editor, nothing to do with the notes of the piano roll, is only to add the possibility of exting or contracting the piano roll blocks in the song editor, as well as the sample track, bb editor and automation blocks. regards

watch this video, it's something like this:

![clip de piano roll no se extira ni contrae](https://user-images.githubusercontent.com/26127693/46179840-37f75980-c28b-11e8-81e8-13ccbc9c3d35.gif)

**Comment by jibin1573** [comment] 2018-09-28 04:37
Yes now I understand clearly! You are right, the Instrument blocks on the Song editor are rigid and cannot be adjusted like the BB Blocks, Sample Blocks etc. Adjustable Instrument blocks can turn out to be pretty useful.

**Comment by tresf** [comment] 2018-09-29 16:52
Added use-case to https://github.com/LMMS/lmms/issues/1658.  Marking as duplicate.  @Gabrielxd195 please search first.

**Closed by tresf** 2018-09-29 16:52 UTC
