### ISSUE TITLE
VST instruments and VeSTige

### ISSUE THREAD

**Issue by mqbaka** [LMMS/lmms#2477] opened 2015-12-04 10:00 UTC
LMMS often freezes when using a VST plugin whith VeSTige.

**Comment by musikBear** [comment] 2015-12-04 11:56
I cant assist you here, but This resource is not the right forum for Q&A, Q&A should takes place in our dedicated help-forum :)
Could i ask you to create an account there: http://lmms.io/forum/ ?
Please post
* OS (+service-pack-ver)
* lmms vers
* if any, name of theme
* hardware specification (ram & soundcard is the most imortant)
* names and best download links of the failing vst's

**Comment by tresf** [comment] 2015-12-04 13:27
@musikBear please stop asking for irrelevant things.  Steps to reproduce (including OS and VST) are sufficient.

@mqbaka steps to reproduce including OS and VST are required, otherwise this will be closed.

**Comment by tresf** [comment] 2015-12-27 02:24
23 days without proper response.  Closing as invalid, as we can't fix something we can't reproduce.

**Closed by tresf** 2015-12-27 02:24 UTC
Labels: invalid
