### ISSUE TITLE
[Linux Mint 20] Appimage creation fails

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#5609] opened 2020-08-03 01:02 UTC
### Bug Summary
The title.
#### Steps to reproduce
- Build LMMS.
- Attempt to `make appimage`.

#### Expected behavior
Appimage is created.
#### Actual behavior
something named "linuxdeployqt-continuous-x86_64.appimage" is created, but no lmms appimage.

#### Affected LMMS versions
1.2.2, i guess?

#### Logs
i finally have logs
<details>
  <summary>Click to expand</summary>
<pre>
› make appimage                                              build git:(master)
Scanning dependencies of target removeappimage
Removing old AppImage
Built target removeappimage
Scanning dependencies of target appimage
Generating AppImage

Writing verbose output to "/home/gingka/lmms-build/lmms/build/appimage.log"

Downloading linuxdeployqt to /home/gingka/lmms-build/lmms/build/linuxdeployqt...
   [.......] Downloading (x86_64): https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
   [success] Downloaded /home/gingka/lmms-build/lmms/build/linuxdeployqt
   [success] Extracted squashfs-root/usr/bin/appimagetool

Creating /home/gingka/lmms-build/lmms/build/LMMS.AppDir/...
   [success] Created /home/gingka/lmms-build/lmms/build/LMMS.AppDir/

Copying /home/gingka/lmms-build/lmms/target to /home/gingka/lmms-build/lmms/build/LMMS.AppDir/...
   [success] /home/gingka/lmms-build/lmms/build/LMMS.AppDir/
mv: cannot stat '/home/gingka/lmms-build/lmms/build/LMMS.AppDir/usr/lib/lmms/32/RemoteVstPlugin32.exe.so': No such file or directory
mv: cannot stat '/home/gingka/lmms-build/lmms/build/LMMS.AppDir/usr/lib/lmms/RemoteVstPlugin64.exe.so': No such file or directory
ldd: /home/gingka/lmms-build/lmms/build/LMMS.AppDir/usr/bin/RemoteVstPlugin32.exe.so: No such file or directory
ldd: /home/gingka/lmms-build/lmms/build/LMMS.AppDir/usr/bin/RemoteVstPlugin64.exe.so: No such file or directory

Bundling and relinking system dependencies...
make[3]: *** [cmake/linux/CMakeFiles/appimage.dir/build.make:59: cmake/linux/CMakeFiles/appimage] Error 1
make[2]: *** [CMakeFiles/Makefile2:2197: cmake/linux/CMakeFiles/appimage.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2204: cmake/linux/CMakeFiles/appimage.dir/rule] Error 2
make: *** [Makefile:238: appimage] Error 2
</pre>
</details>

**Comment by jslater89** [comment] 2020-08-17 15:28
I have a similar problem—trying to build an appimage with ghost note support for local use. My logs are slightly different:

```
$ make appimage
Removing old AppImage
Built target removeappimage
Generating AppImage

Writing verbose output to "/home/jay/development/lmms/build/appimage.log"

Downloading linuxdeployqt to /home/jay/development/lmms/build/linuxdeployqt...
   [.......] Downloading (x86_64): https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
   [success] Downloaded /home/jay/development/lmms/build/linuxdeployqt
   [success] Extracted squashfs-root/usr/bin/appimagetool

Creating /home/jay/development/lmms/build/LMMS.AppDir/...
   [success] Created /home/jay/development/lmms/build/LMMS.AppDir/

Copying /home/jay/development/lmms/target to /home/jay/development/lmms/build/LMMS.AppDir/...
   [success] /home/jay/development/lmms/build/LMMS.AppDir/
	libwine.so.1 => not found

Bundling and relinking system dependencies...
make[3]: *** [cmake/linux/CMakeFiles/appimage.dir/build.make:59: cmake/linux/CMakeFiles/appimage] Error 1
make[2]: *** [CMakeFiles/Makefile2:2195: cmake/linux/CMakeFiles/appimage.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2202: cmake/linux/CMakeFiles/appimage.dir/rule] Error 2
make: *** [Makefile:238: appimage] Error 2
```

linuxdeployqt doesn't like the newness of the Mint 20 package base:

```
>>>>> linuxdeployqt
linuxdeployqt 6 (commit d41e234), build 723 built on 2020-07-30 06:25:46 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (xenial), which is glibc 2.23.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
```

**Comment by PhysSong** [comment] 2020-10-31 06:09
`linuxdeployqt` refuses to create AppImages on systems much newer than the baseline(currently Ubuntu 16.04 Xenial). Linux Mint 20 is based on Ubuntu 20.04, so you can't create one on it.

**Comment by GingkathFox** [comment] 2020-10-31 18:01
is `linuxdeployqt` out of date or something? 16.04 is years ago

**Comment by PhysSong** [comment] 2020-11-01 02:09
> is `linuxdeployqt` out of date or something?

It's rather their policy due to some compatibility issues. For example, you can't run an AppImage created on Ubuntu 20.04 on 18.04.

**Comment by GingkathFox** [comment] 2020-11-01 15:14
Ah, makes sense

**Comment by PhysSong** [comment] 2020-12-25 06:55
Closing because this is an intended behavior from upstream.

**Closed by PhysSong** 2020-12-25 06:55 UTC
Labels: bug
