### ISSUE TITLE
"Add Effect" causes the entire program to freeze

### ISSUE THREAD

**Issue by Fothcrah** [LMMS/lmms#3736] opened 2017-07-29 11:33 UTC
Clicking "Add Effect" in both the FX-Mixer and in instrument-specific FX chains causes LMMS to freeze and stop responding. CPU usage briefly jumps to 100%, but throttles down after 4-5 seconds. RAM fills up and beings swapping out, but return to normal after about 20-30 seconds. I never get to see the window to select a plugin and the program stays unresponsive until I kill it. It does not output anything to the console during that time or after. All other GUI elements and dialogue boxes seem to be perfectly functional, including ZynAddSubFX's GUI and VeSTige.
This is persistent across all builds I've tried (1.2.0 against Qt5 as well as GTK3 and 1.1.3 against GTK3).
The problem seems to be fixed by running LMMS as root.

Further details:
OS: Arch Linux (running KDE Plasma)
Kernel: 4.9.37-1 LTS
RAM: 4GB DDR3-1600
CPU: Intel Core i5-3210m @ 2.5GHz
GPU: nvidia GeForce 610m

**Comment by musikBear** [comment] 2017-07-30 11:05
@Fothcrah this cant ofcause be a general issue (bug), Mio's of peeps has run lmms 1.1.3 on linux, and a general crash-bug for adding effects has not been reported, nor has it been seen in development  it has to be a local issue on your distro, or pc. 
So you are asking for support, and our forum is best for that:
http://lmms.io/forum/index.php

**Comment by BaraMGB** [comment] 2017-08-01 08:49
Perhaps there's something wrong with one of the paths you set in the settings. Seems like a infinite loop. Do you use symbolic links?

**Comment by Umcaruje** [comment] 2017-08-01 09:06
A user already had this issue iirc, please check that your vst effect
folder is not your home folder or any other huge folder like that.

On 1 Aug 2017 10:49, "Steffen Baranowsky" <notifications@github.com> wrote:

Perhaps there's something wrong with one of the paths you set in the
settings. Seems like a infinite loop. Do you use symbolic links?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LMMS/lmms/issues/3736#issuecomment-319309074>, or mute
the thread

**Comment by musikBear** [comment] 2017-08-01 18:52
> or any other huge folder like that

Oh yes! Folders with huge size, and or huge number of files takes *very* long to index, it may appear that lmms is 'frozen', but infact it is 'just' indexing for very long time.
I actually also think that zipped files in the folder, will make the indexing take longer time. Look like they are being unzipped as temporary files.
@zonkmachine -Have you any input regarding zipped files. Synth1 zipped banks takes significantly longer to index

**Comment by zonkmachine** [comment] 2017-08-02 10:03
> @zonkmachine -Have you any input regarding zipped files. Synth1 zipped banks takes significantly longer to index

You're ol' xp is indexing compressed content?
https://www.pcmag.com/article2/0,2817,1573774,00.asp

**Comment by musikBear** [comment] 2017-08-02 11:17
> You're ol' xp is indexing compressed content?

LOOoool 🥇 
Bobyslam detected..

**Comment by Umcaruje** [comment] 2017-08-08 12:11
@Fothcrah can you please check your `.lmmsrc.xml` file?

**Comment by lukas-w** [comment] 2017-12-26 12:59
No reaction from @Fothcrah in five months, so we can only speculate what the cause of this is/was. Closing.

**Closed by lukas-w** 2017-12-26 12:59 UTC
Labels: needs clarification

**Comment by he29-net** [comment] 2019-01-31 11:10
In case anyone encounters this problem again: I just ran into this issue with 1.2.0-rc7 and the problem was indeed caused by incorrect folder setting as someone suggested earlier.
The LADSPA plugin directory was set to "/usr/bin/../lib/x86_64-linux-gnu//ladspa/" -- looks like some sort of auto-generated path, perhaps filled in by a package manager (I previously used version 1.1.3 installed from Debian repository).
Locating the correct directory (in my case /usr/lib/ladspa/) and fixing the path solved the freezing issue.
