### ISSUE TITLE
Importing a midi file and exporting it again resets all instruments to acoustic piano

### ISSUE THREAD

**Issue by ell1e** [LMMS/lmms#6180] opened 2021-10-02 15:23 UTC
### Bug Summary

Importing a midi file into LMMS and exporting it again resets all instruments to acoustic piano when played via timidity++ or VLC (when the original file had correct instruments).

#### Steps to reproduce
1. (Maybe not required) Set a GM default soundfont in settings
2. File > Import of https://github.com/abique/midi-parser/files/7212564/test.mid.zip (if you play this original file in VLC or timidity++, it should have correct instruments)
3. Play it in LMMS just to verify, you should get proper instrument assignments here still
4. File > Export Midi...
5. Play the resulting exported file in VLC or timidity++, and suddenly acoustic piano galore.

#### Expected behavior
correct GM instruments retained after export

#### Actual behavior
acoustic piano galore

#### Affected LMMS versions

1.2.2

**Comment by ell1e** [comment] 2021-10-02 15:29
On further examination, it seems playback speed is greatly messed up too. (The export plays ~2x faster, even though again in LMMS itself everything plays fine.)

**Comment by Spekular** [comment] 2021-10-02 15:36
Main post is a duplicate of #5198, #5287

**Comment by Spekular** [comment] 2021-10-02 15:41
> On further examination, it seems playback speed is greatly messed up too. (The export plays ~2x faster, even though again in LMMS itself everything plays fine. So the import evidently works correctly, just the export somehow messes it all up.)

This may be related to #4765. Is there any chance your original file is ~70BPM, and if not had you changed the project tempo before importing? We use an automation track to set the tempo when importing MIDI, but since automation isn't respected on output perhaps it's using the pre-automation tempo or default project tempo instead.

**Comment by ell1e** [comment] 2021-10-02 15:43
I didn't make that midi file so I have no idea. You can easily reproduce the tempo problem by downloading the file and following the steps, I didn't do anything else to trigger it.

**Comment by Spekular** [comment] 2021-10-02 15:52
The tempo is indeed 72 (you can see it when you import and play the file), so the tempo issue is a side effect of #4765. Closing as duplicate.

**Closed by Spekular** 2021-10-02 15:52 UTC
Labels: bug
