### ISSUE TITLE
SongEditor - Pencil Tool Usage

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#942] opened 2014-07-07 12:41 UTC
winXp 32
in use of pencil
1) Its not intuitive that ctrl+LMB does not change pencil to fast-select (as in Piano-roll)

2)cursor still change to 'resize' at right-end of note-blocks (cant be resized)

**Comment by Spekular** [comment] 2020-07-28 22:33
Issue 1 is solved. I'm not sure if 2 warrants an issue all by itself, but it should probably be a quick fix if so.

**Comment by DomClark** [comment] 2020-07-29 12:21
(2) is a duplicate of #740, fixed in #1563.

**Closed by DomClark** 2020-07-29 12:21 UTC
Labels: enhancement
