### ISSUE TITLE
Empty automation patterns are treated as disconnected

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#5725] opened 2020-10-21 18:54 UTC
In master:
- Create an automation clip by ctrl + dragging a control onto an automation track
- Double click or use context menu to open it in the automation editor
- Erase all the points with right mouse button or erase mode
- Automation editor displays "Please open an automation pattern [...]" and no new points can be drawn

LMMS 1.2.2 behaves correctly, acknowledging the fact that the pattern has a connection and allowing points to be placed.

Marking for 1.3 since it's a regression.

**Comment by zonkmachine** [comment] 2020-10-21 19:53
Issue confirmed. Bisect points to commit e37f3793f381d84658c9dafd115f8c10bcba9c1a

Author: Kevin Zander <veratil@gmail.com>
Date:   Wed Jul 29 13:26:20 2020 -0500

    Fix validPattern to check if hasAutomation as well (#5124)

@Veratil

**Comment by Spekular** [comment] 2020-10-21 20:02
Aaaaand I'm the one who merged it, after also approving it. Lol.

**Comment by Veratil** [comment] 2020-10-21 20:32
Hm, alright. I'll see what I can figure out. It fixed the piano roll problem, but caused the automation editor issue now.

What if we just don't allow the first *and only* node from being deleted?

**Comment by IanCaio** [comment] 2020-10-21 21:03
Where was `validPattern` used on the Piano Roll? I tried to find it on the detuning drawing but didn't.

I think keeping the user from removing the last node from being removed could be a good solution, I can even include that last node safety check on my PR since it changes `AutomationPattern` and `AutomationEditor` so much. First we just need to check there's nothing else calling `validPattern` where an empty pattern could be expected.

**Comment by Veratil** [comment] 2020-10-21 21:05
You're right, I was thinking of something else. This was in AutomationEditor.

**Comment by Veratil** [comment] 2020-10-21 21:20
> First we just need to check there's nothing else calling `validPattern` where an empty pattern could be expected.

There are 17 hits in https://github.com/LMMS/lmms/blob/master/src/gui/editors/AutomationEditor.cpp that use `validPattern`. I think the only time it's expected to tell the user to connect a pattern.

Alternatively, maybe we need to double check the `m_pattern->hasAutomation()` call, too? Currently it looks like it's just checking if `m_timemap.isEmpty() == false`. Should we look to change this or prevent the first node from being deleted?

**Comment by IanCaio** [comment] 2020-10-21 21:33
I think we will have to get philosophical now, what makes a pattern valid? :thinking:

Jokes aside, I think most of the places the `if (!validPattern())` safety check is present actually wants to keep a `m_pattern` with value of nullptr of being used. Afaik, they would still work with an empty pattern, have to double check though. Should we study the code on #5712 instead? Since most of those methods get changed there?

Btw, I agree with the idea of preventing the last node from being deleted, but thinking here, isn't the detuning automation pattern empty when there's no detune information? Another thing I need to check.

**Comment by Veratil** [comment] 2020-10-21 22:38
If there is no detuning data then there should be no pattern. I don't believe we make a pattern until you open the detuning editor for that note. So removing the last node in this instance would be okay (delete the detuning info), or maybe we should have a way to remove detuning from a note since I don't think we have a way right now other than deleting the note.

**Comment by IanCaio** [comment] 2020-10-25 00:32
I was checking every method that called `validPattern` on _AutomationEditor.cpp_, and unless I missed something they all are safe to call with an empty pattern. Some quick testing seems to confirm it. We could just consider an empty pattern valid for now, and later decide whether we should allow the user to remove all nodes from a pattern.

While doing it I realized that `AutomationEditor::paintEvent` is in need of a big refactor. There are about 3 `validPattern` conditionals in a row (and one `if (m_pattern)` which in the context is pretty much the same). It's a big method and I think it could be done after #5712 is merged. As for changing `validPattern` to consider empty patterns valid, it could be included on my PR or I could leave it for later (maybe for the paintEvent refactor), whatever you think is better!

**Comment by Veratil** [comment] 2020-10-25 03:03
I can help out with `paintEvent` if you want to take it on, or you can take a look at the PianoRoll refactor PR to see how I reorganized things (and used a lot of lambda functions). The better we refactor things and the faster it can repaint the better responsiveness we'll get. 😄

**Comment by IanCaio** [comment] 2020-10-25 11:42
Sure, I can try to tackle this one! I could start on it as soon as the other PR gets merged, unless most think it should be included in there.

As for the fix for this issue, should I include in the PR? (removing `m_pattern->hasAutomation()` from `AutomationEditor::validPattern()`)

**Comment by PhysSong** [comment] 2020-12-25 06:49
Then should we check if `m_objects` is empty instead? IIRC, the intention was to prevent editing automation patterns which are connected to nothing.

**Comment by IanCaio** [comment] 2020-12-29 13:45
> Then should we check if `m_objects` is empty instead? IIRC, the intention was to prevent editing automation patterns which are connected to nothing.

Even if we check for an empty objects list, I think it would be wise to rename this method. `validPattern()` is very misleading: We can have a valid pattern and not have it connected to anything. I suggest we rethink this issue after reorg, it's another one of those bugs that are more UX related than critical By then we will have more time to think of the best solution without hurry.

**Comment by PhysSong** [comment] 2021-06-05 02:30
@Veratil Should we revert #5124 for now?

**Comment by Veratil** [comment] 2021-06-05 02:53
> @Veratil Should we revert #5124 for now?

I'm fine with that. I wasn't sure if that fix was the proper way to do it anyway, and it seems like it's not when you go deep enough. :)

**Closed** 2021-06-06 02:27 UTC
Labels: bug
