### ISSUE TITLE
Enhancement. User control of 'My_Home' tab in sidebar

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1899] opened 2015-03-24 11:21 UTC
The idea comes from this question:
http://lmms.io/forum/viewtopic.php?f=7&t=1772
I looked im my installation, and there is really no relevance in any of the assigned folders in *My-Home*, and i realize that i never had used this shortcut.
How about a config for this option, where a user can list path for the *My-Home* targets?
If *My-Home* is important for OS MAC or LINUX, then those users could simply omit to change the config file -win win

**Comment by tresf** [comment] 2015-03-24 12:56
Possible duplicate of #1043.

**Comment by StakeoutPunch** [comment] 2015-03-24 15:34
Duplicate of #1130, which is in turn a possible duplicate of #1043 :>

**Comment by tresf** [comment] 2015-03-24 20:42
:meat_on_bone: :outbox_tray: :punch:

**Comment by musikBear** [comment] 2015-03-25 13:53
:speak_no_evil: njeaaj.. not *exactly* the same, but similar :p. -The difference is that the orr. op asks for a *config* for the options, and imo *that* would be the most potent and user-friendly approach to this

**Comment by StakeoutPunch** [comment] 2015-03-25 16:08
As in letting the user directly select which folders appear in the Home folder versus setting what folder the Home tab points to? I can see the difference.

**Comment by Sti2nd** [comment] 2015-03-25 23:06
Oh, yeah there are a difference, but it isn't useful. If you don't like the plugin/sample/whatever folder delete it and change the setting...

**Comment by tresf** [comment] 2015-03-26 00:23
Closing as duplicate of #1130,

**Closed by tresf** 2015-03-26 00:23 UTC
