### ISSUE TITLE
make Zynaddsubfx's window name the same as the track name

### ISSUE THREAD

**Issue by knobo** [LMMS/lmms#1955] opened 2015-04-13 21:58 UTC
All zynaddsubfx windows comes up with the same name. If I have two tracks with zyn, it is a bit dificult to keep track which one is which.

**Comment by tresf** [comment] 2015-04-14 03:14
Thanks @knobo.

For now, there is a feature in the preferences which reuses the same instrument window.

@curlymorphic, shall we roll this feature in with the 2.5 upgrade?  Seems like a very basic request. :)

**Comment by knobo** [comment] 2015-04-14 07:58
Which setting is that?

**Comment by curlymorphic** [comment] 2015-04-14 08:16
> @curlymorphic, shall we roll this feature in with the 2.5 upgrade?

I would prefer to get the 2.5 upgrade at least tested and working with it's current features. before adding any new features.

I am happy to look into these additional features, but would prefer to do them as separate issues.

**Comment by musikBear** [comment] 2015-04-14 10:35
@tresf i think you misunderstood knobo, and the issue is FAR from simple
I believe knobo is referring to the zasfx sub windows. If he has 2 or more **OPEN** zasfx instruments **GUIs-**, these sub-windows (forms) are identical, and it is not possible at all to see, where they belong. This is not a lmms issue, but a zasfx

@knobo The setting tresf refereed to is the *One instrument track window mode*
That will prevent you from looking at more than one lmms instrument at a time (a horrible feature btw), but it has nothing to do with zasfx's sub-windows

**Comment by knobo** [comment] 2015-04-14 10:42
I tested the "one instr mode", and it does not help much.

I think we could consider this two issues. One issue settingn zyn's main window and one setting sub-window names which is a zyn issue and not lmms.

**Comment by tresf** [comment] 2015-04-14 14:41
Sub-windows and sub-dialogs sound like an upstream feature request to the Zyn team then.  Probably a `Not our bug` categorization if that is the case as this is out of our control.

**Comment by tresf** [comment] 2015-04-24 14:38
Closing as not-our-bug (we don't write Zyn).  Please file an enhancement with the Zyn project to add the ability to make the preset name automatically appear in the title of the Zyn window.

**Closed by tresf** 2015-04-24 14:38 UTC
Labels: enhancement
