### ISSUE TITLE
ASIO support

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#2004] opened 2015-04-24 10:10 UTC
i'll add this issue, so it was here and maybe someone would do this sometimes.
i've tried LMMS under win7 with portaudio - works only 1 no midi working
i've digged a little about asio, but not sure what can be helpful
audacity and foobar both are using it, but audacity asks to download ASIO SDK
one of examples on codeproject is about 18kb source code, so maybe it's not so hard
Why? to solve a problem with windows and forget about it. or explain everyone how to use jack instead knowing that most of windows-users prefer to not bother with things they can do with other programs
asio have midi support, i don't know why WinMM is not working (my midi goes through sound card that is not selected as the sound source, because it's not working with portaudio)
another solution can be in adding jack as another midi source
http://www.steinberg.net/index.php?id=48&L=1
http://www.codeproject.com/Articles/24536/Low-Latency-Audio-using-ASIO-Drivers-in-NET
http://www.asio4all.com/
http://wiki.audacityteam.org/wiki/ASIO_Audio_Interface
http://sourceforge.net/projects/wineasio/
contacting steinberg about their licensing conditions

**Comment by tresf** [comment] 2015-04-24 12:50
Duplicate of #1173.

**Closed by tresf** 2015-04-24 12:50 UTC

**Comment by halfcyan** [comment] 2025-12-30 06:10
Steinberg recently released ASIO's source code under GPLv3 so it's possible to add to LMMS
https://www.steinberg.net/developers/asiosdk-open/
