### ISSUE TITLE
Invisible Song Segments

### ISSUE THREAD

**Issue by bradharms** [LMMS/lmms#2034] opened 2015-05-03 21:06 UTC
Sometimes my project files enter a state where none of the song segments can be truly deleted. I can move them, but deleting them actually just turns them invisible, and they still play when the play head moves over where they used to be. If I save and then reload the song, they reappear and I can move them around, but still can't truly delete them. The problem occurs for all segments, whether they are piano roll segments, beat/bassline, etc.

I used DataFileHost to provide an example file. *Link removed @tresf May 4th*
This was created using LMMS 1.1.3 on Windows 8.1.

**Comment by tresf** [comment] 2015-05-04 12:39
Please find an alternate hosting solution, that one you sent is full of garbage.

![image](https://cloud.githubusercontent.com/assets/6345473/7453615/0c72a5b0-f239-11e4-8013-395eeb5e15f2.png)

**Comment by musikBear** [comment] 2015-05-04 12:53
@bradharms That file you see this fail with, will that **always** have that behavior? I *have* seen the visual bug in songeditor, but only 'once' -Eg not reproduceable.
I doubt the file will show this odd behavior if you reload? or?
The glitch as i have seen it is entirely graphical, there is no lost project parts, and the 'invisible' blocks **re- appear** if you click on them -right?

**Comment by tresf** [comment] 2015-05-04 13:32
@musikBear I know what you are describing (blocks not appearing).  His problem is the opposite as it reads, his blocks are being explicitly deleted and they still play.

> deleting them actually just turns them invisible, and they still play when the play head moves over where they used to be

**Comment by StakeoutPunch** [comment] 2015-05-05 16:21
I have had this issue before, but I can't tell you how to reproduce. It always happened randomly to me.

**Comment by bradharms** [comment] 2015-06-01 04:34
Indeed, it's a random problem. Some days it happens and some days it doesn't, and I can't find a consistent way to reproduce it. However its not a graphical glitch because the UI behaves as if the space is empty, ie. I can click in the empty space to create a new segment, rectangle select picks up nothing for that region, etc.

@tresf, sorry for my choice of file share service. I was not aware it was presenting any EXEs; I only linked an lmms file.

**Comment by tresf** [comment] 2015-06-01 04:54
> @tresf, sorry for my choice of file share service. I was not aware it was presenting any EXEs; I only linked an lmms file.

No worries, the free storage solutions are notorious for this.  If you can host a project or provide steps which reproduce this problem, we'll be able to take a deeper look into it.

**Comment by musikBear** [comment] 2015-06-01 10:51
a derail .. ->  the LSP - how about a category for temporary files?
There really are no 'good' category for files that demonstrate issues or bugs.
I have used 'tuts |misc' for some, but they are misplaced imo..

**Comment by tresf** [comment] 2015-06-01 12:19
The LSP lacks quite a bit of basic features.  I agree we could use a bug tracking category.  It's just a matter of taking the time to update the database similar to https://github.com/LMMS/lmms.io/issues/54#issuecomment-63312025.  We've open sourced the entire codebase, so hypothetically anyone can do this, but you're right, it is a derail and not only off-topic, but also on the wrong repository. :+1:

**Comment by Umcaruje** [comment] 2015-07-05 21:43
@bradharms can you please upload your example file onto an bloatware-free filehost (dropbox, mega, google drive, lsp, etc.)?

**Comment by bradharms** [comment] 2015-07-06 14:50
Sorry, but I no longer have that file. But anyway I don't think it was related to that specific file, as I have had it happen with arbitrary files, and once it starts happening it happens for all files. Then it stops happening just as randomly.

**Comment by Umcaruje** [comment] 2015-07-06 15:05
@bradharms We need a reliable way of reproducing this issue, so we can fix it. If you can't provide steps to reproduce this issue, or some screen recording of it, I'm afraid I'll have to close it.

**Comment by tresf** [comment] 2015-08-27 05:17
Closing as the OP hasn't offer the file which reproduced the problem in any reasonable amount of time.

**Closed by tresf** 2015-08-27 05:17 UTC
Labels: needs clarification

**Comment by Hectate** [comment] 2016-07-31 19:42
Just as a note; I encountered this same issue (Windows 8.1, LMMS 1.1.3). Deleting the segments and reopening the project caused them to re-appear. However, when I shut down LMMS entirely and re-opened it, I was able to then "permanently" delete the segments and saving/reopening maintained that modified state of the project finally (as well as playing the project).
I noted also that using the "Clear Track" option seemed to make those changes permanent at the cost of losing everything else. I was able to easily re-set Beat/Bassline editor segments since it's just a click, but when the bug happened to a Piano Roll track this option was too destructive.
This all makes me wonder if there's some kind of time/usage-based element to this bug. Too many changes in memory for the undo, or a memory leak that causes changes to not be entirely made even though the UI reflects them.

**Comment by Nesdood007** [comment] 2018-04-09 05:34
Sorry to bump an old thread, but I'm having this issue too in one of my most recent projects. There are a few Automation Tracks and Song Segments that I cannot delete. Anytime I try to delete it, it seems to disappear, but the effects or notes from the segment continue to play as if they were there, and is also saved to the file and reappears when reloading the project. Here is a link to my project: [https://drive.google.com/file/d/1tcXaotrBoFRuXN4YjyfROeafdzK0FOHE/view?usp=sharing](https://drive.google.com/file/d/1tcXaotrBoFRuXN4YjyfROeafdzK0FOHE/view?usp=sharing)

I wonder if it has something to do with the number of segments in my project?
