### ISSUE TITLE
Better Midi Pitch Bend Support

### ISSUE THREAD

**Issue by 0x0015** [LMMS/lmms#5753] opened 2020-10-30 01:55 UTC
LMMS for the most part has good midi support, and decent pitch bend in the piano roll(using automation editor), but only with the build in instruments (triple oscillator, etc...).  It seem that using a midi piano with a pitch bend knob, I can add pitch bend to any instrument, separately from the piano roll, but this is not stored in any way when recording.  

I really like the sound of pitch bend, but being limited to the stock instruments is a big drawback, especially when I can hear the pitch bend through any instrument through my midi keyboards pitch bend knob.

If these two features could combine and allow recording of pitch bend through midi, which then gets stored in the piano roll automation editor(much like recording a automation track from midi), which then is converted back to midi pitch bend for the instrument, that I think would be the best possible solution; allowing for ease of use with automation allowing you to edit it manually, while also keeping the midi aspect for recording and vst/lv2 instruments.

**Comment by Spekular** [comment] 2020-10-30 05:41
Closing as a duplicate of https://github.com/LMMS/lmms/issues/3724, which has been consolidated into https://github.com/LMMS/lmms/issues/1472.

**Closed by Spekular** 2020-10-30 05:42 UTC
Labels: enhancement
