### ISSUE TITLE
VST compilation fail on Ubuntu 17.04

### ISSUE THREAD

**Issue by n-pigeon** [LMMS/lmms#3564] opened 2017-05-19 16:05 UTC
```File does not exist: /usr/lib/i386-linux-gnu/wine/libwinecrt0.a```

Full log:
https://hastebin.com/pubopoteke.erl

tresf suggested that this workaround could fix this for 17.04:
https://github.com/LMMS/lmms/pull/3130/files

**Comment by tresf** [comment] 2017-05-26 05:55
@n-pigeon thanks for the bug report.  `libwinecrt0.a` missing seems to be a common problem amongst build environments.  Can you please `updatedb` and post the output of `locate libwinecrt0.a` so that we can see where it's located and why it's failing?

**Comment by GuessWhatBBQ** [comment] 2017-05-28 11:34
Workaround not affective.Compiled with `make -Bi` to get operational app.
Output of `sudo updatedb` then `locate libwinecrt0.a`:
 `foo@foo:/media/foo$ sudo updatedb`
`foo@foo:/media/foo$ locate libwinecrt0.a`
`/usr/lib/i386-linux-gnu/wine/libwinecrt0.a`
`/usr/lib/x86_64-linux-gnu/wine/libwinecrt0.a`

**Comment by n-pigeon** [comment] 2017-05-28 17:22
Oh sorry forgot about this.
Here is location: `/usr/lib/x86_64-linux-gnu/wine/libwinecrt0.a`

Sorry for late reply :<

**Comment by karmux** [comment] 2017-05-28 18:52
@n-pigeon is `libwine-dev:i386` installed?

**Comment by n-pigeon** [comment] 2017-05-28 19:13
@karmux yes

**Comment by tresf** [comment] 2017-05-28 20:44
@n-pigeon reproduced on 17.04.  `libwine-dev:i386` installs `/usr/lib/i386-linux-gnu/wine/libwinecrt0.a` properly, but cmake still finds the 64-bit version... 

This appears to be caused by `wine64-tools`, somewhat explained here #3142 (thanks @karmux!)

Note, `wine32-tools:i386` will remove `wine64-tools` and compilation will succeed.  I've added this information to our wiki here: https://github.com/LMMS/lmms/wiki/Dependencies-Ubuntu#winegcc-g-failed

https://github.com/LMMS/lmms/wiki/Dependencies-Ubuntu#winegcc-g-failed

**Comment by tresf** [comment] 2017-05-30 18:21
Closing as duplicate of #3564.  We'll work towards a more permanent solution over there.

**Closed by tresf** 2017-05-30 18:21 UTC
