### ISSUE TITLE
Beta version

### ISSUE THREAD

**Issue by DjGGAV** [LMMS/lmms#2722] opened 2016-04-09 18:02 UTC
When i open the LMMS program the Setup LMMS shows up, and when i wanna check for other languages, it doesn't show up. It's the Beta version Windows 64 download.
![uten navn](https://cloud.githubusercontent.com/assets/18368735/14405374/074bc7bc-fe8e-11e5-850c-23eb6dee47a0.png)

**Comment by tresf** [comment] 2016-04-09 18:04
Thanks for reporting this bug!

This is a duplicate of #2577, so it will be fixed in the next beta release.

**Closed by tresf** 2016-04-09 18:04 UTC
Labels: duplicate
