### ISSUE TITLE
Zero-length-notes from B&B does not appear as notes in Piano-roll 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5338] opened 2019-12-07 23:11 UTC
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by Spekular** [comment] 2019-12-07 23:53
Closing as duplicate of #5339

**Closed by Spekular** 2019-12-07 23:53 UTC
Labels: bug
