### ISSUE TITLE
Vertical Play Line In B+B Editor and Piano Roll

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3187] opened 2016-12-28 16:34 UTC
Hello Everyone,

Couldn't think of/find the terminology for it, but the Song Editor contains a vertical white line and white arrow pointing down that indicates the position of what is being played when you hit the play button.
The piano roll contains just the arrow and not the vertical white line.
The B+B Editor does not have either.
Not sure if this would be desired by others but it might be nice to have a vertical line added to the one in the piano roll and also have the down arrow/vertical line shown in the B+B Editor to give an indication of what is being played in it.
I assume this was not added in the piano roll due to the grid but sometimes it could be desired, even if it was a different color like maybe a bright green or something,
Not a huge deal, definitely would be something that would need an on/off if it was added because it may not be desired by everyone.
Probably not a desired feature by many, but I would be interested to hear some opinions.

**Comment by tresf** [comment] 2016-12-28 17:53
@miketurn Thanks for the writeup.  I believe this to be a duplicate of #3052.  Please let us know if this categorization is incorrect.

**Comment by miketurn** [comment] 2016-12-29 23:15
@tresf 
Dammit! Terminology has yet again caused me to create another double post.
I searched and searched and didn't find this one #3052, thank you tresf for calling this post to my attention. In answer to your question, yes that post does bring up what I am requesting.  I see that you added the "B+B Editor" to the title of #3052, I will copy some things from this post not mentioned there yet so it can all be in one place, and I will also close this post to keep things tidy.

Also, I see how much work you put into answering questions and cleaning up this site, I just wanted to say thank you for all your help.

**Closed** 2016-12-29 23:15 UTC
