### ISSUE TITLE
Automation Editor: Strange lines with the playback head.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4986] opened 2019-05-20 22:12 UTC
This is mentioned in #4978. While I was wondering why the playback manager of the automation editor does not move when you play. I discovered this error.

![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/26127693/58055049-8b742b80-7b2a-11e9-9555-3bbf00861d1c.gif)

I do not know how to explain this well, but when you have an automation editor window or piano roll over the song editor, when you play, the playback cursor jumps over these editors and takes the editor header, the editor header the song draws a strange line and the mouse icon is redrawn.

**Comment by zonkmachine** [comment] 2019-05-21 04:55
Duplicate of https://github.com/LMMS/lmms/issues/2714

**Closed by zonkmachine** 2019-05-21 04:55 UTC
Labels: duplicate
