### ISSUE TITLE
Improve SoundFont Support with Musescore Code

### ISSUE THREAD

**Issue by Anonymouqs** [LMMS/lmms#4178] opened 2018-02-19 12:21 UTC
Most of you are familiar with Musescore, another open-source music program. LMMS has been having difficulty with SoundFont support, while Musescore is able to use a wide variety of SoundFonts on every Platform. They even have support for SoundFont 2. Using their code, we should be able to give LMMS the same level of SoundFont support as they have. 

I understand that you can use Polyphonic to convert SoundFonts, but it would be easier and more user-friendly to simply allow users to use SoundFont 3.0 for example, right out of the box, instead of having to research SoundFont encoding ect. 

https://github.com/musescore/MuseScore

I would love to help code this if this feature gains approval, but alas, I am rather occupied with school and unfortunately has little C++ experience :(
(I'm more familiar with Python and GDscript)

**Comment by Mark-Agent003** [comment] 2018-02-19 14:24
As of #3895, SoundFont 3.0 files will be supported in LMMS.  This seems to be a duplicate of #3286.

**Closed** 2018-02-23 15:22 UTC
