### ISSUE TITLE
Note probability

### ISSUE THREAD

**Issue by alandmoore** [LMMS/lmms#1371] opened 2014-11-30 05:14 UTC
A feature I miss from other software is being able to set note probability; that is, the probability that an individual note will play.  This is quite useful in repeating patterns (drums, e.g.) to provide some variation.

I would envision this as being controlled similar to how note volume and panning are controlled, and of course default probability would be 100%.

**Comment by tresf** [comment] 2015-11-02 14:09
> My unfinished arpeggiator mod does this and I like it a lot.

Then we'll track it there if this ever comes to fruition.  Closing out as duplicate of PR #687, which has a final status of:

> **zonkmachine commented on Nov 9, 2014**
> I'm not totally vanished, I hope to get back to this eventually... Sorry! :-)

**Closed by tresf** 2015-11-02 14:09 UTC
Labels: duplicate, enhancement, ux
