### ISSUE TITLE
'fftw3.h' file not found

### ISSUE THREAD

**Issue by emlai** [LMMS/lmms#2726] opened 2016-04-10 15:59 UTC
I have `fftw3.h` in `/usr/local/include` but still get the following error when compiling:

```
[ 40%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/fft_helpers.cpp.o
In file included from /Users/emlai/Documents/Code/lmms/src/core/fft_helpers.cpp:26:
/Users/emlai/Documents/Code/lmms/include/fft_helpers.h:31:10: fatal error: 
      'fftw3.h' file not found
#include <fftw3.h>
         ^
```

Although during `cmake ..` it looks like it was found:

```
-- Checking for module 'fftw3f>=3.0.0'
--   Found fftw3f, version 3.3.4
```

**Comment by tresf** [comment] 2016-04-11 02:11
@emlai some more information about your build environment would be helpful.

For starters, I recognize the Mac-only `/Users/foo` folder syntax, suggesting you're building on a Mac.

We support Homebrew and MacPorts build environments per our dedicated Apple build tutorial [`Compiling-lmms-(Apple)`](https://github.com/LMMS/lmms/wiki/Compiling-lmms-(Apple)).

When I last tried on MacPorts, I believe I needed to use a package called `fftw-3-single` to get the build to fire properly.  Also, if you've added this dependency after your build has started, I'd recommend that you do a clean build just to rule out any cmake caching issues.

In regards to Homebrew (which I would guess you are using as observed by the `/usr/local/include` path you've mentioned, our [`.travis/osx..install.sh`](https://github.com/LMMS/lmms/blob/master/.travis/osx..install.sh) is still passing, so perhaps there is a discrepancy in the `fftw` we use and the `fftw` you've installed.

**Comment by emlai** [comment] 2016-04-11 19:49
Yes. I'm building on a Mac with the default AppleClang setup + dependencies via Homebrew. I installed `fftw` with `brew install fftw`.

Now, I deleted the `build` directory, and did a fresh build with `.travis/osx..install.sh`, but still get the exact same error.

**Comment by tresf** [comment] 2016-04-12 00:39
Then for some reason `cmake` is having problems finding it, I'd think... `include_directories` could help... you could try shimming it the root `CMakeLists.txt` to test (or add as a cmake command line param).

What version of OSX are you running?  AFAIK our automated build env is Yosemite and I test our builds on El Capitan.

You may also chose to reinstall some components for good measure.  If `cmake` can't find `fftw3`, there's a good chance it won't be able to see other items in `/usr/local/include` as well.

**Comment by emlai** [comment] 2016-04-12 10:02
I'm running El Capitan (10.11.4).

It builds without errors if I add `-DCMAKE_CXX_FLAGS='-isystem /usr/local/include'` to the `cmake` invocation, so I believe there's a missing `include_directories` for `fftw` in some `CMakeLists.txt` file, and your automated build probably searches in `<prefix>/include` by default. Just a guess though.

But until it is fixed, I'm fine with this. Thanks!

**Comment by tresf** [comment] 2016-04-12 14:02
@emlai No one else has reported this and we can't reproduce on our environments which leads me to believe your homebrew `cmake` is unaware of your homebrew `include` dir.

I do not believe this to be true:

> I believe there's a missing `include_directories` for `fftw` in some `CMakeLists.txt`

Reason being, `/usr/local/includes` has much more than just `fftw` headers.

I'm closing this as invalid for now.  Please feel free to reopen if someone else is able to reproduce.

**Comment by liushuyu** [comment] 2016-04-12 14:02
>It builds without errors if I add -DCMAKE_CXX_FLAGS='-isystem /usr/local/include' to the cmake invocation, so I believe there's a missing include_directories for fftw in some CMakeLists.txt file, and your automated build probably searches in <prefix>/include by default. Just a guess though.



Travis CI set up many environmental variables prior to the actual building process. So your guess is likely to be correct.

**Closed** 2016-04-12 14:02 UTC
Labels: invalid

**Comment by prios-george-huestis** [comment] 2023-09-27 18:25
This is happening for me as well - I haven't tried any solutions yet, I'm just posting to knock over the "No one else has reported this"

**Comment by tresf** [comment] 2023-09-27 18:35
> [DELETED] This is happening for me as well - I haven't tried any solutions yet, I'm just posting to knock over the "No one else has reported this"

I assume this comment was deleted because the issue was resolved .  Do you mind sharing the solution so that others can benefit from it?

**Comment by tresf** [comment] 2024-01-24 16:36
@jmturner thanks for this pointer.  Do you believe that this issue is caused by using a `cmake` that is not part of the same ARM64 homebrew installation, quoting:

>  If cmake can't find `fftw3`, there's a good chance it won't be able to see other items in ~~`/usr/local/include`~~  `/opt/homebrew/include` as well.

Note, I was part of the beta Apple Silicon program and have been actively using Homebrew on ARM64 since the beta releases and haven't seen this issue firsthand, hence asking.  Lastly, did you find this issue via Google and wanted to offer some assistance or are you actually compiling LMMS?  Either is fine, just curious, we have very (very) few Apple devs. :)

**Comment by jmturner** [comment] 2024-01-24 16:50
I'm an LMMS user but never compiled it. I happened to find this page when I was troubleshooting why fftw3 failed to compile for another app (nrsc5) on my M1 Mac. The cmake I am using was installed by homebrew. I thought it might be helpful here but feel free to disregard. :)

**Comment by tresf** [comment] 2024-01-24 16:59
Interesting... nrsc5 says [it'll just build fftw from source if it's not found](https://github.com/theori-io/nrsc5/blob/8daad374a5f757ff1e66c4cacaa17992083b1d20/CMakeLists.txt#L49C1-L56C9).   This is a neat trick.  Anyway, if cmake can't find headers in that directory there's a chance the library was installed after the cmake cache was built.  Assuming that you already thought of that, this information will be useful until build systems can be patched to address this.   
 Currently LMMS is only built for Intel, so you may experience this again if you wanted a native M1 build.  Regardless, I've made a mental note of this incase it resurfaces. 🍻
