### ISSUE TITLE
Unable to resize inbuilt/stock instrument plugins like TripleOscillator, Nescaline, Vibed...

### ISSUE THREAD

**Issue by aziagiles** [LMMS/lmms#6636] opened 2023-02-08 16:57 UTC
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by musikBear** [comment] 2023-02-08 20:21
That is not a bug. that is default architecture. Those components cant be sized.
You can use default tools in your OS to make everything larger. In Windows you hold down Win-key and tap on +
Reverting is hold down Win-key and tap on Esc

**Comment by aziagiles** [comment] 2023-02-08 20:39
Ok. I see. Thanks for the response.

**Comment by michaelgregorius** [comment] 2023-06-04 20:17
Hi @aziagiles!

Thanks for your report! It would indeed be nice and more user friendly if the plugin windows could be resized. However, making them resizable would involve a major overhaul/reimplementation of LMMS' GUI. There are already several other open issues and discussions related to a redesign (see #6712 and #1911). These issues should cover your request. Therefore I will close this specific issue.

**Closed** 2023-06-04 20:19 UTC
Labels: bug
