### ISSUE TITLE
Auto Preview 

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1833] opened 2015-03-07 02:47 UTC
Add Auto Preview button to all of the audio file search boxes in LMMS.

**Comment by musikBear** [comment] 2015-03-07 09:41
whitch??
Please again be precise, and could you take these **first to forum-wish-list**, because the tracker needs cleaner /precise descriptions
In windows (???) all samples *has* pre-view. Hold your mouse over the file-name, and press and hold left-mouse

**Comment by mikobuntu** [comment] 2015-03-07 11:16
If I understand @Reaper10 correctly he means whenever you open the folder search icon on the Audio_File_Processor you should be able to preview your samples there without actually having to load them into the plugin 1st. I would agree that this would be a very useful; feature.

![afp-preview-samples](https://cloud.githubusercontent.com/assets/335217/6541192/6ff45db4-c4bb-11e4-86a5-156f368b9802.png)

**Comment by mikobuntu** [comment] 2015-03-07 11:45
@tresf  The title of this feature request should be changed to something more meaningful e.g " AudioFileProcessor's file browser audio preview ? " or something to that effect and labelled as a feature request.

**Comment by tresf** [comment] 2015-03-07 12:54
I think we are getting a bit overzealous in terms of what a common fine dialog can do.  :)

**Comment by mikobuntu** [comment] 2015-03-07 13:47
@tresf Possibly, although Ardour has the ability to preview audio from a file browser before inserting to a track and I see this as a workflow enhancement personally .  ( see video link ).

https://www.youtube.com/watch?v=1fWXaQEhj4U&feature=youtu.be

**Comment by tresf** [comment] 2015-03-07 14:01
Yes, but with that argument, Ardour's browse dialog will spawn 20 new enhancement requests. :)  Look at all of those features.

![screen shot 2015-03-07 at 8 51 57 am](https://cloud.githubusercontent.com/assets/6345473/6541558/3eee0bfc-c4a7-11e4-825d-74e5e44099b0.png)

On a side note... as a project team, we have to be careful to focus on what is important to the project's longevity.  @Reaper10 has opened [37 requests](https://github.com/LMMS/lmms/issues?q=is%3Aissue+author%3AReaper10) since July, none of which has actually helped the team implement.

Babysitting these poor bug titles, poor bug descriptions and continuously helping him to get HIS point across is taking up time that could be spent fixing stuff that is broken.

If you want the bug title and description fixed, he has to do it for now on.

**Comment by tresf** [comment] 2015-03-07 14:15
Duplicate of #1834

**Closed by tresf** 2015-03-07 14:15 UTC

**Comment by mikobuntu** [comment] 2015-03-07 14:18
@tresf Yeah true comparing to Ardours existing features may be a bit of wishful thinking on my part :) 
I agree that the project team needs to focus on what is most important for LMMS to move along .
Ok cool I have noticed that too, no disrespect to @Reaper10 but probably inundating the issue track with poorly explained feature request will fall on deaf ears, and as @tres said tkae up time that could be spent fixing things" :)

**Comment by Reaper10** [comment] 2015-03-07 19:19
sorry I'm not much I don't how to code.

**Comment by tresf** [comment] 2015-03-07 19:22
@Reaper10, what about helping with CC0 samples?  We have plenty of areas where non-coders can help.
